snapcraft/internal/errors.py
snapcraft/internal/lxd/_containerbuild.py
tests/unit/test_errors.py
tests/unit/test_lxd.py

-----
This PR implements support for merging the contents of `SNAPCRAFT_IMAGE_INFO` set when building in a container with the information gathered from LXD in the container. The result of it will go into `manifest.yaml` if `SNAPCRAFT_BUILD_INFO` is set (as usual). The exact values aren't filtered but taken as-is - InvalidLaunchpadBuildInfoError is raised if the parsing fails.
This variable is going to be set by [buildd](https://launchpad.net/launchpad-buildd).
Note on compatibility: Older Snapcraft versions already pick up `SNAPCRAFT_IMAGE_INFO`, the main take away here is that builds in containers will merge the provided JSON with what's taken from the container.
The following new tests are being added:
- tests.unit.test_lifecycle.RecordManifestTestCase.test_prime_with_launchpad_build_inf …

lxd: merge existing image info contents

---

snapcraft/cli/store.py
snapcraft/config.py
snapcraft/storeapi/errors.py
tests/unit/commands/test_export_login.py
tests/unit/test_config.py

-----
And instead of simply printing the ini file, base64-encode it so it can be more easily handled. This is intended to fit the use-case of sticking the exported login straight into the environment of a CI system instead of needing to encrypt a file.

cli: support exporting login to stdout

---

schema/snapcraft.yaml
snapcraft/cli/snapcraftctl/_runner.py
snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/pluginhandler/_runner.py
tests/integration/general/test_scriptlets.py
tests/integration/snaps/scriptlet-override-prime/part1/file
tests/integration/snaps/scriptlet-override-prime/part2/file2
tests/integration/snaps/scriptlet-override-prime/snap/snapcraft.yaml
tests/unit/pluginhandler/test_runner.py
tests/unit/project_loader/test_config.py

-----
Currently Snapcraft supports override scriptlets for the pull, build, and stage steps. This PR resolves #1674 by adding one for the prime step called `override-prime` which, if specified, overrides the part's prime step. It also adds a `prime` subcommand to `snapcraftctl` to ensure developers can still complete the default prime action.

many: add override-prime scriptlet

---

MANIFEST.in

Ensure relevant standalone files are part of the python package
when running `python setup.py sdist` for future installations
based out of the created package.
-----

package: ensure all relevant files are in for sdist

---

snapcraft/plugins/python.py
tests/unit/plugins/test_python.py

The Python packages in bionic changed slightly, so that
distutils/sysconfig.py (which pip needs) is now in a separate package.
This fixes https://bugs.launchpad.net/snapcraft/+bug/1762456

python plugin: install python-distutils when run on bionic

---

patches/ctypes_init.diff
snap/snapcraft.yaml
snaps_tests/__init__.py
tests/integration/__init__.py

Now that 2.40 has been released, we can get rid of compiling our own
python and any other component needed to run correctly in a classic
confined snap.
-----

packaging: simplify snapcraft.yaml

---

schema/snapcraft.yaml
snapcraft/internal/lifecycle/_runner.py
snapcraft/internal/meta/_errors.py
snapcraft/internal/meta/_snap_packaging.py
snapcraft/internal/project_loader/_config.py
tests/unit/test_errors.py
tests/unit/test_meta.py

-----
This PR introduces a new **pass-through** keyword to `snapcraft.yaml` which comes in two forms, a global and an app-local property [as proposed in the forum](https://forum.snapcraft.io/t/support-for-passthrough-into-snap-yaml/4698). As proposed, the key is just defined as a dictionary (object in the schema) and not validated, but instead applied in `snap_packaging.py` where its use will be logged and ambiguous keys will raise an error. The original snapcraft.yaml is used to validate what values have been specified as opposed to default values filled in by Snapcraft.
Note that, as discussed offline, properties like `name` or `command` are not special-cased and not supported by pass-through due to their being strings processed by Snapcraft.
The following tests are added/ modified:
- …

meta: implement pass-through of properties to snap.yaml

---

schema/snapcraft.yaml
snapcraft/cli/snapcraftctl/_runner.py
snapcraft/extractors/_metadata.py
snapcraft/internal/errors.py
snapcraft/internal/meta/_snap_packaging.py
snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/pluginhandler/_runner.py
snapcraft/internal/project_loader/_config.py
snapcraft/internal/states/_build_state.py
snapcraft/internal/states/_prime_state.py
snapcraft/internal/states/_pull_state.py
snapcraft/internal/states/_stage_state.py
snapcraft/project/_project_info.py
tests/integration/__init__.py
tests/integration/general/test_snapcraftctl_set_version.py
tests/unit/commands/snapcraftctl/test_build.py
tests/unit/extractors/test_metadata.py
tests/unit/pluginhandler/test_pluginhandler.py
tests/unit/pluginhandler/test_runner.py
tests/unit/pluginhandler/test_scriptlets.py
tests/unit/project_loader/test_config.py
tests/unit/test_meta.py

-----
This PR resolves #1676 by adding the ability to set the snap version from a scriptlet using `snapcraftctl set-version <version>`. It also lays down generic infrastructure to make adding future such "setters" easy.

many: add snapcraftctl set-version

---

snapcraft/cli/_errors.py
tests/unit/cli/test_errors.py

Gate the use of sentry error data with a feature flag
-----

errors: feature flag error reports

---

snapcraft/storeapi/errors.py
tests/fake_servers/api.py
tests/integration/store/test_store_release.py
tests/unit/store/test_store_client.py

-----
This PR fixes LP: [#1750177](https://bugs.launchpad.net/snapstore/+bug/1750177) and #2028 by properly handling the store returning a 500 error formatted as HTML instead of a typical error response. It also starts printing store error responses when in debug mode in order to streamline such fixes in the future.

storeapi: handle 500 error response when releasing snap

---

snapcraft/internal/states/_build_state.py
snapcraft/internal/states/_prime_state.py
snapcraft/internal/states/_pull_state.py
snapcraft/internal/states/_stage_state.py
tests/integration/snaps/old-part-src/parts/part-name/state/pull
tests/unit/pluginhandler/test_pluginhandler.py
tests/unit/states/test_build.py
tests/unit/states/test_prime.py
tests/unit/states/test_pull.py
tests/unit/states/test_stage.py

-----
Otherwise they can change without their corresponding steps being considered dirty.

states: track override scriptlets

---

snapcraft/extractors/_errors.py
snapcraft/extractors/_metadata.py
snapcraft/extractors/setuppy.py
tests/fixture_setup.py
tests/integration/general/test_metadata_setuppy.py
tests/unit/extractors/test_setuppy.py

Add support for loading setup.py and retrieving version and
description information from it.
-----

extractors: support for setup.py

---

snapcraft/storeapi/errors.py
tests/fake_servers/api.py
tests/unit/store/test_store_client.py

`SnapcraftError.fmt` is run through `str.format` by
`SnapcraftError.__str__`, so it shouldn't itself be the output of a
`str.format` operation.  If it is, and the output contains `{}` (as for
example if it contains raw JSON output), then `__str__` will raise an
exception.
LP: [#1761488](https://bugs.launchpad.net/bugs/1761488)

Fix formatting of some store errors

---

snapcraft/plugins/python.py
tests/unit/plugins/test_python.py

If there are no wheels to install then do not even attempt to install.
This behavior is recently changing due to pip 10 being released.
-----

python plugin: do not invoke wheel install if empty

---

schema/snapcraft.yaml
snapcraft/internal/project_loader/_config.py
snapcraft/internal/project_loader/errors.py
tests/integration/__init__.py
tests/integration/general/test_architectures.py
tests/unit/commands/test_snap.py
tests/unit/project_loader/test_config.py
tests/unit/test_meta.py

-----
This PR resolves #1685 by changing the `architectures` keyword according to the new CI-friendly proposal [here](https://forum.snapcraft.io/t/4675). This adds support for new syntax to that keyword:
architectures:
- build-on: [<build arch 1>, <build arch 2>]
run-on: [<run arch 1>, <run arch 2>]
Please see the proposal for more details.

project_loader: support architectures for CI

---

snapcraft/internal/elf.py
snapcraft/internal/pluginhandler/_patchelf.py
tests/unit/test_elf.py

Bring back the behavior of 2.39, this is a half revert of
commit 64f78f762a05122fafe0a4d5defced2965603fb7
-----

elf: patch everything instead of a subset of elf files

---

snapcraft/internal/elf.py
tests/integration/general/test_elf.py

Given https://github.com/NixOS/patchelf/issues/94 we may find ourselves
in a situation where given an elf file with an existing RUNPATH, a
proper RPATH may not be set.
Resolve #2071
-----

elf: clear the current runpath before setting the rpath

---

.travis.yml
snapcraft/plugins/python.py
tests/unit/plugins/test_python.py

distutils has been split out into its own package for python3 but
not for python2.
-----

python plugin: properly handle distutils on bionic

---

snapcraft/plugins/_python/_pip.py
snapcraft/plugins/_python/errors.py
tests/integration/plugins_python/test_python_plugin.py
tests/unit/plugins/python/test_errors.py
tests/unit/plugins/python/test_pip.py

-----
This PR brings back support for older versions of pip, most notably 8.1.1 which is in Xenial, that don't support `pip list --format=json`. Ease of parsing is why we dropped that support previously. And we support pulling in pip from stage-packages so that should include Xenial and not require resorting to PyPI, which is what Snapcraft does with pip, setuptools and wheel when they're not available.
Note that no effort is made to hide the error message as per what we do in other places.
The following new test is being added:
- tests.unit.plugins.python.test_pip.PipListTestCase.test_no_json_format
- To verify that we fallback to the legacy format if pip returns an error and list the packages from that successfully.
I locally ran the tests:
- `./runtests.sh tests/unit` with unrelated …

python: bring back support for older versions of pip

---

snapcraft/plugins/dotnet.py
tests/unit/plugins/test_dotnet.py

Add dotnet command to path and enable developer scenario for  snap ild via application yaml
-----

dotnet plugin: add dotnet command to path and enable developer scenario for  snap

---

snapcraft/internal/lifecycle/_packer.py
tests/unit/commands/test_snap.py

When base snaps become bootable we will need to ensure that they
do not squash all uids on the snap into "root". This fixes core18 builds that
change some files like etc/shadow from root:shadow to root:root.

internal: skip -all-root for base snaps

---

snapcraft/cli/_command_group.py
snapcraft/cli/containers.py
snapcraft/cli/env.py
snapcraft/cli/lifecycle.py
snapcraft/cli/parts.py
snapcraft/internal/lifecycle/_containers.py
snapcraft/internal/lxd/_project.py
tests/integration/lifecycle/test_clean_pull_step.py
tests/unit/commands/test_clean.py
tests/unit/commands/test_refresh.py
tests/unit/commands/test_snap.py
tests/unit/commands/test_update.py
tests/unit/test_lxd.py

Remove the support as it has not proved to be the best experience, cleanbuild should be used
instead.
Also future feature proof the environment detection.
-----

many: remove support for remote lxd per project containers

---

snapcraft/internal/meta/_snap_packaging.py
tests/unit/test_meta.py

-----
Currently Snapcraft warns that a snap using passthrough cannot be released to the store. What it means is that it may be flagged for manual review upon push, but even that isn't necessarily the case, as the store may gain support for the option being passed through. Also, some users are interpreting this warning as a fatal error, i.e. that Snapcraft won't allow release.
Stop mentioning the store in the passthrough warning.

meta: soften warning about using passthrough

---

MANIFEST.in

packaging: include changelog for setup.py's version detection

---

tests/integration/__init__.py
tests/integration/general/test_asset_recording.py
tests/integration/platform.py
tests/integration/repo.py

-----
This PR removes uses of `os_release` and `repo` from the `snapcraft` module from the integration tests. Necessary functionality is instead added to the integration-specific `platform` and `repo` modules.
Fixes: #1982 
No tests were added or removed.
I locally ran the tests:
- `./runtests.sh tests/unit` with unrelated failures in [tests.unit.test_lifecycle.CoreSetupTestCase.test_core_setup_if_docker_env](https://bugs.launchpad.net/snapcraft/+bug/1752576), `tests.unit.test_mangling.TestClearExecstack.test_execstack_clears` and `tests.unit.test_elf`.
- `./runtests.sh tests/integration` with one unrelated failure in [tests.integration.general.test_parser.TestParserWikis](https://bugs.launchpad.net/snapcraft/+bug/1752580)
- `./runtests.sh static`: Everything passed

tests: don't use os_release and repo from snapcraft

---

tests/fixture_setup.py
tests/integration/__init__.py
tests/integration/plugins_catkin/test_catkin.py
tests/integration/snapd/test_catkin_snap.py
tests/integration/snapd/test_catkin_tools_snap.py

Our integration tests are might slow and we make things worse by removing
any caching we have which consequentally removes an integration point
from our tests.
If a test needs to test the caching specifically, it can set the
required variables to do so.
-----

tests: use a common cache for the integration tests

---

snapcraft/internal/lxd/_containerbuild.py
tests/unit/test_lxd.py

-----
This PR adds a `snap watch` call before injecting (core and snapcraft) snaps into the LXD container to force any on-going refreshes to be done.
Fixes: #2037 
Fixes: [LP: #1722049](https://bugs.launchpad.net/snapcraft/+bug/1722049)
The following tests were updated:
- tests.unit.test_lxd.test_inject_snap
- To verify that the `snap watch` call is made first.
I locally ran the tests:
- `./runtests.sh tests/unit` with unrelated failures in [tests.unit.test_lifecycle.CoreSetupTestCase.test_core_setup_if_docker_env](https://bugs.launchpad.net/snapcraft/+bug/1752576), `tests.unit.test_mangling.TestClearExecstack.test_execstack_clears` and `tests.unit.test_elf`.
- `./runtests.sh tests/integration` with one unrelated failure in [tests.integration.general.test_parser.TestParserWikis](https://bu …

lxd: wait for on-going refreshes to finish

---

snap/snapcraft.yaml

Use override-pull and override-build instead of their respective prepare, build
and install counterparts.
Also, switch to using `snapcraftctl set-version` instead of
`version: git` leveraging the version value to also
`snapcraftctl set-grade`.
-----
Fixes [LP: #1758958](https://bugs.launchpad.net/snapcraft/+bug/1758958)

package: make use of snapcraftctl snapcraft features

---

snapcraft/storeapi/_client.py
snapcraft/storeapi/errors.py
tests/unit/store/test_client.py
tests/unit/store/test_store_client.py
tests/unit/test_errors.py

-----
Currently Snapcraft prints an ugly warning every time it retries a connection instead of just retrying until the max number has occurred. And then, if after all the retries have happened and no connection has been made, it dumps a traceback.
This PR fixes LP: [#1765671](https://bugs.launchpad.net/snapcraft/+bug/1765671) by fixing both of othese issues: up the log level of urllib to ERROR, and properly handle connection errors resulting from exceeding the maximum number of retries.
In the long run, we should consider doing retries differently-- this stuff leaks right through requests.

storeapi: better handle network errors and retries

---

snapcraft/internal/repo/_deb.py
snapcraft/internal/repo/errors.py
tests/unit/repo/test_deb.py
tests/unit/test_errors.py

-----
This PR handles errors when updating the package cache, such as a hash mismatch or unresolved hostnames. The apt API doesn't distinguish these, so unfortunately we can't be very specific here but need to rely on the output we get before the error is raised.
If the error is a hashsum mismatch, the index will be cleared and Snapcraft will continue.
Fixes: #2029 #2030 
Fixes: [LP: #1747715](https://bugs.launchpad.net/snapcraft/+bug/1747715)
The following tests are added/ modified:
- tests.unit.test_errors
- To verify CacheUpdateFailedError
- tests.unit.repo.test_deb.UbuntuTestCase.test_cache_update_failed
- To verify that an `apt.cache.FetchFailedException` is handled as a proper error.
- tests.unit.repo.test_deb.UbuntuTestCase.test_cache_hashsum_mismatch
- To verify that a hashsum …

repo: catch error updating the package cache

---

tests/fake_servers/api.py
tests/integration/store/test_store_push_metadata.py

-----
We have implemented some changes in the store initializing the snap package on snap name approval, allowing to update the snap metadata (through web UI or snapcraft) without needing to push any revision.

tests: update metadata store integration test, no previous push required

---

snapcraft/plugins/nodejs.py
tests/unit/plugins/test_nodejs.py

nodejs plugin: lazy load the required tarballs

---

setup.py
snapcraft/cli/env.py
snapcraft/cli/lifecycle.py
snapcraft/internal/build_providers/__init__.py
snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_factory.py
snapcraft/internal/build_providers/_multipass/__init__.py
snapcraft/internal/build_providers/_multipass/_instance_info.py
snapcraft/internal/build_providers/_multipass/_multipass.py
snapcraft/internal/build_providers/_multipass/_multipass_command.py
snapcraft/internal/build_providers/errors.py
snapcraft/internal/lifecycle/_containers.py
snapcraft/project/__init__.py
tests/unit/build_providers/__init__.py
tests/unit/build_providers/multipass/test_instance_info.py
tests/unit/build_providers/multipass/test_multipass.py
tests/unit/build_providers/multipass/test_multipass_command.py
tests/unit/build_providers/test_base_provider.py
tests/unit/build_providers/test_errors.py
tests/unit/commands/test_cleanbuild.py

build_providers is a new package to handle different providers snapcraft
can use to create a snap.
In addition to the scaffolding, an implementation to handle
multipass is provided. This is the MVP for multipass integration.
-----

build_providers: new build provider using multipass

---

snapcraft/internal/sources/_base.py
tests/unit/sources/test_base.py
tests/unit/sources/test_rpm.py
tests/unit/sources/test_tar.py

-----
The source directory is already removed by the pluginhandler, having the sources do it is redundant and prevents `override-pull` from being useful when using those sources. This PR fixes [LP: #1767753](https://bugs.launchpad.net/snapcraft/+bug/1767753) by changing the `Tar`, `Zip`, and `Rpm` sources to no longer clean the target directory before extracting.

sources: don't clean target for FileBase sources

---

snapcraft/internal/meta/_snap_packaging.py
tests/unit/test_meta.py

-----
The snapcraft CLI currently has manifest generation hidden behind a feature flag. However, it's not quite all the way hidden, as an empty `snap` directory is still created in the priming area. This isn't particularly useful, so this PR fixes [LP: #1660890](https://bugs.launchpad.net/snapcraft/+bug/1660890) by no longer doing that.

meta: stop creating empty snap directory in prime

---

snapcraft/internal/pluginhandler/_runner.py
snapcraft/internal/project_loader/_parts_config.py
tests/unit/project_loader/test_config.py

Deduplicate the environment entries when generating it for a specific part.
Also wrap the override script into an actual file to reduce the possibility
of an argument list error occurring.
LP: #1767625
-----

many: dedup environment entries

---

snapcraft/file_utils.py
snapcraft/internal/errors.py
snapcraft/plugins/dump.py
tests/unit/plugins/test_copy.py
tests/unit/plugins/test_dump.py
tests/unit/test_errors.py

-----
Currently, when `file_utils.link_or_copy` is asked to copy files that don't exist (or symlinks that point to files that don't exist), `FileNotFoundErrors` from the underlying python calls leak through, resulting in a nasty traceback.
This PR fixes [LP: #1765282](https://bugs.launchpad.net/snapcraft/+bug/1765282) by catching `FileNotFoundErrors`, and turning them it into `SnapcraftError`-based exceptions.

file_utils: don't let FileNotFoundError escape

---

snapcraft/storeapi/_store_client.py
snapcraft/storeapi/errors.py
tests/fake_servers/api.py
tests/integration/store/test_store_status.py
tests/unit/store/test_store_client.py

-----
The store had a bug that ended up causing a snap to be registered to a user, but have no ID. The snapcraft CLI didn't handle this well, producing a traceback. This PR fixes [LP: #1763721](https://bugs.launchpad.net/snapcraft/+bug/1763721) by checking the snap ID before using it.

storeapi: ensure snap ID is sane before using it

---

snapcraft/internal/pluginhandler/__init__.py
tests/unit/pluginhandler/test_pluginhandler.py

Snapcraft's collision detection currently only checks files. This PR fixes LP: [#1658225](https://bugs.launchpad.net/snapcraft/+bug/1658225) by adding directories and symlinks to the list, making sure to catch files that collide with directories, and symlinks that point to different places.

pluginhandler: collide with directories and symlinks

---

snapcraft/storeapi/_client.py
snapcraft/storeapi/_store_client.py
snapcraft/storeapi/_upload.py
snapcraft/storeapi/errors.py
tests/fake_servers/api.py
tests/integration/store/test_store_release.py
tests/unit/store/test_store_client.py
tests/unit/test_errors.py

-----
Currently, the snapcraft CLI handles a 500 response when releasing a snap. This PR fixes [LP: #1768370](https://bugs.launchpad.net/snapcraft/+bug/1768370) by making this more robust, and nicely handling 5xx codes for all endpoints.

storeapi: handle 5xx error codes for all store endpoints

---

snapcraft/internal/lifecycle/_runner.py
snapcraft/internal/parser.py
snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/project_loader/__init__.py
snapcraft/internal/project_loader/_config.py
snapcraft/internal/project_loader/_env.py
snapcraft/internal/project_loader/_parts_config.py
snapcraft/project/_project_info.py
tests/integration/general/test_environment.py
tests/integration/snaps/cmake-with-env-var/CMakeLists.txt
tests/integration/snaps/cmake-with-env-var/snapcraft.yaml
tests/integration/snaps/cmake-with-env-var/test.c
tests/unit/pluginhandler/test_pluginhandler.py
tests/unit/project_loader/test_config.py
tests/unit/test_lifecycle.py

-----
This PR resolves [LP: #1763028](https://bugs.launchpad.net/snapcraft/+bug/1763028) by adding new environment variables (and replacements) for part src and build directories. It also refactors the `SNAPCRAFT_*` environment handling to happen in one place instead of multiple.

many: introduce variables for part src and build

---

tests/integration/__init__.py

Logic around `SNAPCRAFT_SEND_ERROR_DATA` has been removed so it makes little
sense to keep it for tests.
-----

tests: remove obsolete env var

---

snapcraft/internal/repo/_deb.py
tests/fixture_setup/_fixtures.py
tests/unit/repo/test_deb.py
tests/unit/test_lifecycle.py

-----
The apt cache doesn't do any hand-holding when it comes to alternative dependencies. As a result, it's possible for the snapcraft CLI to get into the following situation:
- A depends on B OR C
- B depends on D
- C conflicts with B
- A and C are `stage-packages`
If A is handled first, apt defaults to the first alternate (which is sensible), and marks both A and B (and, by extension, D) to be installed. Then C is handled, which automatically unmarks B, but doesn't do anything to D. As a result, A, C, and D are installed into the snap, even though D is no longer required.
Fix this by crawling the set of changes in the cache and taking care of anything that can be automatically removed.

repo: automatically prune unneeded stage-packages

---

snapcraft/internal/common.py
snapcraft/internal/errors.py
tests/unit/plugins/test_ament.py
tests/unit/plugins/test_dotnet.py
tests/unit/plugins/test_ruby.py
tests/unit/test_errors.py
tests/unit/test_lifecycle.py

Catch exceptions for subprocess.check_call and subprocess.check_output
in snapcraft.internal.common and display a consumable message.
Fixes SNAPCRAFT-11
Fixes SNAPCRAFT-G
Fixes SNAPCRAFT-P
Fixes SNAPCRAFT-5
-----

errors: generic exception for common.run[_output]

---

tools/travis/run_tests.sh

Bring back codecov and ensure the proper checks are done before
publishing.
-----

ci: resurrect codecov

---

.travis.yml

The autopkgtest which are cronned aren't really used and cause
unnecessary overhead we can do without.
-----

ci: remove unused cron tests

---

snapcraft/plugins/plainbox_provider.py
tests/integration/plugins/test_plainbox_provider_plugin.py
tests/integration/snaps/plainbox-provider-python-stage-pkg-mix/com.example_simple/manage.py
tests/integration/snaps/plainbox-provider-python-stage-pkg-mix/com.example_simple/units/simple.pxu
tests/integration/snaps/plainbox-provider-python-stage-pkg-mix/snap/snapcraft.yaml

-----
Launchpad bug 1768233 discussed a problem that was encountered when building checkbox snaps using the plainbox-provider plugin. This PR includes the workaround discussed so builds can begin working again. Integration test included for the original report.

lp 1768233 workaround for plainbox_provider plugin

---

snapcraft/internal/lifecycle/_runner.py
tests/unit/test_lifecycle.py

-----
Take the following situation: we have two parts, `A` and `B`. `A` depends on `B` by way of having `after: [B]`. Today, if one runs `snapcraft pull A`, the snapcraft CLI errors out complaining that it needs to stage `B` first, requiring one to run `snapcraft pull A B`. Not only is this an error, it's a `RuntimeError`, causing a traceback.
Stop erroring in this situation, and just stage `B` like the user wants.

lifecycle: automatically stage dependencies

---

snapcraft/config.py
snapcraft/internal/lifecycle/_runner.py
tests/unit/test_config.py
tests/unit/test_lifecycle.py

-----
Currently the snapcraft CLI will error out if a given step has already run, but has changed since doing so (e.g. if a part has been pulled, but then had a `stage-package` added).
This PR resolves [LP: #1774021](https://bugs.launchpad.net/snapcraft/+bug/1774021) by adding support for automatically cleaning the required steps instead of erroring. It leaves today's behavior as the default, but adds a configuration item to enable the new behavior. Simply add the following snippet to `~/.config/snapcraft/cli.cfg`:
[Lifecycle]
outdated_step_action = clean

lifecycle: automatically clean dirty steps

---

snapcraft/plugins/jhbuild.py

JHBuild has recently acquired the ability to run under the root account with an environment variable to acknowledge the operation.
If applied, this commit will:
* Add JHBUILD_RUN_AS_ROOT environment variable to jhbuild plugin
* Remove previous attempt to work around snapcraft running under root from jhbuild plugin
- `FAILED (failures=3, errors=5)`
- failures and errors are in unrelated parts of snapcraft:
- tests.unit.sources.test_bazaar.BazaarDetailsTestCase.test_bzr_details_commit
- tests.unit.sources.test_bazaar.BazaarDetailsTestCase.test_bzr_details_tag
- tests.unit.sources.test_mercurial.MercurialDetailsTestCase.test_hg_details_branch
- tests.unit.sources.test_mercurial.MercurialDetailsTestCase.test_hg_details_commit
- tests.unit.sources.test_mercurial.MercurialDetailsTestCase.test_hg …

jhbuild plugin: allow running as 'root'

---

tools/travis/setup_lxd.sh

-----
An update to LXD was recently released that changes some of the networking stuff done by `init` such that Travis broke on us. Even though this breakage also effects 3.0, we should be using LXD 3.0 in CI so we don't get other random breakage. Also, stop setting up testbr0, which broke and doesn't seem to be necessary anymore.

travis: use LXD from 3.0 track

---

snapcraft/internal/meta/_manifest.py
tests/unit/test_lifecycle.py

Expose the version of snapcraft used to create the snap in manifest.yaml
LP: #1768820
-----

recording: expose the version of snapcraft

---

snapcraft/internal/project_loader/_parts_config.py
tests/unit/project_loader/test_parts.py

-----
Currently, if parts are not strictly ordered by using `after`, the snapcraft CLI will process them in a completely non-deterministic order that changes between runs. This can make it extremely difficult to track down bugs that only occur when building in a specific order. This PR resolves [LP: #1759875](https://bugs.launchpad.net/snapcraft/+bug/1759875) by processing parts consistently and deterministically by sorting them by name.

project_loader: process parts in consistent order

---

schema/snapcraft.yaml
snapcraft/internal/project_loader/_config.py
tests/unit/project_loader/test_config.py

-----
This PR fixes [LP: #1772027](https://bugs.launchpad.net/snapcraft/+bug/1772027) by allowing one to specify remote parts without requiring the use of `after`, which implies a relationship which may not exist. With this PR, one can specify that the want a remote part simply by listing the part name, e.g.:
```yaml
parts:
my-part:
plugin: whatever
desktop-gtk3:
```

project_loader: allow loading null parts

---

tests/integration/__init__.py
tests/unit/__init__.py

-----
Currently, if an error occurs during a test, it just hangs waiting for user input that is never given. Fix this by disabling Sentry reporting when under test.

tests: disable sentry

---

snapcraft/internal/errors.py
snapcraft/internal/lifecycle/_clean.py
snapcraft/internal/mountinfo.py
tests/unit/test_errors.py
tests/unit/test_lifecycle.py
tests/unit/test_mountinfo.py

-----
Currently, if one uses 'snap try' and then runs 'snapcraft clean', one must 'snap try' again once the snap has been re-primed. This PR fixes [LP: #1774015](https://bugs.launchpad.net/snapcraft/+bug/1774015) by being smarter about this: checking to see if the priming area is being used by 'snap try', and if so, not removing it when cleaning, just its contents. Then once the snap has been re-primed, it'll just start working again, no 'snap try' required.

lifecycle: don't clean priming area if the snap is being tried

---

snap/snapcraft.yaml
snapcraft/internal/repo/_deb.py

Since the introduction of patchelf, it is not necessary to compile apt
anymore, this brings in two important benefits:
- faster builds
- automatic USNs for CVEs where apt is affected
-----
On bionic the correct apt methods are being used and there is no SIGSEV, ps output follows
```
sergius+ 30148 30108  6 18:49 pts/3    00:00:04 /snap/snapcraft/x14/usr/bin/python3 /snap/snapcraft/x14/bin/snapcraft pull
sergius+ 30173 30148  0 18:49 pts/3    00:00:00 /snap/snapcraft/x14/usr/lib/apt/methods/http
sergius+ 30174 30148  0 18:49 pts/3    00:00:00 /snap/snapcraft/x14/usr/lib/apt/methods/http
sergius+ 30176 30148  0 18:49 pts/3    00:00:00 /snap/snapcraft/x14/usr/lib/apt/methods/gpgv
sergius+ 30222 30148  1 18:49 pts/3    00:00:00 …
```

snap: use apt from the archive instead of compiling

---

snapcraft/cli/lifecycle.py
snapcraft/internal/common.py
snapcraft/internal/errors.py
snapcraft/internal/lifecycle/_clean.py
snapcraft/internal/lifecycle/_packer.py
snapcraft/internal/lifecycle/_runner.py
snapcraft/internal/lifecycle/constants.py
snapcraft/internal/lxd/_project.py
snapcraft/internal/meta/_manifest.py
snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/states/_state.py
snapcraft/internal/steps.py
tests/unit/__init__.py
tests/unit/commands/test_clean.py
tests/unit/pluginhandler/test_pluginhandler.py
tests/unit/test_errors.py
tests/unit/test_lifecycle.py
tests/unit/test_steps.py

-----
Currently the snapcraft CLI has step names and ordering hard-coded in a number of places, and those areas where it isn't hard-coded, a difficult-to-read index method is used. Simplify and extract this logic into a single module used by the others to determine lifecycle steps and ordering.

many: extract lifecycle ordering into own module

---

snapcraft/internal/errors.py
snapcraft/internal/lifecycle/_clean.py
snapcraft/internal/lifecycle/_runner.py
snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/project_loader/_config.py
snapcraft/internal/project_loader/_parts_config.py
snapcraft/internal/states/_build_state.py
snapcraft/internal/states/_prime_state.py
snapcraft/internal/states/_pull_state.py
snapcraft/internal/states/_stage_state.py
snapcraft/internal/states/_state.py
tests/integration/lifecycle/test_clean_build_step.py
tests/integration/lifecycle/test_clean_dependents.py
tests/unit/commands/test_clean.py
tests/unit/commands/test_prime.py
tests/unit/commands/test_snap.py
tests/unit/commands/test_stage.py
tests/unit/pluginhandler/test_pluginhandler.py
tests/unit/states/test_state.py
tests/unit/test_errors.py
tests/unit/test_lifecycle.py

-----
Currently, if a step for a given part has already run, the snapcraft CLI won't run it again without it first being cleaned. For example, if the `pull` step of part `A` had already run, running `snapcraft pull A` would say that it had already run, and skip it. This PR resolves [LP: #1774260](https://bugs.launchpad.net/snapcraft/+bug/1774260) by changing this behavior so that, if a part is specified, that step for that part is cleaned and re-run.

many: automatically redo step for specified part

---

requirements-devel.txt
runtests.sh
snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/project_loader/_config.py
snapcraft/plugins/kernel.py
snapcraft/plugins/ruby.py
snapcraft/project/_project_options.py
tools/travis/run_tests.sh
tools/travis/setup_lxd.sh

- Run mypy first and only then do spell checking.
- Update codespell to 0.12.0 which has better detection.
- Fix spelling issues discovered by codespell.
- Narrow down the list of directories searched for (no need to look in
e.g.; parts).
-----

tests: new codespell, narrowed checks and better execution order

---

snapcraft/formatting_utils.py
snapcraft/internal/errors.py
snapcraft/internal/lifecycle/__init__.py
snapcraft/internal/lifecycle/_clean.py
snapcraft/internal/lifecycle/_runner.py
snapcraft/internal/lifecycle/_status_cache.py
snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/pluginhandler/_dirty_report.py
snapcraft/internal/project_loader/_parts_config.py
snapcraft/internal/states/_build_state.py
snapcraft/internal/states/_prime_state.py
snapcraft/internal/states/_pull_state.py
snapcraft/internal/states/_stage_state.py
snapcraft/internal/states/_state.py
snapcraft/internal/steps.py
tests/unit/lifecycle/test_lifecycle.py
tests/unit/lifecycle/test_order.py
tests/unit/lifecycle/test_status_cache.py
tests/unit/pluginhandler/test_dirty_report.py
tests/unit/project_loader/test_config.py
tests/unit/states/test_state.py
tests/unit/test_errors.py

-----
Currently the only way parts know they're dirty from dependency changes is if the lifecycle tells them so. This is a very error-prone approach, since if the lifecycle forgets to tell the part, then it doesn't know it needs to be cleaned. This PR fixes [LP: #1778081](https://bugs.launchpad.net/snapcraft/+bug/1778081) by automatically detecting changes instead of noting them in code, which also simplifies the upcoming feature of detecting source changes.
Note that this PR breaks backward state compatibility with #2152 (i.e. running on trees made dirty since then will break). This was judged to be acceptable based on the fact that it has not yet been contained in a release.

many: automatically detect dependency changes

---

snapcraft/plugins/_python/_pip.py
snapcraft/plugins/python.py
tests/integration/plugins_python/test_python_plugin.py

-----
Both the Catkin and Python plugins utilize the Pip class in order to clean their pull steps (specifically, they tell the Pip class to clean its packages). However, when cleaning the pull step, Python has already been removed from the installdir, which means the Pip class cannot be instantiated, causing an error about being unable to find Python.
It's reasonable to ask Pip to clean any fetched packages, and doing so doesn't require Python. This PR fixes LP: [#1778716](https://bugs.launchpad.net/snapcraft/+bug/1778716) by lazily looking for Python only when it's required instead of upon class instantiation.

{catkin,python} plugin: support cleaning

---

.travis.yml

Homebrew updated to Python 3.7 which causes build failures with the currently
released PyYaml https://github.com/yaml/pyyaml/issues/126.
Disabled the tests until a working version for Ptthon 3.7 of PyYaml is released.
-----

ci: disable osx tests until a new pyyaml is released

---

snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_multipass/_multipass.py
snapcraft/internal/build_providers/_multipass/_multipass_command.py
snapcraft/internal/build_providers/errors.py
snapcraft/internal/repo/errors.py
snapcraft/internal/repo/snaps.py
tests/unit/build_providers/__init__.py
tests/unit/build_providers/multipass/test_multipass.py
tests/unit/build_providers/multipass/test_multipass_command.py
tests/unit/build_providers/test_base_provider.py
tests/unit/build_providers/test_errors.py

If running from the snapcraft snap, inject the snapcraft and its "base"
from the host to ensure parity.
If not running from the snap, install from the store.
LP: #1779137
-----
An easy way to test this is to install the snap, `snap run --shell snapcraft` and then run something like the following:
```python
import os
from snapcraft.cli import echo
from snapcraft.project import Project
from snapcraft.internal.build_providers import get_provider_for
os.chdir('/home/sergiusens/source/test-project')
Provider = get_provider_for('multipass')
project = Project(snapcraft_yaml_file_path='snap/snapcraft.yaml')
p = Provider(project=project, echoer=echo)
p.create()
```
Which would result in,
```
sergiusens@tupa:~/source/snapcraft$ snap run …
```

build_providers: inject snaps when running from a snap

---

snapcraft/cli/lifecycle.py
snapcraft/internal/lifecycle/_containers.py
snapcraft/internal/lxd/_containerbuild.py
tests/unit/commands/test_snap.py

-----
The snapcraft CLI recently switched from using hard-coded strings as lifecycle steps to an actual class. Unfortunately, containerbuilds also started using them, but they were never actually written to operate on steps: they require snapcraft commands instead. Sadly, this was never enshrined in tests.
This PR fixes [LP: #1780997](https://bugs.launchpad.net/snapcraft/+bug/1780997) by continuing to use string commands for containerbuilds, and adds tests to ensure things continue working that way.

lifecycle: pass commands to containerbuild, not steps

---

snapcraft/cli/env.py
tests/unit/commands/test_snap.py

-----
SNAPCRAFT_CONTAINER_BUILDS is deprecated, but we have a confusing error message if both are provided, saying that SNAPCRAFT_BUILD_ENVIRONMENT is the one that's deprecated. Fix this to say that SNAPCRAFT_CONTAINER_BUILDS is the one that's deprecated.

cli: SNAPCRAFT_BUILD_ENVIRONMENT isn't deprecated

---

snapcraft/internal/pluginhandler/__init__.py
tests/unit/lifecycle/test_lifecycle.py

-----
Currently, when recording the manifest from the `PluginHandler`, the snapcraft CLI runs `uname` using `common.run_output`, which is made for running binaries out of parts or the staging area. That's never desired in this case, so this PR fixes LP: [#1780825](https://bugs.launchpad.net/snapcraft/+bug/1780825) by using `subprocess` directly to always run `uname` from the host.

pluginhandler: use uname from the host

---

snapcraft/_store.py
tests/unit/commands/test_push.py

-----
In 2.41, the snapcraft CLI properly handled the situation of deltas being disabled on the store, which returned a 501. However, there was no test for this, which means as of 2.42.1, the behavior has regressed. This PR fixes [LP: #1780851](https://bugs.launchpad.net/snapcraft/+bug/1780851) by by properly handling 501s when pushing deltas.

store: properly handle disabled deltas

---

HACKING.md
snapcraft/cli/_runner.py
snapcraft/cli/snapcraftctl/_runner.py
tests/integration/general/test_list_plugins.py
tests/integration/store/test_store_push_metadata.py
tests/unit/__init__.py
tests/unit/commands/test_push_metadata.py

--debug has been conflated to debug snapcraft as a project itself and
snapcraft projects users of snapcraft work on. For the former we
introduce an environment variable to enable the existing debug logs
statements in the snapcraft code base.
LP: #1782772
-----

cli: reserve the --debug option for snapcraft projects

---

snapcraft/plugins/python.py
tests/unit/plugins/test_python.py

==> Contributor form ask me for my Launchpad ID but I don't know how to get it (the link provided lead me to https://login.launchpad.net/ which show my personal details, but not this id...)
==> Contributor form also ask me for a "Project contact", no idea what to put there
-----
Currently `process-dependency-links` option is not considered as a pull_properties i.e. build of this part won't be restarted if this option change. I guess this is not intended given this option do change the dependencies resolution.

Python plugin: add process-dependency-links to the pull_properties

---

tests/integration/store/test_store_revisions.py

Out of the blue we started getting this weird error in the 'Pre-merging' tests:
https://travis-ci.org/snapcore/snapcraft/builds/412858741
The proposed fix stop matching a chunk of opaque data before the revisions table. I suspect it was there for coping with the 'deprecation' message when the `history` command is used, but I can't tell for sure if anything related changed in snapcraft.

Stop expecting the deprecation message in test.

---

spread.yaml

-----
Ubuntu 17.10 is EOL as of July 19th, 2018. Stop testing it.

spread: stop testing 17.10

---

snapcraft/plugins/kbuild.py
tests/unit/plugins/test_kernel.py

Configs should be read from source directory instead of TOPDIR, in order
to handle a remote git repo properly.
Signed-off-by: Wen-chien Jesse Sung <jesse.sung@canonical.com>
-----

plugins: kbuild: read configs from source directory instead

---

snapcraft/plugins/kbuild.py
tests/unit/plugins/test_kbuild.py

-----
If the `kconfigfile` option is supplied, the kbuild plugin uses a hard link to put it into place. This becomes problematic if `kconfigfile` is used alongside `kconfigs`, because doing so modifies the config file, thereby modifying the original `kconfigfile` in the source tree.
This PR fixes [LP: #1786083](https://bugs.launchpad.net/snapcraft/+bug/1786083) by copying the `kconfigfile` instead of using hard links.

kbuild: stop modifying kconfigfile

---

snapcraft/cli/_errors.py
spread.yaml
tests/integration/__init__.py
tests/unit/__init__.py
tests/unit/cli/test_errors.py

-----
We recently regressed on #2154 by removing the ability to disable Sentry, which can cause tests to hang. Add this ability back.

sentry: support disabling error reporting

---

spread.yaml
tests/spread/plugins/catkin/run/task.yaml

-----
Also switch Google zones to us-east1-b.

spread: stop running catkin tests on 18.10

---

snapcraft/cli/containers.py
snapcraft/cli/lifecycle.py
snapcraft/cli/parts.py
snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_snap.py
snapcraft/internal/build_providers/errors.py
snapcraft/internal/lifecycle/_containers.py
snapcraft/internal/lxd/_cleanbuilder.py
snapcraft/internal/lxd/_containerbuild.py
snapcraft/internal/lxd/_lxc_command.py
snapcraft/internal/lxd/_project.py
snapcraft/internal/project_loader/_config.py
tests/fixture_setup/__init__.py
tests/fixture_setup/_fixtures.py
tests/unit/build_providers/test_base_provider.py
tests/unit/build_providers/test_snap.py
tests/unit/commands/test_build.py
tests/unit/commands/test_cleanbuild.py
tests/unit/commands/test_refresh.py
tests/unit/commands/test_snap.py
tests/unit/commands/test_update.py
tests/unit/lxd/test_lxd.py
tests/unit/project_loader/test_config.py

Use the same logic as the one implemented in the new provider logic.
Take the opportunity to normalize and untangle the code and also
fix the tests to remove duplication and unnecessary over mocking.
-----

lxd: support new style snap injection

---

snap/snapcraft.yaml

This projects snapcraft.yaml does not allow for easy rebuilding
given the use of linking and patching to make ctypes work properly
and the required patches to PyYAML.
-----

snap: prepare override scripts to allow rebuilding

---

snapcraft/storeapi/errors.py
tests/fake_servers/api.py
tests/unit/store/test_store_client.py

Releasing to a curly braced branch name should fail gracefully.
LP: #1788934
-----

storeapi: handle releasing to curly braced branch

---

debian/snapcraft-completion
snapcraft/cli/_command_group.py
snapcraft/cli/extensions.py

-----
This PR resolves [LP: #1788639](https://bugs.launchpad.net/snapcraft/+bug/1788639) by adding a `list-extensions` command. It also add both `list-extensions` and `extensions` to bash-completion.

cli: add list-extensions command

---

setup.py

-----
Extensions are currently being installed into "extensions-data" instead of the expected "extensions". This PR resolves [LP: #1790197](https://bugs.launchpad.net/snapcraft/+bug/1790197) by installing extension parts into "extensions".

extensions: fix install path

---

tests/integration/general/test_asset_recording.py

Make the integration tests for manifest generation go all the way
to creating a snap and run them through the review tools.
LP: #1790026
-----

tests: cover manifest generation with review-tools

---

snapcraft/cli/_errors.py
tests/unit/cli/test_errors.py

If an error occurs with a released version of snapcraft,
record it for the report.
-----

reporting: record the released version for errors

---

snapcraft/file_utils.py
tests/unit/test_file_utils.py

The case of returning an empty string was missed. More so,
the case of using the deb inside docker was not covered.
LP: #1790665
Fixes SNAPCRAFT-2E
-----

file_utils: find tool when using docker and deb

---

snapcraft/cli/_errors.py
tests/unit/cli/test_errors.py

-----
I have not built a snap of snapcraft to test. Neither multipass nor the snapcore/snapcraft docker image are happy with me.
This branch:
- Prints a traceback of the error when Raven isn't installed, rather than writing to a file.
- Makes it more clear that internal errors are ours to fix, but we'd greatly appreciate sentry or LP reports.

Error communication improvements

---

Dockerfile
docker/xenial-proposed.Dockerfile

Adding a dockerfile specifically tailored for testing the snapcraft deb
in xenial-proposed.
Also remove the multiverse sed from the standard Dockerfile as
multiverse is already in the base image.
LP: #1791116
-----

docker: support for testing snapcraft in proposed

---

snapcraft/__init__.py
snapcraft/project/_project_info.py
tests/unit/project_loader/test_validation.py

-----
This PR resolves [LP: #1791187](https://bugs.launchpad.net/snapcraft/+bug/1791187) by checking for unhashable types and raising a `ConstructorError` if it finds one. PyYAML deals with this by default, but the snapcraft CLI uses a custom dict loader that doesn't.  It also updates `ProjectInfo` to properly handle `ConstructionError`s, and adds a test for the whole thing.

yaml loading: properly handle unhashable types

---

snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_multipass/_multipass.py
snapcraft/internal/build_providers/_multipass/_multipass_command.py
snapcraft/internal/build_providers/errors.py
snapcraft/project/_project.py
tests/unit/build_providers/__init__.py
tests/unit/build_providers/multipass/test_multipass_command.py
tests/unit/build_providers/test_errors.py

Add support to shell into the provider,
$ $SNAP/usr/bin/python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from snapcraft.cli import echo
>>> from snapcraft.project import Project
>>> from snapcraft.internal.build_providers import get_provider_for
>>> p = Project(snapcraft_yaml_file_path="snapcraft.yaml")
>>> mp = get_provider_for("multipass")
>>> instance = mp(project=p, echoer=echo)
>>> instance.create()
snapcraft 2.42.1+git81.gca11846.dirty installed
>>> instance.shell()
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-134-generic x86_64)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage
Get …

build providers: provide support to shell in

---

snap/snapcraft.yaml
snapcraft/internal/pluginhandler/_runner.py
tests/integration/__init__.py
tests/unit/__init__.py
tests/unit/pluginhandler/test_runner.py

-----
Once the snapcraft CLI supports plugins providing command chains, scriptlets will need to be run in a subshell, a boundary across which aliases cannot cross. Instead of using an alias when running from the snap, this PR makes progress on [LP: #1790978](https://bugs.launchpad.net/snapcraft/+bug/1790978) by simply installing snapcraftctl into its own directory and adding it to the PATH.

pluginhandler: stop using alias for snapcraftctl

---

snapcraft/internal/build_providers/_images.py
snapcraft/internal/build_providers/_multipass/_multipass.py
snapcraft/internal/build_providers/errors.py
tests/unit/build_providers/__init__.py
tests/unit/build_providers/multipass/test_multipass.py
tests/unit/build_providers/test_errors.py
tests/unit/build_providers/test_images.py

Use snapcraft build images for multipass environments.
Quirck it for darwin as there is no "launch" support available
on darwin yet.
LP: #1791821
-----

build providers: snapcraft images for multipass

---

snapcraft/internal/common.py
tests/unit/sources/test_local.py

-----
This PR resolves [LP: #1791773](https://bugs.launchpad.net/snapcraft/+bug/1791773) by no longer copying the .snapcraft directory, and by no longer taking it into account when determining if a given part is out-of-date.

local source: don't include .snapcraft directory

---

snapcraft/internal/build_providers/_multipass/_multipass.py
snapcraft/internal/build_providers/_multipass/_multipass_command.py
tests/unit/build_providers/multipass/test_multipass.py
tests/unit/build_providers/multipass/test_multipass_command.py

We do this only for multipass given that we want to leave
the general build provider class available as a base to
add support for container based build providers.
Two environment variables are added to be able to override
the default memory and disk values.
LP: #1791661
-----

build providers: allow setting ram and disk size

---

snapcraft/internal/lifecycle/_runner.py
snapcraft/internal/meta/_snap_packaging.py
tests/unit/test_meta.py

-----
Today there's only a single environment used when generating the snap's snap.yaml, and it's set by the Lifecycle. However, as we move toward having separate environments per lifecycle step, generating the snap.yaml will involve using multiple environments. Instead of continuing to use Lifecycle for this, this PR makes progress on [LP: #1790978](https://bugs.launchpad.net/snapcraft/+bug/1790978) by moving the responsibility into meta.

meta: take charge of environment used to run commands

---

snapcraft/internal/build_providers/_base_provider.py
tests/unit/build_providers/test_base_provider.py

Inject the base snap building against if we are doing classic
confinmenent to get the appropriate linker paths.
LP: #1791938
-----

build providers: inject the base for classic

---

snapcraft/cli/_errors.py
tests/unit/cli/test_errors.py

-----
Currently the snapcraft CLI writes any traceback into a tracefile, regardless of whether or not stdout is a tty. In practice this means that when running in CI or cleanbuild, errors are hidden within a tracefile that cannot be accessed.
This PR resolves [LP: #1790697](https://bugs.launchpad.net/snapcraft/+bug/1790697) by printing the traceback if stdout is not a tty.

cli: show trace if no tty

---

snapcraft/plugins/_ros/rosdep.py
snapcraft/plugins/catkin.py
tests/unit/plugins/ros/test_rosdep.py
tests/unit/plugins/test_catkin.py

-----
In the old days of the snapcraft CLI, we used a lot of built-in exceptions. Now that we have a base exception and are using Sentry, it's important to make sure we no longer do that. The catkin plugin, however, does. This PR resolves [LP: #1791743](https://bugs.launchpad.net/snapcraft/+bug/1791743) by fixing it.

catkin plugin: use SnapcraftException

---

snapcraft/internal/build_providers/_snap.py
tests/unit/build_providers/test_snap.py

Enabled for early testing when snapcraft is not injected from the host.
Warn the user when this is done.
LP: #1792185
-----

build providers: allow snapcraft channel selection

---

snapcraft/project/_project_info.py
tests/integration/lifecycle/test_snap.py
tests/unit/project/test_project_info.py
tests/unit/project_loader/test_validation.py

-----
Currently `ProjectInfo` is pretty granular with the YAML exceptions it catches. There is no need for this since most of them inherit from `MarkedYAMLError` anyway, and it means we're constantly playing a game of whack-a-mole as new YAML exceptions are discovered. This PR fixes [LP: #1792049](https://bugs.launchpad.net/snapcraft/+bug/1792049) by catching `MarkedYAMLError`s and `ReaderError`s explicitly, and finally fall back to catching a `YAMLError` to avoid these tracebacks in the future.

project: catch parent YAML exceptions

---

snapcraft/cli/containers.py
snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_multipass/_multipass.py
snapcraft/internal/repo/_base.py
snapcraft/internal/repo/_deb.py
tests/unit/build_providers/__init__.py
tests/unit/build_providers/test_base_provider.py
tests/unit/commands/test_refresh.py
tests/unit/repo/test_deb.py

Run packaging repo refresh tasks when bringing up an environment.
This requires adding start to the BaseProvider and bringing up logic
that was in the Multipass provider.
LP: #1792214
-----

build providers: refresh packages on bring up

---

snapcraft/cli/_errors.py
tests/unit/cli/test_errors.py

Errors can occur during submission. This handles failing gracefully.
LP: #1791968
-----

reporting: fail gracefully on submit errors

---

snapcraft/plugins/_ros/rosdep.py
snapcraft/plugins/catkin.py
tests/unit/plugins/ros/test_rosdep.py
tests/unit/plugins/test_catkin.py

-----
Using non-`SnapcraftError`s results in tracebacks being sent to Sentry instead of nice error messages. Fix this by introducing `SnapcraftError`-derived exceptions for these cases instead of using `FileNotFoundError`s.

catkin, rosdep: stop using FileNotFoundErrors

---

snapcraft/internal/errors.py
snapcraft/internal/meta/_snap_packaging.py
tests/unit/test_errors.py
tests/unit/test_meta.py

Provide a nicer error for when the command entires under
an specific application cannot be found.
Also, for future proofing, ensure a warning is raised when these
commands are not relative to the prime directory.
-----

meta: friendlier message for incorrect app command

---

snapcraft/project/_sanity_checks.py
tests/spread/general/snap_local_dir/snaps/snap-local-dir/snap/local/dir/dir-file
tests/spread/general/snap_local_dir/snaps/snap-local-dir/snap/local/root-file
tests/spread/general/snap_local_dir/snaps/snap-local-dir/snap/snapcraft.yaml
tests/spread/general/snap_local_dir/task.yaml
tests/spread/plugins/nil/basic/task.yaml
tests/unit/project/test_sanity_checks.py

-----
It's natural for folks to want to put all snap-specific files into the `snap/` directory. This PR resolves [LP: #1792203](https://bugs.launchpad.net/snapcraft/+bug/1792203) by giving them a place to do that: `snap/local/`.

sanity checks: allow snap/local dir

---

snap/snapcraft.yaml

Do "snapcraftctl pull" before "snapcraftctl set-version"
-----

snap: pull early

---

snapcraft/project/_sanity_checks.py
tests/unit/project/test_sanity_checks.py

The snapcraft CLI runs sanity checks. The check of the snap/ directory is currently relative to cwd, which breaks in build VMs. This PR fixes [LP: #1792962](https://bugs.launchpad.net/snapcraft/+bug/1792962) by making it relative to the project directory instead.

sanity checks: run properly on build VMs

---

snapcraft/cli/_runner.py

When snapcraft is called from managed-host environment, it needs to re-exec itself as root.
LP: #1791977
-----

build providers: re-exec as root

---

snap/snapcraft.yaml
tools/snapcraft-override-build.sh

-----
In order to reduce duplication in the snapcraft.yaml as we work toward vendoring snapcraft within itself ([LP: #1793261](https://bugs.launchpad.net/snapcraft/+bug/1793261), refactor the current override-build into a script.

snapcraft snap: refactor override-build into a script

---

snapcraft/internal/build_providers/_multipass/_multipass.py
snapcraft/internal/build_providers/_multipass/_multipass_command.py
tests/unit/build_providers/multipass/test_multipass.py
tests/unit/build_providers/multipass/test_multipass_command.py

build providers: make use of time for multipass stop

---

snapcraft/cli/lifecycle.py

build providers: use multipass automatically when on darwin

---

snapcraft/config.py
tests/unit/lifecycle/test_lifecycle.py

-----
Without bases, the default outdated action is to error. This PR resolves [LP: #1793466](https://bugs.launchpad.net/snapcraft/+bug/1793466) by changing the default to clean if using bases.

config: change default outdated action to clean

---

bin/snapcraft
setup.py
snap/snapcraft.yaml
snapcraft/internal/common.py
snapcraft/internal/dirs.py

-----
This PR resolves [LP: #1793261](https://bugs.launchpad.net/snapcraft/+bug/1793261), continuing support for the lack of a base by vendoring legacy snapcraft into the snapcraft snap and dispatching to it if there is no base specified in the snapcraft.yaml.
**Note:** These tests will fail until #2283 lands in legacy.

snapcraft snap: vendor legacy snapcraft

---

snapcraft/internal/sources/_7z.py
snapcraft/internal/sources/_base.py
snapcraft/internal/sources/_bazaar.py
snapcraft/internal/sources/_git.py
snapcraft/internal/sources/_mercurial.py
snapcraft/internal/sources/_rpm.py
snapcraft/internal/sources/_subversion.py
snapcraft/internal/sources/errors.py
tests/unit/sources/test_7z.py
tests/unit/sources/test_bazaar.py
tests/unit/sources/test_git.py
tests/unit/sources/test_mercurial.py
tests/unit/sources/test_rpm.py
tests/unit/sources/test_subversion.py

-----
Currently, the snapcraft CLI doesn't handle any `CalledProcessError`s coming from the sources (e.g. `git clone [...]`). This means that any network issues or invalid repo URLs result in tracebacks and error submissions to Sentry. This PR fixes [LP: #1794272](https://bugs.launchpad.net/snapcraft/+bug/1794272) by properly handling this situation and printing an error.

sources: properly handle pull failures

---

snap/snapcraft.yaml

Remove --dirty from git-describe to workaround LP: #1662388
-----

snap: workaround the dirty tree

---

snapcraft/internal/meta/_snap_packaging.py
tests/integration/lifecycle/test_snap.py
tests/integration/snaps/assemble/binary1.after
tests/integration/snaps/assemble/command-chain
tests/unit/test_meta.py

-----
Currently, the snapcraft CLI takes the environment and runnables from plugins and shoves them into a wrapper per app. In anticipation of moving to command-chain, this PR resolves [LP: #1794261](https://bugs.launchpad.net/snapcraft/+bug/1794261) by extracting this information into a separate script, leaving the app wrappers as bare-bones as possible.

meta: put environment into runner instead of app wrapper

---

snapcraft/internal/project_loader/grammar_processing/_part_grammar_processor.py
spread.yaml
tests/spread/plugins/python/dirty-autoclean/task.yaml
tests/spread/plugins/python/snaps/python-hello/hello
tests/spread/plugins/python/snaps/python-hello/setup.py
tests/spread/plugins/python/snaps/python-hello/snap/snapcraft.yaml
tests/spread/setup/restore.sh

-----
Currently the part processor is handed a plugin and immediately saves off various grammar-powered attributes, such as stage- and build-packages, etc. However, there are plugins (specifically Python) that define these to be properties with definitions that change depending on the environment. For example, if it already finds Python, it won't add it to stage-packages. This proves to be problematic when a part is automatically cleaned because it was dirty: the grammar processor isn't created multiple times, just once before the part was cleaned. However, at least in the Python plugin case, once the part is cleaned it's stage-packages must be re-evaluated or Python will be missing when it's rebuilt.
This PR fixes [LP: #1794443](https://bugs.launchpad.net/snapcraft/+bug/1794443) by …

part grammar processor: lazily capture attributes from plugin

---

snapcraft/internal/errors.py
snapcraft/internal/pluginhandler/__init__.py
tests/unit/pluginhandler/test_pluginhandler.py

-----
If a part uses the `organize` keyword, in order for the `build` step to be updated, the organization must support happening twice without a clean. This PR resolves [LP: #1794083](https://bugs.launchpad.net/snapcraft/+bug/1794083) by adding the ability for `organize` to overwrite files and directories previously organized by the part.

pluginhandler: update build should overwrite organize

---

requirements.txt

-----
This PR is a backport of #2302, fixing [LP: #1794703](https://bugs.launchpad.net/snapcraft/+bug/1794703) for legacy.

[legacy] requirements.txt: stop using pymacaroons-pynacl

---

requirements.txt

-----
This PR resolves [LP: #1794703](https://bugs.launchpad.net/snapcraft/+bug/1794703) by no longer using pymacaroons-pynacl. It doesn't seem necessary, clashes with pymacaroons, and results in failures to link at runtime.

requirements.txt: stop using pymacaroons-pynacl

---

snapcraft/internal/dirs.py

When running in legacy mode, the directory paths for fixed assets differs.
Assets are found within legacy_snapcraft instead of the topdir $SNAP.
LP: #1795380
-----

setup: improve dir setup for when running in legacy mode

---

bin/snapcraft

The current logic missed the detection when running inside
a build provider given that by default snapcraft does not
run within the project directory.
LP: #1795501
-----

snap: improve early base detection logic

---

snapcraft/cli/_runner.py

When running in in re-exec mode and re-exec'ing as root
the wrong interpreter is used. This is solved by calling
the snapcraft "script" by prepending the interpreter.
LP: #1795501
-----

snap: legacy needs to now it is legacy for re-exec

---

snapcraft/internal/errors.py
snapcraft/internal/pluginhandler/__init__.py
tests/unit/pluginhandler/test_pluginhandler.py

-----
This PR is a backport of #2290, fixing [LP: #1794083](https://bugs.launchpad.net/snapcraft/+bug/1794083) for legacy.

[legacy] pluginhandler: update build should overwrite organize

---

snapcraft/internal/meta/_snap_packaging.py
tests/unit/test_meta.py

Build VMs use a different fs mount than where the prime directory
actually is, use file_utils.link_or_copy to setup the
icon.
LP: #1794974
Fixes SNAPCRAFT-5J
-----

meta: link the icon correctly across filesystems

---

snapcraft/plugins/nodejs.py

LP: #1795531
-----
The addition of the ppc64el and s390x to the list of nodejs plugin supported architectures has been tested with custom plugin x-nodejs to work with auto-building Hugo snaps Launchpad, see:
* Temporary workaround with x-nodejs plugin https://github.com/gohugoio/hugo/commit/91f49c0700dde13e16f42c745584a0bef60c6fe2 (Line 68)
* https://launchpad.net/~gohugoio/+snap/hugo
* Successful s390x buildlog: https://launchpadlibrarian.net/391166164/buildlog_snap_ubuntu_xenial_s390x_hugo_BUILDING.txt.gz

nodejs plugin: add support for ppc64el and s390x

---

snapcraft/internal/build_providers/_multipass/_multipass.py
snapcraft/internal/build_providers/errors.py
tests/unit/build_providers/multipass/test_multipass.py
tests/unit/build_providers/test_errors.py

Multipass now offers a new remote, as support for new bases comes
it will grow into multipass on its own. Due to this, we now also
delegate the error message handling to multipass itself as we no
longer keep a static mapping in snapcraft for this.
LP: #1794361
-----

build providers: use the new snapcraft: remote for multipass

---

snapcraft/internal/pluginhandler/_plugin_loader.py
tests/unit/pluginhandler/test_plugin_loader.py

Logic existed to be able to support plugins that did not support
a signature with Project, support for this is removed with the
move to bases.
LP: #1796668
-----

pluginhandler: remove legacy plugin loading without project

---

schema/snapcraft.yaml
snapcraft/_baseplugin.py
snapcraft/internal/project_loader/_parts_config.py
snapcraft/internal/project_loader/_schema.py
tests/unit/plugins/test_base.py
tests/unit/project_loader/test_parts.py
tests/unit/project_loader/test_validation.py

With bases, wiki parts are gone so part names with forward
slashes can now be forbidden.
LP: #1796723
-----

pluginhandler: remove big solidus workaround

---

snapcraft/plugins/catkin.py
spread.yaml
tests/spread/plugins/catkin/catkin-with-python/task.yaml
tests/spread/plugins/catkin/content-sharing/task.yaml
tests/spread/plugins/catkin/legacy-pull/task.yaml
tests/spread/plugins/catkin/pip-support/task.yaml
tests/spread/plugins/catkin/recursive-rosinstall/task.yaml
tests/spread/plugins/catkin/run/task.yaml
tests/spread/plugins/catkin/snaps/catkin-recursive-rosinstall/snap/snapcraft.yaml
tests/spread/plugins/catkin/snaps/catkin-shared-ros/consumer/snap/snapcraft.yaml
tests/spread/plugins/catkin/snaps/catkin-shared-ros/producer/snap/snapcraft.yaml
tests/spread/plugins/catkin/snaps/catkin-with-python-part/snap/snapcraft.yaml
tests/spread/plugins/catkin/snaps/ros-pip/snap/snapcraft.yaml
tests/spread/plugins/catkin/snaps/ros-talker-listener/snap/snapcraft.yaml
tests/unit/plugins/test_catkin.py
tests/unit/plugins/test_catkin_tools.py

-----
This PR resolves [LP: #1794778](https://bugs.launchpad.net/snapcraft/+bug/1794778) and [LP: #1794779](https://bugs.launchpad.net/snapcraft/+bug/1794779) by updating the Catkin plugin (and by extension the Catkin Tools plugin) to be base-aware. It removes the `rosdistro` option and use only the LTS ROS release corresponding to the base being used, specifically Kinetic if core16 and Melodic if core18. Finally, it updates all Catkin Spread tests to use bases except for one legacy test that ensures legacy gets dispatched when no bases are being used.

catkin, catkin-tools: add support for bases

---

bin/snapcraft
snapcraft/cli/_options.py
snapcraft/cli/env.py
snapcraft/cli/lifecycle.py
spread.yaml
tests/integration/__init__.py
tests/unit/__init__.py

Add a destructive mode to trigger building on the host.
LP: #1791201
-----

lifecycle: switch to multipass by default

---

snapcraft/plugins/ruby.py
spread.yaml
tests/spread/plugins/ruby/bin-check/task.yaml
tests/spread/plugins/ruby/bundle/task.yaml
tests/spread/plugins/ruby/gem/task.yaml
tests/spread/plugins/ruby/legacy-pull/task.yaml
tests/spread/plugins/ruby/run/task.yaml
tests/spread/plugins/ruby/snaps/ruby-bins-exist/snap/snapcraft.yaml
tests/spread/plugins/ruby/snaps/ruby-bundle-install/snap/snapcraft.yaml
tests/spread/plugins/ruby/snaps/ruby-gem-install/snap/snapcraft.yaml
tests/unit/plugins/test_ruby.py

-----
This PR resolves [LP: #1794800](https://bugs.launchpad.net/snapcraft/+bug/1794800) by updating the Ruby plugin to be base-aware, only supporting core16 and core18.

ruby plugin: add support for base

---

snapcraft/internal/project_loader/_extensions/_extension.py
snapcraft/internal/project_loader/_extensions/_utils.py
tests/unit/project_loader/extensions/test_utils.py

-----
Currently, extensions are limited to adding YAML snippets to apps and parts, and adding new parts. In order to facilitate adding e.g. new plugs and slots, this PR resolves [LP: #1794531](https://bugs.launchpad.net/snapcraft/+bug/1794531) by adding the ability for extensions to also add YAML snippets to the root of the snapcraft.yaml.

extensions: support adding root properties

---

snapcraft/internal/project_loader/_extensions/_utils.py
tests/unit/project_loader/extensions/test_utils.py

-----
It's not clear how root extensions should be applied: to all apps? To apps that don't declare their own extensions? This PR resolves [LP: #1797631](https://bugs.launchpad.net/snapcraft/+bug/1797631) by holding off on that decision until we see how extensions are used, and removing the ability to declare extensions in the root for now.

extensions: remove root extensions

---

tests/unit/commands/test_pack.py
tests/unit/commands/test_snap.py

Use snap names that would pass a snap pack --check-skeleton run.
-----

tests: use valid snap names in unit tests

---

spread.yaml
tests/fake_servers/__init__.py
tests/fixture_setup/__init__.py
tests/fixture_setup/_fixtures.py
tests/fixture_setup/_unittests.py
tests/integration/__init__.py
tests/integration/general/test_alias.py
tests/integration/general/test_architectures.py
tests/integration/general/test_asset_recording.py
tests/integration/general/test_list_plugins.py
tests/integration/general/test_metadata_appstream.py
tests/integration/general/test_metadata_setuppy.py
tests/integration/general/test_snapcraftctl_set_grade.py
tests/integration/general/test_snapcraftctl_set_version.py
tests/integration/general/test_version_script.py
tests/integration/lifecycle/test_build_properties.py
tests/integration/lifecycle/test_pull_properties.py
tests/integration/lifecycle/test_snap.py
tests/integration/plugins/test_rust_plugin.py
tests/integration/plugins_nodejs/test_nodejs_plugin.py
tests/integration/snaps/assemble/binary1.after
tests/integration/snaps/assemble/command-chain
tests/integration/snaps/local-plugin-build-properties/snapcraft.yaml
tests/integration/snaps/local-plugin-legacy-build-properties/snapcraft.yaml
tests/integration/snaps/local-plugin-legacy-pull-properties/snapcraft.yaml
tests/integration/snaps/local-plugin-pull-properties/snapcraft.yaml
tools/travis/run_integration_test.sh

The integration tests import snapcraft into the suite, this causes all
sorts of problems, the most concerning one is test independence.
-----

tests: remove dependency on snapcraft for integration tests

---

snapcraft/plugins/scons.py
spread.yaml
tests/spread/plugins/scons/legacy-build-run/task.yaml
tests/unit/plugins/test_scons.py

Update the Scons plugin to be base-aware, only supporting core16 and
core18.
LP: #1794801
-----

scons plugin: add support for bases

---

snapcraft/internal/build_providers/_multipass/_multipass.py
tests/unit/build_providers/multipass/test_multipass.py

Use a more conservative default which is more aligned with the default
memory allocation.
Also add messaging on changes due to overriding.
LP: #1795666
-----

multipass: change default CPU value

---

snapcraft/plugins/qmake.py
spread.yaml
tests/spread/plugins/qmake/legacy-pull/task.yaml
tests/spread/plugins/qmake/run/task.yaml
tests/spread/plugins/qmake/snaps/qmake-hello/hello.c
tests/spread/plugins/qmake/snaps/qmake-hello/hello.pro
tests/spread/plugins/qmake/snaps/qmake-hello/snap/snapcraft.yaml
tests/unit/plugins/test_qmake.py

-----
This PR resolves [LP: #1794799](https://bugs.launchpad.net/snapcraft/+bug/1794799) by updating the qmake plugin to be base-aware, limited to core16 and core18. It also creates a suite of spread tests for it.

qmake plugin: add support for bases

---

TESTING.md
spread.yaml
tests/spread/general/multipass/snaps/make-hello/Makefile
tests/spread/general/multipass/snaps/make-hello/hello.c
tests/spread/general/multipass/snaps/make-hello/snap/snapcraft.yaml
tests/spread/general/multipass/task.yaml
tests/spread/tools/restore.sh

-----
This PR resolves [LP: #1798682](https://bugs.launchpad.net/snapcraft/+bug/1798682) by changing all amd64 Xenial and Bionic Spread tests to run on a GCE image with nested KVM enabled, and adding a test that uses multipass build VMs.
Hat tip to @sergiocazzolato who made this happen.

tests: add spread test exercising multipass build VMs

---

tests/unit/project_loader/extensions/test_extensions.py

-----
This should have been a part of #2375, but was missed.

unit tests: missing full adapter in extension test

---

snapcraft/internal/meta/_snap_packaging.py
tests/unit/test_meta.py

-----
Currently the snapcraft CLI supports a "full" app adapter that utilizes snapd's new `command-chain` functionality instead of app wrappers. However, `command-chain` still isn't contained within a stable snapd release. This PR resolves [LP: #1799295](https://bugs.launchpad.net/snapcraft/+bug/1799295) by, automatically adding an `assumes: [command-chain]` when using the "full" app adapter.
**Note:** This PR depends on https://github.com/snapcore/snapd/pull/6029, and assumes (heh) it will make it into v2.36. If it doesn't, we'll have to hard-code snapd versions instead, which isn't ideal since it's easy to lose track of what that means.

meta: add assumes if using "full" app adapter

---

snapcraft/internal/errors.py
snapcraft/internal/project_loader/_parts_config.py
snapcraft/internal/project_loader/errors.py
tests/unit/project_loader/test_parts.py
tests/unit/test_errors.py

-----
The removal of remote parts in 06532fe0cea61462f371c6a87439771bfa6d67d6 also removed the sanity checking of parts contained within the `after` keyword. As a result, the snapcraft CLI simply ignores part names specified in `after` that aren't defined in the `snapcraft.yaml`. This isn't very helpful, and also makes the migration from remote parts incredibly difficult since they magically don't work instead of erroring nicely.
This PR fixes [LP: #1799596](https://bugs.launchpad.net/snapcraft/+bug/1799596) by raising an error if a part specified in `after` isn't defined.

project_loader: raise error if part in after is undefined

---

spread.yaml

-----
@sergiocazzolato let me know that the virt-enabled image names will be changing this week. Update the `spread.yaml` to use the new names.

spread: change virt-enabled image name

---

runtests.sh

This helps to see the exact error and save some time on checking out and rerunning the check locally.
-----

runtests: run black with --diff

---

snapcraft/internal/meta/_snap_packaging.py
snapcraft/internal/pluginhandler/_plugin_loader.py
snapcraft/internal/project_loader/__init__.py
snapcraft/internal/project_loader/_config.py
snapcraft/internal/project_loader/_extensions/_utils.py
snapcraft/internal/project_loader/errors.py
snapcraft/project/_project_info.py
snapcraft/project/_sanity_checks.py
snapcraft/project/_schema.py
snapcraft/project/errors.py
tests/unit/__init__.py
tests/unit/commands/test_build_providers.py
tests/unit/commands/test_snap.py
tests/unit/project/__init__.py
tests/unit/project/test_sanity_checks.py
tests/unit/project/test_schema.py
tests/unit/project_loader/extensions/test_utils.py
tests/unit/project_loader/test_schema.py
tests/unit/test_meta.py

Avoid creating and invalid multipass instance by doing an early
validation of snapcraft.yaml. This has the benefit of faster turnaround
times too.
LP: #1794507
-----

project: early snapcraft.yaml validation

---

snapcraft/internal/build_providers/_multipass/_multipass.py
tests/unit/build_providers/multipass/test_multipass.py

The uid and gid mapping removal for when on non Linux was the wrong
solution to the problem to solve a multipass problem which is now fixed.
-----

Partial Revert "build providers: fix osx non base and injection"

---

snapcraft/internal/project_loader/_config.py
tests/unit/project_loader/test_build_packages.py

When version is set to git, snapcraft should ensure that git makes it
into the build-packages set.
LP: #1802899
Fixes SNAPCRAFT-7P
-----

project_loader: add git to build-packages for version: git (#2403)

---

requirements.txt

packaging: update requests

---

snapcraft/internal/build_providers/_multipass/_multipass_command.py
tests/unit/build_providers/multipass/test_multipass_command.py

multipass commands that do not require stdin should have it point to
subprocess.DEVNULL to avoid multipass' metrics UI
LP: #1803445
-----

multipass: avoid stdin where possible

---

requirements.txt
snapcraft/internal/build_providers/_base_provider.py
tests/unit/build_providers/test_base_provider.py

Use the value from the host if possible, if not, fallback to Etc/UTC.
Leverage cloud-init to set the timezone correctly.
LP: #1801742
-----

build providers: preset the timezone

---

snapcraft/plugins/python.py
tests/spread/plugins/python/setup-py-with-external-dep/task.yaml
tests/spread/plugins/python/snaps/python-setuppy-with-deps/hello
tests/spread/plugins/python/snaps/python-setuppy-with-deps/setup.py
tests/spread/plugins/python/snaps/python-setuppy-with-deps/snap/snapcraft.yaml
tests/unit/plugins/test_python.py

This change ensures that if setup.py has a dependency in order to be processed
that it can be handled by processing dependencies separately followed
by the handling of setup.py.
for increased cleanup, setup.py does not form part of the "download"
process.
LP: #1803573
-----

python plugin: process deps before and separately from setup.py

---

tools/cla_check.py

We'll get to snap these sometime, but until then, here have the
cla_check.py we're using in snapd, based on yours (but much
improved). It's faster, more accurate, and has nicer, simpler, easier
to understand output.
Note that it does have an output of "I don't know", which still passes
the test. This can happen if a PR is done entirely using github's web
tools from a privacy-enabled account. You'd need to verify manually
then.

tools: pull in imporved cla_check.py from snapd

---

snapcraft/cli/lifecycle.py
snapcraft/internal/lifecycle/_init.py
tests/spread/legacy/command-define/task.yaml
tests/spread/legacy/command-update/task.yaml
tests/unit/commands/test_init.py

Add a link to where the syntax is defined after doing an init.
LP: #1803776
-----

cli: snapcraft init with a base

---

snapcraft/internal/lifecycle/_init.py
tests/unit/commands/test_init.py

This reverts commit 4e46b5a18f222d1f4e3084d642633e6d25bbd3bd after considering:
- https://forum.snapcraft.io/t/snap-multi-line-descriptions-need-newline-trim-on-store-import/3934/12
- https://forum.snapcraft.io/t/use-of-markdown-in-snap-metadata-summary-description/2128
-----

Revert "lifecycle: make snapcraft init template use > not | (#2393)"

---

tests/fixture_setup/_fixtures.py

The `bash` package name might be used internally for other tests, so let's use a separate one reserved for the snapcraft tests.

Do not use `bash` package name in staging

---

snapcraft/plugins/nodejs.py
tests/unit/plugins/test_nodejs.py

LP: #1807971
Fixes SNAPCRAFT-9X
-----

nodejs plugin: fail gracefully when a package.json is missing

---

snapcraft/cli/help.py

-----
LP: https://bugs.launchpad.net/snapcraft/+bug/1745040
Forum: https://forum.snapcraft.io/t/snapcraft-help-command-showing-wrong-usage/9045?u=felicianotech
P.S. The last two items in the checklist above, aren't documented well in the HACKING guide and don't even pass on master.

cli: fix usage string in help command

---

requirements.txt
runtests.sh
snapcraft/extractors/appstream.py
tests/unit/extractors/test_appstream.py

Take into account more complex descriptions by transforming them using XSLT
prior to retrieving their contents by applying normalization into plain text
and taking into account language attributes (xml:lang).
LP: #1778545
-----

extractors: better appstream support for descriptions

---

.travis.yml
snapcraft/plugins/rust.py
tests/integration/plugins/test_rust_plugin.py
tests/integration/snaps/rust-with-revision/Cargo.toml
tests/integration/snaps/rust-with-revision/snapcraft.yaml
tests/unit/plugins/test_rust.py

- Latest versions of rustup removed --prefix, --disable-sudo and --save.
- Using command qualifiers for channels and revisions.
- A global rustup and cargo area is now in place for multiple parts
to reuse.
- Removed the test target as it was inconsitent with other plugins.
- Made use of .cargo/config for consistency across execution.
LP: #1809259
LP: #1803466
-----

rust plugin: refactor to use the latest rustup

---

schema/snapcraft.yaml
tests/unit/project/test_schema.py
tests/unit/test_meta.py

Rely on most of the validation done by `snap pack`.
LP: #1808148
-----

schema: allow before and after

---

snapcraft/internal/meta/_snap_packaging.py
tests/unit/test_meta.py

-----
Fixes https://bugs.launchpad.net/snapcraft/+bug/1812003
This is a cherry-pick of #2440

legacy/meta: make hooks executable instead of complaining they're not

---

snapcraft/internal/build_providers/_multipass/_multipass_command.py

The issue has been fixed upstream (CanonicalLtd/multipass#221).
-----

build providers: remove SIGUSR1 signal ignore workaround for multipass

---

snapcraft/cli/lifecycle.py
snapcraft/internal/build_providers/_base_provider.py
tests/unit/build_providers/test_base_provider.py
tests/unit/commands/test_build_providers.py
tests/unit/commands/test_clean.py
tests/unit/commands/test_inspect.py

Bring back snapcraft clean <part-name> when using build providers.
LP: #1779136
-----

cli: enable cleaning of parts

---

snapcraft/internal/pluginhandler/__init__.py
tests/unit/pluginhandler/test_pluginhandler.py

When a part is cleaned, the system does its housekeeping by removing
all the files or directories it prepared for stage or prime. If the
user manually removes a file (say, in another part's override-prime),
we should ignore the non-existent file and issue a warning instead
of halting and catching fire.
See https://bugs.launchpad.net/snapcraft/+bug/1813033 for more details.
-----

pluginhandler: handle removal of inconsistent files

---

snapcraft/plugins/ant.py
snapcraft/plugins/gradle.py
snapcraft/plugins/maven.py
spread.yaml
tests/spread/plugins/ant/run/task.yaml
tests/spread/plugins/gradle/run-gradlew/task.yaml
tests/spread/plugins/gradle/run/task.yaml
tests/spread/plugins/maven/run/task.yaml
tests/spread/plugins/maven/snaps/maven-hello/my-app/pom.xml
tests/spread/tools/snapcraft-yaml.sh
tests/unit/plugins/test_ant.py
tests/unit/plugins/test_gradle.py
tests/unit/plugins/test_maven.py

Ensure that the expected java version is properly set when the default
openjdk option is used so that the globbing mechanism can format the
path to the java binary correctly.
Also ensure that the sytem works end to end for core16 and core18,
removing the typo of core19 which was supposed to be core16.
LP: #1813637
LP: #1813636
Fixes SNAPCRAFT-D1
-----

ant, maven and gradle plugins: use correct defaults for jre

---

snapcraft/cli/_options.py
snapcraft/cli/lifecycle.py
tests/unit/commands/test_clean.py

Reduce the risk of cleaning a non snapcraft base project by erroring out
if the snapcraft.yaml or the name is not defined in it.
LP: #1777501
-----

clean: error out on invalid or missing yaml

---

snapcraft/internal/lifecycle/_runner.py
snapcraft/internal/project_loader/_config.py
tests/unit/lifecycle/test_snap_installation.py

Docker environments are not capable of installing snaps given there is no
snapd running. Instead of trying to install, inform the user about the
situation for them to take the appropriate measures.
LP: #1814148
-----

lifecyle: avoid installation of snaps in docker

---

spread.yaml

ci: use non virt-enabled gce instances for 16.04

---

snapcraft/cli/_errors.py
snapcraft/cli/lifecycle.py
snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_multipass/_multipass.py
tests/unit/build_providers/__init__.py
tests/unit/build_providers/multipass/test_multipass.py
tests/unit/cli/test_errors.py

Upon facing an unhandled exception, snapcraft generates traceback data and stores it in the filesystem. If running in a build provider, the filesystem location is not accessible from host, and to give user access to error details we need to retrieve this data from the managed provider.
This fix addresses this issue by letting inner instance to save error data in a known location, which is retrieved by outer instance before proceeding.
LP: #1793082
**Note:** this patch refactors CLI error handling to deal with formatted trace data from provider. Raw traceback data can't be easily pickled up for transferring, hence the pre-formatting. It's also hard to test since this version must also be injected in the build provider, but I …

cli: retrieve error data from provider

---

debian/changelog
snapcraft/internal/build_providers/_base_provider.py
tests/unit/build_providers/__init__.py
tests/unit/build_providers/test_base_provider.py

Once a build provider is provisioned, changes in project base are
ignored and the existing VM is used for new builds. To ensure base
and provider contents are consistent, we test base values at the
start of each build and force instance recreation if base has
changed.
LP: #1794506
-----

build providers: recreate instance if base changed

---

tests/unit/project/test_schema.py

---
The theory for why this doesn't always fail is because, as of 2a2f798d0de8ad32cde48a8c9e6a48c53e6a9fb0, the schema is no longer an ordered dict, which makes the order in which validation finds multiple issues non-deterministic.
(We should consider ordering the loaded json, this may cause other issues)

tests: make before/after items an array in schema test

---

snapcraft/plugins/ruby.py
tests/unit/plugins/test_ruby.py

-----
This PR resolves [LP: #1815336](https://bugs.launchpad.net/snapcraft/+bug/1815336) by supporting the new URL required to download Ruby 2.6 and above (note that it's backward compatible, the older versions are available at this URL as well).

ruby plugin: support new download URL

---

snapcraft/plugins/ruby.py
tests/unit/plugins/test_ruby.py

-----
This PR is a backport of #2466, fixing [LP: #1815336](https://bugs.launchpad.net/snapcraft/+bug/1815336) for legacy.

[legacy] ruby plugin: support new download URL

---

schema/snapcraft.json
snapcraft/_baseplugin.py
snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/project_loader/grammar_processing/_part_grammar_processor.py
snapcraft/internal/repo/errors.py
snapcraft/internal/repo/snaps.py
snapcraft/internal/sources/__init__.py
snapcraft/internal/sources/_snap.py
snapcraft/internal/sources/errors.py
tests/fixture_setup/_unittests.py
tests/spread/general/stage_snaps/task.yaml
tests/unit/project_loader/grammar_processing/test_part_grammar_processor.py
tests/unit/repo/test_snaps.py
tests/unit/sources/test_errors.py
tests/unit/sources/test_snap.py

Add support for stage-snaps, with support for advanced grammar. Support for a snap
source was added to be able to extract the downloaded snaps.
LP: #1805214
-----

many: support for stage-snaps

---

snapcraft/internal/project_loader/_parts_config.py
tests/spread/general/build_environment/task.yaml
tests/unit/project_loader/test_environment.py

When using after, all components related to the environment get
concatenated when using after, that is not an intuitive behavior from a
user's point of view.
LP: #1815658
-----

project loader: do not leak a part's build-environment

---

snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_multipass/_multipass.py
tests/unit/build_providers/multipass/test_multipass.py

Remove methods from when build providers supported cleanbuild.
-----

build providers: remove dead code

---

tests/spread/plugins/colcon/run/task.yaml

Upstream changes broke the plugin. Temporarily disable the spread tests.
-----

tests: disable spread colcon tests

---

snapcraft/internal/meta/_snap_packaging.py
tests/unit/test_meta.py

Handling of symlinked hooks broke with the introduction of #2440
which tries to change permissions of their file type which can
lead to FileNotFoundErrors as the symlinked file may not be
available at the time of the stat change.
-----

meta: handle symlinked hooks

---

.travis.yml
bin/snapcraftctl
runtests.sh
snapcraft/internal/project_loader/_env.py
snapcraft/internal/project_loader/_parts_config.py
snapcraft/plugins/dotnet.py
tests/spread/plugins/autotools/classic/task.yaml
tests/spread/plugins/autotools/snaps/autotools-hello/snap/snapcraft.yaml
tests/spread/plugins/plainbox/snaps/checkbox/launchers/checkbox-cli-wrapper
tests/unit/project_loader/test_environment.py

This implementation can cause clashes with changes in the host with
regards to the base in use (i.e; core, core18, ...) as their might
be libc6 mismatches at the time that can lead to undefined behavior.
The issue comes up when the core snap is installed as it is when
the libraries are used, this specific behavior is no longer needed
as the library crawling feature has improved since this was first
introduced.
Additionally, the Travis CI job has been moved to using the deb
for the time being to overcome the bootstrapping issue that this
misbehavior creates.
This fix also has to come into legacy first to as snapcraft builds with
legacy be
LP: #1817300
-----

project loader: remove special LD_LIBRARY_FLAGS handling for classic

---

snapcraft/internal/meta/_snap_packaging.py
tests/unit/test_meta.py

Handling of symlinked hooks broke with the introduction of #2440
which tries to change permissions of their file type which can
lead to FileNotFoundErrors as the symlinked file may not be
available at the time of the stat change.
-----

meta: handle symlinked hooks (#2478)

---

snapcraft/internal/sources/_local.py
tests/unit/sources/test_local.py

A regression was introduced with the fix in PR #2419 which fixed
LP: #1806746. Local sources were being marked as dirty when contents
of the snap directory changed.
LP: #1816397
-----

sources: avoid marking changes to the snap directory as dirty

---

snapcraft/plugins/colcon.py
tests/spread/plugins/colcon/run/task.yaml
tests/spread/plugins/colcon/snaps/colcon-talker-listener/snap/snapcraft.yaml
tests/unit/plugins/test_colcon.py

-----
Until recently, colcon had a bug that caused it to not chain workspaces at build-time. That was recently fixed in a way that broke the colcon plugin. This PR fixes [LP: #1816565](https://bugs.launchpad.net/snapcraft/+bug/1816565) by reworking the plugin to rely more on the setup files and less on environment variables to avoid this issue in the future.

colcon plugin: support build-time chaining

---

snapcraft/_store.py
snapcraft/cli/store.py
snapcraft/internal/deltas/_deltas.py
snapcraft/storeapi/_upload.py
tests/unit/commands/test_push.py
tests/unit/test_deltas_xdelta3.py

The output of the 'snapcraft push' command shows too much information,
often displayed in inconsistent format and with seemingly arbitrary
colors (in fact, tied to the log level used for that line). This patch
partially cleans up the output, moving unnecessary messages to debug
level and making filename representation consistent across messages.
The final success message remains colored green, as does a log message
originary from the delta subsystem. We leave output colorization to be
discussed later and resolved globally.
LP: #1804439
-----

cli: clean up snapcraft push output

---

tests/unit/cli/test_errors.py

Certain build environments may need Raven client to be mocked in order
to get deterministic results from the error handling tests.
**Note**: this PR and PR #2488 are mutually exclusive, one must be chosen to address the traceback count errors in the final build.
-----

cli: Mock Raven client in error tests

---

snapcraft/internal/sources/_base.py
snapcraft/internal/sources/errors.py
tests/unit/sources/test_base.py

When pulling sources, handle network connection errors and HTTP request
errors.
Fixes SNAPCRAFT-DQ
Fixes SNAPCRAFT-G7
Fixes SNAPCRAFT-FJ
-----

sources: handle network request errors

---

snapcraft/_store.py
snapcraft/internal/errors.py
tests/data/invalid.snap
tests/unit/commands/test_push.py
tests/unit/commands/test_sign_build.py

Properly handle corrupt or invalid snap files when extracting package
data for signing or push.
Fixes SNAPCRAFT-GE
-----

store: handle invalid snap file errors

---

snapcraft/plugins/_python/_pip.py
tests/unit/plugins/python/test_pip.py

Return gracefully when no packages are provided in the package
related commands, these are:
- explicit python_packages
- requirements files
- setup.py directory
LP: #1794216
-----

python plugin: graceful ret when no packages set

---

snapcraft/cli/lifecycle.py
snapcraft/internal/meta/_snap_packaging.py
snapcraft/project/_get_snapcraft.py
snapcraft/project/_project.py
tests/spread/general/build-aux/task.yaml
tests/unit/project/test_get_snapcraft.py
tests/unit/test_meta.py

Many projects required an alternate snap directory to store
snapcraft related assets, in particular Gnome relate projects
have consolidated with the use of build-aux which snapcraft
is now adopting as an alternative as well.
LP: #1805219
-----

many: support the use of build-aux/snap

---

tests/spread/multipass/error-handling/task.yaml

Fix the multipass error handler spread test but don't remove the manual switch as multipass tests in gcloud don't seem to be stable enough.
-----

Fix multipass error handling spread test

---

snapcraft/plugins/nodejs.py
tests/unit/plugins/test_nodejs.py

The plugin was only capable of parsing bin entries inside package.json
of type dict, this adds support for str entries, taking into account
scoped package names.
LP: #1817553
-----

nodejs pluging: support for type str bin entries

---

snapcraft/_store.py
snapcraft/cli/store.py
snapcraft/storeapi/_sca_client.py
snapcraft/storeapi/_store_client.py
tests/fake_servers/api.py
tests/integration/__init__.py
tests/integration/store/test_store_register.py
tests/unit/commands/test_register.py
tests/unit/store/test_store_client.py

Add a --store-id option to the register command.
-----

store: support registering to a specific store

---

snapcraft/plugins/go.py
snapcraft/plugins/python.py
tests/unit/plugins/test_go.py
tests/unit/plugins/test_python.py

When using build providers, validate our yaml file schema prior to
executing ourselves inside the provider instance. This allows us
to quickly interrupt execution if validation fails. Also added
extra validation entries to the Go and Python plugins, to require
either sources or packages and prevent crashes in the test case
listed in the original bug report.
LP: #1806055
-----

plugins: improve python and go schema validation

---

snapcraft/internal/meta/_snap_packaging.py
tests/unit/test_meta.py

Do not copy snap/local into the snap, furthermore, improve the copy
logic to work better with embedded directories.
Fixes SNAPCRAFT-J2
Fixes SNAPCRAFT-JB
-----

meta: fix management of snap/local

---

snapcraft/cli/_errors.py
tests/unit/cli/test_errors.py

In order to avoid bogus environment misconfiguration reports, only allow
Sentry submissions if running from the packaged distribution.
-----

cli: disable raven if not running from package

---

snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_multipass/_multipass.py
snapcraft/internal/build_providers/_snap.py
tests/unit/build_providers/__init__.py
tests/unit/build_providers/test_snap.py

Cleanup up the channel warning when the
SNAPCRAFT_BUILD_ENVIRONMENT_CHANNEL_SNAPCRAFT is not set.
Removed unnecessary use of sudo, given that the providers all run as
root.
Silenced the call on holds for refreshes as it is unnecessarily noisy
and adds little value to users.
LP: #1820864
-----

build providers: improve handling in snap logic

---

snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_multipass/_multipass.py
snapcraft/internal/build_providers/_snap.py
tests/unit/build_providers/__init__.py
tests/unit/build_providers/multipass/test_multipass.py

Extend the signature for _run to be able to return output. Use this
across the Multipass implementation which wraps execute instead of
calling exectute for everywhere.
LP: #1821401
-----

build providers: modify the _run signature

---

snapcraft/internal/repo/_deb.py
snapcraft/internal/repo/errors.py
tests/unit/repo/test_deb.py

End gracefully instead of crashing if a deb package can't be
fetched.
Fixes SNAPCRAFT-JE
Fixes SNAPCRAFT-JF
-----

repo: handle deb package fetch error

---

snapcraft/cli/lifecycle.py
snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_multipass/_multipass.py
snapcraft/internal/build_providers/_multipass/_multipass_command.py
snapcraft/internal/build_providers/errors.py
snapcraft/project/_sanity_checks.py
snapcraft/project/errors.py
tests/unit/build_providers/__init__.py
tests/unit/build_providers/multipass/test_multipass_command.py
tests/unit/build_providers/test_errors.py

Move checks and setup to the provider implementation.
LP: #1821586
-----

build providers: support for provider setup

---

snapcraft/project/_project_info.py
tests/unit/project/test_project_info.py

PyYAML yaml loading and parsing can return None if given an empty file
or empty string. When validating its yaml file, Snapcraft expects the
result to be subscriptable, so return an empty dictionary instead of None.
Fixes SNAPCRAFT-JQ
-----

project: ensure yaml load returns a dictionary

---

snapcraft/extractors/appstream.py
snapcraft/internal/meta/_desktop.py
snapcraft/internal/meta/_snap_packaging.py
snapcraft/internal/pluginhandler/_metadata_extraction.py
tests/unit/extractors/test_appstream.py
tests/unit/test_meta.py

Appstream icons can be specified as a full path ("local") or just the
application name to be searched in the standard locations ("stock").
The system search for stock icons doesn't include directories that are
part of snap packages, so support stock icons by resolving the path
at packaging time. If icons are not specified in the AppStream file,
use the desktop file definition instead.
LP: #1814898
-----

many: better handling of appstream icons

---

schema/snapcraft.json
tests/unit/project/test_schema.py

Provide some more detail around numeric version error
messages as per the Snapcraft reference at
https://docs.snapcraft.io/snapcraft-yaml-reference.
Signed-off-by: Nathan Howard <adanhawthorn@gmail.com>
-----

schema, tests: add more detail wrt numeric version errors

---

.travis.yml
snap/snapcraft.yaml

This would allow snapcraft to build with the new functionality from 3.x.
-----

snap: set core as a base

---

.travis.yml

The integration conditionals were wrong for the spread tests as they
require Google Keys which not many people have setup before hand leading
to many failed runs when pushing to branches not owned by
snapcore/snapcraft.
Also remove the unnecessary cron conditional, as it is no longer used.
Additionally, indent the integration scripts so they match all other
declarations in .travis.yml
-----

ci: improve travis integration conditionals

---

snap/snapcraft.yaml

Upstream patchelf issue NixOS/patchelf#167 prevents package building on
s390x. The test failure is apparently not significant for our use cases, so
switch patchelf sources to a branch with the offending test disabled.
Note: this PR requires patchelf PR snapcore/patchelf#1 to be merged before
running tests on s390x.
-----

packaging: use our patchelf branch

---

snapcraft/internal/build_providers/_lxd/_lxd.py
tests/unit/build_providers/lxd/test_lxd.py

Fixes SNAPCRAFT-MB
-----
Before
```
(snapcraft) multipass@lxd-snapcraft:~/t$ snapcraft --use-lxd
Using 'snap/snapcraft.yaml': Project assets will be searched for from the 'snap' directory.
The LXD provider is offered as a technology preview for early adopters.
The command line interface, container names or lifecycle handling may change in upcoming releases.
Launching a container.
Sorry, an error occurred in Snapcraft:
Traceback (most recent call last):
File "/home/multipass/snapcraft/snapcraft/internal/build_providers/_base_provider.py", line 249, in launch_instance
self._start()
File "/home/multipass/snapcraft/snapcraft/internal/build_providers/_lxd/_lxd.py", line 166, in _start
raise …
```

build providers: idempotent destroy for LXD

---

snap/snapcraft.yaml

After extensive tests with patchelf 0.10 on different architectures,
it seems that it's not producing reliable binaries on (at least) i386,
ppc64el and s390x. Revert back to 0.9 with local patches until 0.10
issues are properly addressed.
-----

snap: revert to patchelf 0.9 with local patches

---

snapcraft/internal/build_providers/_lxd/_lxd.py

Filter out this specific warning, and potentially others coming from
pylxd.models.operation which are irrelevant to the end user:
/snap/snapcraft/2839/lib/python3.5/site-packages/pylxd/models/operation.py:59: UserWarning: Attempted to set unknown attribute "location" on instance of "Operation"
.format(key, self.__class__.__name__))
-----

build providers: get rid of attribute warnings from pylxd

---

snapcraft/internal/project_loader/_env.py
tests/unit/project/test_project_info.py
tests/unit/project_loader/test_environment.py

New variable pointing to the project directory, the directory
the snapcraft command was run from. This variable should be correct
regardless of what build environment (container or host) the build
is running in. This allows easy reference to supporting script or
other resources inside snapcraft.yaml overrides sections.
Fixes https://bugs.launchpad.net/snapcraft/+bug/1824417
-----

Add SNAPCRAFT_PROJECT_DIR environment variable.

---

tests/spread/plugins/catkin/run/task.yaml

-----
Upstream ROS changed to start using python2. Both are valid, so make sure the test accounts for that.

catkin spread test: allow python2 as well as python

---

snapcraft/plugins/rust.py
tests/spread/plugins/rust/channel/task.yaml
tests/unit/plugins/test_rust.py

rustup.sh no longer accepts a --channel argument. Fix by setting up the
toolchain using rustup.
For consistency, do not install the default toolchain on toolchain setup
and instead use the former mechanism for all code paths.
Lastly, remove an unsued variable in RustPlugin._get_toolchain
LP: #1825062
-----

rust plugin: fix usage of rust-channel

---

tests/unit/extractors/test_appstream.py

A typo in the existing icon test in the appstream desktop file fallback
test cases caused the the missing icon scenario to be tested twice. Fix
the test so the existing icon case is also tested.
-----

extractors: fix typo in appstream icon unit test

---

tests/integration/__init__.py

-----
Currently, `get_package_version` returns the results from the latest Ubuntu release, regardless of the series requested. Until recently, this happened to work out, whether that's because the versions all lined up (doubtful) or because people.canonical.com only recently started using HTTPS.
However, now tests are breaking. This is due to a [bug in requests](https://github.com/kennethreitz/requests/issues/5077) that double-encodes URL parameters upon redirect. Simply switching over to HTTPS works around the bug (i.e. no redirect needed) and solves the problem.

integration tests: use correct series in get_package_version

---

tests/integration/__init__.py

-----
This PR is a backport of #2548 for legacy.

[legacy] integration tests: use correct series in get_package_version

---

snapcraft/plugins/catkin.py
snapcraft/plugins/catkin_tools.py
tests/unit/plugins/test_catkin.py
tests/unit/plugins/test_catkin_tools.py

-----
Currently, the Catkin plugin pulls compilers off to the side rather than requesting that they be installed on the host. The reason for this is historical at this point: before bases existed, one could build a ROS snap on any version of Ubuntu, even versions unsupported by the ROS distribution being used. In an effort to ensure this worked as well as possible, the Catkin plugin did as much as it could without utilizing `build-packages` to ensure all components were compatible.
With the introduction of bases (and the fact that the only ROS1 releases available correspond to LTS releases, and thus bases), this is no longer a concern. It's no longer possible to build a ROS snap on an unsupported Ubuntu version in a supported manner. Add to that the fact that there's a bug in the plugin's …

catkin plugin: use build-packages for compilers

---

tests/spread/plugins/catkin/run/task.yaml

-----
This PR is a backport of #2540 for legacy.

[legacy] catkin spread test: allow python2 as well as python

---

snapcraft/plugins/catkin.py
tests/unit/plugins/test_catkin.py

-----
Currently some of the include paths aren't ordered deterministically, and they change between builds, which ruins the rebuilding story because Catkin takes it as a sign that it needs to start the build over. This PR fixes [LP: #1827148](https://bugs.launchpad.net/snapcraft/+bug/1827148) for legacy by making sure they stay the same between builds.

[legacy] catkin plugin: ensure cxxflags are consistent

---

snapcraft/_store.py
snapcraft/file_utils.py
snapcraft/internal/build_providers/_snap.py
snapcraft/plugins/kernel.py
snapcraft/storeapi/_client.py
snapcraft/storeapi/_snap_index_client.py
snapcraft/storeapi/_store_client.py
snapcraft/storeapi/errors.py
snapcraft/storeapi/info.py
tests/fake_servers/search.py
tests/integration/snaps/kernel-download/snapcraft.yaml
tests/integration/store/test_store_download.py
tests/unit/build_providers/test_snap.py
tests/unit/plugins/test_kernel.py
tests/unit/store/test_store_client.py

Instead of accessing each element from the returned calls as dictionary
elements, this implementation offers classes with attributes and some
methods to interact with the API results.
-----
This implementation strays away from the existing implementation pattern of what lives in the storeapi package but I personally think, even if more work initially, will provide easier ways to interact with the results when the Snap Store API is not fresh in your head.

storeapi: move from details (v1) to info (v2)

---

snapcraft/extractors/_metadata.py
snapcraft/internal/meta/_snap_packaging.py
tests/unit/test_meta.py

Appstream common IDs should reference IDs actually used in the metadata.
To prevent typos, add a consistency check and fail if any common ID is
not found in appstream files.
LP: #1814902
-----

meta: Validate common ID against appstream metadata

---

snapcraft/internal/pluginhandler/_plugin_loader.py
snapcraft/internal/project_loader/_parts_config.py
snapcraft/project/_project.py
snapcraft/project/_project_options.py
tests/unit/__init__.py
tests/unit/project/test_project.py

When loading snapcraft.yaml from the build-aux/snap instead of snap, we
should also read local plugins from the alternative location.
LP: #1827095
-----

project: read local plugins from build-aux

---

snapcraft/internal/project_loader/_extensions/_utils.py
tests/unit/commands/test_extensions.py

Don't directly load extensions if their name starts with an underscore. These
extensions are internal and shouldn't be available for public consumption,
to avoid spawn new unanticipated scenarios that need to be supported forever.
-----

extensions: block direct use of private extensions

---

snapcraft/internal/meta/_manifest.py
snapcraft/internal/meta/_snap_packaging.py
snapcraft/project/_project.py
tests/unit/lifecycle/test_lifecycle.py
tests/unit/project/test_project.py

Expose snapcraft-started-at in the manifest.yaml to use as an ordering
mechanism when processing snaps coming into the Snap Store.
LP: #1806658
-----

manifest: expose snapcraft-started-at

---

snapcraft/plugins/dotnet.py

-----
In the process of setting up snapcraft for a dotnet core project I ran into an issue when using newer runtime versions. The releases metadata file that is being parsed to find the right sdk file to download has newer releases in a slightly different format. They now include the full URL instead of just the filename. They also changed the checksum file to use upper case instead of lower case letters in the checksum values. You can see this [here](https://raw.githubusercontent.com/dotnet/core/master/release-notes/releases.json) if you compare the releases at the top of the file to the ones lower down.
This updates the plugin to handle both release formats.
------
**I'm not developing on an ubuntu machine so running this test suite proved to be a challenge.

dotnet plugin: fix parsing of newer sdk releases

---

spread.yaml
tests/spread/general/cwd_not_on_sys_path/task.yaml
tests/spread/legacy/command-define/task.yaml
tests/spread/legacy/command-update/task.yaml
tests/spread/legacy/wiki-filesets/task.yaml
tests/spread/legacy/wiki/task.yaml
tests/spread/plugins/catkin/run/task.yaml
tests/spread/plugins/catkin/snaps/ros-talker-listener/snap/snapcraft.yaml
tests/spread/plugins/go/classic/task.yaml
tests/spread/plugins/go/cross_compile_cgo/task.yaml
tests/spread/plugins/meson/run/task.yaml

-----
Indigo snaps can no longer be built due to its being EOL (rosdep cannot discover dependencies for EOL distros without special flags). This PR resolves [LP: #1830769](https://bugs.launchpad.net/snapcraft/+bug/1830769) for legacy by updating the Catkin spread tests to use Kinetic instead of Indigo.
Given that 14.04 is EOL as well, it also removes all 14.04 spread tests.

[legacy] catkin spread tests: stop testing indigo

---

snapcraft/plugins/catkin.py
tests/unit/plugins/test_catkin.py

-----
The Catkin plugin currently defaults to using Indigo, a now-EOL ROS distro. Anyone relying on that default is now unable to build a snap. They will probably need to start using another one to get unblocked. Rather than simply set the default to something else and potentially run into this issue again, this PR resolves [LP: #1830784](https://bugs.launchpad.net/snapcraft/+bug/1830784) by getting rid of the default altogether and making users specify which one they want, thus keeping behavior predictable in the future.

[legacy] catkin plugin: remove default rosdistro

---

tests/spread/general/cwd_not_on_sys_path/task.yaml
tests/spread/legacy/command-define/task.yaml
tests/spread/legacy/command-update/task.yaml
tests/spread/legacy/scriptlets/task.yaml
tests/spread/legacy/wiki-filesets/task.yaml
tests/spread/legacy/wiki/task.yaml
tests/spread/plugins/catkin/legacy-pull/task.yaml
tests/spread/plugins/meson/legacy-build-run/task.yaml

-----
Indigo snaps can no longer be built due to its being EOL (rosdep cannot discover dependencies for EOL distros without special flags). This PR resolves [LP: #1830769](https://bugs.launchpad.net/snapcraft/+bug/1830769) by updating the legacy pull test in the Catkin spread suite to use Kinetic instead of Indigo. It also removes all 14.04 spread filters given that no 14.04 runners exist anymore (it, too, is EOL).

catkin spread tests: use kinetic instead of indigo

---

tests/spread/plugins/plainbox/snaps/checkbox/snap/snapcraft.yaml
tests/spread/plugins/plainbox/snaps/provider-basic/snap/snapcraft.yaml
tests/spread/plugins/plainbox/snaps/provider-python-stage-package-mix/snap/snapcraft.yaml
tests/spread/plugins/plainbox/snaps/provider-with-deps/snap/snapcraft.yaml
tests/spread/plugins/plainbox/snaps/provider-with-stage-packages/snap/snapcraft.yaml

This should reduce inconsistencies due to conflicting dependencies being
satisfied and produce consistent results.
-----

plainbox spread tests: lock down python packages

---

snapcraft/internal/remote_build/_launchpad.py
tests/unit/remote_build/test_launchpad.py

Also download build logs from Launchpad when the build succeeds. The
log file name is based on the project name and build architecture.
Numbered suffixes are added if the file already exists.
-----

remote build: retrieve build log files

---

snapcraft/plugins/rust.py

On i386 environment, linker becomes `i386-linux-gnu-gcc` according to
arch_triplet. It causes the following error on build.snapcraft.io:
```
error: linker `i386-linux-gnu-gcc` not found
|
= note: No such file or directory (os error 2)
```
To fix it, I added `_get_linker` method to adjust linker name.
-----

rust plugin: fix linker on i386

---

tests/spread/plugins/catkin/legacy-pull/task.yaml

When moving to defaulting to indigo in:
2c1b97bf41c4bf9e787c06bd85d3119a23263fb7
The finer architecture filter was lost and the spread task for catkin's
legacy-pull started to run on ppc64el. To solve this, the
relevant parts of the system filter at the suite level was brought
into this task.
-----

catkin spread tests: finer system filter for legacy-pull

---

snapcraft/formatting_utils.py
snapcraft/plugins/_ros/__init__.py
snapcraft/plugins/_ros/rospack.py
snapcraft/plugins/catkin.py
tests/spread/plugins/catkin/snaps/source-dependencies/snap/snapcraft.yaml
tests/spread/plugins/catkin/snaps/source-dependencies/src/CMakeLists.txt
tests/spread/plugins/catkin/snaps/source-dependencies/src/dependency/package.xml
tests/spread/plugins/catkin/snaps/source-dependencies/src/dependent/package.xml
tests/spread/plugins/catkin/source-dependencies/task.yaml
tests/unit/plugins/ros/test_rospack.py
tests/unit/plugins/test_catkin.py

-----
Currently the Catkin plugin doesn't check the workspace for dependencies, which causes the build to fail if a declared dependency isn't contained within the rosdep index (even though it's satisfied by another package in the workspace). Until rosdep [grows the ability to do this on its own](https://github.com/ros-infrastructure/rosdep/issues/685), this PR resolves [LP: #1832044](https://bugs.launchpad.net/snapcraft/+bug/1832044) by adding the ability for the snapcraft CLI to do this manually, using `rospack` to enumerate the packages contained in the workspace and filtering dependencies through that list.

catkin plugin: check workspace for dependencies

---

snapcraft/plugins/ant.py
tests/unit/plugins/test_ant.py

With this the ant plugin can use a build file in a non-default location.
-----

ant plugin: make build file location configurable

---

snapcraft/cli/remote.py
tests/unit/remote_build/test_worktree.py

Retrieved build logs are now saved using the project name, so update
our filters to prevent sending them back to the remote builder as
part of the local project files.
-----

remote build: don't send log files back to remote

---

snapcraft/internal/sources/_base.py
snapcraft/internal/sources/errors.py
tests/unit/sources/test_base.py
tests/unit/sources/test_errors.py

Many of the errors seen by users indicate source not found.
- introduce SnapcraftSourceNotFoundError with helpful error
message
- chain to FileNotFoundError raised by shutil.copy2(), a common
cause of the captured FileNotFoundError exceptions
-----

sources: introduce SnapcraftSourceNotFoundError

---

snapcraft/internal/remote_build/_repo.py
tests/unit/remote_build/test_repo.py

When dispatching a remote build job using --git and we're currently in
detached head state, branch name retrieval raises an exception. Fix that
by returning HEAD if detached head is detected.
-----

remote_build: handle git push in detached head state

---

snapcraft/plugins/crystal.py
spread.yaml
tests/integration/general/test_list_plugins.py
tests/spread/plugins/crystal/run/task.yaml
tests/spread/plugins/crystal/snaps/crystal-hello/hello/shard.yml
tests/spread/plugins/crystal/snaps/crystal-hello/hello/src/hello.cr
tests/spread/plugins/crystal/snaps/crystal-hello/snap/snapcraft.yaml
tests/unit/plugins/test_crystal.py

Initial plugin for crystal applications.

crystal plugin: initial version

---

snapcraft/cli/_options.py
snapcraft/cli/echo.py
snapcraft/cli/remote.py
snapcraft/internal/remote_build/errors.py

Add an option to prevent user interaction when running on a noninteractive
environment while still acknowledging that uploaded code will be public.
-----

remote build: add option to skip public upload question

---

snapcraft/internal/build_providers/_snap.py

Use a fixed well-known path for temporary files when copying files to
the build provider. If the user environment specifies a non-standard
temporary directory, the file may fail to copy to a multipass instance.
LP: #1833292
Signed-off-by: Mike Miller <mtmiller@debian.org>
-----

build providers: enforce well-known temp dir

---

schema/snapcraft.json
tests/unit/commands/test_snap.py
tests/unit/project/test_schema.py

Allow "snapd" snap type in the schema.
-----

schema: allow 'snapd' snap type

---

tests/spread/plugins/catkin/legacy-pull/task.yaml

The legacy tests intermittently fail when the backend is GCE,
on failures the entire apt-config will be printed to verify
that the original expectations of a 16.04 release with regards
to apt's configuration are still valid.
-----

catkin spread tests: dump apt-config on failures for legacy

---

snapcraft/plugins/rust.py
tests/spread/plugins/rust/rust-toolchain/task.yaml
tests/unit/plugins/test_rust.py

If the plugin options are not used and a rust-toolchain file
is found in the source, use that and only default to the
stable toolchain channel as a last resort.
-----

rust plugin: use rust-toolchain by default if present

---

tests/spread/plugins/catkin/legacy-pull/task.yaml

The legacy tests intermittently fail when the backend is GCE, setting to
manual until we can properly address the issue.
-----
```
+ cd ../snaps/ros-talker-listener
+ snapcraft pull
This snapcraft project does not specify the base keyword, explicitly setting the base keyword enables the latest snapcraft features.
Read more about bases at https://docs.snapcraft.io/t/base-snaps/11198
Installing build dependencies: libexpat1-dev libpython-all-dev libpython-dev libpython2.7-dev python-all python-all-dev python-dev python-pip python-pip-whl python-wheel python2.7-dev
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
libexpat1-dev libpython-all-dev …
```

catkin/legacy-pull: set test to manual

---

snapcraft/cli/_errors.py
snapcraft/cli/_options.py
snapcraft/cli/assertions.py
snapcraft/cli/ci.py
snapcraft/cli/echo.py
snapcraft/cli/lifecycle.py
snapcraft/cli/store.py
tests/integration/__init__.py
tests/unit/cli/test_echo.py
tests/unit/cli/test_errors.py
tests/unit/commands/__init__.py

Adapted from @cmatsuoka's remote-build work.
-----

tty-aware echo prompt and confirm

---

tests/spread/general/cwd_not_on_sys_path/snaps/sys-path-test/snap/snapcraft.yaml
tests/spread/general/cwd_not_on_sys_path/task.yaml

This tests currently does not specify a base.
As this test is not labelled as legacy, set the base.
Also set `source: .` to comply with non-legacy schema.
-----

tests/spread/cwd_not_on_sys_path: set base

---

.travis.yml
mypy.ini
snapcraft/cli/ci.py
snapcraft/internal/deltas/_deltas.py
snapcraft/internal/lifecycle/_packer.py
snapcraft/internal/project_loader/inspection/_latest_step.py
snapcraft/internal/repo/_deb.py
snapcraft/plugins/dotnet.py
snapcraft/storeapi/_sca_client.py
snapcraft/storeapi/errors.py
spread.yaml
tests/fake_servers/api.py
tests/unit/build_providers/multipass/test_instance_info.py
tests/unit/build_providers/test_errors.py
tests/unit/commands/__init__.py
tests/unit/lifecycle/test_lifecycle.py
tests/unit/lifecycle/test_status_cache.py
tests/unit/project/test_errors.py
tests/unit/project_loader/grammar_processing/test_global_grammar_processor.py
tests/unit/project_loader/test_build_packages.py
tests/unit/project_loader/test_validation.py
tests/unit/repo/test_deb.py
tests/unit/store/test_store_client.py
tests/unit/test_errors.py

tests/spread/general/cwd_not_on_sys_path tests are intermittently failing (see https://travis-ci.org/snapcore/snapcraft/jobs/551606315#L1020).  It takes the legacy code path as it doesn't specify a base.
The source: https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1832522.
The diff: https://git.launchpad.net/ubuntu/+source/openssl/diff/?id=783a1f8c6e756eb395025d4bc37a2d046369349b
Did some testing to confirm that DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true DEBIAN_PRIORITY=critical  should be sufficient:
```
root@b4eb8bc50540:/# wget https//launchpad.net/~ci-train-ppa-service/+archive/ubuntu/3662-deletedppa/+build/16554812/+files/libssl1.1_1.1.1-1ubuntu2.1~18.04.1_amd64.deb
root@b4eb8bc50540:/# dpkg -i libssl1.1_1.1.1-1ubuntu2.1~18.04.1_amd64.deb 
dpkg: warning: …
```

legacy backports: critical deb priority, updated black (and source formatting)

---

snapcraft/cli/_runner.py

Fixes https://bugs.launchpad.net/snapcraft/+bug/1807423
https://click.palletsprojects.com/en/7.x/documentation/#help-parameter-customization
-----

Add -h short option for help

---

snapcraft/cli/_errors.py
tests/unit/cli/test_errors.py

- Ensure that exception message is _always_ printed.
- Tweak rules of engagement
- Print exception message (always)
- Capture trace in temporary file and print path, conditionally if:
(1) Exception is SnapcraftReportableError or
(2) Exception is non-Snapcraft error
(3) debug is true
- Automatically send bug report if:
(1) SNAPCRAFT_ENABLE_SILENT_REPORT=y
(2) "Always" send has been previously set.
- Prompt to send bug report, conditionally if connected to TTY and:
(1) Exception is SnapcraftReportableError or
(2) Exception is non-Snapcraft error
- Print trace, conditionally if:
(1) debug is true, or
(2) Reportable (see above) and either:
(a) no TTY
(b) not running as snap
- Use exit code from snapcraft error (if available), otherwise 1.
- Fixup unit tests to comply with changes.
-----

errors: refactor exception/error handling

---

snap/snapcraft.yaml
snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_lxd/_lxd.py
snapcraft/internal/build_providers/_multipass/_multipass.py
snapcraft/internal/build_providers/_snap.py
snapcraft/internal/repo/snaps.py
tests/fake_servers/snapd.py
tests/unit/__init__.py
tests/unit/build_providers/__init__.py
tests/unit/build_providers/test_base_provider.py
tests/unit/build_providers/test_snap.py
tests/unit/repo/test_snaps.py

By use of snapd's new snaps/<snap-name>/file API.
This also removes the use of mounts and leverages file
pushing.
Refactoring has been done for a better separation of concerns.
-----

build providers: support injection for LXD

---

snapcraft/plugins/ant.py

Signed-off-by: Stefan Bodewig <stefan.bodewig@freenet.de>
-----
I've just released the ant snaps from candidate to stable and I feel stable is a better default than edge.

use the stable risk level now that ant has been released

---

schema/snapcraft.json
snapcraft/internal/lifecycle/_packer.py
snapcraft/internal/project_loader/_config.py
tests/unit/commands/test_pack.py
tests/unit/commands/test_snap.py
tests/unit/lifecycle/test_lifecycle.py
tests/unit/project/test_schema.py

Base support superseed the os type which should stay in legacy.
-----

schema: remove support for os when using bases

---

snapcraft/extractors/appstream.py
tests/unit/extractors/test_appstream.py

appstream extractor: skip non icon file paths

---

snapcraft/file_utils.py
snapcraft/internal/pluginhandler/__init__.py
tests/unit/pluginhandler/test_pluginhandler.py

Addresses the usr-merge issues discussed at https://bugs.launchpad.net/snapcraft/+bug/1833408
Adds tests to reproduce issue, fixup/remove faulty tests that are exposed with these changes.

pluginhandler: honour symlink directory paths for filesets (LP: #1833408)

---

spread.yaml
tests/spread/build-providers/lxd-basic/task.yaml
tests/spread/build-providers/lxd-prime-then-try/task.yaml
tests/spread/build-providers/lxd-try/task.yaml
tests/spread/build-providers/multipass-basic/task.yaml
tests/spread/build-providers/multipass-error-handling/task.yaml
tests/spread/tools/restore.sh

Move LXD setup to early prepare and do not remove at the end of each test
to avoid the setup overhead (including image download).
Additionally, move the common declarations from task.yaml to spread.yaml
for the build-providers suite.
-----

spread tests: enable LXD build provider tests

---

schema/snapcraft.json
tests/unit/project/test_schema.py
tests/unit/test_meta.py

synchronizing snapd supported schema to snapcraft
- Explicitly specify type string for existing options with unspcecified type:
- `stop-command`
- `reload-command`
- Add daemon type `dbus`
- Add daemon options:
- `bus-name` (for use with `daemon: dbus`) with regex pattern found in snapd
- `restart-delay`
- `start-timeout`
- `timer`
- `watchdog-timeout`
- Add `on-watchdog` for `restart-condition`
- Add `autostart` for apps installing autostart desktop files
- Specify dependencies on daemon for new daemon options, as well
as existing options (`stop-timeout`, `restart-condition`)
- Add some tests for newly exposed schema items.
- Update some descriptions to match https://docs.snapcraft.io/snap-format
- Add regex patterns for stop timeout (to match introduced timeouts).

synchronizing snapd supported schema to snapcraft

---

snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/pluginhandler/_dependencies.py
snapcraft/internal/repo/_base.py
snapcraft/internal/repo/_deb.py
snapcraft/internal/repo/errors.py
tests/unit/pluginhandler/test_missing_dependency.py
tests/unit/repo/test_deb.py

After priming, DT_NEEDED is checked for in all the files that were primed
and a list of missing files is listed, `stage-packages` are now listed
for the cases where these can be satisfied by adding them.
-----

pluginhandler, repo: find stage-packages from DT_NEEDED on host

---

tests/unit/lifecycle/test_lifecycle.py

Some fake webserver messages can sneak into the checked for
message output, using a more flexible check avoids this
situation.
-----

unit tests: make lifecycle tests more robust

---

snapcraft/internal/errors.py
snapcraft/internal/meta/_snap_packaging.py
tests/unit/test_errors.py
tests/unit/test_meta.py

Add a specific errors for
- command app not found
- command app not executable
LP: #1727425
-----

errors: Add InvalidAppCommand errors for non-existent and not-found

---

snapcraft/plugins/ant.py

Change the documented default channel from latest/edge to
latest/stable and normalize how the default is presented.
-----

ant plugin: correct default channel and improve help

---

snapcraft/cli/lifecycle.py
snapcraft/project/_sanity_checks.py
tests/unit/project/test_sanity_checks.py

Mute the directories that will be searched for, there is a
default and the build-aux one is an advanced use case. It can be
revisited in the future if necessary.
Also use the proper directories to search for outliers within
the snap directory to be used.
-----

project, cli: clean up snap asset messages

---

snapcraft/internal/deprecations.py
snapcraft/internal/meta/_snap_packaging.py

Part script `snapcraftctl set-version` is the currently recommended
method for dynamically determining the snap version information.
See 'https://docs.snapcraft.io/using-external-metadata' for additional
information on `snapcraft set-version`.
Output looks something like:
```
Priming <project>
DEPRECATED: The 'version-script' keyword has been deprecated in favour of the 'snapcraftctl set-version' part scriptlet.
See http://snapcraft.io/docs/deprecation-notices/dn10 for more information.
Determining the version from the project repo (version-script).
The version has been set to '<version>'
Snapping '<project>' \
Snapped <snap>
```
-----

deprecations: add deprecation notice for version-script (dn10)

---

snapcraft/internal/remote_build/_launchpad.py
snapcraft/internal/remote_build/errors.py
tests/unit/remote_build/test_launchpad.py

The easiest-to-reproduce example I have come across is to simply
ship the build repository to launchpad without a snapcraft.yaml. In
this case, snapcraft now fails with the following message from launchpad:
```
Sorry, an error occurred in Snapcraft:
Remote builder failed with error: 'Cannot find snapcraft.yaml in
https://cjp256@git.launchpad.net/~cjp256/+git/snapcraft-6cf35d52abc44b19a021b100cb883c8a/ master'
```
The original assumption was that the builder was busy, but now we can
determine if that's the case by checking if status is still "Pending".
It's seemingly quite rare (if ever?) to have the timeout condition hit,
but this commit maintains the checks should it happen:
```
Sorry, an error occurred in Snapcraft:
Remote builder failed with error: 'Timeout exceeded waiting for builder …
```

remote-build: detect early build errors

---

snapcraft/file_utils.py
tests/unit/sources/test_local.py
tests/unit/test_file_utils.py

file utils: better error for NotADirectory

---

snapcraft/cli/remote.py

Incorporate the project name into the build-id so it's identifiable when
looking at the list of snaps from the launchpad web portal.
When building `figlet`, instead of having a git repo like:
- snapcraft-891d00183565470496c42f4bdaed4388
It would now be:
- snapcraft-figlet-891d00183565470496c42f4bdaed4388
-----

remote-build: include project name in build-id

---

snapcraft/internal/meta/_snap_packaging.py
snapcraft/internal/project_loader/_config.py
snapcraft/project/_sanity_checks.py
tests/unit/project/test_sanity_checks.py
tests/unit/project_loader/test_config.py
tests/unit/test_meta.py

Remove checks that invalidated the use of command-chain without
any other adapter than full.
Instead, transparently move to full-mode if a command-chain is
present in an apps entry.
-----

meta: transparently support command-chain

---

snapcraft/internal/pluginhandler/__init__.py
tests/unit/pluginhandler/test_scriptlets.py

```
Once a project is re-run, snapcraft loses metadata generated
from scripts (i.e. snapcraftctl set-version and set-grade).
Snapcraft itself will reproduce this issue when the sources change:
```
Skipping stage bash-completion (already ran)
Skipping stage snapcraft-libs (already ran)
Skipping stage legacy-snapcraft (already ran)
Skipping stage patchelf (already ran)
Cleaning later steps and re-staging snapcraft ('build' step changed)
Skipping prime bash-completion (already ran)
Skipping prime snapcraft-libs (already ran)
Skipping prime legacy-snapcraft (already ran)
Skipping prime patchelf (already ran)
Priming snapcraft
Compiling pyc files...
Failed to generate snap metadata: 'adopt-info' refers to part 'snapcraft', but that part is lacking the 'parse-info' property.
```
- Since version …
```

scriplets: run override-pull on update_pull

---

requirements.txt
snapcraft/cli/_options.py
snapcraft/cli/ci.py
snapcraft/cli/lifecycle.py
snapcraft/cli/store.py
tests/unit/commands/test_enable_ci.py
tests/unit/commands/test_sign_build.py

cli: drop custom HiddenOption and use click's hidden flag
Hidden flag now available as first-class option in Click 7.0.
While here, consolidate add_build_options()'s two lists,
_BUILD_OPTION_NAMES and _BUILD_OPTIONS, as they are zipped
together anyhow.

click: update to 7.0

---

snapcraft/extractors/appstream.py
tests/unit/extractors/test_appstream.py

Expand the xslt template to support ul nodes with li inside a p node.
LP: #1839197
-----

appstream: xslt support for ul nested in p

---

snapcraft/_store.py
snapcraft/file_utils.py
snapcraft/internal/deltas/_deltas.py
snapcraft/internal/deltas/_xdelta3.py
snapcraft/internal/deltas/errors.py
tests/unit/deltas/test_deltas.py
tests/unit/deltas/test_deltas_xdelta3.py
tests/unit/test_file_utils.py

- Use more prominent error classes.
- Setup typing instead of runtime checks for class implementation.
- Remove duplication of logic.
- Move delta tests to own package.
-----

deltas: code cleanup

---

snapcraft/internal/elf.py
tests/unit/test_elf.py

When coming across invalid ELF files, handle exception thrown by
elftools.  If it's invalid, just silently ignore it, we only care
to analyze valid ELF flies.
Introduce test case to reproduce issue (that now passes).
LP #1838098
-----

elf: handle invalid elf files

---

snapcraft/cli/_options.py
snapcraft/cli/lifecycle.py
snapcraft/internal/errors.py
tests/unit/commands/test_clean.py

When the project is fresh (i.e. not-built, or fully cleaned), the
multipass managed instance will fail to find the project and raise a
FileNotFound exception.  Handle it gracefully (ignore it).
- Add new ProjectNotFound exception, set as reportable because it shouldn't
have unhandled cases surfacing up to the user.
- Add test case which would expose the bug if the build provider was multipass.
It's not for unit testing, but we'll add it regardless.
LP #1839014
-----

cli: handle exception when cleaning a part with a fresh project

---

snapcraft/internal/meta/_snap_packaging.py
snapcraft/yaml_utils.py
tests/unit/test_yaml_utils.py

Also add a unit test for dumping yaml from OctInt
-----

yaml utils: move OctInt from meta

---

snapcraft/cli/env.py
snapcraft/internal/common.py
snapcraft/internal/lifecycle/_runner.py
snapcraft/internal/project_loader/_config.py
tests/unit/lifecycle/test_snap_installation.py
tests/unit/test_file_utils.py

https://github.com/containers/libpod/blob/master/docs/podman-run.1.md
-----

Add support for building inside podman containers

---

snapcraft/plugins/catkin.py
tests/unit/plugins/test_catkin.py

-----
Plugin catkin : forward the `parallel-build-count`/`disable-parallel` options down to the build invocation command.
Replace #2665

Plugin catkin: forward parallel build count

---

spread.yaml
tests/spread/build-providers/multipass-basic/task.yaml
tests/spread/build-providers/multipass-error-handling/task.yaml
tests/spread/tools/restore.sh

- Only install multipass for the tests that need it (they are manual).
- --purge on snap removals to avoid snapshotting.
- More workers for 16.04 on GCE (8->12).
-----

spread tests: minor performance improvements

---

spread.yaml

After accidentally running spread's autopkgtest, an error occurred with
unbound variables.
```
...
Allocating ad-hoc ubuntu-16.04-amd64
/bin/bash: line 18: ADT_ARTIFACTS: unbound variable
...
```
Spread sets -u, which will causes incorrect behavior when checking
against an unset variable:
```
$ set +u
$ if [ -z "${unsetvariable}" ]; then echo "empty"; fi
empty
$ set -u
$ if [ -z "${unsetvariable}" ]; then echo "empty"; fi
bash: unsetvariable: unbound variable
```
Fix it by checking if set.
```
$ setvariable=set
$ if [ -z "${setvariable:-}" ]; then echo "empty"; fi
$ if [ -z "${unsetvariable:-}" ]; then echo "empty"; fi
empty
```
Simply do the same for ADT_ARTIFACTS, and allow the check to happen as
originally intended:
```
2019-08-22 17:34:40 Allocating autopkgtest:ubuntu-16.04-amd64... …
```

spread: fix unbound variable error

---

HACKING.md

The user is unlikely to care about anything but the defaults, especially
when found in the `HACKING` docs. Use `--auto` with the suggested
storage-backend of `dir` for `lxd init`.
-----

docs: quick init for lxd in HACKING.md

---

snapcraft/internal/meta/_snap_packaging.py
snapcraft/internal/meta/desktop.py
tests/unit/meta/test_desktop.py

- move DesktopFile to meta.desktop
- Decouple ExtractedMetadata from DesktopFile.
- Pass gui_dir to .write instead of figuring it out in-method.
-----

meta: decouple DesktopFile logic

---

snapcraft/internal/repo/_deb.py

The `is_package_installed()` function was assuming the package was known to APT. There are cases where this is not true, e.g. `lxd` isn't currently available in Debian.
Rather than having to explicitly `check build_package_is_valid()` first, just return False from `is_package_installed()`. It's almost certainly the answer you want.
-----

internal: unknown apt packages aren't installed

---

snapcraft/cli/remote.py
snapcraft/internal/remote_build/_launchpad.py
tests/unit/remote_build/test_launchpad.py

When initializing LaunchpadClient, lookup user information from
snapcraft config.  If not present, and user not passed in, raise
error to inform user --user is required. I effectively broke
this behavior in 4253354cf3f995da19f1a568ffcaaa3a1c3359d3 because
this was done in login(), but not consistent with push_source_tree().
- Rename self.user -> self._user for consistency.
- Modify login() and push_source_tree() to use saved username.
- Move launchpad init up before worktree preparation so it fails
soonest if --user was required.
- Shuffle config handling bits into _load_snapcraft_config() and
_update_snapcraft_config().
-----

remote-build: error when --user is required

---

tests/spread/plugins/colcon/snaps/colcon-talker-listener/snap/snapcraft.yaml
tests/spread/plugins/colcon/snaps/colcon-talker-listener/src/listener_py/setup.py

-----
A breaking change was recently made to upstream colcon that stopped doing this on behalf of the developers, expecting them to do it for themselves.

spread tests: install package marker into ament index

---

snapcraft/internal/dirs.py

My previous commit 27e56863c576c3f0e5c4a5b15d093ca1619730d7 added
a check to ensure the data dirs were set.  This was done with the
incorrect assumption that one of those paths must occur, and did
not take into account the default values.  The defaults are used
within the development environment when installing snapcraft with pip.
Instead of raising exception, first check for the required schema,
extensions, and keyrings directories. Plugins and legacy snapcraft
directories are not required.
-----

dirs: check for existence of required data directories

---

schema/snapcraft.json
snapcraft/internal/project_loader/_config.py
tests/unit/project/test_schema.py

Enabled building these snap types using the build-base keyword.
It has been determined that until hooks are implemented for the
kernel type, that these snaps should not require a base.
-----

schema: build-base support for the kernel type

---

spread.yaml
tests/spread/extensions/gnome-3-28/task.yaml
tests/spread/extensions/snaps/glib-hello/snap/snapcraft.yaml

Restrict to architectures the content snap is available on.
Clean up summary and use the base logic setup implemented in all the tests.
-----

spread tests: update gnome extension tests

---

snapcraft/internal/project_loader/_extensions/_utils.py
snapcraft/internal/project_loader/_extensions/gnome_3_28.py
tests/unit/commands/test_extensions.py
tests/unit/project_loader/extensions/test_gnome_3_28.py
tests/unit/project_loader/extensions/test_utils.py

This simplifies the logic and removes the need to parse
strings to get the implementation of the Extension class.
-----

extensions: rename extension classes to known names

---

extensions/desktop/gnome/Makefile

This is the target directory for the gnome "platform" content interface plug.
-----

extensions: create the gnome-platform directory

---

snapcraft/internal/project_loader/_extensions/gnome_3_28.py

Provide a better explanation of what the goal of this extension is and
what it does when used, providing a much better output for
`snapcraft extension gnome-3-28`.
-----

extensions: improve docsting (used in the cli)

---

.travis.yml
runtests.sh

Minor refactoring and cleanup for runtests script to make it easier
to follow and remove some of the cruft.
Modify travis config to specify google: for spread.
-----

tests: change default spread provider to lxd outside of travis

---

spread.yaml

Use debug and debug-each to obtain information on when a test fails.
This could be an individual test or the entire (test) project setup.
-----

tests: print journal logs when spread tests fail

---

.travis.yml
tests/unit/sources/test_bazaar.py

This should speed them up, there are integration tests for ensuring
the rest.
-----

tests: completely mock bzr tests

---

.travis.yml
tests/unit/sources/test_mercurial.py

This should speed them up, there are integration tests for ensuring
the rest.
-----

tests: completely mock mercurial tests

---

snapcraft/internal/build_providers/_base_provider.py
tests/unit/build_providers/test_base_provider.py

build providers: inject core18 instead of core

---

snapcraft/internal/remote_build/_launchpad.py

snapcraft on edge is now on core18.
-----

remote build: switch from core to core18

---

.travis.yml
spread.yaml
tests/unit/sources/test_subversion.py

This should speed them up, there are integration tests for ensuring
the rest.
-----

tests: completely mock subversion tests

---

snapcraft/internal/meta/desktop.py
tests/unit/meta/test_desktop.py

Fix for desktop files with multiple sections.
Fix to preserve Exec= arguments.
-----

meta: fixes for desktop file handling

---

snapcraft/internal/repo/snaps.py

is_valid() requires reaching out to the snap store.  If it's
installed and a project dependency, it is presumably valid.
- Reduces some network traffic for users.
- Enables limited offline development when the project depends
on build or content snaps.
-----

snaps: if snap is installed, don't check is_valid()

---

tests/spread/plugins/rust/rust-toolchain/task.yaml

Nightlies do not seem to be generated nightly anymore which breaks
the assumptions the test made.
-----

tests: update rust-toolchain test so it pulls from beta

---

runtests.sh
snapcraft/_store.py
snapcraft/cli/store.py
snapcraft/plugins/_ros/rospack.py
snapcraft/storeapi/_sca_client.py
snapcraft/storeapi/_store_client.py
snapcraft/storeapi/errors.py
tests/fake_servers/api.py
tests/integration/store/test_store_close.py
tests/integration/store/test_store_push.py
tests/integration/store/test_store_status.py
tests/unit/commands/test_push.py
tests/unit/store/test_store_client.py

Switch from releasing  manually to adding the channels intent attribute
from the snap-push endpoint.
https://dashboard.staging.snapcraft.io/docs/api/snap.html#push-a-snap-build-to-the-store
Additional fixes for mypy were added to accomodate the new code.
-----

storeapi: use the channels attribute in push

---

snapcraft/internal/meta/application.py
tests/unit/meta/test_application.py

Avoid an empty command-chain in the apps entry from being set
as a result of using classic confinement for which snapcraft's
core does not prepend its own command-chain.
-----

meta: take no command-chain being prepended into account

---

snapcraft/plugins/cmake.py
tests/unit/plugins/test_cmake.py

-----
Currently the cmake plugin utilizes the `parallel_build_count` attribute from `Project`. This PR switches it over to using the one from the `BasePlugin` to support the `disable-parallel` option. It also verifies that it works with a test.

cmake plugin: support disable-parallel option

---

snapcraft/project/_project_options.py
tests/unit/__init__.py
tests/unit/project_loader/test_environment.py

-----
`multiprocessing.cpu_count` always returns the number of raw hardware CPUs available. However, in the context snapcraft is using it, what is actually desired is the number of _usable_ CPUs (taking cgroups, affinity, etc. into account). For example, if you limit a LXD container to a single CPU, `multiprocessing.cpu_count` will continue to detect the number of CPUs available on the host, not 1.
This PR moves snapcraft away from this, and starts using `os.sched_getaffinity` instead, which detects the CPUs actually available for use by the process.

project: use os.sched_getaffinity instead of multiprocessing.cpu_count

---

TESTING.md
snapcraft/internal/project_loader/_extensions/gnome_3_28.py
tests/unit/project_loader/extensions/test_gnome_3_28.py

-----
The `gsettings` plug is needed for GTK applications to use the correct theme under Wayland. As a result, every GTK application should add this plug, so it seems better to just do it in the extension itself.
https://forum.snapcraft.io/t/gnome-3-28-extension-add-gsettings-to-plugs/13471

extensions: add gsettings plug to gnome-3-28 extension

---

snapcraft/cli/_runner.py
snapcraft/cli/lifecycle.py
tests/spread/legacy/clean/task.yaml

The command line is analyzed by the new code base before re-executing
into the legacy one. The short option scenario for --step in clean got
lost in that refactor.
LP: #1834628
-----

cli: add -s back to clean for legacy

---

mypy.ini
runtests.sh
tests/fake_servers/__init__.py
tests/fixture_setup/_fixtures.py
tests/fixture_setup/_unittests.py
tests/unit/build_providers/__init__.py
tests/unit/plugins/test_cmake.py

mypy.ini: set python version to 3.6
tests: minor fixups for mypy to run successfully
runtests: add mypy coverage of unit tests for static target

mypy: add coverage to tests

---

tests/unit/test_errors.py

Triggered by merging the mypy coverage and SnapcraftException
bits.  The SnapcraftException had a mypy issue in test_errors:
(__init__ must return None).
-----

tests: fix mypy error with test_errors.py

---

snapcraft/internal/common.py
snapcraft/internal/elf.py
snapcraft/internal/lifecycle/_runner.py
snapcraft/internal/meta/__init__.py
snapcraft/internal/meta/_snap_packaging.py
snapcraft/internal/meta/application.py
snapcraft/internal/meta/command.py
snapcraft/internal/meta/errors.py
snapcraft/internal/meta/hooks.py
snapcraft/internal/meta/plugs.py
snapcraft/internal/meta/slots.py
snapcraft/internal/meta/snap.py
snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/project_loader/_config.py
snapcraft/plugins/crystal.py
snapcraft/project/_project.py
snapcraft/project/_project_options.py
tests/fixture_setup/_fixtures.py
tests/spread/general/unicode-metadata/expected_snap.yaml
tests/unit/meta/test_application.py
tests/unit/meta/test_command.py
tests/unit/meta/test_hook.py
tests/unit/meta/test_plugs.py
tests/unit/meta/test_slots.py
tests/unit/meta/test_snap.py
tests/unit/test_elf.py
tests/unit/test_options.py

This removes the false-positive warnings associated with use of the gnome extension (and hopefully any users of content snaps).
Tested with gnome-calculator using gnome extension:
https://github.com/cjp256/gnome-calculator/commits/master
Still needs some tests, but open for feedback! :)
-----

incorporate content provider snaps in dependency resolution

---

snapcraft/internal/project_loader/_parts_config.py
tests/unit/project_loader/test_environment.py

-----
Currently it's impossible to define a `build-environment` that uses variables defined by snapcraft itself (e.g. `$SNAPCRAFT_PART_INSTALL`), since the `build-environment` is evaluated before snapcraft's environment. Fix this by simply switching the order.

project_loader: load build-environment after snapcraft environment

---

snapcraft/internal/elf.py
tests/bin/elf/ldd
tests/fixture_setup/_unittests.py
tests/unit/test_elf.py

I believe that prior testing involved ldd picking up the
host-installed binaries to properly catch which libs are missing.
Handle the case where ldd may return "not found" or some other
invalid resolution.  In those cases, initialize soname_path to soname.
- Update load_dependencies so that it does not filter out libraries
that are not found.  If done, the returned set isn't very useful
for determining missing dependencies (unless they managed to get
found on host, which is why it has worked thus far).
- Refactor ldd into its own method and update it to parse ldd
output more reliably.
- Add unit test coverage for missing libraries in ldd output.

elf: handle missing dependencies not found on system

---

snapcraft/internal/deprecations.py
snapcraft/internal/meta/command.py
tests/unit/meta/test_command.py
tests/unit/meta/test_command_mangle.py

Warn when a wrapper is needed due to the command used or when the command
has changed to something more compatible with snapd's accepted format.
-----

meta: warn about command mangling

---

snapcraft/_store.py
snapcraft/storeapi/errors.py
tests/fake_servers/api.py
tests/unit/commands/test_push.py
tests/unit/commands/test_push_metadata.py
tests/unit/store/test_store_client.py

This class should make it easy to query the error listing
and use the provided messages. It is meant to be used by
composing in the corresponding error classes. This commit
adds it to StorePushError.
StorePushError now properly handles resource-not-found and
resource-forbidden.
-----

storeapi: add StoreErrorList to handle store errors

---

snapcraft/_store.py
tests/unit/commands/test_promote.py
tests/unit/commands/test_push.py
tests/unit/commands/test_push_metadata.py
tests/unit/commands/test_release.py

- Use obvious decorators for login
- Add type annotations and force keyword arguments in StoreClientCLI
-----

cli: clean up StoreClientCLI

---

snapcraft/_store.py
snapcraft/storeapi/errors.py
tests/unit/commands/test_push.py

Add registration to the push workflow via use echo.confirm
by adding a decorator to the push related methods that catches
the resource-not-found error code and prompts for registration
before trying to push again.
LP: #1805211
-----

cli: use click utilities for registering on push

---

extensions/desktop/common/desktop-exports
snapcraft/internal/project_loader/_extensions/gnome_3_28.py
tests/unit/project_loader/extensions/test_gnome_3_28.py

-----
This PR enables snaps to use the gjs bundled in the gnome runtime snap ([MR](https://gitlab.gnome.org/Community/Ubuntu/gnome-3-28-1804/merge_requests/1) accepted, available in revision 87 and up).
I tested this with the foliate snap: https://github.com/snapcrafters/foliate/tree/gjs-via-gnome-extension
This removes a lot of boilerplate and reduces the `foliate` snap size from  `92M` to `324K`!
*Note:  `./runtests.sh static` gives the following error at the end, but this also happens on master.*
```
tests/unit/project_loader/grammar/test_compound_statement.py:223: error: Module has no attribute "errors"
tests/unit/project_loader/grammar/test_compound_statement.py:235: error: Module has no attribute "errors"
```

extensions: support using gjs from gnome runtime

---

snapcraft/internal/meta/plugs.py
snapcraft/project/_project.py
tests/unit/meta/test_plugs.py

meta: support the case of a plug without a default provider

---

snapcraft/extractors/_metadata.py
snapcraft/extractors/appstream.py
tests/unit/extractors/test_appstream.py

-----
This PR extracts `title` and `version` from AppStream's `name` tag and
from the `version` property of the first `release` tag.
According to the AppStream docs:
> `<name/>`: A human-readable name for this software component.
> Each release of the software component should have a `<release/>`
> tag describing it, but at least one release child must be present
> for the current release of the software. **The release children
> should be sorted in a latest-to-oldest order to simplify reading
> the metadata file.**
[source](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases)
This PR assumes the AppStream follows the spec in that the first `<release>` element describes the latest release. It's possible to check the `date` and `timestamp` properties of each …

appstream: extract title and version

---

TESTING.md
snapcraft/extractors/appstream.py
tests/unit/extractors/test_appstream.py

-----
Some desktop launchers are not found by Snapcraft because their AppStream file doesn't include any `launchable` entries and the component id does not end in `.desktop`.
This PR uses component id + ".desktop" as possible desktop file id if no launchables are found and the component id does not have `.desktop` suffix.
This was originally proposed in https://bugs.launchpad.net/snapcraft/+bug/1778546 but the initial fix did not include appending the suffix.
See https://github.com/snapcrafters/foliate/pull/3/files for an example of a snap using this feature.

 appstream: support legacy ids without desktop suffix 

---

snapcraft/internal/errors.py
tests/unit/test_errors.py

- Add SnapcraftReportableException helper class for reportable
errors, which simply flips the default value for get_reportable().
- Convert MissingStateClean, StepOutdatedError,
SnapcraftEnvironmentError, SnapcraftDataDirectoryMissingError,
and SnapcraftMissingLinkerInBaseError and associated tests.
- Add missing test for SnapcraftDataDirectoryMissingError.
- Update tests to verify expected "reportable" value as well.
The error messages are being shortened and I am also using
this opportunity to simplify them (and the resolution messages).
For example, when StepOutdatedError occurs, instead of suggesting
that the user clean just one part/step when something is out of date,
ask them to instead clean the whole project.  Something unusual has
happened and it's probably a good idea to clean …

errors: migrate handful of errors to SnapcraftException

---

docker/beta.Dockerfile
docker/candidate.Dockerfile
docker/edge.Dockerfile
docker/stable.Dockerfile

```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
```
-----

docker: use apt-get to avoid warnings

---

snapcraft/project/_project.py

A full sha1 hash is admittedly a bit excessive, truncate
it to 6 characters.  Security is irrelevant and collisions
are not a realistic concern for these use cases.
Shorten it before it proliferates beyond remote-build :)
-----

project: truncate project directory hash

---

snapcraft/internal/project_loader/_extensions/gnome_3_28.py
tests/unit/project_loader/extensions/test_gnome_3_28.py

This is breaking the iso image builds
-----

"snap debug validate-seed" fails if the slot is specified in the default-provider.

---

setup.py
snapcraft/file_utils.py
snapcraft/internal/remote_build/_launchpad.py
snapcraft/internal/remote_build/_worktree.py
snapcraft/internal/sources/__init__.py
tests/unit/remote_build/test_launchpad.py

Requires: https://github.com/snapcore/snapcraft/pull/2759
Tested against: https://github.com/cjp256/figlet/tree/use-install

remote-build: initial Windows support

---

snapcraft/internal/project_loader/_extensions/kde_neon.py
tests/unit/project_loader/extensions/test_kde_neon.py

The default-provider should just be the content snap name.
-----

Snapd doesn't actually honor the slot specified in the default-provider.

---

snapcraft/internal/project_loader/_extensions/gnome_3_28.py
snapcraft/internal/project_loader/_extensions/kde_neon.py
tests/unit/project_loader/extensions/test_kde_neon.py

-----
This PR adds the common cursor, icon and sound themes to the `kde-neon` extension using the `gtk-common-themes` content snap. Unlike its name implies, the cursor, icon and sound themes are also applicable to Qt/KDE applications.
This fixes the issue where applications using this extension have a weird pixelated cursor on default Ubuntu.
I tested this by building the Krita snap using this extension: https://invent.kde.org/merlijnsebrechts/krita/blob/neon-extension/packaging/linux/snap/snapcraft.yaml Without this PR, the cursor is correct on Kubuntu, but incorrect on Ubuntu. With this PR, the cursor is correct on both flavors.

extensions: kde-neon: add icon and sound themes

---

snapcraft/internal/meta/_manifest.py
snapcraft/internal/pluginhandler/__init__.py

Sort `build-packages`, `stage-packages`, `installed-packages`,
`installed-snaps`,  and `build-snaps`.
-----

manifest: sort package and snap lists for consistency

---

snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_snap.py
tests/unit/build_providers/test_base_provider.py
tests/unit/build_providers/test_snap.py

The snapd snap is nimble and small when compared to having to add the core
snap always (an additional burden from always needing to add "core18" to
support snapcraft).
-----

build providers: inject snapd snap for latest feature availability

---

snapcraft/internal/repo/snaps.py
tests/unit/repo/test_snaps.py

Refreshing to a channel that does not exist raised a KeyError, move
the is_valid check to be part of the class and generally catch the
issue there instead of from the helper methods.
-----

repo: convey proper error message when refreshing to invalid channel

---

snapcraft/internal/errors.py

The exception will not show any effective quotes in the command.
This uses shlex.quote() to print a more accurate description of
the command that failed.
-----

erorrs: preserve quotes when printing SnapcraftPluginCommandError

---

snapcraft/internal/remote_build/_launchpad.py
snapcraft/internal/remote_build/errors.py
tests/unit/remote_build/test_errors.py
tests/unit/remote_build/test_launchpad.py

Introduce `LaunchpadHttpsError` for cases where connectivity
fails to be established to Launchpad.
Introduce `_lp_load_url()` wrapper to handle connection failures.
If fetch error occurs, retry login and re-fetch URL.
Includes unit tests to validate new functionality.
-----

remote-build: improve resiliency for https connection issues

---

snapcraft/project/_project_info.py
snapcraft/yaml_utils.py
tests/unit/test_yaml_utils.py

Rename to `load_yaml_file`.
This version of load has the most complete error handling,
converting the assortment of yaml errors into a YamlValidationError.
We will re-use this logic for snapcraft's configuration file.

yaml_utils: move _load_yaml from project for re-use (and add tests)

---

tests/integration/store/test_store_push.py

When pushing and releasing, there is no "Ready to release" message anymore
as the store now handles the release on behalf of snapcraft with the new
calls which were introduced in f3c17a99b4e87a5412d80e64da4f3f1e9b3146d7
This updates the tests to work against the staging Snap Store.
-----

tests: update the push and release tests for staging

---

tests/spread/plugins/rust/classic/task.yaml
tests/spread/plugins/rust/conditional/task.yaml
tests/spread/plugins/rust/legacy-pull/task.yaml
tests/spread/plugins/rust/rebuild/task.yaml
tests/spread/plugins/rust/run/task.yaml

The stable toolchain is missing components in order to correctly test:
error: some components unavailable for download for channel stable: 'clippy', 'rustfmt'
-----

tests: skip spread tests for rust on s390x

---

extensions/desktop/common/desktop-exports
extensions/desktop/common/init

-----
Calling `mkdir -p` is relatively expensive because it starts an external process. This commit uses bash to check if the directory exists to avoid calling `mkdir -p` altogether in a hot start. This saves ~20% execution time in a hot start and has no significant impact on a cold start.
As an example; the hot startup time of [the SDLPoP snap using `gtk-3-28-1804`](https://github.com/galgalesh/sdlpop/tree/gnome-extension) with fix:
```
0.069s /snap/core/7917/usr/lib/snapd/snap-confine
0.008s /usr/bin/realpath
0.008s /usr/bin/realpath
0.008s /usr/bin/realpath
0.008s /usr/bin/realpath
0.008s /usr/bin/realpath
0.008s /usr/bin/realpath
0.009s /usr/bin/realpath
0.008s /bin/rm
0.147s /snap/sdlpop/x1/snap/command-chain/desktop-launch
```
without fix:
```
0.071s …
```

extensions: speed up desktop-launch by not calling mkdir -p

---

setup.py
snapcraft/cli/_review.py
snapcraft/cli/store.py
snapcraft/internal/review_tools/__init__.py
snapcraft/internal/review_tools/_runner.py
snapcraft/internal/review_tools/errors.py
tests/unit/commands/test_push.py
tests/unit/review_tools/test_errors.py
tests/unit/review_tools/test_runner.py

Consider only snap v2 lint warnings and errors. On discovery of any issues,
emit warnings, but do not fail as we have no easy way to override
any of these issues.
-----

cli: run review tools before pushing to the store if available

---

tests/unit/commands/test_remote.py

Add some tests test for `remote-build` and `build-on`
arch handling.
-----

remote-build: add initial command unit tests

---

snapcraft/internal/pluginhandler/__init__.py
tests/unit/pluginhandler/test_pluginhandler.py

Use of build_packages and build_snaps throughout code assumes a list
of packages.  Prevent proliferation of the raw unprocessed
properties in the pull state info by first using the grammar
processor (as is done for stage packages).
Add a couple of tests for verification.
-----

pluginhandler: use well-formed build package/snap lists

---

spread.yaml
tests/spread/plugins/nil/basic/task.yaml
tests/unit/__init__.py

Provide additional test coverage of manifest-related changes.
-----

tests: enable SNAPCRAFT_BUILD_INFO for spread

---

snapcraft/internal/meta/snap.py
tests/unit/meta/test_meta.py
tests/unit/meta/test_snap.py

When reading the config data dictionary, convert the list to a set.
The `assumes` property is defined as a set in Snap meta, but derives
from a list in the the snap meta.  This causes an exception when
using `command-chain`, but `command-chain` is not already in
the `assumes` (due to the use of Snap's usage of `.add()` on the
set, which is not available for lists).
Add a test for coverage/verification.
-----

meta: ensure Snap's `assumes` is initialized as a set

---

requirements.txt
snapcraft/internal/errors.py
snapcraft/internal/meta/_manifest.py
snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/repo/_base.py
snapcraft/internal/repo/_deb.py
snapcraft/internal/states/_prime_state.py
snapcraft/internal/xattrs.py
tests/unit/lifecycle/test_lifecycle.py
tests/unit/pluginhandler/test_pluginhandler.py
tests/unit/project_loader/inspection/test_lifecycle_status.py
tests/unit/project_loader/inspection/test_provides.py
tests/unit/test_errors.py
tests/unit/test_xattrs.py

Use extended attributes to implement a low-overhead file-origin
tracking solution.  As debs are extracted, they are marked with
an attribute that indicates their source origin.
Primed files that carry the marker are expected to have originated
from the source package that it was extracted from.
Add `xattr` version 0.9.6 to requirements.txt.
-----

manifest: track and annotate `primed-stage-packages`

---

snapcraft/cli/_command.py
snapcraft/cli/_options.py
snapcraft/cli/lifecycle.py
snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_lxd/_lxd.py
snapcraft/internal/build_providers/_multipass/_multipass.py
tests/spread/build-providers/host-env-passthrough/task.yaml
tests/spread/build-providers/lxd-env-passthrough/task.yaml
tests/spread/build-providers/snaps/env-passthrough/snap/snapcraft.yaml
tests/unit/build_providers/__init__.py
tests/unit/build_providers/lxd/test_lxd.py
tests/unit/build_providers/test_base_provider.py
tests/unit/cli/test_options.py
tests/unit/commands/__init__.py

Some modules support configuration of http(s) proxies today (e.g.
ant, maven, nodejs) - but they are only honoured if building
with host provider and the environment variables are already in
the environment.
Add two explicit build options for http_proxy and https_proxy,
with matching environment variables to support typical application
behavior.
Only add these to the environment if provider is one of 'lxd',
'multipass', 'host', or 'managed-host'. Otherwise, either:
(a) warn if found in the user's environment.
(b) error if not found in environment, and therefor must have
been configured with an explicit command-line option.
Add tests for coverage of get_build_environment_flags() with
new http_proxy and https_proxy handling.

cli: add support for 'http-proxy' and 'https-proxy' parameters

---

extensions/desktop/common/desktop-exports

-----
Some icon themes, such as cursor-only themes, can't have a cache. However, desktop-exports still tries to create a cache for every icon theme, which is surprisingly expensive. It takes up to 30% of the time of a cold desktop-launch run. This is partly due to the script creating additional directories and softlinks during this process.
This commit skips icon cache creation for everything in the theme and runtime snaps because those should already contain caches.
With this commit, the cold start time of the desktop-launch script is reduced by ~30%.
The KDE Neon apps also have an improved boot time with this fix, although it's less pronounced.
| App | without fix | with fix | reduction |
| --- | --- | --- | --- |
| [SDLPoP](https://github.com/galgalesh/sdlpop/tree/gnome-extension) | …

extensions: skip icon cache creation for theme and runtime snaps 

---

snapcraft/cli/remote.py

It was pointed out that something being public has a very different connotation
to something being publicly available. In this case the code or artifacts do
not necessarily become public but publicly available.
-----

cli: improve the remote-build upload messaging

---

.travis.yml

Fixes failure with:
```
shellcheck: src/ShellCheck/Analytics.hs:1825:10-27:
No instance nor default method for class operation mappend
```
It's probably not a good idea to use the edge channel for CI
when not required, so just pivot to stable channel.
-----

travis: use `stable` channel for shellcheck snap

---

snapcraft/internal/project_loader/_extensions/kde_neon.py

-----
This PR only affects a comment - no functionality changes.
The comment block at the top of the kde_neon extension mentioned including the gsettings plug when this is not actually the case.

Remove gsettings from comment in kde extension

---

snapcraft/plugins/conda.py
tests/unit/plugins/test_conda.py

Replace _MINICONDA_URL and _MINICONDA_UNKNOWN_URL dictionaries
with a helper function using a single format string
and dictionary to lookup known checksums.
This is motivated by an uprev of mypy which stumbles on
the type checking:
```
snapcraft/plugins/conda.py:111:
error: Item "None" of "Optional[str]" has no attribute "format"
snapcraft/plugins/conda.py:116:
error: Value of type "object" is not indexable
snapcraft/plugins/conda.py:118:
error: Value of type "object" is not indexable
```
This helper was introduced as `_get_miniconda_source()`, and
CondaPlugin's method was renamed to `_get_miniconda_script()`
to better indicate its behavior.
-----

conda plugin: simplify source url/checksum handling

---

snapcraft/internal/repo/_deb.py

It returns a string path, not None.
Addresses mypy uprev errors.
-----

repo: fix fetch_binary()'s return type for deb repo

---

requirements-devel.txt
snapcraft/internal/lifecycle/_status_cache.py
snapcraft/project/_project.py
snapcraft/project/_project_info.py

lifecycle: add optionals to StatusCache reports
project: label get_build_base() return as optional
project: ignore project.info's Optional[ProjectInfo] type
requirements-devel: uprev mypy to 0.740
The ignore on ProjectInfo is an unfortunate hack, but I would like to see it fixed properly by going down the road of something like:
https://github.com/snapcore/snapcraft/pull/2818

uprev mypy to 0.740! (and address remaining errors)

---

snapcraft/internal/build_providers/_snap.py
spread.yaml
tests/spread/build-providers/lxd-env-passthrough/task.yaml
tests/unit/build_providers/test_snap.py

When setting the experimental.snapd-snap to true, the system goes into a
deadlock expecting the snapd snap to be there. Given that the snapd snap
is not install when core is injected it causes a deadlock on the build
environment. Avoid the situation by only setting this flag when the snapd
snap is to be installed.
-----

build providers: only set the snapd flag when installing snapd

---

requirements.txt
snapcraft/internal/xattrs.py

I did not realize that python added xattrs to Linux's `os` package
in python 3.3.  Use that instead of the xattrs library.
https://docs.python.org/3/library/os.html#linux-extended-attributes
-----

xattrs: switch to python's os package for reading/writing xattrs

---

snapcraft/extractors/appstream.py
tests/unit/extractors/test_appstream.py

The Markdown used by the Snap Store does not yet support "verbatim"
or code-like formatting while Appstream does.
The new XSLT snippet is added to ensure these code tags are not
swallowed during the transformation.
-----

appstream extractor: add support for code

---

snapcraft/internal/errors.py
snapcraft/internal/xattrs.py
tests/unit/test_errors.py

As SNAPCRAFT_BUILD_INFO is not always enabled, ignore errors
setting xattrs to record origin stage packages.  This data
will not be used if there is no manifest being generated.
This should prevent unnecessary errors being raised to the user
if their file system doesn't support xattrs (or are otherwise
limited from reading/modifying them).
Introduce XAttributeError() to improve the error messaging
to the user should reading/writing xattrs fail.  Mark as
reportable for now, but ultimately this should be False once
the feature is stable and extensively used by the community.
-----

xattrs: ignore errors if SNAPCRAFT_BUILD_INFO is unset

---

snapcraft/cli/remote.py
snapcraft/internal/remote_build/_launchpad.py
snapcraft/internal/remote_build/errors.py
tests/unit/commands/test_remote.py
tests/unit/remote_build/test_launchpad.py

A few other tweaks/cleanup while we're here.
remote-build: remove requirement to specify user …
Thanks to @cjwatson for the great idea! :+1: 
https://bugs.launchpad.net/snapcraft/+bug/1852482
remote-build: login automatically when initialized …
remote-build: fix AcceptPublicUploadError option …
remote-build: remove _waiting from LaunchpadClient …

remote-build: remove need to specify user

---

snapcraft/plugins/colcon.py
tests/unit/plugins/test_colcon.py

-----
This PR adds support for the newest ROS 2 release, Eloquent Elusor. For more information about the release, see https://github.com/ros2/ros2/issues/734.

colcon plugin: support ROS 2 Eloquent

---

snapcraft/internal/remote_build/_launchpad.py
snapcraft/internal/sources/_git.py
snapcraft/internal/sources/errors.py
tests/unit/sources/test_errors.py
tests/unit/sources/test_git.py

remote-build: use easier to read git commit message format
sources: introduce GitCommandError for improved user-facing errors
sources: improve command quoting in SnapcraftPullError
sources: disable gpg signing for git commit
@flexiondotorg reported his git config enabled GPG signing which broke remote-build's use of git.
This series disables gpg-signing as well as improves user-facing messaging in a few areas so the user can more easily determine what went wrong.

remote-build: gpg-signing and usability fixes

---

snapcraft/plugins/rust.py
tests/unit/plugins/test_rust.py

RUSTUP_HOME is typically ~/.rustup
CARGO_HOME is typically ~/.cargo
They are both currently set to ~/.cargo.
It has been reported that overlapping the two may have side
effects.  While I have not yet reproduced this, it's probably
a good idea to decouple the two directories anyways.
LP: #1852545
-----

rust plugin: split RUSTUP_HOME and CARGO_HOME

---

schema/snapcraft.json
snapcraft/internal/meta/hooks.py
snapcraft/internal/meta/snap.py
tests/unit/meta/test_hook.py
tests/unit/meta/test_snap.py

Enables command-chain regardless of base, but does not actively enable or otherwise use it. It just passes it through if the user configures it in their snapcraft yaml.

hooks: enable command-chain

---

snapcraft/_baseplugin.py

Print a more accurate representation of the command being executed.
Similar to other runs throughout the codebase.
-----

base plugin: use shlex quoting for logged command in run()

---

snapcraft/project/errors.py

Remove SanityCheckError and CommandChainWithLegacyAdapterError.
-----

project: remove unused errors

---

snapcraft/plugins/_ros/wstool.py
tests/spread/plugins/catkin/catkin-with-python/task.yaml
tests/spread/plugins/catkin/snaps/catkin-with-python-part/snap/snapcraft.yaml
tests/unit/plugins/ros/test_wstool.py

-----
The Catkin plugin utilizes wstool to support rosinstall files. While wstool is fetched into its own install area so as to not contaminate either the host or the snap, it doesn't properly use the git that is fetched along with it. This means that merging rosinstall files that include git repositories only works if git is already installed on the host. If the host doesn't include git, it errors out.
This PR properly sets the variables necessary to run git from wstool's install area, thereby no longer relying on the host already having git installed.

wstool: don't rely on host git

---

snapcraft/cli/remote.py
snapcraft/internal/remote_build/_launchpad.py
snapcraft/internal/remote_build/errors.py
tests/unit/remote_build/test_launchpad.py

The error was ambiguous when the timeout was hit, and there was no recourse for the user.
Re-instate a configurable timeout as `--launchpad-timeout` but apply it to both the start_build and monitor_build as a deadline.  When Launchpad is slow, it may take some time to process the request, but as long as its Pending, we keep waiting for a response (unless deadline is hit).

remote-build: configurable timeout/deadline for starting and monitoring build

---

snapcraft/internal/meta/_snap_packaging.py
tests/spread/general/adapter/expected_snap.yaml
tests/spread/general/adapter/snaps/adapter-tests/snapcraft.yaml
tests/spread/general/adapter/snaps/adapter-tests/test-cmd
tests/spread/general/adapter/task.yaml

When adapter == "none", snapcraft should not modify the
command or command-chain.  However snapcraft presently
ignores the adapter setting when it comes time to set
the command-chain.
Instead, honor when adapter is "none".
With these changes, given a snapcraft yaml:
```
<snipped>
apps:
adapter-none:
command: test-cmd
adapter: none
adapter-full:
command: test-cmd
adapter: full
adapter-legacy:
command: test-cmd
adapter: legacy
wrapped-default:
command: test-cmd --test "@"
<snipped>
```
Will now yield:
```
apps:
adapter-full:
command: test-cmd
command-chain:
- snap/command-chain/snapcraft-runner
adapter-legacy:
command: test-cmd
command-chain:
- snap/command-chain/snapcraft-runner
adapter-none:
command: test-cmd
wrapped-default:
command: command-wrapped-default.wrapper
command-chain:
- …
```

meta: do not set snapcraft-runner when adapter is "none"

---

snapcraft/internal/meta/_snap_packaging.py
snapcraft/internal/meta/application.py
snapcraft/internal/project_loader/__init__.py

Introduce enum ApplicationAdapter to use instead of strings.
Remove the unused `Adapter` equivalent found in project loader.
-----

meta: convert Application's `adapter` from string to enum

---

snapcraft/internal/meta/snap.py

Make Snap fully configurable upon init.
-----

meta: enable Snap to be fully initialized with __init__ parameters

---

snapcraft/internal/common.py

To support debugging, update run() to create a script that accounts
for the parameters `cwd` and `env` passed along to check_call(),
stripping those parameters (if present).
No longer remove script generated, but instead persist it in
/tmp/snapcraft-<pid>/run-<#>.sh for optional debugging.
Now a developer can look at the script and re-run it independently of
snapcraft for debugging/development purposes.
-----

common: generate run scripts which can execute independently

---

tests/spread/plugins/plainbox/snaps/provider-basic/snap/snapcraft.yaml
tests/spread/plugins/plainbox/snaps/provider-with-deps/snap/snapcraft.yaml

spread tests: use source-depth: 1 for plainbox tests

---

snapcraft/plugins/_python/_pip.py
snapcraft/plugins/python.py
tests/spread/plugins/python/intra-dependency/task.yaml
tests/spread/plugins/python/snaps/python-with-source-subdir-dependencies/mod1/setup.py
tests/spread/plugins/python/snaps/python-with-source-subdir-dependencies/mod2/setup.py
tests/spread/plugins/python/snaps/python-with-source-subdir-dependencies/snap/snapcraft.yaml
tests/unit/plugins/python/test_pip.py
tests/unit/plugins/test_python.py

Try to install setup.py with dependencies satisfied from:
- python-packages
- requirements
If that fails, resort to using PyPI to satisfy missing install_requires
from setup.py
LP: #1841861
-----

python plugin: first try processing setup.py without PyPI

---

snapcraft/cli/_errors.py
tests/unit/cli/test_errors.py

If the user chooses to kill snapcraft prematurely, that's OK
but it shouldn't be reported to Sentry.
Squelches SNAPCRAFT-1D
-----

cli: do not report KeyboardInterrupt errors

---

snapcraft/internal/meta/snap.py
tests/spread/general/adapter/expected_snap.yaml
tests/unit/meta/test_meta.py

`prepend_command_chain` was not checked when determining the need
for assuming command-chain.
- Add & update a test to ensure coverage of `assumes`.
- Check for use of `prepend_command_chain`.
-----

meta: assume command-chain fix for prepending snapcraft-runner

---

snapcraft/internal/build_providers/_multipass/_multipass_command.py
tests/spread/build-providers/multipass-basic/task.yaml
tests/spread/build-providers/multipass-error-handling/task.yaml
tests/unit/build_providers/multipass/test_multipass_command.py

Multipass 1.0 has been released to the stable channel. Consume multipass from
there from now on.
-----

build providers: use multipass from stable

---

requirements.txt
snap/snapcraft.yaml

pylxd is designed in such a way that it will display warnings every
attribute coming from the server that is unknown to the client.
pylxd 2.2.10 adds a way to inhibit these warnings.
-----

snap: set PYLXD_WARNINGS to inhibit unknown LXD attribute warnings

---

tests/spread/general/adapter/task.yaml

The expected_snap.yaml includes the architecture definition,
which breaks when building on other architectures.  Since
adapter isn't relevant to arch, simply limit the tests to amd64.
-----

spread tests: limit adapter test to amd64

---

snapcraft/internal/elf.py
tests/fixture_setup/_unittests.py
tests/unit/pluginhandler/test_pluginhandler.py

- Set defaults in __init__ and update in _extract_attributes().
- Operate directly on self instead of returning a massive
tuple.
- Rename to _extract_attributes() and drop `path` argument
already available in self.
- Update fake elf fixtures.
-----

elf: remove return parameters for ElfFile's _extract()

---

snapcraft/internal/meta/plugs.py
snapcraft/internal/meta/slots.py
snapcraft/internal/meta/snap.py
tests/unit/meta/test_plugs.py
tests/unit/meta/test_slots.py

Although undocumented, the plug and slot objects may in
fact be a string, such as the case here:
https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/modem-manager/tree/snapcraft.yaml#n16
If the object is a string, use that string as the interface.
To ease the handling of this, we introduce cls.from_object() for
Slot and Plug to handle None, string, and dict cases. Snap will
now use these methods when populating the slots and plugs, instead
of cls.from_dict().
Add tests for coverage of from_object() and the string case.
LP #1859806
-----

meta: handle plug & slot string objects

---

snapcraft/internal/meta/plugs.py
snapcraft/internal/meta/slots.py
snapcraft/internal/meta/snap.py
tests/unit/meta/test_plugs.py
tests/unit/meta/test_slots.py

Although undocumented, the plug and slot objects may in
fact be a string, such as the case here:
https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/modem-manager/tree/snapcraft.yaml#n16
If the object is a string, use that string as the interface.
To ease the handling of this, we introduce cls.from_object() for
Slot and Plug to handle None, string, and dict cases. Snap will
now use these methods when populating the slots and plugs, instead
of cls.from_dict().
Add tests for coverage of from_object() and the string case.
LP #1859806
-----

[3.9 backport] meta: handle plug & slot string objects

---

snapcraft/internal/meta/snap.py
tests/unit/meta/test_meta.py
tests/unit/meta/test_snap.py

When reading the config data dictionary, convert the list to a set.
The `assumes` property is defined as a set in Snap meta, but derives
from a list in the the snap meta.  This causes an exception when
using `command-chain`, but `command-chain` is not already in
the `assumes` (due to the use of Snap's usage of `.add()` on the
set, which is not available for lists).
Add a test for coverage/verification.
Fixes SNAPCRAFT-16C
-----

[3.9-backport] meta: ensure Snap's `assumes` is initialized as a set

---

snapcraft/internal/meta/snap.py

Ignore plugs without defined provider in get_provider_content_directories().
The type is declared as optional and mypy uprev errors on the fact that
provider could be None.
If processing a plug without a provider, just skip it and move on.
-----

[backport] meta: fix missing provider case for get_provider_content_directories()

---

snapcraft/internal/project_loader/_extensions/_utils.py
tests/unit/project_loader/extensions/test_utils.py

When merging "build-environment", merge_lists will fail
because OrderedDict is unhashable when calculating the "seen"
set.
- When merging lists, just append the user-defined list after the
extension-defined list.  If the merged list is is comprised of just
strings, strip duplicates.
This ordering has changed from previous behavior, where user-defined
items were first, then the extension.  This ripples to multiple extensions
and seeing the culmative effects (i.e. ExtensionOrderConsistencyTest).
- Add tests for coverage for `build-environment`.

extensions: change extension merge-strategy to fix build-environment

---

snapcraft/plugins/catkin.py
tests/unit/plugins/test_catkin.py

This PR fixes a bug when calling snapcraft with `--destructive-mode`.
Some installation paths from the host machine leak into the list of paths considered by the catkin plugin. It results in having dependencies being found (in the host path) and thus not being installed by the plugin in the expected 'parts' path.
In the 'pull' step, prior to building, the ROS dependencies of the package(s) to be built are retrieved.
When checking whether a dependency is available 'locally' or should be installed, the `catkin_find` tool will look into workspaces exported in `CMAKE_PREFIX_PATH` among other paths:
[`catkin_find` calls `find_in_workspaces`](https://github.com/ros/catkin/blob/kinetic-devel/bin/catkin_find#L41) which in turns [calls `get_workspaces`](https://github.com/ros/catkin/blob/kinetic-de …

Catkin plugin: consider only 'local' workspaces

---

snapcraft/internal/meta/plugs.py
snapcraft/internal/meta/slots.py
snapcraft/internal/meta/snap.py
tests/unit/meta/test_plugs.py
tests/unit/meta/test_slots.py
tests/unit/meta/test_snap.py

Snapcraft recently started always writing the long-form
of plugs for consistency, where the `interface` attribute
is always defined.
Unfortunately this seems to have tripped up a bug in review-tools
that won't likely be fixed for a while.  This commit restores
the 3.8 behavior to ensure the output snap.yaml matches the syntax
used in the snapcraft.yaml.
-----

plugs/slots: match output format read in snapcraft.yaml

---

docker/beta.Dockerfile
docker/candidate.Dockerfile
docker/edge.Dockerfile
docker/stable.Dockerfile

Also update comments for correctness and syntax.
-----

docker: add core18 snap that snapcraft now uses as a base

---

snapcraft/internal/lifecycle/_runner.py
snapcraft/internal/meta/snap.py
snapcraft/internal/repo/snaps.py
tests/spread/general/content-interface-provider-found/snaps/provider/snap/snapcraft.yaml
tests/spread/general/content-interface-provider-found/task.yaml
tests/spread/general/content-interface-provider-not-found/snaps/provider/snap/snapcraft.yaml
tests/spread/general/content-interface-provider-not-found/task.yaml

Snapcraft gained the ability to check for artifacts from snaps listed as plugs
when using the content interface.
The side effect, is that the snap needs to be published on the main Snap Store,
this is a requirement brand stores cannot meet, so instead of failing,
Snapcraft resorts to warning instead.
-----

lifecycle: only warn when a default provider snap is missing

---

snapcraft/internal/elf.py
tests/unit/test_elf.py

The elf type may be used for decision making when handling
executables.  This will be useful for determining what to do
when stripping executables, as different types should be handled
differently.
Use the enum strings provided by pyelftools instead of integer
value.  Initialize to "ET_NONE", but always read the entry
when extracting attributes from file.
-----

elf: read ELF type when extracting attributes

---

snapcraft/internal/meta/_snap_packaging.py
tests/fixture_setup/_fixtures.py
tests/unit/meta/test_snap_packaging.py

Snapcraft previously generated wrappers for most commands.  Once
snapcraft became more conserative about generating unnecessary wrappers,
issues began to surface with regard to PATH being set incorrectly
for classic snap apps that did not use shell.
To work around the issue, this commit adds an empty snapcraft-runner to
the command-chain for all apps, where they typically would have none.
Once this issue is resolved in snapd, we can probably remove this
workaround.
LP#: 1860369
-----

meta: always generate snapcraft-runner to workaround classic PATH bug

---

snapcraft/internal/meta/_snap_packaging.py
tests/fixture_setup/_fixtures.py
tests/unit/meta/test_snap_packaging.py

Snapcraft previously generated wrappers for most commands.  Once
snapcraft became more conserative about generating unnecessary wrappers,
issues began to surface with regard to PATH being set incorrectly
for classic snap apps that did not use shell.
To work around the issue, this commit adds an empty snapcraft-runner to
the command-chain for all apps, where they typically would have none.
Once this issue is resolved in snapd, we can probably remove this
workaround.
Add unit tests for snapcraft-runner generation
Add some additional parameters to the SnapcraftYaml fixture
to make it more configurable.
LP#: 1860369
-----

meta: always generate snapcraft-runner to workaround classic (#2889)

---

snapcraft/internal/build_providers/_multipass/_multipass.py

-----
os.getuid() does not exist on win32, so it will crash when called. I just disable the UID and GID map by setting it to `{"0":"0"}` if it's win32.

Fix issue with multipass mount on win32

---

snapcraft/internal/lifecycle/_packer.py

Sentry is full of bug reports related to RuntimeError for failing
to execute mksquashfs.  However, there is no clue as to the failure,
because snapcraft just prints it to logger.  Instead of logging the
error, include the output as part of the raised RuntimeError.
If we can get a better idea of the nature of the failures, we can
further refine handling here.
-----

lifecycle: raise detailed error if mksquashfs fails

---

snapcraft/internal/meta/_snap_packaging.py
tests/unit/meta/test_meta.py
tests/unit/meta/test_snap_packaging.py

Snapcraft regressed in how it handled environment for app wrappers and
hook wrappers in that is no longer includes it for hooks (only apps).
Add back the environment inclusion for hooks.
LP: #1824255
Signed-off-by: Kyle Fazzari <kyrofa@ubuntu.com>
-----

meta: include environment in hook wrappers

---

snapcraft/internal/meta/_snap_packaging.py

Remove unused _wrap_exe() and _find_bin().
-----

meta: remove dead code from snap packaging

---

snapcraft/internal/lifecycle/_status_cache.py
snapcraft/internal/project_loader/_config.py
snapcraft/plugins/_python/_pip.py
snapcraft/plugins/catkin.py
snapcraft/project/errors.py

This was mostly from running a flake8 from 3.9, but they are valid issue to
fix nonetheless.
Running flake8
./snapcraft/plugins/catkin.py:82:1: F401 'typing.Set' imported but unused
./snapcraft/plugins/_python/_pip.py:28:1: F401 'typing.Dict' imported but unused
./snapcraft/project/errors.py:19:1: F401 'typing.Dict' imported but unused
./snapcraft/project/errors.py:19:1: F401 'typing.List' imported but unused
./snapcraft/internal/project_loader/_config.py:24:1:
F401 'typing.List' imported but unused
./snapcraft/internal/project_loader/_config.py:24:1:
F401 'typing.Set' imported but unused
./snapcraft/internal/lifecycle/_status_cache.py:19:1:
F401 'typing.List' imported but unused
-----

static: fix some valid flake8 issues

---

snapcraft/internal/meta/_snap_packaging.py
tests/unit/test_meta.py

-----
Snapcraft regressed in how it handled environment for app wrappers and hook wrappers in that is no longer includes it for hooks (only apps). This PR fixes [LP: #1824255](https://bugs.launchpad.net/snapcraft/+bug/1824255) for legacy by adding back the environment inclusion for hooks.

[legacy] meta: include environment in hook wrappers

---

snapcraft/plugins/_python/_sitecustomize.py
tests/spread/plugins/python/site-packages/task.yaml
tests/spread/plugins/python/snaps/python-site-packages/snap/snapcraft.yaml
tests/unit/plugins/python/test_sitecustomize.py

The current sitecustomize generated by the python plugin always considers
adding site-packages from $SNAP which is only meant for runtime. This is a
problem as snapcraft runs in the context of a snap, so $SNAP always exists
in the environment.
When building, snapcraft exports SNAPCRAFT_INTERPRETER, use this as a condition
to export site-packages found under $SNAP.
LP: #1860884
-----

python plugin: do not leak snapcraft's site-packages

---

snapcraft/internal/elf.py
tests/bin/elf/ldd
tests/fixture_setup/_unittests.py
tests/unit/test_elf.py

A regression was introduced with commit 76e8a3f3f1c3f69d957b2806c9387ac3c57e926a
which considered elf files on the host system to be valid. Additionally, since
the host-found libraries were absolute paths, an os.path.join suffixing the
search paths snapcraft cared about were ignored.
A unit test which considers this scenario was added.
LP: #1860766
-----

elf: search for host libraries within search paths

---

snapcraft/internal/meta/snap.py
snapcraft/internal/meta/system_user.py
tests/unit/meta/test_snap.py
tests/unit/meta/test_system_user.py

Tidy it up a bit in preparation for further cleanup of from_dict().
No functional changes.
-----

meta: move Snap's from_dict() system-username parsing into SystemUser

---

snapcraft/internal/meta/_snap_packaging.py
tests/spread/general/adapter/expected_snap.yaml
tests/spread/general/adapter/snaps/adapter-tests/snapcraft.yaml
tests/spread/general/adapter/snaps/adapter-tests/test-cmd.py
tests/unit/meta/test_meta.py

Snapcraft is priming (modifying) the commands when adapter is set
to "none".  These commands should be passed through as-is and never
modify them.  This will be consistent with snapcraft's behavior with
regards to wrappers and snapcraft-runner (it does not generate wrappers
or modify the command-chain).
Add unit test for "none" case and update adapter spread test to
include a case for a adapter "none" with a python script command.
LP #1862163
-----

meta: do not prime commands with adapter == "none"

---

.travis.yml
spread.yaml

Most failures do not require the journal to debug.  To prevent flooding
the user with a lot of unnecessary information, only dump the journal
if SPREAD_DEBUG_JOURNAL=true.  Set this default for Travis CI.
-----

spread: disable journal debug dump unless configured

---

snapcraft/internal/meta/application.py
tests/spread/general/passthrough/expected_snap.yaml
tests/spread/general/passthrough/snaps/passthrough-tests/snap/hooks/configure
tests/spread/general/passthrough/snaps/passthrough-tests/snap/snapcraft.yaml
tests/spread/general/passthrough/snaps/passthrough-tests/test-cmd
tests/spread/general/passthrough/task.yaml
tests/unit/meta/test_application.py

The original `passthrough` was leaking through into the snap.yaml
from the app_dict.  Ensure "passthrough" is popped from the dict
used to create the snap.yaml.
Add unit tests for passthrough coverage of Application.
LP #1862197
-----

meta: ensure Application passthrough is scrubbed for snap.yaml

---

snapcraft/plugins/rust.py
tests/spread/plugins/rust/cargo-lock/task.yaml
tests/unit/plugins/test_rust.py

The previous PR was checking against the existence of the
Cargo.lock in builddir, which does not work at pull time.
So snapcraft it fetched the incorrect crate verisons at pull
time, but still built against the correct versions at build time.
Check for Cargo.lock in the source directory instead of the build
directory.  This will work anytime after the rust project's sources
have been fetched.
Improve the spread test to hopefully capture this error by
ensuring that "time" is downloaded only once.
-----

rust plugin: fetch correct (locked) crates during pull

---

snapcraft/project/_sanity_checks.py

-----
The sanity checks for expected snap directories were not checking to see if the path had backslashes in it, so the sanity check was failing on Windows. This fixes it.

sanity_checks: fix sanity check on Windows

---

snapcraft/internal/elf.py

If it the gnu_version_r section is not an instance of
GNUVerNeedSection, then we cannot use the iter_versions()
interface.  Just ignore processing needed in those cases.
Since the section type will be "SHT_GNU_verneed" [1], we
don't have to check that it is != "SHT_NOBITS".
LP #1862318
[1] https://github.com/eliben/pyelftools/blob/46dea162e8154328d4e4c6ede630d8b235bf91f9/elftools/elf/elffile.py#L491
-----

elf: ensure _GNU_VERSION_R section is of type GNUVerNeedSection

---

snapcraft/_store.py
snapcraft/cli/store.py
snapcraft/storeapi/_snap_index_client.py
snapcraft/storeapi/_store_client.py
snapcraft/storeapi/assertions.py
snapcraft/storeapi/errors.py
snapcraft/storeapi/info.py
tests/integration/store/test_store_revisions.py
tests/integration/store/test_store_status.py
tests/unit/commands/test_list_registered.py
tests/unit/commands/test_list_revisions.py
tests/unit/commands/test_status.py
tests/unit/lifecycle/test_lifecycle.py
tests/unit/store/test_errors.py
tests/unit/store/test_store_client.py
tests/unit/test_errors.py

Series, mostly used with constants.DEFAULT_SERIES has been long deprecated and
has not use.
Remove its broad exposure across the code base. No great changes should be
observed aside from reworking how SnapNotFoundError is implemented by making
use of the new SnapcraftException.
-----

storeapi: remove exposure of series

---

snapcraft/config.py
snapcraft/internal/lifecycle/_runner.py
snapcraft/internal/meta/snap.py
snapcraft/internal/mountinfo.py
snapcraft/internal/pluginhandler/_metadata_extraction.py
snapcraft/plugins/catkin_tools.py
snapcraft/plugins/colcon.py
snapcraft/plugins/kernel.py
snapcraft/plugins/ruby.py

logging: use .warning instead of deprecated .warn

---

snapcraft/internal/pluginhandler/__init__.py
tests/spread/general/snapd-workaround/expected_snap.yaml
tests/spread/general/snapd-workaround/snaps/fake-snapd/Makefile
tests/spread/general/snapd-workaround/snaps/fake-snapd/fake-snapd.c
tests/spread/general/snapd-workaround/snaps/fake-snapd/snapcraft.yaml
tests/spread/general/snapd-workaround/task.yaml

ELF files are always processed when `type: app`, where `app`
is the default type.
This causes an issue when snapd is building without specifying
the type, as it gets treated as `type: app` and its files
are processed like typical app snaps.  The schema currently
allows for this because it fails to set the default type `app`
in time for validation.
Since snapd does not have a base, check for the existence of the
base before attempting to process ELF files.  This will prevent
the error reported in LP #1857019 and allow snapd to build without
a type specified.
Once snapd moves to `type: snapd`, we can fix the schema to
ensure that the invalid configuration that led to this error
does not pass verification.
LP #1857019
LP #1862642 …

plugin handler: process elf files only if base is specified

---

extensions/desktop/common/desktop-exports
extensions/desktop/common/init

This is a fix for bug https://github.com/ubuntu/snapcraft-desktop-helpers/issues/173
This reduces hot run time for `desktop-launch` on *affected systems*. Depending on the snap, this can remove 1 - 10 seconds off its hot start time.
`desktop-launch` keeps needlessly setting `needs_xdg_reload=true` when `~/.config/user-dirs.dirs` exist but `~/.config/user-dirs.locale` doesn't. This happens when a user gets the `xdg-user-dirs-gtk` dialog (after changing the system language) and checks the "Don't ask me this again" option, which removes `~/.config/user-dirs.locale` .
This patch makes sure we only set `needs_xdg_reload=true` when something actually changes and removes the hash of `~/.config/user-dirs.locale` when the file itself is removed.
Note: depending on what logic runs when …

extensions: Handle case when user-dirs.dirs exits but not user-dirs.locale

---

snapcraft/internal/elf.py
tests/unit/test_elf.py

elf: catch and chain elftools' ConstructErrors to CorruptedElfFileError
elf: ignore corrupted elf files when crawling for libraries

elf: fixes for corrupt shared objects

---

snapcraft/internal/meta/slots.py
tests/unit/meta/test_slots.py
tests/unit/meta/test_snap.py

Content was not being initialized correctly from the
snapcraft.yaml.  Ensure it is used to create ContentSlot.
Update existing tests to ensure coverage of explicit content.
-----

meta: fix for missing content slot's 'content' property

---

snapcraft/internal/build_providers/_lxd/_lxd.py

This message about waiting for cloud-init is an implementation detail.
This has confused users, some thought that their data was being
_sent to the cloud_ which is not what is happening considering
what cloud-init is meant to be doing.
The code base is also moving away from cloud-init to profile containers
for Snapcraft, it might as well be ready for that moment.
-----

build providers: clean up LXD startup message

---

tests/spread/tools/restore.sh

Fixes spread test errors with LXD using snapd snap.
error: cannot remove "snapd": snap "snapd" is not removable:
remove all other snaps first
-----

spread tests: do not attempt to remove snapd snap

---

snapcraft/internal/remote_build/_launchpad.py
tests/unit/remote_build/test_launchpad.py

Add a test to cover the default options to snap.requestBuilds().
-----

remote build: default to snapcraft's stable channel

---

snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_lxd/_lxd.py
tests/unit/build_providers/test_base_provider.py

This workaround was put in place, but it is the wrong fix.
The underlying problem was fixed with the addition of --preserve-env
on commit:
97fdf64b731e23f02898e7921e838a2fc80a6c5d
-----

build providers: remove tzdata workaround

---

snapcraft/cli/store.py
tests/unit/commands/test_release.py

The exposure of the progressive key has been reassessed and will not be part of
the exposed feature.
The UX also needs reconsideration on how the table is presented when a
progressive release is triggered.
-----

store: temprorarily remove support for progressive releases

---

snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/pluginhandler/_runner.py
tests/unit/pluginhandler/test_runner.py

snapcraftctl for each part creates a CALL_FIFO and a FEEDBACK_FIFO.
These live under /tmp on a random directory.
This change makes it so that this directory temporary directory is part of
partdir, which would scope these files to the part that is supposed to use
them.
-----

pluginhandler: user directories scoped to partdir for snapcraftctl

---

snapcraft/internal/remote_build/_worktree.py
tests/unit/remote_build/test_worktree.py

It is currently being stripped with the other source keys,
but we need to instead pass it through.
Add a test to verify source properties are passed through (or not).
-----

remote-build: pass through 'source-subdir' property

---

spread.yaml
tests/spread/legacy/command-define/task.yaml
tests/spread/legacy_python/general/task.yaml
tests/spread/legacy_python/lifecycle/task.yaml

This information can often be useful to diagnose what is wrong.
Since spread only spits out the output on failure, it shouldn't
clutter up typical logs.
Sets SNAPCRAFT_ENABLE_DEVELOPER_DEBUG=yes in the spread env.
-----

spread: capture developer debug information

---

requirements.txt

-----
They are no longer providing updated wheels for windows for newer python versions (>3.7). This updates snapcraft to use 5.3 instead, which is the current version and is being provided updated wheels for newer python versions.

requirements: Update PyYAML requirement to 5.3

---

extensions/desktop/common/desktop-exports

The absence of the cache file (after manual deletion) was causing the chromium snap to crash when opening a GTK file dialog.
This is a backport of the fix from the snapcraft-desktop-helpers project (https://github.com/ubuntu/snapcraft-desktop-helpers/commit/769110c9101c333c3ae6ccc3663098f094e580be).

Regenerate the GDK pixbuf loaders cache file if for whatever reason it isn't there (LP: #1863801).

---

snapcraft/internal/meta/_snap_packaging.py

The check is incorrect as-is because is_host_compatible points to a
function, not a bool, effectively evaluating to true (always).
Just remove the check and generate the environment as is currently
being done anyways.  Even if the host were incompatible, the
environment will be more correct that omitting it.  Building on
an incompatible host is user-beware and this is one of the risks.
-----

snap-packaging: remove broken host-compatibility check for runner

---

snapcraft/internal/meta/snap.py
tests/unit/meta/test_snap.py

- remove `__dict__` usage and detail each property
- remove snap.yaml-isms from to_dict, into newly added to_snap_yaml_dict()

meta: Snap to_dict() cleanup

---

snap/snapcraft.yaml
snapcraft/internal/elf.py
tests/fixture_setup/_unittests.py
tests/unit/test_elf.py

elf: resolve paths in `ldd()` to purge relative path components
ldd may return paths with relative components such as "..", e.g.:
{
'linux-vdso.so.1': '',
'libc.so.6': '/snap/core/current/lib/x86_64-linux-gnu/libc.so.6',
'libnvidia-container.so.1': '/root/prime/usr/bin/../lib/x86_64-linux-gnu/libnvidia-container.so.1',
'libcap.so.2': '/snap/core/current/lib/x86_64-linux-gnu/libcap.so.2',
'libdl.so.2': '/snap/core/current/lib/x86_64-linux-gnu/libdl.so.2',
'libseccomp.so.2': '/snap/core/current/lib/x86_64-linux-gnu/libseccomp.so.2'
}
(1) Resolve the paths before using them to ensure we have a consistent
values that do not look odd in potential warnings/errors (e.g.
corrupted ELF).
This also appears to expose an issue with the FakeElf fixture which
was not creating a fake "barsnap.so.2" in …

elf: resolve paths in `ldd()` to purge relative path components

---

snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_lxd/_lxd.py
snapcraft/internal/build_providers/_multipass/_multipass.py
tests/unit/build_providers/lxd/test_lxd.py
tests/unit/build_providers/multipass/test_multipass.py
tests/unit/build_providers/test_base_provider.py

Make use of other build provider functionality to have the necessary
assets on the build environment (i.e.; ._run and ._push_file).
The initial "first run" setup has been moved to its own method.
-----

build providers: remove use of cloud-init

---

tests/spread/general/appstream/expected_appstream-desktop.desktop
tests/spread/general/appstream/expected_snap.yaml
tests/spread/general/appstream/snaps/appstream-desktop/appstream-desktop
tests/spread/general/appstream/snaps/appstream-desktop/io.snapcraft.appstream.desktop
tests/spread/general/appstream/snaps/appstream-desktop/io.snapcraft.appstream.metainfo.xml
tests/spread/general/appstream/snaps/appstream-desktop/snap/snapcraft.yaml
tests/spread/general/appstream/snaps/appstream-desktop/snapcraft.svg
tests/spread/general/appstream/task.yaml

- Ensure that adopt-info + parse-info is capturing the correct
data.
- Test the desktop icon path is rewritten using ${SNAP}.
There does some to be some unexplained difference when running this test against local LXD.  My newlines are different in the description field... see https://github.com/snapcore/snapcraft/compare/4f3f58f0fcd40e3cc6383a278eefb7f61b1b90d3..221da1a606f2cf51d33489db0ac1fcada30519fa

spread: introduce appstream parse-info test

---

snapcraft/internal/meta/snap.py
tests/unit/meta/test_snap.py

also fix a c901 label for python 3.8 while I'm in the vicinity.

meta: remove remaining `__dict__` and key list usage in snap

---

snapcraft/internal/repo/_deb.py
tests/unit/repo/test_deb.py

Use `--preserve-env` as used for `apt-get install`.
Switch to `apt-get` for updating packages as well for
consistency.
-----

repo: respect http proxy for apt update

---

snapcraft/plugins/dotnet.py
tests/unit/plugins/test_dotnet.py

The old endpoint has been removed
https://github.com/dotnet/core/commit/599cf6d47ffbdf51f9117062b2db6f63cd9f9635
-----

dotnet plugin: use the new endpoint for releases

---

snapcraft/cli/_runner.py

If using the lifecycle commands, the config file is read.  This
commit also extends it to the base `snapcraft` command, which runs
the snap lifecycle command.
-----

cli: enable config file for base snapcraft command

---

snapcraft/plugins/go.py
tests/spread/plugins/go/snaps/go-use-stage-packages/go-hello/main.go
tests/spread/plugins/go/snaps/go-use-stage-packages/snap/snapcraft.yaml
tests/spread/plugins/go/use-stage-packages/task.yaml

Packages configured in a part's stage-packages are installed prior
to build and installed to $SNAPCRAFT_PART_INSTALL.  Cleaning
$SNAPCRAFT_PART_INSTALL/bin will purge any files that may have been
installed there.
Running go build should overwrite any previously installed files,
which will be OK for incremental builds.  However, as the go plugin
does not enable out_of_source_build, the entire build directory is
purged on every build anyways.
Add spread test for coverage.
Reported by @stgraber

go plugin: do not remove install /bin directory before build

---

snapcraft/internal/pluginhandler/__init__.py
tests/spread/general/dependency-check-missing-lib/snaps/missing-lib/snap/snapcraft.yaml
tests/spread/general/dependency-check-missing-lib/task.yaml
tests/spread/general/dependency-check-missing-none/snaps/missing-none/snap/snapcraft.yaml
tests/spread/general/dependency-check-missing-none/task.yaml
tests/unit/pluginhandler/test_pluginhandler.py

The search paths already include primedir which has all of the primed
and staged files at this point.  The installdir and stagedir may
contain files that are not shipped in the final snap, so limit search
to primedir as it should be fully populated.
- Replace _handle_dependencies() with a simpler _warn_missing_dependencies()
and _calculate_dependency_paths() called from _handle_elf().
- Add a couple useful debug prints.
- Add two tests to cover the case where the dependency is found, and
another where the dependency is missing.  For the latter, the lib is
removed using `stage` configuration.
This last test would have previously failed, because the dependency
was found in installdir, and ignored by the missing dependency resolver.
Signed-off-by: Chris Patterson …

pluginhandler: do not search installdir or stagedir for dependencies

---

snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_multipass/_multipass.py
tests/unit/build_providers/multipass/test_multipass.py
tests/unit/build_providers/test_base_provider.py

Using -i when stdin is set to DEVNULL causes an ioctl warning in
Multipass.
-----

build providers: remove over use of -i in sudo

---

requirements.txt
tests/unit/commands/test_enable_ci.py
tests/unit/commands/test_sign_build.py

Lock in the version so it doesn't uprev itself to a "compatible version"
as it did here.  This uprev changed the quoting used for click errors
when failing to provide a required parameter.
-----

requirements: uprev click to 7.1.1

---

snapcraft/plugins/_ros/rosdep.py
snapcraft/plugins/colcon.py
tests/unit/plugins/ros/test_rosdep.py
tests/unit/plugins/test_colcon.py

-----
Snapcraft has support for a number of ROS distributions that are actually end-of-life upstream. Once they go end-of-life, such snaps suddenly stop building. This PR fixes this by letting them continue to work, but adding a warning to let users know that it's officially EOL and no longer supported.

rosdep: include EOL ROS distros

---

snapcraft/internal/build_providers/_lxd/_lxd.py
tests/unit/build_providers/lxd/test_lxd.py

Get rid of the LXD specific environment handling considering that
everything is already driven by Provider._get_env_command
-----

build providers: remove LXD specific env setup

---

snapcraft/plugins/go.py
tests/spread/plugins/go/run-go-mod-subdir/task.yaml
tests/spread/plugins/go/snaps/go-mod-hello-subdir/go-hello/main.go
tests/spread/plugins/go/snaps/go-mod-hello-subdir/go.mod
tests/spread/plugins/go/snaps/go-mod-hello-subdir/go.sum
tests/spread/plugins/go/snaps/go-mod-hello-subdir/snap/snapcraft.yaml
tests/unit/plugins/test_go.py

When using go modules, `go build -o <path>` will pick up main package only if it's in the root of repository.
Steps to reproduce:
0. Given a go module, where [main](https://github.com/pavel-d/snaptest/blob/master/cli/main.go) package is located in `./cli` subdirectory
1. Clone https://github.com/pavel-d/snaptest
2. `cd snaptest`
2. Run `snapcraft build --use-lxd --debug`
Result:
```
snapcraft --use-lxd  --debug
The LXD provider is offered as a technology preview for early adopters.
The command line interface, container names or lifecycle handling may change in upcoming releases.
Launching a container.
Waiting for container to be ready
......................
status: done
snapd 2.43.3 from Canonical✓ refreshed
Skipping pull snaptest (already ran)
Building snaptest 
go build -o …
```

Go: unable to build snap when using `go mod` and main package is not in the root

---

snapcraft/project/_project_options.py
tests/unit/project_loader/test_environment.py

Project was recently updated [1] to use os.sched_getaffinity()
to get a more accurate view of how many threads are available
for use.
However, OSX does not implement os.sched_getaffinity(), failing
with AttributeError.
Fall back to multiprocessing.cpu_count if os.sched_getaffinity()
does not exist.
Failing that, return 1.
Add a couple of unit tests for coverage.
[1] 332df0f97e93ac7ecc325f929faacb79ae55ddd1
-----

project: add fallbacks for os.sched_getaffinity

---

snap/snapcraft.yaml
spread.yaml

Binary wheels are only available for x86.
-----

snap: re-add xml development packages for non x86

---

snapcraft/internal/sources/_git.py
tests/unit/sources/test_git.py

Two cases where git will fail on specified source-commit:
- commit ID is not in specified branch history (or master, if no branch
is specified).
- source-depth is used which doesn't contain neccessary commit ID.
This commit changes the git module to fetch the reference from origin
before attempting to use it.
LP: #1817907
-----

git: always fetch specified source-commit before using

---

snapcraft/cli/_options.py
snapcraft/internal/build_providers/_base_provider.py
tests/unit/build_providers/test_base_provider.py

Currently the approach translates them to a formatted version of
the kwarg used to pass around to functions.  Instead of performing
that translation, just match the envvar used.
cmd arg       -> kwarg parameter -> environment variable
--------------------------------------
--http-proxy  -> http_proxy      -> http_proxy
--https-proxy -> https_proxy     -> https_proxy
--bind-ssh    -> bind_ssh        -> SNAPCRAFT_BIND_SSH
Since apply_host_provider_flags() sets the flags in the environment
for all build provider options, internal functions can lookup settings
using os.getenv() without the kwarg translation.  They can simply
used the defined interface name (e.g. http_proxy, SNAPCRAFT_BIND_SSH).
This will improve consistency as their use is expanded for future
options.  The kwarg version …

providers: match build provider flag keys to envvar

---

snapcraft/plugins/colcon.py
tests/unit/plugins/test_colcon.py

-----
The version of poco in Ubuntu Bionic (v1.8.0.1) has a bug where it installs absolute library paths in its cmake target file. ROS Eloquent was updated to inherit those paths, and no longer builds (although Dashing still does). This PR fixes [LP: #1866723](https://bugs.launchpad.net/bugs/1866723) by re-using the existing cmake-fixing logic, but also apply it to the directory containing poco's target file (`usr/lib/cmake`).
Note that this is not as targeted as it could be. I figure this issue may not be unique, so fixing all of `usr/lib/cmake` made sense, but we could keep it to the specific file that's broken as well.

colcon plugin: rewrite poco absolute library paths

---

snapcraft/cli/_options.py
snapcraft/cli/_runner.py

It will now be handled in the same manner as other build
provider options.  If it is set, it will automatically get
passed through to build environment if used on host with LXD
or Multipass providers.
-----

cli: formalize developer debug as hidden build option

---

snapcraft/internal/project_loader/_env.py
tests/unit/project_loader/test_environment.py

project_loader: use -isystem instead of -I for system include paths
Warnings are ignored for sytem includes.  However, when a system
include gets installed to staging directory, the user may be
issued warnings (errors if -Werror) because snapcraft is adding
include paths thats include these system headers.
Use `-isystem` rather than `-I` to add system include paths to
the default compiler flags.  The other option is to use `-idirafter`,
but is more likely to affect current builds by changing the order
of the search paths.
For example:
```
In file included from /root/parts/workspace/install/usr/include/x86_64-linux-gnu/bits/fcntl.h:61:0,
from /root/parts/workspace/install/usr/include/fcntl.h:35,
from /root/parts/workspace/build/benchmark_catkin/benchmark_src-prefix/src/benchmark_src/src/sys …
```

project_loader: use -isystem instead of -I for system include paths

---

spread.yaml

This should make it easier to locally test things that require
"containers" or snap installations to work.
-----

tests: add multipass adhoc spread backend

---

snapcraft/cli/_options.py
snapcraft/cli/_runner.py
snapcraft/cli/lifecycle.py

In reality these options only work with specific providers.
Merge the build options and provider option lists to simplify
the option handling code.
-----

cli: merge build options into provider options

---

spread.yaml
tests/spread/snaps/lxd/task.yaml

Test that LXD builds fine and installs. Instrumenting the
installation comes later.
-----
2020-03-17 18:00:05 Restoring multipass:ubuntu-18.04-64:tests/spread/snaps/lxd:destructive...
2020-03-17 18:00:55 Discarding multipass:ubuntu-18.04-64...
2020-03-17 18:01:31 Successful tasks: 2
2020-03-17 18:01:31 Aborted tasks: 0

tests: add LXD spread test

---

.flake8
pyproject.toml

direnv creates a .direnv when using a pyenv layout that holds python's
standard libraries which black modifies and flake8 fails on.
-----

static: ignore direnv created artifacts

---

tests/spread/plugins/catkin/run/task.yaml

Timing out on 18.04 is killing tests.
-----

tests: only run catkin based snap on 16.04

---

.travis.yml

The service is currently broken and this test has already been disabled
for a while.
-----

ci: remove osx test from Travis

---

snapcraft/plugins/catkin.py
snapcraft/plugins/catkin_tools.py
tests/spread/plugins/catkin/snaps/ros-talker-listener/snap/snapcraft.yaml
tests/unit/plugins/test_catkin.py
tests/unit/plugins/test_catkin_tools.py

Parse the args like bash would using shlex.split().
This parsing should match the behavior currently performed by
pumping it all out to bash and executing it there.
While I think any approach here is a bit fragile, we demonstrate
various test cases with some unit tests and add a few cmake arg
variants to ros-talker-listener:
- no quotes
- basic quotes
- nested quotes using inner-escaped
For the spread test, we don't really need to validate the variables,
just that it managed to build.

catkin plugins: remove bash workaround for catkin cmake args

---

snapcraft/internal/repo/_deb.py
tests/unit/repo/test_deb.py

- Remove functions are redundant with those found in _base.
- Remove unused geoip support, we'll eventually allow the user
to configre the primary mirrors.
- Remove unused default sources list.  We'll always be using
the host's.
-----

repo: remove dead code from deb implementation

---

snapcraft/internal/project_loader/_parts_config.py
snapcraft/internal/repo/_deb.py
snapcraft/plugins/v1/_plugin.py
snapcraft/plugins/v1/_ros/wstool.py
snapcraft/plugins/v1/catkin.py
snapcraft/plugins/v1/colcon.py
tests/unit/plugins/v1/test_catkin.py

The Ubuntu object is now responsible for ensuring that all of
the configured apt sources are merged (performed in
AptCache._collected_sources_list()).
- (Re)define plugin.PLUGIN_STAGE_SOURCES to be a list of strings of
repositories to be added.  The base plugin will return an empty
list if the plugin doesn't define it.  There was a bit of mixed
usage of str vs. list, so we make it explicit.
- Remove the redundant sources specified by the catkin and colcon
plugins, we do not support building for non-native releases.
- Update tests accordingly, removing catkin's tests for verifying
sources are formatted for cross-release build (i.e. base does
not match build environment), which is no longer supported.
- Remove unused reference to plugin._PLUGIN_STAGE_SOURCES.
- Remove unused reference to …

repo: always use host source lists and remove those found in plugins

---

snapcraft/plugins/v1/dotnet.py
tests/unit/plugins/v1/test_dotnet.py

Changes:
- Add `dotnet-version` to be able to choose runtime version. Now it can be used for 3.1 version of dotnet core. Defaults to 2.0.9, nothing changed
- Update dependencies for core18
- Remove test for unsupported version core
Prereq:
-----

Change dotnet runtime version from snapcraft.yaml

---

snapcraft/internal/project_loader/_extensions/gnome_3_34.py
tests/unit/project_loader/extensions/test_gnome_3_34.py

-----
Even though gcc is staged in the gnome-3-34-1804-sdk build snap, Ken still needs this to build firefox in docker.

Add gcc to the build-packages for the gnome-3-34 extension

---

snapcraft/plugins/v1/go.py
tests/spread/plugins/v1/go/multiple_mains/task.yaml

There was a check to assert only one binary was built.
- Remove the error check. If no binaries are found, warn.
- Update logic to handle relinking multiple binaries.
- Update multiple main spread test to also build with go.mod.
-----

go: support projects with multiple binaries when using go.mod

---

snapcraft/internal/repo/_deb.py
tests/fixture_setup/_unittests.py
tests/unit/repo/test_deb.py

python-apt has been updated to be less verbose, so we can
use the fetch_binary() logic that was lifted from there.
Update mocks, fixture, and tests accordingly.
-----

repo: use python-apt's fetch_binary implementation

---

snapcraft/internal/project_loader/_parts_config.py
snapcraft/internal/repo/_deb.py
snapcraft/plugins/v1/_ros/rosdep.py
snapcraft/plugins/v1/_ros/wstool.py
snapcraft/plugins/v1/catkin.py
snapcraft/plugins/v1/colcon.py
tests/unit/plugins/v1/ros/test_rosdep.py
tests/unit/plugins/v1/ros/test_wstool.py
tests/unit/plugins/v1/test_catkin.py
tests/unit/repo/test_deb.py

- Remove dependency of ProjectOptions parameter.
- Update format_sources_list() tp query release arch/release
separately.
Update tests accordingly.
-----

repo: always use host release and arch for Ubuntu

---

snapcraft/internal/repo/_deb.py
snapcraft/internal/repo/errors.py
tests/unit/repo/test_deb.py
tests/unit/repo/test_errors.py

Allow system-wide installation of trusted GPG keys and deb sources
for apt.
- GPG keys are installed to: /etc/apt/trusted.gpg.d/snapcraft.gpg
- Installed using apt-key with sudo.
- Introduce AptGPGKeyInstallError to help format apt-key errors.
This will expand as we incorporate more cases of apt-key.
- Deb sources are installed to: /etc/apt/sources.list.d/snapcraft.list
- Installed using a helper to write the file with sudo.
- Add tests for coverage.
-----

repo: introduce install_source() and install_gpg_key() to Ubuntu

---

snapcraft/internal/build_providers/_multipass/_multipass.py
snapcraft/internal/build_providers/_multipass/_multipass_command.py
tests/unit/build_providers/multipass/test_multipass.py
tests/unit/build_providers/multipass/test_multipass_command.py

With Multipass going strict, that's the reliable way.
I've not found a better way around [LP#1849753](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1849753).
This does build the Multipass snap on strict Multipass from `snap refresh --channel edge/pr1074` fine.

[multipass] use stdio to get data in/out of Multipass

---

tests/spread/plugins/v1/x-local/snaps/from-baseplugin/snap/snapcraft.yaml
tests/spread/plugins/v1/x-local/snaps/from-nilplugin/snap/snapcraft.yaml

Follow the pattern applied in commit
feb2672d28c6198515f55601a16ec3b2001ce1e9
-----

spread tests: default base for local plugin tests

---

snapcraft/internal/remote_build/_launchpad.py
tests/unit/remote_build/test_launchpad.py

A snapcraft.yaml may have a configuration of `build-on` that allows
Launchpad to pick from a set of architectures that will run on
multiple architectures.
This will fail our sanity check which assumes the arch, which may
in fact end up as `multi`.  There isn't really any need to sanity
check the artifacts anyhow, so we'll remove this check and download
whatever Launchpad provides.
LP: #1870730
-----

remote-build: remove artifact sanity check

---

snapcraft/internal/elf.py
snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/pluginhandler/_patchelf.py
snapcraft/internal/project_loader/_parts_config.py
snapcraft/plugins/v1/_plugin.py
tests/unit/__init__.py
tests/unit/pluginhandler/test_patcher.py
tests/unit/pluginhandler/test_pluginhandler.py

Rely less on setting from the plugin and remove duplicate attributes
already held by Project and Project._snap_meta.
This involved a general cleanup.
-----

pluginhandler: move attributes to PluginHandler

---

snapcraft/cli/_channel_map.py
snapcraft/storeapi/v2/_api_schema.py
snapcraft/storeapi/v2/channel_map.py
tests/unit/build_providers/lxd/test_lxd.py

Add missing __init__.py to workaround python/mypy#1645
Fix mypy type hint issues in the code found from this.
-----

static: mypy requires __init__.py

---

runtests.sh

static: add codespell excludes for .direnv

---

.travis.yml
spread.yaml
tests/spread/general/dependency-check-missing-lib/task.yaml
tests/spread/general/dependency-check-missing-none/task.yaml
tests/spread/plugins/v1/autotools/legacy-pull/task.yaml
tests/spread/plugins/v1/cmake/legacy-pull/task.yaml
tests/spread/plugins/v1/go/legacy-build-run/task.yaml
tests/spread/plugins/v1/godeps/legacy-build-run/task.yaml
tests/spread/plugins/v1/kbuild/legacy-pull/task.yaml
tests/spread/plugins/v1/make/legacy-pull/task.yaml
tests/spread/plugins/v1/qmake/legacy-pull/task.yaml
tests/spread/plugins/v1/ruby/legacy-pull/task.yaml
tests/spread/plugins/v1/scons/legacy-build-run/task.yaml
tests/spread/tools/snapcraft-yaml.sh

Some systems were a bit greedy on their selections.
Removed the logic to install deb or snap, we just install the snap.
Added a specific environment for unit tests to identify easily.
-----

spread tests: add core20 and cleanup systems

---

snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/project_loader/_parts_config.py
snapcraft/internal/project_loader/grammar_processing/_part_grammar_processor.py
snapcraft/internal/repo/_base.py
snapcraft/internal/repo/_deb.py
snapcraft/plugins/v1/_ros/rosdep.py
snapcraft/plugins/v1/_ros/wstool.py
snapcraft/plugins/v1/catkin.py
snapcraft/plugins/v1/colcon.py
tests/unit/__init__.py
tests/unit/lifecycle/test_lifecycle.py
tests/unit/pluginhandler/test_pluginhandler.py
tests/unit/plugins/v1/ros/test_rosdep.py
tests/unit/plugins/v1/ros/test_wstool.py
tests/unit/plugins/v1/test_catkin.py
tests/unit/plugins/v1/test_colcon.py
tests/unit/repo/test_base.py
tests/unit/repo/test_deb.py

This does remove the broken dependency handling... I need
a working test case to make sure that's solid.
- Move repo.get_pkg_name_parts to test_base, even though it's
in __init__.
- Remove all instance methods from repo and Ubuntu, consolidating
to install_stage_packages() classmethod.
- Move non-class methods in Repo into Repo class so they can be
easily inherited.
- Remove custom _AptCache implementation.
- Use a single instance of the system's apt cache, which should
improve performance due to the penalty of recreating caches in
numerous points.  It also simplifies usage without the requirement
of copying/sharing instances for what is (now) a system-wide
resource.
- Remove old scheme for gathering stage packages, and simply do a scan
ourselves for the packages and their dependencies. …

repo: drop _AptCache and add migrate to install_stage_packages()

---

snapcraft/internal/build_providers/_lxd/_lxd.py
tests/unit/build_providers/lxd/test_lxd.py

Do not print out the output of "getent hosts snapcraft.io" which run
during environment setup.
-----

build providers: do not print network test output for LXD

---

.travis.yml

Bootstrap snapcraft snap building using stable channel.  Upcoming
commit will install this snap and use it to rebuild snapcraft using
the PR.  This will prevent against a PR from breaking snapcraft's
own builds in the future.

travis: use stable channel for building snapcraft snap

---

snapcraft/internal/repo/_deb.py
tests/spread/general/virtual-packages/snaps/virtual-packages-test/hello
tests/spread/general/virtual-packages/snaps/virtual-packages-test/snapcraft.yaml
tests/spread/general/virtual-packages/task.yaml
tests/unit/repo/test_deb.py

With my previous PR, virtual build packages are no longer found.
Ensure that build and stage packages are resolved the best we can,
and persist any potential versioning.
Log any build and stage packages that have been resolved so the
user can see any assumptions we're making to resolve it.
Add unit and spread test coverage.
-----

repo: fix resolution of virtual build packages

---

.travis.yml

Self-hosting snapcraft as part of the PR will help prevent a PR from
breaking the snapcraft build for subsequent builds.  Snapcraft is an
excellent test case anyways.
Do this by first building the snap from stable snap, then rebuild
snapcraft using the newly created snap.
-----

travis: add and ship a self-hosting build of snapcraft

---

snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/repo/_deb.py

Move one log from pluginhandler to install_stage_packages().
While here, remove unnecessary empty list check in
install_build_packages().  The function will handle
an empty list appropriately.
-----

repo: minor debug log tweaks

---

snapcraft/internal/project_loader/grammar/typing.py
snapcraft/internal/project_loader/grammar_processing/_part_grammar_processor.py
tests/unit/project_loader/grammar_processing/test_part_grammar_processor.py

This enables support for v2 which decouples user added
properties (build-packages, stage-packages, build-snaps and
stage-snaps) and the ones the plugin needs to operate.
-----

grammar: pick from properties if attributes not in the plugin

---

snapcraft/internal/build_providers/_base_provider.py
tests/unit/build_providers/test_base_provider.py

Non-x86 mirrors use http://ports.ubuntu.com/ubuntu-ports, not
the default archives.  Detect the host CPU and use the correct
mirror.

build providers: use ubuntu-ports mirrors for non-x86 platforms

---

snapcraft/internal/repo/_deb.py
tests/unit/repo/test_deb.py

Instead of returning `<package>=<version>`, it was returning
`<package>=<apt.Version>`.  Resolve the version string which
is the intended return value.
Fix unit tests to cover this. Switch to using PropertyMocks,
as the MagicMock(wraps=...) did not work as I had expected.
LP #1873349
-----

repos: fix returned strings for install_stage_packages()

---

snapcraft/project/_project.py
snapcraft/project/_sanity_checks.py
tests/unit/project/test_sanity_checks.py

Keys will be stored in /snap/keys/<key_id>.asc.
- Add _get_keys_path() interface for Project.
- Update asset sanity checks to ensure keys formatted as
<assets-dir>/keys/*.asc are OK, and warns on unsupported
extensions (e.g. '.key').
-----

project: introduce 'keys' for project assets

---

snapcraft/internal/meta/package_repository.py
tests/unit/meta/test_package_repository.py

These sanity checks are supposed to be covered by the schema,
but in the event the schema fails, it's difficult to diagnose.
Provide a unique RuntimeError for each unexpected case.
-----

meta: split up package repository sanity checks

---

schema/snapcraft.json
snapcraft/internal/repo/_deb.py
snapcraft/plugins/v1/catkin.py
snapcraft/plugins/v1/colcon.py
tests/unit/project/test_schema.py
tests/unit/repo/test_deb.py

Change schema reference of $host_arch to $SNAPCRAFT_APT_HOST_ARCH as well,
but that's not implemented just yet.
Depends on #3055

repo: format $SNAPCRAFT_APT_RELEASE instead of ${release} for suites

---

schema/snapcraft.json
snapcraft/internal/meta/package_repository.py
tests/unit/meta/test_package_repository.py
tests/unit/project/test_schema.py

Default to using the URL, stripping non-alphanumeric characters.
-----

package-repositories: make 'name' optional

---

snapcraft/cli/_options.py
snapcraft/internal/meta/_snap_packaging.py
snapcraft/internal/xattrs.py
tests/spread/build-providers/lxd-build-info/task.yaml
tests/unit/build_providers/test_base_provider.py
tests/unit/cli/test_options.py

-----
In order to include a `snap/manifest.yaml` in a snap, you can set the `SNAPCRAFT_BUILD_INFO` environment variable.  However, this doesn't work with build providers that perform a build within a container/VM, since the variable is not passed to the child Snapcraft instance.
This should fix [bug #1871770][1].
[1]: https://bugs.launchpad.net/snapcraft/+bug/1871770

build_providers: pass through SNAPCRAFT_{BUILD,IMAGE}_INFO to container or VM

---

tests/spread/plugins/v1/x-local/local-plugin/state-pull
tests/spread/plugins/v1/x-local/local-plugin/task.yaml

This is to allow for the autopkgtests, which run on more than amd64 to
pass.
-----

tests: fix local plugin spread test to be multi-arch aware

---

snapcraft/plugins/v2/autotools.py
snapcraft/plugins/v2/cmake.py
snapcraft/plugins/v2/go.py
snapcraft/plugins/v2/make.py
snapcraft/plugins/v2/meson.py
snapcraft/plugins/v2/python.py
snapcraft/plugins/v2/rust.py
tests/unit/plugins/v2/test_autotools.py
tests/unit/plugins/v2/test_cmake.py
tests/unit/plugins/v2/test_go.py
tests/unit/plugins/v2/test_meson.py
tests/unit/plugins/v2/test_python.py
tests/unit/plugins/v2/test_rust.py

- Remove invalid uses of minitems (and not minItems) in the plugin
schemas.
- Remove use of any "prefix" setup, it is up to the developer of the
snap to pick.
- Remove the concept of setting a default build type for plugins.
- Fixup the docstrings so they are consistent with spacing and general
presentation.
-----

plugins v2: update plugins so they have a similar behavior

---

schema/snapcraft.json
tests/unit/project/test_schema.py

- Grammar fixes.
- Add test coverage for empty architectures, suites, and components.
- Correct tests that were passing for incorrect reasons (missing url).
Requires better error detection handling than what we can do wih the
schema.
- Remove name from one of the validity checks, it is no longer required.
-----

schema: minor tweaks/fixes for package-repositories

---

schema/snapcraft.json
snapcraft/internal/repo/_deb.py
tests/unit/repo/test_deb.py

CalledProcessError.output is a bytes object that must
be decoded, not a string.
- Set LANG in _install_gpg_key_id_from_keyserver() as
done for _install_gpg_key().
- Fix unit test coverage for CalledProcessError.output.
- Add test coverage for install_gpg_key_id().
-----

repo: fix decoding of CalledProcessError output

---

snapcraft/storeapi/v2/_api_schema.py

This is provides no change today, but allows the Snap Store to grow
the API responses and include new keys without breaking Snapcraft.
-----

storeapi: remove strict additionalProperties from store responses

---

snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/pluginhandler/_part_build_environment.py
tests/unit/__init__.py
tests/unit/pluginhandler/test_patcher.py
tests/unit/pluginhandler/test_pluginhandler.py

This method is not there anymore. Update unit tests, but these really
need redoing.
Fixes SNAPCRAFT-1JS
-----

pluginhandler: skip plugin clean_pull for PluginV2

---

snapcraft/plugins/v2/meson.py
tests/spread/plugins/v2/build-and-run-hello/task.yaml
tests/spread/plugins/v2/snaps/meson-hello-staged-python/hello.c
tests/spread/plugins/v2/snaps/meson-hello-staged-python/meson.build
tests/spread/plugins/v2/snaps/meson-hello-staged-python/snap/snapcraft.yaml
tests/unit/plugins/v2/test_meson.py

meson v2 plugin: ignore any staged python when installing meson

---

snapcraft/cli/help.py
snapcraft/plugins/v2/nil.py
snapcraft/plugins/v2/python.py
tests/unit/commands/test_help.py
todo.org

- Use click pager by default (it does the right thing).
- Fix the python and nil plugin help for v2.
- Load base from project or default to core20 if --base is not passed.
-----

cli: add plugin help for core20

---

snapcraft/internal/remote_build/_launchpad.py
tests/unit/remote_build/test_launchpad.py

Log when there is no URL to be downloaded.
Add unit test case coverage.
Fixes: SNAPCRAFT-1JW, SNAPCRAFT-1FS
-----

remote-build: fix case where build log url is None

---

snapcraft/internal/repo/_deb.py
tests/unit/repo/test_deb.py

When enabling multiple architectures, python-apt's BaseDependency
may yield target_versions for a package which are for the unintended
architecture when coming across a package with ':all' architecture.
For example: python3-pip has a dependency on "python3:any". On AMD64
it may point to the i386 package, when having i386 architectures
enabled:
```
>>> apt.Cache()["python3-pip"].candidate.dependencies[-1].target_versions
[
<Version: package:'python3:i386' version:'3.6.7-1~18.04'>,
<Version: package:'python3' version:'3.6.7-1~18.04'>,
<Version: package:'python3:i386' version:'3.6.5-3'>,
<Version: package:'python3' version:'3.6.5-3'>]
]
```
Instead, we'll look at python-apt's `or_dependencies` list, which is
used to calculate the allowable target_versions:
```
>>> …
```

repo: fix for multi-arch stage-package scenario

---

snapcraft/internal/repo/_deb.py

dpkg-architecture is not installed on all systems and the code path
is run from the host before entering build environments.
Fixes SNAPCRAFT-1K1
-----

repo: revert logic to get deb_arch

---

snapcraft/internal/repo/_deb.py
tests/unit/repo/test_deb.py

wine-devel-i386 does not have the explicit ":i386" tag, but
the virtual package is provided by "wine-devel-i386:i386".
Account for this possibility by resolving the package and
checking the architecture first, if no arch is specified by
the user.
- Revert the use of or_dependendencies back to target_versions
now that target_arch should correct the previously faulty
behavior (where target_versions ended up switching to the
incorrect arch after following an :any package).
- Fix apt.Package.architectures to architectures() method call.
-----

repo: fix for multi-arch virtual-packages

---

snapcraft/internal/meta/_snap_packaging.py
tests/unit/meta/test_snap_packaging.py

Keep the command-chain workaround for core, core16, core18 and the
case of no base (when used with build-base).
All other bases should follow user instruction and have no
command-chain if not specifically requested when using classic
confinement.
-----

meta: remove snapd workaround for classic for core20 onwards

---

snapcraft/internal/repo/_deb.py
snapcraft/internal/repo/apt_cache.py
tests/unit/lifecycle/__init__.py
tests/unit/repo/test_apt_cache.py
tests/unit/repo/test_deb.py

Re-introduce refactored AptCache to wrap apt-cache usage.
Use it in read-only mode for working with the host cache
for use with build-packages, and use it to create a new
transient cache for use with handling stage packages. It
will symlink the host /etc/apt configuration so it matches
the host configuration, but allow for an empty cache to mark
packages and dependencies for fetching.
The strategy of marking stage packages ourselves was more
complicated than it appeared, and this achieves a far better
result with less risk of affecting existing snaps.
Additionally this fixes primed-stage-packages, which mistakenly
was using a `:` instead of `=` to split the name and version.
TODO: unit tests and a spread test for the manifest …

repo: restore marked-install strategy for apt-cache

---

snapcraft/internal/build_providers/_lxd/_lxd.py
tests/spread/general/package-repositories/task.yaml
tests/unit/build_providers/lxd/test_lxd.py

core20 is missing it, ensure it is part of our bootstrapping
requirements.
Switch the package repositories to use lxd explicitly which has a
minimalist environment when compared to the one where spread runs.
-----

build providers: bootstrap with dirmngr

---

snapcraft/storeapi/v2/_api_schema.py
snapcraft/storeapi/v2/channel_map.py
tests/fake_servers/api.py
tests/unit/commands/__init__.py
tests/unit/commands/test_release.py
tests/unit/commands/test_status.py
tests/unit/store/v2/test_channel_map.py

Removed ``key`` from ``progressive`` dict following changes in the server API.

---

snapcraft/internal/errors.py
snapcraft/internal/repo/__init__.py
snapcraft/internal/repo/_base.py
snapcraft/internal/repo/_deb.py
snapcraft/internal/repo/apt_cache.py
tests/unit/repo/test_base.py
tests/unit/repo/test_deb.py
tests/unit/test_errors.py

Make sure cache is up to date by refreshing whenever a package
being requested is not already installed.

repo: always refresh cache when build packages are required

---

snapcraft/internal/sources/__init__.py

Previously it was enabled for Windows, but OS X will require
these as well for remote-build.
LP #1876326
-----

sources: enable git, local, and tar handlers for all platforms

---

snapcraft/internal/build_providers/_snap.py
tests/unit/build_providers/test_snap.py

hold refresh for 1 day for installed snaps

build providers: prevent snap refreshing in build environment

---

appveyor.yml
setup.py

The current versioning is gathered from debian/changelog which
is no longer maintained.  Use git-describe, with an additional
check to label the package -dirty if the tree is not porcelain.
-----

packaging: use git-based versioning for python package

---

snapcraft/plugins/v2/python.py
tests/unit/plugins/v2/test_python.py

Add the path to the interpreter instead of activating. From
Snapcraft's point of view this is essentially the only thing done by
activation.
LP: #1876162
-----

python v2 plugin: set path to the interpreter

---

snapcraft/internal/build_providers/_base_provider.py
tests/fixture_setup/_fixtures.py
tests/unit/build_providers/test_base_provider.py

1. If base doesn't match, clean the instance. (Existing behavior)
2. If base was not recorded, clean the instance.  This should fix
issues where environment was created by legacy snapcraft. (New)
3. If instance was created by newer snapcraft, clean the instance.
This should fix issues where build environment was created by
newer snapcraft versions which makes environment modifications
incompatible with older versions. (New)
- Update test scenarios to cover each compatbility scenario.
- Update SNAP_VERSION fixture to "4.0" for more realistic version.
- Use apt_pkg's version_compare to compare versions using debian
rules.
-----

build provider: clean incompatible build-environments

---

snapcraft/internal/elf.py

We cannot rely on iterating on the notes via the note segment.
Patchelf may move note sections into other segments, and worse
yet, possibly leave the note segment standing with invalid data.
Here we instead iterate over each section and (more) reliably
gather the note information.
There is some improvement that should be done on the patchelf
side, as `readelf` complains on these binaries, and other issues
have surfaced in the past (e.g. mesa in classic snaps).  However,
this will hopefully address snapcraft build-time issues with not
only our patched files for classic snaps, but externally patched
binaries that are being packaged.
Add a couple of developer logs to indicate when we are parsing
an ELF, so future investigations are easier when something explodes.
Signed-off-by: Chris …

elf: fix parsing of notes after patchelf mangling

---

snapcraft/plugins/v1/colcon.py

repo.ros2.org has uninstallable catkin-pkg due to a depdencency
on "python2" rather than "python".  The installation directions
now suggest using packages.ros.org/ros2 as the apt repository,
so we will switch to that since it is still working.
-----

colcon: use packages.ros.org/ros2 repository

---

snapcraft/cli/_channel_map.py
tests/unit/commands/test_status.py

Following logic was not considering previous states so all channels
were marked as closed instead of as following.
-----

cli: fix following hints in channel status

---

tests/spread/general/package-repositories/task.yaml

Use --destructive-mode for testing in autopkgtest until the
environment is verified to work.
-----

spread: only run in LXD with the google/multipass provider for repo

---

tests/spread/plugins/v2/snaps/python-hello-with-stage-package-dep/setup.py
tests/spread/plugins/v2/snaps/python-hello-with-stage-package-dep/snap/snapcraft.yaml

- Add 'appdirs' to install_requires.
- Set PYTHONPATH which will incorporate the stage-packages at build-time.  Otherwise pip will fetch and install these dependencies separately.
-----

spread tests: improvements for python-hello-with-stage-package-dep

---

snapcraft/plugins/v2/cmake.py
tests/unit/plugins/v2/test_cmake.py

This avoids errors on projects that check that the source directory
does not match the build directory.
-----

cmake v2 plugin: configure with $SNAPCRAFT_PART_SRC

---

snapcraft/cli/_errors.py

- Use inline typing (removing the need for noqa hints)
- Get rid of try/except clause considering 16.04 as we only care about
the snap now.
-----

cli: cleanup error handling

---

snapcraft/internal/pluginhandler/__init__.py
tests/spread/plugins/v1/rust/rebuild/task.yaml
tests/spread/plugins/v1/rust/rust-toolchain/task.yaml
tests/spread/plugins/v2/build-and-run-hello/task.yaml
tests/spread/plugins/v2/snaps/autotools-hello/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/cmake-hello/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/dump-hello/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/go-build-tags/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/go-mod-hello/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/make-hello/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/meson-hello-staged-python/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/meson-hello/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/npm-hello/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/python-hello-staged-python/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/python-hello-with-python-package-dep/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/python-hello-with-stage-package-dep/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/python-hello/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/rust-hello-features/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/rust-hello/snap/snapcraft.yaml

PluginV2 based parts were not able to clean due to the improper guard
set at the start of the clean_build method.
-----

pluginhandler: allow cleaning the build step

---

snapcraft/internal/build_providers/_snap.py
tests/unit/build_providers/test_snap.py

-----
This was prompted by the following post on the forums:
https://forum.snapcraft.io/t/error-no-changes-of-type-auto-refresh-found/17562
The error message comes from the `snap watch` call when no auto-refresh changes exist in the log.   We can suppress this error by adding a question mark to the change type, which also causes `snap watch` to return a success error code in this case.

build providers: don't show an error if there are no auto-refresh changes

---

snapcraft/plugins/v1/go.py
tests/spread/plugins/v1/go/run-go-mod/task.yaml
tests/spread/plugins/v1/go/snaps/go-mod-hello-with-env/go.mod
tests/spread/plugins/v1/go/snaps/go-mod-hello-with-env/go.sum
tests/spread/plugins/v1/go/snaps/go-mod-hello-with-env/main.go
tests/spread/plugins/v1/go/snaps/go-mod-hello-with-env/snap/snapcraft.yaml
tests/unit/plugins/v1/test_go.py

Add limited support for using Go Modules for 1.11 and 1.12 of Go.
The limitation when using 1.11 and 1.12 is that only the main module is
installed. This is due to limitations in "go build" in those versions,
to find the correct target, a new method "_get_module" is introduced.
A warning is issued when using 1.11 and 1.12 with a link on how to
enable support for Go Modules with precautions to only print the warning
once per execution.
Some general cleanup in GoPluing._build took place to remove repetition
of "domain" specific flag settings for when building and relinking.
LP: #1879315
-----

go v1 plugin: go.mod support for 1.11 and 1.12

---

snapcraft/cli/store.py
tests/unit/commands/test_status.py

Print a nicer message than the table headers with nothing in them.
LP: #1695241
-----

cli: nicer message for status with no releases

---

appveyor.yml

We can re-enable it in the future.  Windows support is still
unsupported at the moment anyhow.
-----

appveyor: disable artifact collection

---

snapcraft/internal/build_providers/_base_provider.py

Windows was interpreting HOME as \root which caused various failures.
When reading home, make sure we use the posix-formatted string.
-----

build providers: set HOME environment variable using posix format

---

snapcraft/internal/lifecycle/_packer.py

The snapd team has made the recommendation for Snapcraft to just use the
snap command from the host.
LP: #1862242
-----

lifecycle: use snap from path to --check-skeleton

---

snapcraft/storeapi/_store_client.py
tests/unit/store/test_store_client.py

storeapi: reset account_id on store login

---

snapcraft/internal/build_providers/_lxd/_lxd.py
tests/unit/build_providers/lxd/test_lxd.py

A DNS server is provided by LXD, we just need to configure
the host to use systemd-resolved for name resolution.
After installing these files, there is no need to restart
the container, just restart networkd.
-----

build providers: use LXD-provided DNS by default

---

snapcraft/internal/errors.py
snapcraft/internal/pluginhandler/__init__.py
tests/unit/test_errors.py

Iterate over plugin commands and run them in isolation. This allows
clearer error reporting. The same exception as in PluginV1 is raised on
command execution.
Fixes SNAPCRAFT-1NQ
-----

pluginhandler: run plugin commands in isolation

---

snapcraft/__init__.py
snapcraft/_store.py
snapcraft/cli/store.py
tests/unit/commands/test_close.py
todo.org

The implementation was moved to the CLI as being done for all commands.
With this, the new implementation for displaying a channel map is used,
which avoids the bug in the channel_map_tree returned in close that is
not progressive release aware and shows channels mistakenly as open.
The closed_channels API results are skipped as well as they are not
really track aware, returning mixed results for tracks in some scenarios
and plain risks for others (when latest is used, which is not allowed
when using more than one track).
The tests have been simplified to the concerns of the close CLI results
as display variants of the channel map tree are already done under test_status.
A missing todo checklist entry was added to take care of the upload logic.
Signed-off-by: Sergio Schvezov …

cli: migrate close to use the new channel map

---

snapcraft/internal/build_providers/_snap.py
tests/fake_servers/snapd.py
tests/unit/build_providers/test_snap.py

Avoid refreshing to "latest/stable" which is set to the default channel
to track in snapd when installing a snap that has a revision assertion.
The results:
```
$ snapcraft pull --use-lxd --shell
...
snapd 2.44.3 from Canonical✓ installed
"snapd" switched to the "latest/stable" channel
core18 20200427 from Canonical✓ installed
"core18" switched to the "latest/stable" channel
snapcraft 4.0.3 installed
"snapcraft" switched to the "latest/edge" channel
ubuntu # snap list
Name       Version   Rev   Tracking       Publisher   Notes
core18     20200427  1754  latest/stable  canonical✓  base
snapcraft  4.0.3     x1    latest/edge    -           classic
snapd      2.44.3    7264  latest/stable  canonical✓  snapd
```
-----

build providers: snap sw to channels if injecting

---

extensions/desktop/common/desktop-exports

-----
This commit changes the `prepend_dir` and `append_dir` functions to not use `eval` and to not check whether the directory exists when the path contains tokens. This makes it possible to use rpath tokens in the `LD_LIBRARY_PATH`. These tokens are useful to create paths which support multi-arch apps.
More info about rpath tokens: [ld.so man page](http://man7.org/linux/man-pages/man8/ld.so.8.html), [Using LD_PRELOAD mixed 64bit/32bit environment in Linux](https://stackoverflow.com/a/38253231/1588555).
*These versions of `pre/append_dir` and rpath tokens are already used in the [sommelier-core](https://github.com/snapcrafters/sommelier-core/blob/master/scripts/sommelier#L279) script to support Wine, which uses both 32-bit and 64-bit libraries when it runs 32-bit windows apps. The …

extensions: pre/append_dir: support rpath tokens by not using eval

---

snapcraft/internal/elf.py

Due to yet more patchelf mangling, snapcraft was tripping on
invalid tag data.  We can avoid this by iteration over the
dynamic sections.
LP: 1879519
-----

elf: search dynamic tags within sections, not segment

---

snapcraft/cli/_options.py

It currently doesn't have any effect, so rather than imply that
it is in fact working, disable it outright.  We will be working
toward expanding "--build-on" to target other architectures without
cross-compilation that is broken in many cases (like this).
-----

cli: disable --target-arch for multipass/lxd

---

snapcraft/internal/review_tools/_runner.py
tests/unit/review_tools/test_runner.py

Snapcraft issues the error when uploading classic snaps:
```
(NEEDS REVIEW) confinement 'classic' not allowed. If your snap needs classic confinement to function, please make a request for this snap to use classic by creating a new topic in the forum using the 'store-requests' category and detail the technical reasons why classic is required.
```
Since snapcraft doesn't know if the snap has already been approved,
allow classic during local review, and let the the store can return
the error from the upload's automatic review, which snapcraft will
handle gracefully.
-----

review-tools: add --allow-classic flag for local review

---

snapcraft/cli/_options.py
snapcraft/cli/remote.py
tests/spread/build-providers/lxd-prime-then-try/task.yaml
tests/spread/build-providers/lxd-try/task.yaml
tests/unit/cli/test_options.py
tests/unit/commands/test_remote.py

Sentry is filled with bug reports resulting from permission
errors due to mixed usage of sudo in different environments.
By checking for use of sudo, we can prevent most of these
errors from occurring.
- For lxd, multipass & remote-build users, exit with an error
if user is using sudo.
- For host (destructive-mode) users, warn if sudo is detected,
suggesting that the user also use sudo when cleaning.
Update spread tests to use `env -i` when using sudo.

cli: error/warn when using sudo

---

snapcraft/cli/lifecycle.py
snapcraft/project/_project.py
snapcraft/project/_sanity_checks.py

Rather than cross-compiling, which has numerous limitations,
this commit disables --target-arch. We need to work on expanding
support for --build-on to create an environment to target the
correct architecture.
-----

cli: disable --target-arch support on core20

---

snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/pluginhandler/_part_environment.py
snapcraft/plugins/v2/cmake.py
tests/spread/plugins/v2/build-and-run-hello/task.yaml
tests/spread/plugins/v2/snaps/cmake-hello-subdir/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/cmake-hello-subdir/subdir/CMakeLists.txt
tests/spread/plugins/v2/snaps/cmake-hello-subdir/subdir/hello.c
tests/unit/lifecycle/test_lifecycle.py
tests/unit/plugins/v2/test_cmake.py
tests/unit/project_loader/test_environment.py

Setup 2 _WORK variables, for the pull and build step, use
SNAPCRAFT_PART_SOURCE_WORK from get_build_commands instead of
SNAPCRAFT_PART_SOURCE.
-----

cmake v2 plugin: take source-subdir into account

---

snapcraft/cli/_options.py
snapcraft/cli/remote.py
tests/unit/cli/test_options.py
tests/unit/commands/test_remote.py

Some environments will `sudo` to another user.  To avoid
unnecessary warnings/errors, additionally check that the
effective user is root.
-----

cli: improve sudo detection with euid check for warnings/errors

---

snapcraft/internal/project_loader/_config.py
snapcraft/internal/project_loader/_parts_config.py

v1 plugins were unconditionally having their repositories installed
on the host when using a build environment.  Consolidate to previous
work in Config, creating a new method `install_package_repositories()`
to handle both v1 plugins and `package-repositories` configured repo
installation, when required.
-----

project loader: fix v1 plugin repository installation on host

---

snapcraft/plugins/v2/npm.py
tests/unit/plugins/v2/test_npm.py

That's where we are unpacking node to anyways, always include it.
If node is already in ${SNAPCRAFT_PART_INSTALL}/bin, then the PATH
never gets updated, breaking the build.
-----

npm v2 plugin: always include $SNAPCRAFT_PART_INSTALL/bin in $PATH

---

tests/unit/lifecycle/test_order.py

This is to ease the transition to pytest.
-----

tests: remove scenario usage from lifecycle order

---

snapcraft/plugins/_plugin_finder.py

Typo "catkin_tools" should be "catkin-tools".
We need a spread test for this plugin.
LP: #1882996
-----

plugins: fix loading of catkin-tools

---

snapcraft/internal/project_loader/_extensions/gnome_3_28.py
tests/unit/project_loader/extensions/test_gnome_3_28.py

extensions: add gcc to GNOME 3.28 extension part

---

snapcraft/internal/repo/_deb.py
snapcraft/internal/repo/apt_cache.py
tests/spread/general/virtual-packages/task.yaml
tests/unit/repo/test_deb.py

Virtual packages were not considered when checking if all build-packages
are satisfied between runs. Check and resolve with a warning to avoid
use of virtual packages for deterministic results.
Logic has shifted a bit to avoid exposing more functionality from
AptCache and have a nicer separation of concerns.
LP: #1883546
-----

repo: consider virtual pkgs for cache invalidation

---

snapcraft/cli/lifecycle.py

cli: don't warn about --target-arch if target_arch is None

---

snapcraft/internal/build_providers/_lxd/_lxd.py
snapcraft/internal/build_providers/errors.py
tests/unit/build_providers/lxd/test_lxd.py
tests/unit/build_providers/test_errors.py

Create a new exception to handle bad bases being used for LXD.
Fixes SNAPCRAFT-1H2
-----

build providers: nice message on bad base

---

snapcraft/internal/build_providers/_snap.py
tests/unit/build_providers/test_snap.py

Snapcraft was switching channels on the availability of a tracking
channel, it may be that this was incorrectly implemented or that snapd
now switched to always report a tracking-channel when installing a snap
with --dangerous after previously having installed a revision from the
Snap Store.
An additional check for revision is now enforced before setting the
switch.
LP: #1884576
-----

build providers: check revision before switching

---

snapcraft/plugins/v1/maven.py

-----
Recently joined Canonical and tried to build a Snap out of a Java library. The error seemed a bit difficult to understand at first (have done mostly Gradle before so was not used to Maven).
I have then improved a bit the error message to explain that it could just that maven-targets declaration does not match the directory in which the Java library has been built. To help the user better understand what could be wrong the error message has been improved to add the directories in which the `arfiles` were searched and clarifying a simple scenario (the one that happened to me) that could lead to fix the situation.
What I think it would help even more is to replace to have the actual part name at this point so that we could `Could not find built jar files for part [the name of the part …

Maven plugin: improve error message when target libs are not found.

---

extensions/desktop/common/desktop-exports

Also remove conditional check on the "base" vendor directory as
append_dir already takes care of directory existence.
Co-authored-by: Ken VanDine <ken.vandine@canonical.com>
-----

extensions: export content snap egl vendor dir

---

snapcraft/cli/_options.py

This simplifies checks for various option flags by ensuring the
environment variable is only set when true.
-----

cli: unset false boolean flags in environment

---

schema/snapcraft.json
snapcraft/internal/project_loader/_extensions/flutter_master.py
snapcraft/plugins/v1/flutter.py
specifications/flutter-extension.org
tests/spread/plugins/v1/flutter/snaps/flutter-hello/snap/snapcraft.yaml
tests/unit/plugins/v1/test_flutter.py
tests/unit/project_loader/extensions/test_flutter_master.py
todo.org

An extension that sets up an environment with flutter-master and is able
wraps the usage of GNOME into a dependency.
-----

extensions: introduce flutter-master

---

snapcraft.spec

Workaround PyInstaller & SetupTools pypa/setuptools#1963
-----

pyinstaller: workaround pkg_resources issue

---

tests/unit/plugins/v2/test_python.py

Fix broken tests that fell out of date after the removal
of virtual environment `activate` usage.
-----

tests: add missing asserts to python unit tests

---

setup.py
snap/snapcraft.yaml

If HEAD matches a tag, then version is simply the tag (e.g. 4.1.1).
If HEAD does not match a tag, then version indicating the distance to
last tag with the ".post" indicator and the git commit revision in
the local identifier (e.g. 4.1.1.post17+git92348a7eb).
Local identifiers should not be published publically, but since we only
push tagged versions to the pip index, this should not occur.
Now we can do package version comparisons, e.g.:
```
>>> from packaging import version
>>> version.parse("4.1.1") > version.parse("4.1.2")
False
>>> version.parse("4.1.1.post17+git92348a7eb") > version.parse("4.1.1")
True
```
Finally, match the snap version to the python package version to
ensure they stay in sync. Do this by querying setup.py for the
version number so only one implementation is …

packaging: use PEP-440 compliant versioning for python & snap

---

snap/snapcraft.yaml
snapcraft/internal/build_providers/_base_provider.py
tests/unit/build_providers/test_base_provider.py

Use the fixed path setup in the build environment, this brings parity to
the launchpad buildd environment and any other --destructive-mode
instance.
-----

snap: set PATH for snapcraft command

---

docker/beta.Dockerfile
docker/candidate.Dockerfile
docker/edge.Dockerfile
docker/stable.Dockerfile
docker/xenial-proposed.Dockerfile

Recent changes to snapcraft now require the use of `snap pack`,
so we must install the snapd package for Docker images to continue
to function.
-----

docker: install snapd dependency

---

snapcraft/cli/store.py

Snapcraft recommended to register <snap-name>-<username> to overcome
concerns about ownership of a given name. It was agreed a while ago to
prefix the username suggestion to have a common namespace for a
publisher for ordering/listing.
Minor updates to quoting were also done.
-----

cli: use prefix in store name registration hint

---

snap/snapcraft.yaml

Follow the advice of our own warning :)
-----

snap: specify 'libxslt1-dev' than virtual 'libxslt-dev' build-package

---

snapcraft/internal/build_providers/_base_provider.py

Now that we're using PEP-440 compliant versioning, use the version
objects provided by pkg_resources for comparison.
-----

build providers: use PEP-440 compliant version comparison operator

---

snapcraft/plugins/v2/cmake.py
tests/unit/plugins/v2/test_cmake.py

Also update the unit tests to use pytest.
-----
Done as noted on https://forum.snapcraft.io/t/porting-cmake-based-core18-snap-to-core20-snap-fails/18647/5 by @jhenstridge

cmake v2 plugin: add stage to CMAKE_PREFIX_PATH

---

snapcraft/internal/build_providers/_lxd/_lxd.py
tests/spread/build-providers/lxd-mknod/task.yaml
tests/spread/build-providers/snaps/devices/snap/snapcraft.yaml
tests/unit/build_providers/lxd/test_lxd.py

-----
When building a bootable base snap, it is common to include a few device files in `/dev` for the benefit of anything running in early boot before udev/devtmpfs is available.
However, trying to build such a snap with the LXD build provider fails because the `mknod` syscall is blocked by default for unprivileged containers.  LXD does provide a way to give unprivileged containers limited access to the syscall for device nodes it considers safe:
https://linuxcontainers.org/lxd/docs/master/syscall-interception#mknod-mknodat
This safe set of devices includes all of the ones included in the `core18` and `core20` snaps, so enabling it should allow bases like that to be built under LXD.

lxd: enable security.syscalls.intercept.mknod if supported to allow snaps to create some device nodes

---

snapcraft/internal/review_tools/_runner.py
tests/unit/review_tools/test_runner.py

Attempt to link and then copy the snap to review into the review-tools'
SNAP_USER_COMMON area to support the cases where the snap created in an
area the review tools cannot read from or the broader case of having the
"home" interface disconnected.
-----

review tools: link or copy snap to snap common

---

snapcraft/internal/meta/slots.py
tests/unit/meta/test_slots.py

If using the 'source' key, the content key was lost.  Fix
and add accompanying unit tests.
-----

meta: fix content slot to set content when using source key

---

snapcraft/internal/errors.py
tests/unit/test_errors.py

If a tool on the host is required, this exception
would be thrown if not found.
This differentiates from the ToolMissingError which
would be scoped to tools that are packaged with the
snapcraft snap.
-----

errors: introduce HostToolNotFoundError exception

---

extensions/desktop/kde-neon/launcher-specific

-----
This PR makes the KDE neon extension default to using the `gtk3` platform theme on GTK based desktops. This also enables the file chooser portal on those desktops, providing a completely native file chooser for the apps which support it.
The `kde-frameworks-*` platform snaps currently do not ship the `gtk3` platform theme or `QGnomePlatform`. This is not an issue, however, because Qt will fallback to `QGnomeTheme`, which is a builtin theme and is always available.
> Note: `QGnomeTheme` will use Xorg and XWayland to get theme info, so there are no additional connections required for snaps using it.
I'm still trying to figure out what the best way is to provide the `gtk3` platform themes to the snaps. Either I add them to the KDE-frameworks platform snaps, or I create a separate snap …

extensions: kde-neon: use gtk3 platform theme on gtk-based DE's

---

.travis.yml

It's useful to see test results regardless of the outcome
of the CLA checks.  This may encourage further development
of PRs while contributors work on getting their CLAs sorted out.
-----

travis: set cla check as final stage

---

snapcraft/plugins/v2/python.py
tests/spread/plugins/v2/snaps/python-hello-with-python-package-dep/snap/snapcraft.yaml
tests/unit/plugins/v2/test_python.py

If using a python package with conditionals, e.g.:
python-packages:
- ibm-db-sa; platform_machine == 'x86_64'
- ibm-db-sa; platform_machine == 'ppc64le'
- ibm-db-sa; platform_machine == 's390x'
Then snapcraft would pass the python packages unquoted to pip,
resulting in build errors.  Ensure the packages are quoted
safely using shlex.quote() when building the command string.
Update existing python-package spread test and python-package
unit test to cover this case.
LP: #1884429
-----

plugins v2: quote python packages argument for pip

---

tests/spread/general/classic-patchelf/task.yaml

ppc64el and others may not follow the `ld-linux` convention, e.g.:
/snap/core18/current/lib64/ld64.so.2
Fix by broadening the match to ld.*.
-----

spread tests: fix classic patchelf linker regex to match all arches

---

snapcraft/cli/lifecycle.py
snapcraft/file_utils.py
snapcraft/internal/errors.py
tests/unit/test_errors.py
tests/unit/test_file_utils.py

A counterpart to get_snap_tool_path() for finding commands inside of
snapcraft snap, this finds tools required on the host.
Raises snapcraft.internal.errors.SnapcraftHostToolNotFoundError if not found.
- Renames HostToolNotFoundError -> SnapcraftHostToolNotFoundError
- Uses this new method for lifecycle finding snapd.
- Update tests (and minor refactor to import 'errors' rather
than continue cherry-picking each exception import.)
-----

file utils: introduce get_host_tool_path() to find commands on host

---

extensions/desktop/common/desktop-exports

The system path needs precedence, as their contents are not looked through to find the highest priority one.
References:
- ubuntu/snapcraft-desktop-helpers#212
- https://github.com/NVIDIA/libglvnd/blob/master/src/EGL/icd_enumeration.md

extensions: prepend the snapd glvnd path

---

snapcraft/internal/common.py
snapcraft/internal/meta/_utils.py
snapcraft/internal/meta/command.py
snapcraft/internal/meta/errors.py
tests/unit/meta/test_command.py
tests/unit/meta/test_command_mangle.py

Better detail what command changes are happening and indicate why.
A little refactoring to make this possible in a fairly clean way.
Other than logging, there shouldn't be functional changes.
-----

meta: detailed warnings for resolution of commands

---

tests/spread/plugins/v2/build-and-run-hello/task.yaml
tests/spread/plugins/v2/colcon-ros2-hello/task.yaml

Requires splitting the task yaml to its own config.
Bump test time to 30m as well because the arm64 test may take
longer than the usual 15 or so minutes.
-----

tests: restrict colcon / ros2-foxy test to amd64 & arm64

---

snapcraft/internal/remote_build/_launchpad.py

A step towards standardizing on requests library.
When combined with PR #3252:
Fixes SNAPCRAFT-1ZK
-----

remote-build: use requests.get() instead of urlopen()

---

snapcraft/cli/extensions.py

Allow users to expand experimental extensions.
-----

cli: add --enable-experimental-extensions option for expand-extensions

---

snapcraft/internal/build_providers/_lxd/_images.py
tests/unit/build_providers/lxd/test_lxd.py

Switch the simplestreams endpoint from daily to releases to retrieve LXD
images.
Signed-off-by: Ubuntu <ubuntu@snapcraft-dev.lxd>
-----

build providers: use the releases endpoint for LXD

---

snapcraft/cli/_options.py

cli: ignore sudo warning when using multipass

---

extensions/desktop/common/desktop-exports

I've been working on the snap of FFmpeg and OBS Studio and noticed that VDPAU is not working correctly. This pull request sets  `VDPAU_DRIVER_PATH` appropriately and supports NVIDIA hardware when the host has the proprietary drivers installed.

Set VDPAU_DRIVER_PATH appropriately

---

snapcraft/internal/lxd/_containerbuild.py

Reverts snapcore/snapcraft#3239
Now that the former URL is restored, a quick fix for LP #1894656

Revert "lxd: update connectivity check url"

---

snapcraft/internal/build_providers/_lxd/_lxd.py
tests/unit/build_providers/lxd/test_lxd.py

The LXD setup is overly verbose. This is a first pass to hide some of
the many unnecessary things show by default (snapcraft's internal debug
still shows them).
-----

build providers: hide systemd setup for LXD

---

snapcraft/plugins/godeps.py
tests/unit/plugins/test_godeps.py

godeps hasn't been updated in quite some time, but it has
dependencies that need to be locked [1].  Specifically, go-toml
has been updated recently to require newer string interfaces,
requiring go 1.10+, breaking godeps projects on older go
versions.
Since godeps is used for dependency tracking (prior to go
modules), we lock in the dependencies ourselves by checking
out the correct revisions after downloading via go-get.
https://github.com/rogpeppe/godeps/blob/master/dependencies.tsv
-----

[legacy backport] v1 plugins: lock godep's dependencies

---

snapcraft/plugins/v1/godeps.py
tests/unit/plugins/v1/test_godeps.py

godeps hasn't been updated in quite some time, but it has
dependencies that need to be locked [1].  Specifically, go-toml
has been updated recently to require newer string interfaces,
requiring go 1.10+, breaking godeps projects on older go
versions.
Since godeps is used for dependency tracking (prior to go
modules), we lock in the dependencies ourselves by checking
out the correct revisions after downloading via go-get.
https://github.com/rogpeppe/godeps/blob/master/dependencies.tsv
-----

v1 plugins: lock godep's dependencies

---

requirements.txt
snapcraft/internal/db/datastore.py
snapcraft/internal/db/errors.py
snapcraft/internal/db/migration.py
tests/unit/db/test_datastore.py
tests/unit/db/test_errors.py
tests/unit/db/test_migration.py

Provides a generalized datastore for snapcraft components that
need persistent storage.  This datastore provides:
- a TinyDB-based storage system with YAML file-backed storage
- schema versioning with migration support
Initial use will be the environment manager datastore, allowing
snapcraft to better track all snapcraft-created build environments.
-----

db: introduce generalized datastore

---

snapcraft/internal/build_providers/_base_provider.py
tests/unit/build_providers/test_base_provider.py

Changed tempfile management when pushing assets to the build
environment as transfer opens the tempfile which caused issues on
Windows.
Fixed the path used on destination (os.path.join created a half breed
of Unix and Windows based paths).
Repository setup takes into account the platform.machine value
returned by Windows.
Lastly, and this affects all setups, deb-src was removed from the
default list as it is not default in most installations and should be
managed by package repositories if needed (Snapcraft has no apt source
semantics).
-----

build providers: fix issues running on Windows

---

snapcraft/internal/project_loader/_config.py

This was previously addressed by installing the required packages
in the LXD provider's setup environment and Multipass images already
have the required packages installed.  However, on Launchpad,
the required package would not be installed.
Install the required packages when additional package-repositories
are configured, including 'dirmngr' and 'gnupg' using
'Repo.install_build_packages()' which accounts for already-installed
packages.
-----

project loader: install dirmngr prior to configuring package repositories

---

snapcraft/internal/repo/_deb.py
tests/unit/repo/test_deb.py

It either was never implemented, or has been broken for a long time.
However, it is documented as supported, so install the
build-package versions as requested.
This requires passing '--allow-downgrades' to apt, in case the user
changes the desired build-package.  Additionally, now the version
for each apt package is explicitly specified for apt-get install.
LP: #1887960
-----

repo: install requested build-package versions

---

snapcraft/cli/lifecycle.py
tests/unit/cli/test_lifecycle.py
tests/unit/commands/test_snap.py

Currently one may only specify an explicit path to output snap
in the case of destructive mode.  For LXD/Multipass, one may only
specify the name of the snap within the project directory, otherwise
it gets "lost" in the container and is not retrieved.
This change allows output to point to an output directory, rather
than a snap file name.  This will help providers that may ship
multiple snaps, or users that want the snapcraft-provided name,
but rather have it shipped into a different directory.
NOTE that this change does not fix the still-broken case where
LXD/Multipass users specify a path outside of the project. This
should be addressed in upcoming work.
- Update _pack() to support the three uses of 'output'
- Introduce test coverage for _pack()
Signed-off-by: Chris Patterson …

cli: support snap --output <directory>

---

snapcraft/internal/build_providers/_base_provider.py
snapcraft/internal/build_providers/_snap.py
snapcraft/storeapi/_store_client.py
snapcraft/storeapi/info.py
tests/unit/build_providers/test_base_provider.py
tests/unit/build_providers/test_snap.py

The base build provider and SnapInjector() specifies the architecture of the
snap to download/install, which causes unnecessary coupling of the host <->
build provider architecture. While this could trivially determined, it appears
to be unnecessary as Snapd assumes the correct architecture to match the runtime
environment.
To preserve the functionality for potential usage in the future, this change
makes the arch field optional in get_channel_mapping() and download() store
APIs.
-----

storeapi: drop arch requirement for get_channel_mapping()

---

snapcraft/cli/_options.py
snapcraft/internal/build_providers/_base_provider.py
tests/unit/build_providers/test_base_provider.py

Allow user to specify a specific CA file, or directory of CA files,
to install into LXD or Multipass build environment.
- Adds `--install-ca-certificates <certs-path>` CLI option.
- Implement certification installation in base provider using
_push_file() and running `update-ca-certificates` on every launch.
- Update unit tests.
LP: #1807988
-----

cli: provide option to install ca certs into build environment

---

specifications/history-to-releases.org
todo.org

specifications: v1 history to v2 releases

---

runtests.sh

Instructions in `TESTING.md` for testing a subsuite don't work as expected: it just runs the whole suite.
Before:
```sh
$ ./runtests.sh tests/unit/commands
...
collected 3842 items                                                                                                                                                                                                                                        
...
```
After:
```sh
$ ./runtests.sh tests/unit/commands
...
collected 295 items                                                                                                                                                                                                                                         
...
```
- `shellcheck` throws a bunch of warnings, but I believe these …

unit tests: fix runtests.sh not filtering tests when passed a subdirectory

---

spread.yaml
tests/spread/electron-builder/no-template/electron-builder-hello-world/.gitignore
tests/spread/electron-builder/no-template/electron-builder-hello-world/electron-builder.yml
tests/spread/electron-builder/no-template/electron-builder-hello-world/index.html
tests/spread/electron-builder/no-template/electron-builder-hello-world/main.js
tests/spread/electron-builder/no-template/electron-builder-hello-world/package.json
tests/spread/electron-builder/no-template/electron-builder-hello-world/preload.js
tests/spread/electron-builder/no-template/electron-builder-hello-world/renderer.js
tests/spread/electron-builder/no-template/expected_snap.yaml
tests/spread/electron-builder/no-template/expected_snapcraft.yaml
tests/spread/electron-builder/no-template/task.yaml

Add test case for electron builder with `useTemplate: false`.
This scenario will invoke snapcraft for the build rather than
using their pre-canned snap template.
Compare the generated snapcraft.yaml and meta/snap.yaml.  These
will have to be updated as upstream changes, but this test is
most valuable to track the latest electron.
-----

spread tests: introduce electron-builder test

---

setup.py

When running from a shallow clone, the version detection fails to work out the
version, resulting in a ValueError that has a misleading trace.
When this occurs, assert with a helpful hint.
-----

setup.py: assert with helpful error when unable to determine version

---

snapcraft/cli/_channel_map.py
snapcraft/storeapi/v2/_api_schema.py
snapcraft/storeapi/v2/channel_map.py
tests/fake_servers/api.py
tests/unit/commands/__init__.py
tests/unit/commands/test_release.py
tests/unit/commands/test_status.py
tests/unit/store/v2/test_channel_map.py

Parse the [`"current-percentage"` Snap Store API field](https://dashboard.staging.snapcraft.io/docs/api/snap.html#about-progressive-releases) and show the current status of progressive releases on CLI.
- `shellcheck` throws a bunch of warnings, but I believe these are not related with this at all.
-----

storeapi: add support for reporting status of progressive releases

---

schema/snapcraft.json
snapcraft/internal/project_loader/_extensions/ros1_noetic.py
snapcraft/internal/project_loader/_extensions/ros2_foxy.py
snapcraft/internal/repo/_deb.py
snapcraft/plugins/v1/catkin.py
snapcraft/plugins/v1/colcon.py
specifications/package-repositories.org
tests/spread/general/snaps/test-apt-key-fingerprint/snap/snapcraft.yaml
tests/spread/general/snaps/test-apt-key-name/snap/snapcraft.yaml
tests/spread/general/snaps/test-apt-keyserver/snap/snapcraft.yaml
tests/unit/project/test_schema.py
tests/unit/project_loader/extensions/test_ros2_foxy.py
tests/unit/repo/test_deb.py

Remove prior to stabilization of package-repositories. We
can revisit in the future if required.
-----

package repositories: drop $SNAPCRAFT_APT_RELEASE variable

---

snapcraft/cli/snapcraftctl/_runner.py
snapcraft/internal/pluginhandler/_runner.py
tests/spread/general/scriptlets/scriptlet-failures/snap/snapcraft.yaml
tests/spread/general/scriptlets/task.yaml
tests/unit/commands/snapcraftctl/test_build.py
tests/unit/commands/snapcraftctl/test_set_grade.py
tests/unit/commands/snapcraftctl/test_set_version.py
tests/unit/pluginhandler/test_runner.py
tests/unit/pluginhandler/test_scriptlets.py

Address issues including:
- snapcraftctl operations always exiting with 0, even for failure
cases.
- snapcraft override scripts continue to run even after
parent snapcraft process fails.  This is because `set -e` does
not catch the error when snapcraftctl returns 0, and nothing
is otherwise done to terminate the script.
Given the nature of these symptoms, this is likely the cause of
a number of other seemingly unrelated issues.
These issues occur because _handle_builtin_function() only
catches exceptions of type errors.ScriptletBaseError,
ignoring other cases that may result from the build/pull operations,
such as NodejsPluginMissingPackageJsonError, or
SnapcraftPluginBuildError.
Instead of trying to manage exceptions in _handle_builtin_function(),
catch _any_ unhandled exception in …

plugin handler: properly handle snapcraftctl errors

---

snapcraft/cli/snapcraftctl/_runner.py
snapcraft/plugins/v1/catkin.py
snapcraft/plugins/v1/colcon.py
tests/unit/build_providers/lxd/test_lxd.py
tests/unit/commands/snapcraftctl/test_build.py
tests/unit/commands/snapcraftctl/test_set_grade.py
tests/unit/commands/snapcraftctl/test_set_version.py
tests/unit/pluginhandler/test_runner.py
tests/unit/pluginhandler/test_scriptlets.py
tests/unit/repo/test_deb.py

- Add common prefix args with defaults to be shared by all
tests in `LXD_RUN_COMMAND_PREFIX`.
- Remove mock to fake the environment args to capture all
flags relevant to LXD build provider.
- Make command checks much more concise using list
comprehension to filter out the prefix args and/or
using `LXD_RUN_COMMAND_PREFIX`.
-----

lxd unit tests: simplify command checking pattern

---

snapcraft/plugins/v1/_ros/rosdep.py

Sets `ROS_PYTHON_VERSION = 2` for the env used by `rosdep` to fix an harmless but annoying warning:
```terminal
WARNING: ROS_PYTHON_VERSION is unset. Defaulting to 2
```
Signed-off-by: artivis <deray.jeremie@gmail.com>
-----

set ROS_PYTHON_VERSION for rosdep

---

snapcraft/internal/meta/package_repository.py
snapcraft/internal/repo/_deb.py
snapcraft/plugins/v1/catkin.py
snapcraft/plugins/v1/colcon.py
tests/unit/meta/test_package_repository.py
tests/unit/repo/test_deb.py

It should assume "deb" if the list is empty or unspecified,
otherwise apt will complain.
Also rename remaining use of "deb_type" to "format" for
consistency.
-----

package repositories: fix case where formats is empty

---

specifications/package-repositories.org

This updates the spec to match the behavior intended for
the first stable release of `package-repositories`.
Changes include:
- introduction of `path` property to configure repositories
using absolute pathing, decoupling from `suites`.
- simplified key handling:
- always require 40 character key id
- find key at snap/keys/<key-id[0:8]>.asc
- error if any unused keys are present in snap/keys/
- add note on how to get GPG key ID from key file.
- removed exploratory conjecture about `name` field.
- other minor cleanup.
-----

specifications: finalization of package repositories spec
