canonical/snapcraft

.travis.yml, tests/integration/general/test_asset_recording.py, tests/os_release.py
-----
See https://forum.snapcraft.io/t/7339 for more information.
=> integration tests: disable tests using snaps in bionic container

snapcraft/cli/lifecycle.py, tests/unit/commands/__init__.py, tests/unit/commands/test_build_providers.py
=> build providers: use the provider if exported

requirements.txt
=> snap: move to a newer pysha3

snapcraft/internal/build_providers/_base_provider.py, snapcraft/internal/build_providers/_multipass/_multipass.py, snapcraft/internal/build_providers/_multipass/_multipass_command.py, snapcraft/internal/build_providers/errors.py, tests/unit/build_providers/multipass/test_multipass.py, tests/unit/build_providers/multipass/test_multipass_command.py, tests/unit/build_providers/test_base_provider.py, tests/unit/build_providers/test_errors.py
=> build providers: cleaner start and launch messaging

snapcraft/internal/meta/_snap_packaging.py, tests/unit/test_meta.py
=> meta: support relocatable prime for path verification

requirements.txt
-----
It was recently updated to 7.0 which changed the formatting enough to start failing our tests.
=> requirements.txt: pin click to v6

requirements.txt
-----
Backport of #2298 for legacy.
=> [legacy] requirements.txt: pin click to v6

snapcraft/internal/project_loader/grammar_processing/_part_grammar_processor.py, spread.yaml, tests/spread/plugins/python/dirty-autoclean/task.yaml, tests/spread/plugins/python/snaps/python-hello/hello, tests/spread/plugins/python/snaps/python-hello/setup.py, tests/spread/plugins/python/snaps/python-hello/snap/snapcraft.yaml, tests/spread/setup/restore.sh
-----
This PR is a backport of #2296, fixing [LP: #1794443](https://bugs.launchpad.net/snapcraft/+bug/1794443) for legacy.
=> [legacy] part grammar processor: lazily capture attributes from plugin

snapcraft/_store.py, snapcraft/cli/store.py, tests/integration/__init__.py
=> Use the better snapcraft.io/account URL

snapcraft/internal/meta/_snap_packaging.py, tests/unit/test_meta.py
=> meta: support relocatable prime for path verification (#2287)

tests/unit/commands/test_list_plugins.py
=> tests: use mocked plugins for list-plugins

snapcraft/plugins/nodejs.py
=> nodejs plugin: update to the latest 8.x LTS version

snapcraft/internal/project_loader/_extensions/_utils.py, tests/unit/project_loader/extensions/test_utils.py
-----
Currently extensions are naively applied as they're discovered, which causes problems when multiple apps use the same extension. This PR fixes [LP: #1797638](https://bugs.launchpad.net/snapcraft/+bug/1797638) by parsing all declared extensions before applying any.
=> extensions: parse all declared extensions before applying

MANIFEST.in, debian/snapcraft-completion, setup.py, snapcraft/cli/extensions.py, snapcraft/internal/project_loader/__init__.py, snapcraft/internal/project_loader/_extensions/__init__.py, snapcraft/internal/project_loader/_extensions/_extension.py, snapcraft/internal/project_loader/_extensions/_utils.py, tests/unit/commands/test_extensions.py, tests/unit/project_loader/extensions/test_extensions.py
-----
This PR resolves [LP: #1791172](https://bugs.launchpad.net/snapcraft/+bug/1791172) by making sure extensions are properly installable and also adds a few generic tests to smoke test future extensions.
=> extensions: cleanup and generic tests

snapcraft/_baseplugin.py, tests/unit/pluginhandler/test_plugin_loader.py, tests/unit/plugins/test_jhbuild.py, tests/unit/plugins/test_qmake.py, tests/unit/plugins/test_waf.py
=> schema: remove deprecated plugin pull and build-properties

.travis.yml
Also remove the unsused docker service.
-----
=> ci: use more travis primitives for osx tests

snapcraft/internal/project_loader/_config.py, tests/unit/lifecycle/test_lifecycle.py
=> project: do not install base if already installed

snapcraft/internal/build_providers/_base_provider.py, snapcraft/internal/build_providers/_multipass/_multipass.py, tests/unit/build_providers/__init__.py, tests/unit/build_providers/multipass/test_multipass.py, tests/unit/build_providers/test_base_provider.py
Fixes SNAPCRAFT-78
Fixes SNAPCRAFT-7A
LP: #1801965
-----
=> build providers: fix osx non base and injection

tests/spread/plugins/maven/snaps/maven-hello/snap/snapcraft.yaml
=> tests: fix maven spread test

spread.yaml
=> ci: reduce spread system declarations

.travis.yml, tests/spread/general/multipass/task.yaml, tests/unit/test_meta.py
=> ci: update travis.yaml to use xenial

snapcraft/cli/_command_group.py, snapcraft/cli/_runner.py, snapcraft/cli/legacy.py, tests/spread/legacy/cleanbuild-no-base-invalid-yaml/task.yaml, tests/spread/legacy/cleanbuild-with-base-invalid-yaml/task.yaml, tests/spread/legacy/cleanbuild-with-base-valid-yaml/task.yaml, tests/spread/legacy/snaps/cleanbuild-no-base-invalid-yaml/snapcraft.yaml, tests/spread/legacy/snaps/cleanbuild-with-base-invalid-yaml/snapcraft.yaml, tests/spread/legacy/snaps/cleanbuild-with-base-valid-yaml/snapcraft.yaml, tests/unit/commands/test_cleanbuild.py
=> cli: handle yaml errors for cleanbuild

snapcraft/yaml_utils.py, tests/spread/general/unicode-metadata/expected_snap.yaml, tests/spread/general/unicode-metadata/snap/snapcraft.yaml, tests/spread/general/unicode-metadata/task.yaml
=> yaml_utils: allow unicode while encoding

snapcraft/yaml_utils.py, tests/spread/general/unicode-metadata/expected_snap.yaml, tests/spread/general/unicode-metadata/snap/snapcraft.yaml, tests/spread/general/unicode-metadata/task.yaml
=> yaml_utils: allow unicode while encoding (#2414)

schema/snapcraft.yaml, snapcraft/internal/meta/_snap_packaging.py, tests/unit/project/test_schema.py, tests/unit/test_meta.py
=> schema: add support for title

debian/changelog, tests/spread/plugins/go/snaps/go-gotty/snap/snapcraft.yaml, tests/spread/plugins/godeps/snaps/godeps-use-build-packages/snap/snapcraft.yaml, tests/spread/plugins/godeps/snaps/godeps-with-go-packages/snap/snapcraft.yaml, tests/spread/plugins/godeps/snaps/godeps/snap/snapcraft.yaml
=> Release changelog for 3.0.1

requirements-devel.txt, setup.py, snapcraft/extractors/setuppy.py, snapcraft/file_utils.py, snapcraft/internal/build_providers/_base_provider.py, snapcraft/internal/repo/snaps.py, snapcraft/plugins/_python/_pip.py, snapcraft/plugins/catkin.py, snapcraft/plugins/kbuild.py, snaps_tests/__init__.py, tests/integration/__init__.py, tests/integration/store/test_store_register.py, tests/integration/store/test_store_revisions.py, tests/unit/build_providers/test_base_provider.py, tests/unit/commands/test_push.py, tests/unit/pluginhandler/test_pluginhandler.py, tests/unit/project/test_schema.py, tools/cla_check.py
=> static: update to the latest flake8

snapcraft/internal/common.py, snapcraft/internal/lifecycle/_clean.py, snapcraft/internal/lifecycle/_runner.py, snapcraft/internal/meta/_snap_packaging.py, snapcraft/project/_project.py, tests/unit/sources/test_local.py
=> project: state file path change

snapcraft/internal/errors.py, snapcraft/internal/lifecycle/_clean.py, tests/unit/test_errors.py
LP: #1807443
Fixes SNAPCRAFT-49
-----
=> clean: user friendly message when cleaning

tests/spread/plugins/plainbox/snaps/checkbox/snap/snapcraft.yaml, tests/spread/plugins/plainbox/snaps/provider-basic/snap/snapcraft.yaml, tests/spread/plugins/plainbox/snaps/provider-python-stage-package-mix/snap/snapcraft.yaml, tests/spread/plugins/plainbox/snaps/provider-with-deps/snap/snapcraft.yaml, tests/spread/plugins/plainbox/snaps/provider-with-stage-packages/snap/snapcraft.yaml
=> tests: use fixed version for idna in plainbox

snap/snapcraft.yaml, tools/snapcraft-override-build.sh
=> snap: re-add pyc files for snapcraft

.travis.yml, snapcraft/plugins/rust.py, spread.yaml, tests/spread/plugins/rust/revision/task.yaml, tests/unit/plugins/test_rust.py
=> rust plugin: update to use latest rustup command options

snap/snapcraft.yaml
=> snap: add build-package for xml

snapcraft/extractors/appstream.py, snapcraft/extractors/setuppy.py, snapcraft/internal/meta/_snap_packaging.py, snapcraft/internal/pluginhandler/__init__.py, snapcraft/internal/pluginhandler/_metadata_extraction.py, tests/unit/extractors/test_appstream.py, tests/unit/extractors/test_setuppy.py, tests/unit/pluginhandler/test_metadata_extraction.py, tests/unit/pluginhandler/test_pluginhandler.py, tests/unit/test_meta.py
=> Appstream desktop

.travis.yml, HACKING.md, requirements.txt, snap/snapcraft.yaml, snapcraft/extractors/appstream.py, spread.yaml, tools/travis/run_integration_test.sh
=> snap: add xslt dependencies for lxml

snapcraft/internal/meta/_snap_packaging.py, tests/unit/test_meta.py
-----
Fixes https://bugs.launchpad.net/snapcraft/+bug/1812003
=> meta: make hooks executable instead of complaining they're not

debian/changelog, tests/spread/plugins/rust/revision/task.yaml, tests/unit/extractors/test_appstream.py, tests/unit/lifecycle/test_lifecycle.py, tests/unit/plugins/test_rust.py
=> Release changelog for 3.1

snapcraft/extractors/setuppy.py
=> Fix typo in comments

snapcraft/plugins/catkin.py
-----
Add the documentation blurb left out of the fix for [LP: #1721168.](https://bugs.launchpad.net/snapcraft/+bug/1721168).
=> catkin plugin: describe how to build all packages

debian/changelog
=> Release changelog for 3.1.1

.travis.yml
=> ci: shallow clones for CLA checks on travis

debian/changelog
=> Release changelog for 3.2

tests/integration/__init__.py
=> Test store

snapcraft/internal/build_providers/errors.py, tests/unit/build_providers/test_errors.py
=> Build provider errors

debian/changelog, tests/spread/plugins/ament/snaps/ros2-talker-listener/snap/snapcraft.yaml, tests/spread/plugins/ant/run/task.yaml, tests/spread/plugins/autotools/cross_compile/task.yaml, tests/spread/plugins/go/cross_compile/task.yaml, tests/spread/plugins/go/cross_compile_cgo/task.yaml, tests/spread/plugins/kbuild/cross_compile/task.yaml, tests/spread/plugins/maven/run/task.yaml, tests/spread/plugins/waf/cross-compile/task.yaml
=> Release changelog for 3.3

README.md
=> readme: add snap store badge

snapcraft/cli/_options.py, snapcraft/cli/lifecycle.py
=> cli: cleanup environment detection

tests/spread/plugins/ant/classic/task.yaml, tests/spread/plugins/ant/snaps/ant-hello/snap/snapcraft.yaml, tests/spread/plugins/autotools/classic/task.yaml, tests/spread/plugins/go/rpath-rewrite-cgo/task.yaml, tests/spread/plugins/maven/classic/task.yaml, tests/spread/plugins/rust/classic/task.yaml, tests/spread/tools/snapcraft-yaml.sh
=> tests: classic confinement spread tests for ant and maven 

debian/changelog
=> release: 3.4.1

.gitignore
=> vcs: ignore .idea

snapcraft/storeapi/status.py, tests/fake_servers/api.py, tests/integration/store/test_store_promote.py, tests/integration/store/test_store_status.py, tests/unit/store/test_store_client.py
=> Promote branches fix

debian/changelog, tests/fake_servers/search.py
=> Release changelog for 3.5

requirements.txt
=> requirements: update to requests-toolbelt 0.8.0

HACKING.md, tools/environment-setup.sh
Make it consistent to a single environment and easier to setup.
-----
=> docs: consolidate on a simple HACKING.md

tests/spread/plugins/plainbox/snaps/provider-with-deps/snap/snapcraft.yaml
=> plainbox spread tests: use https for the git source entries

snapcraft/internal/common.py, tests/unit/test_common.py
=> Legacy is deb

debian/changelog, tests/unit/store/test_store_client.py
=> Release changelog for 3.5.1

docker/beta.Dockerfile, docker/candidate.Dockerfile, docker/edge.Dockerfile, docker/stable.Dockerfile
=> docker images: use build stages and generate locale

docker/beta.Dockerfile, docker/candidate.Dockerfile, docker/edge.Dockerfile, docker/stable.Dockerfile
=> docker images: update to be self contained

tools/environment-setup.sh
=> tools: add `black` snap to environment-setup.sh

snapcraft/cli/ci.py, snapcraft/internal/deltas/_deltas.py, snapcraft/internal/lifecycle/_packer.py, snapcraft/plugins/cmake.py, snapcraft/storeapi/_sca_client.py, snapcraft/storeapi/errors.py, tests/fake_servers/api.py, tests/unit/build_providers/multipass/test_instance_info.py, tests/unit/build_providers/test_errors.py, tests/unit/commands/__init__.py, tests/unit/project/test_errors.py, tests/unit/project_loader/grammar_processing/test_global_grammar_processor.py, tests/unit/project_loader/test_build_packages.py, tests/unit/store/test_store_client.py, tests/unit/test_errors.py
=> static: update to newer black

snapcraft/internal/repo/_deb.py, spread.yaml, tests/unit/repo/test_deb.py
Only show "Questions that you really, really need to see
(or else)."
LP: #1821313
-----
=> repo: set priority to critical for debs

debian/changelog
=> Release changelog 3.6

mypy.ini, snapcraft/internal/project_loader/inspection/_latest_step.py, snapcraft/plugins/dotnet.py, tests/unit/project_loader/test_schema.py
=> black: minor format changes from updated black

.travis.yml, tools/environment-setup.sh
=> static: use beta channel for black

requirements.txt, snapcraft/plugins/rust.py, tests/unit/plugins/test_rust.py
=> rust plugin: use toml to dump the config

snapcraft/internal/sources/_script.py, snapcraft/plugins/conda.py, spread.yaml, tests/integration/general/test_list_plugins.py, tests/spread/plugins/conda/run/task.yaml, tests/spread/plugins/conda/snaps/conda-hello/snap/snapcraft.yaml, tests/unit/plugins/test_conda.py
=> conda plugin: new plugin

spread.yaml
=> spread: use more workers to reduce job times

snapcraft/plugins/ant.py, tests/unit/plugins/test_ant.py
=> ant plugin: switch to using ant snap for building (by default)

snapcraft/plugins/colcon.py, tests/spread/plugins/colcon/run/task.yaml, tests/spread/plugins/colcon/snaps/colcon-talker-listener/snap/snapcraft.yaml, tests/spread/plugins/colcon/snaps/colcon-talker-listener/src/listener_py/launch/talk_and_listen.launch.py, tests/spread/plugins/colcon/snaps/colcon-talker-listener/src/listener_py/listener.py, tests/spread/plugins/colcon/snaps/colcon-talker-listener/src/talker_cpp/main.cpp, tests/unit/plugins/test_colcon.py
-----
ROS 2 Dashing was recently released. This PR adds support to the colcon plugin.
=> colcon plugin: add support for dashing

snapcraft/cli/_errors.py, snapcraft/cli/_options.py, snapcraft/cli/assertions.py, snapcraft/cli/ci.py, snapcraft/cli/echo.py, snapcraft/cli/lifecycle.py, snapcraft/cli/store.py, snapcraft/internal/build_providers/_base_provider.py, snapcraft/internal/build_providers/_multipass/_multipass.py, tests/integration/__init__.py, tests/unit/build_providers/__init__.py, tests/unit/build_providers/multipass/test_multipass.py, tests/unit/cli/test_echo.py, tests/unit/cli/test_errors.py, tests/unit/commands/__init__.py
=> Legacy errors

snapcraft/cli/store.py
Clarify what is being pushed.
-----
=> cli: improve help for push-metadata

snapcraft/cli/_errors.py
=> cli: only say sorry for in-snapcraft issues

snapcraft/internal/build_providers/_lxd/_lxd.py, snapcraft/internal/build_providers/errors.py, tests/unit/build_providers/test_errors.py
=> build providers: catch LXD socket error

debian/changelog
=> Release changelog for 3.7.1

snapcraft/cli/extensions.py, snapcraft/internal/project_loader/_extensions/_extension.py, snapcraft/internal/project_loader/_extensions/_utils.py, snapcraft/internal/project_loader/errors.py, tests/unit/commands/test_extensions.py, tests/unit/project_loader/extensions/test_utils.py
=> Extension confinement

debian/changelog
=> Release changelog for 3.7.2

snapcraft/plugins/rust.py, spread.yaml, tests/unit/plugins/test_rust.py
=> rust plugin: support for s390x

snapcraft/internal/build_providers/_multipass/_multipass_command.py
In setup_multipass, there is a case where multipass installs OK, but then
the call to check the version info fails with FileNotFoundError.
The most plausible explanation is that the multipass snap installs OK,
but /snap/bin is not in the PATH, so multipass is not found. This is
easily reproduced.
When this occurs, raise SnapcraftEnvironmentError() with
an error message suggesting the user check their PATH.
Catching this exception was the straw that broke the flake8 "is too
complex" check, so move the wait loop into _wait_for_multipass_ready() -
and flip "multipass" to cls.provider_cmd for consistency.
Fixes SNAPCRAFT-10S
-----
=> multipass: fix setup exception when multipass is not found in PATH 

debian/changelog, debian/tests/integrationtests-spread, tests/spread/extensions/gnome-3-28/task.yaml, tests/spread/general/stage_snaps/task.yaml, tests/spread/general/unicode-metadata/task.yaml, tests/spread/legacy/command-cleanbuild/task.yaml, tests/spread/plugins/rust/cross-compile/task.yaml
=> Release changelog for 3.8

.gitignore, debian/changelog, snapcraft/plugins/rust.py, spread.yaml, tests/spread/general/unicode-metadata/task.yaml, tests/spread/plugins/catkin/catkin-with-python/task.yaml, tests/spread/plugins/catkin/content-sharing/task.yaml, tests/spread/plugins/catkin/pip-support/task.yaml, tests/spread/plugins/catkin/recursive-rosinstall/task.yaml, tests/spread/plugins/catkin/run/task.yaml, tests/unit/plugins/test_rust.py
=> Release changelog for 2.44

.travis.yml, snap/snapcraft.yaml, snapcraft/extractors/appstream.py, spread.yaml, tests/integration/__init__.py, tests/spread/unit/coverage/task.yaml, tools/environment-setup.sh, tools/snapcraft-override-build.sh
=> snap: migrate to core18

CODE_OF_CONDUCT.md
=> docs: add a Code of Conduct

snapcraft/_store.py, tests/integration/store/test_store_close.py, tests/integration/store/test_store_gated.py, tests/integration/store/test_store_promote.py, tests/integration/store/test_store_push.py, tests/integration/store/test_store_push_metadata.py, tests/integration/store/test_store_register.py, tests/integration/store/test_store_release.py, tests/integration/store/test_store_revisions.py, tests/integration/store/test_store_sign_build.py, tests/integration/store/test_store_status.py, tests/integration/store/test_store_validate.py, tests/integration/store/test_store_whoami.py, tests/unit/commands/test_create_key.py, tests/unit/commands/test_gated.py, tests/unit/commands/test_list_keys.py, tests/unit/commands/test_list_registered.py, tests/unit/commands/test_list_revisions.py, tests/unit/commands/test_push.py, tests/unit/commands/test_push_metadata.py, tests/unit/commands/test_register.py, tests/unit/commands/test_release.py, tests/unit/commands/test_status.py, tests/unit/commands/test_validate.py, tests/unit/commands/test_whoami.py
Promp to login if it is required instead of exiting with an error.
-----
=> cli: prompt for login if required

extensions/desktop/common/desktop-exports, extensions/desktop/kde-neon/Makefile, extensions/desktop/kde-neon/desktop-exports, extensions/desktop/kde-neon/init, extensions/desktop/kde-neon/launcher-specific, extensions/desktop/kde-neon/locale-gen, extensions/desktop/kde-neon/mark-and-exec, schema/snapcraft.json, snapcraft/internal/project_loader/_extensions/kde_neon.py, tests/spread/extensions/kde-neon/task.yaml, tests/spread/extensions/snaps/neon-hello/CMakeLists.txt, tests/spread/extensions/snaps/neon-hello/hello.cpp, tests/spread/extensions/snaps/neon-hello/snap/snapcraft.yaml, tests/unit/project_loader/extensions/test_kde_neon.py
=> Neon extension

snapcraft/_store.py, snapcraft/storeapi/constants.py, tests/integration/__init__.py, tests/unit/commands/__init__.py, tests/unit/commands/test_create_key.py, tests/unit/commands/test_export_login.py, tests/unit/commands/test_gated.py, tests/unit/commands/test_list_keys.py, tests/unit/commands/test_list_registered.py, tests/unit/commands/test_list_revisions.py, tests/unit/commands/test_login.py, tests/unit/commands/test_promote.py, tests/unit/commands/test_push.py, tests/unit/commands/test_push_metadata.py, tests/unit/commands/test_register.py, tests/unit/commands/test_register_key.py, tests/unit/commands/test_release.py, tests/unit/commands/test_status.py, tests/unit/commands/test_validate.py, tests/unit/integrations/test_travis.py
=> cli: use click utilities for login prompts

snapcraft/cli/remote.py, snapcraft/internal/remote_build/_launchpad.py, snapcraft/internal/remote_build/errors.py, snapcraft/project/_project.py, tests/unit/remote_build/test_launchpad.py
=> remote-build: https token support

schema/snapcraft.json, snapcraft/internal/meta/_snap_packaging.py, snapcraft/internal/meta/errors.py, snapcraft/internal/meta/snap.py, snapcraft/internal/repo/snaps.py, snapcraft/plugins/make.py, tests/unit/__init__.py, tests/unit/build_providers/multipass/test_multipass_command.py, tests/unit/build_providers/test_snap.py, tests/unit/lifecycle/test_lifecycle.py, tests/unit/meta/test_errors.py, tests/unit/meta/test_meta.py, tests/unit/meta/test_snap.py, tests/unit/project/test_schema.py, tests/unit/repo/test_snaps.py
=> Core20 base

debian/changelog
=> Release changelog for 3.9

requirements.txt, snapcraft/internal/lifecycle/_runner.py, snapcraft/internal/meta/_snap_packaging.py, snapcraft/internal/meta/snap.py, snapcraft/internal/states/_global_state.py, tests/unit/lifecycle/__init__.py, tests/unit/lifecycle/test_lifecycle.py, tests/unit/meta/test_meta.py, tests/unit/meta/test_snap.py, tests/unit/states/test_global_state.py
=> Safe grade

debian/changelog
=> Release changelog for 3.9.1

requirements.txt, snapcraft/cli/_config.py, snapcraft/cli/lifecycle.py, snapcraft/cli/remote.py, tests/unit/cli/test_config.py
=> snapcraft: introduce click-based YAML configuration file support

snapcraft/cli/_options.py, snapcraft/internal/build_providers/_base_provider.py, snapcraft/internal/build_providers/_lxd/_lxd.py, snapcraft/internal/build_providers/_multipass/_multipass.py, tests/unit/build_providers/__init__.py, tests/unit/build_providers/test_base_provider.py
Introduce support for binding user's .ssh to local LXD and Multipass build environments.
Depends on #2786 and #2078
=> introduce bind-ssh support

tests/spread/plugins/plainbox/run/task.yaml, tests/spread/plugins/plainbox/snaps/checkbox/snap/snapcraft.yaml, tests/unit/build_providers/__init__.py
=> Plainbox test updates

TESTING.md, requirements-devel.txt, runtests.sh, snapcraft.spec, snapcraft/internal/common.py, snapcraft/internal/meta/snap.py, snapcraft/internal/project_loader/_config.py, snapcraft/internal/sources/_checksum.py, snapcraft/plugins/_python/_pip.py, snapcraft/plugins/catkin.py, snapcraft/project/errors.py, snapcraft/shell_utils.py, tests/integration/snaps/circular-dependencies/tree/snapcraft.yaml, tests/spread/plugins/kernel/pull/task.yaml, tests/unit/test_common.py
Sync everything except mypy in requirements-devel.txt to the latest, making minor changes, as necessary.
=> uprev devel python package requirements

snapcraft/cli/lifecycle.py, snapcraft/cli/remote.py
Type fixes and missing argument fix for cli that should not affect runtime behavior.
-----
=> cli: address type errors for mypy uprev 

snapcraft/internal/meta/_snap_packaging.py, snapcraft/internal/meta/application.py, snapcraft/internal/meta/command.py, snapcraft/internal/meta/plugs.py, snapcraft/internal/meta/slots.py, snapcraft/internal/meta/snap.py
Assorted changes to address mypy errors in newer mypy.
Mostly fixes that should not affect runtime behavior.  But a couple do possibly improve handling in unexpected cases, should they ever occur.
=> meta: address errors from mypy uprev

snapcraft/plugins/_python/_pip.py, snapcraft/plugins/cmake.py, snapcraft/plugins/python.py
Type fixes for plugins that should not affect runtime behavior.
=> plugins: address type errors for mypy uprev

snapcraft/extractors/_metadata.py, snapcraft/extractors/appstream.py, snapcraft/extractors/setuppy.py
=> extractors: address errors from mypy uprev

snapcraft/_store.py, snapcraft/cli/store.py, snapcraft/storeapi/_store_client.py, snapcraft/storeapi/channels.py, snapcraft/storeapi/errors.py, snapcraft/storeapi/info.py, tests/integration/store/test_store_push.py
=> store: address errors from mypy uprev

snapcraft/internal/pluginhandler/__init__.py
=> pluginhandler: address errors from mypy uprev

snapcraft/internal/build_providers/_base_provider.py, snapcraft/internal/build_providers/_lxd/_lxd.py, snapcraft/internal/build_providers/_multipass/_multipass.py, snapcraft/internal/build_providers/_multipass/_windows.py, snapcraft/internal/build_providers/_snap.py, tests/unit/commands/test_build_providers.py
=> build-providers: address errors from mypy uprev

snapcraft/config.py, snapcraft/file_utils.py, snapcraft/internal/cache/_file.py, snapcraft/internal/dirs.py, snapcraft/internal/elf.py, snapcraft/internal/lifecycle/_clean.py, snapcraft/internal/lifecycle/_runner.py, snapcraft/internal/remote_build/_launchpad.py, snapcraft/internal/steps.py, snapcraft/project/_project_options.py, snapcraft/yaml_utils.py, tests/fake_servers/__init__.py, tests/integration/general/test_hooks.py, tests/os_release.py, tests/unit/remote_build/test_launchpad.py
Most of the remaining fixes that didn't really warrant breaking up into their own PRs.
=> assorted: address errors from mypy uprev

snapcraft/internal/project_loader/_extensions/_utils.py, snapcraft/internal/project_loader/_extensions/gnome_3_28.py, snapcraft/internal/project_loader/_extensions/kde_neon.py, snapcraft/internal/project_loader/grammar/_on.py, snapcraft/internal/project_loader/grammar/_processor.py, snapcraft/internal/project_loader/grammar/_statement.py, snapcraft/internal/project_loader/grammar/_to.py, snapcraft/internal/project_loader/inspection/_latest_step.py, snapcraft/internal/project_loader/inspection/_provides.py
=> project-loader: address errors from mypy uprev

CODE_STYLE.md, HACKING.md, tools/environment-setup.sh
=> minor developer env/doc updates

snap/snapcraft.yaml
- [ :heavy_check_mark: ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
-----
=> snap: add license to snapcraft.yaml

snapcraft/extractors/appstream.py, tests/unit/extractors/test_appstream.py
=> appstream extractor: take xml comments into account

snapcraft/plugins/go.py, tests/spread/plugins/go/run-go-mod/task.yaml, tests/spread/plugins/go/snaps/go-mod-hello/go.mod, tests/spread/plugins/go/snaps/go-mod-hello/go.sum, tests/spread/plugins/go/snaps/go-mod-hello/main.go, tests/spread/plugins/go/snaps/go-mod-hello/snap/snapcraft.yaml, tests/unit/plugins/test_go.py
=> Support for go.mod

CODE_STYLE.md
- [] Have you successfully run `./runtests.sh static`?
- [] Have you successfully run `./runtests.sh tests/unit`?
-----
=> Add punctuation rule for comments

snapcraft/internal/meta/plugs.py, snapcraft/internal/meta/slots.py, tests/unit/meta/test_plugs.py, tests/unit/meta/test_slots.py
if plug has no subelement, then the interface changes crash this
=> plugs: plugs can have no element

schema/snapcraft.json, snapcraft/internal/meta/errors.py, snapcraft/internal/meta/snap.py, snapcraft/internal/meta/system_user.py, tests/unit/meta/test_errors.py, tests/unit/meta/test_snap.py, tests/unit/meta/test_system_user.py, tests/unit/project/test_schema.py
=> add support for system-usernames

.travis.yml
=> docker: test image builds with Travis CI

extensions/desktop/common/desktop-exports, extensions/desktop/gnome/launcher-specific, extensions/desktop/kde-neon/launcher-specific
=> Use ensure_dir_exists instead of mkdir -p

snapcraft/internal/lifecycle/_runner.py, snapcraft/internal/meta/plugs.py, snapcraft/internal/meta/slots.py, snapcraft/internal/meta/snap.py, snapcraft/internal/repo/snaps.py, tests/spread/general/content-interface-provider-found/snaps/provider/snap/snapcraft.yaml, tests/spread/general/content-interface-provider-found/task.yaml, tests/spread/general/content-interface-provider-not-found/snaps/provider/snap/snapcraft.yaml, tests/spread/general/content-interface-provider-not-found/task.yaml, tests/unit/meta/test_plugs.py, tests/unit/meta/test_slots.py, tests/unit/meta/test_snap.py
=> 3.9 cherrypicks

requirements-devel.txt
=> requirements-devel: uprev pyinstaller to 3.6

tests/integration/store/test_store_status.py
=> tests: fix status test for staging store

.travis.yml, tools/travis_deploy.sh
-----
This is just like #2899 which I use to verify that both scenarios work
=> ci: publish the CI built snap to the Snap Store

snapcraft/storeapi/_agent.py, tests/fixture_setup/os_release.py, tests/unit/store/test_agent.py
Also add support for Windows and Darwin.
-----
=> store: improve platform detection

.travis.yml, requirements.txt, snap/snapcraft.yaml, spread.yaml, tools/environment-setup.sh
Should now fetch wheel for Windows and Linux.
-----
=> requirements: uprev lxml to 4.5.0

specifications/20200304-core20-plugins.org, todo.org
=> specifications: add core20 plugin specification

specifications/20200316-enabling-experimental-features.org, todo.org
=> specifications: experimental features guidelines

spread.yaml, tests/spread/snaps/microk8s/task.yaml
Test that microk8s builds fine and install. Instrumenting the
installation comes later.
-----
=> tests: add microk8s spread test

.gitignore
=> vcs: add direnv files to .gitignore

specifications/20200317-enabling-experimental-lzo-compression.org, todo.org
=> specifications: experimental snap compression

setup.py
=> packaging: use find_namespace_packages in setup.py

requirements-devel.txt
=> requirements: uprev mypy to 0.770

specifications/20200329-progressive-delivery.org, todo.org
=> specifications: progressive delivery

CODE_STYLE.md
Discussed as a team and agree for the following changes to be enforced.
-----
=> CODE_STYLE: update to reflect latest conventions

snapcraft/internal/repo/_base.py, snapcraft/internal/repo/_deb.py
=> repo: type annotations and mypy fixes for base

snapcraft/internal/repo/_deb.py
Instead of tracking with a local dictionary, simply rely on
functools.lru_cache wrapper as we do for dpkg -s.
Rename _run_dpkg_query_s() -> _run_dpkg_query_search() for
consistency.
-----
=> repo: use functools.lru_cache for dpkg -L queries

snapcraft/storeapi/_snap_v2_client.py, snapcraft/storeapi/_store_client.py, snapcraft/storeapi/constants.py, snapcraft/storeapi/errors.py, snapcraft/storeapi/v2/_api_schema.py, snapcraft/storeapi/v2/channel_map.py, tests/fake_servers/api.py, tests/fixture_setup/_fixtures.py, tests/unit/store/test_store_client.py, tests/unit/store/v2/test_channel_map.py, todo.org, tools/staging_env.sh
Only the data required to implement the Progressive Delivery feature are considered.
-----
=> storeapi: add channel-map endpoint

requirements.txt, spread.yaml, tests/spread/legacy_python/snapd/task.yaml
=> requirements: uprev python-apt to 1.6.0 (bionic package)

requirements.txt, snapcraft/_store.py, snapcraft/cli/_channel_map.py, snapcraft/cli/store.py, snapcraft/storeapi/v2/_api_schema.py, specifications/20200329-progressive-delivery.org, specifications/20200329-progressive-releases.org, tests/integration/store/test_store_status.py, tests/unit/commands/__init__.py, tests/unit/commands/test_status.py, todo.org
Also:
- introduce --experimental-progressive-delivery
- fixup the channel-map schema
-----
=> cli: use the channel-map api for status

snapcraft/__init__.py, snapcraft/_store.py, snapcraft/cli/store.py, snapcraft/storeapi/_sca_client.py, snapcraft/storeapi/_store_client.py, snapcraft/storeapi/v2/_api_schema.py, tests/fake_servers/api.py, tests/integration/store/test_store_release.py, tests/unit/commands/test_promote.py, tests/unit/commands/test_release.py, tests/unit/store/test_store_client.py, todo.org
=> cli: add progressive releases support to the release command

snapcraft/plugins/v1/ant.py, snapcraft/plugins/v1/catkin.py, snapcraft/plugins/v1/cmake.py, snapcraft/plugins/v1/colcon.py, snapcraft/plugins/v1/conda.py, snapcraft/plugins/v1/crystal.py, snapcraft/plugins/v1/dotnet.py, snapcraft/plugins/v1/dump.py, snapcraft/plugins/v1/go.py, snapcraft/plugins/v1/godeps.py, snapcraft/plugins/v1/gradle.py, snapcraft/plugins/v1/kbuild.py, snapcraft/plugins/v1/make.py, snapcraft/plugins/v1/maven.py, snapcraft/plugins/v1/meson.py, snapcraft/plugins/v1/nil.py, snapcraft/plugins/v1/nodejs.py, snapcraft/plugins/v1/plainbox_provider.py, snapcraft/plugins/v1/python.py, snapcraft/plugins/v1/qmake.py, snapcraft/plugins/v1/ruby.py, snapcraft/plugins/v1/rust.py, snapcraft/plugins/v1/scons.py, snapcraft/plugins/v1/waf.py, tests/unit/plugins/v1/test_python.py
=> plugins: use v1 import path for all plugins

mypy.ini, setup.cfg
=> static: consolidate tooling setup to setup.cfg

tests/unit/lifecycle/test_lifecycle.py
Use a couple targetted mock.patches to provide equivalent
functionality.  Some related cleanup included.
-----
=> tests: remove usage of FakeApt fixtures in lifecycle

requirements.txt
This will reduce some noise because it converts some print()
statements with logger.debug().
-----
=> requirements: uprev python-apt

snapcraft/plugins/v2/make.py, tests/spread/plugins/v2/snaps/make-hello/Makefile, tests/spread/plugins/v2/snaps/make-hello/hello.c, tests/spread/plugins/v2/snaps/make-hello/snap/snapcraft.yaml, tests/unit/plugins/v2/test_make.py
=> make v2 plugin: make use of make-parameters

snapcraft/plugins/v2/make.py, tests/unit/plugins/v2/test_make.py
=> make v2 plugin: also pass make-parameters to install

snapcraft/internal/repo/_deb.py, tests/unit/repo/test_deb.py
=> repo: add interface to get packages from base

spread.yaml, tests/spread/plugins/v2/snaps/python-hello-staged-python/snap/snapcraft.yaml
=> ci: install the snapd snap when preparing spread systems

snapcraft/internal/pluginhandler/__init__.py, snapcraft/internal/repo/_base.py, snapcraft/internal/repo/_deb.py, snapcraft/plugins/v1/_ros/rosdep.py, snapcraft/plugins/v1/_ros/wstool.py, snapcraft/plugins/v1/catkin.py, snapcraft/plugins/v1/colcon.py, tests/spread/plugins/v2/build-and-run-hello/task.yaml, tests/spread/plugins/v2/snaps/python-hello-staged-python/snap/snapcraft.yaml, tests/spread/plugins/v2/snaps/python-hello-with-python-package-dep/hello, tests/spread/plugins/v2/snaps/python-hello-with-python-package-dep/setup.py, tests/spread/plugins/v2/snaps/python-hello-with-python-package-dep/snap/snapcraft.yaml, tests/spread/plugins/v2/snaps/python-hello-with-stage-package-dep/hello, tests/spread/plugins/v2/snaps/python-hello-with-stage-package-dep/setup.py, tests/spread/plugins/v2/snaps/python-hello-with-stage-package-dep/snap/snapcraft.yaml, tests/unit/plugins/v1/ros/test_rosdep.py, tests/unit/plugins/v1/ros/test_wstool.py, tests/unit/plugins/v1/test_catkin.py, tests/unit/plugins/v1/test_colcon.py, tests/unit/repo/test_deb.py
=> repo: filter stage-packages using base's manifest (core20)

snapcraft/plugins/v1/_ros/rosdep.py
The colcon v2 plugin may call this directly, at least temporarily.
-----
=> plugins: break out rosdep resolve parsing for external use

tools/environment-setup.sh
=> tools: install wheel in snapcraft-dev

.github/release-drafter.yml, .github/workflows/release-drafter.yml
=> ci: setup release-drafter

snapcraft/plugins/v2/npm.py
Replace nodejs with npm
LP: #1877479
-----
=> npm v2 plugin: update doc string

snapcraft/internal/elf.py
=> elf: fix string format for debug log

snapcraft/internal/lifecycle/_runner.py, snapcraft/internal/pluginhandler/__init__.py, snapcraft/internal/pluginhandler/_part_build_environment.py, snapcraft/internal/pluginhandler/_part_environment.py, snapcraft/internal/pluginhandler/_runner.py, snapcraft/internal/project_loader/_config.py, snapcraft/internal/project_loader/_parts_config.py, tests/spread/plugins/v2/nil/task.yaml, tests/spread/plugins/v2/snaps/nil-basic/snap/snapcraft.yaml, tests/unit/pluginhandler/test_pluginhandler.py, tests/unit/pluginhandler/test_runner.py
=> pluginhandler: make the build environment available to all steps

snapcraft/_store.py, snapcraft/storeapi/_metadata.py, snapcraft/storeapi/_sca_client.py, snapcraft/storeapi/_store_client.py, snapcraft/storeapi/_upload.py, snapcraft/storeapi/errors.py, tests/unit/commands/__init__.py, tests/unit/commands/test_upload.py, tests/unit/commands/test_upload_metadata.py, tests/unit/store/test_store_client.py
=> storeapi: update api and error messages from push to upload

snapcraft/project/_project_options.py
=> project: add core20 linker version

snapcraft/_store.py, snapcraft/cli/store.py, tests/unit/commands/__init__.py, tests/unit/commands/test_upload.py, todo.org
=> cli: migrate upload and release to new channel-map

spread.yaml
=> spread: add snap watch

snapcraft/internal/pluginhandler/__init__.py, snapcraft/internal/repo/_base.py, snapcraft/internal/repo/_deb.py, snapcraft/plugins/v1/_ros/rosdep.py, snapcraft/plugins/v1/_ros/wstool.py, snapcraft/plugins/v1/catkin.py, snapcraft/plugins/v1/colcon.py, tests/unit/pluginhandler/test_pluginhandler.py, tests/unit/plugins/v1/ros/test_rosdep.py, tests/unit/plugins/v1/ros/test_wstool.py, tests/unit/plugins/v1/test_catkin.py, tests/unit/plugins/v1/test_colcon.py, tests/unit/repo/test_deb.py
=> repo: decouple fetch and unpack stage-packages

snapcraft/cli/_options.py, snapcraft/cli/lifecycle.py
=> cli: restore --target-arch with warning for LXD and Multipass

snapcraft/internal/build_providers/_base_provider.py
=> build providers: improve warning for unknown base

snapcraft/plugins/v1/_ros/wstool.py
=> static: prepare for update to black 19.10b0

tools/environment-setup.sh
=> tools: fix environment-setup to work on aarch64

snapcraft/cli/store.py, tests/unit/commands/test_promote.py
=> cli: allow promoting from edge without --yes

snapcraft/cli/lifecycle.py
=> cli: use maxval of UnknownLength for pack progress

schema/snapcraft.json, snapcraft/cli/lifecycle.py, snapcraft/internal/meta/snap.py, specifications/enabling-experimental-lzo-compression.org, tests/spread/general/pack/task.yaml, tests/unit/commands/test_snap.py, tests/unit/meta/test_snap.py, tests/unit/project/test_schema.py, todo.org
=> Snap compression

snapcraft/internal/project_loader/_extensions/gnome_3_28.py, snapcraft/internal/project_loader/_extensions/gnome_3_34.py, tests/unit/project_loader/extensions/test_gnome_3_28.py, tests/unit/project_loader/extensions/test_gnome_3_34.py
=> extensions: plug the opengl interface for GNOME

snapcraft/project/_project_options.py, tests/unit/test_options.py
-----
I'm not sure which tests to add and where. Especially since this architecture is not yet available in any channel maps.
=> Riscv64 support

snapcraft/internal/build_providers/_base_provider.py
=> build providers: fix base change warning message

spread.yaml
=> spread tests: higher timeout for extension tests

extensions/desktop/common/desktop-exports
Signed-off-by: Ian Johnson <ian.johnson@canonical.com>
-----
=> extensions/desktop/common: add snapd gl vdpau dir to LD_LIBRARY_PATH

snapcraft/internal/build_providers/_base_provider.py
Requires #3215
This error is often incorrect:
f"Build environment was created with unknown snapcraft version {built_by!r}, cleaning."
Update to more accurately describe that we simply don't know its state:
"Build environment is in unknown state, cleaning first."
For consistency, also reword the following by specifying "first":
(2) f"Project base changed from {provider_base!r} to {build_base!r}, cleaning build instance."
-> f"Project base changed from {provider_base!r} to {build_base!r}, cleaning first."
(3) f"Build environment was created with newer snapcraft version {built_by!r}, cleaning."
-> f"Build environment was created with newer snapcraft version {built_by!r}, cleaning first."
Pull these checks into new function '_check_environment_needs_cleaning()',
so there is only one call to …
=> build providers: tweak environment clean detection and logging

snapcraft/internal/review_tools/_runner.py
Expand ~ for the actual path to home.
-----
=> review tools: fix snap link or copy path

specifications/default-tracks.org, todo.org
=> specifications: default tracks

snap/snapcraft.yaml, spread.yaml, tools/environment-setup.sh
=> spread: use host pip

tests/unit/remote_build/test_errors.py, tests/unit/repo/test_errors.py, tests/unit/test_errors.py
=> tests: fix assert ordering for error format tests

snapcraft/internal/lxd/_containerbuild.py
=> lxd: update connectivity check url

specifications/package-repositories.org
=> Tiny typo fix

snapcraft/cli/_command_group.py, snapcraft/cli/store.py, snapcraft/storeapi/v2/channel_map.py, specifications/default-tracks.org, tests/fake_servers/api.py, tests/spread/general/store/task.yaml, tests/unit/commands/__init__.py, tests/unit/commands/test_list_tracks.py, tests/unit/store/v2/test_channel_map.py, todo.org
=> cli: implement list-tracks

snapcraft/cli/_runner.py
The `requests` library relies on `certifi` library for CA
certificates, unless the use overrides REQUESTS_CA_BUNDLE
environment variable to point to a different certificate
bundle.
Since there is no way for the user to tell certifi to use
the host certificates, unless using the OS distribution
patched package), have snapcraft always set
REQUESTS_CA_BUNDLE to the host SSL certificates, if they
exist in the usual Debian/Ubuntu location.
Log the setting to debug.
Note that this approach does allow the user to override
this default setting of REQUESTS_CA_BUNDLE with their own.
=> snapcraft: use system certificates by default for https requests

requirements-devel.txt
=> requirements: pin setuptools devel requirement

snapcraft/plugins/v2/colcon.py, tests/unit/plugins/v2/test_colcon.py
=> colcon v2 plugin: honour http(s) proxy for stage-runtime-dependencies

tests/spread/plugins/v1/plainbox/snaps/provider-python-stage-package-mix/snap/snapcraft.yaml
=> spread tests: lock down setuptools for plainbox

snapcraft/storeapi/v2/channel_map.py
Follow the guideline set for docstrings in pep-257.
-----
=> storeapi: improve to channel map docstrings

schema/snapcraft.json, snapcraft/internal/meta/package_repository.py, snapcraft/internal/project_loader/_extensions/ros2_foxy.py, specifications/package-repositories.org, tests/spread/general/snaps/test-apt-key-fingerprint/snap/snapcraft.yaml, tests/spread/general/snaps/test-apt-key-name/snap/snapcraft.yaml, tests/spread/general/snaps/test-apt-keyserver/snap/snapcraft.yaml, tests/unit/meta/test_package_repository.py, tests/unit/meta/test_snap.py, tests/unit/project/test_schema.py, tests/unit/project_loader/extensions/test_ros2_foxy.py
Rename all associated references for consistency.
-----
=> schema: rename package-repository's "deb-types" to "format"

snapcraft/cli/store.py, specifications/default-tracks.org, tests/unit/commands/test_set_default_track.py, todo.org
=> cli: introduce set-default-track

tests/spread/general/license-invalid/task.yaml, tests/spread/general/license-valid/task.yaml, tests/spread/plugins/v1/dotnet/snaps/dotnet-hello/snap/snapcraft.yaml
=> spread tests: remove references of core16

snapcraft/plugins/v2/cmake.py
=> cmake v2 plugin: add help for cmake generators

README.md
=> readme: remove link to Google+

snapcraft/storeapi/_snap_v2_client.py, snapcraft/storeapi/_store_client.py, snapcraft/storeapi/v2/_api_schema.py, snapcraft/storeapi/v2/releases.py, tests/fake_servers/api.py, tests/unit/store/test_store_client.py, tests/unit/store/v2/test_releases.py, todo.org
=> storeapi: add releases endpoint

snapcraft/__init__.py, snapcraft/_store.py, snapcraft/cli/store.py, tests/unit/commands/__init__.py, tests/unit/commands/test_list_revisions.py, todo.org
=> cli: update revisions to use releases API

tests/unit/repo/test_deb.py
Some tests are copying the environment which can complicate
debugging/analysis.  Mock it for all tests with autouse=True.
-----
=> unit tests: mock os.environ.copy() for deb tests

snapcraft/internal/project_loader/_extensions/gnome_3_34.py, tests/unit/project_loader/extensions/test_gnome_3_34.py
=> include SNAPCRAFT_STAGE in XDG_DATA_DIRS, needed to find Gir files built by other parts

tools/brew_install_from_source.py, tools/cla_check.py, tools/collect_ppa_autopkgtests_results.py, tools/run_ppa_autopkgtests.py, tools/spread-shellcheck.py
=> tools: import sort with isort

snapcraft/cli/__main__.py, snapcraft/cli/_channel_map.py, snapcraft/cli/_command.py, snapcraft/cli/_command_group.py, snapcraft/cli/_errors.py, snapcraft/cli/_review.py, snapcraft/cli/assertions.py, snapcraft/cli/discovery.py, snapcraft/cli/help.py, snapcraft/cli/legacy.py, snapcraft/cli/store.py
=> cli: import sort with isort

snapcraft/internal/remote_build/_launchpad.py, tests/unit/remote_build/test_launchpad.py
Mock the git source handler using dependency injection so unit
tests do not depend on functional git installed and configured.
-----
=> launchpad tests: mock git source handler

snapcraft/storeapi/v2/_api_schema.py, snapcraft/storeapi/v2/releases.py, tests/unit/store/v2/test_releases.py
=> storeapi: allow revision entries without a base set

snap/snapcraft.yaml
=> snap: address snapcraft warnings for app command

snapcraft/plugins/v2/autotools.py, tests/spread/plugins/v2/build-and-run-hello/task.yaml, tests/spread/plugins/v2/snaps/autotools-hello-autogen/COPYING, tests/spread/plugins/v2/snaps/autotools-hello-autogen/INSTALL, tests/spread/plugins/v2/snaps/autotools-hello-autogen/Makefile.am, tests/spread/plugins/v2/snaps/autotools-hello-autogen/autogen.sh, tests/spread/plugins/v2/snaps/autotools-hello-autogen/configure.ac, tests/spread/plugins/v2/snaps/autotools-hello-autogen/hello.c, tests/spread/plugins/v2/snaps/autotools-hello-autogen/snap/snapcraft.yaml, tests/unit/plugins/v2/test_autotools.py
=> autotools v2 plugin: support autogen.sh and bootstrap

appveyor.yml, requirements-devel.txt
=> ci: uprev pyinstaller and switch timestamp server

snapcraft/_store.py, tests/unit/commands/test_list_keys.py
=> cli: add missing quote key creation hint

schema/snapcraft.json, snapcraft/internal/project_loader/_extensions/gnome_3_34.py, snapcraft/internal/project_loader/_extensions/gnome_3_38.py, tests/spread/extensions/gnome-3-38/task.yaml, tests/unit/project_loader/extensions/test_gnome_3_38.py
=> Add new gnome-3-38 extension which uses gnome-3-38-2004 and core20

snapcraft/internal/project_loader/_extensions/gnome_3_34.py, tests/unit/project_loader/extensions/test_gnome_3_34.py
=> Ensure PYTHONPATH is properly set for gnome-3-34 builds

extensions/desktop/gnome/launcher-specific, snapcraft/internal/project_loader/_extensions/gnome_3_38.py, tests/unit/project_loader/extensions/test_gnome_3_38.py
=> Ensure PYTHONPATH is appropriate for building packages with gnome-3-38

snapcraft/plugins/v1/flutter.py, tests/unit/plugins/v1/test_flutter.py
=> flutter: Specify arch specific bundle dirs fixes LP:1915991

tests/spread/electron-builder/no-template/expected_snap.yaml, tests/spread/electron-builder/no-template/expected_snapcraft.yaml
=> spread: update electron-builder test

tests/spread/plugins/v1/go/multiple_mains/task.yaml, tests/spread/plugins/v1/go/snaps/go-cgo/snap/snapcraft.yaml, tests/spread/plugins/v1/go/snaps/go-gotty/snap/snapcraft.yaml, tests/spread/plugins/v1/go/snaps/go-hello/snap/snapcraft.yaml, tests/spread/plugins/v1/go/snaps/go-with-multiple-main-packages/snap/snapcraft.yaml
=> spread tests: pin go for v1 plugin snaps

spread.yaml
=> ci: add requirements for snapcraft legacy in spread

snapcraft/internal/repo/snaps.py, tests/unit/repo/test_snaps.py
Branches are not advertised in store channels, the only way to check is to
to check with the store API, which `install` and `refresh` do already.
Fixes https://bugs.launchpad.net/snapcraft/+bug/1901733
=> snaps: do not validate snaps before install/refresh (Fixes LP#1901733)

snapcraft/storeapi/_dashboard_api.py, snapcraft/storeapi/_store_client.py, snapcraft/storeapi/errors.py, tests/fake_servers/api.py, tests/unit/store/test_store_client.py
=> storeapi: add binding for validations-sets

snapcraft/_store.py, snapcraft/cli/assertions.py, tests/unit/commands/test_list_validation_sets.py
=> cli: introduce list-validation-sets

snapcraft/cli/assertions.py, snapcraft/yaml_utils/__init__.py, tests/unit/commands/test_edit_validation_sets.py
-----
This is roughly based on edit-collaborators
=> cli: introduce edit-validation-sets

snapcraft/cli/_options.py, snapcraft/project/_sanity_checks.py, specifications/package-repositories.org, tests/spread/general/package-repositories/task.yaml, todo.org
=> package-repositories: remove experimental flag

spread.yaml, tests/spread/snaps/lxd/task.yaml, tests/spread/snaps/maas/maas_helpers.sh, tests/spread/snaps/maas/task.yaml, tests/spread/snaps/microk8s/task.yaml
-----
Running,
```
SNAPCRAFT_CHANNEL=candidate spread -debug google:tests/spread/snaps/maas
```
yields,
```
2021-06-01 01:48:56 Successful tasks: 2
```
=> tests: manual spread task for MaaS (CRAFT-225)

snapcraft/cli/echo.py, snapcraft/internal/log.py, tests/spread/general/content-interface-provider-not-found/task.yaml, tests/spread/general/dependency-check-missing-lib/task.yaml, tests/spread/general/fix-symlink-host-copy/task.yaml, tests/spread/general/virtual-packages/task.yaml, tests/unit/test_log.py
=> cli: warn and error messages to stderr (CRAFT-134)

snapcraft/project/_project_options.py
=> project: add architecture definition for m1 (CRAFT-267)

requirements-devel.txt, requirements.txt, setup.py, snapcraft/file_utils.py, tests/unit/sources/test_checksum.py
=> requirements: remove pysha3 (CRAFT-270)

snapcraft/internal/deprecations.py, snapcraft/project/_sanity_checks.py, snapcraft/project/errors.py, tests/unit/project/test_errors.py, tests/unit/project/test_sanity_checks.py
=> project: convert core warning to error

snapcraft/internal/meta/snap.py, tests/unit/meta/test_snap.py
=> meta: support for metadata links (CRAFT-370)

schema/snapcraft.json, tests/spread/general/metadata-links/snapcraft.yaml, tests/spread/general/metadata-links/task.yaml, tests/unit/project/test_schema.py
=> project: validate metadata links (CRAFT-369)

snapcraft/cli/remote.py, snapcraft/project/_project.py, tests/unit/commands/test_remote.py
-----
Currently, when spinning up a remote build, snapcraft calculates a hash of the path for the project being built, and uses that as a unique identifier for the build. This artificially limits the number of builds that can be happening for a given project to 1, which really limits the usefulness of remote builds.
Instead of calculating a hash for the project directory, calculate a hash that represents the _state_ of the project, such that changing any file in the working tree (e.g. switching git branches) changes the hash. This allows multiple builds for different versions of a given project to be running at the same time.
Of course, this introduces the complication of needing to track such builds. Expose the concept of a "build ID" to the user and allow them to specify it for every …
=> cli: add support for parallel remote builds

tests/spread/general/store/task.yaml
=> spread tests: store metrics against staging (CRAFT-391)

snapcraft/internal/build_providers/_multipass/_windows.py
=> multipass: bump windows installer to 1.7.0 (CRAFT-412)

.github/workflows/tests.yaml, requirements-devel.txt, requirements.txt, snap/snapcraft.yaml, snapcraft/internal/meta/package_repository.py, snapcraft/internal/meta/snap.py, snapcraft/internal/repo/apt_cache.py, tests/unit/meta/test_command.py, tests/unit/meta/test_command_mangle.py, tools/environment-setup-local.sh, tools/environment-setup.sh, tools/snapcraft-override-build.sh, tools/spread-shellcheck.py
=> snap: move base to core20 (CRAFT-509)

.github/workflows/publish.yaml, .github/workflows/spread.yml
=> github: update snapcore/action-build dep

extensions/desktop/common/desktop-exports
New shellcheck error SC2295.
-------
-----
=> desktop: improve shell substitution logic

tests/spread/electron-builder/no-template/task.yaml
=> spread: switch to yarn for electron-builder test

appveyor.yml, requirements-devel.txt, requirements.txt, snapcraft.spec, snapcraft/cli.py, snapcraft/legacy.py, snapcraft/lifecycle.py, snapcraft/meta/snap_yaml.py, snapcraft/parts.py, snapcraft/projects.py, snapcraft/providers/_buildd.py, snapcraft/providers/_lxd.py, snapcraft/providers/_multipass.py, tests/spread/electron-builder/no-template/task.yaml, tools/freeze-requirements.sh
=> [spike] new-snapcraft: fix execution in managed environment

snapcraft/internal/repo/snaps.py
=> snap: do not refresh already installed snaps

schema/snapcraft.json, snapcraft/internal/lifecycle/_runner.py, snapcraft/internal/pluginhandler/_build_attributes.py, tests/spread/general/core22-step-dependencies/snapcraft.yaml, tests/spread/general/core22-step-dependencies/task.yaml, tests/unit/lifecycle/test_order_core20.py
=> lifecycle: core22 lifecycle conditional on build-attributes entry (CRAFT-725)

spread.yaml
=> spread: update error when local snap is missing

snapcraft/cli/_command_group.py
LP: #[1943244](https://bugs.launchpad.net/snapcraft/+bug/1943244)
-----
=> cli: reintroduce remote-build and promote to snapcraft help

schema/snapcraft.json, snapcraft_legacy/internal/pluginhandler/__init__.py, snapcraft_legacy/internal/remote_build/_worktree.py, snapcraft_legacy/internal/sources/_7z.py, snapcraft_legacy/internal/sources/__init__.py, snapcraft_legacy/internal/sources/_base.py, snapcraft_legacy/internal/sources/_bazaar.py, snapcraft_legacy/internal/sources/_deb.py, snapcraft_legacy/internal/sources/_git.py, snapcraft_legacy/internal/sources/_mercurial.py, snapcraft_legacy/internal/sources/_rpm.py, snapcraft_legacy/internal/sources/_script.py, snapcraft_legacy/internal/sources/_snap.py, snapcraft_legacy/internal/sources/_subversion.py, snapcraft_legacy/internal/sources/_tar.py, snapcraft_legacy/internal/sources/_zip.py, snapcraft_legacy/internal/states/_pull_state.py, tests/legacy/unit/pluginhandler/test_state.py, tests/legacy/unit/remote_build/test_worktree.py, tests/legacy/unit/sources/test_git.py, tests/legacy/unit/states/test_pull.py, tests/spread/general/sources/snaps/git-submodules/snapcraft.yaml, tests/spread/general/sources/task.yaml, tests/spread/plugins/v1/x-local/local-plugin-x-compat/state-pull, tests/spread/plugins/v1/x-local/local-plugin/state-pull
-----
Duplicate of https://github.com/snapcore/snapcraft/pull/3629, but applied to `snapcraft/7.0`.
=> sources: make submodule fetching configurable

snapcraft/parts/grammar.py, snapcraft/parts/lifecycle.py, tests/unit/parts/test_grammar.py
=> parts: support for grammar parsing

Makefile, pyproject.toml, schema/snapcraft.json, snapcraft/meta/snap_yaml.py, snapcraft/projects.py, tests/legacy/unit/project_loader/test_schema.py, tests/unit/meta/test_snap_yaml.py, tests/unit/test_projects.py
-----
Support for application fields in `snapcraft/7.0`.
=> meta: support application fields (CRAFT-814)

tools/staging_env.sh
=> tools: update staging store URL for uploading blobs

snapcraft/meta/snap_yaml.py, snapcraft/projects.py, tests/unit/meta/test_snap_yaml.py, tests/unit/test_projects.py
-----
Support for `plugs` (including `ContentPlugs`).
CRAFT-816
=> meta: support plugs

snapcraft/meta/snap_yaml.py, snapcraft/projects.py, tests/unit/meta/test_snap_yaml.py, tests/unit/test_projects.py
-----
Support for `hooks` in `snapcraft.yaml`.  
CRAFT-808
=> meta: add support for hooks

TESTING.md, runtests.sh
-----
Update urls for spread tarball.
=> tests: update spread url

snapcraft/internal/project_loader/_extensions/kde_neon.py, tests/unit/project_loader/extensions/test_kde_neon.py
- [X ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [X ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [X ] Have you successfully run `./runtests.sh static`?
- [X ] Have you successfully run `./runtests.sh tests/unit`?
-----
=> kde extension: new content snap for core20

tests/spread/plugins/v2/snaps/python-hello-multiple-parts-staged/setup.py, tests/spread/plugins/v2/snaps/python-hello-multiple-parts/setup.py
=> spread: fix python-hello

snapcraft/storeapi/_store_client.py
No and no - I assume CI will do this for me :-)
-----
=> storeapi: fix typo

snapcraft/cli.py, snapcraft/commands/__init__.py, snapcraft/commands/extensions.py, snapcraft/parts/lifecycle.py, tests/unit/commands/test_expand_extensions.py
=> Expand extensions

requirements-devel.txt, requirements.txt, setup.py, snapcraft/cli.py, snapcraft/commands/__init__.py, snapcraft/commands/lifecycle.py, snapcraft/parts/lifecycle.py, snapcraft/parts/parts.py, snapcraft/providers/_lxd.py, tests/spread/general/core22/clean/snap/snapcraft.yaml, tests/spread/general/core22/clean/task.yaml, tests/unit/commands/test_lifecycle.py, tests/unit/parts/test_lifecycle.py, tests/unit/parts/test_parts.py
Add command to clean parts. The build instance will be removed if
no parts are specified and not running in destructive or managed
modes.
-----
CRAFT-985
=> commands, parts: add clean command

snapcraft_legacy/internal/build_providers/_snap.py, snapcraft_legacy/internal/lifecycle/_runner.py, snapcraft_legacy/storeapi/__init__.py, snapcraft_legacy/storeapi/_snap_api.py
=> storeapi: export SnapAPI

snapcraft_legacy/_store.py, snapcraft_legacy/cli/assertions.py, snapcraft_legacy/cli/store.py, snapcraft_legacy/storeapi/__init__.py, snapcraft_legacy/storeapi/_store_client.py, snapcraft_legacy/storeapi/constants.py, tests/spread/general/store/task.yaml
=> storeapi: environment variable for auth selection

snapcraft/parts/lifecycle.py, snapcraft/providers/_get_provider.py, snapcraft/providers/_multipass.py
=> providers: support env and pause for confirmation

requirements-devel.txt, requirements.txt, snapcraft/parts/lifecycle.py, snapcraft/parts/parts.py, tests/unit/parts/test_parts.py
Hook the entries up to the LifeCycleManager and add the base if there as
extra_snap_packages
-----
=> parts: extra_snap_packages & extra_build_packages

requirements-devel.txt, requirements.txt, tests/unit/cli/test_version.py, tests/unit/commands/test_account.py, tests/unit/commands/test_expand_extensions.py, tests/unit/commands/test_list_extensions.py, tests/unit/commands/test_names.py, tests/unit/commands/test_version.py, tests/unit/conftest.py, tests/unit/extensions/test_extensions.py, tests/unit/parts/test_parts.py
=> tests: use craft-cli lib fixtures

snapcraft/parts/lifecycle.py, snapcraft/parts/parts.py, snapcraft/projects.py, tests/unit/parts/test_lifecycle.py, tests/unit/parts/test_parts.py, tests/unit/test_projects.py
-----
Install snaps from content plug's `default-provider` field.
=> plugs: install snaps from content plugs

snapcraft/parts/lifecycle.py, snapcraft/parts/plugins/__init__.py, snapcraft/parts/plugins/conda_plugin.py, snapcraft/parts/plugins/register.py, spread.yaml, tests/spread/plugins/craft-parts/build-and-run-hello/conda-hello/hello, tests/spread/plugins/craft-parts/build-and-run-hello/conda-hello/snap/snapcraft.yaml, tests/spread/plugins/craft-parts/build-and-run-hello/task.yaml, tests/unit/parts/plugins/test_conda_plugin.py
=> plugins: (new) conda

.github/workflows/tests.yaml
=> ci: disable Python 3.9 unit testing

snapcraft/providers/_buildd.py, snapcraft/providers/_lxd.py
=> providers: user core22 buildd

requirements-devel.txt, requirements.txt
Update craft-cli to 0.6.0.
-----
=> requirements: update dependencies

snapcraft/repo/apt_sources_manager.py, tests/unit/repo/test_apt_sources_manager.py
Run `dpkg --add-architecture` for architectures listed in package
repositories.
LP: #1973213
-----
=> repo: enable package repository architectures

snapcraft/cli.py
=> cli: enable craft-store logging

snapcraft/cli.py
=> cli: disable new pylint false positive

snapcraft/meta/snap_yaml.py, snapcraft/projects.py, tests/unit/meta/test_snap_yaml.py
=> meta: add slots

snapcraft/cli.py
The legacy logger will emit debug messages for our libraries when used
if they have an explicit log level.
-----
=> cli: reset the logger before running legacy

requirements-devel.txt, requirements.txt
-----
providers: update craft-providers
(CRAFT-1102)
=> providers: update craft-providers

snapcraft/cli.py, snapcraft/commands/__init__.py, snapcraft/commands/upload.py, tests/unit/commands/test_upload.py
=> commands: add legacy push

snapcraft/cli.py, tests/unit/cli/test_exit.py
=> cli: message with more information about keyring

snapcraft/commands/account.py, tests/unit/commands/test_account.py
=> export-login: clarify use of exported tokens

.github/workflows/spread.yml, snapcraft/cli.py, snapcraft/commands/legacy.py, snapcraft/commands/store/_legacy_account.py, snapcraft/commands/store/client.py, snapcraft/errors.py, snapcraft/legacy_cli.py, tests/spread/general/store/task.yaml, tests/unit/commands/conftest.py, tests/unit/commands/store/test_legacy_account.py
=> store: support configparser credentials

snapcraft/commands/legacy.py, tests/unit/cli/test_legacy.py
=> promote: add snap-name to args

snapcraft/parts/lifecycle.py, snapcraft/projects.py, tests/spread/core22/root-packages/snapcraft.yaml, tests/spread/core22/root-packages/task.yaml, tests/unit/parts/test_lifecycle.py
=> lifecyle: root level build-packages and build-snaps

extensions/desktop/command-chain/Makefile, extensions/desktop/command-chain/desktop-launch, extensions/desktop/command-chain/hooks-configure-fonts, extensions/desktop/command-chain/run, snapcraft/extensions/gnome.py, snapcraft/extensions/registry.py, tests/spread/extensions/gnome/task.yaml, tests/unit/commands/test_list_extensions.py, tests/unit/extensions/test_gnome.py, tests/unit/extensions/test_registry.py
=> extensions: add core22 gnome

snapcraft/utils.py, tests/unit/test_utils.py
Locate the given tool in the host system or inside a snap. The new
utilities will be used during ELF file handling.
-----
CRAFT-1189
=> utils: add calls to find host and snap tools

Makefile, snapcraft_legacy/_store.py, snapcraft_legacy/cli/assertions.py, snapcraft_legacy/cli/store.py, snapcraft_legacy/config.py, snapcraft_legacy/file_utils.py, snapcraft_legacy/plugins/v1/_plugin.py, snapcraft_legacy/plugins/v1/flutter.py, snapcraft_legacy/plugins/v2/conda.py, snapcraft_legacy/plugins/v2/crystal.py, snapcraft_legacy/project/_sanity_checks.py, snapcraft_legacy/storeapi/__init__.py, snapcraft_legacy/storeapi/_snap_api.py, snapcraft_legacy/storeapi/_store_client.py, tests/legacy/unit/plugins/v1/test_base.py, tests/legacy/unit/store/test_errors.py
-----
Re-enable `isort` for legacy code.
=> lint: lint legacy code with isort

Makefile, snapcraft_legacy/internal/project_loader/_config.py, snapcraft_legacy/plugins/v1/_ros/wstool.py, snapcraft_legacy/plugins/v2/crystal.py, tests/legacy/fixture_setup/_unittests.py, tests/legacy/unit/cli/test_lifecycle.py, tests/legacy/unit/project/test_schema.py, tests/legacy/unit/repo/test_apt_key_manager.py, tests/legacy/unit/repo/test_apt_ppa.py, tests/legacy/unit/repo/test_apt_sources_manager.py, tests/legacy/unit/repo/test_deb.py, tests/legacy/unit/states/test_pull.py
-----
lint legacy code with black
=> lint: lint legacy code with black

Makefile, snapcraft_legacy/__init__.py, snapcraft_legacy/cli/echo.py, snapcraft_legacy/cli/snapcraftctl/_runner.py, snapcraft_legacy/internal/elf.py, snapcraft_legacy/internal/errors.py, snapcraft_legacy/internal/meta/package_repository.py, snapcraft_legacy/internal/project_loader/grammar_processing/_global_grammar_processor.py, snapcraft_legacy/internal/project_loader/grammar_processing/_part_grammar_processor.py, snapcraft_legacy/storeapi/__init__.py, snapcraft_legacy/storeapi/errors.py, tests/legacy/unit/plugins/v1/test_ant.py, tests/legacy/unit/plugins/v1/test_gradle.py, tests/legacy/unit/plugins/v1/test_maven.py, tests/legacy/unit/project_loader/grammar_processing/test_part_grammar_processor.py, tests/legacy/unit/store/test_errors.py, tests/legacy/unit/test_elf.py
-----
lint legacy code with flake8
=> lint: lint legacy code with flake8

snapcraft/commands/legacy.py, tests/unit/cli/test_legacy.py
=> cli: fixup args to list-validation-sets

requirements-devel.txt, requirements.txt, snapcraft/cli.py, snapcraft/commands/__init__.py, snapcraft/commands/discovery.py, snapcraft/errors.py, snapcraft/parts/lifecycle.py, tests/unit/commands/test_discovery.py
And clarify message on why a base is picked.
-----
CRAFT-1256
=> plugins command: support for core22

tests/spread/plugins/craft-parts/build-and-run-hello/conda-hello/snap/snapcraft.yaml, tests/spread/plugins/v1/conda/snaps/conda-hello/snap/snapcraft.yaml, tests/spread/plugins/v2/snaps/conda-hello/snap/snapcraft.yaml
Newer version required to handle internal changes in anaconda/conda.
-----
=> tests: uprev miniconda

snapcraft/commands/manage.py, snapcraft/store/__init__.py, snapcraft/store/client.py, tests/unit/store/test_client.py
=> store: initial support for an onprem store

requirements-devel.txt, requirements.txt, snapcraft/store/channel_map.py, snapcraft/store/client.py, tests/unit/store/test_channel_map.py, tests/unit/store/test_client.py
=> store: support status for an onprem store

snapcraft/meta/snap_yaml.py, snapcraft/projects.py, tests/unit/meta/test_snap_yaml.py
Implement snap.yaml passthrough and add missing fields
`daemon_scope` and `activates_on`.
=> Write passthrough to meta data and add some missing fields

snapcraft/commands/manage.py, snapcraft/store/client.py, tests/unit/commands/test_manage.py, tests/unit/store/test_client.py
=> store: support close for an on prem store

snapcraft/commands/lifecycle.py
Use consistent command class summaries in lifecycle docstrings.
-----
=> commands: update lifecycle docstrings

tests/unit/store/test_client.py
=> tests unit: add for on prem store list-revisions

tests/unit/elf/conftest.py, tests/unit/elf/test_patcher.py
=> unit tests: minor improvement to fixture usage

tests/unit/providers/test_providers.py
-----
I forgot to add unit tests for https://github.com/snapcore/snapcraft/pull/3935.
Tests were pulled from [rockcraft](https://github.com/canonical/rockcraft/pull/77/files#diff-213dd6ab20435bf3358d2d1dba0a40ecc55d4a4538869de29a87ba72178442b8R59)
(CRAFT-1307)
=> tests: add unit test for `capture_logs_from_instance()`

snapcraft/commands/validation_sets.py, tests/unit/commands/test_validation_sets.py
Validation sets on error used to not provide a way to re-edit if the set
was rejected. Prompt the user if they want to re-edit the set after
showing the error.
The change here is the while loop, _generate_template and
_submit_validation_set have been extracted from the run method.
-----
CRAFT-1388
=> commands: allow re-editing validation sets on error

requirements-devel.txt, requirements.txt
=> requirements: craft-store 2.3.0 for new credentials

snapcraft/providers.py
-----
A limitation of craft-providers prevents snapcraft from pushing files to Multipass's `/root/` directory.   This limitation was uncovered with the recent PR https://github.com/snapcore/snapcraft/pull/3951.
This PR prevents pushing `.bashrc` to Multipass environments.  This reversion can be addressed after https://github.com/canonical/craft-providers/issues/169 is resolved.
=> providers: do not push .bashrc to Multipass instances

tests/unit/test_utils.py
-----
Added some missing tests from charmcraft.
=> tests: unit tests for `confirm_with_user()`

.github/workflows/publish.yaml, .github/workflows/spread.yml, tests/spread/core22/linters/classic-libc/expected_linter_output.txt, tests/spread/core22/linters/classic/expected_linter_output.txt
=> ci: remove docker before building snap

requirements-devel.txt, requirements.txt
This enables git+ssh:// scheme in in git sources.
-----
=> requirements: update craft-parts to 1.17.1

HACKING.md
-----
A minor `HACKING.md` update requested by @giusebar.
I recently added `snapd-testing-tools` as a submodule.  This submodule is required for running spread tests, so now I've updated the hacking instructions.
=> docs: update HACKING.md to recurse submodules

requirements-devel.txt, requirements.txt
=> requirements: update craft-providers to 1.7.1

setup.cfg
=> tests: ensure coverage is set per tox env

snapcraft_legacy/plugins/v2/autotools.py
- [x ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
-----
=> doc: fix docstring for accuracy

tests/legacy/unit/build_providers/multipass/test_multipass_command.py, tests/legacy/unit/review_tools/test_runner.py, tests/unit/store/test_client.py
=> Fix typo from 'unkown' to 'unknown'

snapcraft/cli.py, snapcraft/commands/__init__.py, snapcraft/commands/lint.py, tests/spread/core22/linters/lint-file/task.yaml, tests/unit/commands/test_lint.py
-----
Add CLI handling for a new command, `snapcraft lint`.
(CRAFT-1688)
=> cli: add lint command

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/task.yaml, .github/workflows/issues.yaml
=> ci: add issue templates and workflow for JIRA

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/task.yaml
=> Issue template

.github/workflows/issues.yaml
Use the correct action for the JIRA Workflow
-----
=> github: update issue sync action

tools/freeze-requirements.sh
=> deps: correct pyinstaller version in freeze-requirements.sh

.github/ISSUE_TEMPLATE/config.yml
=> github: disable blank issues and provide alternative comms

tests/unit/meta/test_snap_yaml.py
=> tests: remove arch_triplet from unit test (#4160)

requirements-devel.txt, requirements.txt
Craft Parts 1.19.5 fixes subdir in pull and build steps.
-----
=> requirements: update craft-parts to 1.19.5

requirements-devel.txt, requirements.txt, setup.py, snapcraft_legacy/plugins/v1/catkin.py, snapcraft_legacy/plugins/v1/colcon.py
=> requirements: update craft-archives

extensions/desktop/common/desktop-exports
=> desktop extensions: set libthai dictionary path

requirements-devel.txt, requirements.txt
Craft-parts 1.21.1 reverts changes in pull and build subdirs.
-----
=> requirements: update craft-parts to 1.21.1

requirements-devel.txt, requirements.txt
=> dependencies: update craft-cli to 2.0.0

requirements-devel.txt, requirements.txt
-----
Resolves #4181 
- Set hostname when launching LXD instances
- Update Lunar image for Multipass to stable image
- Pin dependency urllib3<2
(CRAFT-1767)
=> requirements: update craft-providers to 1.10.1

docs/explanation/architectures.rst, docs/explanation/index.rst, docs/howto/architectures.rst, docs/howto/index.rst, docs/reference/architectures.rst, docs/reference/index.rst
-----
View docs [here](https://canonical-snapcraft--4349.com.readthedocs.build/en/4349/)
Even though this is a draft, feedback is welcome anytime.
cc @rpjday 
Fixes #4336
(CRAFT-2009)
=> docs(architectures): add how-to, reference, and explanation

pyproject.toml, requirements-devel.txt, requirements.txt, snapcraft/remote/__init__.py, snapcraft/remote/errors.py, snapcraft/remote/git.py, tests/unit/remote/test_errors.py, tests/unit/remote/test_git.py
-----
Fixes #4320
(CRAFT-1975)
=> feat(remote-build): add GitRepo class

tox.ini
=> tox: exclude submodules from spread-shellcheck

snapcraft/commands/remote.py, tests/unit/commands/test_remote.py
-----
2 separate commits - do not squash
Refactor and cleanup in preparation for #4322.  Now there is a location to add code for #4322.
(CRAFT-1977)
=> refactor(remote-build): reorganize functions

snapcraft/elf/_elf_file.py, tests/unit/test_projects.py
-----
Fix for errors in pyright 1.1.332.  Unblocks #4087
=> chore: ignore types

pyproject.toml, setup.py
=> chore: update Python version metadata

.github/workflows/tox.yaml
-----
On `hotfix` branches, `pyright` should be pinned like all other requirements.
=> ci: pin pyright

pyproject.toml, setup.py, snapcraft/commands/extensions.py, snapcraft/elf/_elf_file.py, snapcraft/meta/appstream.py, snapcraft/meta/manifest.py, snapcraft/meta/snap_yaml.py, snapcraft/parts/grammar.py, snapcraft/parts/lifecycle.py, snapcraft/parts/parts.py, snapcraft/parts/plugins/_ros.py, snapcraft/store/_legacy_account.py, snapcraft/utils.py, snapcraft_legacy/ruff.toml, tests/legacy/unit/meta/test_meta.py, tests/unit/elf/conftest.py, tests/unit/parts/test_grammar.py, tools/brew_install_from_source.py, tools/version.py
=> chore(deps): update ruff to 0.1.1 and fix lint issues

TESTING.md
These commands no longer point to valid paths.
-----
=> docs: update stale commands for running local tests in TESTING.md

snapcraft/pack.py, snapcraft/parts/lifecycle.py, tests/unit/test_pack.py
From hotfix: #4424
Fixes: #4413 
CRAFT-2172
=> chore(log): hide command in output when pack failed

.github/workflows/publish.yaml
=> chore(ci): publish snaps for feature/ branches

tests/spread/core22/clean/task.yaml
-----
Fix a test failure introduced by #4431.  
Unblocks #4450
=> test(spread): check for new lifecycle message

snapcraft/projects.py, tests/spread/core24/components/snap/Makefile, tests/spread/core24/components/snap/hello.c, tests/spread/core24/components/snap/snapcraft.yaml, tests/spread/core24/components/task.yaml, tests/unit/test_projects.py
-----
Adds a `components` model.  See #4464 for the naming conventions.
You can review per-commit.
Fixes #4464
(CRAFT-2308)
=> feat(projects): add components model

snapcraft/commands/remote.py, snapcraft/remote/__init__.py, snapcraft/remote/errors.py, snapcraft/remote/launchpad.py, snapcraft/remote/remote_builder.py, snapcraft_legacy/cli/remote.py, snapcraft_legacy/internal/remote_build/_launchpad.py, snapcraft_legacy/internal/remote_build/errors.py, tests/legacy/unit/commands/test_remote.py, tests/legacy/unit/remote_build/test_launchpad.py, tests/unit/cli/test_exit.py, tests/unit/remote/test_launchpad.py, tests/unit/remote/test_remote_builder.py
=> fix(remote): return error when remote build failed

.github/workflows/tox.yaml
-----
Pin pyright because patch releases are breaking CI.
=> ci: pin pyright to 1.1.344

.github/workflows/spread-scheduled.yaml, spread.yaml, tests/spread/general/remote-build/task.yaml
=> Spread update

requirements-devel.txt, snapcraft/commands/status.py, snapcraft/elf/_elf_file.py, snapcraft/extensions/ros2_humble_desktop.py, snapcraft/extensions/ros2_humble_ros_base.py, snapcraft/extensions/ros2_humble_ros_core.py, tests/legacy/unit/deltas/test_deltas_xdelta3.py, tests/legacy/unit/meta/test_meta.py, tests/legacy/unit/pluginhandler/test_pluginhandler.py, tests/legacy/unit/store/test_store_client.py
Black and pyright update broken the CI, so this one fixed it.
=> chore(deps): update black and pyright

snap/snapcraft.yaml
-----
Cherry-pick #4522 on `feature/components`
=> chore(deps): bump version of Chisel (#4522)

snapcraft/application.py, tests/spread/core24/environment/paths/task.yaml, tests/spread/core24/environment/test-variables/task.yaml, tests/spread/core24/lifecycle/snapcraft.yaml, tests/spread/core24/lifecycle/task.yaml, tests/spread/core24/package-repo-archs/task.yaml, tests/spread/core24/patchelf/classic-patchelf/task.yaml, tests/spread/core24/patchelf/strict-patchelf/task.yaml, tests/spread/core24/plugs-warn/task.yaml, tests/spread/core24/remove-hook/task.yaml, tests/spread/core24/root-packages/task.yaml, tests/spread/core24/scriptlets/empty-overrides/task.yaml, tests/spread/core24/scriptlets/scriptlet-failures/task.yaml, tests/spread/core24/set-version-twice/task.yaml, tests/spread/core24/try/task.yaml
=> lifecycle commands

spread.yaml
=> chore(spread): add more 22.04 workers for the google backend

.github/workflows/tox.yaml, requirements-devel.txt, setup.py, tools/environment-setup-local.sh, tox.ini
=> build(lint): use ruff from snap

snapcraft/application.py, tests/unit/test_application.py
=> fix(application): support snap/craft environment variables

snapcraft/application.py, tests/unit/test_application.py
=> fix: alias project-type to type

spread.yaml, tests/spread/core24-suites/patchelf/classic-python/task.yaml, tests/spread/core24/appstream-desktop/desktop/appstream-desktop, tests/spread/core24/appstream-desktop/desktop/expected_appstream-desktop.desktop, tests/spread/core24/appstream-desktop/desktop/expected_snap.yaml, tests/spread/core24/appstream-desktop/desktop/io.snapcraft.appstream.desktop, tests/spread/core24/appstream-desktop/desktop/io.snapcraft.appstream.metainfo.xml, tests/spread/core24/appstream-desktop/desktop/snap/snapcraft.yaml, tests/spread/core24/appstream-desktop/desktop/snapcraft.svg, tests/spread/core24/appstream-desktop/icon-desktop/appstream-desktop, tests/spread/core24/appstream-desktop/icon-desktop/expected_appstream-desktop.desktop, tests/spread/core24/appstream-desktop/icon-desktop/expected_snap.yaml, tests/spread/core24/appstream-desktop/icon-desktop/io.snapcraft.appstream.desktop, tests/spread/core24/appstream-desktop/icon-desktop/io.snapcraft.appstream.metainfo.xml, tests/spread/core24/appstream-desktop/icon-desktop/snap/snapcraft.yaml, tests/spread/core24/appstream-desktop/icon-desktop/snapcraft.svg, tests/spread/core24/appstream-desktop/task.yaml, tests/spread/core24/content-interface-provider-found/snapcraft.yaml, tests/spread/core24/content-interface-provider-found/task.yaml, tests/spread/core24/content-interface-provider-not-found/snapcraft.yaml, tests/spread/core24/content-interface-provider-not-found/task.yaml, tests/spread/core24/grammar/snap/snapcraft.yaml, tests/spread/core24/grammar/src/on-amd64-to-amd64/hello-world.sh, tests/spread/core24/grammar/src/on-amd64-to-arm64/hello-world.sh, tests/spread/core24/grammar/task.yaml, tests/spread/core24/linters-pack/task.yaml, tests/spread/core24/metadata-links/snapcraft.yaml, tests/spread/core24/metadata-links/task.yaml, tests/spread/general/grammar/task.yaml
-----
hooks will be reworked as part of the hooks PR
=> Spread restore no abort

snapcraft/parts/__init__.py, snapcraft/parts/lifecycle.py, snapcraft/services/lifecycle.py, tests/spread/core24-suites/patchelf/classic-python/task.yaml, tests/unit/parts/test_lifecycle.py, tests/unit/services/test_lifecycle.py
=> feat: enable patchelf for core24

snapcraft/application.py, snapcraft/cli.py, tests/unit/test_application.py
=> fix(application): fallback earlier for managed core20

docs/requirements.txt, requirements-devel.txt, requirements.txt
=> build(deps): bump craft-providers to 1.23.1

requirements-devel.txt, requirements.txt
=> build(deps): bump craft-providers to 1.20.2

tests/spread/core24-suites/environment/snaps/staged-common-library/expected_snap.yaml, tests/spread/core24-suites/environment/test-variables/task.yaml, tests/spread/core24-suites/manifest/manifest-creation/task.yaml, tests/spread/core24/linters-file/task.yaml
=> chore(spread): miscellaneous spread fixes for core24

snapcraft/application.py, tests/unit/cli/test_version.py, tests/unit/test_application.py
=> refactor(app): use more code from craft-app

docs/requirements.txt, requirements-devel.txt, requirements.txt, setup.py
=> build(deps): update craft-application to 2.1.0

snapcraft/extensions/gnome.py, tests/spread/core24/linters-pack/library-gnome/snap/snapcraft.yaml, tests/spread/core24/linters-pack/task.yaml, tests/unit/commands/test_list_extensions.py, tests/unit/extensions/test_gnome.py
=> feat(extensions): support core24 in the gnome extensions

snapcraft/extensions/gnome.py, snapcraft/extensions/kde_neon.py
-----
I have been asked about `builtin` twice, so it's time to update the docstrings and comments.
=> docs(extensions): improve docstrings and comments

docs/requirements.txt, requirements-devel.txt, requirements.txt, snapcraft/application.py, snapcraft/pack.py, snapcraft/services/lifecycle.py, snapcraft/services/package.py, tests/spread/core24/components/Makefile, tests/spread/core24/components/expected-component.yaml, tests/spread/core24/components/hello.c, tests/spread/core24/components/snapcraft.yaml, tests/spread/core24/components/task.yaml, tests/unit/conftest.py, tests/unit/services/test_lifecycle_components.py, tests/unit/services/test_package_components.py, tests/unit/test_pack.py
=> feat: partitions for core24 

snapcraft/commands/lifecycle.py, tests/unit/commands/test_lifecycle.py, tests/unit/commands/test_validation_sets.py, tests/unit/extensions/test_extensions.py, tests/unit/services/test_package.py
=> Multiple fixes

snapcraft/parts/lifecycle.py, snapcraft/parts/parts.py, snapcraft/parts/setup_assets.py, snapcraft/services/lifecycle.py, snapcraft/services/package.py, tests/spread/core24/components/snapcraft.yaml, tests/spread/core24/components/squashfs-root/meta/component.yaml, tests/spread/core24/components/task.yaml, tests/unit/parts/test_parts.py, tests/unit/parts/test_setup_assets.py, tests/unit/parts/test_setup_assets_components.py, tests/unit/services/test_lifecycle.py, tests/unit/services/test_lifecycle_components.py, tests/unit/services/test_package.py, tests/unit/services/test_package_components.py
-----
Add support for packaging component hooks for core24.
I recommend reviewing per-commit.
(CRAFT-2540)
=> feat: package component hooks for core24

tests/spread/core24-suites/manifest/manifest-creation/task.yaml
-----
Today, the test package is `hello=2.10-3build1`.
=> tests: expand regex for `hello` package

tests/spread/core-devel/basic/task.yaml
-----
This test ensures that snapcraft can create a base snap and that the devel base is usable.
=> tests: fix devel base snap test

snapcraft/models/project.py, tests/spread/core22/plugs-warn/expected_output.txt, tests/spread/core24/plugs-warn/expected_output.txt, tests/unit/models/test_projects.py
-----
Updates to the documentation and a better link based on @Saviq's [feedback](https://matrix.to/#/!GGqzbFAUQprdPgYYCM:ubuntu.com/$2AWZ0x1S-KTH1rcHENdYF4Yxdu6oGCJXOwlmmuuXwIs?via=ubuntu.com&via=matrix.org&via=kde.org).
=> chore: update link for top level plug and slots warning

docs/requirements.txt, requirements-devel.txt, requirements.txt, tests/spread/core24/grammar/snap/snapcraft.yaml, tests/spread/core24/grammar/task.yaml
-----
Fixes https://github.com/canonical/snapcraft/issues/4764
~~Needs a craft-application 2.6.1 release to pull in https://github.com/canonical/craft-application/pull/328~~
Needs a craft-application 2.6.2 release to pull in https://github.com/canonical/craft-application/pull/330
=> tests(spread): regression test for grammar and non-grammar lists

docs/requirements.txt, requirements-devel.txt, requirements.txt, tests/spread/core24/grammar/snap/snapcraft.yaml, tests/spread/core24/grammar/task.yaml
=> chore(merge): '8.2.2' into 'main'

tests/spread/core22/package-repositories/test-multi-keys/snap/snapcraft.yaml, tests/spread/core24/package-repositories/test-multi-keys/snap/snapcraft.yaml
-----
The source package has changed and the test isn't particularly important.
=> tests(spread): drop check for specific files in ppa tests

tests/spread/plugins/craft-parts/build-and-run-hello/flutter-hello/lib/main.dart
=> tests: fix flutter spread test

extensions/desktop/kde-neon-6/launcher-specific, setup.cfg, snapcraft/extensions/kde_neon_6.py, snapcraft_legacy/internal/meta/hooks.py, tests/legacy/unit/project/test_project_info.py, tests/unit/extensions/test_kde_neon_6.py
=> many: hotfix for kf6

docs/requirements.txt, requirements-devel.txt, requirements.txt, snapcraft/commands/remote.py, tests/unit/commands/test_remote.py
=> chore(merge): '8.2.10' into 'main'

snapcraft/commands/remote.py, tests/unit/parts/plugins/test_colcon.py
-----
Remove the last few pylint references that were probably added in between #4817 and the ROS2 Jazzy PRs
=> style: remove pylint comments

snapcraft/models/project.py, tests/unit/models/test_projects.py
=> fix: allow coreXX-desktop bases

docs/requirements.txt, requirements-devel.txt, requirements.txt, setup.py, tests/spread/core24/package-filter/snapcraft.yaml, tests/spread/core24/package-filter/task.yaml
=> tests: add a test for package filtering in core24

.github/workflows/tics.yaml
=> ci: use correct attribute for tics workflow

snapcraft/application.py
-----
The task to refactor commands in Snapcraft is tracked in #4911.
=> chore: add issue number to overriding the command_groups property

.github/renovate.json5, .github/workflows/check-renovate.yaml
-----
Sync renovate config and workflow to match starbase: https://github.com/canonical/starbase/pull/232
=> ci: update renovate config and workflow

.github/workflows/cla-check.yaml, docs/reference/changelog.rst, snapcraft/parts/setup_assets.py, tests/unit/parts/test_setup_assets.py
-----
Bring `7.5.6` into `main` and add release notes.
=> chore(merge): 7.5.6 into 'main'

snapcraft/commands/remote.py
=> style(lint): fix ruff 0.6 linting errors

docs/reference/changelog.rst
-----
`8.3.3` updated dependencies that were already bumped on `main`, so there are no changes.
`hotfix/8.3` doesn't have a changelog, so this PR adds changelog notes too.
=> chore(merge): 8.3.3 into main

requirements-devel.txt, requirements-docs.txt, requirements.txt, tests/spread/core24/npm-reentrant/hello.js, tests/spread/core24/npm-reentrant/package-lock.json, tests/spread/core24/npm-reentrant/package.json, tests/spread/core24/npm-reentrant/snap/snapcraft.yaml, tests/spread/core24/npm-reentrant/task.yaml
=> build(deps): bump craft-parts for hotfix/8.4

docs/reference/changelog.rst
=> docs(changelog): add 8.4.1 release notes

.github/workflows/security-scan.yaml, osv-scanner.toml, requirements-devel.txt, requirements-docs.txt, requirements.txt, tools/freeze-requirements.sh
=> ci: add security scan

.github/workflows/publish.yaml
-----
This branch has expired and needs to be tested.
=> ci: allow republishing branches

docs/reference/changelog.rst
=> docs(changelog): add 8.4.3 release notes

docs/reference/changelog.rst, requirements-devel.txt, requirements-docs.txt, requirements.txt, setup.py, snapcraft/models/project.py, tests/spread/core24-suites/environment/test-variables/task.yaml, tests/spread/core24/package-repositories/task.yaml, tests/spread/core24/package-repositories/test-key-conflict/snapcraft.yaml, tests/unit/models/test_projects.py
-----
Merge 8.4.3 and 8.4.4 into main.
=> chore(merge): 8.4.4 into main

docs/reference/changelog.rst
-----
Add 8.5.0 release notes.
=> docs(changelog): add 8.5.0 release notes

docs/reference/bases.rst
=> docs: minor fix in bases.rst

docs/reference/changelog.rst
-----
Trying a new practice where I set the release date to the scheduled date for a release to the `stable` channel.
This is a hotfix before the holidays, so I am doing a rapid release.
=> docs(changelog): add 8.5.1 changelog

docs/reference/changelog.rst, requirements-devel.txt, requirements-docs.txt, requirements.txt, snapcraft/models/project.py, tests/unit/models/test_projects.py
=> chore(merge): 8.5.1 into main

snapcraft/models/project.py
Add pydantic.Field description and examples to the Project model for Snapcraft.
-----
=> feat: pydantic fields for jsonschema output in Project

docs/reference/changelog.rst, requirements-devel.txt, requirements-docs.txt, requirements.txt, snapcraft/errors.py, snapcraft/pack.py, tests/unit/test_errors.py
=> fix: improve error message from snapd pack

snapcraft/application.py, snapcraft/commands/extensions.py, snapcraft/commands/lint.py, snapcraft/commands/plugins.py, snapcraft/meta/snap_yaml.py, snapcraft/models/project.py, snapcraft/parts/lifecycle.py, snapcraft/parts/parts.py, snapcraft/services/lifecycle.py, snapcraft/store/client.py, snapcraft/utils.py, tests/unit/commands/test_expand_extensions.py, tests/unit/commands/test_lint.py, tests/unit/commands/test_remote.py, tests/unit/conftest.py, tests/unit/models/test_projects.py, tests/unit/parts/test_lifecycle.py, tests/unit/services/test_lifecycle.py, tests/unit/store/test_client.py, tests/unit/test_utils.py
-----
Closes #4993.
CRAFT-3278.
=> refactor: use craft-platforms utilities

docs/howto/craft-a-snap/example-ros-1-app.rst, docs/reference/code/extensions/ros-1-content-desktop-extension-talker-listener-expanded.diff, docs/reference/code/extensions/ros-1-extension-talker-listener-expanded.diff, docs/reference/extensions/index.rst, docs/reference/extensions/ros-1-content-extensions.rst, docs/reference/extensions/ros-1-extension.rst
=> docs: migrate ros 1 extensions

docs/reference/changelog.rst, requirements-devel.txt, requirements-docs.txt, requirements.txt, setup.py
-----
Brings in https://github.com/canonical/craft-parts/pull/1003 and finalizes the 8.6.1 changelog.
=> docs(changelog): finalize 8.6.1 entry

docs/explanation/remote-build.rst, docs/reference/changelog.rst, requirements-devel.txt, requirements-docs.txt, requirements.txt, setup.py
=> chore(merge): 8.6.1 into main

docs/reference/changelog.rst, snapcraft/parts/plugins/flutter_plugin.py, tests/unit/parts/plugins/test_flutter_plugin.py
---
Cherry-picks #5264 onto 8.6.
=> fix: correct git errors in flutter plugin

docs/conf.py
Make the links in the nav bar fit the intended design.
---
---
=> docs(config): update links in nav

spread.yaml, tests/spread/core-devel/base-snap/snapcraft.yaml, tests/spread/core-devel/base-snap/task.yaml, tests/spread/core-devel/basic/snapcraft.yaml
---
* re-enable the devel spread test suite
* simplify the test
* add a second simple test
Fixes #4921
(CRAFT-3141)
=> test: re-enable devel spread tests

uv.lock
---
Addresses https://osv.dev/vulnerability/GHSA-cpwx-vrp4-4pq7
=> build(deps): update jinja to 3.1.6

docs/release-notes/changelog.rst
---
Merge 8.6.3 into main.  The changes were already in `main` so only the changelog is updated here.
=> chore(merge): 8.6.3 into main

snapcraft/extensions/kde_neon.py, snapcraft/extensions/kde_neon_6.py, snapcraft/extensions/kde_neon_qt6.py, tests/unit/extensions/test_kde_neon.py, tests/unit/extensions/test_kde_neon_6.py
- [x ] Have you followed the [guidelines for contributing](https://github.com/canonical/snapcraft/blob/main/CONTRIBUTING.md)?
- [x ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ x] Have you successfully run `make lint`?
---
I can't seem to run make test anymore python-apt fails and libgit on plucky
=> fix: Fix cmake prefix path and remove invalid cmake root path.

pyproject.toml, uv.lock
Update `craft-application` dependency
=> build(deps): update craft-application to 4.10.0

SECURITY.md, docs/release-notes/index.rst
---
Adds a security policy using language from https://docs.google.com/document/d/1lFrbvsGc273dRGOyfGKjqlT2fIfMZiotu3JJanQ75V4/edit?tab=t.0.
=> docs: add security policy

docs/conf.py, docs/explanation/index.rst, docs/explanation/parts-lifecycle.rst, docs/explanation/parts.rst, docs/reference/snap-build-process.rst
=> docs: migrate 'parts lifecycle'

docs/release-notes/snapcraft-8-7.rst, snapcraft/store/client.py
---
Adds a release note entry for 8.7.3.  I'm doing a release now because we have nothing else scheduled this month for 8.7.
=> docs(release-notes): finalize 8.7.3

snapcraft/store/client.py
---
Minor updates for ruff 0.10 and 0.11.
=> style: ruff 0.11 fixes

docs/reference/index.rst, docs/reference/snapshots.rst
---
[RTD build](https://canonical-snapcraft--5363.com.readthedocs.build/en/5363/reference/snapshots.html)
=> docs: add "snapshots" reference

docs/how-to/publish/index.rst, docs/how-to/publish/manage-snaps-on-the-snap-store.rst, docs/how-to/publish/publish-a-snap.rst, docs/how-to/publish/register-a-snap.rst
---
[RTD build](https://canonical-snapcraft--5360.com.readthedocs.build/en/5360/how-to/publish/register-a-snap.html)
=> docs: add "register a snap" how-to

snap/snapcraft.yaml, snapcraft/cli.py, tests/spread/core24/craft-test/snapcraft.yaml, tests/spread/core24/craft-test/spread.yaml, tests/spread/core24/craft-test/spread/.extension, tests/spread/core24/craft-test/spread/cloud-config.yaml, tests/spread/core24/craft-test/task.yaml, tests/spread/core24/craft-test/tests/spread/craft-test/my-test/task.yaml
=> feat: add 'test' command

docs/conf.py, docs/howto/index.rst, docs/reference/plugins.rst, docs/release-notes/index.rst, docs/release-notes/snapcraft-8-8.rst
---
* Adds release notes for 8.8
* Adds new craft-parts docs
* Minor template updates
[RTD build](https://canonical-snapcraft--5365.com.readthedocs.build/en/5365/release-notes/snapcraft-8-8/)
(CRAFT-4291)
=> docs(release-notes): add 8.8 release notes

docs/conf.py, docs/explanation/bases.rst, docs/how-to/craft/configure-package-information.rst, docs/how-to/debug/debug-a-snap.rst, docs/how-to/debug/index.rst
=> docs: migrate 'debug a snap'

tests/unit/commands/test_account.py, tests/unit/commands/test_lint.py
---
Fixture updates for failing command unit tests.
(CRAFT-4414)
=> test: fix command tests

docs/reference/external-package-information.rst, docs/reference/index.rst, docs/reference/metadata.rst
---
Migrates the [external metadata docs](https://snapcraft.io/docs/using-external-metadata).
SNAPCRAFT-433
=> docs: migrate metadata reference

snap/snapcraft.yaml
=> fix: remove uneeded distro whl

docs/explanation/index.rst, docs/explanation/snap-configurations.rst, docs/how-to/craft/add-a-snap-configuration.rst, docs/how-to/craft/index.rst, docs/how-to/debug/debug-with-gdb.rst
=> docs: migrate 'adding snap configuration'

docs/conf.py, docs/reference/plugins.rst, docs/release-notes/changelog.rst, docs/release-notes/snapcraft-8-8.rst, snapcraft_legacy/internal/meta/_manifest.py, tests/legacy/unit/meta/test_meta.py, tests/spread/core20/manifest/snapcraft.yaml, tests/spread/core20/manifest/task.yaml, tests/spread/core24-suites/manifest/manifest-creation/task.yaml
---
Brings the hotfix/8.8 branch back into main.
=> chore(merge): 8.8.1 into main

docs/conf.py, docs/how-to/debug/index.rst, docs/how-to/debug/use-the-classic-linter.rst
---
Migrates the docs from [classic linters](https://snapcraft.io/docs/linters-classic) and [how to use linters](https://snapcraft.io/docs/how-to-classic#use-linters-to-identify-problems).
SNAPCRAFT-402
=> docs: migrate classic linting how-to

common.mk, pyproject.toml
---
Merge starbase into main for an 8.9 release.
(SNAPCRAFT-1105)
=> chore(merge): starbase into main

docs/index.rst
=> docs: revise home page

docs/explanation/index.rst, docs/how-to/debugging/use-the-classic-linter.rst, docs/how-to/index.rst, docs/index.rst, docs/reference/index.rst, docs/reference/parts/parts-and-steps.rst, docs/tutorials/index.rst
=> docs: align landing pages with model

docs/index.rst, docs/release-notes/index.rst, docs/release-notes/snapcraft-8-9.rst
---
Adds release notes for Snapcraft 8.9.
(SNAPCRAFT-1105)
=> docs(release-notes): add 8.9 release notes

docs/conf.py, docs/how-to/crafting/index.rst, docs/how-to/crafting/manage-dependencies.rst, docs/how-to/debugging/debug-a-snap.rst
---
[RTD build](https://canonical-snapcraft--5452.com.readthedocs.build/en/5452/how-to/crafting/manage-dependencies/)
=> docs: migrate 'Build and staging dependencies'

docs/conf.py, docs/how-to/crafting/enable-classic-confinement.rst, docs/how-to/publishing/authenticate.rst, docs/how-to/publishing/index.rst, docs/how-to/publishing/publish-a-snap.rst
=> docs: migrate 'releasing your app'

docs/release-notes/snapcraft-8-9.rst, snapcraft/application.py, snapcraft/services/project.py, tests/spread/core22/project-variables/expected.txt, tests/spread/core22/project-variables/snapcraft.yaml, tests/spread/core22/project-variables/task.yaml, tests/spread/core24/project-variables/expected.txt, tests/spread/core24/project-variables/snapcraft.yaml, tests/spread/core24/project-variables/task.yaml, tests/unit/test_application.py
=> chore(merge): 8.9.2 into main

pyproject.toml, uv.lock
---
Bump and set a minimum version of requests for a CVE.
=> build(deps): bump requests to 2.32.4

snapcraft/application.py
---
Updates an outdated comment about the dotnet plugin.
=> chore: fix dotnet comment

snapcraft/extensions/kde_neon.py, snapcraft/extensions/kde_neon_6.py, snapcraft/extensions/kde_neon_qt6.py, tests/unit/extensions/test_kde_neon.py, tests/unit/extensions/test_kde_neon_6.py, tests/unit/extensions/test_kde_neon_qt6.py
- [x ] Have you followed the [guidelines for contributing](https://github.com/canonical/snapcraft/blob/main/CONTRIBUTING.md)?
- [x ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
---
=> fix: kde-neon: Append usr to cmake prefix path #5272

pyproject.toml, uv.lock
=> build(deps): update craft-application to 5.4.0

docs/release-notes/snapcraft-8-10.rst
---
Finalizes the [release notes](https://canonical-ubuntu-documentation-library--5619.com.readthedocs.build/snapcraft/5619/release-notes/snapcraft-8-10/) for an 8.10.2 release.
=> docs: finalize 8.10.2 release notes

docs/conf.py, docs/explanation/cryptography.rst, docs/explanation/parts-lifecycle.rst, docs/how-to/crafting/override-the-default-build.rst, docs/how-to/debugging/debug-a-snap.rst, docs/how-to/integrations/index.rst, docs/reference/plugins.rst, docs/reference/plugins/colcon_plugin.rst, docs/reference/plugins/matter_sdk_plugin.rst, docs/reference/project-file/anatomy-of-snapcraft-yaml.rst, docs/release-notes/snapcraft-8-10.rst, pyproject.toml, snapcraft/extensions/gnome.py, snapcraft/parts/plugins/_ros.py, snapcraft/templates/test/spread.yaml.j2, snapcraft/templates/test/spread/.extension, snapcraft_legacy/plugins/v2/_ros.py, tests/spread/core24/craft-test/spread/.extension, tests/spread/core24/init-test/task.yaml, tests/unit/extensions/test_gnome.py, uv.lock
=> chore(merge): 8.10.2 into main

CONTRIBUTING.md
---
* fixes a typo and internal links in CONTRIBUTING.md
=> docs: fix CONTRIBUTING.md typos

docs/contribute-to-this-documentation.rst, docs/index.rst
---
Merges the 8.10 hotfix branch into main in preparation for an 8.11 release.
=> chore(merge): hotfix/8.10 into main

docs/reference/architectures.rst
=> docs: fix missing link to supported architectures

docs/how-to/crafting/customize-lifecycle-steps-and-part-variables.rst
---
Moved here from https://github.com/canonical/craft-parts/pull/1216 per suggestion of @mr-cal
=> docs: document custom project vars (SNAPCRAFT-1053)

docs/reference/plugins.rst, docs/reference/plugins/crystal_plugin.rst
=> docs: add 'Crystal plugin' reference

docs/reference/plugins/catkin_plugin.rst, docs/reference/plugins/catkin_tools_plugin.rst, docs/reference/plugins/colcon_plugin.rst, docs/reference/plugins/conda_plugin.rst, docs/reference/plugins/crystal_plugin.rst, docs/reference/plugins/flutter_plugin.rst, docs/reference/plugins/matter_sdk_plugin.rst, docs/reference/plugins/maven_plugin.rst
---
* Replace 'Keywords' with 'Keys'
* Standardize whitespace across files
* Make lists consistent in the 'How it works' sections
* Update the maven plugin's example
I'll standardize the "Default" values when https://github.com/canonical/craft-parts/pull/1349#discussion_r2400061830 is resolved.
=> docs: format plugin references
