canonical/snapcraft

snapcraft/cli/snapcraftctl/_runner.py
tests/unit/commands/snapcraftctl/test_set_grade.py
tests/unit/commands/snapcraftctl/test_set_version.py
tests/unit/pluginhandler/test_scriptlets.py

It's a pretty common mistake for scriplets to end up setting "" in
set-version, leading the the following error:
`Failed to generate snap metadata: 'adopt-info' refers to part <part>,
but that part is lacking the 'parse-info' property.`
Setting an empty grade effectively just ignores the invalid value,
relying on the default grade later.
Explicitly error out with helpful messages when invalid options
are used.
-----

snapcraftctl: add checks for empty string for set-version & set-grade

---

snapcraft/internal/meta/errors.py
snapcraft/internal/meta/package_repository.py
tests/unit/meta/test_errors.py
tests/unit/meta/test_package_repository.py

- Create PackageRepositoriesValidationError for errors
pointing user to documentation page for package-repositories.
- Convert all validation RuntimeErrors to
PackageRepositoriesValidationError.
- Add some trivial checks/handling for empty string url and ppa.
- Add trivial check for empty suites/components.
-----

package repositories: improve error handling

---

snapcraft/cli/_channel_map.py
specifications/progressive-releases.org
tests/unit/commands/test_release.py
tests/unit/commands/test_status.py

This allows for easier column parsing.
-----

cli: remove spaces from progressive metrics

---

snapcraft/internal/repo/_deb.py
snapcraft/internal/repo/apt_ppa.py
tests/unit/repo/test_apt_ppa.py
tests/unit/repo/test_deb.py

This decouples the apt ppa helpers from the _deb module and
improves test coverage of the specific ppa helper functions.
-----

repo: move apt ppa helpers into apt_ppa module

---

pyproject.toml
requirements-devel.txt

pyproject: add isort with black-compatible configuration

---

snapcraft/plugins/v1/_ros/rosdep.py

Sets `ROS_PYTHON_VERSION=3` if `Rosdep` used for ROS 2 (colcon plugin V1).
Signed-off-by: artivis <deray.jeremie@gmail.com>
-----

Fix rosdep ROS_PYTHON_VERSION

---

snapcraft/cli/discovery.py
snapcraft/plugins/_plugin_finder.py
tests/unit/commands/test_list_plugins.py
tests/unit/pluginhandler/test_plugin_loader.py

When trying to use build-base core22, some portions of cli/plugins
defaulted to legacy/v1 plugins, instead of v2.
Use a list of old cores, and assume anything new to be modern/v2.
Add a test for a "future core2y" to use v2 plugins.
- no, fails on groovy with new pyflakes?
- no, fails on groovy, as it's trying to run pytest (python2) not pytest-3 (python3)?

cli,plugins: assume that core22 base wants v2 plugins.

---

snapcraft/storeapi/__init__.py
snapcraft/storeapi/_agent.py
snapcraft/storeapi/_client.py
snapcraft/storeapi/_sca_client.py
snapcraft/storeapi/_snap_index_client.py
snapcraft/storeapi/_snap_v2_client.py
snapcraft/storeapi/_sso_client.py
snapcraft/storeapi/_status_tracker.py
snapcraft/storeapi/_up_down_client.py
snapcraft/storeapi/_upload.py
snapcraft/storeapi/assertions.py
snapcraft/storeapi/channels.py
snapcraft/storeapi/constants.py
snapcraft/storeapi/errors.py
snapcraft/storeapi/status.py
snapcraft/storeapi/v2/_api_schema.py

Add some isort:skip statements where ordering matters in the
package's __init__.py.
-----

storeapi: import sort with isort

---

snapcraft/plugins/v1/colcon.py
tests/unit/plugins/v1/test_colcon.py

Currently colcon v1 sources the wrong script for the overlay workspace preventing from running twice the build. This PR fixes this by sourcing the appropriate script as per [the documentation](https://index.ros.org/doc/ros2/Tutorials/Workspace/Creating-A-Workspace/#source-the-overlay).
related LP:#1866719
-----

Fix colcon v1 workspace sourcing

---

tests/unit/project/test_schema.py

Many of the tests would fail when not running the whole test suite.
This is because the json format checkers in project_loader._config
have not been loaded.  Ensure this module is imported, and mark the
import to ignore related warnings.
-----

project schema tests: ensure json format checkers are loaded

---

snapcraft/_store.py
snapcraft/cli/assertions.py
tests/fake_servers/api.py
tests/fake_servers/search.py
tests/unit/commands/test_validate.py

Info API can only retrieve snap-id's for what is publicly available,
workaround the issue by allowing for using the snap-id as a fallback
to the snap-name.
LP: #1902913
-----

cli: allow snap-id for validate

---

extensions/desktop/common/desktop-exports
extensions/desktop/common/fonts

This mitigates issues with fonts breaking when snaps update in the
backround (yet to be fixed in snapd).
-----

extensions: use SNAP_COMMON instead of SNAP_DATA for fonts

---

tools/environment-setup-local.sh
tools/environment-setup.sh

Use script locations to find snapcraft directory so the script
may be run from anywhere.
Local virtual env setup is configurable using
SNAPCRAFT_VIRTUAL_ENV_DIR, but defaults to $HOME/.venv/snapcraft.
-----

tools: split local environment setup from environment-setup.sh

---

tests/unit/plugins/v1/test_rust.py

If the rustup command exists on host, the cross compilation
unit tests will fail.  Simply mock the pull() step to return
False for os.path.exists().
-----

tests: add missing mock for rust unit tests

---

.travis.yml
Makefile
TESTING.md

Instead of an all-or-nothing runtests, break up each test
into a discrete make target.  Add `static-tests` target to
execute all static tests.
-----

tests: make each static test available as a make target

---

snapcraft/internal/meta/_snap_packaging.py
tests/fixture_setup/_fixtures.py
tests/unit/meta/test_snap_packaging.py

If a hook stub is being generated it would overwrite a primed
hook (in meta/hooks/).  Check for existence of script before
generating the stub.
Add some unit tests to get some needed coverage here, extending
the SnapcraftYaml fixture to include support for hooks.
LP: #1905072
-----

meta: don't overwrite preconfigured hooks with stubs

---

snapcraft/formatting_utils.py
snapcraft/internal/meta/_snap_packaging.py
snapcraft/internal/project_loader/_config.py
snapcraft/internal/project_loader/_env.py
tests/unit/project_loader/test_environment.py
tests/unit/test_formatting_utils.py
tests/unit/test_meta.py

Prevent library injection vulnerability on strict mode snaps built
with Snapcraft via misconfigured LD_LIBRARY_PATH:
- project_loader: do not export empty environment
- meta: do not export empty environment. Warn on empty environment.
CVE-2020-27348
LP: #1901572
-----

project_loader, meta, formatting_utils: account for empty env

---

snapcraft/formatting_utils.py
snapcraft/internal/meta/_snap_packaging.py
snapcraft/internal/project_loader/_config.py
snapcraft/internal/project_loader/_env.py
tests/unit/meta/test_meta.py
tests/unit/meta/test_snap_packaging.py
tests/unit/project_loader/test_environment.py
tests/unit/test_formatting_utils.py

A general solution for a specific problem with LD_LIBRARY_PATH and
PATH where the env can contain two successive colons and that being
interpreted as the CWD.
-----

project_loader, formatting_utils: take empty env values into account

---

requirements-devel.txt

Until python-apt doesn't break on install, pin pip to the last
known working version.
-----

requirements: pin pip to 20.1.1 for devel

---

snapcraft/plugins/v1/_plugin.py
snapcraft/plugins/v1/ant.py
snapcraft/plugins/v1/catkin.py
snapcraft/plugins/v1/cmake.py
snapcraft/plugins/v1/conda.py
snapcraft/plugins/v1/crystal.py
snapcraft/plugins/v1/flutter.py
snapcraft/plugins/v1/godeps.py
snapcraft/plugins/v1/gradle.py
snapcraft/plugins/v1/kbuild.py
snapcraft/plugins/v1/make.py
snapcraft/plugins/v1/maven.py
snapcraft/plugins/v1/meson.py
snapcraft/plugins/v1/plainbox_provider.py
snapcraft/plugins/v1/python.py
snapcraft/plugins/v1/qmake.py
snapcraft/plugins/v1/ruby.py
snapcraft/plugins/v1/rust.py
snapcraft/plugins/v1/scons.py
snapcraft/plugins/v1/waf.py
tests/unit/plugins/v1/test_colcon.py
tests/unit/plugins/v1/test_go.py
tests/unit/plugins/v1/test_godeps.py

V1 plugins can be used only if the build base is core, core16 or
core18. As an additional sanity check, each plugin tests for base
consistency. To clean that up, move the base check from each
individual plugin to the V1 plugin base class constructor.

plugins v1: move build base test in v1 plugins to base class

---

snapcraft/internal/project_loader/grammar/_processor.py
tests/unit/project_loader/grammar/test_processor.py

Any statement prior to an 'on.. to..' clause vanishes into
the abyss.
E.g.:
```
stage-packages:
- on amd64 to arm64:
- foo
- on amd64 to i386:
- foo2
``` 
In this case `foo` will never be added to the package list.
When starting to process an on/to statement, ensure the previous
one is added to the statement collection.
Add a test to cover this case and update the basic grammar tests
to explicitly declare the target (deb) arch.
-----

grammar: fix the case of disappearing statements

---

snapcraft/cli/store.py
tests/unit/commands/__init__.py
tests/unit/commands/test_status.py

-----
Currently snapcraft supports getting the status by architecture. Add support for getting the status by track as well.

cli: support getting snap status by track

---

snapcraft/internal/pluginhandler/__init__.py
snapcraft/plugins/v2/_plugin.py
snapcraft/plugins/v2/cmake.py
snapcraft/plugins/v2/meson.py
tests/unit/plugins/v2/test_cmake.py
tests/unit/plugins/v2/test_meson.py

-----
This is intended as an alternative to PR #3347.  It adds an `out_of_source_build` property to `PluginV2`, which is interpreted the same way it would be on `PluginV1` implementations, in that it disables the automatic copying of a part's source code to the build directory.  The default implementation of the property is `plugin.out_of_source_build == False`.
To demonstrate that this works, I've ported the meson and cmake plugins to use this mode.  For what it is worth, the cmake plugin was already configuring the build to use the copy of the source in `part_source_dir`, ignoring the copy in `part_build_dir`.

plugins v2: add support for out of source tree builds

---

snapcraft/_store.py
tests/unit/commands/__init__.py
tests/unit/commands/test_create_key.py
tests/unit/commands/test_list_keys.py
tests/unit/commands/test_register_key.py
tests/unit/commands/test_sign_build.py

Assertion commands do not require snapd to be installed through the
deb, it just needs to be available for most commands.
LP: #1906506
-----

cli: do not require snapd deb for assertions

---

snapcraft/storeapi/errors.py

storeapi: remove unused MissingSnapdError

---

snapcraft/internal/pluginhandler/__init__.py
tests/unit/pluginhandler/test_pluginhandler.py

When generating the include file set, snapcraft will walk through
symlinks.  This effectively results in being unable to filter out
anything that itself, or parent is pointed to by an external symlink.
e.g. bin -> usr/bin  will prevent filtering anything under usr/bin.
This is because snapcraft will include 'bin/foo' even though 'bin'
is a symlink.  Subsequently, it will then preserve 'usr/bin/foo'.
Avoid this by simply checking if target is a link before walking
it.
-----

pluginhandler: do not walk symlinks for include filesets

---

snapcraft/internal/elf.py
tests/fixture_setup/_unittests.py
tests/unit/test_elf.py

-----
I think it would be useful for Snapcraft to warn if a snap was missing libraries, or including duplicate libraries provided by the base snap or a content interface snap.
The current `ElfFile` class contains most of this information, in the form of the list of needed libraries together with the required symbol versions.  What is missing is a list of symbol versions defined by the library.  This PR adds that information to the class.

elf: extract defined symbol versions

---

snapcraft/internal/sources/__init__.py

Zip uses the python zipfile implementation.
The remainder will fail if the equivalent tools are not in the
user's path on the host. That error should be more obvious
than the "KeyError" uses are currently getting when using
remote-build.  Future work should update these source handlers
to use file_utils.get_host_tool_path() to perform this check
prior to executing the command.
LP: #1898877
-----

sources: enable 7z, bzr, hg, svn, zip for non-linux

---

snapcraft/internal/repo/_deb.py
snapcraft/internal/repo/apt_cache.py
tests/unit/repo/test_apt_cache.py
tests/unit/repo/test_deb.py

Ubuntu usage of apt_cache.get_marked_packages() assumes any
marked package is marked for installation.  However, it may
contain packages marked for deletion.
Modify get_marked_packages() to get_packages_marked_for_installation()
to accurately capture the required build packages to install. Apt
will handle deletion as necessary.
-----

repo: only install build packages marked for installation

---

tests/spread/plugins/v2/snaps/catkin-catkin-packages-ignore/src/package1/package.xml
tests/spread/plugins/v2/snaps/catkin-catkin-packages-ignore/src/package2/package.xml
tests/spread/plugins/v2/snaps/catkin-cmake-args/src/customizable_message/package.xml
tests/spread/plugins/v2/snaps/catkin-noetic-hello/src/snapcraft_hello/package.xml
tests/spread/plugins/v2/snaps/catkin-noetic-in-source-hello/package.xml
tests/spread/plugins/v2/snaps/catkin-specific-packages/src/package1/package.xml
tests/spread/plugins/v2/snaps/catkin-specific-packages/src/package2/package.xml
tests/spread/plugins/v2/snaps/catkin-tools-cmake-args/src/customizable_message/package.xml
tests/spread/plugins/v2/snaps/catkin-tools-noetic-hello/src/snapcraft_hello/package.xml
tests/spread/plugins/v2/snaps/catkin-tools-noetic-in-source-hello/package.xml
tests/spread/plugins/v2/snaps/catkin-tools-specific-packages/src/package1/package.xml
tests/spread/plugins/v2/snaps/catkin-tools-specific-packages/src/package2/package.xml

Here is the follow-up PR to https://github.com/snapcore/snapcraft/pull/3405 fixing a few licenses in ROS-related test files. The license declared in a few `package.xml` did not match those in sources.
See [this discussion](https://github.com/snapcore/snapcraft/pull/3405#discussion_r554162049) for reference.
Signed-off-by: artivis <deray.jeremie@gmail.com>
-----

Fix a few licenses in ros-related test files

---

snapcraft/internal/project_loader/grammar/_processor.py
tests/unit/project_loader/grammar/test_processor.py

There is no impact for current projects because there is
no supported usage until build-environment is enabled.
Improve test coverage of dicts and rename "expected_packages"
to "expected_results" as not all test cases imply packages.
-----

grammar: ensure all dictionary primitives are captured

---

snapcraft/internal/pluginhandler/_part_environment.py
tests/unit/project_loader/test_environment.py

project loader: export SNAPCRAFT_TARGET_ARCH in build environment

---

snapcraft/cli/assertions.py
tests/unit/commands/test_validate.py

A recent customer request includes being able to revoke an already issued
validation assertion. The store backend already supported this option, but
it was needed to surface the option in the `snapcraft validate` CLI.
- [x ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
-----

Allow validation assertions to be revoked

---

snapcraft/project/_project_options.py

project: always set target arch even if not cross compiling

---

snapcraft/cli/_options.py
snapcraft/project/_sanity_checks.py

Allow use of --target-arch with an *EXPERIMENTAL* warning.
-----

project: enable experimental target-arch support for core20

---

tests/spread/plugins/v1/plainbox/legacy-build-run/task.yaml
tests/spread/plugins/v1/plainbox/provider-basic/task.yaml
tests/spread/plugins/v1/plainbox/provider-python-stage-package-mix/task.yaml
tests/spread/plugins/v1/plainbox/provider-with-deps/task.yaml
tests/spread/plugins/v1/plainbox/provider-with-stage-packages/task.yaml
tests/spread/plugins/v1/plainbox/run/task.yaml

They intermittently fail and these failures do not appear to be
Snapcraft-specific.  Until the issue is resolved, set the tasks
to manual.
Failure log:
```
python3 manage.py validate
error: ???: Cannot load '/snapcraft/tests/spread/plugins/v1/plainbox/snaps/provider-with-deps/parts/parent-plainbox-provider/build/units/parent.pxu': (chardet 4.0.0 (/snapcraft/tests/spread/plugins/v1/plainbox/snaps/provider-with-deps/stage/lib/python3.6/site-packages), Requirement.parse('chardet<3.1.0,>=3.0.2'), {'requests'})
NOTE: subsequent units from problematic files are ignored
Validation of provider plainbox-provider-parent has failed
```
-----

plainbox spread tests: set tasks to manual

---

snapcraft/internal/project_loader/_extensions/gnome_3_38.py
tests/unit/project_loader/extensions/test_gnome_3_38.py

Ensure pulse libs can be found during linking and set ACLOCAL_PATH to include build snap paths
-----

Include SDK snap paths in ACLOCAL_PATH

---

snapcraft/plugins/_python/_pip.py

pip 21 dropped support for python 3.5 and python 2.
pip >=21 no longer support python3.5 or python 2 and if used will result in a
broken install with pip unable to install packages.
* Drop support for Python 3.5 https://github.com/pypa/pip/issues/9189
* Drop support for Python 2 https://github.com/pypa/pip/issues/6148
-----

plugins: Pin pip to supported versions

---

snapcraft/plugins/v1/_python/_pip.py

pip 21 dropped support for python 3.5 and python 2.
pip >=21 no longer support python3.5 or python 2 and if used will result in a
broken install with pip unable to install packages.
* Drop support for Python 3.5 https://github.com/pypa/pip/issues/9189
* Drop support for Python 2 https://github.com/pypa/pip/issues/6148
-----

plugins v1: Pin pip to supported versions

---

snapcraft/internal/build_providers/_base_provider.py
tests/unit/build_providers/test_base_provider.py

A common issue when a user moves/copies/relocates a project directory,
or re-uses the same project name.
Save the project directory location and verify it when checking
instance compatibility.  If it doesn't match, clean the environment
prior to building.
-----

build providers: clean environment if project directory is changed

---

extensions/desktop/common/fonts

installation to fail on some systems.
-----

Don't error out if font cache generation fails.  This can cause

---

snapcraft/plugins/v2/python.py
tests/unit/plugins/v2/test_python.py

Typo resulted in "opts_state command not found", though unlikely
to cause any real behavioral issues.
Use curly braces, not parenthesis.
-----

python v2 plugin: fix typo restoring shell state

---

snap/snapcraft.yaml

Latest version that works with Snapcraft on all architectures with
current requirements.
E.g. on s390x with 3.4.1 it runs into an issue with pip:
```
Collecting PyYAML==5.3
Downloading PyYAML-5.3.tar.gz (268 kB)
ERROR: Exception:
Traceback (most recent call last):
File "/build/snapcraft-snapcraft-b7d60c/parts/snapcraft/install/lib/python3.6/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
crit = self.state.criteria[name]
KeyError: 'pyyaml'
```
-----

snap: pin cryptography to 3.4

---

extensions/desktop/gnome/Makefile
snapcraft/internal/project_loader/_extensions/gnome_3_28.py
snapcraft/internal/project_loader/_extensions/gnome_3_34.py
snapcraft/plugins/v1/make.py
tests/unit/plugins/v1/test_make.py
tests/unit/project_loader/extensions/test_gnome_3_28.py
tests/unit/project_loader/extensions/test_gnome_3_34.py

Split the Makefile into smaller logical pieces and add a conditional
for bindtextdomain.so. Set bindtextdomain.so to build for GNOME 3.28
and 3.34 extensions.
-----

extensions: add conditional for GNOME Makefile using bindtextdomain

---

snapcraft/_store.py
snapcraft/config.py
snapcraft/storeapi/_metadata.py
snapcraft/storeapi/_sca_client.py
snapcraft/storeapi/_snap_index_client.py
snapcraft/storeapi/_snap_v2_client.py
snapcraft/storeapi/_sso_client.py
snapcraft/storeapi/_up_down_client.py
snapcraft/storeapi/constants.py
tests/fake_servers/api.py
tests/fixture_setup/_fixtures.py
tests/unit/test_config.py
tools/staging_env.sh

Simplify the use of constants to root urls only, using full endpoint
paths where relevant. Rename the constants to reflect the backend
naming for clarity.
-----

storeapi: reduce the amount of constants and their meaning

---

.github/workflows/publish.yaml

This process happens externally (for all architectures).
-----

ci: don't publish snap on push to master

---

snapcraft/_store.py
snapcraft/internal/build_providers/_snap.py
snapcraft/internal/lifecycle/_runner.py
snapcraft/storeapi/_snap_api.py
snapcraft/storeapi/_store_client.py
tests/unit/lifecycle/test_global_state.py

This is the client side API on api.snapcraft.io. Rename and adapt
docstrings to align with reality.
-----

storeapi: rename SnapClientIndex to SnapAPI

---

snapcraft/plugins/v2/python.py
tests/unit/plugins/v2/test_python.py

pip has an especially ugly error when wheel is not installed.  Install
the latest pip, setuptools, and wheel to the v2 python environment.
This may be overriden if/when the user sets python-packages manually,
this just improves the out-of-the-box behavior for the majority of
projects.
LP: #1912244
-----

python v2 plugin: default python-packages to [pip, setuptools, wheel]

---

snapcraft/plugins/v2/python.py
tests/unit/plugins/v2/test_python.py

If the snap is large, there is extra noise iterating over all
executable files.  Replace this loop with xargs to reduce the
output noise.
-----

python v2 plugin: reduce noise by replacing for-loop with xargs

---

snapcraft/plugins/v2/python.py
tests/unit/plugins/v2/test_python.py

There are 25+ bash options that end up being printed multiple
times.  Reduce noise in the output/logs by filtering in the
only option we actually care about.
-----

python v2 plugin: filter set options to reduce output noise

---

snapcraft/internal/meta/_snap_packaging.py
tests/unit/meta/test_meta.py

Snapd supports the "kernel.yaml" file for kernel snaps since
some versions. The file is used to ship boot assets that are
part of the kernel.
The first PR with support can be found here:
https://github.com/snapcore/snapd/pull/9150
This commit adds support for including a `kernel.yaml` as
meta/kernel.yaml in the snap. This will help the pi-kernel
to ship their DTBs as part of the kernel snap.
-----

meta: add support for `kernel.yaml` for kernel snaps

---

snapcraft/storeapi/_store_client.py
snapcraft/storeapi/_ubuntu_sso_client.py
tests/unit/store/test_store_client.py

store: set auth headers when using login --with

---

snapcraft/storeapi/_agent.py
tests/fixture_setup/os_release.py
tests/unit/store/test_agent.py

Removes need for platform.dist() which is not supported in python 3.7+.

[backport] store: improve platform detection (#2931)

---

.github/workflows/spread.yml
tests/spread/general/store/task.yaml
tools/staging_env.sh

ci: run spread store tests when secret is available

---

snapcraft/plugins/v1/godeps.py
tests/spread/plugins/v1/godeps/snaps/godeps-use-build-packages-go-snap/snap/snapcraft.yaml
tests/unit/plugins/v1/test_godeps.py

The godeps plugin breaks with 1.16 due to a change of behavior
with go get (go/src/... is no longer populated as the plugin
expects).
As godeps is no longer maintained, it doesn't really make sense
to update the plugin to work with 1.16.  Simply sets the plugin's
default to the last-known working version of go, 1.15.
-----

godeps: set default channel to 1.15/stable

---

.github/workflows/spread.yml
spread.yaml

This reduces the payload to upload for spread to just the tests
directory. Everything is git commited to keep current reset behavior.
This work implies that when running locally, the snap to be tested
needs be copied into the test directory.
-----

ci: reduce amount of artifacts to upload for spread

---

tests/spread/plugins/v1/crystal/snaps/crystal-hello/hello/shard.lock

tests: crystal 1.0.0 requires shard.lock

---

requirements.txt
snap/snapcraft.yaml

PyNaCl 1.4.0 has crypto related symbol issues when using the system
provided sodium.
-----

requirements: use PyNaCl 1.3.0 and ensure is compiled on linux

---

schema/snapcraft.json
snapcraft/internal/meta/application.py
tests/unit/meta/test_application.py
tests/unit/project/test_schema.py

Add support for the "install-mode" property in snapcraft.yaml apps.
LP: #1907668
-----

Support install-mode option for apps

---

extensions/desktop/common/desktop-exports

When using extensions on systems where a desktop session has never run,
desktop-launch will create noise complaining that paths cannot be found.
Simply redirect the error messages to /dev/null.
E.G, running over SSH in Multipass, using snaps in a CLI environment.
Additionally, prevent behaviour where `rmdir $HOME` would be called
by ensuring the variable is not empty.
This is unlikely to have caused problems as rmdir would not delete directories
that have content, but it's better to not rely on semantics here.
- [Y] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [Y] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [Y] Have you successfully run `./runtests.sh static`?
- [Partial] Have you …

extensions: suppress realpath noise on headless systems

---

snapcraft/internal/errors.py
tests/unit/test_errors.py

Many handlers of command errors are doing their own variant of
the same thing.  This provides a standardized helper to use
details to provide command failure details.

errors: introduce details_from_called_process_error() helper

---

tests/spread/cross-compile/stage-packages/task.yaml

spread: run cross compile tests on amd64 only

---

snapcraft/cli/store.py

It was SNAPCRAFT_LOGIN, which conflicted with commonly named
environment variables used for CI/CD.
-----

cli: rename experimental login environment variable

---

snapcraft/storeapi/_dashboard_api.py
tests/spread/general/store/task.yaml

storeapi: set content-type and accept headers for close

---

snapcraft/internal/repo/_base.py
tests/spread/general/fix-symlink-host-copy/snaps/fix-symlink-host-copy/snap/snapcraft.yaml
tests/spread/general/fix-symlink-host-copy/task.yaml
tests/spread/general/fix-symlink-relative/snaps/fix-symlink-relative/snap/snapcraft.yaml
tests/spread/general/fix-symlink-relative/task.yaml

If the file was copied from host, the symlink was not updated
to point to the new file.  It was logged as being copied, but
the copy wasn't utilized without a fixed (relative) symlink.
Add spread tests to cover relative and host copy cases.

repo: fix regression in fix_symlink()

---

snapcraft/cli/store.py
snapcraft/storeapi/_dashboard_api.py
snapcraft/storeapi/_store_client.py
snapcraft/storeapi/v2/_api_schema.py
snapcraft/storeapi/v2/whoami.py
tests/fake_servers/api.py
tests/spread/general/store/task.yaml
tests/unit/commands/conftest.py
tests/unit/commands/test_whoami.py
tests/unit/store/test_store_client.py
tests/unit/store/v2/test_whoami.py

Add the MVP support for the whoami endpoint to the Store APIs under
Dashboard to serve as a replacement for using the account information
endpoint to serve as the backend to the whoami command.
Caching was removed from the command as the existing caching was too
strict (over caching).
"whoami" command test was rewritten in pure pytest.
-----

store: use whoami dashboard endpoint for cli

---

docker/Dockerfile

This is a followup up #2673. I've noticed that RISK is not passed down, because ARGs are scoped.
https://docs.docker.com/engine/reference/builder/#scope
-----

docker: Need to repeat ARG in every section

---

snapcraft/plugins/v2/conda.py
tests/unit/plugins/v2/test_conda.py

Using the same strategy as the npm v2 plugin to download the correct
miniconda with the additional testing.
Tests were also migrated to pytest.
-----

conda v2 plugin: support for more architectures

---

docker/README.md

Leave only relevant details and mention how to specify Ubuntu version
Addresses https://github.com/snapcore/snapcraft/pull/2673#issuecomment-813871624
-----

Update Docker image instructions

---

snapcraft/internal/repo/_deb.py
tests/spread/plugins/v2/build-and-run-hello/task.yaml
tests/spread/plugins/v2/snaps/python-with-stage-package-in-base/hello
tests/spread/plugins/v2/snaps/python-with-stage-package-in-base/setup.py
tests/spread/plugins/v2/snaps/python-with-stage-package-in-base/snap/snapcraft.yaml
tests/spread/tools/snapcraft-yaml.sh
tests/unit/repo/test_deb.py

To make it easier on users, do not filter python3 packages found
in the core20 base.  Snapcraft will now stage them so that they
can be found in-snap alongside python3 staged packages that are
not found in the base for consistency.
-----

deb: do not filter python3 packages on core20

---

snapcraft/internal/repo/snaps.py
tests/fixture_setup/_unittests.py
tests/unit/repo/test_snaps.py

Otherwise branches can't be staged (LP#1901733).
-----

snaps: don't validate snaps before `SnapPackage.download()`

---

extensions/desktop/common/desktop-exports

-----
This PR cleans up the generation of the user `fonts.conf` file in the desktop extension, partially reverting some of the changes in PR #3299.  Namely:
1. Use fonts from $XDG_DATA_DIRS.  In particular, this means the small number of fonts provided by the platform snap will be visible to applications.  This avoids malfunctions when no fonts are available.
2. Don't include $FONTCONFIG_FILE, since this represents an include loop.
For (1), this has only really manifested in trying to run snaps on Ubuntu Core systems where there is no `desktop` slot available to share system fonts.
For (2), it seems to be a misunderstanding of what the `$XDG_CONFIG_HOME/fontconfig/fonts.conf` file is for.  It isn't used in place of the top level `fonts.conf` file (either identified by `$FONTCONFIG_FILE` …

extensions/desktop: use fonts from $XDG_DATA_DIRS, and remove unnecessary includes

---

snapcraft/storeapi/v2/_api_schema.py
snapcraft/storeapi/v2/validation_sets.py
tests/unit/store/v2/test_validation_sets.py

-----
Full set of changes https://github.com/snapcore/snapcraft/compare/validation-sets

storeapi: add classes for validation sets

---

snapcraft/internal/project_loader/_extensions/gnome_3_28.py
snapcraft/internal/project_loader/_extensions/gnome_3_34.py
snapcraft/internal/project_loader/_extensions/gnome_3_38.py
snapcraft/internal/project_loader/_extensions/kde_neon.py
tests/unit/project_loader/extensions/test_gnome_3_28.py
tests/unit/project_loader/extensions/test_gnome_3_34.py
tests/unit/project_loader/extensions/test_gnome_3_38.py
tests/unit/project_loader/extensions/test_kde_neon.py

-----
This PR updates the GNOME and KDE extensions to configure their desktop plug to set the `mount-host-font-cache: false` interface attribute.  In snapd 2.50, this will instruct the interface not to mount `/var/cache/fontconfig` into the sandbox mount namespace, ensuring that cache files found in that directory cannot be used.  More details can be found in https://github.com/snapcore/snapd/pull/9805.
All of these extensions include code to build a private version of the fontconfig cache, so the host cache can only be a source of problems.
Snapd versions prior to 2.50 do not support this interface attribute, so will ignore it and behave as before.  So there is no need to delay merging this until it is released or update the `assumes` setting.

extensions: don't expose host system fontconfig cache

---

snapcraft/internal/elf.py
tests/unit/test_elf.py

libc6 may mismatch with the paths provided to ldd in LD_LIBRARY_PATH.
This may be avoided if invoking the binary directory and using
LD_TRACE_LOADED_OBJECTS, but this method is limited to executable
files.
This updates the library dependency search to try three variants:
(1) use ldd as today.  if ldd fails..
(2) use ldd with LD_PRELOAD to specify libc6 from host. if ldd fails...
(3) use ld trace method. if ldd trace fails...
(4) warn as before.
For #2, libc6 is expected as /lib/<arch-triplet>/libc.so.6.  This likely
will need to be more robust in the future.
-----

elf: add fallback methods to detect library dependencies

---

.github/workflows/spread.yml
spread.yaml

This change updates the gce project used to run spread tests.
The computeengine project is going to be deprecated soon and the
snapd-spread project has been created to replace it under the canonical
organization.

Use snapd-spread gce project instead of computeengine project

---

snapcraft/plugins/v1/dotnet.py

HTTP is no longer accessible.
-----

dotnet plugin: use https for release metadata url

---

snapcraft/internal/repo/apt_cache.py
snapcraft/internal/repo/errors.py
tests/spread/general/xenial-without-ua-token/snaps/xenial-test/snap/snapcraft.yaml
tests/spread/general/xenial-without-ua-token/task.yaml
tests/unit/repo/test_errors.py

(1) Add some checks to ensure package.candidate is not None before using
it.  If it is None, when expected to not be None, raise a
PackageNotFoundError with the name of the package in question.
(2) Do not iterate over all packages when unmarking.  This is the cause of
https://forum.snapcraft.io/t/snapcraft-crash-when-esm-repositories-are-present/24587/8
where a package was being inspected that did not have an available candidate,
causing Snapcraft to fail unnecessarily.
Fixes SNAPCRAFT-2NE
Fixes SNAPCRAFT-2H2
Fixes SNAPCRAFT-2BC
Fixes SNAPCRAFT-277
Fixes SNAPCRAFT-263
Fixes SNAPCRAFT-1R4
Fixes SNAPCRAFT-1Q5
Fixes SNAPCRAFT-1DH
Fixes a comment in unrelated bug report: LP: #1853682
-----

apt cache: improve error handling when packages do not have candidates available (CRAFT-136) (CRAFT-218)

---

snapcraft/internal/repo/_base.py
snapcraft/internal/repo/_deb.py
tests/spread/general/stage-snaps-normalization/task.yaml
tests/unit/repo/test_base.py

Normalization takes place across the entire working tree for a part.
As a side effect, files that are not part of stage-packages are also
normalized, for that matter, stage-snaps, as those are unpacked first.
When considering the pc snap, Snapcraft creates a snap.pc to correctly
namespace the snaps snap directory. The .pc artifact fixes does not
filter on file type, fileinput is used for the fixup and internally
creates a .bak file as a backup which fails as snap.pc is a directory
and not a file.
-----

repo: normalize if stage-packages and check types (CRAFT-222)

---

snapcraft/internal/build_providers/_multipass/_multipass_command.py
tests/unit/build_providers/multipass/test_multipass_command.py

"brew cask install" no longer works.
-----

build providers: update brew installation (CRAFT-268)

---

snapcraft/storeapi/v2/_api_schema.py

This is returned by the store but rejected by snapcraft

store: Add ReviewInProgress status

---

snapcraft/storeapi/v2/_api_schema.py

The schema was incorrect, causing errors when package names were scoped
in the permissions e.g.; reproduced with something like
snapcraft export-login --snaps <snap-name> login-creds && \
snapcraft login --with login-creds && \
snapcraft whoami
-----

store: whoami schema fix

---

snapcraft/storeapi/_dashboard_api.py
snapcraft/storeapi/errors.py
tests/fake_servers/api.py
tests/unit/store/test_store_client.py

All responses are now logged in debug mode (response.text) and the error
code is properly printed out on registration errors.
-----
A very minimal change PR in case we need to cherry pick it to an older release

storeapi: log responses and registration error code

---

snapcraft/internal/project_loader/_extensions/kde_neon.py
tests/spread/extensions/kde-neon/task.yaml
tests/unit/project_loader/extensions/test_kde_neon.py

- [ X] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [ X] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ X] Have you successfully run `./runtests.sh static`?
- [ X] Have you successfully run `./runtests.sh tests/unit`?
-----
I created a new kde neon content snap because we updated the version of Qt we use and Qt is very fussy about using the same version everywhere.

update kde neon extension to use the newer content snap with qt-5-15-3

---

snapcraft/cli/remote.py
tests/unit/commands/test_remote.py

-----
Remote build currently has a few papercuts.
First of all, if there is no outstanding build, `--recover` literally means nothing: it just spins up another build as if it wasn't supplied at all, which in my experience is never what is desired. It also means there is a disconnect between how `--recover` and `--status` works. Fix that by making `--recover` function more like `--status`, and simply say that there are no builds. Harmony!
Second, one is _always_ prompted about how data being sent to the remote builders is publicly available, even when using options that don't send any meaningful data to the builders, like `--status` and (now) `--recover`. Fix that by no longer using Click to prompt, and prompting only when actually spinning up a new build.
Finally, add tests confirming …

cli: make remote-build more user-friendly

---

snapcraft/cli/echo.py
tests/unit/cli/test_echo.py

Determine if output string is too large for current terminal and
use a pager to echo information using click.echo_via_pager() if so.
If output looks small enough to fit in terminal, use click.echo().
-----

cli: introduce echo.echo_with_pager_if_needed() (CRAFT-380)

---

snapcraft/storeapi/v2/_api_schema.py

Another failure such as #3533
```
snapcraft list-revisions joplin --arch=amd64
'ReviewQueued' is not one of ['Published', 'Unpublished', 'ManualReviewPending', 'NeedsInformation', 'AutomaticallyRejected', 'Rejected', 'ReviewInProgress']
Failed validating 'enum' in schema['properties']['revisions']['items']['properties']['status']:
{'enum': ['Published',
'Unpublished',
'ManualReviewPending',
'NeedsInformation',
'AutomaticallyRejected',
'Rejected',
'ReviewInProgress'],
'introduced_at': 1,
'type': 'string'}
On instance['revisions'][0]['status']:
'ReviewQueued'
```
-----

store: Add ReviewQueued status

---

snapcraft/storeapi/metrics.py
tests/unit/store/test_metrics.py

Adds support for marshalling / unmarshalling requests & responses for
metrics API.
-----

storeapi: introduce data model module for metrics (CRAFT-385)

---

snapcraft/_store.py
snapcraft/storeapi/_dashboard_api.py
snapcraft/storeapi/_store_client.py
snapcraft/storeapi/errors.py
tests/fake_servers/api.py
tests/unit/store/test_store_client.py

- Add support for /dev/api/snaps/metrics endpoint.
- Add ACL token support for package_metrics.
- Add a couple of error helpers to format queries and
error lists suited for get_details() section.  It is
handled a few different ways through the various exceptions
and we should probably consolidate it some in the future.
NOTE: requires re-login to gain appropriate permissions.
-----

store: add API support for metrics (CRAFT-386)

---

snapcraft/cli/_metrics.py
snapcraft/cli/store.py
tests/fixture_setup/_fixtures.py
tests/unit/cli/test_metrics.py
tests/unit/commands/__init__.py
tests/unit/commands/test_metrics.py

- Add metrics command with:
-- required args for name and format.
-- optional args for start and end dates
-- JSON and table format options
- Update fake terminal fixture to support lines
Future work is still required to re-auth if needed, the user
must relogin to get credentials if they don't already have
the package_metrics ACL token.
-----

cli: introduce metrics command (CRAFT-387)

---

snapcraft/storeapi/http_clients/_candid_client.py
snapcraft/storeapi/http_clients/errors.py
tests/unit/store/http_client/test_candid_client.py
tests/unit/store/http_client/test_errors.py

Provide distinct error classes and messages when dealing with tokens.
-----

storeapi: improve candid interaction errors (CRAFT-135)

---

appveyor.yml
setup.py
tools/version.py
windows/snapcraft.iss

Added a simple script to call from AppVeyor to set the version correctly
on 'windows/snapcraft.iss'.
For this, 'determine_version' was extracted from 'setup.py'.
Appveyor has been reconfigured to store the non self signed
'snapcraft-installer.exe'.
-----

win32 installer: store artifact with tagged version (CRAFT-413)

---

schema/snapcraft.json
tests/unit/project/test_schema.py

The code to create this user has [recently landed](https://github.com/snapcore/snapd/pull/10375) in snapd master. It will be most likely be released in 2.52, but for the time being it can be obtained by just installing snapd from the edge channel.

schema: add "microk8s" to the list of allowed system users

---

schema/snapcraft.json
snapcraft/internal/meta/hooks.py
tests/spread/general/environment/expected_snap.yaml
tests/spread/general/environment/snaps/environment-tests/snapcraft.yaml
tests/unit/meta/test_hook.py
tests/unit/meta/test_snap.py
tests/unit/project/test_schema.py

- Consolidate definition of environment in the schema and use it for
global, apps, and now hooks.
- Update meta to support processing hooks.
- Add unit and spread test coverage.
-----

schema: add environment support for hooks (CRAFT-424)

---

snapcraft/cli/lifecycle.py
snapcraft/internal/build_providers/_base_provider.py
tests/unit/build_providers/test_base_provider.py
tests/unit/commands/test_build_providers.py
tests/unit/commands/test_pull_build_stage_prime.py
tests/unit/commands/test_snap.py

Executing lifecycle commands with part names will result
in the parts being dropped when executing snapcraft in the
provided environment.
- Pass these part names along to managed snapcraft.
- Fix type annotation for 'parts' in lifecycle's execute().
LP: #1897337
-----

cli & providers: pass part names for lifecycle commands (CRAFT-481)

---

Makefile
snapcraft/internal/project_loader/_extensions/ros1_noetic.py
snapcraft/internal/project_loader/_extensions/ros2_foxy.py
snapcraft/plugins/v2/_ros.py
tests/spread/plugins/v2/snaps/catkin-noetic-hello/src/snapcraft_hello/package.xml
tests/spread/plugins/v2/snaps/catkin-tools-noetic-hello/src/snapcraft_hello/package.xml
tests/spread/plugins/v2/snaps/colcon-ros2-foxy-rlcpp-hello/package.xml
tests/unit/plugins/v2/test_catkin.py
tests/unit/plugins/v2/test_catkin_tools.py
tests/unit/plugins/v2/test_colcon.py
tests/unit/project_loader/extensions/test_ros1_noetic.py
tests/unit/project_loader/extensions/test_ros2_foxy.py

This PR enables ROS conditional dependencies in `package.xml` such as e.g.
```xml
<build_depend condition="$ROS_VERSION == 1">roscpp</build_depend>
<build_depend condition="$ROS_VERSION == 2">rclcpp</build_depend>
```
It only enables conditions based on "ROS_VERSION", "ROS_DISTRO" and "ROS_PYTHON_VERSION" which are the most commonly encountered.
This is the plugin V2 equivalent of #3313.
-----

ROS V2 plugins: resolve conditional dependencies

---

extensions/ros2/launch
snapcraft/plugins/v2/_ros.py
snapcraft/plugins/v2/catkin.py
snapcraft/plugins/v2/catkin_tools.py
snapcraft/plugins/v2/colcon.py
tests/spread/plugins/v2/colcon-ros2-stage-snap/task.yaml
tests/spread/plugins/v2/snaps/colcon-stage-snaps/CMakeLists.txt
tests/spread/plugins/v2/snaps/colcon-stage-snaps/launch/talker_subscriber.launch.py
tests/spread/plugins/v2/snaps/colcon-stage-snaps/package.xml
tests/spread/plugins/v2/snaps/colcon-stage-snaps/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/colcon-stage-snaps/src/subscriber.cpp
tests/spread/plugins/v2/snaps/test-snapcraft-fake-ros2-package-core20/CMakeLists.txt
tests/spread/plugins/v2/snaps/test-snapcraft-fake-ros2-package-core20/README.md
tests/spread/plugins/v2/snaps/test-snapcraft-fake-ros2-package-core20/include/test_minimal_publisher/subscriber.h
tests/spread/plugins/v2/snaps/test-snapcraft-fake-ros2-package-core20/package.xml
tests/spread/plugins/v2/snaps/test-snapcraft-fake-ros2-package-core20/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/test-snapcraft-fake-ros2-package-core20/src/publisher.cpp
tests/spread/plugins/v2/snaps/test-snapcraft-fake-ros2-package-core20/src/subscriber.cpp
tests/unit/plugins/v2/test_catkin.py
tests/unit/plugins/v2/test_catkin_tools.py
tests/unit/plugins/v2/test_colcon.py

This PR is a follow-up on #3536 and essentially fixes the same issues for ROS 2 plugins v2.
This PR most notably,
- changes the colcon install path from `$SNAPCRAFT_PART_INSTALL` to `$SNAPCRAFT_PART_INSTALL/opt/ros/snap` for a cleaner separation of ROS 2 workspaces (similar to what's in the v1 plugin).
- looks for ROS 2 packages in `$SNAPCRAFT_PART_INSTALL/opt/ros/snap` in case the workspace exists (e.g. provided by a stage-snap) during the build step
- does not `rosdep resolve` packages that are available locally in `$SNAPCRAFT_PART_INSTALL` during stage step. Such locally available package may be part of the built sources or provided by a stage-snap. Furthermore, it fixes the following current issue; if the source contains packages `foo` & `bar` - two packages that are not released in …

ROS 2 plugins v2 misc fixes

---

tools/environment-setup-local.sh

snapcraft.yaml builds cryptography without rust, local development
should match that. Currently rustc toolcahin is not installed, and
when available it may fail to build rust based cryptography 3.4 on
some architectures.
Signed-off-by: Dimitri John Ledkov <dimitri.ledkov@canonical.com>
-----

environment-setup-local: do not build rust

---

snapcraft/internal/build_providers/_base_provider.py
tests/spread/tools/restore.sh
tests/unit/build_providers/test_base_provider.py

Stop injecting core18.
-------
-----

build providers: snapcraft's new base is core20 (CRAFT-544)

---

snapcraft/internal/repo/_deb.py
snapcraft/internal/repo/apt_cache.py
tests/unit/repo/test_apt_cache.py
tests/unit/repo/test_deb.py

Instead of having a split state for stage cache, rely on the
host's cache by setting the state directory to /var/lib/apt.
-----

repo: use host state for apt cache (CRAFT-488)

---

snapcraft/project/_project_info.py
snapcraft/yaml_utils/__init__.py
tests/unit/yaml_utils/test_yaml_utils.py

A very primitive check to warn if duplicate keys are found in
the snapcraft.yaml.  At the moment the file is loaded multiple
times which may result in duplicate warnings (ha ha) which we
need to address in future work.  Given that there shouldn't be
duplicates in YAML files, the extra verbosity should be OK.
-----

yaml: detect and log warning on duplicate keys in snapcraft.yaml (CRAFT-553)

---

snapcraft/internal/lifecycle/_init.py
tests/unit/commands/test_init.py

lifecycle: init with core20 (CRAFT-517)

---

snapcraft/internal/project_loader/_extensions/kde_neon.py
tests/spread/extensions/kde-neon/task.yaml
tests/unit/project_loader/extensions/test_kde_neon.py

Using the same plug name "kde-frameworks-5-plug"
for all providers leads to problems when an
application updates its base or changes its default
provider because a new framework snap gets published
for the same base.
In that case, snapd will keep the old framework snap
connected and will happily connect the new framework
snap in addition to the old one.
This breaks applications because they won't find the correct
framework snap mounted at $SNAP/kf5.
Prevent this by using the same strategy that the gnome
extensions use: plug name = content snap name
See https://forum.snapcraft.io/t/snap-accumulates-content-interface-connections-to-multiple-platform-snaps/27523/8
-----
I built a snap (anki-ppd) with this change and everything works as expected. Also CC @jriddell.
I'm not sure about the …

extensions/kde-neon: use platform snap as plug name

---

snapcraft/internal/remote_build/_launchpad.py
tests/unit/remote_build/test_launchpad.py

Remove the forcing of a specific channel for snapcraft and
core18 (which is no longer relevant as snapcraft moved to core20).
-------
-----

remote build: use channel defaults (CRAFT-568)

---

snapcraft/plugins/v1/autotools.py
tests/unit/plugins/v1/test_autotools.py

The autogen.sh and bootstrap scripts had overeager permissions set
when they were found not to be executable.
The code has also been simplified.
LP: #1951645
-------
-----

autotools v1 plugin: set correct file permissions for scripts (CRAFT-666)

---

snapcraft/internal/lifecycle/_runner.py
tests/unit/lifecycle/test_order_core20.py

core20 uses Plugins V2, there is no plugin logic required from a dependency for
pulling like for V1 Plugins.
-----

lifecycle: do not stage deps for pull on core20 (CRAFT-725)

---

snapcraft/internal/project_loader/_extensions/kde_neon.py
tests/spread/extensions/kde-neon/task.yaml
tests/unit/project_loader/extensions/test_kde_neon.py

From the removed TODO comment:
"remove experimental once sdk is on stable"
As the SDK snap kde-frameworks-5-qt-5-15-3-core20-sdk has
a stable revision now, the experimental flag can
be removed, and the build snap can be pulled from the
stable channel.
-----
~~Includes https://github.com/snapcore/snapcraft/pull/3596, but I can remove that if necessary and rebase later.~~
This is also significant because launchpad build jobs cannot be configured to enable experimental extensions at the moment, which prevents many snaps from using this extension.

extensions/kde-neon: declare non-experimental for core20

---

snapcraft/internal/project_loader/_extensions/_flutter_meta.py
snapcraft/internal/project_loader/_extensions/gnome_3_28.py
snapcraft/internal/project_loader/_extensions/gnome_3_34.py
snapcraft/internal/project_loader/_extensions/gnome_3_38.py
tests/unit/project_loader/extensions/test_flutter.py
tests/unit/project_loader/extensions/test_gnome_3_28.py
tests/unit/project_loader/extensions/test_gnome_3_34.py
tests/unit/project_loader/extensions/test_gnome_3_38.py

Added layout for libdrm, needed by AMD GPUs

---

tests/spread/plugins/v1/flutter/snaps/flutter-hello/src/pubspec.yaml

Github no longer support unauthenticated git
-----

spread: change uri for flutter's pubspec to https

---

snapcraft_legacy/internal/repo/snaps.py

This is #3617 ported to `snapcraft_legacy`.

snap: do not refresh already installed snaps

---

setup.py
snapcraft/cli.py
snapcraft_legacy/cli/legacy.py

Set a new entry point to the snapcraft application. This currently
invokes the legacy implementation in all cases (future PRs will
add logic to decide between new and legacy code execution).
-----

cli: create new snapcraft entry point (CRAFT-729)

---

snapcraft/plugins/v2/npm.py
tests/unit/plugins/v2/test_npm.py

-----
Since snapcraft in lxd/multipass is run as root user, there can be cases where the installation of npm packages fails with "permission denied". This issue has been lurking around for a long time and there isn't really a workaround apart from not using the npm plugin and shipping npm in a custom part.
The reason for that is that npm plugin's `get_build_commands` method downloads npm from upstream and then in the next command calls `npm install` and `npm pack`, leaving no way for the developers to configure npm at all.
Here is one related issue https://forum.snapcraft.io/t/issue-with-nodejs-plugin-when-using-base-keyword/11109/14

npm plugin: allow running as root

---

snapcraft/plugins/v2/npm.py
tests/unit/plugins/v2/test_npm.py

-----
It seems the changes that landed via https://github.com/snapcore/snapcraft/commit/52c6c7d9ce7db66a6575845d88e73067229ec2d9 weren't enough, there is another fundamental issue lurking. The node archive that is downloaded from upstream, when extracted, are owned by user `1001`, this is causing the case where installation would fail with permission denied (npm surprise!). The proposed change does actually fix the issue as I have verified it.

npm plugin: extract node archive without preserving ownership

---

snapcraft/internal/common.py

The autotools plugin will attempt to run `autogen.sh` or `bootstrap` scripts if they are present in the part's source. However, the internal representation of these scripts is a `Path` object, not a string, so when passed to `shlex` it throws an exception stating that it was expecting a bytes-like object.
Signed-off-by: Dani Llewellyn <dani@bowlhat.net>
-----

Autotools Plugin (v1): Fix fatal crash when running autogen.sh or bootstrap

---

schema/snapcraft.json
snapcraft/internal/pluginhandler/__init__.py
snapcraft/internal/remote_build/_worktree.py
snapcraft/internal/sources/_7z.py
snapcraft/internal/sources/__init__.py
snapcraft/internal/sources/_base.py
snapcraft/internal/sources/_bazaar.py
snapcraft/internal/sources/_deb.py
snapcraft/internal/sources/_git.py
snapcraft/internal/sources/_mercurial.py
snapcraft/internal/sources/_rpm.py
snapcraft/internal/sources/_script.py
snapcraft/internal/sources/_snap.py
snapcraft/internal/sources/_subversion.py
snapcraft/internal/sources/_tar.py
snapcraft/internal/sources/_zip.py
snapcraft/internal/states/_pull_state.py
tests/spread/general/sources/snaps/git-submodules/snapcraft.yaml
tests/spread/general/sources/task.yaml
tests/spread/plugins/v1/x-local/local-plugin-x-compat/state-pull
tests/spread/plugins/v1/x-local/local-plugin/state-pull
tests/unit/__init__.py
tests/unit/pluginhandler/test_state.py
tests/unit/remote_build/test_worktree.py
tests/unit/sources/test_git.py
tests/unit/states/test_pull.py

-----
Alternative solution from https://github.com/snapcore/snapcraft/pull/3623
https://bugs.launchpad.net/snapcraft/+bug/1957767
Configure which submodules to fetch from the source tree in snapcraft.yaml with `source-submodules: <list-of-submodules>`. 
If `source-submodules` is defined, only the listed submodules are fetched.
```
parts:
git-test:
plugin: dump
source-type: git
source: git@github.com...
source-submodules:
- submodule_1
- dir1/submodule_2
```
If `source-submodules` in defined and empty, no submodules are fetched.
```
parts:
git-test:
plugin: dump
source-type: git
source: git@github.com...
source-submodules: []
```
If `source-submodules` is not defined, all submodules are fetched (default behavior).
If a submodule is fetched, any submodules of that submodules are fetched …

sources: make submodule fetching configurable

---

snapcraft/internal/pluginhandler/_dependencies.py
snapcraft/internal/repo/_deb.py
snapcraft/internal/repo/errors.py
tests/unit/pluginhandler/test_missing_dependency.py
tests/unit/repo/test_deb.py

-----
Improvements to resolution of missing libraries.
<div class="OutlineElement Ltr  BCX2 SCXO33065325" style="margin-left: 0px; direction: ltr;"><div class="TableContainer SCXO33065325 BCX2"><div id="{b857542e-4fa0-4221-8d46-26722fa234f7}{136}" class="WACAltTextDescribedBy SCXO33065325 BCX2" aria-hidden="true"></div>
scenario | description | examples | previous behavior | new behavior
-- | -- | -- | -- | --
1 | snapcraft resolves library path | normal usage | suggests package to stage | suggests package to stage
2 | snapcraft resolves library path with symlinks | <ul><li>`usrmerge` package installed</li><li>custom library, i.e. library package has postinst action to make symlinks</li></ul> | **dpkg error** | suggests package to stage
</div></div>
</br>
For testing, this repo exercises …

dependencies: missing library resolution (CRAFT-422)

---

.gitignore
pyproject.toml
snapcraft/commands/lifecycle.py
snapcraft/errors.py
snapcraft/parts/lifecycle.py
snapcraft/parts/validation.py
snapcraft/projects.py
tests/unit/commands/test_lifecycle.py
tests/unit/parts/test_lifecycle.py
tests/unit/test_projects.py

Add pydantic model and validators for the snapcraft.yaml project file,
based on legacy schema and public documentation.
Package layout was slightly changed to prevent cyclic imports during
test execution. The layout may be further changed during the integration
of craft-parts. Additional validation and tests will be added as more features are
implemented.
-----

projects: add project model and validation (CRAFT-763)

---

snapcraft/meta/__init__.py
snapcraft/meta/snap_yaml.py
snapcraft/parts/lifecycle.py
snapcraft/parts/parts.py
snapcraft/projects.py
tests/conftest.py
tests/unit/meta/test_snap_yaml.py
tests/unit/test_projects.py

Create a minimal snap.yaml metadata file from data we already have
available to enable snap packing.
-----

meta: generate basic snap.yaml (CRAFT-801)

---

pyproject.toml
snapcraft/os_release.py
tests/unit/test_os_release.py

Create a class around parsing `/etc/os-release` so we can gracefully
fallback as appropriate when e.g. `VERSION_CODENAME` isn't set. This is
a forward port of a25cfcc (PR #1636) by Kyle Fazzari.
Co-authored-by: Kyle Fazzari <kyrofa@ubuntu.com>
-----

utils: gracefully determine host os (CRAFT-845)

---

snapcraft/internal/project_loader/_extensions/kde_neon.py
tests/unit/project_loader/extensions/test_kde_neon.py

Add a layout for KF5 to find the information it requires.
-----

extension: compose and deadkeys for neon

---

snapcraft/plugins/v2/colcon.py
tests/unit/plugins/v2/test_colcon.py

Colcon v2 plugin has a parameter, `colcon-cmake-args`, to define cmake args (for plain cmake packages). Said args were not forwarded to the build command.
-----

colcon v2: forward cmake args

---

pyproject.toml
snapcraft/meta/snap_yaml.py
snapcraft/projects.py
snapcraft/repo/__init__.py
snapcraft/repo/apt_key_manager.py
snapcraft/repo/apt_ppa.py
snapcraft/repo/apt_sources_manager.py
snapcraft/repo/errors.py
snapcraft/repo/package_repository.py
snapcraft/repo/projects.py
tests/unit/parts/test_lifecycle.py
tests/unit/repo/test_apt_key_manager.py
tests/unit/repo/test_apt_ppa.py
tests/unit/repo/test_apt_sources_manager.py
tests/unit/repo/test_package_repository.py
tests/unit/repo/test_projects.py
tests/unit/test_projects.py

Port definitions and helpers to add apt repositories and PPAs. Original
code from PRs #2911, #3341, #3359, #3363.
-----

repo: add package repository handling (CRAFT-846)

---

snapcraft/meta/snap_yaml.py
snapcraft/projects.py
tests/unit/meta/test_snap_yaml.py
tests/unit/test_projects.py

-----
Parse `environment` dictionary in snapcraft.yaml, both for apps and at the root level.

meta: parse environment variables (CRAFT-835)

---

tests/unit/commands/test_version.py

tests: pass proper type to run for version

---

Makefile

-----
`autoformat-black` should only apply to source files, matching `test-black`.

lint: apply autoformat-black to source files

---

pyproject.toml
requirements-devel.txt
requirements.txt
setup.py
snapcraft/cli.py
snapcraft/commands/lifecycle.py
snapcraft/pack.py
snapcraft/parts/lifecycle.py
snapcraft/providers/__init__.py
snapcraft/providers/_buildd.py
snapcraft/providers/_get_provider.py
snapcraft/providers/_logs.py
snapcraft/providers/_lxd.py
snapcraft/providers/_multipass.py
snapcraft/providers/_provider.py
snapcraft/utils.py
tests/spread/general/core22/task.yaml
tests/spread/plugins/v1/flutter/snaps/flutter-hello/src/pubspec.yaml
tests/unit/cli/test_default_command.py
tests/unit/cli/test_lifecycle.py
tests/unit/parts/test_lifecycle.py
tests/unit/test_pack.py

Run lifecycle commands inside a build provider using lxd or multipass.
Craft-providers glue code based on Chris Patterson's implementation for
Charmcraft. Note: multipass images for multipass will be fixed when base
devel is implemented.
-----

providers: integrate craft-providers support

---

snapcraft/internal/project_loader/_extensions/kde_neon.py
tests/unit/project_loader/extensions/test_kde_neon.py

- [x ] Have you followed the [guidelines for contributing](https://github.com/snapcore/snapcraft/blob/master/CONTRIBUTING.md)?
- [x ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [x ] Have you successfully run `./runtests.sh static`?
- [x ] Have you successfully run `./runtests.sh tests/unit`?
enable lzo compression in kde-neon extension by default
from chatting with ppd and post at https://forum.snapcraft.io/t/lzo-for-platform-snaps/27501
-----

set lzo compression by default in kde-neon extension

---

snapcraft/plugins/v1/gradle.py

Allow users to choose JDK 17.
JDK 17 is available in bionic: https://packages.ubuntu.com/search?suite=bionic&searchon=names&keywords=openjdk-17-jdk
Not having this feature causes my snap to both have JRE 11 *and* 17: https://github.com/EduMIPS64/edumips64/issues/657
In an attempt to not inadvertently have lots of snaps build with JDK 17,
also change the default JDK to be 11, changing the default stated behavior
from auto-picking the last JDK available in the base (which was not happening
anyway) to auto-picking version 11.
-----

feat: add support for JDK 17 in the Gradle plugin

---

docker/Dockerfile

This change fixes some issues with the Python installation within a
Docker container containing snapcraft built from the docker/Dockerfile
in the project as described here:
https://bugs.launchpad.net/snapcraft/+bug/1956216
Background: The image built from the Dockerfile used to work fine. Some
weeks/months ago, it stopped working out of a sudden. Digging into the
failures, it seems the Python installation that comes with recent
snapcraft versions seems to be somehow broken. This change remedies this
by fixing up the Python installation after installation within the
Docker image. For this, we:
- Adjust PATH so the correct Python interpreter will be used.
- Fix a symlink.
- Add a *.pth file to make sure the Python 3 in the snapcraft snap finds
its own site-packages (for some reason, the …

Launchpad bug 1956216: Fix Python installation

---

snapcraft/plugins/v2/_plugin.py
snapcraft/plugins/v2/_ros.py
snapcraft/plugins/v2/catkin.py
snapcraft/plugins/v2/catkin_tools.py
snapcraft/plugins/v2/colcon.py
tests/spread/plugins/v2/colcon-ros2-hello/task.yaml
tests/spread/plugins/v2/ros1-hello/task.yaml
tests/spread/plugins/v2/snaps/catkin-noetic-subdir/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/catkin-noetic-subdir/subdir/src/snapcraft_hello/CMakeLists.txt
tests/spread/plugins/v2/snaps/catkin-noetic-subdir/subdir/src/snapcraft_hello/package.xml
tests/spread/plugins/v2/snaps/catkin-noetic-subdir/subdir/src/snapcraft_hello/src/hello.cpp
tests/spread/plugins/v2/snaps/catkin-tools-noetic-subdir/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/catkin-tools-noetic-subdir/subdir/src/snapcraft_hello/CMakeLists.txt
tests/spread/plugins/v2/snaps/catkin-tools-noetic-subdir/subdir/src/snapcraft_hello/package.xml
tests/spread/plugins/v2/snaps/catkin-tools-noetic-subdir/subdir/src/snapcraft_hello/src/hello.cpp
tests/spread/plugins/v2/snaps/colcon-subdir/colcon-ros2-foxy-rlcpp-hello/CMakeLists.txt
tests/spread/plugins/v2/snaps/colcon-subdir/colcon-ros2-foxy-rlcpp-hello/hello.cpp
tests/spread/plugins/v2/snaps/colcon-subdir/colcon-ros2-foxy-rlcpp-hello/package.xml
tests/spread/plugins/v2/snaps/colcon-subdir/snap/snapcraft.yaml
tests/spread/plugins/v2/snaps/colcon-subdir/this-package-should-not-be-compiled/CMakeLists.txt
tests/spread/plugins/v2/snaps/colcon-subdir/this-package-should-not-be-compiled/package.xml
tests/unit/plugins/v2/test_catkin.py
tests/unit/plugins/v2/test_catkin_tools.py
tests/unit/plugins/v2/test_colcon.py

Update comment
Remove useless dependency in catkin_tools.
Now python3-osrf-pycommon is an explicit dependency of
python3-catkin-tools
see:
http://packages.ros.org/ros/ubuntu/dists/focal/main/binary-amd64/Packages
Use source-subdir for rosdeps dependencies pull
Use source-subdir for ROS plugins v2
Adapt test to match new ROS tools v2 source-subdir use
Add test for Colcon V2 subdir usage
Add tests for catkin/catkin-tools V2 subdir usage
-----

ROS plugins v2: respect source-subdir key

---

schema/snapcraft.json
tests/unit/project/test_schema.py

-----
This PR adds schema support for the `activates-on` property of apps.  The property holds a list of slot names representing D-Bus bus names the service activates on.  The property only makes sense when used with `daemon` type apps.
Like PR #3129, support for this feature is currently gated behind a snapd experimental feature flag (`experimental.dbus-activation` in this case).  So merging it might need to wait until the feature is turned on by default.

schema: add support for activates-on app property to schema

---

setup.cfg
snapcraft/errors.py
snapcraft/extensions/__init__.py
snapcraft/extensions/_extension.py
snapcraft/extensions/_utils.py
snapcraft/extensions/registry.py
snapcraft/parts/lifecycle.py
tests/unit/extensions/__init__.py
tests/unit/extensions/conftest.py
tests/unit/extensions/test_extensions.py
tests/unit/extensions/test_registry.py
tests/unit/extensions/test_utils.py

This adds some variations to the API and changes where things are
processed when compared to the original implementation.
For integration it is rather hard to test until there is an extension
implementation to test with, so the current code only makes sure that
use of apply_extensions does not break the current implementation.
-----
CRAFT-861

extensions: support core22

---

tests/spread/plugins/v2/snaps/python-hello-multiple-parts-staged/setup.py
tests/spread/plugins/v2/snaps/python-hello-multiple-parts/setup.py

-----
[`setuptools-61.1.0`](https://setuptools.pypa.io/en/latest/history.html#breaking-changes) broke two spread tests:
- `tests/spread/plugins/v2/build-and-run-hello:python_multiple_parts`
- `tests/spread/plugins/v2/build-and-run-hello:python_multiple_parts_staged`
The following error is produced:
```
Successfully installed pip-22.0.4 setuptools-61.0.0 wheel-0.37.1
+ '[' -f setup.py ']'
+ pip install -U .
Processing /root/parts/hello/build
Preparing metadata (setup.py) ... error
error: subprocess-exited-with-error
× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [14 lines of output]
error: Multiple top-level packages discovered in a flat-layout: ['snap', 'empty'].
To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this …
```

spread: fix python-hello

---

snapcraft/parts/lifecycle.py
snapcraft/parts/yaml_utils.py
tests/unit/parts/test_yaml_utils.py

- Move yaml loading to a new module in the part package: yaml_utils
- Forward port the safe loading implementation from legacy
LP: #1942217
-----
CRAFT-829

parts: raise error when duplicate keys are used

---

snapcraft/internal/pluginhandler/_part_environment.py
snapcraft/plugins/_plugin_finder.py
snapcraft/plugins/v2/__init__.py
snapcraft/plugins/v2/crystal.py
tests/spread/plugins/v2/build-and-run-hello/task.yaml
tests/spread/plugins/v2/snaps/crystal-hello/hello.cr
tests/spread/plugins/v2/snaps/crystal-hello/shard.lock
tests/spread/plugins/v2/snaps/crystal-hello/shard.yml
tests/spread/plugins/v2/snaps/crystal-hello/snap/snapcraft.yaml
tests/unit/plugins/v2/test_crystal.py
tests/unit/project_loader/test_environment.py

-----
Initial implementation of a v2 Crystal plugin.  Manually tested by loading in the changes as a local plugin and build a Crystal shard via snap.
> **NOTE:** You'll need to name the local plugin `PluginImpl` instead of `CrystalPlugin`
@mamantoha If you could test with your project that would be 💯.
Some things that still need handled:
* Ideally we update it once https://github.com/crystal-lang/shards/issues/518 is implemented/released
(CRAFT-823)

plugins: add crystal v2 plugin

---

snapcraft/parts/lifecycle.py
snapcraft/parts/yaml_utils.py
tests/unit/parts/test_lifecycle.py
tests/unit/parts/test_yaml_utils.py

The yaml loader is shared, the strategy is to load twice, once with the
plain safe loader to check for the base and raise if necessary, then
load again with Snapcraft's new custom _SafeLoader.
-----

parts: consider non core22 when loading yaml

---

requirements-devel.txt
requirements.txt
snapcraft/parts/lifecycle.py
snapcraft/parts/parts.py

Update craft-parts to version 1.4.2 to fix long loops blocking the
sequencer in projects with many dependency-chained parts (such
as gnome-sdk). Fix verbosity levels in the managed containers
to display craft-parts debug messages. Pause the emitter during
execution and redirect output streams to improve output readability.
-----
CRAFT-975

parts: fix long recursion when verifying dirty steps

---

requirements-devel.txt
setup.cfg
setup.py
snapcraft/cli.py
snapcraft/commands/__init__.py
snapcraft/commands/extensions.py
tests/unit/commands/test_list_extensions.py
tests/unit/conftest.py

Bring in the extensions available from the new code base and then mesh
them with the ones from legacy.
Use inheritance to support the alias of extensions to list-extensions.
-----
CRAFT-947

commands: list-extensions and extensions alias

---

snapcraft/providers/_buildd.py

If a new injection is required it should also be performed on
instance warm-up. Note that snaps that are already installed won't
be reinstalled.
-----

providers: override instance warmup

---

snapcraft/cli.py
tests/unit/cli/test_help.py

Handle craft-cli's `ProvideHelpException` error to display the same
message displayed when invoked using the `--help` option.
-----

cli: fix help command legacy fallback

---

snapcraft/cli.py
snapcraft/commands/__init__.py
snapcraft/commands/lifecycle.py
snapcraft/pack.py
snapcraft/parts/lifecycle.py
snapcraft/providers/__init__.py
snapcraft/providers/_get_provider.py
tests/spread/general/core22/packing/snap/snapcraft.yaml
tests/spread/general/core22/packing/task.yaml
tests/unit/commands/test_lifecycle.py
tests/unit/parts/test_lifecycle.py

Allow usage of the legacy command `snap` to create a snap package, and
fix passing the output parameter to the managed instance.
-----
CRAFT-984

commands: add snap command

---

snapcraft/utils.py
tests/unit/test_utils.py

distutils is mostly going away in Python 3.12
-----

utils: in-house strtobool implementation

---

.github/workflows/publish.yaml

If the new environment "secret" is set, trigger use of the new workflow.
-----
CRAFT-1022
Relates to snapcore/action-publish#27

gha: setup alternative publication action

---

snapcraft/parts/lifecycle.py
snapcraft/parts/parts.py
tests/unit/parts/test_parts.py

-----
Pass `project_name` to craft_parts for the [Conda plugin](https://github.com/canonical/craft-parts/pull/201).
(CRAFT-1029)

lifecycle: pass project name

---

Makefile
pyproject.toml
snapcraft/errors.py
snapcraft/meta/appstream.py
snapcraft/meta/extracted_metadata.py
snapcraft/meta/metadata.py
tests/unit/meta/test_appstream.py
tests/unit/meta/test_metadata.py

Extract application metadata from appstream files.
Co-authored-by: Kyle Fazzari <kyle@canonical.com>
Co-authored-by: Leo Arias <leo.arias@canonical.com>
Co-authored-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-----
CRAFT-1033

meta: add appstream metadata extractor

---

snapcraft/providers/_lxd.py

Update lxd image from daily to final 22.04.
-----

providers: use final 22.04 lxd image

---

snapcraft/utils.py
tests/unit/test_utils.py

Imported from Charmcraft with tests updated to use mocker.
-----

utils: platform detection logic

---

snapcraft/utils.py
tests/unit/test_utils.py

No functional change, tests update to pytest
-----

utils: port humanize_list from Snapcraft legacy

---

snapcraft/meta/snap_yaml.py
snapcraft/projects.py
tests/unit/meta/test_snap_yaml.py
tests/unit/parts/test_lifecycle.py
tests/unit/test_projects.py

Grade is an optional field and assumed as stable if not explicitly
set in project or adopted metadata.
-----

projects: field grade is not mandatory

---

setup.py
snapcraft/errors.py
snapcraft/meta/snap_yaml.py
snapcraft/parts/desktop_file.py
snapcraft/parts/lifecycle.py
snapcraft/parts/parts.py
snapcraft/parts/setup_assets.py
snapcraft/parts/update_metadata.py
tests/spread/general/core22/appstream-desktop/snaps/appstream-desktop/snap/snapcraft.yaml
tests/spread/general/core22/appstream-desktop/task.yaml
tests/unit/parts/test_desktop_file.py
tests/unit/parts/test_setup_assets.py

Copy icon and desktop files to the snap payload and edit entries in
the desktop file to point to the correct executables and icon files.
Co-authored-by: Leo Arias <leo.arias@canonical.com>
Co-authored-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-----
CRAFT-1039

parts: set up snap assets

---

snapcraft/repo/apt_sources_manager.py
tests/unit/repo/test_apt_sources_manager.py

Remove legacy hook to obtain host architecture, use OsPlatform instead.
-----

repo: get host architecture using non-legacy code

---

requirements-devel.txt
requirements.txt
setup.py
tests/legacy/unit/project/test_project_info.py

Unpin mccabe and PyYAML, allow libyaml binding with python 3.10.
-----

requirements: unpin pyyaml and update dependencies

---

snapcraft/meta/snap_yaml.py

Set yaml dumping to allow unicode. This fixes formatting of multiline
text in e.g. snap.yaml when it contains unicode characters.
-----

meta: dump unicode yaml data

---

tests/unit/parts/test_lifecycle.py

Fix lifecycle tests to not run on the current directory.
-----

tests: fix lifecycle tests to run on new directory

---

snapcraft/utils.py
tests/unit/test_utils.py

Solve the case of a 64 kernel running a 32 bit userpace
-----

utils: return the userspace architecture

---

snapcraft/meta/snap_yaml.py
snapcraft/projects.py
tests/spread/core22/appstream-desktop/expected_snap.yaml
tests/unit/meta/test_snap_yaml.py
tests/unit/parts/test_lifecycle.py
tests/unit/test_projects.py

Fix undeclared snap type and app list if no apps defined.
-----

meta: fix snap yaml generation to match legacy

---

spread.yaml
tests/spread/plugins/v1/python/pbr/task.yaml

This is not needed for spread under google, set up git author and email
through environmnent variables for general system support (e.g.;
Multipass).
-----

spread: remove git user config from pbr test

---

tests/spread/core22/clean/task.yaml

Tests are ordinarily conducted in destructive mode, enable lxd in
provider cleaning tests.
-----

tests: use lxd in clean provider test

---

snapcraft/commands/lifecycle.py
snapcraft/parts/lifecycle.py
snapcraft/parts/parts.py
tests/unit/cli/test_default_command.py
tests/unit/cli/test_lifecycle.py
tests/unit/parts/test_lifecycle.py

Handle arguments --debug, --shell and --shell-after to run a shell
on the build environment (tipically on instance) in case of a parts
error or to replace a lifecycle step.
-----
CRAFT-993

parts: run debug shell on build environment

---

snapcraft/meta/snap_yaml.py
snapcraft/parts/setup_assets.py
snapcraft/projects.py
tests/unit/meta/test_snap_yaml.py
tests/unit/test_projects.py

Improve project layout validation and add layout definition to
snap.yaml. Also change project definition to not allow extra fields,
and fix toplevel and part environment field type.
-----

meta: add layout to snap.yaml

---

snapcraft_legacy/plugins/v1/_plugin.py
tests/legacy/unit/plugins/v1/test_base.py

-----
Convert `Path` to `string` for commands in legacy v1 plugins.  Add regression tests.
Bug was exposed when https://github.com/snapcore/snapcraft/pull/3601/files started using `pathlib` for `autotools`.  
@diddledani partially fixed the issue https://github.com/snapcore/snapcraft/pull/3628, but this PR should wrap up the issue.

legacy: plugins: convert paths to strings for commands

---

snapcraft/parts/lifecycle.py
snapcraft/parts/setup_assets.py
tests/unit/parts/test_setup_assets.py

If the snap type is gadget, then the project root gadget.yaml must be copied into meta/gadget.yaml.
If the snap type is kernel, then the project root kernel.yaml can be copied into meta/kernel.yaml
-----
CRAFT-1072

parts: copy kernel.yaml and gadget.yaml

---

snapcraft/pack.py
tests/unit/test_pack.py

Run "snap pack --check-skeleton" until "snap pack" does it.
-----

pack: check skeleton

---

extensions/desktop/common/init

-----
This fixes error caused by `desktop-launch` loading `amd64` `bindtextdomain.so` first from `gnome-platform` then `i386` from snap.
```
ERROR: ld.so: object '/snap/test/x1/gnome-platform/$LIB/bindtextdomain.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

extensions/desktop: preload bindtextdomain from snap first if it exists

---

snapcraft/meta/snap_yaml.py
snapcraft/projects.py
tests/unit/meta/test_snap_yaml.py
tests/unit/test_projects.py

Contrary to what was done for legacy, make the system-usernames much more lax.
More strict errors should be raised by "snap pack".
-----
CRAFT-1083

project: support system-usernames

---

snapcraft/projects.py
tests/unit/test_projects.py

-----
Allow for other data types in slot sub-fields in core22, similar to core20 behavior.
The TODO for slot validation (casting and validating ContentSlots, DbusSlots) is still left open, as this is a much larger effort.
(CRAFT-1084)

slots: allow lists

---

bin/snapcraftctl-compat
setup.py
snap/snapcraft.yaml
tests/spread/core22/craftctl/task.yaml
tests/spread/core22/craftctl/test-craftctl-snapcraftctl-compat/Makefile
tests/spread/core22/craftctl/test-craftctl-snapcraftctl-compat/hello.c
tests/spread/core22/craftctl/test-craftctl-snapcraftctl-compat/snap/snapcraft.yaml
tests/spread/core22/environment/test-variables/task.yaml
tests/spread/core22/package-repositories/task.yaml
tests/spread/core22/scriptlets/task.yaml

Add snapcraftctl wrapper to craftctl to make the transition to core22
easier. Execution of the wrapper displays a message encouraging the
user to update to craftctl.
Also add a spread test and fix existing core22 spread tests that were
not being executed.
-----
CRAFT-965

craftctl: add snapcraftctl compatibility wrapper

---

spread.yaml
tests/spread/core22/clean/task.yaml
tests/spread/core22/craftctl/task.yaml
tests/spread/core22/environment/paths/task.yaml
tests/spread/core22/environment/test-variables/task.yaml
tests/spread/core22/packing/task.yaml
tests/spread/core22/scriptlets/task.yaml

-----
`core22 latest/edge` now depends on `snapd 2.55.5`, which is not easily available to the github runners.  This is preventing spread tests from running.
Error:
```
+ snap install core22 --edge
error: cannot install "core22": snap "core22" assumes unsupported features:
snapd2.55.5 (try to refresh snapd)
```
Source: https://github.com/snapcore/core-base/commit/ed8f06c2ed30dc6084fc11591372744d67e2e4bb#diff-e68b9afd67bb77dec8eda77796d3e0b784c7011203114996383eed6533be0cefR11

spread: move core22 to stable

---

requirements-devel.txt
requirements.txt
tests/spread/core22/environment/test-variables/task.yaml

Update dependencies including craft-providers to 1.3.0 (fixes snap
injection) and craft-parts to 1.7.1 (fixes plugin validation
dependencies).
-----

requirements: update dependencies

---

snapcraft/meta/snap_yaml.py
snapcraft/parts/lifecycle.py
snapcraft/parts/parts.py
snapcraft/projects.py
snapcraft/utils.py
tests/spread/core22/appstream-desktop/expected_snap.yaml
tests/spread/general/unicode-metadata/task.yaml
tests/unit/meta/test_snap_yaml.py
tests/unit/test_projects.py
tests/unit/test_utils.py

-----
Properly determine path for LD_LIBRARY_PATH for core22.  The behavior should be identical to core20.
This is a hasty PR.  I still have a few changes to make, perhaps they can be in a follow up PR if this one needs to get merged ASAP.  
Changes to make:
1. More unit tests
2. Some cleanup/refactoring (documentation, comments, types)
(CRAFT-1095)
LP: # [1975498](https://bugs.launchpad.net/snapcraft/+bug/1975498)

environment: get LD_LIBRARY_PATH

---

snapcraft/pack.py
tests/unit/test_pack.py

-----
I accidentally found a bug in the `pack_snap()` unit tests where the tests would fail if `/tmp/foo/` existed.
After looking at the coverage report, I noticed the path comparison logic for `pack_snap()` was broken.
Changes:
1. Fix logic for path comparison.
2. Fix test that failed when `/tmp/foo/` existed.
3. Add 3 more unit tests to better exercise `pack_snap()`.

pack: check if output directory is current working directory

---

snapcraft/parts/setup_assets.py
tests/unit/parts/test_setup_assets.py

When preparing metadata assets, don't attempt to copy files if they
are already where the system expects it to be.
-----

parts: don't copy metadata if already at destination

---

snapcraft/extensions/gnome.py
tests/unit/extensions/test_gnome.py

The snaps generated with the gnome-42 extension didn't have the
LD_LIBRARY_PATH correctly set.
This patch fixes it.
-----

extensions: fix gnome run environment

---

snapcraft/extensions/extension.py
snapcraft/extensions/gnome.py
tests/unit/extensions/test_extensions.py
tests/unit/extensions/test_gnome.py

This MR adds two functions that simplifies the management of environment variables, allowing to just pass the name of one variable and one or more paths, and they will return a piece of shell code that prepends or appends the paths to the variable, taking into account the case when the variable is empty, to avoid adding a trailing or leading colon.
-----

extensions: prepend and append functions for ENV

---

snapcraft/meta/appstream.py
snapcraft/parts/setup_assets.py
snapcraft_legacy/internal/meta/_snap_packaging.py
tests/legacy/unit/meta/test_meta.py
tests/legacy/unit/meta/test_snap_packaging.py
tests/spread/general/stub-hooks/snap/snapcraft.yaml
tests/spread/general/stub-hooks/task.yaml
tests/unit/parts/test_setup_assets.py

This is mostly relevant for when using extensions (like the
desktop ones that add a "configure" hook to set up the font
cache).
The original implementation lives in
snapcraft_legacy/internal/meta/_snap_packaging
.py::_SnapPackaging::generate_hook_wrappers
-----

setup assets: ensure hooks when command-chain is present

---

snapcraft/providers/_provider.py

Signed-off-by: artivis <jeremie.deray@canonical.com>
-----
Forward `SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS` to providers allowing to actually enable experimental extensions.

provider: forward SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS

---

snapcraft/meta/snap_yaml.py
snapcraft/providers/_buildd.py
tests/spread/general/version-git/task.yaml
tests/unit/meta/test_snap_yaml.py

Add special handling for projects with `version: git` so that the
snap version is set to the result of `git describe --dirty`.
-----

meta: handle version git

---

snapcraft/utils.py
tests/spread/core22/environment/paths/task.yaml
tests/spread/core22/environment/snaps/staged-common-library/expected_snap.yaml
tests/spread/core22/environment/snaps/staged-common-library/snap/snapcraft.yaml
tests/spread/core22/environment/snaps/staged-common-library/test-cmd
tests/unit/test_utils.py

-----
1. Add another spread test for LD_LIBRARY_PATH
2. Deprecate `ld.conf.so` library path searching for `libgl1-mesa`.
[This code](https://github.com/snapcore/snapcraft/pull/204) was original merged in 2016 for `libopencv-dev`, which pulled in the `libgl1-mesa` as a dependency.
It is no longer needed because:
1. `/usr/lib/<arch>/mesa/ld.conf.so` was removed from the `libgl1-mesa` libraries in version 18.2.8, in 2018
2. Ubuntu started using `libgl1-mesa` >= 18.2.8 in 18.04
3. `/usr/lib/<arch>/mesa/ld.conf.so` still doesn't exist in 22.04 / core22

enviroment: deprecate ld.conf.so library path searching for libgl1-mesa

---

snapcraft/pack.py
tests/spread/core22/snap-creation/task.yaml
tests/unit/test_pack.py

When packing a snap, show the packed snap filename upon completion.
-----

pack: display snap filename

---

pyproject.toml
snapcraft/parts/lifecycle.py
snapcraft/parts/project_check.py
snapcraft/parts/update_metadata.py
tests/unit/parts/test_desktop_file.py
tests/unit/parts/test_lifecycle.py

-----
`snapcraft/parts/` and `tests/unit/parts/` were ignored by black.

lint: apply black to parts directories

---

snapcraft/parts/yaml_utils.py
tests/unit/parts/test_yaml_utils.py

-----
I was trying to build a snap with the following in its snapcraft.yaml:
```yaml
base: whatever
build-base: core22
```
... and Snapcraft fell back to its legacy mode, printing the following in the trace log:
```
2022-06-13 19:58:20.422 run legacy implementation: base is not core22
```
The build then fails because legacy Snapcraft does not support building on core22.
After a quick poke around, it looks like `snapcraft.parts.yaml_utils.load` misspells `build-base` as `build_base`, causing the project to be misidentified as legacy. It's possible there are further problems, but fixing this is a necessary first step.

parts: correct spelling of build-base in yaml_utils.load

---

snapcraft/commands/account.py
snapcraft/commands/store/__init__.py
snapcraft/commands/store/_legacy_account.py
snapcraft/commands/store/client.py
tests/unit/commands/conftest.py
tests/unit/commands/store/test_client.py
tests/unit/commands/store/test_legacy_account.py
tests/unit/commands/test_account.py

This is the simplest implementation for backwards compatibility.
-----
CRAFT-1103
The new code here is LegacyUbuntuOne, the get_auth code path is brought back from legacy snapcraft (6.1) with the tests it had.

store: support login --with

---

snapcraft/commands/store/_legacy_account.py
tests/unit/commands/conftest.py
tests/unit/commands/store/test_client.py
tests/unit/commands/store/test_legacy_account.py

It uses craft-store's mechanisms to assemble the authorization header
while still referencing the original login credentials from previous
versions of Snapcraft. This is essentially full backwards compatibility.
-----

store: full support for legacy login

---

tests/spread/core22/package-repositories/task.yaml
tests/spread/core22/package-repositories/test-apt-key-fingerprint/snap/snapcraft.yaml
tests/spread/core22/package-repositories/test-apt-key-name/snap/snapcraft.yaml
tests/spread/core22/package-repositories/test-apt-keyserver/snap/snapcraft.yaml
tests/spread/core22/package-repositories/test-apt-ppa/snap/snapcraft.yaml

Ensure build packages are also installable using package repositories
specified in snapcraft.yaml, in both destructive mode and using a
build instance.
-----

spread: add build packages to package repository tests

---

snapcraft_legacy/_store.py
snapcraft_legacy/cli/legacy.py

Additional measures for proper exit handling on errors
-----

store: correct login for register-key

---

requirements-devel.txt
tests/unit/parts/test_lifecycle.py
tests/unit/test_projects.py

-----
Bump pylint to latest version, remove redundant `disable: too-many-lines`.
Part 2 of supporting architectures for `core22`. Full code change is proposed [here](https://github.com/snapcore/snapcraft/pull/3712).
This is no longer strictly required for architectures support since Claudio bumped the major version (2.13->2.14) last week.  I'm still pushing it, as it's a simple update.
(CRAFT-1164)

lint: bump pylint

---

snapcraft/meta/snap_yaml.py
snapcraft/utils.py
tests/unit/test_utils.py

-----
Move `process_version()` to `utils.py`, because other files will need to use this function in an upcoming PR.
Part 4 of supporting architectures for `core22`. Full code change is proposed [here](https://github.com/snapcore/snapcraft/pull/3712).
(CRAFT-1166)

utils: move process_version to utils.py

---

tests/spread/plugins/v1/colcon/run/task.yaml

Temporarily disable until test or code is fixed.
-----

spread: set colcon for 18.04 to manual

---

snapcraft/parts/lifecycle.py
snapcraft/projects.py
tests/unit/conftest.py
tests/unit/parts/test_lifecycle.py
tests/unit/test_projects.py

- moved it away from lifecycle
- added support to not install content snaps if a build-snap provides it
-----
CRAFT-1112

project: method to return snaps to install

---

tests/spread/plugins/v1/colcon/run/task.yaml
tests/spread/plugins/v1/colcon/snaps/colcon-talker-listener/src/listener_py/setup.cfg

-----
Due to a recent update on colcon-core: https://github.com/colcon/colcon-core/issues/518

fix(colcon-core18-test): use underscore instead of dash

---

snapcraft/parts/lifecycle.py
snapcraft/providers/_lxd.py
snapcraft/providers/_multipass.py
snapcraft/providers/_provider.py
tests/unit/parts/test_lifecycle.py
tests/unit/providers/test_lxd.py
tests/unit/providers/test_multipass.py
tests/unit/providers/test_provider.py

-----
New naming convention for instances.
Part 6 of supporting architectures for `core22`. Full code change is proposed [here](https://github.com/snapcore/snapcraft/pull/3712).
`snapcraft-<project_name>-<inode-number>`
`snapcraft-hello-world-10488157`
`snapcraft-<project_name>-on-<build_on>-for-<build_for>-<inode-number>`
`snapcraft-hello-world-on-amd64-for-arm64-10488157`
`charmcraft-<project_name>-<inode-number>-<bases_index>-<build_on_index>-<target_arch>`
`charmcraft-hello-world-20846552-2-1-amd64`
Where `bases_index` and `build_on_index` are the indices of each base and architecture defined in the charmcraft config.
For snapcraft, I chose to use the architectures names themselves, rather than indices.  It's more descriptive and is not affected by the re-ordering of architectures in …

providers: specify build-on and build-for in instance name

---

snapcraft/pack.py
snapcraft/parts/lifecycle.py
tests/unit/parts/test_lifecycle.py
tests/unit/test_pack.py

-----
Allow snapcraft to specify the output snap name from the project's name, version, and target architecture.  
This will be used when building snaps where the target architecture is different than the host architecture.
Part 5 of supporting architectures for `core22`. Full code change is proposed [here](https://github.com/snapcore/snapcraft/pull/3712).
(CRAFT-1171)

pack: specify snap filename

---

snapcraft/projects.py
tests/unit/conftest.py
tests/unit/test_projects.py

-----
Add support for defining architectures in snapcraft.yaml.
Part 1 of supporting architectures for core22.  Full code change is proposed [here](https://github.com/snapcore/snapcraft/pull/3712).
(CRAFT-1163)

architectures: add schema support

---

snapcraft/pack.py

pack: only print the basename of the snap filename

---

snapcraft/commands/status.py
tests/spread/general/store/task.yaml

Correctly parse the --track and --arch options which are sequences.
-----

cli: argparse append action for status command

---

requirements-devel.txt
requirements.txt
snapcraft/cli.py
snapcraft/commands/account.py
snapcraft/commands/lifecycle.py
snapcraft/commands/manage.py
snapcraft/commands/names.py
snapcraft/commands/store/client.py
snapcraft/extensions/extension.py
snapcraft/pack.py
snapcraft/parts/lifecycle.py
snapcraft/parts/parts.py
snapcraft/parts/project_check.py
snapcraft/parts/setup_assets.py
snapcraft/parts/update_metadata.py
snapcraft/providers/_logs.py
snapcraft/repo/apt_key_manager.py
snapcraft/repo/apt_ppa.py
snapcraft/repo/apt_sources_manager.py
snapcraft/utils.py
tests/unit/commands/test_account.py
tests/unit/commands/test_lifecycle.py
tests/unit/commands/test_manage.py
tests/unit/commands/test_names.py
tests/unit/extensions/test_extensions.py
tests/unit/parts/test_lifecycle.py
tests/unit/parts/test_parts.py
tests/unit/parts/test_project_check.py

Craft-cli 1.0.0 updates CLI verbosity levels to follow the UX standard
to be used across *craft tools. It makes output to stdout and stderr more
consistent and makes the verbose output less verbose by removing debug
messages and timestamps.
-----
CRAFT-1144

cli: update craft-cli to comply with UX guidelines

---

snapcraft/meta/manifest.py

I recently ran into a problem building a core22 based base snap that had been working fine last week:
https://github.com/canonical/ubuntu-core-desktop/runs/7294752999?check_suite_focus=true
```
Generating snap manifest...                                                    Traceback (most recent call last):
...
File "/snap/snapcraft/x1/lib/python3.8/site-packages/snapcraft/parts/lifecycle.py", line 308, in _generate_manifest
manifest.write(
File "/snap/snapcraft/x1/lib/python3.8/site-packages/snapcraft/meta/manifest.py", line 97, in write
manifest = Manifest(
File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Manifest
base
none is not an allowed value (type=type_error.none.not_allowed)
Failed to execute …
```

snapcraft/meta: make Manifest.base optional

---

snapcraft/elf/__init__.py
snapcraft/elf/_patcher.py
snapcraft/elf/errors.py
tests/unit/elf/test_patcher.py

Patch ELF files using patchelf. This is a port of the corresponding
class from Snapcraft 6.x.
Co-authored-by: Kyle Fazzari <kyrofa@ubuntu.com>
Co-authored-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-----
CRAFT-1191

elf: add elf file patcher

---

snapcraft/parts/parts.py

Importing craft_parts.packages.deb on non-deb systems fails. So this
import should only happen when in the container or VM.
Fixes https://bugs.launchpad.net/snapcraft/+bug/1981979
-----

parts: Do not import craft_parts.packages.deb until needed

---

snapcraft/commands/legacy.py
snapcraft_legacy/_store.py
snapcraft_legacy/storeapi/_dashboard_api.py
snapcraft_legacy/storeapi/errors.py
tests/legacy/unit/commands/test_create_key.py
tests/legacy/unit/store/test_errors.py

-----
Raise new `KeyAlreadyExists` error when `snapcraft create-key` attempts to create an existing key.
1. Add new error `KeyAlreadyExists`
2. Add unit tests for some other `storeapi` errors.  
- https://bugs.launchpad.net/snapcraft/+bug/1979907
(CRAFT-1161)

cli: add KeyAlreadyExists error

---

snapcraft/cli.py
snapcraft/errors.py
snapcraft/linters/__init__.py
snapcraft/linters/base.py
snapcraft/linters/linters.py
snapcraft/meta/snap_yaml.py
snapcraft/parts/lifecycle.py
snapcraft/projects.py
tests/unit/linters/conftest.py
tests/unit/linters/test_base.py
tests/unit/linters/test_linters.py
tests/unit/parts/test_lifecycle.py

Create a basic framework for linting including the `lint` entry in
snapcraft.yaml to disable specific linters. Linters run before
packing a snap.
A specific `lint` command to lint a snap package file will be added
in a future PR. JSON-formatted output is implemented but will only
be used with the `lint` command.
-----
CRAFT-1098

linters: add linting infrastructure

---

snapcraft/utils.py
tests/unit/test_utils.py

-----
I added `s390x` to snapcraft 7, to align with snapcraft_legacy.

meta: add support for s390x

---

requirements-devel.txt
requirements.txt
snapcraft/parts/plugins/_ros.py
snapcraft_legacy/internal/repo/_base.py
tests/legacy/unit/repo/test_base.py
tests/unit/parts/plugins/test_colcon.py

-----
When normalizing pkg-config (.pc) files from staged snaps, directories previously prepended to the prefix parameter will be removed:
- `/build/<snap-name>/stage` from snaps built via launchpad
- `/root/stage` from snaps built via a provider
LP: #[1916281](https://bugs.launchpad.net/snapcraft/+bug/1916281)
(CRAFT-1214)

repo: fix_pkg_config removes prefixes from staged snap's .pc files.

---

snapcraft/cli.py
snapcraft/parts/lifecycle.py
tests/spread/plugins/craft-parts/build-and-run-hello/task.yaml

Register application plugins as soon as possible, to allow plugins
to be available to all commands (not only lifecycle commands). This
fixes plugin-related issues when expanding the ros2-humble extension.
-----
CRAFT-1221

plugins: early registration of application plugins

---

snapcraft/elf/_patcher.py
snapcraft/elf/elf_utils.py
snapcraft/elf/errors.py
snapcraft/linters/classic_linter.py
snapcraft/linters/linters.py
spread.yaml
tests/spread/core22/linters/classic-libc/expected_linter_output.txt
tests/spread/core22/linters/classic-libc/snap/snapcraft.yaml
tests/spread/core22/linters/classic-libc/task.yaml
tests/spread/core22/linters/classic/expected_linter_output.txt
tests/spread/core22/linters/classic/snap/snapcraft.yaml
tests/spread/core22/linters/classic/task.yaml
tests/unit/elf/test_elf_file.py
tests/unit/elf/test_elf_utils.py
tests/unit/elf/test_patcher.py
tests/unit/linters/test_classic_linter.py
tests/unit/linters/test_linters.py

The classic linter warns if elf binary interpreter or rpath values
are not set to expected values for classic confinement or if libc
is staged. In this case, values from the base snap or `$ORIGIN`
should be used.
Note: this PR includes many adjustments to the existing elf
infrastructure used by the classic linter.
-----
CRAFT-1090

linters: add classic confinement linter

---

requirements-devel.txt
requirements.txt
snapcraft/parts/plugins/_ros.py
tests/spread/general/stage-packages/snaps/stage-packages-with-arch/snap/snapcraft.yaml
tests/spread/general/stage-packages/snaps/stage-packages/snap/snapcraft.yaml
tests/spread/general/stage-packages/task.yaml

Craft-parts 1.10.2 fixes local git source cloning with depth and stage
packages installation when building for a different architecture.
-----

requirements: update craft-parts to 1.10.2

---

extensions/desktop/common/desktop-exports

In a hybrid Intel + Nvidia setup, it is costumary to use Intel-Vaapi for
hardware acceleration instead of Nvidia-Vdpau (unless the user chooses
otherwise); this avoids unecessary power consumption.
Moreover, for software that don't work with Vdpau yet, the previous changes
would hard lock to Vdpau nonetheless (e.g. Chromium [LP: #1816497](https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1816497)), resulting
in no hardware acceleration where Vaapi is available.
```
snapcraft/projects.py:320: error: Unexpected keyword argument "extra" for "__init_subclass__" of "object"
snapcraft/projects.py:639: error: Unexpected keyword argument "extra" for "__init_subclass__" of "object"
Found 2 errors in 1 file (checked 153 source files)
make: *** [Makefile:29: test-mypy] Error 1
```
``` …
```

extensions: Do not default to Nvidia VDPAU

---

snapcraft/commands/account.py
tests/unit/commands/test_account.py

Take into consideration that the On Premises Snap Store does not return
an expires key.
-----
CRAFT-1241

whoami command: account for missing expires

---

snapcraft/extensions/gnome.py
tests/unit/extensions/test_gnome.py

The libdrm library expects to find the amdgpu.ids file at
/usr/share/libdrm. Although the file is already available in
Gnome-42-2204, it wasn't binded.
This patch fixes this.
-----

Add binding for amdgpu.ids

---

snapcraft/commands/names.py
snapcraft/store/client.py
tests/unit/commands/test_names.py
tests/unit/store/test_client.py

The names presentation logic is tied to SCA which is incompatible with
the PublisherGW
-----
CRAFT-1242

names command: move presentation logic to StoreClientCLI

---

snapcraft/utils.py
tests/unit/test_utils.py

-----
Similar to https://github.com/snapcore/snapcraft/pull/3850, but for `riscv64`.
I cross-checked with `craft-parts` and `snapcraft_legacy`, I believe this was the last missing architecture for core22 snaps.

meta: add support for riscv64

---

snapcraft/elf/_elf_file.py
snapcraft/linters/classic_linter.py
snapcraft/meta/snap_yaml.py
tests/unit/elf/test_patcher.py
tests/unit/meta/test_snap_yaml.py

Obtain the list of directories exposed by content providers listed
in snap.yaml (provided that the corresponding snaps are installed
on the system).
-----
CRAFT-1246

meta: get content provider dirs from snap metadata

---

snapcraft/meta/snap_yaml.py
tests/unit/meta/test_snap_yaml.py

Don't fail on type errors when detecting content plugs and slots,
allowing empty definitions. Snap metadata contents are validated at
a later point when packaging the snap file.
-----

meta: fix content plug detection

---

requirements-devel.txt
requirements.txt

Use craft-parts 1.12.1 with fixes to cmake plugin prefix path.
Note: this doesn't change the cmake plugin behavior and only fixes a
bug in the `CMAKE_PREFIX_PATH` variable value, so it's targeting
7.1.2 instead of main.
-----

requirements: update craft-parts to 1.12.1

---

requirements-devel.txt
requirements.txt
snapcraft/store/constants.py
snapcraft/store/onprem_client.py
tests/legacy/unit/commands/__init__.py
tests/unit/store/test_onprem_client.py

Derivation from craft-store's BaseClient to support the OnPrem store.
This implementation is specific enough to Snapcraft to be implemented
here.
This includes an update to the test mock in legacy pertaining to the
change of where JSONDecoder comes from now (requests).
-----
CRAFT-1243

store: on prem base client

---

extensions/desktop/command-chain/desktop-launch
extensions/desktop/command-chain/hooks-configure-fonts
extensions/desktop/command-chain/run

Using source it is possible to simplify the chain, reduce memory usage and make execution faster.
This MR emulates "exec $@" using "source", thus avoiding to create a new process and launching a new shell each time a shell script must be executed from another shell script.
-----
DT-504

extensions: replace execs with source

---

snapcraft/commands/lifecycle.py
tests/unit/cli/test_default_command.py
tests/unit/cli/test_lifecycle.py

-----
Parse the command line arguments `--http-proxy` and `--https-proxy`.
source: https://forum.snapcraft.io/t/error-unrecognized-arguments-http-proxy/30967
(CRAFT-1217)

cli: parse http-proxy and https-proxy

---

extensions/desktop/common/desktop-exports
extensions/desktop/gnome/launcher-specific

The printing support in Gtk is supported by several DLLs located
at /usr/lib/TRIPLET/gtk-X.0 (being X equal to 3 or 4).
Unfortunately, that wasn't configured in the layout for Gnome-42,
so some GTK programs (like gnome-text-editor) crashed when trying
to print something.
The first patch binded the modules folder into the root, but James commented that it could be fixed just with an environment variable.
This patch sets that variable for both GTK4 and GTK2, which were both missing (it was set only for GTK3).
It also sets the gweather environment variable, because it was sent only to snapcraft-desktop-integration.
-----

DT-500 Fix Cups for Gtk support in Gnome-42

---

snapcraft/commands/lifecycle.py
snapcraft/parts/lifecycle.py
snapcraft/projects.py
snapcraft/ua_manager.py
tests/unit/cli/test_default_command.py
tests/unit/cli/test_lifecycle.py
tests/unit/parts/test_lifecycle.py
tests/unit/test_projects.py
tests/unit/test_ua_manager.py

UA services can be specified in the project yaml file under the optional
`ua-services` key. These services will be enabled during the execution
of the parts lifecycle.
Note: this handles ua services for core22. Support for legacy snapcraft
will be added in a separate PR.
-----
CRAFT-1289

ua: specify and enable ua services

---

snapcraft/cli.py
tests/unit/cli/test_exit.py
tests/unit/cli/test_verbosity.py

Launchpad is no longer logging builds, we should allow for this by
checking if stdin is closed or not.
SNAPCRAFT_ENABLE_DEVELOPER_DEBUG is also analyzed for core22 projects
which is useful for Snapcraft's own spread tests.
-----

cli: add legacy envvar for login and check stdin

---

schema/snapcraft.json
snapcraft/ua_manager.py
snapcraft_legacy/cli/_options.py
snapcraft_legacy/cli/lifecycle.py
snapcraft_legacy/internal/repo/ua_manager.py
tests/legacy/unit/repo/test_ua_manager.py
tests/unit/test_ua_manager.py

Backport UA services support from core22 to legacy snapcraft. Services
are defined in the project yaml under the `ua-services` key. Parameter
`--enable-experimental-ua-services` is required if you define UA services.
**Note:** This is a baseline implementation that may require improvements
in service management, such as keeping track of services that are already
enabled to avoid re-enabling them. This will be done in future PRs.
Example output:
```
$ snapcraft --ua-token=$MYTOKEN --use-lxd --enable-experimental-ua-services
Launching a container.
Waiting for container to be ready
Waiting for network to be ready...
Attaching specified UA token...
Enabling default service esm-infra
Updating package lists
UA Infra: ESM enabled
Unable to determine current instance-id
This machine is now …
```

ua: enable ua services in legacy

---

snapcraft/cli.py
snapcraft/parts/lifecycle.py
tests/unit/cli/test_exit.py

Don't show the log file name when exiting on error in a managed host,
preventing confusing duplicate log filename reports.
-----
CRAFT-1285

cli: disable log filename report in managed hosts

---

requirements-devel.txt
requirements.txt

-----
Bump `craft-providers` to `1.4.1` to fix a bug in the truncation of long hostnames when creating an instance.

requirements: update craft-providers to 1.4.1

---

snapcraft/cli.py

Finish execution graciously if interrupted from the keyboard instead
of crashing with a backtrace.
-----

cli: graciously handle keyboard interrupt

---

pyproject.toml
snapcraft/parts/lifecycle.py
snapcraft/parts/parts.py
tests/unit/parts/test_lifecycle.py

Shell into the instance if `--debug` is used and a packing error happens
after the execution of the parts lifecycle.
-----
CRAFT-1286

parts: allow debug shell after the lifecycle

---

requirements-devel.txt
requirements.txt
setup.py
snap/hooks/configure
snap/snapcraft.yaml
snapcraft/snap_config.py
snapcraft/utils.py
tests/spread/general/snap-config/snap/snapcraft.yaml
tests/spread/general/snap-config/task.yaml
tests/unit/test_snap_config.py
tests/unit/test_utils.py

-----
Allows Snapcraft to parse data set via `snap set snapcraft <key>=<value>`.  Follows same paradigm as charmcraft.
(CRAFT-1321)

config: add snap config model

---

snapcraft/parts/lifecycle.py
snapcraft/providers/__init__.py
snapcraft/providers/_get_provider.py
tests/unit/providers/test_get_provider.py

-----
The default provider can be set via `snapd`'s config.
It can be set with `snap set snapcraft provider=<provider>` where valid providers are 'lxd' and 'multipass'.
To unset, run `snap unset snapcraft provider`.
This PR depends on https://github.com/snapcore/snapcraft/pull/3898, so the tests will fail until that PR is merged.
(CRAFT-1322)

providers: choose default provider from snap config for core 22

---

requirements-devel.txt
snapcraft_legacy/cli/_options.py
snapcraft_legacy/internal/common.py
tests/legacy/unit/cli/test_options.py

-----
The default provider for `snapcraft_legacy` can be set via snapd's config.
It can be set with `snap set snapcraft provider=<provider>` where valid providers are 'lxd' and 'multipass'.
To unset, run `snap unset snapcraft provider`.
The legacy implementation is much smaller than what is implemented for core22 in https://github.com/snapcore/snapcraft/pull/3899.
This is because the code for core22 validates the snap config during snapcraft's configure hook.  The legacy implementation doesn't need to re-validate the data.  It can just assume the config's data is valid.
(CRAFT-1323)

providers: choose legacy default provider from snap config

---

snapcraft/parts/lifecycle.py
snapcraft/providers/_lxd.py
snapcraft/providers/_multipass.py
snapcraft/providers/_provider.py
tests/unit/parts/test_lifecycle.py
tests/unit/providers/test_lxd.py
tests/unit/providers/test_multipass.py
tests/unit/providers/test_provider.py

-----
Follow up to https://github.com/snapcore/snapcraft/pull/3884.  This PR allows proxies to be used in core22 by passing `http_proxy` and `https_proxy` to `craft-providers` as environmental variables.
`craft-providers` sets the snapd proxy in [this PR](https://github.com/canonical/craft-providers/pull/149).
I tested this manually.  I used working http and https proxies from [this site](https://www.freeproxylists.net/) and checked they were set in the instance.  Then I chose an invalid proxy and received a network error inside the instance when snapcraft attempted to download and install a snap.
(CRAFT-1334)

providers: pass http-proxy and https-proxy to craft-providers

---

snapcraft/parts/lifecycle.py

Refactor to capture logs in finally block instead of calling the function twice.
-----

parts: minor refactoring in instance log capture

---

tests/unit/parts/test_lifecycle.py

Also parametrize the expected result instead of computing it at test run time.
-----

tests: minor refactoring in shell/shell-after tests

---

snapcraft/errors.py
snapcraft/store/client.py
tests/unit/store/test_client.py

When the store returns a 401, Snapcraft tries to do the right thing to prompt for a new login, but the error messages where confusing for the cases it cannot, when this original code was added the concept of a legacy client was not in place.
A logout is done to enforce using the new client if the credentials are the configparser based ones.
LP: #1980533
-----
CRAFT-1181

store: improve error message for 401 error

---

snapcraft/commands/discovery.py

No functional change.
Signed-off-by: Robert P. J. Day <robert.day@canonical.com>
-----

discovery.py: correct comment, "extensions" should say "plugins"

---

snapcraft_legacy/internal/repo/_deb.py
tests/legacy/unit/repo/test_deb.py

Collect installed package versions after the installation.
This allows us to collect the real version whilst avoiding a bug in apt where it would downgrade or remove a package in cases where the pinned version cannot be satisfied.
This is a backport of the corresponding change in craft-parts.
Co-authored-by: Sergio Schvezov <sergio.schvezov@canonical.com>
-----
CRAFT-1328

legacy: install unpinned build packages

---

snapcraft/cli.py
snapcraft/commands/__init__.py
snapcraft/commands/legacy.py
snapcraft/commands/remote.py
snapcraft/utils.py
snapcraft_legacy/cli/remote.py
tests/legacy/unit/commands/test_remote.py
tests/unit/commands/test_remote_build.py

- move the CLI logic out of legacy
- export --build-for and hide --build-on
- stop the emitter when calling confirm_with_user's prompt
-----
CRAFT-1384

cli: move remote build out of legacy

---

schema/snapcraft.json

core22 is currently using the legacy implementation of remote-build and needs to allow gnome in order to work.
The legacy code is safe, it will gracefully fail if used with the gnome extension at loading time
LP: #1986962
-----
CRAFT-1385

schema: allow the gnome extension

---

snapcraft/store/_legacy_account.py
snapcraft/store/client.py
tests/unit/store/test_legacy_account.py

There was a chance of not being able to logout when using legacy credentials as they got loaded into the environment regardless of what their origin was.
LP: #1980534
-----
CRAFT-1297

store: correctly logout when credentials are invalid for legacy

---

snapcraft/providers/_lxd.py
snapcraft/providers/_multipass.py
snapcraft/providers/_provider.py
snapcraft/providers/providers.py
tests/unit/providers/test_provider.py
tests/unit/providers/test_providers.py

-----
`get_instance_name()` is a snapcraft-specific call, so it is moved out of the craft-providers interface.  See [this PR](https://github.com/canonical/rockcraft/pull/74) in rockcraft for reference.
This is the first out of a series of PRs to prepare for the new `craft-providers` API.  The goals are simple:
1. `_provider.py`, `_lxd.py`, and `_multipass.py` contain no snapcraft-specific code
2. All snapcraft-specific code related to `craft-providers` is moved into `snapcraft/providers/providers.py`
This preparation is complete in `rockcraft`.  The new interface will be migrated from `rockcraft` to `craft-providers` in the coming week.
(CRAFT-1305)

providers: move `get_instance_name()` to providers.py

---

snapcraft/providers/_lxd.py
snapcraft/providers/_multipass.py
snapcraft/providers/_provider.py
snapcraft/providers/providers.py
tests/unit/providers/test_lxd.py
tests/unit/providers/test_multipass.py
tests/unit/providers/test_provider.py
tests/unit/providers/test_providers.py

-----
`get_command_environment()` is a snapcraft-specific call, so it is moved out of the craft-providers interface.
Similar to https://github.com/canonical/rockcraft/pull/75
(CRAFT-1352)

providers: move `get_command_environment()` to providers.py

---

snapcraft/parts/lifecycle.py
tests/unit/conftest.py
tests/unit/parts/test_lifecycle.py

-----
Mock and test calls made to `craft-providers` from `lifecycle.py`.  This code was not being tested.
I also simplified the `verbosity` call to match [charmcraft](https://github.com/canonical/charmcraft/blob/b22fcdba3b894004468abfbf45caa54d93fbf7d0/charmcraft/commands/build.py#L321) and [rockcraft](https://github.com/canonical/rockcraft/blob/5d7ed67646a10e5b35319c12d664df7b1e1a14b9/rockcraft/lifecycle.py#L197).
3 weeks ago, I [added some unit tests](https://github.com/snapcore/snapcraft/pull/3906) for `run_in_provider()`.  Today, I am extending those tests further.
The test fixtures are copies of the implementations in [charmcraft](https://github.com/canonical/charmcraft/blob/b22fcdba3b894004468abfbf45caa54d93fbf7d0/tests/conftest.py#L133) and …

tests: mock and test provider calls from lifecycle.py

---

requirements-devel.txt
requirements.txt
snapcraft/parts/lifecycle.py
snapcraft/providers/_lxd.py
snapcraft/providers/_multipass.py
snapcraft/providers/_provider.py
tests/unit/conftest.py
tests/unit/parts/test_lifecycle.py
tests/unit/providers/test_lxd.py
tests/unit/providers/test_multipass.py

-----
Moves the snapcraft-specific calls for mounting directories to `parts/lifecycle.py`.
Similar to https://github.com/canonical/rockcraft/pull/82
(CRAFT-1397)

providers: move mount logic to lifecycle.py

---

snapcraft/parts/lifecycle.py
snapcraft/providers/_lxd.py
snapcraft/providers/_multipass.py
snapcraft/providers/_provider.py
tests/unit/conftest.py
tests/unit/parts/test_lifecycle.py
tests/unit/providers/test_provider.py

-----
Two changes to the `craft-providers()` interface:
1. Move the snapcraft-specific call `get_instance_name()` out of `clean_project_environments()`
2. Rename `is_provider_available()` to `is_provider_installed()`
These changes match what was done for [rockcraft](https://github.com/canonical/rockcraft/blob/5d7ed67646a10e5b35319c12d664df7b1e1a14b9/rockcraft/providers/_provider.py#L33).
(CRAFT-1396)

providers: refactor clean_project_environments

---

snapcraft/parts/lifecycle.py
snapcraft/providers/_buildd.py
snapcraft/providers/_lxd.py
snapcraft/providers/_multipass.py
snapcraft/providers/_provider.py
snapcraft/providers/providers.py
tests/unit/conftest.py
tests/unit/parts/test_lifecycle.py
tests/unit/providers/test_lxd.py
tests/unit/providers/test_multipass.py

snapcraft-specific code in `launched_environment()` is removed from the craft-providers interface.
-----
Removes snapcraft-specific logic from `launched_environment()`.  This function is now matches the implementation in rockcraft ([lxd](https://github.com/canonical/rockcraft/blob/97306bc3d93c8a41f18432b1dadf4569c7f28854/rockcraft/providers/_lxd.py#L99) and [multipass](https://github.com/canonical/rockcraft/blob/97306bc3d93c8a41f18432b1dadf4569c7f28854/rockcraft/providers/_multipass.py#L89))
This is the most complex PR of the series, due to the translation of bases.  The base translation was added in [this PR](https://github.com/canonical/rockcraft/pull/85) to rockcraft.
*craft applications have a concept of a "base". This base is translated a `craft-providers` base and is passed to …

providers: refactor `launched_environment()`

---

snapcraft/providers/_buildd.py
snapcraft/providers/providers.py
tests/unit/providers/test_providers.py

-----
Install snaps and packages via `craft-providers`.
(CRAFT-1281, CRAFT-1283)

providers: install snaps and packages via craft-providers API

---

snapcraft/commands/manage.py

Run `snapcraft release --help`. Note that name, snap-name and snap_name are meaning to refer to the same thing.
It already errors out with
```
./tests/spread/plugins/v1/godeps/snaps/godeps-with-go-packages/snap/snapcraft.yaml:5: unsing ==> using
./tests/legacy/unit/conftest.py:85: Simualte ==> Simulate
./tests/legacy/unit/test_mountinfo.py:40: ro ==> to, row, rob, rod, roe, rot
./tests/legacy/unit/test_mountinfo.py:40: ro ==> to, row, rob, rod, roe, rot
./tests/legacy/unit/test_mountinfo.py:41: ro ==> to, row, rob, rod, roe, rot
./tests/legacy/unit/test_mountinfo.py:64: ro ==> to, row, rob, rod, roe, rot
./tests/legacy/unit/test_mountinfo.py:64: ro ==> to, row, rob, rod, roe, rot
./tests/legacy/unit/test_mountinfo.py:65: ro ==> to, row, rob, rod, roe, rot …
```

commands: make help message consistent

---

snapcraft/parts/lifecycle.py
snapcraft/providers/_lxd.py
snapcraft/providers/_multipass.py
snapcraft/providers/providers.py
tests/unit/parts/test_lifecycle.py
tests/unit/providers/test_lxd.py
tests/unit/providers/test_multipass.py
tests/unit/providers/test_providers.py

-----
`confirm_with_user()` is a snapcraft-specific call, so it is moved out of the craft-providers interface.
Similar to [this rockcraft PR](https://github.com/canonical/rockcraft/pull/91)
(CRAFT-1400)

providers: move `confirm_with_user()` call to providers.py (#91)

---

snapcraft/linters/base.py
snapcraft/linters/linters.py
snapcraft/projects.py
tests/spread/core22/linters/classic-libc/snap/snapcraft.yaml
tests/spread/core22/linters/classic/snap/snapcraft.yaml
tests/unit/linters/test_base.py
tests/unit/linters/test_classic_linter.py
tests/unit/linters/test_library_linter.py
tests/unit/linters/test_linters.py

This commit restructures the lint.ignore project section to allow ignoring files on a per-linter basis. This still lets the user disable all issues for a given linter, but allows for finer-grained control.
This is the current scheme (before this PR):
```yaml
lint:
ignore:
linters:
- library
- classic
files:
- "elf.*"
- lib/libfoo.so.1
```
The two entries (`linters` and `files`) are unrelated and complementary: If `linters` has e.g. `library`, then all `library` linting is ignored, regardless of `files`. If `files` has e.g. "elf.*", then any linting issue found matching that glob will be ignored, regardless of `linters`.
This is the new scheme implemented in this PR:
```yaml
lint:
ignore:
library:
- lib/libfoo.so.1     # Disable "library" linter only for lib/libfoo.so.1
classic: …
```

linters: allow ignoring files per-linter

---

tests/spread/electron-builder/no-template/expected_snap.yaml
tests/spread/electron-builder/no-template/expected_snapcraft.yaml

-----
I'm not sure if this is a "fix" or a "hack", nor why it started failing, but [this spread test](https://github.com/snapcore/snapcraft/tree/main/tests/spread/electron-builder/no-template) is failing with the error:
```
+ diff -U10 /snap/electron-builder-hello-world/x1/meta/snap.yaml /snapcraft/tests/spread/electron-builder/no-template/expected_snap.yaml
--- /snap/electron-builder-hello-world/x1/meta/snap.yaml	2022-10-07 18:27:23.000000000 +0000
+++ /snapcraft/tests/spread/electron-builder/no-template/expected_snap.yaml	2021-04-29 15:11:51.000000000 +0000
@@ -14,20 +14,21 @@
- unity7
- browser-support
- network
- gsettings
- audio-playback
- pulseaudio
- opengl
- raw-usb
environment:
DISABLE_WAYLAND: '1'
+      TMPDIR: …
```

tests: fix electron spread test

---

snapcraft/providers.py
tests/unit/test_providers.py

-----
Captured logs were not being saved to the log file because they were emitted as trace-level messages instead of debug-level.
Previously, they were debug level ([see here](https://github.com/snapcore/snapcraft/blob/f6abc2efd7c665a2df9577499bb022491d36cfc9/snapcraft/providers/_logs.py#L50)).
[Reported](https://forum.snapcraft.io/t/call-for-testing-snapcraft-7-2-0/32171/2?u=mr_cal) by @diddledani

providers: capture logs with debug-level logging

---

tests/legacy/unit/sources/test_git.py

-----
git v2.34.1 requires the config `protocol.file.allow=always` when adding a local submodule

tests: allow local git submodules

---

snapcraft/commands/account.py
snapcraft/store/onprem_client.py
tests/unit/commands/test_account.py
tests/unit/store/test_onprem_client.py

onprem store: support new credentials format

---

snapcraft/meta/snap_yaml.py
tests/unit/meta/test_snap_yaml.py

Add missing slots definition in snap.yaml apps.
-----

meta: fix snap.yaml app slots

---

snapcraft/ua_manager.py
tests/unit/test_ua_manager.py

-----
If a UA service is already enabled, do not attempt to re-enable the service because UA will raise and error.
source: https://bugs.launchpad.net/bugs/1989500
(CRAFT-1450)

ua: do not re-enable enabled services

---

snapcraft_legacy/internal/repo/ua_manager.py
tests/legacy/unit/repo/test_ua_manager.py

-----
Same as https://github.com/snapcore/snapcraft/pull/3960, but for `snapcraft_legacy`.
If a UA service is already enabled, do not attempt to re-enable the service because UA will raise and error.
source: https://bugs.launchpad.net/bugs/1989500
(CRAFT-1451)

ua: do not re-enable enabled services for snapcraft_legacy

---

requirements-devel.txt
requirements.txt

-----
Resolves [an error](https://forum.snapcraft.io/t/call-for-testing-snapcraft-7-2-0/32171/10) when Multipass attempts to write to a directory outside of the user's home directory.
Blocked by https://github.com/canonical/craft-providers/pull/168, which is required before releasing `craft-providers 1.6.1`.

requirements: update craft-providers to v1.6.1

---

snapcraft_legacy/internal/build_providers/_base_provider.py
tests/legacy/unit/build_providers/lxd/test_lxd.py
tests/legacy/unit/build_providers/test_base_provider.py

-----
A spread test on core18 started [consistently failing](https://github.com/snapcore/snapcraft/actions/runs/3329677836/jobs/5510607616) today.
The error is:
```
+ sudo -iu ubuntu env -i PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin bash -c 'cd /snapcraft/tests/spread/plugins/v2/snaps/make-hello && snapcraft try --use-lxd'
Launching a container.
Waiting for container to be ready
Waiting for network to be ready...
error: cannot communicate with server: Put http://localhost/v2/snaps/system/conf: dial unix /run/snapd.socket: connect: no such file or directory
Starting Snapcraft 7.2.1.post6+git822e6686
Logging execution to '/home/ubuntu/.cache/snapcraft/log/snapcraft-20221026-173239.952534.log'
An error occurred when trying to execute 'snap unset system …
```

Setup snapd for snapcraft_legacy providers

---

tests/spread/providers/multipass-basic/task.yaml
tests/spread/providers/multipass-error-handling/task.yaml

-----
Move manual multipass tests out of the legacy directory.  
It's not a very meaningful PR, since they are manual tests that don't work on the google spread infrastructure, but this PR is still a tiny improvement.

Spread multipass tests

---

snapcraft/meta/snap_yaml.py
snapcraft/projects.py
tests/unit/meta/test_snap_yaml.py
tests/unit/test_projects.py

-----
The `provenance` key in snapcraft.yaml can now be moved from underneath `passthrough` to a top-level key.
(CRAFT-1423)

meta: support top-level `provenance` keyword for on-prem support

---

snapcraft/snap_config.py
snapcraft_legacy/internal/common.py
tests/legacy/unit/test_common.py
tests/unit/test_snap_config.py

-----
Follow up to https://github.com/snapcore/snapcraft/pull/3971 to catch another error reported [here](https://forum.snapcraft.io/t/call-for-testing-snapcraft-7-2-0/32171/27).

snap config: catch more errors when config cannot be retrieved

---

snapcraft/cli.py
snapcraft/utils.py
tests/unit/cli/test_verbosity.py
tests/unit/test_utils.py

-----
The default verbosity level can be set with the environment variable `SNAPCRAFT_VERBOSITY_LEVEL`, where valid values are `quiet`, `brief`, `verbose`, `debug`, and `trace`.
The implementation I chose for this PR isn't correct.  Running `SNAPCRAFT_VERBOSITY_LEVEL=trace snapcraft pull --verbosity=quiet` produces the output
```
2022-10-24 15:36:28.919 Starting Snapcraft 7.1.1.post1+git6934c0ba
2022-10-24 15:36:28.919 Logging execution to '/home/developer/.cache/snapcraft/log/snapcraft-20221024-153628.919185.log'
```
Running `SNAPCRAFT_VERBOSITY_LEVEL=trace snapcraft pull --verbosity=trace` outputs the greeting message twice:
```
2022-10-24 15:36:44.269 Starting Snapcraft 7.1.1.post1+git6934c0ba
2022-10-24 15:36:44.269 Logging execution to …
```

cli: set default verbosity level with environment variable

---

snapcraft_legacy/internal/repo/apt_cache.py
snapcraft_legacy/internal/repo/errors.py
tests/legacy/unit/repo/test_apt_cache.py
tests/legacy/unit/repo/test_errors.py

-----
If the contents of `/etc/apt` cannot be copied to the cache directory, snapcraft will now produce a helpful error.
This can occur on a system where Ubuntu Pro is enabled, snapcraft is run in destructive mode, and snapcraft is not being run with sudo nor as root.
(CRAFT-1421)

repo: raise error when populating the apt cache directory fails

---

.github/workflows/spread.yml
.gitmodules
spread.yaml

-----
Use the `retry` function from [snapd-testing-tools](https://github.com/snapcore/snapd-testing-tools) when installing the lxd snap.
This is to workaround an intermittent and hard-to-reproduce [snapd bug](https://bugs.launchpad.net/snapd/+bug/1870201).

tests: retry installing lxd snap

---

HACKING.md
snapcraft/commands/legacy.py
tools/environment-setup-local.sh

-----
fxes: https://bugs.launchpad.net/snapcraft/+bug/1995857
The legacy upload-metadata command didn't have a location argument for the snap file itself. This PR adds that argument, and fixes some issues with the hacking doc and environment setup.
```shell
$snapcraft upload-metadata signal-desktop_5.57.0_amd64-core18.snap
Usage: snapcraft [options] command [args]...
Try 'snapcraft upload-metadata -h' for help.
Error: unrecognized arguments: signal-desktop_5.57.0_amd64-core18.snap
```

cli: accept snap file in legacy upload-metadata command

---

requirements-devel.txt
requirements.txt
snapcraft/elf/_patcher.py
snapcraft/elf/errors.py
snapcraft/linters/classic_linter.py
snapcraft/linters/library_linter.py
snapcraft/parts/lifecycle.py
spread.yaml
tests/spread/core22/patchelf/classic-patchelf/Makefile
tests/spread/core22/patchelf/classic-patchelf/hello-classic.c
tests/spread/core22/patchelf/classic-patchelf/snap/snapcraft.yaml
tests/spread/core22/patchelf/classic-patchelf/task.yaml
tests/spread/core22/patchelf/strict-patchelf/Makefile
tests/spread/core22/patchelf/strict-patchelf/hello-strict.c
tests/spread/core22/patchelf/strict-patchelf/snap/snapcraft.yaml
tests/spread/core22/patchelf/strict-patchelf/task.yaml
tests/unit/parts/test_lifecycle.py

If `enable-patchelf` is listed in the part's build attributes, patch the part's ELF binaries to use the interpreter and libraries from the base snap (or use bundled components if libc is staged).
-----
CRAFT-1460

elf: patch elf files for classic mode

---

snapcraft/linters/library_linter.py

When creating library linker warnings, don't consider the dynamic linker when checking for missing libraries.
-----

linters: don't list dynamic linker as missing library

---

snapcraft/extensions/ros2_humble.py
snapcraft_legacy/internal/project_loader/_extensions/ros1_noetic.py
snapcraft_legacy/internal/project_loader/_extensions/ros2_foxy.py
tests/spread/plugins/v2/catkin-ros1-catkin-packages-ignore/task.yaml
tests/spread/plugins/v2/catkin-ros1-run/task.yaml
tests/spread/plugins/v2/colcon-ros2-daemon/task.yaml
tests/spread/plugins/v2/colcon-ros2-hello/task.yaml
tests/spread/plugins/v2/colcon-ros2-stage-snap/task.yaml
tests/spread/plugins/v2/ros-plugins-error-code/task.yaml
tests/spread/plugins/v2/ros1-cmake-args/task.yaml
tests/spread/plugins/v2/ros1-hello/task.yaml
tests/spread/plugins/v2/ros1-in-source-hello/task.yaml
tests/spread/plugins/v2/ros1-specific-packages/task.yaml

If applied, this commit will allow users to build ros snaps without using the SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS flag.
This would help our ROS snap workshops run smoother and avoid the user's feeling that ROS is not currently at in a stable stage.
-----

extensions, ros: remove experimental flag

---

requirements-devel.txt
requirements.txt

This enables git+ssh:// scheme in in git sources.
-----

dependencies: update craft-parts to 1.15.2

---

.github/workflows/publish.yaml
.github/workflows/spread.yml

This has the docker fix which is yet to be released.
-----

ci: move to latest snapcore/action-build

---

snapcraft/providers.py
tests/unit/test_providers.py

-----
Report from https://bugs.launchpad.net/snapcraft/+bug/1997874
`SNAPCRAFT_MAX_PARALLEL_BUILD_COUNT` was not being passed into the build environment.
Inside the build environment, the [default build count](https://github.com/snapcore/snapcraft/blob/0f49a754d515ffd26cd95404c0891c2dbf1de2a7/snapcraft/utils.py#L205) would be used, since the user's environment variable did not exist.

providers: pass SNAPCRAFT_MAX_PARALLEL_BUILD_COUNT to instance

---

snapcraft/parts/plugins/kernel.py
tests/unit/parts/plugins/test_kernel.py

Fixes failure to copy due to non-existent source file. Source file no longer exists upstream, and intended target already exists. See https://github.com/snapcore/core-initrd/tree/main/modules
-----

kernel plugin: do not copy extra-modules.conf

---

snapcraft/parts/plugins/kernel.py
snapcraft_legacy/plugins/v2/kernel.py
tests/legacy/unit/plugins/v2/test_kernel.py
tests/unit/parts/plugins/test_kernel.py

Multiple 
- fixing a regression introduced by #3973. Please do not remove features if not sure about their functionality
- fix crash if there are no defined kernel modules to be included in initramfs
- improve documentation of multiple options by clarifying default values
- fix warning and occasional error reported when linking initramfs overlays with wild cards
- updated unit tests for the above changes

Kernel plugin: multiple fixes

---

requirements-devel.txt
requirements.txt

-----
This disables [automatic snap refreshes](https://github.com/canonical/craft-providers/pull/182) inside of instances.
Source: https://bugs.launchpad.net/snapcraft/+bug/1998100
(CRAFT-1521)

dependencies: update craft-providers to 1.6.2

---

snapcraft/providers.py
tests/unit/test_providers.py

-----
Cleanup the `.bashrc` file injected into instances. The file is now compliant with shellcheck and checks if the `environment.sh` files exist.
(CRAFT-1454)

providers: update .bashrc to be shellcheck compliant

---

tests/spread/plugins/v1/ruby/snaps/ruby-bundle-install/snap/snapcraft.yaml

-----
Ruby's `bundler v3.4.0` [dropped support](https://github.com/rubygems/rubygems/releases/tag/v3.4.0) for Ruby < `v2.6`, which broke one of our spread tests for the core18 / v1 Ruby plugin.

tests: update ruby bundle v1 spread test

---

tests/unit/elf/test_patcher.py

Discovered this accidentally thanks to a `~/.bashrc` that put `/bin` before `/usr/bin` in `$PATH`.
I'm not entirely sure this was unintentional, so unless someone else knows we should probably wait for @sergiusens.

Tests: Make test_patcher not require a real patchelf in /usr/bin

---

requirements-devel.txt
setup.cfg
setup.py

Ruff is currently iterating quickly and adding many tests in each new version. This change will move ruff breakages into the renovate update PRs rather than random PRs.
-----

Freeze ruff version

---

requirements-devel.txt
requirements.txt
snapcraft/parts/lifecycle.py
snapcraft/parts/parts.py
tests/unit/parts/test_parts.py

Use craft-parts' optional stage package tracking only when manifest is enabled. This allows Snapcraft to run on instances based on tmpfs, for faster builds and snap development cycles.
This release also adds plugins for SCons, Ant, and Maven, and fixes directory cleaning. See the Craft-parts project changelog for a complete list of changes.
-----

requirements: update to craft-parts 1.18.0

---

snapcraft/providers.py
tests/unit/test_providers.py

-----
1. Allow `.bashrc` to be pushed into Multipass instances.  This is now possible due to [this `craft-providers` PR](https://github.com/canonical/craft-providers/pull/193) being merged.
2. Stop writing `.bashrc` to a temporary file on the host.  Instead, use `craft-providers` method `push_file_io`.
(CRAFT-1545)

providers: push .bashrc to Multipass instances

---

Makefile
pyproject.toml
setup.cfg

-----
Some minor fixes to the snapcraft linters that fail in a developer environment but not on CI (due to the dev environment having directories like `./build/`, `./venv/`, and submodules.
1. mypy - ignore `venv`
2. isort - ignore `snapd-testing-tools` and files in `.gitignore`
3. shellcheck - ignore `snapd-testing-tools` and `.ruff-cache`
4. Rename `spellcheck` to `spread-shellcheck`

lint: ignore snapd-testing-tools, venv

---

snapcraft_legacy/cli/_options.py
snapcraft_legacy/cli/_runner.py
tests/legacy/unit/commands/test_verbosity.py
tests/spread/general/verbosity/task.yaml

-----
This PR allows `--verbose` and `-v` to be used when building core18|20 snaps.
Support for other verbosity options (`-q`, `--quiet`, `--verbosity=<verbosity level>`) can be added in the same manner.
(CRAFT-1292)

cli: pass `--verbose` and `-v` to snapcraft_legacy

---

snapcraft_legacy/cli/_options.py

-----
Small documentation improvement to follow up on https://github.com/snapcore/snapcraft/pull/4024

cli: improve docstring for get_build_provider_flags

---

setup.py
snapcraft/elf/_elf_file.py

-----
[`setuptools>=66`](https://setuptools.pypa.io/en/stable/history.html#v66-0-0) enforces versioning requirements from [PEP 440](https://peps.python.org/pep-0440/), which causes some of the unit tests to fail.
Added comments and a TODO so it can be resolved in the future.

requirements: pin setuptools<66

---

requirements-devel.txt
requirements.txt

-----
craft-providers 1.7.2 checks the id map for LXD instances for core22 snaps. 
Previously, when the same instance was launched by different users, it had the potential to raise errors. The most common error was the git error "dubious ownership detected in repository".

requirements: update craft-providers to 1.7.2

---

requirements-devel.txt
requirements.txt

Craft-parts 1.15.3 fixes ignored file patterns when processing local sources.
-----

requirements: update craft-parts to 1.15.3

---

requirements-devel.txt
requirements.txt

Craft-parts 1.18.1 fixes ignored file patterns when processing local sources.
-----

requirements: update craft-parts to 1.18.1

---

setup.cfg
tests/spread/plugins/v1/gradle/snaps/gradlew-hello/gradlew

-----
:heavy_check_mark: shellcheck linter execution time reduced from 20 seconds to 3 seconds
:heavy_check_mark: Ignore files in `.gitignore`
:heavy_check_mark: Ignore submodules (i.e. `test/spread/tools/snapd-testing-tools`)

lint: use `git ls-files` for shellcheck

---

snapcraft/utils.py

-----
No functional changes.
Minor logging improvement to log the environment variable `SNAPCRAFT_MAX_PARALLEL_BUILD_COUNT` when it is invalid.

utils: log envvar SNAPCRAFT_MAX_PARALLEL_BUILD_COUNT when invalid

---

.github/workflows/publish.yaml
.github/workflows/spread.yml

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12
-----

ci: update deprecated node12-based actions

---

.github/workflows/publish.yaml
.github/workflows/spread.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
-----

ci: remove deleted set-output GH Action command

---

snapcraft_legacy/internal/repo/_deb.py
tests/legacy/unit/repo/test_deb.py

Legacy _deb: Add option to specify packages to unmark

---

tests/spread/general/hooks/generated-and-project-hooks/snap/snapcraft.yaml
tests/spread/general/hooks/generated-and-project-hooks/src/Makefile
tests/spread/general/hooks/generated-and-project-hooks/src/go.mod
tests/spread/general/hooks/generated-hooks/snap/snapcraft.yaml
tests/spread/general/hooks/generated-hooks/src/Makefile
tests/spread/general/hooks/generated-hooks/src/go.mod
tests/spread/general/hooks/generated-then-project-hooks/snap/snapcraft.yaml
tests/spread/general/hooks/generated-then-project-hooks/src/Makefile
tests/spread/general/hooks/generated-then-project-hooks/src/go.mod

-----
Some unused go dependencies triggered `dependabot` in:
- https://github.com/snapcore/snapcraft/pull/4049
- https://github.com/snapcore/snapcraft/pull/4050
- https://github.com/snapcore/snapcraft/pull/4051
I removed the deps and bumped the go version.  These tests aren't meant to exercise the Go plugin, they are testing hooks (which happen to be written in Go) generated during the build step.

tests: remove unused go dependencies in generated hook spread tests

---

spread.yaml
tests/spread/tools/snapcraft-yaml.sh

spread: core24 testing infra

---

extensions/desktop/kde-neon/Makefile
snapcraft/extensions/kde_neon.py
tests/spread/extensions/kde-neon/task.yaml
tests/spread/extensions/snaps/neon-hello/snap/snapcraft.yaml
tests/unit/extensions/test_kde_neon.py

- moved back to the full blown command-chain for KDE Neon
- removed dependency on bindtextdomain
- updated the pattern match for kde sdk snaps
- tests updated to consider core22
- fixed the added part names
-----

extensions: fix neon-extension issues for core22

---

snapcraft/commands/upload.py

- [] Have you successfully run `pytest tests/unit`?
Failing:
```
FAILED tests/unit/extensions/test_extensions.py::test_get_extensions_data_dir - AssertionError: assert False
```
-----
Just a small fix on a wrong help message possibly driven by a bad copy&paste.

cli: fix help message for the "upload" command

---

.gitignore
pyproject.toml

-----
1. Replace `exclude` with `extend-exclude` for `black`:
From [black docs](https://black.readthedocs.io/en/stable/usage_and_configuration/file_collection_and_discovery.html#gitignore):
> .gitignore
>
> If --exclude is not set, Black will automatically ignore files and directories in .gitignore file(s), if present.
>
> If you want Black to continue using .gitignore while also configuring the exclusion rules, please use --extend-exclude.
2. Only ignore `prime/` and `stage/` in the root of the project.  This is already done for `parts/`.  All 3 directories come from building snapcraft in destructive mode)

lint: ignore files in .gitignore for black

---

snapcraft/commands/account.py
snapcraft/commands/legacy.py
snapcraft/commands/manage.py
snapcraft/commands/upload.py
snapcraft/store/client.py
snapcraft_legacy/storeapi/errors.py

Some innocuous grammar fixes, including (among other things):
- "login" and "logout" are nouns, "log in" and "log out" are verbs
- hyphenate "comma-separated" to be consistent with rest of code
-----

grammar fixes: a number of grammar-type cleanups, no functional mods

---

snapcraft/elf/_elf_file.py
snapcraft/elf/elf_utils.py
snapcraft/store/_legacy_account.py

-----
Update from [`pyright 1.1.299`](https://github.com/microsoft/pyright/releases/tag/1.1.299):
> Fixed a recent regression that resulted in multi-part imports being evaluated as unknown if a namespace package was used for an intermediate part of the module path and useLibraryCodeForTypes was set to false.
In other words, pyright now complains if you do this:
```python
import xdg.BaseDirectory
CONFIG_PATH = Path(xdg.BaseDirectory.xdg_config_home) / "snapcraft/snapcraft.cfg"
```

lint: fix multi-part imports

---

tests/unit/parts/test_lifecycle.py

-----
One of the lifecycle unit tests was not properly mocked.  The test was loading dependencies for `/bin/true`, which is a process that is dependent on the host's copy of `ldd` and whether the `core22` snap is installed on the host.

tests: mock dependency loading for patch elf test

---

requirements-devel.txt
requirements.txt
tests/spread/core22/clean/task.yaml
tests/spread/core22/environment/test-variables/task.yaml
tests/unit/parts/test_lifecycle.py
tests/unit/parts/test_parts.py

Craft-parts 1.19.0 introduces feature selection, making the overlay step optional, and checks if plugin-specific properties changed when verifying if a part is dirty.
-----

requirements: update craft-parts to 1.19.0

---

snapcraft/cli.py
snapcraft/parts/lifecycle.py
snapcraft/parts/plugins/register.py

Experimental plugins are registered only if the environment variable `SNAPCRAFT_ENABLE_EXPERIMENTAL_PLUGINS` is set to a non-empty value or if the `--enable-experimental-plugins` global argument is used.
Currently the kernel plugin is an experimental plugin.
-----

cli: add option to enable experimental plugins

---

snap/snapcraft.yaml
snapcraft/providers.py
spread.yaml
tests/spread/core22/parallel-install/snap/snapcraft.yaml
tests/spread/core22/parallel-install/task.yaml
tests/spread/tools/prepare.sh
tests/unit/test_providers.py

-----
Allows for core22 snaps to be built using a parallel-installed instance of snapcraft.
A subsequent PR will support core18|20 snaps.
(CRAFT-1660)

providers: inject current snapcraft snap into instances

---

snapcraft/providers.py
tests/unit/test_providers.py

-----
Minor follow up to https://github.com/snapcore/snapcraft/pull/4084 to allow check if snapcraft is running as a snap before reading the envvar `SNAP_INSTANCE_NAME`.
(CRAFT-1660)

providers: allow parallel installations when not running as a snap

---

requirements-devel.txt
requirements.txt

-----
craft-providers 1.10.0 allows using devel images with Multipass.
- Add support for kinetic, lunar, and devel images with Multipass
- Remove unused import suppressions in init files
- Update github actions

requirements: update craft-providers to 1.10.0

---

snapcraft_legacy/cli/_options.py
snapcraft_legacy/cli/lifecycle.py

-----
Adds core18|20 support for `--enable-experimental-extensions` and `SNAPCRAFT_ENABLE_EXPERIMENTAL_EXTENSIONS`.
Similar to https://github.com/snapcore/snapcraft/pull/4085 and https://github.com/snapcore/snapcraft/pull/4092.
(CRAFT-1619)

cli: add option to enable experimental plugins for snapcraft_legacy

---

snapcraft/projects.py
tests/spread/core22/plugs-warn/expected_output.txt
tests/spread/core22/plugs-warn/snap/snapcraft.yaml
tests/spread/core22/plugs-warn/task.yaml
tests/unit/test_projects.py

This commit adds a warning (via emit.message()) when a snapcraft.yaml project has top-level plugs and/or slots that are used for assignment and not per-plug/slot configuration. Thanks to lucyllewy for suggested wording of the warning.
-----

projects: warn on "global" assign of plugs and slots

---

snapcraft/commands/lint.py
tests/spread/core22/linters/lint-file/task.yaml
tests/unit/commands/test_lint.py

-----
`snapcraft lint` now prepares an instance and re-executes `snapcraft lint` inside the instance.
(CRAFT-1690)

lint: prepare instance for linting a snap file

---

spread.yaml

-----
Looks like the spread tests on 22.04 are failing due to insufficient storage (see: https://github.com/snapcore/snapcraft/actions/runs/4708550869/jobs/8352897128). The default is 10 gigs.

spread: bump storage for Google 22.04 spread hosts

---

snapcraft_legacy/internal/build_providers/_multipass/_multipass_command.py
spread.yaml
tests/legacy/unit/build_providers/multipass/test_multipass_command.py

-----
The fixes the warning.
warning: "--mem" long option will be deprecated in favour of "--memory" in a future release.Please update any scripts, etc.

legacy: fix deprecation warning about `multipass --mem`

---

tests/spread/general/parallel-install/task.yaml

-----
18.04 parallel-install tests are sometimes timing out. This should fix that.

spread: increase parallel-install kill timeout for 18.04

---

snapcraft/meta/snap_yaml.py
snapcraft/projects.py
snapcraft_legacy/internal/meta/plugs.py
tests/legacy/unit/meta/test_plugs.py
tests/unit/meta/test_snap_yaml.py
tests/unit/test_projects.py

Add extra validations for default_provider.
-----

meta: disallow Snap channel in default_provider

---

snapcraft/commands/extensions.py
tests/spread/general/expand-extensions/snapcraft.yaml
tests/spread/general/expand-extensions/task.yaml
tests/unit/commands/test_expand_extensions.py

-----
`expand-extensions` command now parses core22 snaps containing parse-info and advanced grammar keywords.
* https://bugs.launchpad.net/snapcraft/+bug/2011719
* https://forum.snapcraft.io/t/parts-part-parse-info-broken/34335
(CRAFT-1701)

extensions: parse snapcraft.yaml before expanding extensions

---

snapcraft_legacy/plugins/v2/_kernel_build.py
tests/legacy/unit/plugins/v2/test_kernel.py
tests/unit/parts/plugins/test_kernel.py

'config.common.ports' config file is deprecated and not used anymore by the Ubuntu kernel, it might disappear in the future altogether, remove use of it when using Ubuntu `kconfigflavour` option, so builds do not break in the future.

plugins: kernel: remove use of deprecated config.common.ports config

---

snapcraft/commands/lint.py
snapcraft/linters/__init__.py
snapcraft/linters/linters.py
tests/spread/core22/linters/lint-file-with-assert/task.yaml
tests/spread/core22/linters/lint-file/expected-linter-output.txt
tests/spread/core22/linters/lint-file/snapcraft.yaml
tests/spread/core22/linters/lint-file/src/test.c
tests/spread/core22/linters/lint-file/task.yaml
tests/unit/commands/test_lint.py

-----
So far, `snapcraft lint` parses the command line, prepares an instance, and re-executes snapcraft inside the instance.
This PR adds the code that is executed inside the instance:
1. Unsquash the snap
2. Collect the metadata from snap.yaml and lint filters from snapcraft.yaml
3. Install the snap
4. Run the linter on `/snap/<snap-name>/current`
5. Report the linter warnings
(CRAFT-1689)

lint: lint snap files inside an instance

---

requirements-devel.txt
requirements.txt

Craft Parts 1.19.3 fixes plugin properties state during the planning phase.
-----

requirements: update craft-parts to 1.19.3

---

snapcraft/parts/plugins/kernel.py
snapcraft_legacy/plugins/v2/_kernel_build.py
snapcraft_legacy/plugins/v2/kernel.py
tests/legacy/unit/plugins/v2/test_kernel.py
tests/unit/parts/plugins/test_kernel.py

when building kernel with `kconfigflavour` Ubuntu config option, the kernel tree should also contain `debian/rules`
call `debian/rules clean` if `debian/rules` exist so `SYSTEM_TRUSTED_KEYS` and `SYSTEM_REVOCATION_KEYS` configs do not need to be modded.

kernel plugin: call deb rules clean

---

snapcraft/meta/snap_yaml.py
tests/unit/meta/test_snap_yaml.py

meta: include project provided assumes in snapd.yaml

---

snapcraft/elf/elf_utils.py
snapcraft/meta/snap_yaml.py
snapcraft/parts/lifecycle.py
snapcraft/projects.py
snapcraft/utils.py
tests/unit/elf/test_elf_utils.py
tests/unit/linters/test_classic_linter.py
tests/unit/linters/test_library_linter.py
tests/unit/linters/test_linters.py
tests/unit/meta/test_snap_yaml.py
tests/unit/parts/test_lifecycle.py
tests/unit/test_projects.py
tests/unit/test_utils.py

-----
Previously, using `build-for: all` in a snapcraft project would cause `meta/snap.yaml` to contain the `build-on` architecture, due to [this line](https://github.com/snapcore/snapcraft/blob/2f2d1eac63de39dbd4f9bbfab8ffa5df0ac9ca62/snapcraft/parts/parts.py#L88) from my first implementation of adding support for the `architectures` keyword.
Now, `build-for: all` will cause `meta/snap.yaml` to use `architectures: all`. 
https://bugs.launchpad.net/snapcraft/+bug/1999580
https://forum.snapcraft.io/t/incorrect-architecture-with-snapcraft-7-x-and-build-for-build-on/34130
(CRAFT-1535)

meta: use build-for in snap.yaml architecture

---

tests/unit/meta/test_snap_yaml.py

-----
Minor fix for unit tests.
Two PRs ([1](https://github.com/snapcore/snapcraft/pull/4150) and [2](https://github.com/snapcore/snapcraft/pull/4152)) touched the same unit test file.  One removed all references to `arch_triplet` and the other added 2 more tests with `arch_triplet` still present.

tests: remove arch_triplet from unit test

---

snapcraft_legacy/plugins/v1/catkin.py

The package `distro-info-data` is not available by default in LXD. This package is necessary for `catkin`.
This enables core18 ROS snap to be built with LXD (and remote-build).
-----

fix(ROS-core18): distro-info-data is not available by default in LXD

---

snapcraft/parts/plugins/_ros.py
snapcraft_legacy/plugins/v2/_ros.py
tests/legacy/unit/plugins/v2/test_catkin.py
tests/legacy/unit/plugins/v2/test_catkin_tools.py
tests/legacy/unit/plugins/v2/test_colcon.py
tests/unit/parts/plugins/test_colcon.py

In remote-build a proxy is used and passed as env var. When calling rosdep init as root those env var were not forwarded. This was causing core20 and core22 ROS snap to be unbuildable on remote-build
rosdep doesn't support proxy:
https://github.com/ros-infrastructure/rosdep/issues/271
-----

fix(ROS): rosdep init executed as root need to forward proxy env var

---

requirements-devel.txt
requirements.txt
snapcraft/providers.py
tests/unit/parts/test_lifecycle.py
tests/unit/test_providers.py

-----
<details>
<summary>Changelog</summary>
1.13.0 (2023-05-31)
-------------------
- Push files to any location in Multipass instances
- Refactor base setup and warmup
- Replace timeout for entire base setup with granular per-step timeouts
- Add option to not install default packages during base setup
- Install build-essentials and python3 in CentOS and AlmaLinux
- Update PATH for CentOS
1.12.0 (2023-05-18)
-------------------
- Add AlmaLinux 9 base
- Add stricter typing for base names
- Refactor CI workflow
- Refactor Multipass `push_file_io`
- Pin dependency urllib3<2
1.11.0 (2023-04-19)
-------------------
- Move Snap pydantic model from `bases.buildd` to `actions.snap_installer`
- Rename `bases.buildd` module to `bases.ubuntu`
- Determine base alias from base configuration in …

requirements: bump craft-providers

---

snapcraft/commands/account.py

-----
[Pyright 1.1.312](https://github.com/microsoft/pyright/releases/tag/1.1.312) now type-checks `kwargs`.  This started causing the following error:
```shell
lint-pyright: commands[0]> pyright
added 1 package, and audited 2 packages in 2s
found 0 vulnerabilities
/home/developer/dev/snapcraft/snapcraft/commands/account.py
/home/developer/dev/snapcraft/snapcraft/commands/account.py:215:68 - error: Argument of type "str | int" cannot be assigned to parameter "ttl" of type "int" in function "login"
  Type "str | int" cannot be assigned to type "int"
    "str" is incompatible with "int" (reportGeneralTypeIssues)
/home/developer/dev/snapcraft/snapcraft/commands/account.py:215:68 - error: Argument of type "str | int" cannot be assigned to parameter "acls" of type "Sequence[str] | None" in …
```

lint: fix for pyright 1.1.312

---

requirements-devel.txt
requirements.txt
snapcraft/commands/account.py

Craft Parts 1.19.6 reverts subdir changes in pull and build steps.
-----

requirements: update craft-parts to 1.19.6

---

snapcraft/commands/names.py
snapcraft/commands/status.py

-----
Cherry-pick #3423 into `hotfix/7.5`

type: workaround for pyright bug

---

snapcraft_legacy/_store.py
tests/legacy/unit/commands/test_list_keys.py
tests/legacy/unit/store/test_keys.py

-----
Cherry-picked hotfix for https://github.com/snapcore/snapcraft/pull/4234
CRAFT-1804

store: add missing case for list-keys

---

spread.yaml

godeps can not longer build due to
https://github.com/golang/go/issues/57051
Instead of removing the godeps feature, disable the tests in case the upstream fixes the problem.
-----

spread: disable godeps tests

---

snapcraft/parts/plugins/kernel_plugin.py

Hi,
I was using kernel plugin to build a  RISC-V kernel, but it won't build `dtbs`, and I found it will append `dtbs` only if `ARCH` matches `arm`, `arm64` or `riscv64`, however, the `ARCH` in my case is `riscv`. The following are some logs
Before the code change:
```
2023-07-01 23:03:45.814 :: Building kernel...
2023-07-01 23:03:45.814 :: ++ nproc
2023-07-01 23:03:45.816 :: + make -j8 -C /home/vagrant/aristo/UbuntuCoreOS/cache/starfive_visionfive2_backup/kernel_snap/parts/kernel/src O=/home/vagrant/aristo/UbuntuCoreOS/cache/starfive_visionfive2_backup/kernel_snap/parts/kernel/build ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- Image modules
```
After the code change:
```
2023-07-01 23:27:34.931 :: Building kernel...
2023-07-01 23:27:34.931 :: ++ nproc
2023-07-01 23:27:34.932 :: + make -j8 …
```

plugins: add riscv into kernel plugin for build dtbs

---

snapcraft_legacy/internal/remote_build/_launchpad.py
tests/legacy/unit/remote_build/test_launchpad.py

The initial mechanism used by Launchpad to grant temporary access tokens to `snapcraft remote-build` was a bit of a hack.  They were essentially pure bearer tokens (implemented as macaroons) that weren't recorded anywhere on the Launchpad side, which meant that there was no mechanism for revoking them.  We mitigated this with a hardcoded expiry time, but it wasn't great.
We now have a new "personal access tokens" mechanism, which is much better.  These tokens show up in a "Manage access tokens" page on the repository and can be revoked by the owner; they have more specific control of the access scopes they grant, and the caller can specify an expiry time.  The old mechanism is now deprecated, and we intend to remove it after a suitable transition period.
This commit changes `snapcraft …

remote-build: Use personal access tokens

---

.gitmodules

docs: remove obsolete submodule

---

snapcraft/extensions/_utils.py
snapcraft/extensions/extension.py
snapcraft/extensions/gnome.py
snapcraft/extensions/kde_neon.py
snapcraft/extensions/ros2_humble.py
snapcraft_legacy/internal/project_loader/_extensions/_extension.py
snapcraft_legacy/internal/project_loader/_extensions/_utils.py
tests/legacy/unit/project_loader/extensions/test_utils.py
tests/unit/conftest.py
tests/unit/extensions/test_extensions.py
tests/unit/extensions/test_gnome.py
tests/unit/extensions/test_kde_neon.py
tests/unit/parts/extensions/test_ros2_humble.py

Extend the API to take a plugin_name, for legacy do the same, but as an optional method in the base class.
-----

extensions: plugin aware part_snippet values

---

snapcraft/commands/lint.py
snapcraft/errors.py
snapcraft/parts/yaml_utils.py
tests/unit/parts/test_yaml_utils.py
tests/unit/test_errors.py

Bases that were once supported and no longer supported in the current version provide a reference to the version/channel of Snapcraft where they once were.
-----
Fixes #4246

bases: improve errors for ESM bases

---

tests/spread/core22/patchelf/classic-python/task.yaml

This commit adds a spread test to check the "Set up classic confinement for a Python project" tutorial. As an overview, the test:
- runs specifically on Ubuntu 20.04 systems;
- clones the test repo from snapcraft-docs/python-ctypes-example;
- builds & installs the snap from the test repo;
- runs the snap on the 20.04 system, to ensure the patchelf fix is working in the presence of the classic confinement.
-----

spread: add a test for the "python + classic" tutorial

---

snapcraft/meta/snap_yaml.py
tests/spread/general/metadata-links/task.yaml
tests/unit/meta/test_snap_yaml.py

meta: write out metadata links

---

requirements-devel.txt
requirements.txt

Version 1.1.2 allows local package repositories (those with scheme `url: file:///...`) again.
-----

requirements: bump craft-archives

---

snapcraft_legacy/internal/meta/package_repository.py
snapcraft_legacy/internal/meta/snap.py
snapcraft_legacy/internal/project_loader/_config.py
snapcraft_legacy/internal/repo/apt_key_manager.py
snapcraft_legacy/internal/repo/apt_ppa.py
snapcraft_legacy/internal/repo/apt_sources_manager.py
snapcraft_legacy/plugins/v1/_plugin.py
snapcraft_legacy/plugins/v1/catkin.py
snapcraft_legacy/plugins/v1/colcon.py
tests/legacy/unit/meta/test_package_repository.py
tests/legacy/unit/repo/test_apt_key_manager.py
tests/legacy/unit/repo/test_apt_ppa.py
tests/legacy/unit/repo/test_apt_sources_manager.py

This PR restores the original (pre-craft-archives) support for `package-repositories` for core18 and core20. This is done by reverting the changes done to the `snapcraft_legacy/` tree (and its tests) in these two commits:
- 0e12894d236a7159 (requirements: update craft-archives)
- ce23bc7d196f67d89 (repo: migrate to craft-archives)

repos: revert package-repositories changes for core18 and core20

---

snapcraft/cli.py
tests/unit/cli/test_exit.py

-----
Resolves #4262 
(CRAFT-1898)

cli: catch craft-provider errors

---

requirements-devel.txt
requirements.txt
tests/spread/core22/package-repo-archs/armhf.yaml
tests/spread/core22/package-repo-archs/i386.yaml
tests/spread/core22/package-repo-archs/task.yaml

Version 1.1.3 fixes the issue with package-repositories that declare
architectures. In addition to addressing the wrong parameter order, the
new version also improves the handling of architectures.
The summary of the change is: if the host system is amd64 and the arch
of the package repository is i386, _or_ if the host is arm64 and the
repo armhf, then `dpkg --add-architecture <repo_arch>` will be called.
Otherwise, the command is not called. This lets us preserve the
behavior of enabling i386 in the official repositories when a repo
using i386 is added, with the improvement of _not breaking_ apt update
when an "incompatible" architecture combination is declared.
The new spread tests reflect this. Both run in amd64 and add the
deadsnakes ppa to fetch Python in a foreign arch:
- For i386, …

requirements: bump craft-archives 

---

tools/version.py

---
Related to #4145
This allows building/installing `snapcraft` from non-git clones. It would be useful to Homebrew, as we prefer to build from lightweight tarballs.
If `git describe` fails, it first checks if the version is defined in the environment via `SNAP_VERSION` or falls back to a [PEP440-compliant](https://peps.python.org/pep-0440/) version string `0.0.0+devel` (this is similar to the fallback in [`snapcraft/__init__.py`](https://github.com/snapcore/snapcraft/blob/91a18b3128de4971edfc090a8683a64ff1679f2e/snapcraft/__init__.py#L24), but updated for PEP440).
Before:
```console
$ pip3 install https://github.com/snapcore/snapcraft/archive/refs/tags/7.5.0.tar.gz
...
subprocess.CalledProcessError: Command '['git', 'describe', '--always', '--long']' returned non-zero exit status 128. …
```

packaging: allow installing without git

---

requirements-devel.txt
requirements.txt
setup.py
tests/spread/core22/linters/linter-ros2-humble-mixed/task.yaml
tests/spread/core22/set-version-twice/modified-snapcraft.yaml
tests/spread/core22/set-version-twice/original-snapcraft.yaml
tests/spread/core22/set-version-twice/task.yaml

Craft Parts 1.19.7 addresses issues related to version being set
twice during rebuilds.
-----

requirements: update craft-parts to 1.19.7

---

snapcraft/parts/lifecycle.py
tests/spread/core22/manifest/manifest-info-cmdline/task.yaml
tests/unit/parts/test_lifecycle.py

-----
This fixes a bug that has been present since manifests were [added to core22](https://github.com/snapcore/snapcraft/pull/3824/files#diff-81bf1b8cfa88289a0432d3e12f4b4c1c104d4463a49dbc0e6c431d4e444a35cdR372-R378).  
The bug is that `--enable-image-information` was not passed into LXD/Multipass instances.  This flag only got used when running in destructive mode.  During the implementation, there was probably a typo/mix-up between the envvar `SNAPCRAFT_BUILD_INFO` and `--enable-image-information`.
This bug was uncovered by #4329, which prevented the spread test from running inside a LXD container.

manifest: use `--enable-image-information` inside instances

---

snapcraft/parts/lifecycle.py
tests/spread/providers/use-lxd/task.yaml
tests/unit/parts/test_lifecycle.py

-----
Prioritize the command line argument `--use-lxd` over the environment variable `SNAPCRAFT_BUILD_ENVIRONMENT=host`.
Resolves #4307 
(CRAFT-1956)

cli: prioritize `--use-lxd` over `SNAPCRAFT_BUILD_ENVIRONMENT`

---

requirements-devel.txt
requirements.txt
snapcraft/cli.py
snapcraft/commands/lint.py
snapcraft/parts/lifecycle.py
tests/unit/conftest.py

The first commit has the version bumps and fixes from the craft-providers bump (not sure if those were expected)
Second commit has the actual enablement of the feature
The changes themselves are ready for review, but still need to:
... so I'm keeping it as a draft for now. The test failures are related to the needed merge
Fixes #4317

enable "streaming brief" CLI mode

---

docs/requirements.txt
requirements-devel.txt
requirements.txt

Craft Parts 1.24.1 includes a workaround for a craft-cli spinner
deadlock issue.
-----

requirements: update craft-parts to 1.24.1

---

snapcraft/commands/discovery.py
snapcraft/commands/extensions.py
snapcraft/commands/init.py
snapcraft/commands/lint.py
snapcraft/commands/remote.py
snapcraft/parts/lifecycle.py
snapcraft/parts/yaml_utils.py
tests/unit/commands/test_init.py
tests/unit/parts/test_lifecycle.py
tests/unit/parts/test_yaml_utils.py

-----
Move 4 `snapcraft.yaml` utility functions out of `lifecycle` module into the `yaml_utils` module.  No functional changes.
I've been wanting to do this for some time.  Working on #4318 is an excuse to get it done since it requires importing these functions.

refactor(parts): move yaml utils out of lifecycle

---

snapcraft/sources.py
tests/spread/plugins/v1/x-local/local-plugin/task.yaml
tests/spread/plugins/v1/x-local/snaps/source-get/snap/plugins/x_local_plugin.py
tests/spread/plugins/v1/x-local/snaps/source-get/snap/snapcraft.yaml

Support legacy local plugins that invoke `snapcraft.sources.get`
by redirecting imports to `snapcraft_legacy`. This is similar
to the strategy used for V1 and V2 plugins.
-----
Fixes #4285

fix(legacy): export sources method to local plugins

---

snapcraft/parts/lifecycle.py
snapcraft/parts/parts.py
tests/spread/core22/try/task.yaml
tests/unit/parts/test_lifecycle.py

This solves the case where prime was run before try, where a subsequent run of try would mask the contents of the existing prime directory with a newly mounted one from the host. In legacy we had the concept of `clean --unprime` to solve this.
-----
Fixes #4219

fix: reprime for try

---

README.md

-----
Add build status badge for readthedocs.
I broke the badges into multiple lines for readability.
Preview here: https://github.com/snapcore/snapcraft/tree/docs-badge#readme

docs(readme): add readthedocs build badge

---

snapcraft/commands/remote.py
tests/unit/commands/test_remote_build.py

-----
Valid values for the environment variable are:
- `disable-fallback`: uses new remote-build code
- `force-fallback`: uses legacy remote-build code
This envar is used for bases core22 and older. Bases newer than core22 use the new remote-build code.
Fixes #4319 
(CRAFT-1974)

feat(remote-build): check SNAPCRAFT_REMOTE_BUILD_STRATEGY envvar

---

snapcraft/projects.py
tests/unit/test_projects.py

Rudimentary support for validating abstract sockets in listen-streams. The complete check will take place at `snap pack --check-skeleton` at the end of the process.
-----
Fixes #4287

fix: support abstract socket listen-streams

---

.github/workflows/tox.yaml
snapcraft/commands/account.py
snapcraft/commands/legacy.py
snapcraft/commands/lint.py
snapcraft/commands/manage.py

-----
Autogenerated documentation needs to be created before running the linters.
You should be able to reproduce this problem on `main`:
```
tox run -e build-docs
tox run -e lint-docs # fails on autogenerated commands
```
2 separate commits so this is a rebase-and-merge.

style(docs): fix linter errors for auto-generated commands

---

snapcraft_legacy/plugins/v2/rust.py
tests/legacy/unit/plugins/v2/test_rust.py

-----
This pull request migrates the Rust plugin to the new plugin system and also makes it more intelligent.
Three new options have been added:
- One option for enabling LTO (more optimized binary)
- One option for specifying Rust toolchain channel/version
- One option for disabling default features in the Rust crate

Rust plugin: rewrite the Rust plugin for core20

---

snapcraft/commands/remote.py
tests/unit/commands/test_remote_build.py

-----
This is the last bit of control logic for remote-build.
If a snapcraft project is not in a git repository, execute the legacy remote-build code.
Fixes #4321 
(CRAFT-1976)

feat(remote-build): check if project is in a git repository

---

.github/workflows/spread-scheduled.yaml
README.md

-----
The scheduled spread tests have never run successfully due to a minor typo.
The badge can be previewed here: https://github.com/snapcore/snapcraft/blob/weekly-spread/README.md

ci: fix weekly spread tests, add status badge

---

extensions/desktop/common/desktop-exports

Fixes: https://launchpad.net/bugs/2025651
At the moment the snaps in at least lunar and mantic load font configuration both from `gnome-42-2204` and from the host system’s `/etc/fonts/conf.d`. This has proved to confuse fontconfig and result in unexpected issues. Stopping the snaps from loading from `/etc/fonts/conf.d` seems to fix the issue.
This PR reverts part of https://github.com/snapcore/snapcraft/commit/407dc755, which is sad IMO. But it’s a result of the reluctance to use font configuration from the host system as expressed in [this comment](https://github.com/ubuntu/gnome-sdk/issues/49#issuecomment-1216321729), and for now the proposed change is the easiest way to stop fontconfig from being confused.
-----

Stop fontconfig from loading from host’s /etc/fonts/conf.d

---

docs/requirements.txt
requirements-devel.txt
requirements.txt

Craft Parts 1.24.1 adds numerous improvements to the Rust plugin.
-----

build(deps): bump craft-parts from 1.24.1 to 1.25.1

---

tests/unit/commands/test_remote.py

-----
Instead of mocking the function that loads a `snapcraft.yaml`, the tests now create and load the file.
Preparatory work for #4322
(CRAFT-1977)

tests: use less mocks in remote-build

---

.github/workflows/spread-scheduled.yaml

-----
The scheduled spread tests were not downloading the snap to the `tests/` directory.
I triggered a run and it is working now. See logs here: https://github.com/snapcore/snapcraft/actions/runs/6313456368

ci: download snap to tests dir

---

snapcraft/commands/remote.py
snapcraft/parts/yaml_utils.py
snapcraft/remote/__init__.py
snapcraft/remote/utils.py
tests/unit/commands/test_remote.py
tests/unit/remote/test_utils.py

-----
4 commits.  It's easiest to review one commit at a time.
Generates a build-id or uses the build-id provided at the command line.
Fixes #4322 
(CRAFT-1977)

feat(remote-build): get build id

---

snapcraft/projects.py
snapcraft/utils.py
tests/unit/parts/test_lifecycle.py
tests/unit/test_projects.py
tests/unit/test_utils.py

-----
Fixes #4214
(CRAFT-1808)

fix(project): improve error message for unsupported architectures

---

snap/snapcraft.yaml

Build libgit2 from source, also ensure we do not download any wheels.
-----
Fixes #4379

fix: add part in snapcraft.yaml to build libgit2

---

.github/workflows/tox.yaml
appveyor.yml
pyproject.toml
snapcraft/commands/remote.py
snapcraft/errors.py
tests/unit/commands/test_remote.py
tox.ini

fix(remote-build): warn instead of error when using unsupported bases

---

pyproject.toml
snapcraft/commands/remote.py
snapcraft/legacy_cli.py
snapcraft/remote/__init__.py
snapcraft/remote/errors.py
snapcraft/remote/git.py
snapcraft/remote/launchpad.py
snapcraft/remote/remote_builder.py
snapcraft/remote/utils.py
snapcraft/remote/worktree.py
tests/unit/commands/test_remote.py
tests/unit/remote/test_errors.py
tests/unit/remote/test_launchpad.py
tests/unit/remote/test_remote_builder.py
tests/unit/remote/test_utils.py
tests/unit/remote/test_worktree.py

-----
- Migrate the command logic used to orchestrate a remote build.
- Some of this code was moved to a new class, `RemoteBuild`
- Store a copy of the project directory in the local cache
- Clean up the cache after a build completes
- Typing and linting updates
Builds on #4390, so "only" the last 8 commits are for this PR (update: #4390 was landed and this PR is rebased onto main).  The new remote-build should be functional, so I encourage you to give it try.
Fixes #4324 
(CRAFT-1979)

feat(remote-build): new command logic

---

docs/requirements.txt
requirements-devel.txt
requirements.txt

-----
Update craft-providers to 1.18.0.  The primary motivation for this PR is to capture stdout and stderr when installing a snap inside an instance fails.  There are some other performance improvements when creating base instances for LXD.
1.17.0 introduces the global pip cache, but this is an opt-in feature so snapcraft's behavior is unchanged.
- Check if base instance status before copying
- Fail quickly when LXD errors do not involve instance creation
- Add check parameter to execute_run
- Use a shared pip cache across instances
- Remove Ubuntu 22.10 (Kinetic) support
- Capture details for snap errors
- Improve LXD instance creation process to avoid race conditions. The base instance is now created first and copied to an instance. Retry, timeout, and locking mechanisms prevent …

chore(deps): update craft-providers to 1.18.0

---

snapcraft/commands/remote.py

-----
Fix a regression where `--launchpad-timeout` was not parsed and could not be used by the fallback remote builder.
Note - I made 2 PRs (this one and #4426) because the remote build code is very different between `main` and the `hotfix/7.5` branches (`main` has the new remote builder code, `hotfix/7.5` does not).
Fixes #4397 
(CRAFT-2094)

fix(remote-build): parse `--launchpad-timeout` argument

---

pyproject.toml

-----
X.Y versions in a `pyproject.toml` need to be quoted to avoid being treated as an integer to avoid warnings like this:
```
pyproject.toml: [mypy]: python_version: Python 3.1 is not supported (must be 3.4 or higher). You may need to put quotes around your Python version
```

chore(pyproject): quote versions

---

requirements-devel.txt
requirements.txt
snapcraft/commands/lint.py
snapcraft/providers.py
spread.yaml
tests/spread/core-devel/basic/snap/snapcraft.yaml
tests/spread/core-devel/basic/task.yaml
tests/spread/core24/simple-snap/snap/Makefile
tests/spread/core24/simple-snap/snap/hello.c
tests/spread/core24/simple-snap/snap/snapcraft.yaml
tests/spread/core24/simple-snap/task.yaml
tests/unit/conftest.py
tests/unit/parts/test_lifecycle.py
tests/unit/test_providers.py

-----
Also included devel base tests.
And a fix to run tests in multipass.
Fixes: #4412
CRAFT-2171

build(deps): bump craft-providers to 1.19.1

---

requirements-devel.txt
requirements.txt
snapcraft/providers.py
spread.yaml
tests/spread/core-devel/basic/snap/snapcraft.yaml
tests/spread/core-devel/basic/task.yaml
tests/spread/core24/simple-snap/snap/Makefile
tests/spread/core24/simple-snap/snap/hello.c
tests/spread/core24/simple-snap/snap/snapcraft.yaml
tests/spread/core24/simple-snap/task.yaml

Adds spread tests for `base: devel` spread tests and fixes multipass spread tests.

build(deps): bump craft-providers to 1.19.1 (#4421)

---

snapcraft/cli.py
snapcraft/commands/remote.py
snapcraft/remote/launchpad.py
snapcraft/remote/remote_builder.py
tests/unit/cli/test_exit.py
tests/unit/commands/test_remote.py

-----
Catch `RemoteBuildErrors` and improve the UX for remote building.
The launchpad authorization message (see below) still doesn't look great because it adds its own newlines.  It is directly printed by `launchpadlib` and I'm not sure there is a straightforward way to make it look better.
```python
"Please open this authorization page:\n"
" (%s)\n"
"in your browser. Use your browser to authorize\n"
"this program to access Launchpad on your behalf."
```
Fixes #4399 
(CRAFT-2096)

fix(remote-build): improve logging and catch exceptions

---

.github/workflows/spread-scheduled.yaml
tests/spread/general/remote-build/task.yaml

-----
Test the new and legacy remote-build in the weekly spread test.
See a successful workflow job [here](https://github.com/snapcore/snapcraft/actions/runs/6711140620/job/18238067023)
Fixes #4398
(CRAFT-2095)

tests(spread): add remote-build spread test

---

snapcraft/pack.py
snapcraft/parts/lifecycle.py
tests/unit/test_pack.py

The error will looks like this instead of long stderr output.
```
Command '['snap', 'pack', '--check-skeleton', PosixPath('/root/prime')]' returned non-zero exit status 1.
Failed to execute pack in instance.
```
The stderr output will be saved in the logs.

chore(log): hide details error in the log when pack failed

---

.github/workflows/tox.yaml
tox.ini

-----
- Add [`tox-gh`](https://github.com/tox-dev/tox-gh) from starbase, which adds collapsing sections in CI logs
- Colorize the output of tox (similar to https://github.com/canonical/craft-providers/pull/442)
Replaces https://github.com/snapcore/snapcraft/pull/4422
[Before](https://github.com/snapcore/snapcraft/actions/runs/6721498228/job/18267360658#step:5:1)
[After](https://github.com/snapcore/snapcraft/actions/runs/6734011448/job/18303944002?pr=4435#step:5:1)

ci: colorize tox and collapse sections

---

docs/requirements.txt
requirements-devel.txt
requirements.txt

-----
- Update base compatibility tag from ``base-v2`` to ``base-v3``
This fixes an issue where LXD instances created with
``craft-providers==1.16.0`` may fail to start with
``craft-providers>=1.17.0``.

build(deps): bump craft-providers to 1.19.2

---

docs/howto/architectures.rst
docs/reference/architectures.rst

-----
Update documentation for architectures to discourage the use of the shorthand notation in core22 snaps.
This is because the shorthand notation for core22 snaps is not supported by Launchpad.  Removing support in snapcraft would be disruptive so instead we can discourage its usage by removing it from the documentation.
The documentation on snapcraft.io/docs has already been updated.
[LP #2042167](https://bugs.launchpad.net/snapcraft/+bug/2042167)

docs(architectures): remove shorthand notation for core22 architectures

---

snap/snapcraft.yaml
tests/spread/core22/chisel-base/snapcraft.yaml
tests/spread/core22/chisel-base/task.yaml

feat: enable chisel

---

docs/requirements.txt
requirements-devel.txt
requirements.txt
snapcraft/parts/parts.py
tests/spread/core22/clean/task.yaml
tests/unit/parts/test_parts.py

feat: improve lifecycle messages

---

snapcraft/parts/update_metadata.py

-----
Add a missing f-string to a debug message

fix(metadata): add f-string to debug message

---

requirements-devel.txt
requirements.txt

Allows headless systems to fallback to a file based keyring backend.
-----
To verify, the following would fail
```
multipass shell
snap install snapcraft
snapcraft login
```
but,
```
snap refresh snapcraft edge/pr-4455
snapcraft login
snapcraft whoami
```
would work

build(deps): bump craft-store to 2.5.0

---

docs/reference/architectures.rst
snapcraft/remote/utils.py
snapcraft_legacy/cli/remote.py

This architecture is now virtualized and unrestricted in Launchpad, so remote-build can support it.
-----

remote-build: Add riscv64

---

snapcraft/remote/git.py
snapcraft/remote/launchpad.py
tests/unit/remote/test_git.py
tests/unit/remote/test_launchpad.py

fix: push tags for remote-build

---

snapcraft/parts/parts.py

Wipe "Initializing lifecycle" when parts steps start making progress by moving the action message from the emit.open_stream call to an explicit emit.progress.
-----

fix: improve lifecycle messages

---

requirements-devel.txt
requirements.txt

-----
This resolves a bug introduced in `1.16.0` where improperly set-up base instances would cause snapcraft to fail with the error `Instance setup failed. Check LXD logs for more details`.
- Update base compatibility tag from ``base-v3`` to ``base-v4``
- If an existing base instance is not setup, then it is auto-cleaned.
If the process that created the not setup base instance is inactive, then
``craft-providers`` will immediately auto-clean the instance.
- Snaps injected from the host will have their base snap injected into
the instance.

build(deps): bump craft-providers to 1.20.1

---

snapcraft/remote/git.py
snapcraft/remote/launchpad.py
tests/unit/remote/test_launchpad.py

Call git push directly due to libgit2 bug
Also the token will be used mutiple times, so it cannot expire after 1 min.
Fixes: #4478

fix(remote): use git for push to remote system

---

setup.py
snap/snapcraft.yaml
snapcraft/__init__.py
snapcraft/elf/_elf_file.py
snapcraft_legacy/__init__.py
snapcraft_legacy/cli/_metrics.py
snapcraft_legacy/internal/build_providers/_base_provider.py
snapcraft_legacy/internal/elf.py
tools/freeze-requirements.sh

---
Fixes #4407
This removes the `setuptools<66` pin (which also unblocks python 3.12 support):
- `pkg_resources.parse_version` is replaced with `packaging.version.parse` (which now only accepts PEP 440-compliant version strings. I only made the changes needed to pass the unit tests, but maybe we should be more defensive)
- `pkg_resources.require` is replaced with `importlib.metadata.version` (added in [python 3.8](https://docs.python.org/3/library/importlib.metadata.html))
I've also updated `setup.py` with env markers (see the caveat in the commit message, lmk if that's not ok) and a minimum python (not sure if this should be `3.9` or `3.10`)

refactor: replace `pkg_resources` with `packaging`

---

appveyor.yml
requirements-devel.txt
snapcraft_legacy/internal/dirs.py
tools/freeze-requirements.sh

ci(appveyor): fix pyinstaller

---

snapcraft/commands/remote.py
snapcraft/remote/__init__.py
snapcraft/remote/errors.py
snapcraft/remote/git.py
snapcraft/remote/remote_builder.py
tests/unit/commands/test_remote.py
tests/unit/remote/test_git.py
tests/unit/remote/test_remote_builder.py

Git shallow clone is not pushable by design. Fallback to legacy remote build which has workaround. This only support core20 and core22. Any other bases and devel will report error.

fix(remote): fallback to legacy snapcraft if under shallow git clone

---

snapcraft/meta/component_yaml.py
snapcraft/parts/lifecycle.py
snapcraft/parts/parts.py
snapcraft/projects.py
tests/spread/core22/components/simple/snap/expected-man-pages-component.yaml
tests/spread/core22/components/simple/task.yaml
tests/unit/meta/test_component_yaml.py
tests/unit/parts/test_lifecycle.py
tests/unit/parts/test_parts.py
tests/unit/test_projects.py

-----
Generate metadata for components and write the metadata to `prime/component/<component-name>/meta/component.yaml`.
Fixes #4466 
(CRAFT-2312)

feat(meta): generate metadata for components

---

snapcraft/parts/lifecycle.py
tests/unit/conftest.py
tests/unit/parts/test_lifecycle.py

-----
Stop passing the deprecated parameter `build_base` to craft-providers to avoid the warning intended for developers:
```
Deprecated: Parameter 'build_base' is deprecated and should not be used. The build base now comes from the base_configuration's alias.
```
Note this is already fixed on main.
Source: https://matrix.to/#/!GGqzbFAUQprdPgYYCM:ubuntu.com/$bxytvo9JAtlAkoLNJyXsaQ-4xUM0xRBMLxwP_f1jh34?via=ubuntu.com&via=matrix.org&via=xentonix.net

chore: remove deprecated parameter `build-base`

---

snapcraft/pack.py
snapcraft/parts/lifecycle.py
tests/spread/core22/components/file-migration/task.yaml
tests/spread/core22/components/simple/task.yaml
tests/unit/parts/test_lifecycle.py
tests/unit/test_pack.py

-----
Pack components with `snap pack`.
Snaps can have custom filenames using `--output`  (i.e. `snapcraft pack --output my-dir/my-snap.snap`)
However, components cannot.  Their names are determined by `snap pack`.  They will still be placed in the same output directory (`my-dir` in the example above).
Fixes #4467
(CRAFT-2313)

feat: pack components

---

requirements-devel.txt
requirements.txt
setup.py
snapcraft/providers.py
tests/spread/core22/components/environment/task.yaml
tests/spread/core22/components/file-migration/snap/snapcraft.yaml
tests/spread/core22/components/file-migration/task.yaml
tests/spread/core22/components/simple/snap/expected-component.yaml
tests/spread/core22/components/simple/snap/snapcraft.yaml
tests/spread/core22/components/simple/task.yaml
tests/unit/test_providers.py

-----
1. Install snapd from edge inside build environments
2. Update spread tests to exercise build environments (two tests use lxd, one uses destructive-mode)
Note: 
Installing `snapd` from edge exposed a minor bug in craft-providers `1.20.1`.  However, that bug was mercifully fixed in the `1.19.3` hotfix (which was released and merged to main after `1.20.1` and there hasn't been a release on main since).  So To get this prototype out the door, I'm just pointing to `main` for craft-providers and I'll do a [release](https://github.com/canonical/craft-providers/pull/493) soon.

fix: install snapd from edge inside build environments

---

snap/snapcraft.yaml

Upcoming Chisel (and chisel-releases) changes will break older versions of the tool; update it to v0.8.1 which is compatible with this change and gives us some breathing room before we change the way Chisel is provisioned.
Ref: https://github.com/canonical/rockcraft/pull/449
-----

chore(deps): bump version of Chisel

---

snapcraft/remote/git.py

-----
I personally tried this on Fedora
Fixes #4510
Fixes #4520

fix(remote-build): set a known path to cacerts

---

docs/requirements.txt
requirements-devel.txt
requirements.txt
tests/spread/core22/invalid-utf8/snapcraft.yaml
tests/spread/core22/invalid-utf8/task.yaml

This new version fixes decoding issues when parsing malformed output from other processes (typically during the build step)
Fixes #4515
-----

build(deps): bump craft-cli to 2.5.1

---

docs/requirements.txt
requirements-devel.txt
requirements.txt

-----
Bumping `craft-providers` as a prerequisite for https://github.com/snapcore/snapcraft/issues/4519
- Update base compatibility tag to base-v6
- Add Ubuntu 24.04 (Noble) support
- Remove Ubuntu 23.04 (Lunar) support

build(deps): bump craft-providers to 1.21.0

---

snapcraft/parts/lifecycle.py
snapcraft/parts/yaml_utils.py
snapcraft/projects.py
snapcraft/providers.py
snapcraft/utils.py
tests/unit/commands/test_remote.py
tests/unit/test_utils.py

`get_effective_base()` should not return "devel" and pass it to the `PartsLifecycle()`, which make the parts think the coreXX is "devel". Thus checking the wrong path for dynamic linking.
`LD_LIBRARY_PATH=...:/snap/core24/current/lib:/snap/core24/current/usr/lib:...`
become
`LD_LIBRARY_PATH=...:/snap/devel/current/lib:/snap/devel/current/usr/lib:...`
which not exists.
Fix: #4508

fix(lifecycle): return correct base when using devel for build-base

---

snapcraft/cli.py
snapcraft/remote/errors.py
snapcraft/remote/git.py
tests/unit/commands/test_remote.py
tests/unit/remote/test_git.py

-----
Fixes #4517 
(CRAFT-2387)

style(remote): reword git error messages

---

snapcraft/commands/remote.py
tests/unit/commands/test_remote.py

-----
2 commits:
- fix(remote): make `--build-for` and `--build-on` mutually exclusive
- This was not working as intended (and was not tested)
- This is only for the new remote-build and makes no changes to how legacy remote build handles these arguments
- fix(remote): parse comma-separated architectures
- This uses the same style that legacy remote-build uses for passing architectures - a single comma-separated set
Fixes #4516
(CRAFT-2386)

fix(remote): parse comma-separated architectures

---

docs/requirements.txt
requirements-devel.txt
requirements.txt

-----
Resolves https://bugs.launchpad.net/snapcraft/+bug/2051567
- Do not update apt sources for Ubuntu devel images

build(deps): bump craft-providers to 1.22.0

---

snapcraft/projects.py
tests/unit/test_projects.py

-----
Components beginning with `snap-` are reserved for future use by `snapd`.
Fixes #4538
(CRAFT-2419)

feat(projects): validate component names do not begin with 'snap-'

---

docs/requirements.txt
requirements-devel.txt
requirements.txt

Craft Parts 1.26.2 fixes proxy support in the ant plugin and
the default values of aliased fields in parts.
-----

chore(deps): bump craft-parts to 1.26.2

---

docs/requirements.txt
requirements-devel.txt
requirements.txt
snapcraft/providers.py

-----
When using `build-base: devel`, use the `core24` buildd daily image instead of the `devel` daily image.
There is no change in how a user defines their `snapcraft.yaml`.  Once the `core24` base is available in the beta channel, then we can allow users to use `base: core24`.
There are some intermittent problems with launching buildd daily images, see https://github.com/canonical/craft-providers/issues/498.
Fixes #4519
(CRAFT-2390)

feat(providers): use core24 buildd daily image for devel

---

extensions/desktop/common/init

fixes that #3738 couldn't
-----

extensions/desktop: don't preload bindtextdomain for wine snaps

---

requirements-devel.txt
snapcraft/meta/__init__.py
snapcraft/meta/snap_yaml.py
tests/spread/core24/environment/snaps/paths-all-null/expected_snap.yaml
tests/spread/core24/environment/snaps/paths-one-null/expected_snap.yaml
tests/spread/core24/environment/snaps/paths-user-defined/expected_snap.yaml
tests/spread/core24/environment/snaps/staged-common-library/expected_snap.yaml
tests/unit/conftest.py
tests/unit/meta/test_snap_yaml.py
tests/unit/services/test_package.py

fix: do not propagate build-base to snap.yaml

---

tests/spread/general/store/task.yaml

This works around the review-tools issue triggered by the squasfs block size change in snapd.
-----

fix(tests): upload a larger snap

---

tests/spread/core24/linters/library-unused/expected_linter_output.txt

-----
This fixes `google:ubuntu-22.04-64:tests/spread/core24/linters/library-unused`

fix(tests): expect the proper libpng version in core24 linter test

---

snapcraft/projects.py
tests/unit/test_projects.py

The regular validator's 'values' parameter contains only the fields that have been validated so far (a bad footgun).
-----

fix(project): fix core24/devel validation

---

.github/workflows/spread.yml
spread.yaml
tests/spread/core24/package-repositories/task.yaml

This mainly removes the --use-lxd toggle, there is no reason for it as it is the default.
-----

chore(spread): enable pkg-repo tests for core24

---

docs/requirements.txt
requirements-devel.txt
requirements.txt

-----
- Update base compatibility tag to ``base-v7``
- Use ``buildd`` daily for Ubuntu 24.04 (Noble) and Ubuntu devel images
- Ensure apt installs non-interactively

build(deps): bump craft-providers to 1.23.0

---

snapcraft/models/project.py
snapcraft/parts/update_metadata.py
tests/unit/models/test_projects.py
tests/unit/services/test_package.py

fix: use VersionStr in model and add write test

---

snapcraft/meta/appstream.py
snapcraft/parts/setup_assets.py
tests/unit/parts/test_setup_assets.py

- Move executable setting to one location
- Test for default behavior in relation to hooks
- Test with new asset handler in relation to hooks
-----

feat: allow for overriding project asset handling

---

snapcraft/extensions/_ros2_humble_meta.py
snapcraft_legacy/internal/project_loader/_extensions/_ros1_noetic_meta.py
snapcraft_legacy/internal/project_loader/_extensions/_ros2_foxy_meta.py
tests/legacy/unit/project_loader/extensions/test_ros1_noetic_meta.py
tests/legacy/unit/project_loader/extensions/test_ros2_foxy_meta.py
tests/spread/extensions/catkin-tools-noetic-meta-hello/task.yaml
tests/spread/extensions/ros-noetic-meta-hello/task.yaml
tests/spread/extensions/ros-noetic-meta-talker-listener/task.yaml
tests/spread/extensions/ros2-foxy-meta-hello/task.yaml
tests/spread/extensions/ros2-foxy-meta-talker-listener/task.yaml
tests/spread/extensions/ros2-humble-meta-hello/task.yaml
tests/spread/extensions/ros2-humble-meta-talker-listener/task.yaml
tests/spread/plugins/v2/ros1-hello/task.yaml
tests/unit/parts/extensions/test_ros2_humble_meta.py

(slot) & plug renaming triggered by the request for autoconnection.
For details see [the request on the forum](https://forum.snapcraft.io/t/request-for-global-autoconnect-of-ros-foundation-snaps/38851/8).
Marking as 'draft' until the associated content snaps are released on the store.
-----

Use more specific naming for ROS plugs

---

snapcraft/commands/core22/lifecycle.py
snapcraft/commands/core22/lint.py
snapcraft/parts/lifecycle.py
tests/unit/commands/test_lint.py

`--enable-manifest` and `--manifest-image-information` no longer supported in core24.

feat!: deprecate enable-manifest and manifest-image-information

---

tests/unit/remote/test_launchpad.py

`Mock.called_with` was never actually a real mock method in `unittest.mock`. It was returning a Mock object, which is truthy.
-----

tests: replace mock methods removed in Py3.12

---

snapcraft/providers.py
snapcraft/utils.py
tests/spread/providers/use-lxd/task.yaml
tests/unit/test_providers.py

`craft-application` uses `CRAFT_MANAGED_MODE` environment variable, while `snapcraft` was still using `SNAPCRAFT_MANAGED_MODE`.  This was causing inner managed instances of snapcraft to not realize they were running in managed mode, and write their logs into an ephemeral location inside the LXD instance, rendering those logs inaccessible from the host.
Note that while this fixes the logging issue, this does not fix the spread tests that @tigarmo was hoping it would.
-----
(CRAFT-2539)

fix(application): use SNAPCRAFT_MANAGED_MODE everywhere

---

tests/unit/commands/test_remote.py
tests/unit/models/test_projects.py

This allows running tests with `pytest-xdist` to take advantage of multicore systems
-----

tests: make parametrized unit test order determinable

---

snapcraft/services/package.py
tests/spread/core24/hooks/aux/build-aux/snap/hooks/install
tests/spread/core24/hooks/aux/build-aux/snap/snapcraft.yaml
tests/spread/core24/hooks/aux/src/configure/configure.go
tests/spread/core24/hooks/aux/src/go.mod
tests/spread/core24/hooks/aux/src/install/install.go
tests/spread/core24/hooks/default/snap/hooks/install
tests/spread/core24/hooks/default/snap/snapcraft.yaml
tests/spread/core24/hooks/default/src/configure/configure.go
tests/spread/core24/hooks/default/src/go.mod
tests/spread/core24/hooks/default/src/install/install.go
tests/spread/core24/hooks/task.yaml
tests/unit/services/test_package.py

The PrimeCommand calls
self._services.package.write_metadata(self._services.lifecycle.prime_dir)
Which makes it simple to hook up.
-----
Fixes #4592

feat: setup_assets for core24 metadata

---

snapcraft/meta/appstream.py
snapcraft/meta/extracted_metadata.py
tests/unit/meta/test_appstream.py

This commit adds initial support to adopt more metadata fields from the provided appstream metadata file. Those fields includes,
1. license
2. contact
3. source-code
4. issues
5. website
6. donations
----
-----

feat: adopt more fields from the appstream metadata file

---

snapcraft/models/project.py
snapcraft/utils.py
tests/unit/models/test_projects.py
tests/unit/test_utils.py

For the BuildInfos we want to use "devel" bases, as that is the term that craft-providers expects to create instances based on the development track. We still need to use the regular "base" (e.g. "core24") in other places, so add a customization parameter to get_effective_base() to use either behavior.
-----

fix: use "devel" bases on build plan

---

snapcraft/application.py
snapcraft/parts/extract_metadata.py
snapcraft/parts/parts.py
snapcraft/parts/update_metadata.py
snapcraft/services/package.py
tests/spread/core24/appstream-desktop/desktop/expected_snap.yaml
tests/spread/core24/appstream-desktop/icon-desktop/expected_snap.yaml
tests/spread/core24/appstream-desktop/icon-desktop/snap/snapcraft.yaml
tests/spread/core24/appstream-desktop/task.yaml
tests/unit/conftest.py
tests/unit/services/test_package.py
tests/unit/test_application.py

This is split over multiple commits. The first (valid) one only extracts and stores the data of which part provides the info to be parsed. This lets the project be loaded successfully as the 'parse-info' entry is removed from the parts, but nothing else. The next commit adds the rest of the implementation, and the final commit updates the spread tests.
-----

feat(app): support parse-info

---

tests/unit/services/test_package.py

fix(test): use prime dir in some tests

---

tests/unit/conftest.py
tests/unit/services/test_package.py

There are 2 bugs:
First, the current fixture `snapcraft_yaml` may create 2 `snapcraft.yaml` in `/` and `/snap/` due to it used in different places and it is default to `/snap/snapcraft.yaml`. 
When both `snapcraft.yaml` exists, the `/snapcraft.yaml` is used without any error / warning.
The second bug is when `/snap/snapcraft.yaml` exists,  `/build-aux/snap` will be ignored even if it had hooks in it. This is probably expected behavior since these are two different versions of the structure.
Needs #4661

fix(test): do not create 2 snapcraft.yaml and confuse location

---

spread.yaml
tests/spread/core22/chisel-base/task.yaml
tests/spread/core22/clean/task.yaml
tests/spread/core22/craftctl/task.yaml
tests/spread/core22/invalid-utf8/task.yaml
tests/spread/core22/package-repo-archs/task.yaml
tests/spread/core22/package-repositories/task.yaml
tests/spread/core22/packing/task.yaml
tests/spread/core22/remove-hook/task.yaml
tests/spread/core22/set-version-twice/task.yaml
tests/spread/core22/snap-creation/task.yaml
tests/spread/core22/try/task.yaml

Also make the clean actually clean the correct provider
-----

chore(spread): core22 provider setup cleanup

---

snapcraft/application.py
snapcraft/parts/plugins/__init__.py
snapcraft/parts/plugins/register.py
snapcraft/services/lifecycle.py
tests/unit/services/test_lifecycle.py
tests/unit/test_application.py

Two commits: one registers the plugins in the craft-application codepath, and one adds the confinement and base variables to the lifecycle (so that plugins can use it).

Enable Snapcraft plugins in craft-application codepath

---

.github/workflows/spread-scheduled.yaml
.github/workflows/spread.yml

This ensures we can use any machine with the spread-installed tag. Necessary for upcoming changes to Canonical's self-hosted runners.
Spread will fail until a repo admin adjusts the runner tags.
-----

ci: adjust tags for spread runs

---

snapcraft/meta/component_yaml.py
snapcraft/meta/snap_yaml.py
snapcraft/models/project.py
tests/spread/core22/components/expected-snap.yaml
tests/spread/core22/components/snapcraft.yaml
tests/spread/core22/components/task.yaml
tests/spread/core24/components/expected-snap.yaml
tests/spread/core24/components/snapcraft.yaml
tests/spread/core24/components/task.yaml
tests/spread/general/store/task.yaml
tests/unit/meta/test_component_yaml.py
tests/unit/meta/test_snap_yaml.py
tests/unit/models/test_projects.py
tests/unit/services/test_package_components.py

-----
Support metadata for component hooks.
This includes the project definition and the output in the component's `meta/component.yaml` file.
Built on #4701, so only the last 3 commits are relevant.
Fixes #4570
(CRAFT-2463)

feat: add component metadata for hooks

---

tests/spread/core24/linters-pack/library-unused/snap/snapcraft.yaml

The package we chose was affected by the time_t change.
-----

chore(core24): update package for linter spread test

---

snapcraft/parts/setup_assets.py
tests/spread/core22/components/snapcraft.yaml
tests/spread/core22/components/task.yaml

-----
Package component hooks for core22.
The code was already completed via #4717, it just needed to be enabled.

feat: package component hooks for core22

---

snapcraft/providers.py
tests/spread/core22/components/task.yaml
tests/spread/core24/components/task.yaml
tests/unit/test_providers.py

-----
snapd was installed from the edge channel to support components. This has been replaced with the `_retry_with_newer_snapd` decorator.

fix(providers): do not install snapd from edge

---

snapcraft/extensions/gnome.py
snapcraft/services/provider.py
tests/spread/core24/linters-pack/task.yaml
tests/unit/extensions/test_gnome.py
tests/unit/services/test_provider.py

-----
gnome-extension will be experimental in core24 until support for streamlined graphics support is finalized.
See https://forum.snapcraft.io/t/39718
Note that `core24` snaps using the `gnome-extension` can only be built in environments where the `core24` snap has been pre-installed since `core24` is unavailable on stable.  Thus the extension still isn't being tested by spread ([source](https://github.com/canonical/snapcraft/blob/aed002bbe645a4f8708f3b2094f295b59f467fd6/tests/spread/core24/linters-pack/task.yaml#L23)).

chore: mark gnome-extension experimental for core24

---

snapcraft/application.py
snapcraft/cli.py
snapcraft/commands/__init__.py
snapcraft/commands/core22/__init__.py
snapcraft/commands/core22/extensions.py
snapcraft/commands/lint.py
snapcraft/commands/unimplemented.py
snapcraft/parts/yaml_utils.py
tests/spread/core24/linters-file/lint-file/expected-linter-output.txt
tests/spread/core24/linters-file/lint-file/snapcraft.yaml
tests/spread/core24/linters-file/task.yaml
tests/unit/commands/test_lint.py

Same logic from core22.
2 workarounds, install edge `core24` if stable failed and check only part of the linter warning due to glibc `undefined symbol` in bash.

feat(lint): migrate lint command

---

snapcraft/services/lifecycle.py
tests/spread/core24/package-repositories/task.yaml
tests/unit/services/test_lifecycle.py

This commit mimicks the behavior for core22<= builds where gpg and dirmngr are installed at runtime for projects with package-repositories. The trigger for this commit is the fact that the environment where Snapcraft builds in Launchpad do _not_ have the 'dirmngr' package installed.
Unfortunately the strategy of bundling 'gpg' and 'dirmngr' as stage-packages in Snapcraft's own snap didn't work because gpg has the expected path to the 'dirmngr' executable hardcoded (always trying to call '/usr/bin/dirmngr').
Fixes #4740
-----

fix: install gpg and dirmngr in core24 builds

---

snapcraft/application.py
snapcraft/parts/__init__.py
snapcraft/parts/lifecycle.py
snapcraft/parts/yaml_utils.py
snapcraft/services/lifecycle.py
tests/spread/core24-suites/environment/test-variables/task.yaml
tests/unit/conftest.py
tests/unit/parts/test_lifecycle.py
tests/unit/parts/test_yaml_utils.py

-----
Set project variables for core24 snaps.
`CRAFT_PROJECT_NAME` and `CRAFT_PROJECT_VERSION` are not set, see https://github.com/canonical/craft-application/issues/320 for details.
Fixes #4704
Fixes #4702 
(CRAFT-2657)
(CRAFT-2655)

fix: set project variables for core24

---

docs/requirements.txt
requirements-devel.txt
requirements.txt
setup.py
tests/spread/core24/grammar/snap/snapcraft.yaml
tests/unit/test_application.py

-----
~~Builds on top of https://github.com/canonical/snapcraft/pull/4721, so only look at the last 2 commits.~~
~~I will retarget this on a `hotfix/8.x` branch such that this can fit into `8.2.1`.~~
LP#2061603
(CRAFT-2817)

tests: add tests for advanced grammar in root keywords

---

snapcraft/services/lifecycle.py
tests/spread/core24/package-repositories/test-apt-key-fingerprint/snap/snapcraft.yaml
tests/unit/services/test_lifecycle.py

fix: use local keys for package-repos in core24

---

docs/requirements.txt
requirements-devel.txt
requirements.txt
snapcraft/application.py
snapcraft/parts/__init__.py
snapcraft/parts/lifecycle.py
snapcraft/parts/yaml_utils.py
snapcraft/services/lifecycle.py
tests/spread/core-devel/basic/task.yaml
tests/spread/core24-suites/environment/test-variables/task.yaml
tests/spread/core24/grammar/snap/snapcraft.yaml
tests/spread/core24/package-repositories/task.yaml
tests/spread/core24/package-repositories/test-apt-key-fingerprint/snap/snapcraft.yaml
tests/unit/conftest.py
tests/unit/parts/test_lifecycle.py
tests/unit/parts/test_yaml_utils.py
tests/unit/services/test_lifecycle.py
tests/unit/test_application.py

chore(merge): '8.2.1' into 'main'

---

spread.yaml

-----
Drop core24 workarounds in the spread tests.

tests: remove core24 snap workarounds

---

spread.yaml

-----
Cherry-pick #4761 onto `main` so CI can pass

tests: remove core24 snap workarounds (#4761)

---

snapcraft_legacy/cli/_metrics.py
snapcraft_legacy/storeapi/metrics.py
tests/legacy/unit/cli/test_metrics.py
tests/legacy/unit/store/test_metrics.py

Pursuant to my post on Discourse
(https://forum.snapcraft.io/t/enable-by-architecture-in-the-snapcraft-metrics-cli-tooling/39750), this commit activates the installed_base_by_architecture and weekly_installed_base_by_architecture metrics in the snapcraft metrics tool.
The metric was previously introduced according to this PR https://github.com/canonical/snapcraft.io/issues/1680#issuecomment-688928336
A subsequent issue will be raised against the documentation.
-----

Activate installed_base_by_architecture metrics

---

schema/snapcraft.json
snapcraft/models/project.py
tests/legacy/unit/project/test_schema.py
tests/unit/models/test_projects.py

-----
Snapd 2.57 allows for a [new value](https://github.com/snapcore/snapd/commit/33acdb6167735e23744a7e93149aec366c11ed03) for `refresh-mode` named `ignore-running`
Fixes https://github.com/canonical/snapcraft/issues/4747

feat: support refresh-mode: ignore-running

---

docs/requirements.txt
requirements-devel.txt
requirements.txt
tests/spread/core24-suites/environment/snaps/test-variables/snap/snapcraft.yaml
tests/spread/core24-suites/environment/test-variables/task.yaml
tests/spread/core24/linters-pack/library-gnome/snap/snapcraft.yaml
tests/spread/core24/linters-pack/task.yaml
tests/unit/commands/test_remote.py

-----
Bump craft-application, enable gnome test, and add a regression test for BUILD_ON vars.

build(deps): bump craft-application to 2.6.3

---

snap/snapcraft.yaml

-----
cryptography>=42.0 cannot load legacy algorithms on Ubuntu 20.04 for armhf, ppc64el, riscv64, and s390x.
@cmatsuoka was able to verify this fix in an emulated riscv64 20.04 machine from [here](https://cdimage.ubuntu.com/releases/20.04/release/).
See https://cryptography.io/en/latest/openssl/#legacy-provider-in-openssl-3-x for details on legacy algorithms. 
Fixes [LP#2064639](https://bugs.launchpad.net/snapcraft/+bug/2064639)

fix: set CRYPTOGRAPHY_OPENSSL_NO_LEGACY

---

tests/spread/core24/chisel-base/snapcraft.yaml

-----
Update chisel-base spread test now that `devel` points to Ubuntu 24.10.

tests: update chisel-base test to use core24

---

docs/requirements.txt
requirements-devel.txt
requirements.txt
snapcraft/commands/unimplemented.py
snapcraft/models/project.py
tests/unit/models/test_projects.py

-----
Bump craft-application to 2.7.0.  Requires implementing `_providers_base()`.
Based on https://github.com/canonical/snapcraft/pull/4721

build(deps): bump craft-application to 2.7.0

---

snapcraft/application.py
snapcraft/commands/__init__.py
snapcraft/commands/lifecycle.py
tests/spread/core22/packing/task.yaml
tests/spread/core24/packing/task.yaml
tests/unit/commands/test_lifecycle.py
tests/unit/test_application.py

-----
This fixes a regression in snapcraft 8.2 where `snapcraft pack <directory>` stopped working.  
Fixes #4769
(CRAFT-2861)

feat: allow packing a directory

---

schema/snapcraft.json
snapcraft/models/project.py
tests/legacy/unit/project/test_schema.py
tests/unit/models/test_projects.py

-----
Cherry-pick #4749 onto the `hotfix/8.2` branch to unblock a troublesome issue with the updating the app center (https://github.com/ubuntu/app-center/issues/1643 and https://github.com/ubuntu/app-center/pull/1648)
cc @kenvandine

feat: add refresh-mode value 'ignore-running' (#4749)

---

snapcraft/elf/_elf_file.py
tests/spread/core24/linters-file/task.yaml

-----
Update code comments for #4751

chore: add issue for using `ld` from the base snap

---

snapcraft/commands/remote.py
snapcraft/errors.py
snapcraft/models/project.py
snapcraft/utils.py
tests/spread/general/remote-build/architectures-snap.yaml
tests/spread/general/remote-build/platforms-snap.yaml
tests/spread/general/remote-build/task.yaml
tests/unit/commands/test_remote.py
tests/unit/models/test_projects.py
tests/unit/test_utils.py

This fixes the initial reported bug in #4780. However, I haven't tested some other use cases listed in that bug report.
-----

fix(remote-build): don't fail with certain archs

---

docs/requirements.txt
requirements-devel.txt
requirements.txt
snapcraft/application.py
snapcraft/elf/_patcher.py
snapcraft/parts/lifecycle.py
snapcraft/services/lifecycle.py
tests/spread/core24-suites/patchelf/classic-patchelf/snap/snapcraft.yaml
tests/spread/core24-suites/patchelf/classic-patchelf/task.yaml
tests/spread/core24-suites/patchelf/strict-patchelf/task.yaml
tests/unit/elf/test_patcher.py
tests/unit/services/test_lifecycle.py
tests/unit/test_application.py

-----
This PR has 3 commits for snapcraft 8.2.8.
Replacement PR for https://github.com/canonical/snapcraft/pull/4807
Commits:
- On core24, snapcraft should pass `--no-default-libs` to patchelf to not load libraries from default locations for classic snaps.
- Bump craft parts
- Unregister dotnet for core24

do not load system libraries for classic core24 snaps, bump craft-parts, unregister dotnet

---

Makefile
pyproject.toml
requirements-devel.txt
setup.py
snapcraft/elf/_elf_file.py
snapcraft_legacy/__init__.py
snapcraft_legacy/ruff.toml
snapcraft_legacy/storeapi/__init__.py
tests/unit/meta/test_appstream.py
tox.ini

linter updates

---

snapcraft/meta/appstream.py
snapcraft/meta/extracted_metadata.py
snapcraft/models/project.py
snapcraft/parts/update_metadata.py
tests/spread/core24/appstream-desktop/desktop/expected_snap.yaml
tests/spread/core24/appstream-desktop/icon-desktop/expected_snap.yaml
tests/spread/general/appstream-desktop/expected_snap_core22.yaml
tests/spread/general/appstream-icon-from-desktop/expected_snap_core22.yaml
tests/spread/general/appstream-remote-gfx/expected_snap_core22.yaml
tests/unit/meta/test_appstream.py
tests/unit/meta/test_snap_yaml.py
tests/unit/models/test_projects.py
tests/unit/parts/test_update_metadata.py

-----
This is the Part 2 of PR #4613. This adds a new method named `_update_project_links` which is called from the `update_project_metadata` function. It checks if the `project` has that particular metadata and if yes, then it appends the value into it, and else it casts the value onto it from the `extracted_metadata`

feat: adopt more fields from the appstream metadata file(part 2) 

---

tox.ini

fix(tox): use requirements-devel for linters

---

docs/requirements.txt
requirements-devel.txt
requirements.txt

-----
Craft-application 2.8.0 makes the following remote-build fixes:
- handling comma-separated architectures in `snapcraft remote-build --build-for <arch1>,<arch2>,...`
- retries for launchpad API calls, with an exponential backoff
- correct log file names for remote build logs

build(deps): bump craft-application to 2.8.0

---

snapcraft/application.py
tests/spread/core24/dotnet/snapcraft.yaml
tests/spread/core24/dotnet/task.yaml
tests/spread/plugins/craft-parts/build-and-run-hello/dotnet-hello/dotnet.csproj
tests/spread/plugins/craft-parts/build-and-run-hello/dotnet-hello/hello.cs
tests/spread/plugins/craft-parts/build-and-run-hello/dotnet-hello/snap/snapcraft.yaml
tests/spread/plugins/craft-parts/build-and-run-hello/task.yaml
tests/unit/conftest.py
tests/unit/test_application.py

-----
- re-register dotnet for core22
- add core22 and core24 dotnet spread tests
- refactor `Application` to allow snapcraft to register/unregister plugins per-base
- this includes renaming `_known_core24` to `_known_craft_app_base` in preparation for core26
Fixes #4825 
(CRAFT-2979)

fix: re-register dotnet for core22

---

snapcraft/meta/__init__.py
snapcraft/meta/component_yaml.py
snapcraft/pack.py
tests/spread/core22/components/expected-component.yaml
tests/spread/core22/components/expected-snap.yaml
tests/spread/core22/components/snapcraft.yaml
tests/spread/core24/components/expected-component.yaml
tests/spread/core24/components/expected-snap.yaml
tests/spread/core24/components/snapcraft.yaml
tests/unit/meta/test_component_yaml.py
tests/unit/test_pack.py

-----
Write `provenance` to a component's `meta/component.yaml` file.
Also, use the `SnapcraftMetadata` model such that None and default fields are not written.
source: https://github.com/snapcore/snapd/pull/13964#discussion_r1604828668
Fixes #4827
(CRAFT-2980)

feat: write provenance to component metadata

---

snapcraft/application.py
tests/spread/core24/dotnet/snapcraft.yaml
tests/spread/core24/dotnet/task.yaml
tests/spread/plugins/craft-parts/build-and-run-hello/dotnet-hello/dotnet.csproj
tests/spread/plugins/craft-parts/build-and-run-hello/dotnet-hello/hello.cs
tests/spread/plugins/craft-parts/build-and-run-hello/dotnet-hello/snap/snapcraft.yaml
tests/spread/plugins/craft-parts/build-and-run-hello/task.yaml
tests/unit/conftest.py
tests/unit/test_application.py

-----
This was a clean merge except for a minor conflict between #4841 and #4732 in `snapcraft.application.Application._get_dispatcher()`.

chore(merge): '8.2.11' into 'main'

---

.github/workflows/tics.yaml
tox.ini

-----
- new tox target for a single coverage result for an easier TiCS workflow
- Run TiCS on pushes to main

ci: enable TiCS integration

---

.readthedocs.yaml
docs/requirements.txt

Readthedocs builds don't fetch tags when cloning the repo. This is a problem for us because Snapcraft's version comes from the git tag, so do a fetch of the tags as a post-checkout step.
Additionally, explicitly install snapcraft itself (via "pip install .") so that the code that gets the version from git actually runs. Note that this already works on "latest" because that builds off of "main" where this fix has already been applied (when moving to canonical-sphinx).
-----

build(docs): fix version in rtd builds

---

setup.cfg
snapcraft/application.py
tests/unit/test_application.py

When raised they show up as a Snapcraft internal error if not properly
handled.
This is using the same logic as in legacy.

fix(cli): properly capture store errors

---

.readthedocs.yaml
docs/reference/plugins.rst
docs/requirements.txt
requirements-devel.txt
requirements.txt
setup.cfg
setup.py
snapcraft/application.py
tests/spread/core24/package-filter/snapcraft.yaml
tests/spread/core24/package-filter/task.yaml
tests/unit/test_application.py

-----
Merge 8.2.12 into main
Needs a new craft-parts 1.32.0 release (https://github.com/canonical/craft-parts/pull/762)

chore(merge): '8.2.12' into 'main'

---

docs/explanation/index.rst
docs/explanation/remote-build.rst

-----
This PR explains how the current and legacy remote builders behave.
The behavior of the new and legacy remote builders is nuanced enough that we need comprehensive documentation before we can comfortably make behavioral changes.
Preview here: https://canonical-snapcraft--4882.com.readthedocs.build/en/4882/explanation/remote-build.html
Fixes #4842
(CRAFT-3000)

docs: add explanation for remote build

---

docs/requirements.txt
requirements-devel.txt
requirements.txt
snapcraft/meta/appstream.py
snapcraft/parts/update_metadata.py
tests/unit/meta/test_appstream.py
tests/unit/parts/test_update_metadata.py

-----
This PR checks if the values that are coming from the appstream file are either http/s urls or emails. If they are, those are added to the `ExtractedMetadata`, else they are passed, no code is executed.
Closes #4890

meta: override the links if project links are set and check the links from appstream

---

docs/explanation/remote-build.rst
snapcraft/application.py
tests/unit/test_application.py

-----
Requires core20 snaps to use the legacy remote builder because the new remote builder cannot parse core20 `snapcraft.yaml` files (#4885).
Builds on #4892, so only the last commit is new.
Fixes #4886 
(CRAFT-3071)

fix(remotebuild): require core20 snaps to use the legacy remote builder

---

setup.py

-----
`validators` was added in https://github.com/canonical/snapcraft/pull/4888 to the requirement files but not to `setup.py`

build(deps): add 'validators' to install_requires

---

.github/workflows/tics.yaml

Also shallow checkout like the other workflows
-----

fix: setup Python env for tiobe ci

---

docs/conf.py
docs/explanation/components.rst
docs/explanation/index.rst
docs/howto/code/basic/snapcraft.yaml
docs/howto/code/basic/task.yaml
docs/howto/code/components-organize/snapcraft.yaml
docs/howto/code/components-organize/task.yaml
docs/howto/code/components/snapcraft.yaml
docs/howto/code/components/task.yaml
docs/howto/components.rst
docs/howto/index.rst
docs/reference/components.rst
docs/reference/index.rst
docs/reuse/components-intro.rst
docs/reuse/links.txt
spread.yaml

-----
Add [explanation](https://canonical-snapcraft--4904.com.readthedocs.build/en/4904/explanation/components.html), [how-to](https://canonical-snapcraft--4904.com.readthedocs.build/en/4904/howto/components.html), and [reference](https://canonical-snapcraft--4904.com.readthedocs.build/en/4904/reference/components.html) for components.
Fixes #4857
(CRAFT-3028)

docs: add explanation, howto, and reference for components

---

spread.yaml

-----
Disable `build-base: devel` spread tests until we have the resources to debug the underlying issue with 24.10 buildd images and `systemd-resolved` (#4921).
We should be able to address this issue in 2024-Nov.
Fixes #4910
(CRAFT-3105)

tests: disable `build-base: devel` spread tests

---

snapcraft_legacy/plugins/v2/_kernel_build.py
tests/legacy/unit/plugins/v2/test_kernel.py
tests/unit/parts/plugins/test_kernel.py

Sometimes there may be no `{install_dir}/modules/*/source`, so I think it would be better to add `-rf` for `rm` command, just like how it is used in other lines of the same file(_kernel_build.py)

Add "-f" for rm to ignore file not found error

---

HACKING.md
snapcraft/commands/remote.py
tests/unit/meta/test_appstream.py
tox.ini

-----
`ruff` was already used as a snap for CI but this PR formalizes using the snap.
- use the new `ruff check` call
- compatibility updates for ruff 0.5.4
- documentation changes

build(deps): use the ruff snap

---

docs/howto/bases.rst
docs/reference/changelog.rst
docs/reference/index.rst

-----
Add changelog entries for all existing 8.x releases into readthedocs.
Going forward, all snapcraft changelogs will be in readthedocs.

docs(changelog): add changelog notes for snapcraft 8.0.0-8.3.1

---

.github/workflows/spread.yml
snapcraft/commands/validation_sets.py
snapcraft_legacy/cli/assertions.py
snapcraft_legacy/plugins/v2/_kernel_build.py
snapcraft_legacy/storeapi/v2/_api_schema.py
snapcraft_legacy/storeapi/v2/validation_sets.py
spread.yaml
tests/legacy/unit/plugins/v2/test_kernel.py
tests/legacy/unit/store/test_store_client.py
tests/legacy/unit/store/v2/test_validation_sets.py
tests/spread/store/basic-workflow/task.yaml
tests/spread/store/validation-sets/editor.sh
tests/spread/store/validation-sets/task.yaml
tests/unit/commands/test_validation_sets.py
tests/unit/parts/plugins/test_kernel.py

-----
Snapcraft 8.4 is delayed due to https://github.com/canonical/snapcraft/pull/4884 and https://forum.snapcraft.io/t/kde-global-auto-connect-qt-common-themes/40878/15.
In the interim, we need an 8.3.2 release.
This PR cherry-picks 2 hotfixes and 2 test updates from `main`.  The test updates will fix the failing CI in https://github.com/canonical/snapcraft/pull/4946.

chore: cherry-pick fixes to hotfix/8.3

---

snapcraft/parts/plugins/python_plugin.py
snapcraft/services/lifecycle.py
tests/spread/core24-suites/environment/test-variables/task.yaml
tests/spread/core24/python-hello/classic/snap/snapcraft.yaml
tests/spread/core24/python-hello/src/hello/__init__.py
tests/spread/core24/python-hello/strict/snap/snapcraft.yaml
tests/spread/core24/python-hello/task.yaml
tests/unit/parts/plugins/test_python_plugin.py
tests/unit/services/test_lifecycle.py

Changes to virtual environment handling made our default approach - creating a venv in the build system and then just moving it into the snap - not work for Python 3.12.
My understanding of the issue is that the "home" key in the "pyvenv.cfg" file points to a path in the build system, which obviously does not exist at snap-run-time. This apparently works fine *somehow* in core22 - likely there's some fallback logic that makes the interpreter correctly find the bundled Python libraries, but not in core24. So to address this we update this "home" key to point to its final destination in the snap.
Fixes #4942
-----

fix: fix Python venv in core24 classic snaps

---

docs/conf.py
docs/explanation/index.rst
docs/explanation/parts.rst
docs/requirements.txt
requirements-devel.txt
requirements.txt
setup.py

-----
Fix failing snapcraft doc build due to https://github.com/canonical/craft-parts/pull/765, which added a reference to an excluded overlays explanation.
Depends on https://github.com/canonical/craft-parts/pull/795
-  Allow numbers in partitions, partition namespaces, and namespaced partitions.
-  Add documentation for chisel and the overlay step
-  Improve README onboarding
Unblocks CRAFT-3043

docs: exclude overlay step, bump craft-parts to 1.34.0

---

tests/spread/extensions/ros2-jazzy-meta-hello/task.yaml
tests/spread/extensions/ros2-jazzy-meta-talker-listener/task.yaml

Enable ROS 2 Jazzy (core24) content-sharing spread tests for arm64 (now that the content sharing snaps are available for that arch).
-----

ci: enable jazzy content sharing arm64 spread test

---

docs/reference/changelog.rst
snapcraft/parts/plugins/python_plugin.py
snapcraft/services/lifecycle.py
tests/spread/core24-suites/environment/test-variables/task.yaml
tests/spread/core24/python-hello/classic/snap/snapcraft.yaml
tests/spread/core24/python-hello/src/hello/__init__.py
tests/spread/core24/python-hello/strict/snap/snapcraft.yaml
tests/spread/core24/python-hello/task.yaml
tests/unit/parts/plugins/test_python_plugin.py
tests/unit/services/test_lifecycle.py

-----
This includes an extra commit for the changelog.  I'm adding this in the merge because `docs/reference/changelog.rst` doesn't exist in the `hotfix/8.3` branch.
(CRAFT-3162)
(CRAFT-3103)

chore(merge): '8.3.2' into 'main'

---

snapcraft/models/project.py
tests/unit/models/test_projects.py

-----
- Allows for digits in component names
- Refactor to use same validation for snap and component names
- Begin snap and component names errors with a lowercase character
Depends on https://github.com/canonical/craft-parts/pull/790
Fixes [LP#2069783](https://bugs.launchpad.net/snapcraft/+bug/2069783)
(CRAFT-3043)

feat: allow numbers in component names

---

snapcraft/commands/remote.py
tests/unit/commands/test_remote.py

-----
Currently, remote-build status goes from "Uploading" to "Stopped".
`BuildState` has a PENDING state that is set but not checked for. Going
from "Uploading" to "Pending" improves status messages significantly.
The output could also say "Needs building" to match the web view, but
"Pending" is more in line with the other single-word outputs.

remote-build: add "Pending" as a possible status output

---

.github/workflows/tics.yaml
requirements-devel.txt
setup.py

fix: use proper environment for tics

---

.github/workflows/cla-check.yaml
.github/workflows/publish.yaml
.github/workflows/spread-scheduled.yaml
.github/workflows/spread.yml
.github/workflows/tox.yaml
spread.yaml
tests/spread/core22/package-repositories/test-multi-keys/snap/snapcraft.yaml
tests/spread/electron-builder/no-template/electron-builder-hello-world/electron-builder.yml
tests/spread/electron-builder/no-template/task.yaml
tests/spread/plugins/craft-parts/build-and-run-hello/flutter-hello/lib/main.dart
tests/spread/plugins/v1/flutter/run/task.yaml
tests/spread/plugins/v1/flutter/snaps/flutter_hello/lib/main.dart
tests/spread/plugins/v1/ruby/snaps/ruby-bundle-install/snap/snapcraft.yaml
tox.ini

-----
6 cherry-picks and 6 new commits to repair CI and spread tests in `hotfix/7.5`.
The readthedocs CI failure is expected as Snapcraft 7 predates readthedocs integration.
Unblocks #4950 and #4936
Unblocks CRAFT-3189

tests: update spread tests in hotfix/7.5

---

docs/requirements.txt
requirements-devel.txt
requirements.txt
setup.py
snapcraft/const.py
snapcraft/services/provider.py
tests/unit/services/test_provider.py

-----
* Forward `http_proxy`, `https_proxy`, and `no_proxy` into core24 build environments
* Add a regression test
* Bump craft-application to 4.1.0

fix(provider): forward proxy variables to core24 build environments

---

docs/explanation/remote-build.rst
docs/reference/commands.rst
snapcraft/application.py
snapcraft/commands/remote.py
snapcraft/models/project.py
tests/spread/core24/remote-build/snaps/platforms/snapcraft.yaml
tests/spread/core24/remote-build/task.yaml
tests/unit/commands/test_remote.py
tests/unit/models/test_projects.py
tests/unit/parts/test_lifecycle.py

-----
* '--build-for' and '--platform' can only be used when 'platforms' and 'architectures' are not defined in the project metadata
* '--platform' cannot be used for core22 snaps
* Add links to documentation for remote-build errors
* Update remote-build documentation
Creates #4992
Fixes #4858 
Fixes #4881
(CRAFT-3070)

fix(remotebuild): parse '--build-for' and '--platform'

---

.github/ISSUE_TEMPLATE/bug.yaml

See: https://github.com/canonical/rockcraft/pull/684
-----

 ci: make snapcraft.yaml render as YAML in bug reports

---

docs/requirements.txt
requirements-devel.txt
requirements.txt
setup.py

-----
The main driver for this update is to require Multipass >= 1.14.1 for `core24` snaps.
- Remove Ubuntu 23.10 (Mantic) support
- Require Multipass>=1.14.1 when launching Ubuntu 24.04 (Noble) VMs
- Improve detection of installed LXD
- Update the link to the network troubleshooting docs
- Add support for Ubuntu 24.10 (Oracular)
(CRAFT-3270)

build(deps): bump craft-providers to 1.24.2

---

requirements-devel.txt
setup.py
snapcraft/commands/remote.py
tests/spread/core24/remote-build/snaps/platforms/snapcraft.yaml
tests/unit/commands/test_remote.py

-----
Launchpad cannot build multiple artifacts on the same build-on architecture and will fail with an esoteric error. 
Snapcraft now checks for the scenario and fails with an informative error before the build begins.
Fixes #4995
(CRAFT-3279)

fix(remotebuild): error early for multiple artifacts per build-on

---

snapcraft/extensions/kde_neon_6.py
tests/unit/extensions/test_kde_neon_6.py

-----
This is a temporary revert of #4884 for `hotfix/8.4` to allow releasing snapcraft 8.4.
See the discussion in #4884 and [this forum post](https://forum.snapcraft.io/t/kde-global-auto-connect-qt-common-themes/40878) for context.

chore(revert): add content interfaces for qt-common-themes

---

docs/reference/commands.rst
snapcraft/cli.py
snapcraft/commands/__init__.py
snapcraft/commands/registries.py
snapcraft/const.py
snapcraft/models/__init__.py
snapcraft/models/assertions.py
snapcraft/services/assertions.py
snapcraft/services/registries.py
snapcraft/services/service_factory.py
snapcraft/store/client.py
tests/unit/commands/test_registries.py
tests/unit/conftest.py
tests/unit/models/test_assertions.py
tests/unit/services/test_assertions.py
tests/unit/services/test_registries.py
tests/unit/store/test_client.py

-----
Add support for the `list-registries` command.
Fixes #5001 
(CRAFT-3295)

feat(registries): add `list-registries` command

---

docs/explanation/remote-build.rst
snapcraft/commands/remote.py
tests/spread/core22/remote-build/snaps/build-for-arg/arguments.txt
tests/spread/core22/remote-build/snaps/build-for-arg/expected-snaps.txt
tests/spread/core22/remote-build/snaps/build-for-arg/snapcraft.yaml
tests/spread/core22/remote-build/task.yaml
tests/spread/core24/remote-build/snaps/build-for-arg/arguments.txt
tests/spread/core24/remote-build/snaps/build-for-arg/expected-snaps.txt
tests/spread/core24/remote-build/snaps/build-for-arg/snapcraft.yaml
tests/spread/core24/remote-build/snaps/platform-arg/arguments.txt
tests/spread/core24/remote-build/snaps/platform-arg/expected-snaps.txt
tests/spread/core24/remote-build/snaps/platform-arg/snapcraft.yaml
tests/spread/core24/remote-build/task.yaml
tests/unit/commands/test_remote.py

-----
Allow comma-separated values for `--build-for` and `--platform`.
Remote build spread tests are successful: https://github.com/canonical/snapcraft/actions/runs/10814283451/job/30000756052
Fixes #4990
(CRAFT-3271)

fix(remotebuild): parse comma-separated architectures

---

HACKING.md
tox.ini

- Remove snapcraft_legacy as an autobuild target, since it was blocking.
- Add temporary documentation to HACKING.md, since it likely won't remain after we impose README standards.
-----
I got tired of checking my notes.

docs: document tox builds

---

docs/requirements.txt
requirements-devel.txt
requirements.txt
tests/spread/core24/npm-reentrant/hello.js
tests/spread/core24/npm-reentrant/package-lock.json
tests/spread/core24/npm-reentrant/package.json
tests/spread/core24/npm-reentrant/snap/snapcraft.yaml
tests/spread/core24/npm-reentrant/task.yaml

This new version fixes a bug on the npm plugin. The bug is caused by the plugin
having state that implicitly needs to be passed from the 'pull' step to the
'build' step. If both are done in a single Snapcraft 'run', then it works fine;
however, running first 'pull' and then 'build' separately trigger the issue -
a failure on the build step.
Ref: https://github.com/canonical/craft-parts/issues/844

build(deps): bump craft-parts 

---

snapcraft/models/project.py
tests/spread/core24/platforms/snaps/implicit-build-for/expected-snaps.txt
tests/spread/core24/platforms/snaps/implicit-build-for/snap/snapcraft.yaml
tests/spread/core24/platforms/task.yaml
tests/unit/models/test_projects.py

-----
* Fixes an issue where the wrong type was used when creating a build plan.
* Adds a unit test and spread test for a failure described in https://forum.snapcraft.io/t/building-snaps/41982

fix: use correct type for `build-on` and `build-for` in build plans

---

requirements-devel.txt
requirements-docs.txt
requirements.txt
snapcraft/application.py
tests/unit/commands/test_lifecycle.py
tests/unit/commands/test_remote.py
tests/unit/test_application.py

fix: override _run_inner instead of run to catch exceptions

---

snapcraft/models/__init__.py
snapcraft/models/assertions.py
tests/unit/models/test_assertions.py

-----
Adds pydantic models for registries.
Fixes #5019
(CRAFT-3332)

feat(models): add registries models

---

requirements-devel.txt
requirements-docs.txt
requirements.txt
setup.py
snapcraft/application.py
tests/unit/test_application.py

-----
* bump craft-application to 4.2.4
* Adds documentation links to `RemoteBuild` and `ESM` errors
* Catches `RemoteBuild` errors rather than raising them as internal errors
- Remote build errors are now a subclass of ``CraftError``.
Fixes #4908
(CRAFT-3101)

fix: catch remote build errors

---

snapcraft/cli.py
snapcraft/commands/__init__.py
snapcraft/commands/registries.py
snapcraft/services/__init__.py
snapcraft/services/assertions.py
snapcraft/services/registries.py
snapcraft/services/service_factory.py
snapcraft/store/client.py
tests/unit/commands/test_registries.py
tests/unit/conftest.py
tests/unit/services/test_assertions.py
tests/unit/services/test_registries.py
tests/unit/store/test_client.py

-----
Supports the first half of the `edit-registries` command where a user can retrieve and edit a registries set.
The second half will be implemented in #5018.
Builds on top of #5049, so ignore the first commit.
I broke this up into 2 commits to make reviewing easier.
Fixes #5020
(CRAFT-3333)

feat: add `edit-registries` command

---

tests/spread/store/validation-sets/editor.sh

-----
[Behind the scenes](https://github.com/canonical/snapcraft/pull/5074/files#diff-610b821ececc50adda118ec968fe837957ad1941ad14c938e7e61830d9b0d929R7-R17), I updated the validation sets spread test to use the `hello-world` snap.
This PR flip-flops the `presence` instead of the `revision`, which should make it a little more robust because it won't depend on a specific revision of the snap being accessible.
Fixes #5053
(CRAFT-3418)

tests: fix validation sets spread test

---

docs/reference/changelog.rst

-----
Cherry-pick 8.3 changelog entries that landed after the `hotfix/8.4` was created.
This fixes a problem in the docs where `latest` has all changelog entries but `stable` is missing 8.3.3 and 8.3.4.
This will need to be done in the future whenever changelog entries are created for older releases.

docs(changelog): cherry-pick 8.3.3 and 8.3.4 release notes

---

snapcraft/commands/remote.py
tests/unit/commands/test_remote.py

-----
Fixes a bug where the remote builder would ignore the user and always clean the launchpad project. 
Also drops some magic values in favor of constants.
(CRAFT-3140)
Fixes #4929

fix(remotebuild): do not auto clean interrupted builds

---

requirements-devel.txt
requirements-docs.txt
requirements.txt
setup.py
snap/snapcraft.yaml

-----
Pending a craft-store release (https://github.com/canonical/craft-store/actions/runs/11130571185)
Cherry-picks #5061, which requires this fix for core20 spread tests to pass.
Fixes #5077
(CRAFT-3514)

build(deps): bump craft-store to 3.0.2

---

requirements-devel.txt
requirements.txt
setup.py
tests/legacy/fake_servers/snapd.py
tests/spread/electron-builder/no-template/electron-builder-hello-world/package.json

-----
This is a dependency update that pulls in new patch releases of internal dependencies and switches to requests-unixsocket2, which unlocks the third commit that updates requests.

Dependency updates for 7.5.6

---

snapcraft_legacy/internal/build_providers/_snap.py
snapcraft_legacy/internal/repo/snaps.py
tests/legacy/unit/build_providers/test_snap.py
tests/legacy/unit/repo/test_snaps.py

-----
Fixes a bug where parallel installations of snapcraft would not work if the snapcraft snap was signed.
Same as #5058, but for `hotfix/7.5`.
I recommend reviewing by commit as the refactor commit is noisy.
Builds on top of https://github.com/canonical/snapcraft/pull/5088
Fixes #4683
Fixes #4927
(CRAFT-3259)

fix: allow parallel installations of signed snapcraft snaps (7.5)

---

docs/reference/plugins.rst
docs/reference/plugins/_python_common.rst
docs/reference/plugins/poetry_plugin.rst
docs/reference/plugins/python_plugin.rst
snapcraft/application.py
snapcraft/parts/plugins/__init__.py
snapcraft/parts/plugins/poetry_plugin.py
snapcraft/parts/plugins/python_common.py
snapcraft/parts/plugins/register.py
snapcraft/services/lifecycle.py
tests/spread/core24/python-hello/poetry/snap/snapcraft.yaml
tests/spread/core24/python-hello/poetry/src/pyproject.toml
tests/spread/core24/python-hello/task.yaml
tests/spread/plugins/craft-parts/build-and-run-hello/poetry-hello/snap/snapcraft.yaml
tests/spread/plugins/craft-parts/build-and-run-hello/poetry-hello/src/hello/__init__.py
tests/spread/plugins/craft-parts/build-and-run-hello/poetry-hello/src/pyproject.toml
tests/spread/plugins/craft-parts/build-and-run-hello/task.yaml
tests/unit/parts/plugins/test_python_plugin.py
tests/unit/test_application.py

The plugin has the same behavior and restrictions as the Python plugin with regards to base-dependent behavior, symlink handling, etc.
Therefore, this common behavior is extracted into a new "python_common" module, used by both plugins. This approach is also taken for the reference docs - the requirement of staging a Python interpreter (or not) is the same for both plugins.
Enabled for core22 and core24.
Fixes #5025
-----

feat: add Snapcraft-specific Poetry plugin

---

requirements-devel.txt
requirements-docs.txt
requirements.txt
setup.py
snapcraft_legacy/internal/build_providers/_snap.py
snapcraft_legacy/internal/repo/snaps.py
tests/legacy/unit/build_providers/test_snap.py
tests/legacy/unit/repo/test_snaps.py

-----
Fixes a bug where parallel installations of snapcraft would not work if the snapcraft snap was signed.
I recommend reviewing by commit as the refactor commit is noisy.
Fixes #4683
Fixes #4927
(CRAFT-3259)

fix: allow parallel installations of signed snapcraft snaps

---

tests/spread/store/registries/editor.sh
tests/spread/store/registries/task.yaml
tests/spread/store/validation-sets/task.yaml

-----
Add a spread test for `edit-registries` and `list-registries`.
Fixes #5054
(CRAFT-3419)

tests: add spread tests for registries

---

snapcraft/application.py
snapcraft/commands/validation_sets.py
snapcraft/linters/linters.py
tests/unit/linters/test_linters.py
tests/unit/services/test_package.py

-----
Fixes a handful of deprecation warnings from libraries.

chore: fix deprecation warnings

---

docs/reference/changelog.rst
requirements-devel.txt
requirements-docs.txt
requirements.txt
setup.py
tests/legacy/fake_servers/snapd.py
tests/unit/parts/plugins/test_python_plugin.py

-----
Adds 8.4.2 release notes for next week.
Also adds 7.5.7 release notes, as we don't have a better solution for old releases at the moment.
Fixes [CVE-2024-35195](https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56)
Fixes #5079

build(deps): switch to requests-unixsocket2, release 8.4.2

---

snapcraft/models/project.py
tests/unit/models/test_projects.py

-----
Adds support for `standard` and `kernel-modules` component types.
(CRAFT-3520)
Fixes #5089

feat: support standard and kernel-modules

---

requirements-devel.txt
requirements.txt

-----
Snapcraft 7 is failing to build on non-amd64 architectures for the same reason that snapcraft 8 failed.  The fix is simply updating to the version of craft-store with the fix.
The error is:
```
RuntimeError: OpenSSL 3.0's legacy provider failed to load. This is a fatal error by default, but cryptography supports running without legacy algorithms by setting the environment variable CRYPTOGRAPHY_OPENSSL_NO_LEGACY. If you did not expect this error, you have likely made a mistake with your OpenSSL configuration.
```
Full logs [here](https://launchpadlibrarian.net/752714447/buildlog_snap_ubuntu_focal_ppc64el_snapcraft-7-hotfix_BUILDING.txt.gz).
There aren't any concerning [changes](https://canonical-craft-store.readthedocs-hosted.com/en/latest/changelog/) between 2.5.0 and 2.6.2, so I'm …

build(deps): bump craft-store to 2.6.2

---

requirements-devel.txt
requirements-docs.txt
requirements.txt
setup.py
tests/spread/core24-suites/environment/test-variables/task.yaml

-----
Fixes https://github.com/canonical/snapcraft/issues/4785
(CRAFT-3526)

bump craft-application, check parallel build count in project metadata

---

snapcraft/commands/validation_sets.py
snapcraft_legacy/storeapi/v2/validation_sets.py
tests/legacy/unit/store/v2/test_validation_sets.py
tests/unit/commands/test_validation_sets.py

-----
Hello! This should enable using `edit-validation-sets` with components. Let me know if I'm missing any testing. I don't see any tests that specifically test the allowed format of validation sets, so I don't know if that is something that we need/want to be added.

feat: allow specifying components when using edit-validation-sets

---

requirements-devel.txt
requirements-docs.txt
requirements.txt
tests/spread/core24/package-repositories/task.yaml
tests/spread/core24/package-repositories/test-key-conflict/snapcraft.yaml

This update fixes LP#2083013, where some package-repositories declarations could conflict with default sources present in Noble.
-----

build(deps): bump craft-archives

---

docs/reference/changelog.rst

-----
Adds release notes for 7.5.8 and 8.4.4.

docs(changelog): add 8.4.4 and 7.5.8 release notes

---

snapcraft/commands/legacy.py
snapcraft/commands/manage.py
snapcraft/commands/status.py

Some of the commands auto-generated docs were not rendered correctly, this PR addresses that
Before:
After:

fix(docs): display examples correctly in RTD

---

snap/local/craft.git
snap/snapcraft.yaml
tests/spread/core24/craftgit/snap/snapcraft.yaml
tests/spread/core24/craftgit/task.yaml

Adds a `git` binary as a `craft.git`, that'll be used by the `craft` libraries for the operation which require git client.
(CRAFT-3547)

feat(snap): add git as craft.git to snapcraft

---

docs/howto/code/components-organize/snapcraft.yaml

-----
Minor fix.  In #5174, I updated the type in `docs/howto/code/components/snapcraft.yaml` but not `docs/howto/code/components-organize/snapcraft.yaml`.

docs: fix component type in the howto

---

pyproject.toml

There were two fully deprecated rules being selected for in Ruff's lint rules, as well as an invalid variable name for Black's config. This pull corrects both errors.
-----
Deleted lint rules: [ANN101](https://docs.astral.sh/ruff/rules/missing-type-self/), [ANN102](https://docs.astral.sh/ruff/rules/missing-type-cls/)

chore: fix small pyproject.yaml errors

---

docs/reference/commands.rst
requirements-devel.txt
snapcraft/cli.py
tests/spread/store/registries/task.yaml
tests/unit/commands/test_registries.py

-----
Unregister the `list-registries` and `edit-registries` commands in preparation for renaming them to `list-confdb` and `edit-confdb`.
I retained as many tests as possible to prevent code rot.
(CRAFT-3785)

chore!: unregister registries commands

---

.github/ISSUE_TEMPLATE/bug.yaml

From my experiments on my repo:
https://github.com/locnnil/ci-exp/issues/new/choose
Bullets works using `*` (along with indentation) instead of `-`
-----

chore(.github/ISSUE_TEMPLATE/bug.yaml): fix broken bullet points

---

docs/explanation/components.rst
docs/howto/code/basic/task.yaml
docs/howto/code/components-organize/task.yaml
docs/howto/code/components/task.yaml
docs/howto/components.rst
docs/reference/changelog.rst
docs/reference/channels.rst
docs/reference/snap-build-process.rst
snapcraft/pack.py
snapcraft/parts/extract_metadata.py

-----
Renames 2 commonly used terms in snapcraft to US English, artefact and organise.

style: UK to US English

---

docs/reference/changelog.rst

-----
Add a [changelog entry](https://canonical-snapcraft--5215.com.readthedocs.build/en/5215/reference/changelog/) for 8.6.0.

docs(changelog): add 8.6.0

---

docs/reference/code/extensions/kde-neon-6-extension-keysmith-expanded.diff
docs/reference/code/extensions/kde-neon-extension-kcalc-expanded.diff
docs/reference/extensions/index.rst
docs/reference/extensions/kde-neon-extensions.rst

-----
For review, please focus on `docs/reference/extensions/kde-neon-extensions.rst`. The other files will be merged through another PR.

docs: migrate kde neon extensions

---

docs/conf.py
docs/redirects.txt
requirements-docs.txt
setup.py

Redirects are maintained manually in `conf.py`.
-----

feat(docs): add redirects

---

docs/explanation/remote-build.rst
docs/reference/changelog.rst
requirements-devel.txt
requirements-docs.txt
requirements.txt
setup.py

-----
Pulls in fixes from https://github.com/canonical/craft-application/pull/615, which fixes a bug where the remote-builder would create a public repository and recipe, even when the project is private.
Fixes #5221 
(CRAFT-4035)

fix(remotebuild): use the project's privacy for repos and recipes

---

extensions/desktop/kde-neon-6/launcher-specific

-----
This line was added in #4823 in https://github.com/canonical/snapcraft/pull/4823/commits/d8013464002b93d613f7e2955ca707023777919c
However, the `export` was missing in the original commit.  This error was picked up by shellcheck in #5225.  I'm moving it into a separate PR for trackability.

fix(extensions): resources path for QtWebEngineProcess on kde-neon-6

---

docs/reference/changelog.rst
pyproject.toml
uv.lock

---
Brings 8.6.2 into main.  I had to tweak the craft-providers bump, since `main` now has the starbase and uv.

chore(merge): 8.6.2 into main

---

.github/workflows/release-publish.yaml

---
We don't need to publish wheels for snapcraft, but we can create a pre-release, just like [rockcraft](https://github.com/canonical/rockcraft/commit/6619134b2c4177aa46600329a324a963c04b5179).

ci: don't publish a wheel

---

docs/explanation/remote-build.rst
snapcraft/commands/remote.py
tests/unit/commands/test_remote.py
tests/unit/models/test_projects.py
tests/unit/test_application.py
uv.lock

refactor: use craft-application's remote-build

---

docs/release-notes/snapcraft-8-7.rst
snapcraft/parts/plugins/flutter_plugin.py
tests/unit/parts/plugins/test_flutter_plugin.py

---
This PR uses the [workaround suggested here](https://github.com/flutter/flutter/issues/163308#issuecomment-2661479464). It's a dirty workaround, but it seems like the Flutter development team is going to fix this issue as a bug so this should only be around until upstream is fixed.
Closes #5258 
CRAFT-4149.

fix: correct git errors in flutter plugin

---

.gitignore
snapcraft/parts/extract_metadata.py
snapcraft/parts/grammar.py
snapcraft/parts/plugins/__init__.py
snapcraft/parts/plugins/flutter_plugin.py
snapcraft/parts/plugins/matter_sdk_plugin.py
snapcraft/parts/update_metadata.py
tests/unit/parts/plugins/test_colcon.py
tests/unit/parts/plugins/test_python_plugin.py
tests/unit/parts/test_desktop_file.py
tests/unit/parts/test_yaml_utils.py

---
The .gitignore was ignoring the lifecycle `parts/` directory, but it had its own `parts/` directories (e.g. `snapcraft/parts/`) that were getting ignored as a side-effect. This also meant that Ruff wasn't checking those directories for formatting/linting errors.

chore: fix gitignore entry

---

tests/conftest.py

---
The legacy tests are rarely wanted and are, on average, much slower than any of the modern tests. This PR marks them all as slow tests for the purposes of `make test-fast`.

test: mark all legacy tests as slow

---

spread.yaml

---
The multipass backend had a switch that would cause it to pull a newer image than desired. This PR forces it to only use the image explicitly requested by task.yaml files. Tested locally, works for selecting both 22.04 and 24.04 images with spread.

test: fix spread.yaml multipass backend

---

docs/explanation/remote-build.rst
docs/release-notes/snapcraft-8-7.rst
snapcraft/commands/remote.py
tests/spread/core22/remote-build/snaps/build-for-with-archs/arguments.txt
tests/spread/core22/remote-build/snaps/build-for-with-archs/expected-snaps.txt
tests/spread/core22/remote-build/snaps/build-for-with-archs/snapcraft.yaml
tests/spread/core24/remote-build/snaps/build-for-with-platforms/arguments.txt
tests/spread/core24/remote-build/snaps/build-for-with-platforms/expected-snaps.txt
tests/spread/core24/remote-build/snaps/build-for-with-platforms/snapcraft.yaml
tests/unit/commands/test_remote.py

---
This PR updates Snapcraft to pass `build-on` architectures to Launchpad rather than the `build-for` architectures.  It updates the spread tests to exercise this.
Benefits:
* Previously, a snap with `build-for: [all]` would build on `amd64`.  Now it builds on one of the `build-on` architectures in the `snapcraft.yaml`.
* Cross-compiling works with remote builds.
This is possible due to the following constraints:
* Snapcraft only allows one artifact to be remotely built on each `build-on` architecture.
* Launchpad accepts a list of architectures where to build an artifact and choose one architecture from that list.
Spread tests: https://github.com/canonical/snapcraft/actions/runs/13401419675
Fixes #4996 
(CRAFT-3280)

fix(remotebuild): don't fail when cross-compiling

---

docs/release-notes/snapcraft-8-7.rst

---
I got mixed up with the new release notes and which version of Snapcraft was going to get #5265.  It's now going into Snapcraft 8.8, not 8.7, so I need to drop this from the release notes.
Fortunately, this isn't in the tagged [8.7.0](https://canonical-snapcraft.readthedocs-hosted.com/en/8.7.0/release-notes/snapcraft-8-7.html) or [8.7.1](https://canonical-snapcraft.readthedocs-hosted.com/en/8.7.1/release-notes/snapcraft-8-7.html) release notes.

docs(release-notes): update remote-build notes

---

pyproject.toml
uv.lock

---
Fixes a bug where the final lines of stdout or stderr may not be logged (https://github.com/canonical/craft-parts/issues/1025).

build(deps): bump craft-parts to 2.4.3

---

snapcraft/commands/names.py
tests/unit/commands/test_names.py

fix: give `list` and `list-registered` commands permanent deprecation warnings

---

docs/how-to/debug/disable-a-linter.rst
docs/how-to/debug/index.rst
docs/how-to/index.rst
docs/reference/linters.rst

Part of the migration effort, but this one involved moving a section out of a page already migrated.
---

docs: add 'disable a linter'

---

docs/release-notes/snapcraft-8-7.rst
snapcraft_legacy/plugins/v2/crystal.py

fix: properly quote environment variables in crystal plugin

---

docs/explanation/remote-build.rst
docs/release-notes/snapcraft-8-7.rst
snapcraft/commands/remote.py
tests/spread/core24/remote-build/snaps/build-for-with-shorthand-platforms/arguments.txt
tests/spread/core24/remote-build/snaps/build-for-with-shorthand-platforms/expected-failure.txt
tests/spread/core24/remote-build/snaps/build-for-with-shorthand-platforms/snapcraft.yaml
tests/spread/core24/remote-build/task.yaml
tests/unit/commands/test_remote.py

---
Raises an early error if `--build-for` is used in combination with shorthand `platforms` entries in the project file.
Launchpad fails with an unfriendly error, so Snapcraft now fails early with a friendlier error.
This is designed so that it can be quickly removed once the upstream bug in Launchpad is resolved.
Remote build spread test: https://github.com/canonical/snapcraft/actions/runs/14045570296/job/39326652643
Fixes #5270
(CRAFT-4186)

fix(remote): error early for invalid platform usage

---

docs/release-notes/snapcraft-8-7.rst

---
* organize bug fixes by patch release
* changes the wording of the crystal plugin to match the other bug fixes - they describe the buggy behavior, not the new behavior
* drops the "upcoming fixes" section, as the only fix remaining became more than a bug fix and was moved to Snapcraft 8.8.

docs(release-notes): organize bug fixes by patch release

---

docs/conf.py
docs/reference/build-environment-options.rst
docs/reference/index.rst

---
Migrates the build environment options reference section from [this page](https://snapcraft.io/docs/build-options#p-58836-build-environment-options).

docs: migrate build environment reference page

---

tests/spread/store/basic-workflow/task.yaml
tests/spread/store/confdbs/task.yaml
tests/spread/store/validation-sets/task.yaml

---
Only the second commit needs to be reviewed (the tiny one).
All of snapcraft's secrets were re-provisioned from Sergio's credentials to mine and it broke some of the store tests.
This PR adjusts the tests and the secrets. 
| failing test                                     | fix                                                                        |
| -------------------------------------------- | ---------------------------------------------------------------------------- |
| tests/spread/store/basic-workflow:candid | use the testing snap for `snapcraft metrics`                                                                 |
| tests/spread/store/basic-workflow:legacy     | use base64 encoding for the credentials       |
| tests/spread/store/basic-workflow:ubuntu_one | use the …

test(spread): update store tests

---

docs/conf.py
docs/how-to/debug/index.rst
docs/how-to/debug/use-the-library-linter.rst

---
Migrates the page at https://snapcraft.io/docs/linters-library under the "linter warnings" header.
CRAFT-4235.

docs: migrate library linting tips

---

pyproject.toml
uv.lock

---
Bumps craft-platforms to 0.7.0.
Fixes:
* tests/spread/core24/chisel-base
* tests/spread/core-devel/base-snap

build(deps): bump craft-platforms to 0.7.0

---

snapcraft/extensions/_utils.py
tests/unit/extensions/test_extensions.py

---
Unit test fixes for `expand_extensions()`.  This ended up being simpler than expected, as `expand_extensions()` and `apply_root_packages()` are working as expected for core22 and core24 and no code changes were needed.
(CRAFT-4416)

test: fix extension tests

---

snapcraft/services/__init__.py
snapcraft/services/buildplan.py
snapcraft/services/service_factory.py
tests/unit/conftest.py
tests/unit/services/test_buildplan.py

---
* Adds a `BuildPlan` service
* Adds a new `create_launchpad_build_plan()` method
* This will be used by the remote-build command in CRAFT-4415
* Reworks the unit tests to exercise the new method and drops all `xfail`s 
Creates https://github.com/canonical/craft-application/issues/719
(CRAFT-4417)

feat: add a BuildPlan service

---

docs/release-notes/changelog.rst

---
Adds a notice that the changelog has been superseded by the release notes, based on feedback from @simondeziel.

docs: link from changelog to release notes

---

snapcraft/services/project.py
tests/unit/services/test_lifecycle.py
tests/unit/test_application.py

---
Minor improvement to keep snapcraft from failing early on incorrect base definitions before getting a chance to raise user-friendly errors.
(SNAPCRAFT-313)

fix: don't fail when checking the base

---

snapcraft/commands/remote.py
tests/unit/commands/test_remote.py
tests/unit/conftest.py
tests/unit/services/test_package.py

---
* Uses the new `get_launchpad_build_plan()` added in #5368.
* Removes `xfails` from the remote build unit tests.
Passing remote build spread tests: https://github.com/canonical/snapcraft/actions/runs/14386834165/job/40345445458
(SNAPCRAFT-310)

chore(remotebuild): use new build planner

---

spread.yaml

ci: lock to 24.04 amd64 image on google backend

---

pyproject.toml
uv.lock

---
Updates craft-application to fix:
- spread test failures related to `snapcraft prime` (https://github.com/canonical/craft-application/issues/716)
- pygit2 failing to import on systems without core22 installed
- possibly the spread test failure for `snapcraft test`
Fixes #5321 
(SNAPCRAFT-932)

build(deps): bump craft-application to 5.0.3

---

docs/release-notes/snapcraft-8-8.rst
snapcraft_legacy/internal/meta/_manifest.py
tests/legacy/unit/meta/test_meta.py
tests/spread/core20/manifest/snapcraft.yaml
tests/spread/core20/manifest/task.yaml
tests/spread/core24-suites/manifest/manifest-creation/task.yaml

---
Fixes a regression where core20 snaps would have an invalid timestamp for `snapcraft-started-at` in their `snap/manifest.yaml`.
This regression occurred when we replaced a [deprecated `datetime.utcnow()` call](https://github.com/canonical/snapcraft/commit/f24c83d6b6e218cf18fe8c0380f964ae2ed09115#diff-fc9be1807504ea06b6c1703a5d6112665cccf6a14148fdfab685188ecfeda857L69).
core22 and core24 are unaffected, but I added regression tests to ensure they don't break in the future.
Fixes #5413

fix: format snapcraft-started-at timestamps

---

snapcraft/extensions/gnome.py
snapcraft/extensions/kde_neon.py
snapcraft/extensions/kde_neon_6.py
snapcraft/extensions/kde_neon_qt6.py
tests/unit/extensions/test_gnome.py
tests/unit/extensions/test_kde_neon.py
tests/unit/extensions/test_kde_neon_6.py
tests/unit/extensions/test_kde_neon_qt6.py

---
This reverts #5395.
The purpose of #5395 is good, but it's missing logic for parts that run after the extension's part, such as a "clean up" part. The logic should be to only add parts to the extension's `after` key if they don't depend on the extension's part, directly or indirectly.
For example, here are snaps that would break.  They have parts that run after the [gnome](https://github.com/wasta-linux/lameta-snap/blob/4e995848cd199c951cef6f2ea8d5c6e8b1ff689e/snap/snapcraft.yaml#L124), [ros](https://github.com/canonical/gazebo_snap/blob/8db26ff3ab4dc156dad17730f4e7c2a5f969dc24/snap/snapcraft.yaml), and [kde](https://github.com/canonical/gazebo_snap/blob/8db26ff3ab4dc156dad17730f4e7c2a5f969dc24/snap/snapcraft.yaml#L65) extensions.
We're cutting an 8.9 release so this feature needs to …

chore(revert): "fix: add all parts as a dep of extension part (#5395)"

---

pyproject.toml
snapcraft/services/init.py
snapcraft/services/package.py
snapcraft/templates/test/spread.yaml.j2
tests/spread/core24/craft-test/task.yaml
tests/spread/core24/init-test/task.yaml

Craft-application needs a map of resource names to filenames to set
environment variables exported to the testing service. This allows the
user to use the variables to refer to the newly created artifact and
resource files in test scriptlets.
---

feat(testing): add names to resource files

---

uv.lock

---
Sync the lock file after craft-app's minimum version was bumped in #5438.
Not doing this messes up the versioning of snapcraft and shows `8.9.0.post0+dirty` instead of `8.9.0`.

build(deps): sync lockfile

---

snapcraft/templates/test/spread.yaml.j2
tests/spread/core24/init-test/task.yaml

Set --jailmode when installing the generated artifact in the template
spread.yaml file, so it will work with both devmode and strict
confinement settings in the snapcraft.yaml file.
---

fix(testing): use jailmode in template spread.yaml

---

docs/conf.py
docs/reference/hooks.rst
docs/reference/index.rst

---
Migrate https://snapcraft.io/docs/supported-snap-hooks and https://snapcraft.io/docs/snapcraft-hook-support to [RTD](https://canonical-snapcraft--5463.com.readthedocs.build/en/5463/reference/hooks/).
(SNAPCRAFT-395)

docs: migrate 'hooks'

---

docs/reference/index.rst
docs/reference/project-file/index.rst

---
Migrates https://snapcraft.io/docs/build-configuration and the "snapcraft.yaml" section from https://snapcraft.io/docs/how-snapcraft-builds to [RTD](https://canonical-snapcraft--5466.com.readthedocs.build/en/5466/reference/project-file/).
I added the content to the project file index since it serves as a brief overview and didn't fit perfectly into either of the subpages.
(SNAPCRAFT-394)

docs: migrate 'snapcraft.yaml'

---

.readthedocs.yaml
docs/conf.py
docs/reference/plugins.rst
docs/reference/plugins/matter_sdk_plugin.rst

---
* Renames the matter sdk docs to use underscores to match the other plugins in Snapcraft and Craft Parts.
* Remove migrated docs from the ignored list.  Again, the [build on RTD](https://app.readthedocs.com/projects/canonical-snapcraft/builds/3014663/) doesn't fail on these warnings but fails locally:
* Fail on warnings so we catch this in the future.

docs: fix RTD build

---

README.md
SECURITY.md
docs/conf.py
docs/release-notes/snapcraft-8-9.rst
snap/snapcraft.yaml
snapcraft/application.py

I ran the tests locally, and didn't see any errors related to the domain.
Also, fixes some links in the README.
---
---

docs(config): switch to ubuntu.com domain

---

.github/workflows/spread.yml
tests/spread/general/ua_token/task.yaml

---
Fixes a CI failure where the spread tests would fail locally or whenever someone made a PR from their forked repo of Snapcraft.
For completeness, I tested this both from a fork and from the main repo (#5473).

test: skip ua test outside of main repo

---

docs/explanation/cryptography.rst
docs/explanation/index.rst

---
Adds an [explanation of cryptography](https://canonical-ubuntu-documentation-library--5478.com.readthedocs.build/snapcraft/5478/explanation/cryptography/) used in Snapcraft.
This doc is tricky to organize because there are 3 overlapping codebases used to build snaps (depending on the base), 2 codebases for interacting with the store, and 2 codebases for remote builds.  The store and remote build codebases aren't tied to any particular base.
I've reused as much upstream documentation is possible.
(SNAPCRAFT-1114)

docs: add explanation for cryptography

---

Makefile

---
Since switching to the self-hosted runners, tests have been breaking because patchelf wasn't installed on them. For example, see [this workflow](https://github.com/canonical/snapcraft/actions/runs/14932815042). This PR just adds the apt package to be installed during the creation of the development environment.

build: add patchelf to make dependencies

---

osv-scanner.toml

---
Removes an OSV scanner config that was both resolved and expired.

ci: remove config for osv scanner

---

docs/release-notes/snapcraft-8-9.rst
snapcraft/application.py
snapcraft/services/project.py
tests/spread/core22/project-variables/expected.txt
tests/spread/core22/project-variables/snapcraft.yaml
tests/spread/core22/project-variables/task.yaml
tests/spread/core24/project-variables/expected.txt
tests/spread/core24/project-variables/snapcraft.yaml
tests/spread/core24/project-variables/task.yaml

---
Fixes a bug where project variables weren't being evaluated in project files.
This was a mistake from the craft-application 5 rebase and refactor. It's addressed upstream in https://github.com/canonical/craft-application/pull/762.
Fixes #5491
(SNAPCRAFT-1131)

fix: evaluate variables in project file

---

snapcraft/models/assertions.py
snapcraft/services/confdbschemas.py
tests/unit/models/test_assertions.py
tests/unit/services/test_confdbs.py

This adds support for the optional `summary` field in the `confdb-schema` assertion, both at the top level and under individual views, in accordance with the updated specification.
An existing unit test was also modified to cover these new optional fields.
Fixes: #5442

feat(confdb-schema): support optional summary fields

---

docs/redirects.txt
snapcraft/commands/core22/lifecycle.py
snapcraft/commands/extensions.py
snapcraft/commands/lifecycle.py
snapcraft/commands/names.py
snapcraft/commands/plugins.py
snapcraft/commands/status.py
snapcraft/commands/upload.py
snapcraft/const.py
snapcraft/parts/lifecycle.py
tests/unit/commands/test_lifecycle.py
tests/unit/commands/test_list_extensions.py
tests/unit/commands/test_names.py
tests/unit/commands/test_plugins.py
tests/unit/commands/test_status.py
tests/unit/commands/test_upload.py
tools/docs/gen_cli_docs.py

---
* Adds a uniform deprecation warning for all deprecated commands.
* Hides and redirects reference pages for hidden commands.
* A deprecation warning for the default command (`snapcraft` defaulting to `snapcraft pack`). See #5525.
Fixes #5428
(SNAPCRAFT-1048)

chore: add deprecation warnings for hidden commands

---

docs/explanation/remote-build.rst
snapcraft_legacy/cli/remote.py
tests/legacy/unit/commands/test_remote.py

---
Adds a deprecation notice for core22 snaps using the legacy remote builder.
Fixes #5427 
(SNAPCRAFT-1045)

chore: add deprecation warning for legacy remote builder

---

snapcraft/templates/ros2/snap/snapcraft.yaml.j2
tests/spread/general/init/task.yaml

Add a `ros2` init profile that create a small, yet functional, ROS 2 snap example.
---

Add ros2 profile

---

snapcraft_legacy/cli/_options.py
snapcraft_legacy/cli/_runner.py

---
We updated click in https://github.com/canonical/snapcraft/pull/5505 and now it complains when the same parameter is registered more than once:
```
/snap/snapcraft/x6/lib/python3.12/site-packages/click/core.py:1193: UserWarning: The parameter --debug is used more than once. Remove its duplicate as parameters should be unique.
parser = self.make_parser(ctx)
/snap/snapcraft/x6/lib/python3.12/site-packages/click/core.py:1193: UserWarning: The parameter --verbose is used more than once. Remove its duplicate as parameters should be unique.
parser = self.make_parser(ctx)
/snap/snapcraft/x6/lib/python3.12/site-packages/click/core.py:1193: UserWarning: The parameter -v is used more than once. Remove its duplicate as parameters should be unique.
parser = self.make_parser(ctx) …
```

chore(snapcraft_legacy): deduplicate parameter registration

---

snapcraft_legacy/internal/states/_global_state.py
tests/unit/test_application.py
tests/unit/test_providers.py

---
Fixes some deprecation warnings before they become deprecation errors. Two of the fixes were very simple, but the one involving the context manager was a little bit messier.
In short, the test mocking setup was setting the return value of a context manager to a simple `Path`, when it needed to be a generator object that supported the `__enter__()` method. This wasn't an issue previously since `Path` just did a no-op as a context manager, but now it needs to be correct.
Closes #5539.
SNAPCRAFT-1159

chore: resolve deprecation warnings

---

pyproject.toml
snapcraft/store/_legacy_account.py
tests/unit/store/test_legacy_account.py
uv.lock

---
Invalid text in `SNAPCRAFT_STORE_CREDENTIALS` could cause a `UnicodeDecodeError`, which would be raised as an internal error: 
```
snapcraft internal error: UnicodeDecodeError('utf-8', b'\x9d\xfa(', 0, 1, 'invalid start byte')
```
Now, this is caught and raised as a user-friendly error.
Related: https://github.com/canonical/craft-store/pull/287
Fixes #5161

fix(store): catch credential decoding errors

---

snapcraft/commands/validation_sets.py
snapcraft/services/assertions.py
tests/spread/store/validation-sets/editor.sh
tests/unit/commands/test_validation_sets.py
tests/unit/services/test_assertions.py
tests/unit/store/test_legacy_account.py

---
This PR adds a warning when a user doesn't increment the sequence in a validation set.
I recommend reviewing per-commit.
The first commit does this with a new function `_validate_assertion()` and passing kwargs to the new function.
The second commit adds the same infrastructure to the abstract `AssertionService`, which currently isn't used for validation sets.  There are no user-facing changes here, but I'm doing this now while it's fresh in my mind. This will make creating a `ValidationSetsService` easier when we complete https://github.com/canonical/snapcraft/issues/5337.
Fixes #5367
(SNAPCRAFT-811)

feat(validation-sets): warn when the sequence isn't incremented

---

docs/how-to/crafting/enable-classic-confinement.rst

`takes takes` -> `takes`
Not bothering to do these since this is a simple typo fix:
---

fix typo in enable-classic-confinement.rst

---

docs/conf.py

---
* Adds deprecated command pages to `exclude_patterns`

docs: ignore deprecated command pages

---

docs/explanation/components.rst
docs/how-to/code/integrations/example-python-recipe.yaml
docs/how-to/code/integrations/example-rust-recipe.yaml
docs/how-to/crafting/select-architectures.rst
docs/how-to/debugging/debug-a-snap.rst
docs/how-to/integrations/craft-a-cross-compiled-app.rst
docs/how-to/integrations/craft-a-gtk2-app.rst
docs/how-to/integrations/craft-a-gtk3-app.rst
docs/how-to/integrations/craft-a-gtk4-app.rst
docs/how-to/integrations/craft-a-qt5-kde-app.rst
docs/how-to/integrations/craft-an-ros-2-app.rst
docs/reference/extensions/env-injector-extension.rst
docs/release-notes/changelog.rst
docs/release-notes/index.rst

Fixing issue from task 244, from Open Documentation Academy
Replacing words for standardization
https://github.com/canonical/open-documentation-academy/issues/244
---

docs: switch from UK to US spellings

---

.github/release-drafter.yml
.github/workflows/release-drafter.yaml

---
Re-adds the release drafter, which should make it easier to get a list of contributors for future releases.

ci: add release-drafter workflow

---

snapcraft/parts/plugins/_ros.py
snapcraft_legacy/plugins/v2/_ros.py

Ros plugin: handle stderr separated from stdout, fixes #5600

---

docs/index.rst

We had a change of heart about the position of the page in the TOC. We want release notes to always be the final item.
---
---

docs: place 'about docs' above 'release notes' in toc

---

snapcraft/application.py
tests/unit/commands/test_init.py

---
Fixes the crash when running `snapcraft init` in a directory with an empty `snapcraft.yaml`:
```
$ cd `mktemp -d`
$ touch snapcraft.yaml
$ snapcraft init
Traceback (most recent call last):
File "/snap/snapcraft/15369/bin/snapcraft", line 8, in <module>
sys.exit(main())
^^^^^^
File "/snap/snapcraft/15369/lib/python3.12/site-packages/snapcraft/application.py", line 464, in main
app = create_app()
^^^^^^^^^^^^
File "/snap/snapcraft/15369/lib/python3.12/site-packages/snapcraft/application.py", line 432, in create_app
app = Snapcraft(
^^^^^^^^^^
File "/snap/snapcraft/15369/lib/python3.12/site-packages/snapcraft/application.py", line 99, in __init__
self._known_core24 = self._get_known_core24()
^^^^^^^^^^^^^^^^^^^^^^^^
File "/snap/snapcraft/15369/lib/python3.12/site-packages/snapcraft/applic …
```

fix: snapcraft init crash when snapcraft.yaml exists but is empty

---

docs/release-notes/snapcraft-8-11.rst

---
Fixes 2 typos in the 8.11 release notes.

docs: fix typos in release notes

---

docs/release-notes/snapcraft-8-11.rst
snapcraft_legacy/cli/_options.py
snapcraft_legacy/cli/assertions.py
snapcraft_legacy/cli/discovery.py
snapcraft_legacy/cli/extensions.py
snapcraft_legacy/cli/help.py
snapcraft_legacy/cli/remote.py
snapcraft_legacy/cli/store.py
snapcraft_legacy/cli/version.py
tests/legacy/unit/commands/test_create_key.py
tests/legacy/unit/commands/test_extensions.py
tests/legacy/unit/commands/test_gated.py
tests/legacy/unit/commands/test_help.py
tests/legacy/unit/commands/test_list_keys.py
tests/legacy/unit/commands/test_list_plugins.py
tests/legacy/unit/commands/test_list_validation_sets.py
tests/legacy/unit/commands/test_metrics.py
tests/legacy/unit/commands/test_promote.py
tests/legacy/unit/commands/test_register_key.py
tests/legacy/unit/commands/test_remote.py
tests/legacy/unit/commands/test_set_default_track.py
tests/legacy/unit/commands/test_sign_build.py
tests/legacy/unit/commands/test_upload_metadata.py
tests/legacy/unit/commands/test_validate.py
tests/legacy/unit/commands/test_version.py

---
Adds support for verbosity args in non-lifecycle commands in snapcraft legacy.
Verbosity gets parsed by modern snapcraft, so this PR allows legacy commands to accept and ignore verbosity args.
Fixes https://github.com/canonical/snapcraft/issues/5298

feat(snapcraft_legacy): support verbosity args in non-lifecycle commands

---

snapcraft_legacy/plugins/v2/_plugin.py
snapcraft_legacy/plugins/v2/meson.py

The out_of_source_build() property, as defined, returns a Literal(false), but when overriden by the meson plugin, it returns a Literal(true), which strictly speaking is incompatible, as shown in the python module for Code.
This patch fixes this by specifying that the property is a boolean.
---

fix: remove python complain

---

snapcraft/linters/metadata_linter.py
tests/unit/linters/test_metadata_linter.py

---
Fixes #5794. Does a little fly-by typing work while I'm in this file, as well.

fix: properly ignore source-code field in metadata linter
