canonical/snapcraft

- snapcraft/sources.py
Many people use git over SSH, so using "git@" to identify a git repository helps the developer a little bit.
> Added 'git@' to the automatic identification of the source

- bin/snapcraft
- bin/snapcraft-coverage
- examples/py2-project/sha3sum.py
- examples/py3-project/sha3sum.py
- integration-tests/manage.py
- setup.py
- snapcraft/__init__.py
- snapcraft/cmds.py
- snapcraft/common.py
- snapcraft/dirs.py
- snapcraft/lifecycle.py
- snapcraft/plugins/catkin.py
- snapcraft/plugins/copy.py
- snapcraft/plugins/go.py
- snapcraft/plugins/python3.py
- snapcraft/plugins/qml.py
- snapcraft/sources.py
- snapcraft/tests/test_copy_plugin.py
- snapcraft/tests/test_lifecycle.py
- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
> Replaced the double quotes by single quotes on strings.

- .travis.yml
- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
When a catking package is not found, the incorrect exception is captured.
This fixes issue #66
> Catch the correct exception for missing catkin pkg

- snapcraft/plugins/qml.py
We can't have any ubuntu packages here, they start to pull in all the desktop frameworks. These three quite literally double the size of the snap and the number of packages.
> Remove ubuntu pacakges from the list

- snapcraft/sources.py
- snapcraft/tests/test_sources.py
Wrapping the source management commands in the env can lead to linking
to the wrong libraries such as openssl brought in by stage-packages for
a different release.
> Don't wrap the vcs commands in the env

- snapcraft/cmds.py
- snapcraft/repo.py
Set recommends to false for both build and stage packages to have consistency with launchpad builders
Closed Issue #42
> Do not install recommends for build or stage pkgs

- integration-tests/units/jobs.pxu
- snapcraft/__init__.py
- snapcraft/common.py
- snapcraft/plugins/autotools.py
- snapcraft/plugins/catkin.py
- snapcraft/plugins/cmake.py
- snapcraft/plugins/make.py
- snapcraft/plugins/python2.py
- snapcraft/plugins/python3.py
- snapcraft/plugins/scons.py
- snapcraft/sources.py
- snapcraft/tests/test_sources.py
This makes source handling common for all source types, leaving
the source in sourcedir always and leaving the logic to manage
build from the plugin.
> Making source management common to all types

- snapcraft/cmds.py
If the last command executed in a snapcraft run session exits with a
non-zero status, an exception will be raised because we were using
check_call. Don't check the return value here so that we exit cleanly
rather than making it look like something horrible happened.
Fixed #40
> Don't throw exception on snapcraft run exit status

- integration-tests/units/examples.pxu
This has the added benefit of all examples running and being able to easily pinpoint which on is the one that fails.
> Making the examples individual tests

- snapcraft/__init__.py
- snapcraft/cmds.py
- snapcraft/lifecycle.py
- snapcraft/main.py
- snapcraft/plugins/catkin.py
- snapcraft/tests/test_cmds.py
- snapcraft/tests/test_lifecycle.py
Parts can now be individually cleaned up, involved moving some
of the logic to the plugin handler in the lifecycle itself.
Define things in one place only and expose them accordingly.
sourcedir, builddir and installdir are handled in the plugin while
stagedir, snapdir, ubuntudir and the state file by the lifecycle.
> Clean for parts and removal of duped code for lifecycle and the BasePlugin

- examples/py2-project/snapcraft.yaml
- snapcraft/plugins/python2.py
- snapcraft/plugins/python3.py
- snapcraft/yaml.py
When building there has been this long time issue of reaching into
each parts part/<part-name>/install directory, this breaks part
encapsulation. If anything, the build paths should point to the
stage directory and should be used in combination with the `after`
keyword.
Additionally, python2 needed some help include path mangling to
find its own Python.h
> Stage packages preferred over ./install and system

- schema/snapcraft.yaml
- snapcraft/tests/test_yaml.py
parts/plugins has a special meaning and it should not be used for
part names as it can cause potential issues when working with
local plugins.
Some commented schema yaml was removed too.
> Validate that 'plugins' is not used as a part name

- examples/gopaste/snapcraft.yaml
- integration-tests/data/simple-go/main.go
- integration-tests/data/simple-go/snapcraft.yaml
- integration-tests/units/jobs.pxu
- snapcraft/plugins/go.py
- snapcraft/tests/test_plugin_go.py
This also avoids the error of checking for `:` in self.options.source
Closes LP: #1499240
Closes LP: #1515132
> go plugin: Support local sources

- snapcraft/plugins/autotools.py
- snapcraft/plugins/catkin.py
- snapcraft/plugins/cmake.py
- snapcraft/plugins/go.py
- snapcraft/plugins/maven.py
- snapcraft/plugins/nodejs.py
- snapcraft/plugins/python2.py
- snapcraft/plugins/python3.py
- snapcraft/plugins/scons.py
So it reads *plugin-specific* instead of *plugin specific*
> Docstring polish: inserting a - between words

- snapcraft/cmds.py
- snapcraft/tests/test_cmds.py
There was a missing sys.exit(1) when a plugin failed to load
leading to a confusing traceback
> Exiting with error when plugin cannot be loaded

- integration-tests/units/jobs.pxu
The circle tests where not running as part of the integration tests because their id was being filtered out.
> Fixed the id of the circle tests.

- examples/webcam-webui/snapcraft.yaml
Use 'python3' instead of 'python3-project'. Add a service description to make click-review happy.
> Fix webcam example

- snapcraft/plugins/nodejs.py
This is important to support trusty package builds.
> nodejs plugin: support 32 bit node

- snapcraft/tests/test_plugin_go.py
> go plugin: remove hardcoded arch triplet from test

- integration-tests/units/jobs.pxu
- snapcraft/meta.py
- snapcraft/plugins/python3.py
- snapcraft/tests/test_meta.py
The problem was two fold, on one side, the .pth file was missing for
easy install so pkg resources failed miserably to find the actual
defined script.
The other problem is that with the whole shebang rewrite story, the config
hook was neglected.
Fixes LP: #1519702
> Don't filter out easy install's .pth and wrap config

- snapcraft/cmds.py
- snapcraft/main.py
This was never implemented correctly. We will fix this in 2.0
Fixes LP: #1516775
> Remove the `parts` arg from `init`

- .travis.yml
- examples_tests/__main__.py
Just by using testtools we improve a little the output of the tests in case of error:
ERROR: examples_tests.tests.TestSnapcraftExamples.test_example(webchat)
Requires #107.
> Use testtools to run the examples tests.

- debian/changelog
> Updating debian/changelog for the 0.6 release

- snapcraft/cmds.py
- snapcraft/commands/clean.py
- snapcraft/tests/test_cmds.py
- snapcraft/tests/test_commands_clean.py
- snapcraft/yaml.py
This also involved moving `load_config` to the `yaml` module.
> cli: clean cmd migrated to docopts.

- snapcraft/cmds.py
- snapcraft/commands/pull.py
- snapcraft/common.py
- snapcraft/lifecycle.py
- snapcraft/repo.py
- snapcraft/tests/__init__.py
- snapcraft/tests/test_cmds.py
- snapcraft/tests/test_commands_pull.py
- snapcraft/yaml.py
> cli: pull command migrated to docopts

- snapcraft/commands/clean.py
- snapcraft/tests/test_cmds.py
- snapcraft/tests/test_commands_clean.py
- snapcraft/tests/test_lifecycle.py
- snapcraft/yaml.py
This also migrates clean to use real elements instead of
over mocking.
> clean cmd: migrate to use new lifecycle attribs

- snapcraft/commands/build.py
- snapcraft/lifecycle.py
- snapcraft/tests/test_commands_build.py
> cli: build command migrated to docopts

- integration-tests/data/build-tools/snapcraft.yaml
- integration-tests/data/bzr-head/snapcraft.yaml
- integration-tests/data/bzr-tag/snapcraft.yaml
- integration-tests/data/conflicts/snapcraft.yaml
- integration-tests/data/git-branch/snapcraft.yaml
- integration-tests/data/git-head/snapcraft.yaml
- integration-tests/data/git-tag/snapcraft.yaml
- integration-tests/data/hg-branch/snapcraft.yaml
- integration-tests/data/hg-head/snapcraft.yaml
- integration-tests/data/hg-tag/snapcraft.yaml
- integration-tests/data/local-source/snapcraft.yaml
- integration-tests/data/pypi-config/snapcraft.yaml
- integration-tests/data/simple-cmake/snapcraft.yaml
- integration-tests/data/simple-make-filesets/snapcraft.yaml
- integration-tests/data/simple-make/snapcraft.yaml
- integration-tests/data/simple-tar/snapcraft.yaml
- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
> Obsolete deprecations from 1.x

- schema/snapcraft.yaml
- snapcraft/meta.py
- snapcraft/tests/test_yaml.py
The store should provide an icon if it is missing.
> Making the icon optional

- examples/ros/snapcraft.yaml
- examples/ros/src/beginner_tutorials/CMakeLists.txt
- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
The current Catkin plugin distributes only the built version of a ROS package that would typically go into the devel workspace, but that version doesn't include non-source, non-binary files, such as .launch files. This PR changes the plugin to actually install ROS packages, thereby including any non-source, non-binary files specified by the developer.
This PR also updates the wrapper environment to correctly setup the ROS environment, which allows for the use of typical ROS tools within the snapcraft.yaml, such as roslaunch, rosrun, etc., and updates the ROS examples to make use of them.
Finally, this PR also increases the test coverage of the Catkin plugin twofold.
> Catkin plugin: Add support for ROS tools.

- snapcraft/plugins/catkin.py
- snapcraft/plugins/roscore.py
This simply moves the hack into the roscore plugin, which already has more of them anyway.
> Resolve xml2-config FIXME in Catkin plugin

- snapcraft/meta.py
- snapcraft/tests/test_meta.py
The regex used in wrap_exe was over doing it and globbing more than
necessary for replacement. This makes the match not consider `.*`
but instead uses the match used for valid part names and considers `/`.
Fixes LP: #1523912
> Wrapping exe should not be over match to replace

- snapcraft/plugins/go.py
- snapcraft/tests/test_plugin_go.py
Possible fix for this bug: https://bugs.launchpad.net/snapcraft/+bug/1524374
> Go plugin creating invalid env

- snapcraft/plugins/python2.py
- snapcraft/plugins/python3.py
- snapcraft/tests/test_plugin_python2.py
- snapcraft/tests/test_plugin_python3.py
Currently the Python2 and Python3 plugins create a `<install>/usr/lib/<pythonversion>/site-packages` symlink to `<install>/usr/lib/<pythonversion>/dist-packages`, but that absolute link doesn't exist when the .snap is installed. This commit makes the link relative instead of absolute so the link stays valid.
This may be worth cherry-picking to 1.x.
Fixes LP: [#1523384](https://bugs.launchpad.net/snapcraft/+bug/1523384)
> Python{2,3} plugins: Make site-packages link relative.

- debian/tests/control
- debian/tests/examplestests
- debian/tests/integrationtests
- debian/tests/runexamples
- debian/tests/runtests
On autopkgtests, run the integration tests, build the examples but do not install them, do not run the unittests.
The unittests are run when the package is built, so no need to run them again during package update.
The examples install tests will run only daily, and on PRs.
> Updated the autopkgtests.

- snapcraft/plugins/catkin.py
- snapcraft/plugins/roscore.py
- snapcraft/tests/test_plugin_catkin.py
The Catkin plugin currently does its own dependency resolution via manually parsing each package.xml. It makes some naive assumptions while doing so, and a tool already exists in ROS for doing this: rosdep. This PR gets rid of the manual parsing in favor of rosdep.
> Catkin plugin: use rosdep for dependency resolution

- snapcraft/plugins/python2.py
- snapcraft/plugins/python3.py
- snapcraft/tests/test_plugin_python2.py
- snapcraft/tests/test_plugin_python3.py
This is a cherry-pick of #169 to 1.x.
> Cherry-pick for 1.x: Python{2,3} plugins: Make site-packages link relative.

- snapcraft/meta.py
- snapcraft/tests/test_meta.py
This is a cherry-pick of #162 to 1.x
> Cherry-pick for 1.x: Wrapping exe should not be over match to replace

- docs/ros-snap.md
- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
This PR contains a number of small refactors:
- Change `env()` to only contain variables for run-time, and document each of them.
- Only obtain dependencies upon `pull()`-- for `build()` they should just be ready to go.
- Extract dependency resolution into a standalone function that can be tested in isolation.
- Change `build()` to be less clever and more simple/verbose/robust.
- Add `source-space` keyword to get rid of custom `build()`.
- Get unit testing coverage of the Catkin plugin to 100%.
> Catkin plugin: Refactor build.

- docs/ros-snap.md
- docs/snapcraft-usage.md
Backport of #159 to 1.x
Conflicts:
docs/snapcraft-usage.md
Conflicts occurred due to `snapcraft run` section in docs/snapcraft-usage.md that didn't exist in master. Resolved manually.
> Backport to 1.x: Add a tutorial for turning a ROS project into a .snap.

- snapcraft/plugins/catkin.py
- snapcraft/plugins/roscore.py
- snapcraft/tests/test_plugin_catkin.py
> Backport to 1.x: Catkin plugin: use rosdep for dependency resolution.

- docs/ros-snap.md
> Backport to 1.x: ROS documentation: Fix missing step to make script executable.

- snapcraft/tests/test_plugin_catkin.py
The configtional is `if not ... in ...` when it should be `if ... not in ...`
> Fix ordering for conditional negations in catkin tests

- snapcraft/tests/test_plugin_catkin.py
Mocks using `assert_not_called` don't take a message, to keep the message
we use `assertFalse` and the `called` attribute of the mock.
> Replace use of `assert_not_called` in the catkin tests

- docs/get-started.md
- docs/intro.md
- docs/ros-snap.md
- docs/snapcraft-advanced-features.md
- docs/snapcraft-usage.md
- docs/your-first-snap.md
Most of these changes are to reflect the new cli, but there are also
other minor corrections in here.
> General documentation update

- integration_tests/snaps/license/LICENSE
- integration_tests/snaps/license/snapcraft.yaml
- integration_tests/test_license.py
- schema/snapcraft.yaml
- snapcraft/meta.py
- snapcraft/tests/test_meta.py
- snapcraft/tests/test_yaml.py
> Add licensing support

- snapcraft/plugins/qml.py
> Backport to 1.x: Close not called on the qml plugin

- examples/opencv/snapcraft.yaml
- examples/opencv/src/CMakeLists.txt
- examples/opencv/src/main.cpp
- examples_tests/tests.py
- snapcraft/libraries.py
- snapcraft/tests/test_libraries.py
- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
Currently Snapcraft adds only a few standard paths to LD_LIBRARY_PATH. This PR expands that to include paths used by mesa packages.
This will need to be backported to 1.x once approved.
Resolves LP: [#1531620](https://bugs.launchpad.net/snapcraft/+bug/1531620)
> Add support for mesa libraries.

- snapcraft/plugins/autotools.py
- snapcraft/tests/test_plugin_autotools.py
This PR fixes LP: [#1530995](https://bugs.launchpad.net/snapcraft/+bug/1530995) by setting autogen.sh to be executable (if necessary). It also adds tests for the autotools plugin.
It will need to be backported to 1.x when approved.
> Autotools plugin: Set autogen.sh executable.

- CONTRIBUTING.md
This PR resolves LP: [#1532195](https://bugs.launchpad.net/snapcraft/+bug/1532195) by making the first step of the contribution guidelines "Make sure there's a bug."
> Update CONTRIBUTING.md to require a bug.

- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
This PR fixes LP: [#1532241](https://bugs.launchpad.net/snapcraft/+bug/1532241) by instructing rosdep to resolve dependencies using Trusty, even if Snapcraft is not being run on Trusty.
This will need to be cherry-picked to 1.x as well.
> Ensure rosdep resolves dependencies using Trusty.

- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
> Backport to 1.x: Ensure rosdep resolves dependencies using Trusty.

- snapcraft/tests/test_plugin_catkin.py
> Backport to 1.x: Replace use of `assert_not_called` in the catkin tests

- schema/snapcraft.yaml
- snapcraft/meta.py
- snapcraft/tests/test_yaml.py
LP: [#1533293](https://bugs.launchpad.net/snapcraft/+bug/1533293)
> Support the new security-override semantics

- .travis.yml
- runtests.sh
@sergiusens wants to run the static checks in something newer than trusty. We can do that with the lxc branch, but we have to split them from the unit tests that we do want to run in trusty.
Fixes LP: [#1533397](https://bugs.launchpad.net/snapcraft/+bug/1533397)
> Split the static and unit tests.

- integration_tests/test_snap.py
- snapcraft/meta.py
- snapcraft/tests/test_meta.py
We wrap with the app name as the params are now globbed into the
wrapper
LP: #1534150
> Wrap apps with the app name

- examples/godd/snapcraft.yaml
- snapcraft/common.py
- snapcraft/pluginhandler.py
- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
Environment variables now correctly point to stagedir and snapdir and
don't expose the internal installdir paths for a part.
This required an intermediate change in the handling of stage-packages
but it also gives it a semantic meaning by unpacking everything into
the staging directory. Future work can make the handling of
stage-package more transactional or in a single shot.
LP: #1531481
> Fix environment variable handling

- examples/ros/snapcraft.yaml
- snapcraft/plugins/catkin.py
- snapcraft/plugins/roscore.py
- snapcraft/tests/test_plugin_catkin.py
This works pre-Xenial since python2 is provided on the image. However, it's been removed in Xenial which uncovered this bug. The fix simply rewrites all /usr/bin/python shebangs to use /usr/bin/env python, and also fixes up 10.ros.sh to use python from the path instead of /usr/bin/python.
LP: [#1533297](https://bugs.launchpad.net/snapcraft/+bug/1533297)
> Catkin plugin: Use in-snap python instead of OS-provided.

- examples/gopaste/snapcraft.yaml
- examples/shout/snapcraft.yaml
- examples/webcam-webui/snapcraft.yaml
- examples/webchat/snapcraft.yaml
> Gopasted security override

- snapcraft/pluginhandler.py
- snapcraft/tests/test_pluginhandler.py
This prevents files contained in a stage-package .deb from taking precedence over files of the same name produced in the part. The migration is done via hard linking, which means this doesn't add any noticeable delay.
LP: [#1534800](https://bugs.launchpad.net/snapcraft/+bug/1534800)
> Always migrate files, even if they already exist.

- examples/ros/snapcraft.yaml
- examples_tests/tests.py
- snapcraft/common.py
- snapcraft/plugins/catkin.py
- snapcraft/plugins/roscore.py
- snapcraft/repo.py
- snapcraft/tests/test_common.py
- snapcraft/tests/test_plugin_catkin.py
- snapcraft/tests/test_repo.py
> Add usr/bin to the shebang replace path

- snapcraft/plugins/catkin.py
- snapcraft/plugins/roscore.py
- snapcraft/tests/test_plugin_catkin.py
The ros plugins are setting _setup_util.py's CMAKE_PREFIX_PATH to
build time paths and later inserting the current path. This fails on
runtime due to confinement as the directories accessed don't exist.
(this is the case for armhf).
LP: #1535309
> Initialize CMAKE_PREFIX_PATH to [] for ros

- snapcraft/plugins/go.py
- snapcraft/tests/test_plugin_go.py
> Backport to 1.x: Go plugin creating invalid env

- snapcraft/tests/test_sources.py
I created a test for bazaar type sources. The test ensures that sources.py correctly recognizes and calls the correct methods for bazaar sources.
LP: #1536283
> Added a unit tests for pulling bazaar sources from URIs.

- docs/snapcraft-syntax.md
- snapcraft/__init__.py
This PR resolves LP: [#1536659](https://bugs.launchpad.net/snapcraft/+bug/1536659) by adding a description of `build-packages` to docs/snapcraft-syntax.md.
> Add build-package description to docs/snapcraft-sytax.md

- snapcraft/sources.py
- snapcraft/tests/test_sources.py
This PR resolves LP: [#1536696](https://bugs.launchpad.net/snapcraft/+bug/1536696) by making the git source use a shallow (depth of 1) clone rather than fetching the entire history.
> Git source: Make a shallow clone.

- snapcraft/sources.py
- snapcraft/tests/test_sources.py
> Backport to 1.x: Git source: Make a shallow clone.

- snapcraft/plugins/autotools.py
- snapcraft/tests/test_plugin_autotools.py
This PR resolves LP: [#1536700](https://bugs.launchpad.net/snapcraft/+bug/1536700) by making the Autotools plugin call `make` before it calls `make install`.
> Autotools plugin: Call make before make install

- snapcraft/plugins/autotools.py
- snapcraft/tests/test_plugin_autotools.py
> Backport to 1.x: Autotools plugin: Call make before make install

- snapcraft/sources.py
- snapcraft/tests/test_sources.py
This PR resolves LP: [#1536698](https://bugs.launchpad.net/snapcraft/+bug/1536698) by cloning recursively (thus retrieving submodules), and updates them when pulled as well.
> Git source: Support submodules.

- snapcraft/sources.py
- snapcraft/tests/test_sources.py
> Backport to 1.x: Git source: Support submodules.

- .travis.yml
- runtests.sh
- snapcraft/plugins/catkin.py
- snapcraft/plugins/python2.py
- snapcraft/plugins/roscore.py
- tests/plainbox/whitelists/normal.whitelist
Fixes LP: [#1532213](https://bugs.launchpad.net/snapcraft/+bug/1532213)
> Run the tests in a xenial LXC.

- integration_tests/snaps/simple-tar/snapcraft.yaml
- integration_tests/test_tar_plugin.py
- snapcraft/plugins/tar_content.py
- snapcraft/tests/test_plugin_tar_content.py
The tar will be untared to the defined directory in the ../build and
../install directory from the snap. The new attribute "destination" is optional.
Extract from the spancraft.yaml
destination-dir:
plugin: tar-content
source: simple.tar.bz2
destination: destdir1/destdir2
> [modified] Added an attribute for defining a destination directory.

- integration_tests/snaps/simple-make-nonstandard-makefile/makefile.linux
- integration_tests/snaps/simple-make-nonstandard-makefile/snapcraft.yaml
- integration_tests/snaps/simple-make-nonstandard-makefile/test.c
- integration_tests/test_make_plugin.py
- snapcraft/plugins/make.py
- snapcraft/tests/test_plugin_make.py
This PR fixes LP: [#1500759](https://bugs.launchpad.net/snapcraft/+bug/1500759) by adding a "makefile" property to the Make plugin, which, if specified, results in a `make -f <makefile>` instead of just `make`. This supports projects with makefiles named e.g. makefile.linux, etc.
> Make plugin: Support non-standard makefile name.

- examples_tests/tests.py
- integration_tests/__init__.py
The details will be shown at the end of the execution with the summary
of the restuls.
LP: #1538354
> Add tests errors as details.

- docs/debug.md
> Add document about debugging snaps.

- snapcraft/repo.py
> fix FD leakage by closing apt cache in repo.py

- docs/snapcraft-advanced-features.md
- integration_tests/snaps/stage_env/CMakeLists.txt
- integration_tests/snaps/stage_env/snapcraft.yaml
- integration_tests/test_after.py
- snapcraft/pluginhandler.py
- snapcraft/tests/test_pluginhandler.py
When a part is loaded, instances of $SNAPCRAFT_STAGE
are replaced with the absolute path to the stage directory
during runtime.
LP: #1538688
> Support $SNAPCRAFT_STAGE for parts

- HACKING.md
- docs/upload-your-snap.md
- docs/your-first-snap.md
This PR resolves LP: [#1539234](https://bugs.launchpad.net/snapcraft/+bug/1539234) by adding a document that walks a developer through uploading a snap.
> Add documentation for how to use snapcraft upload.

- snapcraft/tests/__init__.py
- snapcraft/tests/test_storeapi_upload.py
Unit tests now have the logging fixture set by default to avoid leaking
messages to the console
LP: #1539817
> Use the log fixture for logging by default for ut

- .travis.yml
- debian/control
- debian/tests/control
- examples/godd/snapcraft.yaml
- examples/py2-project/snapcraft.yaml
- examples/py3-project/snapcraft.yaml
- integration_tests/test_bzr_source.py
- integration_tests/test_git_source.py
- integration_tests/test_hg_source.py
- snapcraft/common.py
- snapcraft/sources.py
- snapcraft/tests/test_common.py
- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
debian/control has a huge amount of dependencies that could very well
be installed depending on the project. There are also dependencies
included that are not relevant anymore.
The work here:
- cleans up debian/control
- adds logic to install the correct vcs tool depending on the source
in snapcraft.yaml
- makes sure all the examples have complete dependencies
- cleans up .travis.yml
LP: #1539146
> Make package installation dynamic to reduce deps

- integration_tests/snaps/conflicts/snapcraft.yaml
- integration_tests/snaps/dependencies/snapcraft.yaml
- integration_tests/snaps/simple-cmake/snapcraft.yaml
- integration_tests/snaps/simple-make-nonstandard-makefile/snapcraft.yaml
- integration_tests/snaps/simple-make/snapcraft.yaml
- integration_tests/snaps/simple-scons/snapcraft.yaml
- integration_tests/snaps/wiki/snapcraft.yaml
Most of the integration tests require gcc as a build-package.
LP: #1541332
> Add gcc as build-packages to integration tests

- snapcraft/cmds.py
Backport of #268 for 1.x.
Note that in 1.x this wasn't actually in repy.py, but in cmds.py.
> Backport to 1.x: Fix FD leakage by closing apt cache in repo.py

- snapcraft/tests/test_plugin_catkin.py
> Backport to 1.x: Fix ordering for conditional negations in catkin tests

- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
This PR fixes LP: [#1524663](https://bugs.launchpad.net/snapcraft/+bug/1524663) by improving YAML validation errors across the board. Specifically:
-  Improve error message if icon isn't a .png or .svg, or doesn't exist.
Was: "'icon.png' is not an icon-path"
Now: "Specified icon 'icon.png' does not exist" or "'icon' must be either a .png or a .svg"
- Improve error message if apparmor or seccomp profiles don't exist.
Was: "The 'migration' property does not match the required schema: {'security-policy': {'apparmor': 'path/profile', 'seccomp': 'path/profile'}, 'type': 'migration-skill'} is not valid under any of the given schemas"
Now: "Specified file 'path/profile' does not exist"
- Improve generic jsonschema errors to include the properties which had the error.
Was: "None is not of type …
> Improve snapcraft.yaml validation errors.

- integration_tests/test_snap.py
- snapcraft/commands/snap.py
- snapcraft/tests/test_commands_snap.py
Fixes LP: [#1541987](https://bugs.launchpad.net/snapcraft/+bug/1541987)
> Snap: When snapping a directory, look for snap.yaml.

- snapcraft/commands/upload.py
- snapcraft/storeapi/_upload.py
- snapcraft/tests/test_commands_upload.py
- snapcraft/tests/test_storeapi_upload.py
This PR fixes LP: [#1541353](https://bugs.launchpad.net/snapcraft/+bug/1541353) by using the `snapcraft.yaml` to obtain the snap name rather than using regex against the snap package, which was rather fragile and not in accordance with the spec.
> Upload: Obtain name from YAML instead of snap.

- examples_tests/__main__.py
- examples_tests/tests.py
> Use docopt to handle example tests arguments.

- integration_tests/test_snap.py
- snapcraft/commands/snap.py
- snapcraft/tests/test_commands_snap.py
This adds support for -o or --output to have a deterministic
output file for a snap.
LP: #1542479
> Support setting an output file when snapping

- README.md
(raw.githubusercontent.com shows SVG as raw XML, rawgit.com works as expected).
LP: #1542422
> Use image link which actually works

- examples_tests/tests.py
- integration_tests/test_maven_plugin.py
- snapcraft/plugins/maven.py
- snapcraft/repo.py
- snapcraft/tests/test_plugin_maven.py
This makes sure we setup noninteractive for deb installation and
also sets up the proxy configuration for maven.
LP: #1542511
> adt fixes for maven and noninteractive deb install

- snapcraft/tests/test_plugin_maven.py
This considers builder environment variables that could potentially affect
unit tests.
> Pre release unit test fix for 2.2

- integration_tests/snaps/conflicts/snapcraft.yaml
- integration_tests/snaps/dependencies/snapcraft.yaml
- integration_tests/snaps/simple-cmake/CMakeLists.txt
- integration_tests/snaps/simple-cmake/snapcraft.yaml
- integration_tests/snaps/simple-make-nonstandard-makefile/snapcraft.yaml
- integration_tests/snaps/simple-make/snapcraft.yaml
- integration_tests/snaps/simple-scons/snapcraft.yaml
- integration_tests/snaps/simple-tar/snapcraft.yaml
Most integration tests were missing a build dependency of libc6-dev
LP: #1544343
> Add missing libc6 build dep to integration tests

- integration_tests/test_snap.py
- integration_tests/test_upload.py
The replacement is interesting since it allows to capture dependency
issues in the snapcraft.yaml's.
LP: #1544340
> Replace dpkg-architecure calls in tests

- examples/opencv/snapcraft.yaml
It was missing: gcc, g++ and libc6-dev
> Add missing build-packages for the opencv example

- snapcraft/common.py
- snapcraft/plugins/catkin.py
- snapcraft/plugins/python2.py
- snapcraft/tests/test_plugin_catkin.py
- snapcraft/tests/test_plugin_python2.py
python-minimal is needed by the python2 and the catkin plugin.
LP: #1541451
> Adding python-minimal to plugins that need it

- integration_tests/snaps/stage_env/CMakeLists.txt
The after integration test had a cmake project set to use
the generic language template, as this cmake project does
nothing we explicitly set it to NONE.
LP: #1544792
> Set after test cmake project to use no language

- debian/tests/examplestests
The ros example run in adt needs some deep research for it to work
so disabling for now to have a good adt quality gate in place
LP: #1544790
> Disable ros example in adt tests

- .travis.yml
- debian/control
- debian/tests/control
- integration_tests/test_snap.py
- integration_tests/test_stage.py
- snapcraft/commands/cleanbuild.py
- snapcraft/commands/upload.py
- snapcraft/common.py
- snapcraft/lxd.py
- snapcraft/main.py
- snapcraft/repo.py
- snapcraft/tests/test_commands_cleanbuild.py
- snapcraft/tests/test_common.py
- snapcraft/tests/test_lxd.py
- snapcraft/tests/test_main.py
This new command's intention is to make building with a clean
slate and easy chore.
LP: #1480144
> New command cleanbuild (using lxd)

- integration_tests/test_snap.py
- snapcraft/main.py
- snapcraft/tests/test_main.py
Calling snapcraft with no arguments should default to just calling
the `snap` command for easier use.
LP: #1548915
> Calling snapcraft with no args defaults to snap

- .bzrignore
- snapcraft/scripts/generate_reference.py
Run:
```
./snapcraft/scripts/generate_reference.py
```
or
```
./snapcraft/scripts/generate_reference.py --output-file=/tmp/something.md
```
LP: #1544540
> Generate reference from snapcraft's "help" command.

- snapcraft/commands/snap.py
- snapcraft/tests/test_commands_snap.py
To make security better and easier to recreate snaps
we need to add -all-root, we also add -no-xattrs since
it is also an improvement that helps in preventing
people trying to circumvent the system.
LP: #1546821
> More attributes for the squashfs'ed snap

- examples_tests/__init__.py
- examples_tests/__main__.py
- examples_tests/test_libpipeline.py
- examples_tests/testbed.py
- examples_tests/tests.py
Refactor the examples tests to be able to write them independently, each
on its own file.
LP: #1546771
> examples_tests: fix the libpipeline test.

- snapcraft/log.py
A failure to detach should be a noop just like the checked
for conditions.
LP: #1549831
> Catch a failure to detach for the log

- examples_tests/__init__.py
- examples_tests/test_libpipeline.py
> examples_tests/libpipeline: skip the output assertion when skipping the install

- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
This PR fixes LP: [#1548370](https://bugs.launchpad.net/snapcraft/+bug/1548370) by catching the relevant exception raised by `repo.Ubuntu` and printing a message explaining exactly what the problem was.
> Catkin plugin: Print nice message if dependency is invalid.

- snapcraft/log.py
- snapcraft/main.py
- snapcraft/tests/test_log.py
- snapcraft/tests/test_main.py
This PR resolves LP: [#1548492](https://bugs.launchpad.net/snapcraft/+bug/1548492) by re-raising any caught exception and changing the log level to DEBUG if Snapcraft is running with the `-d` or `--debug` argument.
> Support --debug flag to enable backtrace and debug logs.

- snapcraft/plugins/cmake.py
- snapcraft/tests/test_plugin_cmake.py
CMake's `find_file()`, `find_library()`, `find_package()`, and similar functions use environment variables to determine where to look. This PR resolves LP: [#1550778](https://bugs.launchpad.net/snapcraft/+bug/1550778) by updating the CMake plugin to utilize them.
> CMake plugin: Automatically find staged libs and files.

- snapcraft/plugins/cmake.py
- snapcraft/tests/test_plugin_cmake.py
> Backport to 1.x: CMake plugin: Automatically find staged libs and files.

- snapcraft/__init__.py
- snapcraft/tests/test_base_plugin.py
Currently, if source-subdir is specified, Snapcraft copies ONLY that subdir (and excludes the rest of the source) and attempts to build from it. This only works for some projects, not all. A better solution is to copy the entire source and simply build from WITHIN the subdir. This PR fixes LP: [#1549676](https://bugs.launchpad.net/snapcraft/+bug/1549676) by introducing exactly that change. It does so without changing the plugin API or semantics.
> Copy entire source, even if source-subdir is specified.

- snapcraft/__init__.py
- snapcraft/tests/test_base_plugin.py
> Backport to 1.x: Copy entire source, even if source-subdir is specified.

- snapcraft/plugins/autotools.py
- snapcraft/tests/test_plugin_autotools.py
Currently autotools installs via DESTDIR, but not all autotools projects work that way. This PR fixes LP: [#1544629](https://bugs.launchpad.net/snapcraft/+bug/1544629) by adding a config option that enables the prefix to be used instead.
> Autotools plugin: Support installing via prefix.

- snapcraft/meta.py
- snapcraft/tests/test_meta.py
When a command is supposed to be in PATH, make sure
the error is clear.
LP: #1550496
> Clear error when specifying a non existing command

- integration_tests/snaps/local-plugin/parts/plugins/x_local_plugin.py
- snapcraft/pluginhandler.py
This is to support the case of a plugin importing baseplugin
as a symbol instead of the module.
LP: #1547681
> Skip the BasePlugin from plugin search

- integration_tests/test_snap.py
- snapcraft/repo.py
- snapcraft/tests/test_repo.py
The error that results from using an invalid build-package
is not very specific. This exposes the KeyError raised by apt.
LP: #1547672
> Expose the invalid build-package on error

- snapcraft/common.py
- snapcraft/main.py
- snapcraft/plugins/autotools.py
- snapcraft/plugins/cmake.py
- snapcraft/plugins/make.py
- snapcraft/tests/__init__.py
- snapcraft/tests/test_common.py
- snapcraft/tests/test_main.py
- snapcraft/tests/test_plugin_autotools.py
- snapcraft/tests/test_plugin_cmake.py
- snapcraft/tests/test_plugin_make.py
Several plugins within Snapcraft support parallel builds, but Snapcraft currently doesn't take advantage of this and builds them with a single job. This PR resolves LP: [#1551417](https://bugs.launchpad.net/snapcraft/+bug/1551417) by adding support for parallel builds, and enabling them by default in the autotools, cmake, and make plugins. It also adds an option to disable parallel builds via the `--no-parallel-build` option for the case of running in a RAM-limited environment.
> Support parallel builds (enabled by default).

- examples/gopaste/snapcraft.yaml
- examples/mosquitto/snapcraft.yaml
- examples/ros/snapcraft.yaml
- examples/shout/snapcraft.yaml
- examples/tomcat-maven-webapp/snapcraft.yaml
- examples/webcam-webui/snapcraft.yaml
- examples/webchat/snapcraft.yaml
- schema/snapcraft.yaml
- snapcraft/meta.py
- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
This adds some sort of transparent migration logic from "skills" related
keywords to the ones belonging to "interfaces".
LP: #1549427
> Migrate from skills to interfaces

- snapcraft/meta.py
This will print to stderr if there is a reason to, but that is a good thing.
LP: #1551939
> Do not print which's output to stdout

- schema/snapcraft.yaml
- snapcraft/tests/test_yaml.py
Just makes it valid syntax in snapcraft.yaml
> Support for a daemon's restart-condition

- examples_tests/__init__.py
The examples tests shell out and capture output but this output
is not used so we should not decode it.
LP: #1552403
> Remove the useles decode done in tests.

- examples/libpipeline/snapcraft.yaml
- examples/libpipeline/test.c
- examples_tests/test_libpipeline.py
The libpipeline examples tests the pipe using ls. Now that the snap is
run in an empty working directory, the result of ls is empty.
LP: #1554637
> examples_tests: update the expected result of the libpipeline test

- .travis.yml
- examples_tests/__init__.py
- runtests.sh
We applied a hack in travis to get a xenial LXC and run the tests in
there. Something changed and now the tests are taking an excessive
amount of time, and timing out. We no longer need this tests to run in
xenial because we are already running them in Jenkins, so we can get rid
of the hack.
LP: #1555386
> travis: run the tests in the GCE trusty machine

- snapcraft/__init__.py
- snapcraft/main.py
- snapcraft/tests/test_commands_help.py
Help text has Unicode quotes in a few places, which breaks help output as noted in https://bugs.launchpad.net/snapcraft/+bug/1555733. This change replaces them with ASCII quotes
> Remove Unicode quotes from help text

- snapcraft/sources.py
- snapcraft/tests/test_sources.py
isdir evaluates to true as it follows symlinks by default and
later fails when doing an rmdir, so we invert the check and we
also specifically check for a link or fail in a controlled way
if not for healthier user output.
This also fixes the case where you could not pull twice with the
"is a symlink error".
LP: #1558446
> Correct local source pulling

- snapcraft/pluginhandler.py
- snapcraft/tests/__init__.py
- snapcraft/tests/test_commands_build.py
- snapcraft/tests/test_commands_pull.py
- snapcraft/tests/test_commands_snap.py
- snapcraft/tests/test_commands_stage.py
- snapcraft/tests/test_commands_strip.py
- snapcraft/tests/test_commands_upload.py
- snapcraft/tests/test_pluginhandler.py
This PR resolves LP: [#1558810](https://bugs.launchpad.net/snapcraft/+bug/1558810) by moving from a single state file to per-step state files. This is necessary for future changes, such as tracking dirty state and per-step cleaning rules.
> Improve per-step state tracking.

- examples/96boards-kernel/snapcraft.yaml
- integration_tests/test_list_plugins.py
- integration_tests/test_main.py
- schema/snapcraft.yaml
- snapcraft/__init__.py
- snapcraft/common.py
- snapcraft/main.py
- snapcraft/meta.py
- snapcraft/pluginhandler.py
- snapcraft/plugins/kbuild.py
- snapcraft/plugins/kernel.py
- snapcraft/plugins/tar_content.py
- snapcraft/tests/test_commands_list_plugins.py
- snapcraft/tests/test_common.py
- snapcraft/tests/test_main.py
- snapcraft/tests/test_plugin_kbuild.py
- snapcraft/tests/test_plugin_kernel.py
- snapcraft/tests/test_yaml.py
Includes 2 plugins with an example for each.
Jointly developed by Alexander Sack and Sergio Schvezov
LP: #1552168
> New plugin: kernel

- examples_tests/test_libpipeline.py
The next ubuntu-core release changes the name of the binary of this
example. This update makes the test pass in rolling ubuntu-core/edge.
LP: #1560254
> libpipeline example test: update the binary name

- examples_tests/__init__.py
- examples_tests/test_busybox.py
The next ubuntu-core release changes the directory where the command
is run. This lets us use busybox.touch and changes the expected
results of busybox.ls
LP: #1560255
> busybox example: update the expected results

- schema/snapcraft.yaml
- snapcraft/commands/snap.py
- snapcraft/lifecycle.py
- snapcraft/tests/test_commands_snap.py
- snapcraft/tests/test_lifecycle.py
- snapcraft/tests/test_yaml.py
When creating os snaps we want to preserve user permissions.
LP: #1557513
> Snaps of type os should not squash with -all-root

- snapcraft/commands/clean.py
- snapcraft/pluginhandler.py
- snapcraft/tests/test_commands_clean.py
- snapcraft/tests/test_pluginhandler.py
- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
This PR makes progress on LP: [#1537786](https://bugs.launchpad.net/snapcraft/+bug/1537786) by adding a --step argument to the clean command, cleaning reverse dependencies, and implementing per-step clean rules. All per-step clean rules are placeholders to be implemented in subsequent PRs.
> Support per-step clean command.

- snapcraft/commands/snap.py
- snapcraft/tests/test_commands_snap.py
When snapping a directory we want to support architecture all
by omission of mentioning the architecture.
LP: #1560481
> Support architecture all packages when snapping

- integration_tests/test_clean_stage_step.py
- snapcraft/pluginhandler.py
- snapcraft/tests/test_commands_clean.py
- snapcraft/tests/test_pluginhandler.py
This PR makes progress on LP: [#1537786](https://bugs.launchpad.net/snapcraft/+bug/1537786) by adding the ability to clean only a part's staged files. This takes into account the possibility for parts to share files, and such files are not removed.
> Support cleaning stage step.

- snapcraft/meta.py
- snapcraft/tests/test_commands_strip.py
- snapcraft/tests/test_meta.py
Instead of declaring fixed assets we put them into a `setup` dir.
Implementation for gui (including icon) and license provided.
LP: 1560969
> Fixed assets go into a setup dir

- integration_tests/snaps/assemble/binary1.after
- integration_tests/test_snap.py
- snapcraft/plugins/python2.py
- snapcraft/plugins/python3.py
- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
CXXFLAGS was also missing here.
LP: #1558965
> Include and library paths must exist

- integration_tests/test_clean_pull_step.py
- snapcraft/__init__.py
- snapcraft/commands/clean.py
- snapcraft/pluginhandler.py
- snapcraft/plugins/catkin.py
- snapcraft/plugins/go.py
- snapcraft/plugins/nodejs.py
- snapcraft/tests/test_base_plugin.py
- snapcraft/tests/test_commands_clean.py
- snapcraft/tests/test_plugin_catkin.py
- snapcraft/tests/test_plugin_go.py
- snapcraft/tests/test_plugin_nodejs.py
- snapcraft/tests/test_pluginhandler.py
This PR finishes up LP: [#1537786](https://bugs.launchpad.net/snapcraft/+bug/1537786) by adding the ability to clean only a part's pulled files. This involves adding a new `clean_pull()` method to the plugin API as there are a few plugins that have more involved pull steps than the base implementation's.
This commit also reimplements clean_pull() for the Go, NodeJS, and Catkin plugins.
Depends upon #398.
> Support cleaning pull step.

- integration_tests/test_local_plugin.py
- snapcraft/commands/clean.py
- snapcraft/common.py
- snapcraft/pluginhandler.py
- snapcraft/tests/test_commands_clean.py
Currently Snapcraft will remove the parts directory if no parts are using it, but it doesn't take into account the fact that local plugins are kept in there, and will remove them. This PR fixes LP: [#1561546](https://bugs.launchpad.net/snapcraft/+bug/1561546) by checking for local plugins before removing the parts directory. It also adds tests so that this regression can't happen again.
> Clean: Leave local plugins alone.

- docs/snapcraft-advanced-features.md
> docs - Fix indentation of 'cam' example.

- snapcraft/storeapi/_download.py
- snapcraft/tests/test_storeapi_download.py
> Raise a nice error when downloading without a login

- snapcraft/tests/test_commands_help.py
- snapcraft/tests/test_common.py
LP: 1563965
Two root causes:
- missing patch() leaving dirty 'badarch' in snapcraft.common.target_machine,
- pydoc.pager automatic detection failing for wrong reasons.
> Fix test isolation issues.

- snapcraft/pluginhandler.py
- snapcraft/tests/test_pluginhandler.py
Currently if attempting to run a per-step clean on a tree made dirty by a version of Snapcraft that didn't support per-step cleaning, Snapcraft suggests trying to run that step again. This isn't possible since the step has already been run, so it actually requires a full clean. This PR resolves LP: [#1561328](https://bugs.launchpad.net/snapcraft/+bug/1561328) by updating the suggestions to reflect this fact.
> Suggest a full clean if step clean is missing state.

- debian/changelog
- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
> Precedence and library path ordering.

- examples/mosquitto/subscribe.py
- examples_tests/__init__.py
- examples_tests/test_mosquitto.py
- examples_tests/testbed.py
> Add a test for the mosquitto example.

- integration_tests/snaps/dependencies/p4/Makefile
- integration_tests/snaps/dependencies/p4/p4.c
- integration_tests/snaps/dependencies/snapcraft.yaml
- integration_tests/test_clean_dependents.py
- snapcraft/lifecycle.py
- snapcraft/pluginhandler.py
- snapcraft/tests/test_commands_clean.py
- snapcraft/tests/test_lifecycle.py
- snapcraft/yaml.py
This PR resolves LP: [#1568004](https://bugs.launchpad.net/snapcraft/+bug/1568004) by making cleaning more consistent with the way parts are built (i.e. requiring that all interdependent parts be explicitly specified).
> Clean command: Don't automatically clean reverse dependencies.

- snapcraft/internal/states/_state.py
- snapcraft/internal/states/_strip_state.py
- snapcraft/lifecycle.py
- snapcraft/pluginhandler.py
- snapcraft/tests/test_commands_clean.py
- snapcraft/tests/test_lifecycle.py
- snapcraft/tests/test_pluginhandler.py
- snapcraft/tests/test_states_strip.py
Currently Snapcraft doesn't notice YAML changes if a given step has already run-- it simply says that it already ran and halts execution. This PR makes progress on LP: [#1477904](https://bugs.launchpad.net/snapcraft/+bug/1477904) by changing that for the strip step, where now if one changes the `snap` keyword in the YAML, strip will notice that it's out of date and automatically clean itself and re-run.
> Automatically re-strip if dirty.

- snapcraft/internal/states/_stage_state.py
- snapcraft/lifecycle.py
- snapcraft/pluginhandler.py
- snapcraft/tests/test_lifecycle.py
- snapcraft/tests/test_pluginhandler.py
- snapcraft/tests/test_states_stage.py
Currently Snapcraft only notices YAML changes for the strip step. For all other steps, if the step has already run it simply says so and bails. This PR makes progress on LP: [#1477904](https://bugs.launchpad.net/snapcraft/+bug/1477904) by changing that for the stage step, where now if one changes the `stage` keyword in the YAML, stage will notice that it's out of date and automatically clean itself (along with the strip step since it depends upon stage) and re-run.
> Automatically re-stage if dirty.

- examples/busybox/snapcraft.yaml
- examples/downloader-with-wiki-parts/snapcraft.yaml
- examples/gopaste/snapcraft.yaml
- examples/mosquitto/snapcraft.yaml
- examples/qmldemo/snapcraft.yaml
- examples/ros/snapcraft.yaml
- examples/shout/snapcraft.yaml
- examples/tomcat-maven-webapp/snapcraft.yaml
- examples/webcam-webui/snapcraft.yaml
- examples/webchat/snapcraft.yaml
- schema/snapcraft.yaml
- snapcraft/meta.py
- snapcraft/tests/test_meta.py
- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
> Remove `old-security`. Use proper interfaces.

- snapcraft/__init__.py
- snapcraft/internal/states/__init__.py
- snapcraft/internal/states/_build_state.py
- snapcraft/internal/states/_stage_state.py
- snapcraft/internal/states/_state.py
- snapcraft/lifecycle.py
- snapcraft/pluginhandler.py
- snapcraft/plugins/autotools.py
- snapcraft/plugins/cmake.py
- snapcraft/plugins/copy.py
- snapcraft/plugins/go.py
- snapcraft/plugins/kbuild.py
- snapcraft/plugins/kernel.py
- snapcraft/plugins/make.py
- snapcraft/plugins/maven.py
- snapcraft/plugins/nodejs.py
- snapcraft/plugins/scons.py
- snapcraft/plugins/tar_content.py
- snapcraft/tests/test_lifecycle.py
- snapcraft/tests/test_plugin_autotools.py
- snapcraft/tests/test_plugin_kbuild.py
- snapcraft/tests/test_plugin_kernel.py
- snapcraft/tests/test_plugin_make.py
- snapcraft/tests/test_plugin_maven.py
- snapcraft/tests/test_plugin_nodejs.py
- snapcraft/tests/test_pluginhandler.py
- snapcraft/tests/test_states_build.py
Currently Snapcraft notices YAML changes only for the strip and stage steps. For the other steps, if they've already run, it simply says so and bails. This PR makes progress on LP: [#1477904](https://bugs.launchpad.net/snapcraft/+bug/1477904) by changing that for the build step, where now if one changes any part of the YAML that the part's plugin says is associated with building, build will notice that it's out of date and error out asking the user to clean the build step to continue.
The build step is not automatically cleaned like the strip and stage steps because builds can take a very long time and we don't want to blow one away without the user explicitly asking to do so.
> Detect dirty build step.

- snapcraft/__init__.py
- snapcraft/internal/states/__init__.py
- snapcraft/internal/states/_pull_state.py
- snapcraft/lifecycle.py
- snapcraft/pluginhandler.py
- snapcraft/plugins/catkin.py
- snapcraft/plugins/go.py
- snapcraft/plugins/python2.py
- snapcraft/plugins/python3.py
- snapcraft/plugins/tar_content.py
- snapcraft/tests/test_lifecycle.py
- snapcraft/tests/test_plugin_catkin.py
- snapcraft/tests/test_plugin_nodejs.py
- snapcraft/tests/test_pluginhandler.py
Currently Snapcraft notices YAML changes for every step except the pull step.This PR finishes up LP: [#1477904](https://bugs.launchpad.net/snapcraft/+bug/1477904) by adding this functionality for the pull step, where now if one changes any part of the YAML that the part's plugin says is associated with pulling, pull will notice that it's out of date and error out asking the user to clean the pull step to continue.
The pull step is not automatically cleaned like the strip and stage steps because pulls can take a very long time (and require network) and we don't want to blow one away without the user explicitly asking to do so.
> Detect dirty pull step.

- snapcraft/lxd.py
- snapcraft/tests/test_lxd.py
Due to rework on the outside processor the Cleanbuilder was left
not working as the arguments for the constructor where passed
incorrect and therefor the container construction failed.
LP: #1570706
> Fix cleanbuild command

- snapcraft/_options.py
- snapcraft/tests/test_options.py
This PR fixes LP: [#1570835](https://bugs.launchpad.net/snapcraft/+bug/1570835)
> Add support for s390x architecture.

- examples/96boards-kernel/snapcraft.yaml
- snapcraft/plugins/kernel.py
- snapcraft/tests/test_plugin_kernel.py
This is another attempt at fixing LP: [#1569337](https://bugs.launchpad.net/snapcraft/+bug/1569337) which uses the magic library instead of shelling out to `file`. It also adds some tests.
> Kernel plugin: Support lzma/xz-compressed initrd.

- integration_tests/snaps/nil-with-additional-properties/snapcraft.yaml
- integration_tests/test_nil_plugin.py
- snapcraft/plugins/nil.py
- snapcraft/tests/test_commands_build.py
- snapcraft/tests/test_commands_clean.py
- snapcraft/tests/test_commands_stage.py
- snapcraft/tests/test_commands_strip.py
- snapcraft/tests/test_plugin_nil.py
- snapcraft/tests/test_pluginhandler.py
Some users were under the impression that nil could pull sources, when it can't. This PR resolves LP: [#1549691](https://bugs.launchpad.net/snapcraft/+bug/1549691) by hopefully making that more clear, and giving an example of what it CAN do.
> Nil plugin: Make purpose more clear in documentation.

- integration_tests/snaps/assemble/binary1.after
- snapcraft/internal/common.py
- snapcraft/internal/meta.py
- snapcraft/tests/test_meta.py
"$@" is the proper way to expand original positional args; $* will
perform an extra IFS split.
LP: #1572129
Signed-off-by: Loïc Minier <loic.minier@ubuntu.com>
> Fix shell quoting

- integration_tests/__init__.py
- snapcraft/internal/log.py
- snapcraft/tests/test_log.py
This fixes LP: [#1572186](https://bugs.launchpad.net/snapcraft/+bug/1572186) by using the following colors:
- INFO: Green
- WARNING: Yellow
- ERROR: Dark red
- CRITICAL: Light red
> Use colors for logging.

- snapcraft/internal/common.py
- snapcraft/tests/test_pluginhandler.py
Currently Snapcraft does its best to migrate files efficiently by utilizing hard links. However, `os.link()` doesn't seem to respect its `follow_symlinks` parameter, which results in broken symlinks in the final snap. This PR fixes LP: [#1572664](https://bugs.launchpad.net/snapcraft/+bug/1572664), working around that issue by utilizing `os.path.realpath()`.
> Follow symlinks while hard-linking migrated files.

- docs/debug.md
- docs/get-started.md
- docs/mir-snaps.md
- docs/ros-snap.md
- docs/snapcraft-usage.md
Remove any mention of snappy-remote, snappy-tools, snappy-debug, and other old Snappy things. This fixes LP: [#1568113](https://bugs.launchpad.net/snapcraft/+bug/1568113).
> docs/get-started.md: Stop discussing snappy-tools.

- snapcraft/internal/repo.py
> Create the 'partial' directory for apt.

- snapcraft/internal/pluginhandler.py
- snapcraft/internal/states/_build_state.py
- snapcraft/internal/states/_pull_state.py
- snapcraft/internal/states/_stage_state.py
- snapcraft/internal/states/_state.py
- snapcraft/internal/states/_strip_state.py
- snapcraft/tests/test_lifecycle.py
- snapcraft/tests/test_pluginhandler.py
- snapcraft/tests/test_states_build.py
- snapcraft/tests/test_states_pull.py
- snapcraft/tests/test_states_stage.py
This PR fixes LP: [#1564192](https://bugs.launchpad.net/snapcraft/+bug/1564192) by tracking the target architecture and making the `pull` and `build` steps dirty if they change between runs. This was done in an extensible way so utilizing more project options in the state tracking would be easy.
> Make pull and build steps dirty if target arch changes.

- docs/snapcraft-syntax.md
- examples/py3-project/snapcraft.yaml
- schema/snapcraft.yaml
- snapcraft/_schema.py
- snapcraft/internal/meta.py
- snapcraft/internal/yaml.py
- snapcraft/tests/test_meta.py
- snapcraft/tests/test_yaml.py
In order to support step upgrades, snaps need to be able to specify upgrade paths. This PR resolves LP: [#1581113](https://bugs.launchpad.net/snapcraft/+bug/1581113) by implementing that via a new "epoch" property specified in the `snap.yaml`. Valid epochs are positive integers (e.g. `0`, `1`, etc.) or positive integers followed by an asterisk (e.g. `1*`, `2*`, etc.).
`0` is epoch 0; `1*` is the upgrade path from 0 to 1; `1` is epoch 1 (and so on).
> Add support for epoch property.

- docs/snapcraft-advanced-features.md
- snapcraft/tests/test_pluginhandler.py
As discussed in #snappy IRC on Freenode with `sergiusens` at 13:41:02 on 26th May 2016, here is a pull request to correct the autotools plugin documentation and a couple of test cases.
> Correct autotools documentation and tests to use configflags

- snapcraft/internal/pluginhandler.py
- snapcraft/tests/test_pluginhandler.py
> A nicer error message for incorrect stage-packages

- snapcraft/_baseplugin.py
- snapcraft/tests/test_base_plugin.py
This filters out *.snap when in plugin.sourcedir.
LP: #1575628
> Filter out *.snap from sourcedir

- snapcraft/_options.py
Snapcraft currently uses gcc-powerpc64-linux-gnu. This PR fixes LP: [#1570944](https://bugs.launchpad.net/snapcraft/+bug/1570944) by making it use gcc-powerpc64le-linux-gnu.
> Use correct cross-build packages for ppc64le.

- integration_tests/test_list_plugins.py
- integration_tests/test_main.py
- snapcraft/internal/common.py
- snapcraft/main.py
- snapcraft/tests/test_commands_list_plugins.py
- snapcraft/tests/test_common.py
Wrap plugin list output content up to 120 characters depending on terminal size.
Added tests to ensure if detection fails, we are using the 120 characters. as well. Fixes https://bugs.launchpad.net/snapcraft/+bug/1587057.
Note that it's using put cols as a subprocess. A couple of years ago, I had to look into how to get the terminal size on different platforms in a reliable way, and it seems it's the best one without duplicating a fragile logic which evolves over time as new terminals arise.
> Wrap plugin list output content

- integration_tests/test_clean_prime_step.py
- snapcraft/main.py
- snapcraft/tests/test_commands_clean.py
Automatically switches to call in prime and prints a
deprecation warning.
LP: #1590256
> Backwards compatible clean with strip

- snapcraft/tests/__init__.py
- snapcraft/tests/test_common.py
The existing tests (also for plugin dir) were running order dependant.
Ensure we reset the state to default for all internal variables.
> Reenable get and set tourdir unit tests

- snapcraft/tests/test_lxd.py
- snapcraft/tests/test_pluginhandler.py
Remove the architecture in the pluginhandler test case setup.
LP: #1589752
> Make the IsDirty unit test case pass in architectures other than amd64.

- integration_tests/test_tour.py
- snapcraft/main.py
- snapcraft/tests/test_tour.py
Reenable "snapcraft tour" command with tests.
Added a small logic enhancements backed up with tests to ensure we don't nest default directory inside each other for multiple commands run.
> Reenable tour command

- HACKING.md
Sort of a misleading branch name, but this changes apt-get to apt in the HACKING.md file, which encourages people to use apt instead of apt-get.
Reported in bug 1591421: https://bugs.launchpad.net/snapcraft/+bug/1591421
> Changed apt-get to apt in HACKING.md

- schema/snapcraft.yaml
- snapcraft/tests/test_yaml.py
Until recently snapd was too permissive on app names, allowing them to potentially cause issues in the system (e.g. interfering with hook names, or resulting in invalid AppArmor profile names, etc.). This has been changed in snapd, and this PR resolves LP: [#1589613](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1589613) by fixing it in snapcraft as well.
Note that this PR does not change the validation error when using an invalid app name, which is slightly dreadful, but requires a more in-depth refactor.
> Make app names more restrictive.

- integration_tests/__init__.py
- integration_tests/test_parser.py
Add a "Happy Path" integration test for snapcraft-parser.
LP: #1590268
> Add snapcraft-parser integration test.

- setup.py
See https://bugs.launchpad.net/snapcraft/+bug/1568901
> Fix missing python-magic dependency

- setup.py
Reverts ubuntu-core/snapcraft#435
This affecting package builds.
> Revert "Fix missing python-magic dependency"

- HACKING.md
The mailing list has changed from snappy-devel to snapcraft, and we need to update the HACKING.md to reflect that change.
> [Trivial] Changes the mailing list in HACKING.md from snappy-devel to snapcraft

- snapcraft/internal/lxd.py
- snapcraft/tests/test_lxd.py
This fixes https://bugs.launchpad.net/snapcraft/+bug/1577548
> Make lxd containers ephemeral

- snapcraft/internal/yaml.py
- snapcraft/tests/test_yaml.py
Adding support for .snapcraft.yaml and erroring out if both a
.snapcraft.yaml and a snapcraft.yaml are found.
`snapcraft init` will still create an unhidden one.
LP: #1587933
> Support for a hidden snapcraft.yaml

- integration_tests/__init__.py
- integration_tests/test_parts.py
- snapcraft/internal/parts.py
- snapcraft/main.py
- snapcraft/tests/__init__.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/store/test_store_client.py
- snapcraft/tests/test_commands_update.py
- snapcraft/tests/test_config.py
- snapcraft/tests/test_sources.py
> Implement `snapcraft update` for parts

- snaps_tests/demos_tests/test_mosquitto.py
- snaps_tests/demos_tests/test_qt4_text_editor.py
- snaps_tests/demos_tests/test_qt5_text_editor.py
Make sure the cache is updated for the following demos:
- mosquitto
- qt4 text editor
- qt5 text editor
LP: #1596114
> Update the remote parts cache before demo tests

- integration_tests/test_list_plugins.py
This test has been unnecessarily painful to maintain, because every time
we add a new plugin, the format is changed. We don't need to check the format
anymore, and there is little risk of this breaking because the mechanism has been
extensively tested already.
LP: #1596114
> Simplify the list plugins integration test

- .bzrignore
- snapcraft/internal/common.py
- snapcraft/internal/parts.py
- snapcraft/main.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/test_commands_list_plugins.py
- snapcraft/tests/test_commands_search.py
- snapcraft/tests/test_commands_update.py
> Implement snapcraft search

- HACKING.md
- README.md
- debian/control
- debian/copyright
- docs/get-started.md
- docs/mir-snaps.md
- docs/snapcraft-advanced-features.md
- docs/your-first-snap.md
- setup.py
- snapcraft/internal/meta.py
- snapcraft/internal/pluginhandler.py
Update debian packaging, docs and links to point to snapcore
instead of ubuntu-core
LP: #1597006
> Migration from ubuntu-core to snapcore

- snapcraft/plugins/go.py
This fixes the typo detailed in [bug 1590245](https://bugs.launchpad.net/snapcraft/+bug/1590245).
> Fix trivial typo in warning for Go plugin (bug 1590245)

- integration_tests/test_after.py
- integration_tests/test_snap.py
- integration_tests/test_wiki.py
- snapcraft/internal/parts.py
- snapcraft/tests/test_commands_cleanbuild.py
- snapcraft/tests/test_commands_define.py
- snapcraft/tests/test_commands_search.py
- snaps_tests/__init__.py
- snaps_tests/demos_tests/test_mosquitto.py
- snaps_tests/demos_tests/test_qt4_text_editor.py
- snaps_tests/demos_tests/test_qt5_text_editor.py
- snaps_tests/demos_tests/tests.py
> snapcraft update if there is no cache

- .travis.yml
- integration_tests/__init__.py
- integration_tests/test_clean_dependents.py
- integration_tests/test_snap.py
- integration_tests/test_store_download.py
- integration_tests/test_store_login_logout.py
- integration_tests/test_store_register.py
- integration_tests/test_store_upload.py
> Add a travis suite to run the staging store tests

- snapcraft/plugins/python3.py
This should mean that entry_points defined in the setup.py get created at the expected location as well as the modules installed in usr/lib/python3/dist-packages
> python3: use --root instead of --target

- integration_tests/test_store_register.py
The tests were failing because we added a new one that attempts to register
two snaps too fast, in order to check the error the store sends for too many
attempts. After the second registration, we need to wait a little so the
following tests can register without getting the same error.
LP: #1599268
> Fix the store integration tests

- snapcraft/internal/parts.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/test_commands_update.py
requests sends "Accept-Encoding: gzip, deflate" by default which causes
parts.snapcraft.io not to send an ETag, so the logic for detecting when
the parts cache is already up to date didn't work.  Use Last-Modified /
If-Modified-Since instead of ETag / If-None-Match.
> Fix parts cache handling

- snapcraft/tests/__init__.py
- snapcraft/tests/test_commands_define.py
- snapcraft/tests/test_commands_search.py
- snapcraft/tests/test_commands_update.py
- snapcraft/tests/test_yaml.py
Now that we run snapcraft update by deftault to get an initial
remote parts cache, most (not all) test require the FakeParts
fixture to be setup.
LP: #1600273
> Setup the FakeParts store for all unit tests

- snapcraft/storeapi/__init__.py
Small refactor to handle connection retries being
exhausted when trying to query status_details_url
from the snap-push store endpoint.
LP: #1600022
> yield the correct exception when retries are out

- integration_tests/test_maven_plugin.py
- snapcraft/plugins/maven.py
- snapcraft/tests/test_plugin_maven.py
- snaps_tests/__init__.py
Builds in Launchpad require use of an authenticated proxy, and honouring
https_proxy also seems like a good idea on general principles.  I've
switched to using xml.etree.ElementTree to construct settings.xml, as it
was getting more complicated and I'm not a big fan of constructing
non-trivial XML by concatenating strings; this requires the tests to
cope with differing whitespace.
I've dropped the SNAPCRAFT_SETUP_PROXIES environment variable.  Having
one environment variable that tells snapcraft to honour another
environment variable seems rather pointless, especially when it doesn't
actually change the contents of the resulting snap, but rather is just
part of the local networking environment that snapcraft needs to work
within.
LP: #1598193
> Make maven plugin honour https_proxy and proxy authentication

- integration_tests/test_parser.py
- snapcraft/internal/parser.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/test_parser.py
* Split wiki into separate entries so that a YAML error in
one document does not stop the parser from parsing the rest
of the documents.
* Use a FakeServer for integration tests.
LP:#1599598
> parser - Handle malformed wiki entries.

- demos/plainbox-test-tool/2016.com.example:simple/manage.py
- demos/plainbox-test-tool/2016.com.example:simple/units/simple.pxu
- demos/plainbox-test-tool/launchers/plainbox-wrapper
- demos/plainbox-test-tool/snapcraft.yaml
- integration_tests/snaps/simple-plainbox-provider/2016.com.example:simple/manage.py
- integration_tests/snaps/simple-plainbox-provider/2016.com.example:simple/units/simple.pxu
- integration_tests/snaps/simple-plainbox-provider/snapcraft.yaml
- integration_tests/test_plainbox_provider_plugin.py
- snapcraft/plugins/plainbox_provider.py
- snapcraft/tests/test_commands_list_plugins.py
- snaps_tests/demos_tests/test_plainbox_test_tool.py
lp: #1552369
Integration tests provided that check the plugin can be
used in several common Checkbox use cases.
> Create Plainbox Provider plugin

- snapcraft/internal/parser.py
- snapcraft/tests/test_parser.py
LP:#1597057
The first entry is retained and all duplicates are reported via a
warning and skipped.
> parser - Don't allow duplicate wiki entries.

- snapcraft/internal/parser.py
- snapcraft/tests/test_parser.py
- snapcraft/tests/test_pluginhandler.py
LP:#1591208
Signed-off-by: Joe Talbott <joe.talbott@ubuntu.com>
> Preserve the ordering of the wiki entries

- schema/snapcraft.yaml
- snapcraft/tests/test_yaml.py
This PR fixes LP: [#1595661](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1595661) by allowing "never" as a restart condition. Note that "never" is not a valid systemd restart condition, but snapcore/snapd#1551 maps "never" into systemd's "no."
> Support "never" as a daemon restart condition.

- snapcraft/__init__.py
- snapcraft/internal/sources.py
- snapcraft/plugins/autotools.py
- snapcraft/plugins/kernel.py
This fixes four trivial bugs ([1604280](https://pad.lv/1604280), [1604278](https://pad.lv/1604278), [1604305](https://pad.lv/1604305), [1604308](https://pad.lv/1604308)) which are typos in `snapcraft help`.
> Fix four typos in `snapcraft help`

- snapcraft/plugins/gradle.py
Put options before jar task in command.
https://bugs.launchpad.net/snapcraft/+bug/1602829
> Gradle plugin fix for command invocation.

- schema/snapcraft.yaml
- snapcraft/_baseplugin.py
- snapcraft/_schema.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/test_base_plugin.py
- snapcraft/tests/test_cmds.py
- snapcraft/tests/test_commands_update.py
- snapcraft/tests/test_yaml.py
Subparts from remote parts are separated by a / so we now need
too support this scenario in the parts definition.
LP: #1602728
> Allow / in parts

- snapcraft/main.py
- tour/00-SNAPCRAFT/01-easy-start/snapcraft.yaml
- tour/00-SNAPCRAFT/02-parts/snapcraft.yaml
- tour/10-SNAPS/01-service/snapcraft.yaml
- tour/10-SNAPS/02-service-confined/snapcraft.yaml
- tour/20-PARTS-PLUGINS/01-reusable-part/snapcraft.yaml
- tour/README.md
https://snapcraft.io doesn't work. We should link to http://snapcraft.io instead.
Also, `/create#begin` doesn't exist. I think `/create#tour` probably makes sense instead.
This came out of [two](https://github.com/ubuntudesign/snapcraft.io/issues/111) [bugs](https://github.com/ubuntudesign/snapcraft.io/issues/112) filed on the snapcraft.io project.
> Update broken links to https://snapcraft.io

- integration_tests/snaps/simple-pkgconfig/snapcraft.yaml
- integration_tests/test_pkg_config.py
- snapcraft/internal/pluginhandler.py
- snapcraft/tests/test_pluginhandler.py
The .pc files can have a different prefix when coming from the the parts
installdir and messes up the conflict checker so we handle this case when
doing the check for .pc files.
To make this work correctly we need to skip os.linking when dealing with
.pc files.
LP: #1604472
> Special handling for pc files for conflicts

- docs/snapcraft-syntax.md
- schema/snapcraft.yaml
Snapd supports this daemon type already so just allow to set this and
have it sent through.
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>
> Implement "oneshot" daemon type

- snapcraft/plugins/python3.py
Pass --root to the python3 plugin on build so data_paths with absolute paths will be placed in the install directoy of the part.
> Pass --root to the python3 plugin on build

- demos/webcam-webui/snapcraft.yaml
"camera" plug is needed to get the example working, and we should do the manual connection like to make it working:
$ sudo snap connect webcam-webui:camera ubuntu-core:camera
> Added "camera" plug into the example

- snapcraft/plugins/make.py
- snapcraft/tests/test_plugin_make.py
Each project is different on the install flag for the Makefile. Allow changing the make-install-var when building with snapcraft.
> Add make-install-var field to the make plugin.

- snapcraft/plugins/autotools.py
- snapcraft/tests/test_plugin_autotools.py
this enables vlc to build using the autotools plugin and have the plugin
transparently fall back from the regular autogen.sh to vlc's 'bootstrap'
script.
> add multiple generator script options to autotools

- snapcraft/plugins/python2.py
- snapcraft/tests/test_plugin_python2.py
LP:#1603110
There is currently no support for constraints[1] files with the python2 plugin. Some projects make heavy use of constraints. OpenStack is one such project
[1] https://pip.pypa.io/en/stable/user_guide/#constraints-files
> Add constraints to python2 plugin

- snapcraft/internal/lifecycle.py
- snapcraft/plugins/cmake.py
- snapcraft/tests/test_plugin_cmake.py
- snaps_tests/demos_tests/test_plainbox_test_tool.py
Fix indention errors that get the code checkers upset (LP: #1611402).
Signed-off-by: Christian Ehrhardt <christian.ehrhardt@canonical.com>
> fix checker errors to let runtests.sh pass again

- snapcraft/internal/yaml.py
- snapcraft/tests/__init__.py
- snapcraft/tests/test_commands_define.py
- snapcraft/tests/test_commands_search.py
- snapcraft/tests/test_commands_update.py
- snapcraft/tests/test_yaml.py
Load the remote parts in the config lazily.
LP: #1611828
> Start the fake parts server only in the tests that need it

- manual-tests.md
- snapcraft/internal/common.py
- snapcraft/internal/pluginhandler.py
- snapcraft/tests/test_plugin_copy.py
- snapcraft/tests/test_pluginhandler.py
shutil.copystat doesn't preserve owner/group so do it manually with
os.stat() and os.chown()
LP:#1605903
> Set owner/group for directories in stage and prime

- manual-tests.md
- snapcraft/internal/repo.py
This PR fixes LP: [#1612813](https://bugs.launchpad.net/snapcraft/+bug/1612813), making the cache work across filesystem boundaries.
> Use link_or_copy instead of just hard-links for deb cache.

- snapcraft/plugins/make.py
- snapcraft/tests/test_plugin_make.py
Some makefiles don't have an install target. This option allows specifying a list of artifacts to copy from the source directory to the install directory after running 'make'.
If the list of artifacts is not empty, the 'make install' step will be skipped and the artifacts will be copied by the plugin.
> Add artifacts option to make plugin.

- integration_tests/__init__.py
- integration_tests/snaps/yaml-in-subdir/file
- integration_tests/snaps/yaml-in-subdir/subdir/snapcraft.yaml
- integration_tests/snaps/yaml-in-subdir/subdir/subdirfile
- integration_tests/test_yaml_in_subdir.py
- snapcraft/internal/sources.py
- snapcraft/tests/test_sources.py
Currently when one puts the `snapcraft.yaml` in a subdirectory of the project (using `source: ..` etc.) snapcraft dies in a sea of recursion. This PR fixes LP: [#1600428](https://bugs.launchpad.net/snapcraft/+bug/1600428) by skipping over the directory containing the snapcraft.yaml if it's a subdirectory of the project.
> Support having the snapcraft.yaml in a subdir.

- snapcraft/plugins/make.py
Just helped debug a makefile based project that failed because 'install' was the default target, and running 'make && make install' broke the build. This clarification would've made it easier to understand what the plugin was actually doing.
> Clarification of make plugin help text

- snapcraft/internal/parser.py
- snapcraft/tests/test_parser.py
LP:#1602394
Signed-off-by: Joe Talbott <joe.talbott@ubuntu.com>
> parser - Return non-zero code for wiki errors.

- integration_tests/test_store_register.py
- snapcraft/storeapi/errors.py
- snapcraft/tests/store/test_store_client.py
The `-dispute` URL when registering is no longer valid as the register
and dispute URLs have been merged into one.
LP: #1613609
> Remove store dispute logic

- integration_tests/snaps/python-pyyaml/snapcraft.yaml
- integration_tests/test_python_plugin.py
- snapcraft/plugins/python3.py
- snapcraft/tests/test_plugin_python3.py
I only ran into this issue with python3 and not python2. I tested this with:
pyyaml:
plugin: python2
source: http://pyyaml.org/download/pyyaml/PyYAML-3.11.tar.gz
and
pyyaml:
plugin: python3
source: http://pyyaml.org/download/pyyaml/PyYAML-3.11.tar.gz
This branch only changes the python3 plugin as no issues occurred using the python2 plugin.
> Fix bug lp:1586546 allowing setup.py to work on some projects.

- snapcraft/plugins/python2.py
- snapcraft/plugins/python3.py
- snapcraft/tests/test_plugin_python2.py
- snapcraft/tests/test_plugin_python3.py
This will run pip install with --process-dependency-links as per [0].
[0] https://pip.pypa.io/en/stable/reference/pip_wheel/#cmdoption--process-dependency-links
LP: #1614186
> python plugins: add process-dependency-links option

- snapcraft/file_utils.py
- snapcraft/internal/parts.py
Use logger.debug() for chown warnings since they are expected to
fail for most use cases.
LP:#1614524
> Only show chown warnings with --debug.

- snaps_tests/demos_tests/test_ros.py
It is currently failing on yakkety due to gpg key errors with
the cache it is using.
LP: #1614476
> testing: only run the ros demo on xenial

- integration_tests/test_parts.py
- snapcraft/__init__.py
- snapcraft/internal/parser.py
- snapcraft/internal/parts.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/test_commands_define.py
- snapcraft/tests/test_commands_search.py
- snapcraft/tests/test_commands_update.py
- snapcraft/tests/test_parser.py
Make the parts.yaml, 'search', and 'define' output nicer.
* Use block style for multiline strings
* Support OrderedDict for all yaml usage.
* Only show the first line of the description in 'search' output.
LP:#1614651
> Use block style for multiline YAML values.

- HACKING.md
Also describe using `PYTHONHOME` as an alternative mechanism.
> HACKING.md: list dependencies to install with pip

- schema/snapcraft.yaml
- snapcraft/internal/lifecycle.py
- snapcraft/internal/meta.py
- snapcraft/internal/project_loader.py
- snapcraft/tests/test_cmds.py
- snapcraft/tests/test_commands_build.py
- snapcraft/tests/test_commands_clean.py
- snapcraft/tests/test_commands_cleanbuild.py
- snapcraft/tests/test_commands_init.py
- snapcraft/tests/test_commands_prime.py
- snapcraft/tests/test_commands_pull.py
- snapcraft/tests/test_commands_snap.py
- snapcraft/tests/test_commands_stage.py
- snapcraft/tests/test_lifecycle.py
- snapcraft/tests/test_meta.py
- snapcraft/tests/test_pluginhandler.py
- snapcraft/tests/test_project_loader.py
...to assert the built snap quality as per the snappy design doc, see https://docs.google.com/document/d/1MOwyQXkrmMjTJnMsiisfv5Y1lrr5mwNrTxaIbMpNngc/edit#heading=h.4wp4anfwdwtq for the explanation on the purpose of grade.
An upcoming subsequent PR (still depending on snapd changes) will introduce snap-build support that use this new grade parameter.
> Implementing 'grade' support in snapcraft.yaml

- snapcraft/plugins/nodejs.py
- snapcraft/tests/test_plugin_nodejs.py
This runs the build in the pull phase to download all needed dependencies.
There is no way to 'npm install --download-only'.
Additionally, we add the --cache-min=Infinity which is required.
Without it, the run in the build phase will try to reach the npm registry.
Lastly, instead of '-g', use the more self-documenting long form '--global'.
> node plugin: run build in pull phase to download dependencies.

- integration_tests/snaps/assemble/binary1.after
- snapcraft/internal/project_loader.py
- snapcraft/tests/test_project_loader.py
Hi,
This adds $SNAP/sbin and $SNAP/usr/sbin to the PATH in wrapper scripts generated by snapcraft. This is useful when staging packages with binaries in /sbin.
Cheers,
- Loïc Minier
> Include /sbin and usr/sbin in wrappers

- integration_tests/snaps/simple-ant/my-app/build.xml
- integration_tests/snaps/simple-ant/snapcraft.yaml
- integration_tests/test_ant_plugin.py
- snapcraft/plugins/ant.py
- snapcraft/tests/test_plugin_ant.py
Add options for setting ant properties, an ant build target, and the destination directory for ant build artifacts (point the right property at the snapcraft installdir). This change preserves compatibility with the old method of assuming jars will end up in target/.
The motivation was the Cassandra snap. It currently uses a [custom plugin](https://github.com/evandandrea/cassandra-snap/blob/e7f88807c9c0887f3df3dc5a7ca15b196b0cd604/parts/plugins/x-cassandra.py), which can be replaced with the following two settings to the ant plugin:
```
ant-dest-property: dist.dir
ant-build-target: artifacts
```
I'm completely open to changing the name of these options or altering their behaviour.
> Ant properties, build target, and destination directory options

- snapcraft/internal/parser.py
- snapcraft/internal/project_loader.py
- snapcraft/tests/test_parser.py
- snapcraft/tests/test_project_loader.py
Replace $SNAPCRAFT_PROJECT_VERSION and $SNAPCRAFT_PROJECT_NAME
with their respective values from the origin's snapcraft.yaml
in remote parts definitions.
LP:#1619418
> parser - Handle project name and version variables

- snapcraft/plugins/gulp.py
- snapcraft/tests/test_plugin_gulp.py
Fix the gulp plugin npm prefix install, by default gult is being installed globally in /usr/local/bin which is not a proper install prefix for a local snap,
One can easily test with e.g. the snapweb snapcraft install,
LP: #1621921
> Fix gulp plugin's npm install prefix

- snapcraft/internal/lifecycle.py
- snapcraft/tests/test_lifecycle.py
Execute the steps in order and skip early by keeping checks
in runtime. The parts to run are a list instead of a set to not lose
the sort order
LP: #1590599
> Improve lifecycle execution of steps

- snapcraft/internal/pluginhandler.py
- snapcraft/tests/test_pluginhandler.py
Currently snapcraft re-crawls the entire prime directory for dependencies each time a part is primed. If there are enough parts (and enough files to crawl) this can take an inordinate amount of time. This PR fixes LP: [#1575700](https://bugs.launchpad.net/snapcraft/+bug/1575700) by making sure each part has its files crawled exactly once.
> Only discover dependencies once per file.

- snapcraft/plugins/autotools.py
- snapcraft/tests/test_plugin_autotools.py
Sometimes an autotools-using project has a bootstrap directory, such as Basho's fork of Erlang (https://github.com/basho/otp) as used in Riak.
> Do not run the bootstrap directory as a script (autotools plugin).

- snapcraft/plugins/nodejs.py
- snapcraft/tests/test_plugin_nodejs.py
this PR makes the nodejs plugin download the devDependencies from package.json during the build phase.
https://bugs.launchpad.net/snapcraft/+bug/1623509
i have submitted the contributor agreement as well.
> LP: #1623509 nodejs: fix to install dev-deps in build phase

- integration_tests/test_parts.py
Insulate the parts integration tests against trivial differences in YAML
dump ordering of dictionaries.
> Fix parts integration tests

- docs/upload-your-snap.md
- integration_tests/__init__.py
- snapcraft/_store.py
- snapcraft/storeapi/__init__.py
- snapcraft/storeapi/errors.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/store/test_store_client.py
- snapcraft/tests/test_commands_login.py
- snapcraft/tests/test_commands_register_key.py
The store now returns an unambiguous error to indicate that two-factor
authentication is required, so we can use that to make the login process
behave how the UX specification says it should: only prompt for 2fa if
necessary, and provide a hint on a successful login without 2fa.
One obvious hack in this change is that we don't yet provide a
convenient per-store link for enabling 2fa, but instead just hardcode a
link to the SSO FAQ for now.  At the moment, people have to explicitly
opt into 2fa by joining a Launchpad team, which is a deliberate decision
because we don't have a good recovery facility and can't afford the
support bandwidth of doing manual recovery for millions of users.  When
this changes then we can also update snapcraft to do something more
graceful here, but for the …
> Adjust login to conform to UX specification

- snapcraft/storeapi/__init__.py
- snapcraft/storeapi/errors.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/store/test_store_client.py
"WWW-Authenticate: Macaroon needs_refresh=1" tells us that we need to
ask SSO to refresh our discharge macaroon, so do that.
LP: #1621171
> Refresh discharge macaroon if necessary

- snapcraft/internal/parser.py
- snapcraft/tests/test_parser.py
* Make the download location for source/origins mockable to
make cleaning up after tests easier.
LP:#1624099
> Don't litter /tmp with test artifacts.

- snapcraft/plugins/copy.py
- snapcraft/plugins/dump.py
- snapcraft/tests/test_plugin_copy.py
- snapcraft/tests/test_plugin_dump.py
This pull request enables crosscompilation for dump and copy plugins to be able to use them, for example, providing blobs after build a kernel snap for a different architecture.
> Enable crosscompilation for dump and copy plugins

- snapcraft/internal/lxd.py
- snapcraft/tests/test_lxd.py
Instead of setting up our own remote for each cleanbuild
invocation use the provided built-in image streams from
lxd.
LP: #1625787
> lxd: use built-in image streams.

- snapcraft/internal/parts.py
- snapcraft/tests/test_commands_search.py
- Accessing search matches' keys in alphabetical order when listing them
- Added test
---
Hello,
I started exploring snapcraft trying to fix some simple bugs. Please let me know if this can be accepted or it needs some changes.
Best regards
> Fixed bug LP: #1607294 snapcraft search returns results in different order

- snapcraft/plugins/python.py
- snapcraft/tests/test_plugin_python.py
The .pth files are needed by some projects to help with importing. We
currently filter them out, breaking imports for those projects.
LP: #1626668
> Don't filter .pth files in python plugin

- snapcraft/plugins/python.py
- snapcraft/tests/test_plugin_python.py
Only replace shebangs at the beginning of a file.
LP: #1626587
> python plugin: only replace proper shebangs.

- integration_tests/snaps/nodejs-with-run-commands/index.js
- integration_tests/snaps/nodejs-with-run-commands/package.json
- integration_tests/snaps/nodejs-with-run-commands/snapcraft.yaml
- integration_tests/test_nodejs_plugin.py
- snapcraft/plugins/nodejs.py
- snapcraft/tests/test_plugin_nodejs.py
Some complex projects don't install with “npm install”; rather they use “npm run” commands to drive their build, assembly, and packaging.
This support is required to build a snap from (at least) https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-
> nodejs plugin: Add mechanism to run “npm run” commands.

- integration_tests/test_store_sign_build.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/store/test_store_client.py
Even for building the local assertion, the command actually checks if the
account logged in has upload permission on the targeted snap (resolving
name to snap-id via account-info).
The test now builds an random snap, register the name in the store and
only then signs the snap. The fake server was extended to record registered
names and return them in the account-info endpoint.
> Fixing 'sign-build' integration tests.

- snapcraft/plugins/kernel.py
- snapcraft/tests/test_plugin_kernel.py
If modules end up having the same dependencies they would
of been copied twice, this transforms it into a set to
avoid duplicates.
LP: #1627923
> kernel plugin: allow collecting the same mod deps

- snapcraft/plugins/catkin.py
Our test cases all had python installed on the system, so the fact that the plugin used it went unnoticed. This PR fixes LP: [#1628990](https://bugs.launchpad.net/snapcraft/+bug/1628990) by using the in-snap python for build-time as well as run-time. It also pulls in gcc, libc-dev, and make as build packages.
> Catkin plugin: build with in-snap python.

- snapcraft/_baseplugin.py
- snapcraft/internal/pluginhandler.py
- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
Resolve LP: [#1629003](https://bugs.launchpad.net/snapcraft/+bug/1629003) by refactoring the repository source handling into a function that could be re-implemented by subclasses, as well as adding a map of ROS releases to Ubuntu releases. Should make it easy to support newer ROS releases, too.
> Catkin plugin: Support ROS Kinetic.

- debian/snapcraft-completion
- snapcraft/__init__.py
- snapcraft/_store.py
- snapcraft/main.py
- snapcraft/tests/test_commands_create_key.py
Wrapping `snap create-key` means that we don't confuse users by
expecting them to use two similar-but-different commands during the key
creation and registration workflow.  In addition, this augments
`snap create-key` by failing if a key with the same name is already
registered with the store, since a later registration attempt would fail
in that case.
> Add `snapcraft create-key`

- snapcraft/plugins/catkin.py
This PR fixes LP: [#1629955](https://bugs.launchpad.net/snapcraft/+bug/1629955) by adding information about the `rosdistro` parameter to the documentation printed when one runs `snapcraft help catkin`.
> catkin plugin: add `rosdistro` to help documentation.

- snapcraft/tests/test_parser.py
This makes refactoring what is mocked in the future easier
LP: #1630532
> Simplify the parser tests.

- snapcraft/tests/test_sources.py
Minimize mock declarations to one location and move tests to proper
test case classes.
LP: #1630632
> Simplify the handler from uri tests.

- integration_tests/test_store_sign_build.py
- snapcraft/_store.py
- snapcraft/tests/test_commands_list_keys.py
- snapcraft/tests/test_commands_sign_build.py
This way we can handle cases when the keyring is not setup, the selected key name is not present or selected key is not registered (LP #1629966).
Also prevent `snap sign-build` failures to create stray/empty '-build' files (LP #1629984).
> `sign-build` to prompt users for key selection

- demos/downloader-with-wiki-parts/test.c
This prevents the redirect from http to https.
LP: #1631463
> In the downloader demo test, use https

- snapcraft/plugins/go.py
Fixes #1553215. If the user's environment has GOBIN set, it will interfere
with the go plugin, forcing the end result executables to end up there instead of
the expected location.
> Set GOBIN in go plugin build environment.

- snapcraft/_store.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/store/test_store_client.py
- snapcraft/tests/test_commands_gated.py
LP: #1634173
* Show gated snaps that have no active validation
* Mark validations that don't match refresh-control as "not required"
* Show a date marking when validation was done.
> Handle 'broken' validations that don't match refresh-control

- snapcraft/plugins/python.py
- snapcraft/tests/test_plugin_python.py
This PR fixes LP: [#1630005](https://bugs.launchpad.net/snapcraft/+bug/1630005) by removing the `<partdir>/packages` when cleaning the pull step.
> Python plugin: remove pip packages when cleaning pull.

- debian/snapcraft-completion
Autocomplete the plugins after 'help'
Autocomplete directory names after 'snap' or 'tour'
Autocomplete all '.snap' files after 'gated, upload, push, sign-build, register' or 'validate'
> Add some further bash-completion

- snapcraft/internal/repo.py
LP: #1635611
Apt related cache now lives in `$HOME/.cache/snapcraft/apt/sources-list-digest/[apt, packages]` allowing for new top-level cache dirs for snapcraft unrelated to apt.
> Cache apt related files (config, packages) in 'apt' parent directory.

- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
This PR fixes LP: [#1638317](https://bugs.launchpad.net/snapcraft/+bug/1638317) by staging them at the beginning instead of doing so dependent upon whether `roscpp` is in the dependency list.
> Catkin plugin: Python nodes require gcc/g++ too.

- docs/snapcraft-syntax.md
- snapcraft/internal/repo.py
- snapcraft/tests/test_repo.py
This reverts LP: #1637282 as the syntax does not allow us to
do deb multiarch.
This reverts commit 9d6f953a18214a5ed39a6461a2cad07ef01f906f.
> Revert "Allow for architecture-specific packages (#876)"

- integration_tests/snaps/compressed-content-encoding/snapcraft.yaml
- integration_tests/test_dump_plugin.py
- snapcraft/internal/indicators.py
If Content-Encoding is set to a compressed stream we
currently crash badly, this handles it correctly.
LP: #1611776
> indicators: work with Content-Encoding set

- integration_tests/test_store_download.py
- snapcraft/_store.py
- snapcraft/storeapi/__init__.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/store/test_store_client.py
> store: download without login

- setup.py
- snapcraft/_store.py
- snapcraft/internal/cache/__init__.py
- snapcraft/internal/cache/_cache.py
- snapcraft/internal/cache/_snap.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/test_cache.py
- snapcraft/tests/test_commands_push.py
This feature will only be enabled with the `DELTA_UPLOADS_EXPERIMENTAL` environment variable set.
I was a little uncertain where `cache_snap()` should live; `repo` seemed like the most appropriate place, but perhaps you could provide some guidance there. Other thoughts are perhaps this should be SnapCache (similar to AptCache), rather than a solitary func, as we'll be providing pruning in a following branch (see discussion on Rocketchat)?
LP: #1639672
> cache: snap revision caching on 'push'

- integration_tests/__init__.py
- snapcraft/internal/repo.py
- snapcraft/tests/test_repo.py
This allows to clean them up by just running `apt-get autoremove` once the snapcrafting is done, but in any case it's not breaking anything as it only applies to packages that were not previously installed.
A simpler solution for https://bugs.launchpad.net/snapcraft/+bug/1640143
> repo: apt-mark new build-packages as automatically installed

- snapcraft/__init__.py
The documentation for stage-packages and build-packages
was outdated. Not taking into account the elf crawling logic
and basically incomplete in some other cases.
LP: #1642446
> help: update stage-packages and build-packages

- snapcraft/_store.py
- snapcraft/internal/cache/_cache.py
- snapcraft/internal/cache/_snap.py
- snapcraft/tests/test_cache.py
- snapcraft/tests/test_commands_push.py
This prune function will remove all the cached revision files expect the latest revision under the snapcraft’s xdg cache(XDG_CACHE_HOME/snapcraft/{project_name}/revisions),
So far I'm uncertain where should this revision prune function be invoked. now it's called right after the revision cache function is triggered in "snap push".
It's the following branch for PR: #889
LP: #1641512
> Snap revision prune

- snapcraft/internal/meta.py
- snapcraft/tests/test_meta.py
The icon entry in snapcraft.yaml is now (again) the preferred
method to have an icon in a snap, overriding the one in
the `setup` directory if necessary too.
LP: #1610268
> meta: icon is now dedeprecated

- snapcraft/_store.py
- snapcraft/internal/cache/_cache.py
- snapcraft/internal/cache/_snap.py
- snapcraft/tests/test_cache.py
Instances shouldn't need to have knowledge of the full config. Cleanup the logic a bit.
LP: #1642773
> cache: cleanup logic to pass project name

- snapcraft/internal/errors.py
- snapcraft/internal/sources.py
- snapcraft/tests/test_base_plugin.py
- snapcraft/tests/test_parser.py
- snapcraft/tests/test_sources.py
We are checking for missing commands and calling them packages. So
commands is what needs to be exposed. In addition to that, use `shutil.which`
instead of a straight out `subprocess` call.
LP: #1642799
> sources: missing command instead of package

- debian/snapcraft-completion
`_filedir "*.snap"` means only files that match `*.*.snap` get tab-completed.
> _filedir takes an extension, not a glob

- integration_tests/snaps/nodejs-with-run-commands/index.js
- integration_tests/snaps/nodejs-with-run-commands/package.json
- integration_tests/snaps/nodejs-with-run-commands/print.js
- integration_tests/snaps/nodejs-with-run-commands/snapcraft.yaml
- snapcraft/plugins/nodejs.py
Our install logic doesn't install dependencies during `pull` which makes
npm run commands that depend on these dependencies to fail.
LP: #1633298
> nodejs plugin: install during pull to support npm run

- debian/tests/snapstests
- integration_tests/snaps/ftp-source/snapcraft.yaml
- integration_tests/test_dump_plugin.py
- snapcraft/internal/common.py
- snapcraft/internal/indicators.py
- snapcraft/internal/sources.py
- snapcraft/tests/__init__.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/test_indicators.py
- snapcraft/tests/test_sources.py
As requested on bug https://bugs.launchpad.net/snappy/+bug/1602323
This adds support for FTP sources, using urllib was the quickest choice, and with some refactor of the indicator module, adding a progressbar was possible too. If using ftplib or others is preferred let me know, but I went for the fastest and safer way.
In theory this path could be used also for http(s) downloads, but not to change what we've done so far, I've left that job to the nicer `requests` library. `requests` being an HTTP only library has no native suppot for this, while trying to use something like [requests-ftp](https://pypi.python.org/pypi/requests-ftp) I don't think is a choice (looking quite immature).
> ftp source support

- snapcraft/internal/parser.py
- snapcraft/tests/test_parser.py
Ensure that we re-parse the parts that have missing dependencies after we've added all the valid ones to the `master_parts_list`
I would have fixed this in a cleaner way (allowing to include parts of a snapcraft.yaml that are good, and ignoring the bad ones only) but it would have caused a major refactor of the parser which probably is better to avoid.
Fixes [LP: #1645350](https://bugs.launchpad.net/snapcraft/+bug/1645350)
@josepht, please have a look to this.
> parser: support remote dependencies

- snapcraft/integrations/__init__.py
- snapcraft/integrations/tests/test_travis.py
- snapcraft/integrations/travis.py
- snapcraft/main.py
- snapcraft/tests/test_commands_enable_ci.py
This will allow users to refresh credentials bound to expire after 1 year
(clock-ticking bomb) or more likely when there is a SSO password change
(rotation).
Travis 'deploy' phase will fail on expired credentials, so users will know
when it's case to refresh.
We could issue macaroons that never expire (age or passwd-changes), but I guess it ends up being a lot more difficult to handle in case of compromise.
LP: #1646660
> cli: implement `enable-ci travis --refresh` command

- integration_tests/test_store_register.py
- snapcraft/storeapi/errors.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/store/test_store_client.py
- tools/staging_env.sh
On `snapcraft register` of a snap we already own we can just say
it is already owned by using the specific error code returned by
the store for this.
LP: #1602091
> store: return specific error when already owned

- integration_tests/snaps/local-source-subfolders/packaging/snap-package/snapcraft.yaml
- integration_tests/snaps/local-source-subfolders/packaging/snap-package/yes-really-deep/snapcraft.yaml
- integration_tests/snaps/local-source-subfolders/packaging/snapcraft.yaml
- integration_tests/snaps/local-source-subfolders/snapcraft.yaml
- integration_tests/test_local_source.py
- snapcraft/internal/sources.py
- snapcraft/tests/test_sources.py
This avoids to iterate over and over our ignored folders when launching snapcraft from a sub-sub-folder of the sources.
Added integration tests. Rewritten unit tests.
Fixes <a href='http://pad.lv/1644350'>LP: #1644350</a>
> sources: add current dir to ignore list if we're iterating on parent

- docs/snapcraft-parts.md
- integration_tests/__init__.py
- integration_tests/origin_options_wiki
- integration_tests/test_parser.py
- integration_tests/wrong_origin_options_wiki
- snapcraft/internal/parser.py
- snapcraft/tests/test_parser.py
Add support for more sources options, so that you can use multiple branches on remote part repositories.
@josepht
> parser: add support for origin-{branch,commit,tag}

- schema/snapcraft.yaml
- snapcraft/tests/test_meta.py
- snapcraft/tests/test_project_loader.py
The `confinement` property of `classic` should be supported.
<a href='https://bugs.launchpad.net/bugs/1647422'>LP: #1647422</a>
> meta: support classic confinment

- snapcraft/internal/sources/__init__.py
- snapcraft/tests/pluginhandler/test_pluginhandler.py
"no handler to manage source (gdsr://src)"
is a better error message than
"no handler to manage source"
since it makes easier to find out where the mistake is
> Add source name to error message

- snapcraft/internal/sources/__init__.py
- snapcraft/internal/sources/_local.py
- snapcraft/tests/sources/test_local.py
- snapcraft/tests/sources/test_sources.py
This PR makes more progress on LP: [#1648906](https://bugs.launchpad.net/snapcraft/+bug/1648906) by extracting the Local source into `sources/_local.py`.
> sources: refactor local source into module.

- snapcraft/internal/sources/__init__.py
- snapcraft/internal/sources/_script.py
- snapcraft/tests/__init__.py
- snapcraft/tests/sources/test_script.py
This PR makes more progress on LP: [#1648906](https://bugs.launchpad.net/snapcraft/+bug/1648906) by extracting the Script source into `sources/_script.py`.
It also implements some basic tests for the Script source.
> sources: refactor script source into module.

- snapcraft/internal/sources/__init__.py
- snapcraft/internal/sources/_subversion.py
- snapcraft/tests/sources/test_sources.py
- snapcraft/tests/sources/test_subversion.py
This PR makes more progress on LP: [#1648906](https://bugs.launchpad.net/snapcraft/+bug/1648906) by extracting the Subversion source into `sources/_subversion.py`.
> sources: refactor subversion source into module.

- demos/tomcat-maven-webapp/snapcraft.yaml
The `architectures` keyword just forces an architecture to be set on a built snap regardless the contents of the snap. This is effectively useless in this case.
LP: #1591414
> demos: do not force arch for the tomcat demo

- snapcraft/storeapi/__init__.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/store/test_store_client.py
- snapcraft/tests/test_commands_validate.py
Allow users to set `SNAPCRAFT_UBUNTU_STORE` and perform operations
on branded stores.
So far it only affects interactions with the Snap Index (CPI), which
already support the 'X-Ubuntu-Store' header and further permission
checks.
It will be probably used as the foundation for supporting push and
release for branded stores, instead of discrete '--store'.
LP: #1650210
> Support download and validate on branded stores.

- snapcraft/plugins/maven.py
- snapcraft/tests/test_plugin_maven.py
Updated the maven.py plugin to use the get_build_properties() method instead of modifying the schema.
https://bugs.launchpad.net/snapcraft/+bug/1649986
> Updated maven plugin to use get_build_properties()

- demos/gradle/snapcraft.yaml
- snapcraft/plugins/gradle.py
- snapcraft/tests/test_plugin_gradle.py
Updated the maven.py plugin to use the get_build_properties() method instead of modifying the schema.
https://bugs.launchpad.net/snapcraft/+bug/1649988
> Updated gradle plugin to use get_build_properties() 

- integration_tests/snaps/fake-curl-library/snapcraft.yaml
- integration_tests/snaps/fake-curl-library/src/fake-curl/CMakeLists.txt
- integration_tests/snaps/fake-curl-library/src/fake-curl/fake_curl.c
- integration_tests/snaps/fake-curl-library/src/main/CMakeLists.txt
- integration_tests/snaps/fake-curl-library/src/main/main.c
- integration_tests/test_library_precedence.py
- snapcraft/internal/libraries.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/tests/pluginhandler/test_pluginhandler.py
This PR fixes LP: [#1587358](https://bugs.launchpad.net/snapcraft/+bug/1587358) by checking that a system library isn't already available in the snap before migrating it in. Note that it checks part's installdir, the stagedir, and the primedir.
> Prefer in-snap libraries to system libraries.

- demos/java-hello-world/snapcraft.yaml
- snapcraft/plugins/ant.py
- snapcraft/tests/test_plugin_ant.py
Missed this plugin with my other batch because it never added to ['build-properties'] to throw the warning.
https://bugs.launchpad.net/snapcraft/+bug/1650547
> Updated ant plugin to use get_build_properties()

- snapcraft/plugins/cmake.py
- snapcraft/plugins/make.py
- snapcraft/tests/test_plugin_cmake.py
- snapcraft/tests/test_plugin_make.py
Updated make plugin to use get_build_properties().
Updated test_plugin_make as well to test this method.
https://bugs.launchpad.net/snapcraft/+bug/1650548
> plugins: update make plugin to use get_build_properties() 

- snapcraft/plugins/copy.py
- snapcraft/tests/test_plugin_copy.py
This PR finishes LP: [#1647899](https://bugs.launchpad.net/snapcraft/+bug/1647899) as this is the last of the plugins using the deprecated properties.
> plugins: update copy plugin to use get_build_properties().

- snapcraft/internal/project_loader.py
When compiling using classic confinement the core snap is needed, the check is correct but the error message is confusing.
LP: #1650946
> project loader: better error message for classic

- demos/hooks/snap/hooks/configure
- demos/hooks/snapcraft.yaml
- demos/pyhooks/configure_hook.py
- demos/pyhooks/snapcraft.yaml
- integration_tests/snaps/hooks/another-hook/another-hook
- integration_tests/snaps/hooks/configure-again/configure
- integration_tests/snaps/hooks/snap/hooks/configure
- integration_tests/snaps/hooks/snapcraft.yaml
- integration_tests/test_hooks.py
- schema/snapcraft.yaml
- snapcraft/internal/meta.py
- snapcraft/tests/__init__.py
- snapcraft/tests/commands/test_clean.py
- snapcraft/tests/commands/test_cleanbuild.py
- snapcraft/tests/commands/test_prime.py
- snapcraft/tests/commands/test_snap.py
- snapcraft/tests/pluginhandler/test_pluginhandler.py
- snapcraft/tests/test_meta.py
- snapcraft/tests/test_project_loader.py
- snaps_tests/demos_tests/test_hooks.py
- snaps_tests/demos_tests/test_pyhooks.py
Hooks are now supported in snapd and the click reviewer tools. Time to finish off LP: [#1586465](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1586465) by supporting them in snapcraft as well. This is done by convention, and two methods are supported:
1. Place hook executables in the `snap/hooks/` directory, and they will be copied into the snap automatically.
2. Install hook executables from parts into the `snap/hooks/` directory.
> Add support for hooks.

- debian/tests/control
- debian/tests/snapstests
- integration_tests/test_maven_plugin.py
- snapcraft/plugins/catkin.py
- snaps_tests/__main__.py
- snaps_tests/demos_tests/test_git.py
- snaps_tests/demos_tests/test_gradle.py
- snaps_tests/demos_tests/test_hooks.py
- snaps_tests/demos_tests/test_pyhooks.py
- snaps_tests/demos_tests/test_tomcat_maven_webapp.py
- snaps_tests/demos_tests/tests.py
> tests: fix snaps tests in armhf

- snapcraft/_store.py
- snapcraft/storeapi/__init__.py
- snapcraft/storeapi/errors.py
- snapcraft/tests/commands/test_push.py
- snapcraft/tests/store/test_store_client.py
LP: #1610776
This branch adds a precheck request to the store to `snapcraft push`, which in the case of an unregistered snap will report the error to the user before attempting a full upload.
> store: implement push pre-check.

- docs/snapcraft-syntax.md
Fix LP: [#1654900](https://bugs.launchpad.net/snapcraft/+bug/1654900) by documenting the `notify` daemon type. Also reformat daemon types section a little to be a list.
> Document `notify` daemon type.

- snapcraft/internal/common.py
- snapcraft/internal/lifecycle.py
- snapcraft/internal/meta.py
- snapcraft/tests/__init__.py
- snapcraft/tests/test_meta.py
When setting up the wrappers we need a mechanism so that LD_LIBRARY_PATH if set is set to not consume externally and use /snap/core/current as the alternate root.
LP: #1656187
> meta: support core libraries

- integration_tests/test_prime_filter.py
- snapcraft/internal/deprecations.py
> bdocs: update deprecation links

- snapcraft/storeapi/__init__.py
- snapcraft/tests/fake_servers.py
sso_host should be netloc not hostname
example: UBUNTU_SSO_API_ROOT_URL="http://sca-dev:9000/api/v2/"
LP: #1654564
> store: fix sso_host for dev sso

- snapcraft/internal/meta.py
- snapcraft/tests/test_meta.py
snap.yaml has no concept of desktop files, this
is a by-convention mechanism in snap.
LP: #1656487
> meta: ensure snap.yaml is desktop free

- snapcraft/_schema.py
- snapcraft/tests/test_project_loader.py
This PR fixes LP: [#1621726](https://bugs.launchpad.net/snapcraft/+bug/1621726) by adding hints for length-related schema validation errors.
> schema: print allowed length for length failures.

- snapcraft/file_utils.py
- snapcraft/tests/__init__.py
- snapcraft/tests/test_file_utils.py
This PR fixes LP: [#1658155](https://bugs.launchpad.net/snapcraft/+bug/1658155) by ensuring that `file_utils.link_or_copy_tree()` handles symlinks to directories the same way it handles symlinks to files.
> file_utils: copy symlinks to directories as symlinks.

- snapcraft/internal/meta.py
- snapcraft/tests/test_meta.py
https://bugs.launchpad.net/snapcraft/+bug/1658123
> Fix Exec key in desktop files for apps named like their parent package (LP: #1658123).

- snapcraft/plugins/catkin.py
- snapcraft/tests/plugins/test_catkin.py
Instead of pulling necessary compilers in as stage packages, this PR fixes LP: [#1658828](https://bugs.launchpad.net/snapcraft/+bug/1658828) by pulling them to an alternate working area (similar to rosdep) so they can be used without unnecessarily ending up in the final snap.
> catkin plugin: don't stage compilers.

- snapcraft/plugins/python.py
- snapcraft/tests/plugins/test_python.py
Before, there was one command for downloading the packages in
requirements file, one for the ones in setup.py, and one for downloading
the manually specified packages.
That broke the case where you specify high-level dependencies in
setup.py without version-specific contstraints and use requirements.txt
to pin the packages to specific versions. The end result was that even
though packages were pinned in requirements.txt, snapcraft would
download the latest versions of packages.
LP: [#1659234](https://bugs.launchpad.net/snapcraft/+bug/1659234)
> Download all Python packages in the python plugin using one command.

- snapcraft/internal/meta.py
- snapcraft/tests/test_meta.py
This will help unity8 associate them (LP: #1659330).
> Rename desktop files to match the app names.

- debian/control
- integration_tests/test_hardlink_src_old_tree.py
- snapcraft/_options.py
- snapcraft/plugins/gulp.py
- snapcraft/plugins/nodejs.py
- snapcraft/tests/plugins/test_gulp.py
- snapcraft/tests/plugins/test_nodejs.py
- snapcraft/tests/test_options.py
- snapcraft/tests/test_project_loader.py
It might happen in 32bit containers running on 64bit hosts, that
they are detected as 64bit systems since platform's machine()
returns the kernel's architecture, not the userspace one.
Using `gcc -v` `Target:`'s value instead
LP: [#1641123](https://bugs.launchpad.net/snapcraft/+bug/1641123)
> options: use actual userspace architecture for building in 32bit

- snapcraft/plugins/autotools.py
- snapcraft/plugins/make.py
- snapcraft/tests/plugins/test_autotools.py
- snapcraft/tests/plugins/test_make.py
We can use the self.make function from make instead of redefining the build process again here.
LP: #1659363
> autotools: extend Make plugin instead of repeating code

- snapcraft/internal/sources/_local.py
- snapcraft/tests/sources/test_local.py
This PR fixes LP: [#1659653](https://bugs.launchpad.net/snapcraft/+bug/1659653) by preserving any symlinks to directories within local sources instead of creating a new directory.
> local source: preserve symlinks to directories.

- snapcraft/tests/commands/test_cleanbuild.py
It's not relevant to the test.  This strips 5 seconds off the test
run-time.
Checklist:
- Have you signed the contributor licence agreement?
https://www.ubuntu.com/legal/contributors
I assume being a Canonical employee is sufficient?
- Is there a reported a bug for the problem you are fixing?
Given this is a test cleanup, I'm assuming I don't need one.
- Have you read our contribution guide?
[CONTRIBUTING.md](CONTRIBUTING.md)
I have now!
> Don't wait for lxd networking in cleanbuild test

- snapcraft/_options.py
- snapcraft/tests/test_options.py
platform.machine() is returning armv8l instead of aarch64 on
some architectures when on a 32bit userspace. This addresses that
problem.
LP: #1641123
> options: add armv8l to list of translations.

- snapcraft/internal/project_loader.py
- snapcraft/tests/test_project_loader.py
From _dl_map_object in elf/dl-load.c:
```
Unless loading object has RUNPATH:
RPATH of the loading object,
then the RPATH of its loader (unless it has a RUNPATH), ...,
until the end of the chain, which is either the executable
or an object loaded by dlopen
Unless executable has RUNPATH:
RPATH of the executable
LD_LIBRARY_PATH
RUNPATH of the loading object
ld.so.cache
default dirs
```
LP: #1657504
> core: switch to using rpath for clasic confinement.

- snapcraft/internal/meta.py
- snapcraft/tests/test_meta.py
Get the extension as the last item of the splitted file path
LP: [#1660377](https://bugs.launchpad.net/snapcraft/+bug/1660377)
> meta: properly get the icon extension from splitted name

- schema/snapcraft.yaml
- snapcraft/_schema.py
- snapcraft/internal/errors.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/project_loader.py
- snapcraft/plugins/copy.py
- snapcraft/tests/plugins/test_copy.py
- snapcraft/tests/test_project_loader.py
Snapcraft supports a few different objects in its schema that don't enforce the actual presence of a vaue in its items. Of interest in this PR is the `organize` keyword in the core, as well as the `files` keyword in the copy plugin.
This PR fixes LP: [#1587455](https://bugs.launchpad.net/snapcraft/+bug/1587455) by modifying the schema of both the core and the copy plugin to enforce both the type and the presence of values.
> schema,copy plugin: better errors when item has no value.

- snapcraft/internal/lifecycle.py
- snapcraft/tests/commands/test_cleanbuild.py
The `prime/` directory was historically called `snap/`. As a result, snapcraft has code to ignore the `snap/` directory when creating a tarball for cleanbuild. However, the `snap/` directory has recently come back in another form, and it's necessary for building. This PR fixes LP: [#1661391](https://bugs.launchpad.net/snapcraft/+bug/1661391) by no longer ignoring it when creating the cleanbuild tarball.
> cleanbuild: include snap directory in tarball.

- integration_tests/snaps/qbs-nil/main.cpp
- integration_tests/snaps/qbs-nil/qbs-nil-snap.qbs
- integration_tests/snaps/qbs-nil/snapcraft.yaml
- integration_tests/snaps/qbs-qt/main.cpp
- integration_tests/snaps/qbs-qt/qbs-qt-snap.qbs
- integration_tests/snaps/qbs-qt/snapcraft.yaml
- integration_tests/test_qbs_plugin.py
- snapcraft/plugins/qbs.py
- snapcraft/tests/commands/test_list_plugins.py
- snapcraft/tests/plugins/test_qbs.py
This plugin supports building any applications that use gcc or clang
toolchains, as well as Qt(4&5) based applications.
LP: [#1659537](https://bugs.launchpad.net/snapcraft/+bug/1659537)
> Add snapcraft plugin for Qt Build Suite (qbs)

- manual-tests.md
- snapcraft/plugins/catkin.py
- snapcraft/tests/plugins/test_catkin.py
Currently, apps created in snaps that use the Catkin plugin source ROS's setup.sh. However, this means that the setup.sh attempts to parse any command-line parameters passed to the app in question, which is never desired and will break things most of the time parameters are actually used.
This PR fixes LP: [#1660852](https://bugs.launchpad.net/snapcraft/+bug/1660852) by by saving off any parameters, zeroing them right before sourcing setup.sh, and restoring them before execing the binary in question.
Thanks to @didrocks for the initial approach, though I doubt you thought it'd be this yucky, eh?
> catkin plugin: don't pass args to setup.sh.

- demos/git/snap/snapcraft.yaml
- demos/tomcat-maven-webapp/snap/snapcraft.yaml
- demos/tomcat-maven-webapp/wrapper
- schema/snapcraft.yaml
- snapcraft/internal/meta.py
- snapcraft/tests/test_meta.py
- snapcraft/tests/test_project_loader.py
> meta: support for the environment keyword.

- snapcraft/internal/meta.py
- snapcraft/tests/test_meta.py
dn2 was incorrectly setup when it should have been dn3.
LP: #1661956
> meta: correct the deprecation for `setup/gui` use.

- snapcraft/internal/deltas/__init__.py
- snapcraft/internal/sources/__init__.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/test_deltas_xdelta3.py
I was annoyed by these warnings... 
LP: [#1659816](https://bugs.launchpad.net/snapcraft/+bug/1659816)
> snapcraft: fix or ignore PEP8 static errors

- snapcraft/tests/__init__.py
- snapcraft/tests/fixture_setup.py
The unit tests have a glitch where the progress bar when snapping
gets leaked into the reporting. This adds a fixture to silence it.
LP: #1662652
> tests: avoid snapping progress to leak into report

- manual-tests.md
- snapcraft/internal/lifecycle.py
- snapcraft/internal/lxd.py
- snapcraft/main.py
- snapcraft/tests/test_lxd.py
Add the --remote option to cleanbuild which would build the
project on the selected lxd remote.
LP: #1599578
> cleanbuild: allow talking to a remote.

- snapcraft/plugins/kbuild.py
- snapcraft/plugins/kernel.py
- snapcraft/tests/plugins/test_kernel.py
Hi,
This fixes the kernel snap layout for firmware/ and modules/; I've build tested this against the ONL example linked in the bug and prime/ now properly contains a modules/ and firmware/ toplevel.
(Also small fix to list of required packages; these packages were missing on top of a clean Ubuntu 16.04 EC2 instance)
Cheers,
-- Loïc
> kernel plugin: fix kernel snap layout

- integration_tests/snaps/plainbox-provider-with-stage-packages/2016.com.example:simple/manage.py
- integration_tests/snaps/plainbox-provider-with-stage-packages/2016.com.example:simple/units/simple.pxu
- integration_tests/snaps/plainbox-provider-with-stage-packages/snapcraft.yaml
- integration_tests/test_plainbox_provider_plugin.py
- snapcraft/plugins/plainbox_provider.py
- snapcraft/plugins/python.py
- snapcraft/tests/plugins/test_plainbox_provider.py
When a part that uses the plainbox-provider plugin adds a `stage-packages`
entry for a python3 package, conflicts will occur as this plugin
most likely always comes `after` a python part that actually
adds functionality.
Given that sitecustomize.py will be different and the one added
by `stage-packages` is not really useful in a snap we filter it out.
LP: #1663792
> plainbox-provider plugin: filter out sitecustomize

- debian/control
snapcraft.tests.sources.test_git expects to be able to call git, so
snapcraft should build-depend on it directly.
LP: [#1663605](https://bugs.launchpad.net/snapcraft/+bug/1663605)
> Build-depend on git

- demos/96boards-kernel/snap/snapcraft.yaml
The 96boards example doesn't produce a kernel snap that boots on the Dragonboard410c, and these are the required changes to get a working kernel snap:
CONFIG_MMC*: to avoid hanging during boot when initrd can't find a valid /dev/disk... paritition
CONFIG_EXT4: this is self explanatory
CONFIG_BLK_DEV_LOOP: to avoid a "can't mount loop device: no space left on device" error on boot
And while here, unpack firmware.tar to /firmware.
Tested on my dragonbroard, generating a new image from scratch.
Thanks for helping us make a better Snapcraft!
LP: #1665650
> snapcraft.yaml: 96boards: minimal changes to get a working kernel snap

- CONTRIBUTING.md
This PR resolves LP: [#1665760](https://bugs.launchpad.net/snapcraft/+bug/1665760) by adding a commit message template to the contribution guide. This hopefully will help newer contributors write better commit messages.
> contribution guide: add commit message template

- debian/tests/control
- integration_tests/snaps/ftp-source/snapcraft.yaml
- integration_tests/test_dump_plugin.py
- requirements-devel.txt
kernel.org has just shut down the ftp server, so we need to use a different one.
To avoid this happening again, the test starts a local ftp server.
This adds python3-pyftpdlib to the autopkgtest dependencies.
LP: [#1669541](https://bugs.launchpad.net/snapcraft/+bug/1669541)
> tests: update the ftp source for integration test

- snapcraft/_options.py
The existing code did not handle relative symlinks correctly, they were
expanded relative to /snap/core/current, not the directory they resided in.
This is why classic snap builds only worked on amd64 and ppc64el on Launchpad.
LP: [#1665165](https://bugs.launchpad.net/snapcraft/+bug/1665165)
No test because I don't see how to add one (afaict, get_core_dynamic_linker is currently untested).
> core: fix symlink resolution in get_core_dynamic_linker

- snapcraft/plugins/godeps.py
The godeps plugin runs "go get github.com/rogpeppe/godeps", which
requires git to be installed.
LP: #1671546
> godeps plugin: add git to build-packages

- snapcraft/file_utils.py
- snapcraft/internal/repo.py
- snapcraft/tests/test_repo.py
After unpacking stage-packages, the repo runs a number of fixup steps. One of those steps is to rewrite `usr/bin/xml2-config` and `usr/bin/xslt-config` to look within the part instead of on the host. However, this rewrite is done with sed, which has performance issues as well as poor side effects when it comes to the plugin environment.
This PR fixes LP: [#1671675](https://bugs.launchpad.net/snapcraft/+bug/1671675) by using python to fix those files instead of sed.
**Note:** This PR affects the public `file_utils` API by exposing the previously private `file_utils._search_and_replace_contents` as `file_utils.search_and_replace_contents`.
> repo: fixup with python, not sed

- integration_tests/__init__.py
- snapcraft/storeapi/__init__.py
Calling anything related to the store, more so when dealing with CDNs
has become extremely flaky. This registers an adapter to enabled a
maximum retry count of 5 before giving up on connection resets.
LP: #1671817
> store: enable retries for store calls.

- snapcraft/_options.py
When building with classic confinement the logic was to check
if what was defined as ld existed, but it wouldn't if it was
a symbolic link so check for that in the first check as well.
LP: #1672496
> core: resolve ld link first.

- snaps_tests/demos_tests/test_busybox.py
- snaps_tests/demos_tests/test_mosquitto.py
snapd in zesty now creates a symlink from `~/snap/<name>/current`
to `~/snap/<name>/<revision>`. We need to take this into account
when searching for files in the snaps directories.
LP: #1672463
> tests: take into account the new current link.

- snapcraft/tests/plugins/test_ant.py
- snapcraft/tests/plugins/test_autotools.py
- snapcraft/tests/plugins/test_gradle.py
- snapcraft/tests/plugins/test_kbuild.py
- snapcraft/tests/plugins/test_make.py
- snapcraft/tests/plugins/test_maven.py
- snapcraft/tests/plugins/test_scons.py
- snapcraft/tests/plugins/test_waf.py
`stage-packages` handling has been moved to the core of snapcraft so this patching is not needed anymore. We remove it for everything except the catkin tests as it uses its own Ubuntu instance to fetch in the plugin code.
LP: #1672909
> tests: remove repo.Ubuntu patch for plugins

- demos/ros/src/listener/scripts/listener_node
- demos/ros/src/listener/talk_and_listen.launch
- demos/shared-ros/ros-app/bin/run-system
- demos/shared-ros/ros-app/src/listener/scripts/listener_node
- demos/shared-ros/ros-app/src/listener/talk_and_listen.launch
- snaps_tests/demos_tests/test_ros.py
- snaps_tests/demos_tests/test_shared_ros.py
The ROS demos bring up their systems via `roslaunch`. Such systems come up together and are brought down together with `SIGINT`. However, while this makes them somewhat realistic demos, running forever makes them difficult to test in CI.
This PR fixes LP: [#1673621](https://bugs.launchpad.net/snapcraft/+bug/1673621) by adding a parameter to both ROS demos called `exit-after-receive` which, if set, will cause the demos to exit successfully after the listener receives one message. The tests then set this parameter and use regex on the output to verify success.
> demos: make ROS demos support exiting after success

- snapcraft/internal/lifecycle.py
- snapcraft/internal/lxd.py
- snapcraft/tests/commands/test_cleanbuild.py
- snapcraft/tests/test_lxd.py
Don't use the repo to detect if lxd is available as this will prevent use when lxd is provided as a snap or manually installed.
It also makes the logic packaging , agnosting, meaning that a translation layer to figure out what provides the `lxc` command is not necessary.
The work here also migrates the detection out of the lifecycle and into the lxd module.
LP: #1666735
> cleanbuild: packaging independent detection.

- manual-tests.md
LP: [#1590258](https://bugs.launchpad.net/snapcraft/+bug/1590258)
> tests: add manual tests for the kernel snaps

- snapcraft/plugins/kbuild.py
Linux's kernel Makefile gets confused if it is invoked with the
environment already setup by another Linux's Makefile:
linux/package/Makefile -> snapcraft -> linux/Makefile
fix the problem removing the offending make variable (MAKEFLAGS)
LP: #1665661
> kernel plugin: rework MAKEFLAGS from the environment

- snapcraft/plugins/kernel.py
- snapcraft/tests/plugins/test_kernel.py
The module path is always the second item.
LP: #1675029
> kernel plugin: fix modprobe output parsing.

- snapcraft/internal/lxd.py
- snapcraft/tests/commands/test_cleanbuild.py
- snapcraft/tests/test_lxd.py
The cache copy logic needs some more design. Currently it copies in the cache regardless of the  target. We need to be smart and only copy the matching hashes. It also needs to weigh in non local remotes and provide user visible feedback in the case where the cache is copied to a non local remote.
LP: #1669730
> cleanbuild: don't copy cache into container.

- snap/snapcraft.yaml
- snapcraft/internal/common.py
- snapcraft/internal/repo/_platform.py
The tour did not have the brains to properly bootstrap itself when snapcraft was used as a snap.
This also fixes a blcoker for the snap wrt the repo detection.
LP: #1674952
> tour: make it work when its a snap.

- integration_tests/__init__.py
- snapcraft/internal/indicators.py
- snapcraft/storeapi/__init__.py
- snapcraft/storeapi/errors.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/store/test_store_client.py
Use the retry class which allows for more fine grained settings such as forcing a retry when a status code is returned.
LP: #1671817
> store: better retry strategy for GETs.

- snapcraft/plugins/nodejs.py
> nodejs plugin: switch to the newer LTS.

- snapcraft/internal/libraries.py
- snapcraft/tests/test_libraries.py
When collecting libraries when working with classic confinement
we currently collect snaps of our own doing if installed. This
small fix avoids that.
Ideally it would have been good to just add the `no-system-libs`
`build-attributes` but the side effects there are a bit too big
as some libraries are still collected when dealing with snaps
that depend on other snaps.
LP: #1670100
> pluginhandler: exclude `/snap/` from libraries.

- snapcraft/plugins/nodejs.py
Move from 6.10.1 to 6.10.2 as 6.10.1 404s
> nodejs plugin: switch to the newer LTS. (#1228)

- bin/snapcraft-classic
- snap/snapcraft.yaml
- snapcraft/__init__.py
The current implementation as of 3.6 in for find_library in ctypes.util makes use of `ldconfig -p` which depends on the current ld cache which in effect has no knowledge of any library in $SNAP. What makes matters worse is that it will provide results for on host libraries we do NOT want.
LP: #1678289
> core: find the correct libraries as a snap.

- snap/snapcraft.yaml
Since launchpad doesn't support git:// references in code and
the https handler for gnupg is currently broken it seems
appropriate to use the release tarball.
> snap: use the gpg tarball instead of git://.

- snapcraft/internal/repo/_platform.py
- snapcraft/internal/repo/errors.py
Added `elementary` and `"elementary"`. The former for when the
latter is fixed if at all.
LP: #1678286
> repo: enable elementary.

- snapcraft/_store.py
- snapcraft/storeapi/__init__.py
- snapcraft/storeapi/_upload.py
- snapcraft/tests/commands/test_push.py
Use basename of file to leave space for the widget (useful when pushing a delta).
Don't print the 'Upload' message twice and don't leave a trailing spinner after the release is complete.
Upload renamed to push to be more consistent.
LP: #1625784
> cli: improve push output.

- tools/retry_autopkgtest.sh
LP: [#1680960](https://bugs.launchpad.net/snapcraft/+bug/1680960)
> tests: update the location of the upstream retry autopkgtests script

- snapcraft/internal/repo/_platform.py
Currently Snapcraft doesn't work on KDE Neon, an Ubuntu-based distribution which includes latest KDE software. This PR fixes it.
Distribution ID is `neon`. See following for evidence:
```shell
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.linux_distribution()
('neon', '16.04', 'xenial')
```
> repo: enable KDE Neon.

- README.md
Thanks for helping us make a better Snapcraft!
Checklist:
- Have you signed the contributor licence agreement?
https://www.ubuntu.com/legal/contributors
Yes.
- Is there a reported a bug for the problem you are fixing?
https://bugs.launchpad.net/snapcraft/
If there is none, please report it. Once you have the BUG_NUMBER,
replace it here:
Nop... But it's just a minor fix in README....
- Have you read our contribution guide?
[CONTRIBUTING.md](CONTRIBUTING.md)
Yes.
-----
The doc folder was removed in #1227. This fixes/removes the links in README.
> Fixed links to doc

- integration_tests/test_git_source.py
- snapcraft/internal/lifecycle.py
- snapcraft/internal/meta.py
- snapcraft/internal/sources/__init__.py
- snapcraft/internal/sources/_git.py
- snapcraft/internal/sources/errors.py
- snapcraft/tests/sources/test_git.py
If `version: git` is set, snapcraft will determine
the version using git and its tags.
> meta: version from git support.

- integration_tests/snaps/version-script/snap/snapcraft.yaml
- integration_tests/test_version_script.py
- schema/snapcraft.yaml
- snapcraft/internal/lifecycle.py
- snapcraft/internal/meta.py
- snapcraft/internal/project_loader.py
- snapcraft/tests/test_meta.py
- snapcraft/tests/test_project_loader.py
If `version-script` is defined it will override the visible version that ends up in snap.yaml.
> meta: override the version with version-script.

- integration_tests/__init__.py
- integration_tests/test_build_package_version.py
- integration_tests/test_pull_properties.py
The integration tests locked down on a version of "hello" which is error prone. We now get the version using rmadison like logic.
> tests: fix package version pinning tests.

- snapcraft/internal/common.py
- snapcraft/internal/repo/_deb.py
If snapcraft is used from another snap it won't work properly because it's guessing if it's itself a snap in a sloppy manner.
1. SNAP=/snap/doesntevenexist/123
2. export SNAP
3. $ snapcraft
Issues while validating snapcraft.yaml: snapcraft validation file is missing from installation path
snapcraft validation file is missing from installation path
> core: check SNAP_NAME to detect if snapcraft is a snap.

- bin/snapcraft-classic
LP: #[1685530](https://bugs.launchpad.net/snapcraft/+bug/1685530)
> core: predetermine the magic path when a snap.

- manual-tests.md
- snapcraft/internal/lifecycle.py
- snapcraft/internal/lxd.py
- snapcraft/main.py
- snapcraft/tests/commands/test_snap.py
All commands around building snaps and dealing with parts will be passed through into the lxd container.
> lxd: pass through commands into the container

- snapcraft/plugins/kbuild.py
- snapcraft/tests/plugins/test_kbuild.py
- snapcraft/tests/plugins/test_kernel.py
Instead of using shell scripts wrapper, simply teach snapcraft how to extract the entire ubuntu config from debian.$branch/config/ and debian.$branch/config/$arch/config*$flavour files.
To test this, checkout an ubuntu kernel tree:
$ git clone git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/xenial
$ cd xenial
And use a snapcraft.yaml like this:
$ rm snapcraft.yaml
$ cat >> snapcraft.yaml << EOF
name: ubuntu-generic-kernel
version: 4.4.0
summary: The generic kernel for snappy
description: This is a generic snapped kernel, based off the xenial src and config
type: kernel
parts:
kernel:
plugin: kernel
source: .
source-type: git
kconfigflavour: generic
kconfigs:
- CONFIG_LOCALVERSION="-xenial_generic"
- CONFIG_DEBUG_INFO=n
kernel-image-target: bzImage
EOF
and snap it:
$ …
> kernel plugin: learn how to assemble the ubuntu config using kconfigflavour

- snapcraft/plugins/kbuild.py
- snapcraft/plugins/kernel.py
- snapcraft/tests/plugins/test_kernel.py
Make snapcraft smarter by parsing .config and initrd modules list and printing out if there are mandatory options missing, or if a boot required piece of code is not builtin or part packaged into initrd
LP: #1676806
> kernel plugin: check_config() and check_initrd() support

- integration_tests/plugins/test_rust_plugin.py
- snapcraft/plugins/rust.py
- snapcraft/tests/plugins/test_rust.py
LP: [1685563](https://bugs.launchpad.net/snapcraft/+bug/1685563)
> rust snaps can now use source-subdir without failing on pull

- snapcraft/_options.py
- snapcraft/internal/lxd.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/test_lxd.py
To support cross-compilation in LXD containers the image for the host architecture needs to be used, rather than for the target architecture, which would require slow qemu emulation. It's worth noting that host here means the host running LXD which may not be the same as the host running snapcraft eg. snapcraft executed on an armhf machine using an amd64 remote building for arm64.
Note: this is orthogonal to actual support for cross-compilation in individual plugins and only deals with the container setup.
> lxd: Setup image and target arch for cross-compilation

- schema/snapcraft.yaml
- snapcraft/internal/sources/__init__.py
- snapcraft/tests/test_parser.py
Invalid source-type defaults to Local source (handler) and it doesn't print an error message
LP: [#1650943](https://bugs.launchpad.net/snapcraft/+bug/1650943)
I canceled previous PR cause I commited some changes using an incorrect email.
Based on the feedback provided on the canceled PR:
1. I added the list of valid source types in the snapcraft.yaml using an enum
2. I changed the way _source_handler dict is called, so we can get a KeyError if the source type is invalid for API users
3. I added the Local source type to the _source_handler dict, so it can be used as the default value
> sources: validate unknown source-type in yaml

- snapcraft/plugins/kernel.py
- snapcraft/tests/plugins/test_kernel.py
Slightly improve the messaging of check_config(), by specifying if a kernel option applies only to a certain kernel version:
...
CONFIG_CC_STACKPROTECTOR_STRONG (4.1.x and later versions only)
...
CONFIG_DEVPTS_MULTIPLE_INSTANCES (4.8.x and earlier versions only)
...
No functional changes were introduced in this diff, just the messaging text.
LP: #1689564
> kernel plugin: slightly improve the messaging of check_config()

- snapcraft/internal/lxd.py
- snapcraft/tests/fixture_setup.py
LXD recently renamed the kernelarchitecture field to kernel-architecture so snapcraft is unwittingly not backwards-compatible.
This was filed as [bug 1689712](https://bugs.launchpad.net/snapcraft/+bug/1689712).
> Use architectures field which existed in older LXD

- HACKING.md
Noticed that these packages were missing when I ran `./runtests.sh`.
> add missing VCS dependencies to HACKING.md

- snapcraft/plugins/kernel.py
The DMIID config option is only present if a DMI EFI table is present, and since some ubuntu core targets (e.g. armhf) don't support EFI, it's better to stop warning about its absence.
LP: #1691116
> kernel plugin: config check: remove DMIID option

- snapcraft/cli/lifecycle.py
- snapcraft/tests/commands/test_snap.py
Return a proper error code when failing to snap
> cli: proper error for failed snap command

- snaps_tests/tour_tests/20-PARTS-PLUGINS/test_01_reusable_part.py
This reverts commit 2bd87c5afe5322951647366f61af2ff8281f9e2c.
It was originally thought to be a problem with the tested code, but
in the end it was a snapcraft problem.
> Revert "tests: remove the reusable parts tour test (#1321)"

- snapcraft/internal/indicators.py
- snapcraft/storeapi/__init__.py
> storeapi: resume snap downloads

- snapcraft/storeapi/__init__.py
In June 2016, the store added support for an X-Ubuntu-Series header to
be used in preference to X-Ubuntu-Release.
LP: #1691351
> store: send X-Ubuntu-Series, not X-Ubuntu-Release

- HACKING.md
Snapcraft previously did not run from within a virtualenv, so we only recommended installing its dependencies via pip. This was always confusing, and these days snapcraft actually _does_ run from within a virtualenv, so let's make those directions more prominent in HACKING.md.
> HACKING: make running from virtualenv more obvious

- snapcraft/plugins/qmake.py
- snapcraft/tests/plugins/test_qmake.py
Right now it is necessary to manually specify the Qt version to use for the QMake plugin.
For convenience however, the default value should be qt5, as discussed on Launchpad: 
[LP: #1633278](https://bugs.launchpad.net/snapcraft/+bug/1633278)
> qmake plugin: set default qt version

- snapcraft/plugins/python.py
setuptools v36.0.0 (released today) requires that six is installed before it can be used. This PR fixes LP: [#1694945](https://bugs.launchpad.net/snapcraft/+bug/1694945) by doing exactly that.
> python plugin: install six before using setuptools

- tour/00-SNAPCRAFT/01-easy-start/snapcraft.yaml
- tour/00-SNAPCRAFT/02-parts/snapcraft.yaml
Snapcraft tour should download sources
via https instead of http.
See [LP: #1634415](https://bugs.launchpad.net/snapcraft/+bug/1634415)
Should the `source-checksum` feature be used in addition?
> tour: use https for source urls

- snapcraft/internal/sources/_git.py
- snapcraft/tests/sources/test_git.py
Remote in updating submodules means the tip of the remote branch is
checked out, not the commit recorded in the superproject.
This means the project loses control over what content is actually
checked out.
LP: [#1694765](https://bugs.launchpad.net/snapcraft/+bug/1694765)
> git: don't use --remote for updating submodules

- integration_tests/plugins/test_go_plugin.py
- integration_tests/snaps/go-hello/snapcraft.yaml
- manual-tests.md
- snapcraft/plugins/go.py
- snapcraft/tests/matchers.py
- snapcraft/tests/plugins/test_go.py
Support doing `snapcraft snap --target-arch=` with parts using the **go** plugin
> go plugin: Add support for cross-compilation

- snapcraft/_store.py
- snapcraft/tests/commands/test_register.py
Remove the similar message printed for a successful registration.
LP: #1692769
> cli: remove double congrats messaging

- integration_tests/plugins/test_go_plugin.py
- snapcraft/plugins/go.py
- snapcraft/tests/plugins/test_go.py
When no go packages are defined, `go build -o` is incompatible with `./...` so we need to provide it the main packages we want to build.
> go plugin: filter the main packages go-packages are defined

- snapcraft/_baseplugin.py
The wording in case of using a plugin that doesn't implement enable_cross_compilation confusingly refers to the parts name - it should state that the used plugin lacks support.
> plugins: clarify wording of cross-compilation unsupported error

- HACKING.md
- manual-tests.md
- snapcraft/internal/common.py
Currently Snapcraft hard-codes where it looks for its data files (schema, etc.) to support either running from a development tree or running from the Debian package. This actually works for when its installed via pip as well, but only if using an editable installation.
This PR fixes LP: [#1656884](https://bugs.launchpad.net/snapcraft/+bug/1656884) by using sys.prefix to also support being installed via pip (without being editable).
> common: find data files via sys.prefix

- integration_tests/plugins/test_nil_plugin.py
- integration_tests/snaps/build-package-global/snap/snapcraft.yaml
- integration_tests/snaps/build-packages-missing-dependency/snap/snapcraft.yaml
- integration_tests/snaps/build-packages-without-dependencies/snap/snapcraft.yaml
- integration_tests/snaps/build-virtual-package/snap/snapcraft.yaml
- integration_tests/test_build_package_version.py
- integration_tests/test_pull_properties.py
- integration_tests/test_snap.py
- integration_tests/test_snapcraft_recording.py
- snapcraft/internal/lifecycle.py
- snapcraft/internal/meta.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/repo/_deb.py
- snapcraft/internal/states/__init__.py
- snapcraft/internal/states/_build_state.py
- snapcraft/internal/states/_global_state.py
- snapcraft/internal/states/_prime_state.py
- snapcraft/internal/states/_pull_state.py
- snapcraft/internal/states/_stage_state.py
- snapcraft/internal/states/_state.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/repo/test_deb.py
- snapcraft/tests/states/test_state.py
- snapcraft/tests/test_lifecycle.py
We install all the build packages before pulling the individual parts.
Before this branch, we first installed all the build packages, then pulled each individual part, and then the individual parts saved the versions of packages installed inspecting the dependency chain in the cache.
With this change, we save all the build packages and their versions when they are installed. So this changes a few things:
* If a build package is already installed, it won't be saved as an asset. So in the end, the recorded annotated snapcraft.yaml will be accurate only in cleanbuild, and requires that we also record the image used during cleanbuild.
* The recorded annotated snapcraft.yaml will be slightly different than the original, with all the build packages for all the parts as global packages. As we …
> state: save all the build packages as global

- integration_tests/snaps/build-package-global/snap/snapcraft.yaml
- integration_tests/snaps/build-packages-missing-dependency/snap/snapcraft.yaml
- integration_tests/snaps/build-packages-without-dependencies/snap/snapcraft.yaml
- integration_tests/snaps/stage-packages-missing-dependency/snap/snapcraft.yaml
- integration_tests/snaps/stage-packages-without-dependencies/snap/snapcraft.yaml
- integration_tests/test_build_package_version.py
- integration_tests/test_pull_properties.py
- integration_tests/test_snapcraft_recording.py
- integration_tests/test_stage_package_version.py
Grub-docs was removed from artful. We need to test using a different package that will work on all the supported versions.
> tests: replace grub-doc with haskell-doc in build-packages tests

- snapcraft/cli/lifecycle.py
This PR fixes LP: [#1692754](https://bugs.launchpad.net/snapcraft/+bug/1692754) by changing a `click.echo` call into `echo.info`.
> cli: stop leaking green text

- snapcraft/internal/deltas/_deltas.py
- snapcraft/internal/deltas/errors.py
Improved the big delta warning/error message when the user is trying to push changes, making it display the size of the delta before pushing the full snap.
LP: [1681692](https://bugs.launchpad.net/snapcraft/+bug/1681692)
> deltas: Improved message returned when delta is too big

- integration_tests/store/test_store_whoami.py
- snapcraft/cli/store.py
- snapcraft/storeapi/__init__.py
- snapcraft/tests/commands/test_whoami.py
- snapcraft/tests/fixture_setup.py
There are proper fallbacks here as we never
stored the email in our original credentail config location. This provides the proper messaging so this is correct for users wanting to know this.
In some distant future, the account info from the store will also provide this information which is why we loop over the account information .
> cli: provide a whoami command

- snapcraft/_options.py
- snapcraft/tests/test_options.py
The correct kernel arch for s390x is 's390', fix it - kernel snap doesn't even start without this patch.
LP: #1700068
> options: fix s390 kernel arch

- integration_tests/test_build_properties.py
- integration_tests/test_pull_properties.py
- integration_tests/test_snap.py
- snapcraft/cli/_options.py
- snapcraft/cli/lifecycle.py
Raised [in the forum](https://forum.snapcraft.io/t/kernel-cross-compile-problem-missing-snapcraft-target-arch-options/1083/5) the `--target-arch` option seems to be silently ignored depending on where it's specified, specifically if it's specified before the **snap** command.
Additionally the argument never shows up in `--help`.
We're also lacking integration tests for the different methods of invocation.
> Integration tests for snap command with target arch

- snapcraft/plugins/kernel.py
Without this patch, it's always necessary to explicit a kernel target - this patch adds an implicit / default target for these arches too, like for arm, x86, etc.
LP: #1700069
> kernel plugin: add default targets per powerpc, ppc64el and s390x

- snapcraft/cli/lifecycle.py
- snapcraft/internal/lxd.py
- snapcraft/tests/commands/test_clean.py
- snapcraft/tests/commands/test_snap.py
- snapcraft/tests/fixture_setup.py
Add a unit test (and fix) for `SNAPCRAFT_CONTAINER_BUILDS=1 clean`.
> cli: Containerbuild clean

- .travis.yml
Following the suggestion from William Grant, here we disable the default behaviour for packets outside of the receive window. This should avoid the reset failures we see when downloading the core snap from the Internap CDN during the Travis test.
A better solution from the CDN is coming in July, so this change should be reverted soon.
More information: https://forum.snapcraft.io/t/101-connection-resets/775/19
LP: [#1666061](https://bugs.launchpad.net/snapcraft/+bug/1666061)
> tests: workaround issue that causes failures to download core

- snapcraft/plugins/python.py
- snapcraft/plugins/python2.py
- snapcraft/plugins/python3.py
@thomir pointed out in https://github.com/CanonicalLtd/snappy-docs/pull/87 that PyPI is the correct capitalisation for the Python Package Index.
> Correct capitalisation for PyPI

- snapcraft/plugins/python.py
- snapcraft/tests/plugins/test_python.py
LP: [#1683395](https://bugs.launchpad.net/snapcraft/+bug/1683395)
> python plugin: output json in pip list

- tools/travis/run_tests.sh
In runtests.sh we allow to filter the the name of the test file that will be run. It will be useful to pass that parameter also when running the tests in the docker containers that travis uses.
> tests: allow to filter tests in docker

- snapcraft/tests/plugins/test_rust.py
LP: [#1702886](https://bugs.launchpad.net/snapcraft/+bug/1702886)
The default Debian package build system use pybuild[1] set a default http_proxy, which causes the download test failed.
The patch mock download() function in the test.
[1] https://anonscm.debian.org/cgit/dh-python/dh-python.git/tree/pybuild#n55
> rust plugin: unset http_proxy for test_cross_compile.

- snapcraft/plugins/python.py
- snapcraft/plugins/python2.py
- snapcraft/plugins/python3.py
As covered in https://github.com/CanonicalLtd/snappy-docs/pull/87#discussion_r126335736, better explain dependency link processing.
> Better explain dependency link processing

- snapcraft/tests/fixture_setup.py
- snapcraft/tests/sources/test_bazaar.py
When running tests we shouldn't be affect an existing bzr configuration.
LP: #1693839
> tests: do not break a systems `bzr whoami`

- snap/snapcraft.yaml
We should rever tthis as soon as 2.33 hits xenial.
There's a catch-22 since 2.32 does not accept a completer entry in the yaml.
> snap: remove completer entry

- snapcraft/internal/lxd.py
- snapcraft/tests/commands/test_cleanbuild.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/test_lxd.py
If LXD is not installed the exception FileNotFoundError will be raised because the 'lxc' executable doesn't exist. The code currently only handles CalledProcessError.
Fixes: [bug 1703344](https://bugs.launchpad.net/snapcraft/+bug/1703344)
> lxd: Distingish FileNotFoundError if not installed

- integration_tests/plugins/test_waf_plugin.py
- integration_tests/snaps/waf-with-configflags/program/main.c
- integration_tests/snaps/waf-with-configflags/snapcraft.yaml
- manual-tests.md
- snapcraft/plugins/waf.py
- snapcraft/tests/plugins/test_waf.py
CC and CXX environment variables need to be set accordingly to cross-compile with Waf.
> waf: enable cross-compilation support 

- tools/travis/setup_lxd.sh
This is to fix this:
apt-get update
W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
> ci: wait for apt/dpkg lock when setting lxd up

- snapcraft/internal/lxd.py
- snapcraft/tests/commands/test_snap.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/test_lxd.py
Because the project folder is mounted into the container and `$HOME` points at it, .cache ends up in the project folder. We need to stop setting `$HOME`.
This addresses one aspect of bug [1703642](https://bugs.launchpad.net/snapcraft/+bug/1703642).
> lxd: Stop setting $HOME in containers

- schema/snapcraft.yaml
- snapcraft/tests/test_project_loader.py
reload-command and completer fields are supported in snapd, but not snapcraft
Checklist:
- Have you signed the contributor licence agreement?
Yes, am canonical employee
- Is there a reported a bug for the problem you are fixing?
LP: [#1699507](https://bugs.launchpad.net/snapcraft/+bug/1699507)
- Have you read our contribution guide?
yes
> snapcraft.yaml: add support for reload-command and completer directives

- integration_tests/test_clean_dependents.py
- snapcraft/internal/lifecycle.py
- snapcraft/tests/commands/test_clean.py
When running clean it sometimes does not clean to avoid cleaning some things
you might not want to clean but that has proven to be a cumbersome user
facing feature so now it would just clean everything in the path.
> core: a clean command should clean.

- snapcraft/internal/lxd.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/test_lxd.py
If creating a LXD container fails snapcraft always produces two exceptions because it will attempt to remove the non-existing container - this adds a check to avoid that.
Not sure about unit tests... we'd need to know that no exception was raised for 'lxc stop'.
> lxd: Only remove container if one exists

- snapcraft/internal/lxd.py
- snapcraft/tests/commands/test_clean.py
There's no reason to ever run commands inside a LXD container when `SNAPCRAFT_CONTAINER_BUILDS=1 snapcraft clean` is run without any arguments.
> lxd: clean with no parts should only delete

- integration_tests/plugins/test_kbuild_plugin.py
- integration_tests/snaps/kbuild-hello/defconfig
- integration_tests/snaps/kbuild-hello/snap/snapcraft.yaml
- schema/snapcraft.yaml
- snapcraft/__init__.py
- snapcraft/plugins/kbuild.py
- snapcraft/tests/plugins/test_kbuild.py
- snapcraft/tests/plugins/test_kernel.py
Projects using **KBuild** often have no install target in the Makefile.
> kbuild plugin: support Makefile without install target

- snapcraft/plugins/catkin.py
- snapcraft/tests/plugins/test_catkin.py
Change the string 'true' to the boolean True. Thankfully this had no bad side effects since the string 'true' is truthy, but it's still incorrect and a bad example.
> catkin plugin: include-roscore is a boolean

- demos/ros/snap/snapcraft.yaml
- schema/snapcraft.yaml
- snapcraft/__init__.py
- snapcraft/plugins/catkin.py
- snapcraft/tests/plugins/test_catkin.py
This PR resolves LP: [#1709671](https://bugs.launchpad.net/snapcraft/+bug/1709671) by using the Release build type by default. It also adds a new boolean property called `debug` to support changing the build type to Debug.
> catkin plugin: default to release build

- snapcraft/plugins/catkin.py
- snapcraft/tests/plugins/test_catkin.py
Missed this when adding the `rosinstall-files` feature, sorry about that.
> catkin plugin: rosinstall-files is a pull property

- demos/ros/snap/snapcraft.yaml
- snapcraft/plugins/catkin.py
- snapcraft/tests/plugins/test_catkin.py
This PR resolves LP: [#1709640](https://bugs.launchpad.net/snapcraft/+bug/1709640) by adding a new plugin option called `cmake-args` that accepts a list of cmake parameters. If provided, they are appended at the end of the `catkin_make_isolated` invocation.
> catkin plugin: support passing args to cmake

- bin/snapcraft
- requirements.txt
- setup.py
This is a clean repeat of #1427 in order to address Github metadata issues and eliminate overall noise. 
This adds minimal win32 cx_Freeze support and refactors setup.py to account for incompatibilities in `setup()` while eliminating redundant packaging data. Ideally, this should not impact the current setup.py behavior beyond using cx_Freeze. 
This work is not exhaustively tested but should produce a working snapcraft.exe. I also tested `bdist_msi` and found that this can be deployed with an installer.
At this time, I'm targeting `bin/snapcraft` despite the fact that this is supposedly deprecated because it is far easier to pass to cx_Freeze as an entry point. I'd welcome a more future-proof approach.
> Add cx_Freeze options targeting bin/snapcraft

- snapcraft/internal/lxd.py
- snapcraft/tests/commands/test_snap.py
After double-checking that the logic for mounting the project folder on the Snapcraft side I ended up finding that LXD can end up claiming the device exists without actually mounting it. In that case `lxc device remove` aborts with internal errors.
Apparently the LXD issue can be avoided by getting rid of a leading / in the mounted path.
This fixes [Could not find snap/snapcraft.yaml](https://forum.snapcraft.io/t/repeated-container-builds-fail-to-find-snapcraft-yaml/1649).
Notes:
* I'm not especially happy with the test side of this, it's a virtually invisible change. Suggestions would be welcome.
* Maybe we should be moving to using `lxc edit` for configuration as it can be used to fix containers that would be stuck using dedicated commands.
> lxd: path cannot have extra forward slashes

- snapcraft/plugins/ant.py
- snapcraft/plugins/gradle.py
- snapcraft/tests/plugins/test_ant.py
- snapcraft/tests/plugins/test_gradle.py
LP: [#1682534](https://bugs.launchpad.net/snapcraft/+bug/1682534)
ant plugin, gradle plugin: Add support for authenticated proxies
Bring ant and gradle up to par with maven plugin wrt. authenticated proxies. Fixes #1485 and re-fixes the linked LP bug (AFAICT it doesn't need the unauthenticated proxy that @cjwatson suggested in the LP bug)
> ant plugin, gradle plugin: add support for authenticated proxies

- snapcraft/cli/_errors.py
- snapcraft/internal/errors.py
- snapcraft/tests/cli/test_errors.py
Just a quick change to the error API before it's actually used.
> errors: use function for exit code

- snapcraft/internal/sources/_base.py
- snapcraft/tests/sources/test_tar.py
We only really need to cache downloaded files and not local files. This also transparently enables caching for plugins that don't call pull but instead use `download` and `provision`.
> core: improve source caching logic

- snapcraft/internal/lxd.py
- snapcraft/tests/commands/test_snap.py
- snapcraft/tests/fixture_setup.py
As a follow-up on #1483 this change removes an existing device for the project folder.
> lxd: always remove existing device for project folder

- snapcraft/cli/_errors.py
- snapcraft/tests/cli/test_errors.py
Raising exceptions from `excepthook` does not seem to be expected by Python, causing it to print "Error in sys.excepthook: [...]" which may look a little confusing, as the `excepthook` has nothing to do with the error. Instead of raising again and relying on Python to further handle the exception, print the traceback ourselves and exit appropriately.
> cli: don't raise from excepthook

- integration_tests/test_build_package_version.py
- snapcraft/internal/repo/_deb.py
- snapcraft/internal/repo/errors.py
Without this change, repo-based errors result in a traceback even when not in debug mode. This should have been caught in #1436, but alas, it was not.
> repo: make errors based on SnapcraftError

- setup.py
- snapcraft/cli/parts.py
- snapcraft/internal/errors.py
- snapcraft/internal/parser.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/project_loader/__init__.py
- snapcraft/internal/project_loader/_config.py
- snapcraft/internal/project_loader/_env.py
- snapcraft/internal/project_loader/_parts_config.py
- snapcraft/internal/project_loader/_schema.py
- snapcraft/internal/project_loader/errors.py
- snapcraft/internal/remote_parts.py
- snapcraft/tests/commands/test_snap.py
- snapcraft/tests/project_loader/test_config.py
- snapcraft/tests/project_loader/test_parts.py
This PR makes progress on #1492, paving the way for the grammar to be moved into the project loader instead of pluginhandler. It moves `project_loader` into its own package dedicated to loading the project. IT also moves the `PartsConfig` logic in there as well, but leaves the remote parts logic out. Also, since the schema validator was only ever used from project loader, the schema was moved into the `project_loader` package as well. Finally, it creates a base class for project-loading-related errors, and modified the current errors to inherit from that.
> project loader: refactor into package

- snapcraft/internal/errors.py
- snapcraft/internal/lifecycle.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/pluginhandler/_plugin_loader.py
- snapcraft/internal/project_loader/_parts_config.py
- snapcraft/tests/commands/test_clean.py
- snapcraft/tests/pluginhandler/mocks.py
- snapcraft/tests/pluginhandler/test_plugin_loader.py
- snapcraft/tests/pluginhandler/test_pluginhandler.py
- snapcraft/tests/pluginhandler/test_scriptlets.py
- snapcraft/tests/project_loader/test_config.py
- snapcraft/tests/project_loader/test_parts.py
- snapcraft/tests/test_lifecycle.py
Currently, loading a plugin goes through many layers of redirection, which is confusing and causes components to be integrated more tightly than would be ideal. This PR simplifies it by no longer loading plugins within PluginHandler, but rather accepting an already-loaded plugin. That plugin is then loaded in PartsConfig, where it is then handed to the PluginHandler.
Beyond an improved design, this also gives us the ability to extract grammar processing completely from the PluginHandler, which will be done in a follow-up PR.
> many: simplify plugin loading

- schema/snapcraft.yaml
- snapcraft/tests/project_loader/test_config.py
This PR addresses one component of LP: [#1712061](https://bugs.launchpad.net/snapcraft/+bug/1712061) by adding a schema validation for the version's length. This is enforced by the review tools in the store, but now Snapcraft will warn before the user gets to the point of uploading.
Note that this PR should not close LP: [#1712061](https://bugs.launchpad.net/snapcraft/+bug/1712061), as it needs wider discussion.
> schema: version should have a max length of 32

- snapcraft/internal/errors.py
- snapcraft/internal/lxd.py
- snapcraft/tests/commands/test_cleanbuild.py
- snapcraft/tests/commands/test_snap.py
- snapcraft/tests/test_lxd.py
As suggested during the review of #1302 container-related errors should use their own error class.
> errors: introduce ContainerError

- integration_tests/snaps/build-package-grammar-fail/snapcraft.yaml
- integration_tests/snaps/build-package-grammar-global/snapcraft.yaml
- integration_tests/snaps/build-package-grammar-on-else/snapcraft.yaml
- integration_tests/snaps/build-package-grammar-on/snapcraft.yaml
- integration_tests/snaps/build-package-grammar-try-else/snapcraft.yaml
- integration_tests/snaps/build-package-grammar-try-skip/snapcraft.yaml
- integration_tests/snaps/build-package-grammar-try/snapcraft.yaml
- integration_tests/snaps/build-package-grammar/snapcraft.yaml
- integration_tests/test_build_package_grammar.py
- schema/snapcraft.yaml
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/project_loader/_config.py
- snapcraft/internal/project_loader/_parts_config.py
- snapcraft/internal/project_loader/grammar_processing/_global_grammar_processor.py
- snapcraft/internal/project_loader/grammar_processing/_part_grammar_processor.py
- snapcraft/internal/repo/_base.py
- snapcraft/internal/repo/_deb.py
- snapcraft/tests/project_loader/grammar_processing/test_global_grammar_processor.py
- snapcraft/tests/project_loader/test_config.py
Currently Snapcraft only supports grammar-powered stage-packages. This PR makes another good chunk of progress on #1492 by adding support for grammar-powered build-packages as well, both at the part-level and global.
Note that this PR depends upon #1509, but was proposed anyway as I'm leaving for a few days. It also may give the other PR more context.
> project_loader: support grammar on build-packages

- .gitignore
Visual Studio Code allows you to create project specific settings
which we want to ignore to not accidentally commit into the source
tree.
> vcs: ignore .vscode project settings 

- snapcraft/plugins/python.py
- snapcraft/tests/plugins/test_python.py
-----
Sergio suggested an existential question about the usefulness of recording these files if they are already tracked in the source. I made a naive implementation of ignoring the file if it's not from a remote server, but this brings more questions about when we should and when we shouldn't record the contents. If you have an opinion, please comment on the forum:
https://forum.snapcraft.io/t/record-build-details-of-python-snaps/1640/4
For now, I'm just recording it always.
> python plugin: always record constraints and requirements contents

- integration_tests/__init__.py
- snapcraft/internal/common.py
- snapcraft/internal/libraries.py
- snapcraft/internal/repo/_deb.py
- snapcraft/internal/repo/_platform.py
- snapcraft/internal/repo/errors.py
- snapcraft/tests/test_libraries.py
- snaps_tests/demos_tests/test_ros.py
- snaps_tests/demos_tests/test_rosinstall.py
- snaps_tests/demos_tests/test_shared_ros.py
All supported Linux distributions provide an `/etc/os-release` file that contains the necessary information for determining supported repository modules to use.
Thus, we can rely on it instead of the deprecated `linux_distribution` method from the `platform` module that will be removed in Python 3.7.
This will also make it much easier to extend to support RPM-based Linux distributions.
Signed-off-by: Neal Gompa <ngompa13@gmail.com>
-----
> repo: Use os-release(5) to detect supported Linux distributions

- integration_tests/snaps/build-snap-grammar-fail/snapcraft.yaml
- integration_tests/snaps/build-snap-grammar-on-else/snapcraft.yaml
- integration_tests/snaps/build-snap-grammar-on/snapcraft.yaml
- integration_tests/snaps/build-snap-grammar-try-else/snapcraft.yaml
- integration_tests/snaps/build-snap-grammar-try-skip/snapcraft.yaml
- integration_tests/snaps/build-snap-grammar-try/snapcraft.yaml
- integration_tests/snaps/build-snap-grammar/snapcraft.yaml
- integration_tests/test_build_snap_grammar.py
- schema/snapcraft.yaml
- snapcraft/_baseplugin.py
- snapcraft/internal/lifecycle.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/project_loader/_config.py
- snapcraft/internal/project_loader/_parts_config.py
- snapcraft/internal/project_loader/grammar_processing/_part_grammar_processor.py
- snapcraft/internal/repo/__init__.py
- snapcraft/internal/repo/errors.py
- snapcraft/internal/repo/snaps.py
- snapcraft/internal/states/_pull_state.py
- snapcraft/tests/fake_servers/snapd.py
- snapcraft/tests/repo/test_snaps.py
- tools/travis/build_snapcraft_snap.sh
- tools/travis/run_lxd_container.sh
- tools/travis/run_tests.sh
Introduce build-snaps with support for advanced grammar.
> project: introduce build-snaps

- integration_tests/plugins/test_meson_plugin.py
- integration_tests/snaps/meson-hello/meson.build
The latest meson does not allow targets to be prefixed with
`meson-`.
-----
> tests: update the meson test to latest meson requirements

- snapcraft/plugins/jhbuild.py
Move for-loop into the same scope as the variable `chmod_path`.
fixes: https://bugs.launchpad.net/snapcraft/+bug/1715507
Failing test groups:
- snapcraft.tests.sources.test_mercurial.MercurialDetailsTestCase
- snapcraft.tests.test_deltas.BaseDeltaGenerationTestCase
- snapcraft.tests.test_deltas_xdelta3.XDelta3TestCase
- snapcraft.tests.commands.test_push.PushCommandDeltasTestCase
None of those touch the jhbuild plugin so I propose the merge anyway.
-----
> jhbuild plugin: fix UnboundLocalError for chmod_path

- debian/tests/integrationtests
- debian/tests/snapstests
- integration_tests/store/test_store_gated.py
- integration_tests/store/test_store_validate.py
-----
There is a good bunch of things going on here.
First, the autopkgtests scripts are run without -e, so only the last error is reported.
Then, through a set of changes, when there is an exception that causes snapcraft to exit the return code is 2 ( https://github.com/snapcore/snapcraft/blob/67089e05002c5fcbfed0d64ac1b3f69363102e3a/snapcraft/internal/errors.py#L35 ).
Finally, this only happens when the integration tests are run against the fake servers. Otherwise, the tests are skipped. Now this is confusing, because the pull requests from forks should run against the fakes, and should have caught this. However, the tests are being skipped, which means that TEST_STORE env var is not set to `fake`. Probably, we are not passing the right var to the container, but I will take care of that …
> tests: update the store failure tests

- snapcraft/plugins/jhbuild.py
pkgconf : Breaks: pkg-config (>= 0.29-1) so we cannot install both at the same time:
```
pkgconf : Breaks: pkg-config (>= 0.29-1)
```
-----
> jhbuild plugin: remove dependency on pkgconf

- integration_tests/plugins/test_nodejs_plugin.py
- snapcraft/plugins/nodejs.py
- snapcraft/tests/plugins/test_nodejs.py
Expose the path for `yarn run` to find the correct binaries
given that it is now not exposed to the bin directory in the
part's install directory.
-----
> nodejs plugin: expose hidden bin path when using yarn

- snapcraft/_options.py
- snapcraft/internal/lxd.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/test_lxd.py
As [discussed in the forum discussion](https://forum.snapcraft.io/t/cleanbuild-remote-on-pi-grabs-wrong-arch-lxc-image/691/7) container builds should default to the architecture of the container rather than the client.
~~Alternative approach to #1498~~.
> lxd: only pass target arch if specified explicitly

- runtests.sh
- snapcraft/plugins/catkin.py
- snapcraft/tests/plugins/test_catkin.py
This PR fixes LP: [#1714333](https://bugs.launchpad.net/snapcraft/+bug/1714333) by only including the original PYTHONPATH if it's actually set. Otherwise, Python interprets empty PYTHONPATH segments as the current working directory, which in the case of the Catkin plugin is not desired.
> catkin plugin: only append PYTHONPATH if set

- snapcraft/internal/pluginhandler/_scriptlets.py
- snapcraft/tests/pluginhandler/test_scriptlets.py
The code only handled an erroring scenario correctly when the last command executed on
a script raised an error.
LP: #1707189
-----
> pluginhandler: error out on scriptlet errors

- snapcraft/internal/deprecations.py
- snapcraft/internal/project_loader/_config.py
- snapcraft/tests/project_loader/test_config.py
-----
Aliases have become a store-only property, not something to be specified within the snap. As such, we need to point that fact out so developers know how to get aliases working. More details in [this forum post](https://forum.snapcraft.io/t/improving-the-aliases-implementation/18).
Also note the [deprecation notice PR](https://github.com/CanonicalLtd/snappy-docs/pull/97).
> project_loader: aliases are deprecated

- demos/shared-ros/Makefile
- demos/shared-ros/README.md
- integration_tests/snaps/catkin-shared-ros/consumer/snap/snapcraft.yaml
- integration_tests/snaps/catkin-shared-ros/consumer/src/overlay_package/CMakeLists.txt
- integration_tests/snaps/catkin-shared-ros/consumer/src/overlay_package/package.xml
- integration_tests/snaps/catkin-shared-ros/producer/snap/snapcraft.yaml
- integration_tests/snaps/catkin-shared-ros/producer/src/underlay_package/CMakeLists.txt
- integration_tests/snaps/catkin-shared-ros/producer/src/underlay_package/package.xml
- integration_tests/test_catkin_shared_ros.py
- snapcraft/plugins/catkin.py
-----
Currently the Catkin plugin pulls its own Catkin off to the side in order to search for dependencies in the underlay, but then doesn't use it in isolation, using Catkin components out of the underlay. This breaks if the underlay doesn't actually include Catkin, and makes no sense considering that Catkin is already pulled off to the side. This PR fixes LP: [#1696014](https://bugs.launchpad.net/snapcraft/+bug/1696014) by using that version completely.
> catkin plugin: don't assume catkin is in underlay

- snapcraft/plugins/nodejs.py
- snapcraft/tests/plugins/test_nodejs.py
> node plugin: record installed node packages in manifest

- snapcraft/plugins/nodejs.py
- snapcraft/tests/plugins/test_nodejs.py
-----
This is part of #1453.
Requires #1523
> node plugin: record the yarn.lock file

- snapcraft/plugins/_python/__init__.py
- snapcraft/plugins/_python/_python_finder.py
- snapcraft/plugins/_python/errors.py
- snapcraft/tests/plugins/python/test_python_finder.py
-----
This PR is the first in a series that extracts pip from the python plugin, thus making progress on LP: [#1683036](https://bugs.launchpad.net/snapcraft/+bug/1683036). It makes no changes to the Python plugin just yet, just copies functionality out into a more accessible place.
> plugins: extract python finder functions

- integration_tests/__init__.py
- integration_tests/store/test_store_gated.py
- integration_tests/store/test_store_register.py
- integration_tests/store/test_store_register_key.py
- integration_tests/store/test_store_revisions.py
- integration_tests/store/test_store_sign_build.py
- integration_tests/store/test_store_status.py
- integration_tests/store/test_store_validate.py
-----
The environment variable is passed to the containers as ''. The setup of integration tests takes care of translating that to 'fake', but some tests are calling the skip before the setup, so weird things happen.
This is a patch for now. The right solution is to not skip any tests, which is almost always doable.
> tests: fix the TEST_STORE environment variable 

- snapcraft/plugins/_python/__init__.py
- snapcraft/plugins/_python/_sitecustomize.py
- snapcraft/plugins/_python/errors.py
- snapcraft/tests/plugins/python/test_sitecustomize.py
-----
This PR is the next in a series that extracts pip from the python plugin, thus making progress on LP: [#1683036](https://bugs.launchpad.net/snapcraft/+bug/1683036) and #1444. It makes no changes to the Python plugin just yet, just copies functionality out into a more accessible place. The functionality that was copied here is the `sitecustomize.py` generation.
> plugins: extract sitecustomize logic from python

- integration_tests/test_snap.py
- snapcraft/internal/meta.py
The current snap.yaml is unordered to the point it looks ugly, by using an ordered dict we ensure the resulting snap.yaml is ordered for human viewing.
-----
This is just a first step to achieve beautiful results. There used to be a bug for this, I guess it was incorrectly fixed released.
> meta: ensure main keys are ordered in snap.yaml

- .gitignore
- snapcraft/__init__.py
- snapcraft/internal/dirs.py
-----
The default plugin, schema, and library dir are relative to `sys.prefix`, which works nicely for Snapcraft as a deb or in a venv. However, Snapcraft's Python plugin installs packages in `$SNAP/` as a prefix, while Python itself is contained in `$SNAP/usr/`. As a result, using `sys.prefix` (which is `/usr`) to find these files when Snapcraft is a snap ends up looking in the wrong place.
Treat running Snapcraft as a snap as a special case, similar to how running from git is supported, and set the directories appropriately.
It's worth pointing out: when making this change, I realized nothing uses `common.get_plugindir()`. The fact that it points to an invalid place (as it always does, even in a deb or venv) doesn't have any side-effects. This PR sets it anyway for consistency, but we …
> dirs: set plugin, schema, and library dir for snap

- snapcraft/plugins/_python/__init__.py
- snapcraft/plugins/_python/_pip.py
- snapcraft/plugins/_python/_python_finder.py
- snapcraft/plugins/_python/errors.py
- snapcraft/tests/plugins/python/__init__.py
- snapcraft/tests/plugins/python/test_pip.py
- snapcraft/tests/plugins/python/test_python_finder.py
- snapcraft/tests/plugins/python/test_sitecustomize.py
-----
At long last, making more progress on LP: [#1683036](https://bugs.launchpad.net/snapcraft/+bug/1683036) and #1444, here is the final bit of extraction necessary from the Python plugin: the Pip wrapper itself.
Note that unlike the other PRs, this is a bit of a refactor. The previous pip wrapper was a very private implementation detail of the Python plugin, and didn't need much of an API. This PR introduces a bit more of an API to it in the hopes of making it a little easier to use in other plugins. It also makes it easier to test.
This PR doesn't modify the Python plugin in any way just yet (that's the next PR).
> plugins: extract pip from python plugin

- integration_tests/test_asset_recording.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/repo/_base.py
- snapcraft/internal/repo/_deb.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/repo/test_deb.py
- snapcraft/tests/test_lifecycle.py
-----
This closes #1452.
Requires #1528.
> recording: record the packages installed in the machine

- snapcraft/internal/repo/_base.py
- snapcraft/tests/project_loader/test_parts.py
This happens when snapcraft loads the configuration in cleanbuild to
retrieve the name and some other metadata. It's too early to resolve the
parts and they are null outside of the container.
-----
> Make sure we don't try to include an empty set

- snapcraft/internal/common.py
- snapcraft/tests/test_common.py
If we're not going to be able to unpack it, ignore the line.
This is what it looks like on Arch Linux. Note the empty line in the end:
```
$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
$ 
```
-----
> Don't fail over empty or faulty lines

- Dockerfile
The Dockerfile is missing SNAPCRAFT_SETUP_CORE which would enable
straightforward snapcraft builds with classic confinement.
-----
> docker: add the environment variable to setup core

- integration_tests/snapd/test_catkin_snap.py
- integration_tests/snaps/ros-pip/snap/snapcraft.yaml
- integration_tests/snaps/ros-pip/src/CMakeLists.txt
- integration_tests/snaps/ros-pip/src/timezone_test/CMakeLists.txt
- integration_tests/snaps/ros-pip/src/timezone_test/package.xml
- integration_tests/snaps/ros-pip/src/timezone_test/scripts/timezone_test_node
- integration_tests/snaps/ros-pip/src/timezone_test/test.launch
- snapcraft/plugins/_python/_pip.py
- snapcraft/plugins/catkin.py
- snapcraft/tests/plugins/python/test_pip.py
- snapcraft/tests/plugins/test_catkin.py
-----
The Catkin plugin uses rosdep to resolve dependencies, however, the only type of dependencies it currently supports are apt-based. This PR fixes LP: [#1683036](https://bugs.launchpad.net/snapcraft/+bug/1683036) by adding support for pip-based dependencies.
> catkin plugin: support rosdep pip dependencies

- snapcraft/plugins/_ros/__init__.py
- snapcraft/plugins/_ros/ros2.py
- snapcraft/tests/plugins/ros/test_ros2.py
-----
Pave the way for an Ament plugin: make progress on LP: [#1686850](https://bugs.launchpad.net/snapcraft/+bug/1686850) (and #1443) by adding code to bootstrap ROS2 underlay from source.
Note that a Debian archive containing ros2 exists, but according to the docs it's temporary. Until it stabilizes, we'll build from source. This PR is essentially the [documentation for building from source](https://github.com/ros2/ros2/wiki/Linux-Development-Setup) in Python form.
A follow-up PR will add an Ament plugin that utilizes the bootstrapper.
> plugins: add ros2 boostrapper

- snapcraft/internal/repo/_base.py
- snapcraft/internal/repo/errors.py
-----
On distros with no native backend, such as Fedora or Archlinux, currently you get an unhelpful "NotImplementedError" with a stacktrace. Instead Snapcraft could be suggesting the user to build in a container.
@Conan-Kudo I can't request a review from you for some reason... but this is what we talked about, so I'd like your eyes on this (even if we'll have the RPM backend soon).
> repo: friendly, helpful error for unsupported distros

- snapcraft/internal/lxd.py
- snapcraft/tests/test_lxd.py
-----
If a persistent container fails to start it may be because id mapping isn't setup on the host. Snapcraft needs to try and be helpful with how it can be corrected.
Fixes [bug 1716738](https://bugs.launchpad.net/snapcraft/+bug/1716738)
> lxd: instructions for /etc/sub{u,g}id after failed start

- .travis.yml
-----
Otherwise the `if` turns into its own job that does nothing, and the snapd tests run all the time. Look at that 10 second job there:
> travis: run snapd tests only if not cron

- integration_tests/snapd/test_dotnet_snap.py
- integration_tests/snaps/dotnet-hello/Program.cs
- integration_tests/snaps/dotnet-hello/dotnet-hello.csproj
- integration_tests/snaps/dotnet-hello/snap/snapcraft.yaml
- schema/snapcraft.yaml
- snapcraft/plugins/dotnet.py
- snapcraft/tests/commands/test_list_plugins.py
- snapcraft/tests/plugins/test_dotnet.py
> Add Dotnet plugin and a sample snap for integration test

- snapcraft/plugins/nodejs.py
Most Node.js projects building v6.x compatible versions are now targetting Node.js 6.11.3. This pull request simply bumps the default `_NODEJS_VERSION` to 6.11.3 in the Snapcraft Node.js plugin.
---
> Update default node engine to 6.11.3

- snapcraft/internal/repo/snaps.py
- snapcraft/tests/repo/test_snaps.py
> recording: do not crash when snapd is not installed

- snapcraft/_options.py
- snapcraft/tests/project_loader/test_config.py
- snapcraft/tests/test_options.py
ppc64el and s390x had leading slashes on their settings for
`core-dynamic-linker`.  In some cases this caused snapcraft to
incorrectly believe that the core snap was not installed, as the target
of the symlink on the host system couldn't be resolved within the core
snap.
LP: #1722521
> options: fix core-dynamic-linker on ppc64el/s390x

- integration_tests/__init__.py
- integration_tests/test_asset_recording.py
- integration_tests/test_build_snaps.py
-----
A little mistake here on my side: `self.deb_arch` is only available after calling the parent `setUp`. Sorry about that.
> tests: fix the skip of snapd integration tests in armhf

- snapcraft/plugins/kbuild.py
https://bugs.launchpad.net/snapcraft/+bug/1722494
-----
If the part build dir comes bundled with a .config file, reuse it as the actual base config
> kbuild plugin: if the parts build dir already contains a .config file, use it as the base config

- snapcraft/plugins/plainbox_provider.py
- snapcraft/tests/plugins/test_plainbox_provider.py
-----
[LP: #1722833](https://bugs.launchpad.net/snapcraft/+bug/1722833)
Ensure PROVIDER path is set for all provider validations to
prevent providers found on the build host from effecting the
result
> plainbox-provider plugin: init PROVIDERPATH

- snapcraft/storeapi/errors.py
- snapcraft/tests/fake_servers/api.py
- snapcraft/tests/store/test_store_client.py
Currently, when releasing a snap with invalid data (e.g. revision),
the error string is not formatted for a user, e.g.
{'revision': ['This field must be an integer.']}
With this commit, the error is formatted as follows:
"invalid-field: The 'revision' field must be an integer"
Moreover:
- added test case in test_store_client.py: ReleaseTestCase.test_release_with_invalid_revision
- added new conditional branch in fake_servers/api.py:snap_release method to support the test above.
- reworked StoreReleaseError class to wrap the code that formats
different errors in dedicated methods.
Fixes LP 1604815
-----
> Fixed StoreReleaseError format for BAD REQUEST error

- snap/snapcraft.yaml
-----
Creating the snapcraft snap works fine as long as one is using the snap or the deb to build. However, for reasons unknown to me, when running from source, the `make startup` of the `apt` part creates a directory named `build` that clashes with the `build` scriptlet that also tries to create a directory named `build`. I'm still not sure why this only happens when building from source, but an easy fix is to simply create a different directory in the `build` scriptlet.
> snapcraft.yaml: don't re-use build dir

- schema/snapcraft.yaml
- snapcraft/internal/project_loader/errors.py
- snapcraft/tests/project_loader/test_config.py
-----
Currently, when one attempts to use an invalid app, hook, or part name, rather than saying something about it being an invalid name because it didn't match the regex, jsonschema uses the `additionalProperties` validator, which makes the error message extra awful, e.g.:
Issues while validating snapcraft.yaml: The 'apps' property does not match the required schema: Additional properties are not allowed ('invalid_app_name' was unexpected)
This PR fixes LP: [#1606890](https://bugs.launchpad.net/snapcraft/+bug/1606890) by improving these messages, adding custom in-schema validation errors for them instead of relying on jsonschema.
> schema: improve invalid app, hook, and part errors

- integration_tests/plugins/test_nodejs_plugin.py
The integration tests for the default package manager doesn't provide any
useful information. We have a unittest that checks that the default value
is npm.
-----
> tests: remove the duplicate nodejs integration tests

- snapcraft/plugins/catkin.py
- snapcraft/plugins/dotnet.py
- snapcraft/plugins/kbuild.py
- snapcraft/tests/plugins/test_catkin.py
- snapcraft/tests/plugins/test_dotnet.py
- snapcraft/tests/plugins/test_kbuild.py
-----
The build state tracks `build-attributes` as a build property, which means if it changes, the build step is considered dirty. However, a few plugins have also added `build-attributes` to their build properties, which is redundant.
This PR makes sure the core Snapcraft properties are handled in the state classes, and keep the plugins handling their own schema. While we have tests covering this, you can verify `build-attributes` still makes the `build` step dirty manually with the following:
```
$ snapcraft init
Created snap/snapcraft.yaml.
Edit the file to your liking or run `snapcraft` to get started
$ snapcraft build
Preparing to pull my-part 
Pulling my-part 
Preparing to build my-part 
Building my-part 
$ echo "    build-attributes: [debug]" >> snap/snapcraft.yaml 
$ snapcraft …
```
> plugins: build-attributes is already in the state

- integration_tests/snapd/test_catkin_snap.py
-----
The Catkin test uses ROS Kinetic, which targets Ubuntu releases no later than Xenial. So don't expect them to work there. This also gets us around the fact that we have no way for handling third-party repository keys just yet.
> integration tests: skip catkin test on non-xenial

- snapcraft/tests/plugins/ros/test_ros2.py
-----
This causes the PPA tests to fail, and shouldn't be happening in general anyway.
> tests: don't hit internet in ros2 units

- snapcraft/internal/states/_build_state.py
- snapcraft/tests/pluginhandler/test_pluginhandler.py
- snapcraft/tests/states/test_build.py
- snapcraft/tests/test_lifecycle.py
-----
Currently, if one of the scriptlets (`prepare`, `build`, or `install`) changes, Snapcraft doesn't notice. This PR fixes LP: [#1672407](https://bugs.launchpad.net/snapcraft/+bug/1672407) by adding them to the build state so that if one of more of these scriptlets change, Snapcraft considers the build step dirty.
> states: add scriptlets to build state

- schema/snapcraft.yaml
- snapcraft/internal/project_loader/errors.py
- snapcraft/tests/project_loader/test_config.py
-----
The snap name and hook name patterns got out of sync. This PR fixes LP: [#1693798](https://bugs.launchpad.net/snapcraft/+bug/1693798) by getting them back in sync. It also updates the jsonschema error handling to be more readable.
> schema: sync patterns with snapd

- snapcraft/internal/libraries.py
- snapcraft/tests/test_libraries.py
_get_system_libs depends on VERSION_ID for the name of the file that is
expected to contain the list of shared libraries to exclude from the build.
However, according to os-release(5), VERSION_ID is just optional, so its
absence should not cause failures.
With this commit, the absence of VERSION_ID is considered as the file
with the list of shared libraries to be excluded does not exist.
Fixes https://bugs.launchpad.net/snapcraft/+bug/1722650
-----
> Removed dependency on VERSION_ID in os-release

- debian/tests/integrationtests
> tests: add /snap/bin to PATH in autopkgtests

- bin/snapcraft-classic
-----
This PR fixes LP: #1723208 by removing the LD_LIBRARY_PATH set in the snapcraft-classic wrapper. This leaks into the running environment and causes the snap on other distros to break (e.g. Trusty). It also seems completely unnecessary given the rpaths.
> snap: remove leaking LD_LIBRARY_PATH

- snapcraft/internal/libraries.py
- snapcraft/tests/test_libraries.py
> libraries: exclude the full set of libc6

- integration_tests/__init__.py
- snapcraft/_store.py
- snapcraft/cli/store.py
- snapcraft/tests/commands/test_logout.py
-----
As the snapcraft workflow becomes more and more CLI-driven, it may not be clear to developers who start with snapcraft how to create an account.
This PR fixes LP: [#1649356](https://bugs.launchpad.net/snapcraft/+bug/1649356) by adding a note when the user attempts to login.
> store: guide to account creation upon login

- debian/tests/integrationtests
-----
This PR needs to be split in two, because I first need this tiny change in the PPA in order to use it in the travis daily. I'll propose the second part once I get this change into the daily PPA.
> tests: allow to select a suite when running autopkgtests

- snapcraft/internal/repo/_platform.py
-----
Elementary fixed their `/etc/os-release` file, but we don't support the fixed version (just "elementary", no spaces and no "OS"). This PR fixes LP: [#1719336](https://bugs.launchpad.net/snapcraft/+bug/1719336) by adding that support.
> repo: add elementary to deb distros

- snapcraft/cli/_errors.py
- snapcraft/internal/errors.py
- snapcraft/internal/lxd/_containerbuild.py
- snapcraft/tests/test_lxd.py
We do not want to print the same error twice, so the caller should
produce a silent error with a proper exit code as the message
related to the error would be displayed by the callee.
-----
I do wish ContainerRunError would be more generalized and that these Container* exceptions live inside the lxd package, but oh well, this fixes the problem today.
> lxd: better surfacing of errors

- snaps_tests/demos_tests/test_rosinstall.py
- snaps_tests/demos_tests/test_shared_ros.py
- snaps_tests/skip.py
This is to avoid the overly broad imports done in
snapcraft.tests which break autopackage tests.
-----
> tests: fork skip into snaps_tests

- integration_tests/test_catkin_shared_ros.py
> integration tests: skip shared ROS test on non-xenial

- snapcraft/internal/sources/_subversion.py
Currently, svn last changed revision is extracted from `svn info`
text output. The same information can be retrieved directly from
the command
`svn info --show-item last-changed-revision`
without the need to parse text.
Adding also the flag `--no-newline` to avoid the need to strip
newline character from the output.
Since there is not need to parse text anymore, this also remove
the dependency from the current locale and then
fixes https://bugs.launchpad.net/snapcraft/+bug/1724674
-----
> sources: get svn revision with --show-item flag

- snapcraft/cli/lifecycle.py
- snapcraft/internal/lxd/_project.py
- snapcraft/tests/commands/test_clean.py
-----
Fixes [bug 1727445](https://bugs.launchpad.net/snapcraft/+bug/1727445).
> lxd: distinguish argless clean from clean -s pull

- snapcraft/tests/fake_servers/snapd.py
Our base handler makes sure that the server doesn't print debug messages to stdout. This messages can leak into other tests that are checking stdout.
-----
> tests: use the common base handler on the fake snapd server

- integration_tests/plugins/test_autotools_plugin.py
- integration_tests/snapd/test_autotools_snap.py
- integration_tests/snaps/autotools-hello/Makefile.am
- integration_tests/snaps/autotools-hello/configure.ac
- integration_tests/snaps/autotools-hello/snapcraft.yaml
- integration_tests/snaps/autotools-hello/test.c
- snapcraft/plugins/autotools.py
- snapcraft/tests/plugins/test_autotools.py
-----
Take a look at the `configure` output for our autotools cross-compile integration test (I'm doing this by hand, running `snapcraft --target-arch=armhf`):
```
[...]
./configure --prefix= --host=armhf
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for armhf-strip... no
checking for strip... strip
[...]
```
Note that it's using the build system's `strip`, not the cross-toolchain's `strip`. What is `armhf-strip` anyway? Nothing, I tell you! We're setting --host to the deb arch instead of the triplet.
Currently the autotools plugin uses the CC and CXX environment variables to force autotools to cross-compile. However, autotools will do this on its own if one sets the --host parameter correctly, and will actually do …
> autotools: cross-compile using --host instead of env

- debian/tests/integrationtests
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/test_fixture_setup.py
> tests: in autopkgtests, use a tempdir in home, not in the tmpfs

- integration_tests/snaps/ruby-bundle-install/snapcraft.yaml
- integration_tests/snaps/ruby-gem-install/snapcraft.yaml
-----
Make all Ruby integration tests use the default (thus latest) version of Ruby. This is required primarily because older versions of Ruby (such as that used in the tests) fail to build in Artful with GCC7.
> integration tests: remove ruby version

- snapcraft/internal/sources/_deb.py
- snapcraft/internal/sources/errors.py
- snapcraft/tests/sources/test_deb.py
Using DebFile imports apt_inst which when run from a snap isn't properly
setup on the hosts which are not debian based.
LP: #1731478
-----
> sources: use arfile to extract debs

- snaps_tests/demos_tests/test_rosinstall.py
- snaps_tests/demos_tests/test_shared_ros.py
-----
Seeing several adt timeouts where the Catkin tests are priming or snapping. Increase the timeouts significantly, looks like things are running a little slower than usual. We'll remove them completely soon.
> demo tests: bump catkin timeout by a lot

- snapcraft/internal/lxd/_containerbuild.py
- snapcraft/tests/test_lxd.py
-----
In here I'm removing the part that we don't control from the message, and at the same time making it look a little nicer for the issue that Christian pointed out in the original branch.
> recording: don't log the command when image info fails

- integration_tests/snapd/test_dotnet_snap.py
The dotnet plugin as is today only works on 16.04, once the
snap is consumable from the plugin we can remove this
restriction.
LP: #1732065
-----
> tests: dotnet only works on 16.04

- snapcraft/tests/__init__.py
-----
We're not using `log` correctly. Several tests (the command tests, parser tests, etc.) call the main executables with `--debug`, which changes the Snapcraft log level. However, because of how we're using `log`, when running the entire suite together, that level tends to stick, and can make later tests (that depend on debug mode NOT being enabled) fail.
This needs to be fixed properly, but to prevent tests from randomly failing, reset the log level to the default after each test.
> unit tests: reset log level after test

- snapcraft/cli/lifecycle.py
- snapcraft/tests/commands/test_clean.py
-----
With `SNAPCRAFT_CONTAINER_BUILDS=foo` running `snapcraft clean` will actually look for a local container, and clean that instead of the container on `foo` or do nothing.
> cli: pass remote from container_config to clean method

- snapcraft/cli/containers.py
- snapcraft/tests/commands/test_refresh.py
-----
With SNAPCRAFT_CONTAINER_BUILDS=foo running snapcraft refresh will actually look for a local container, and refresh that instead of the container on foo.
> lxd: refresh remote container

- integration_tests/snaps/catkin-with-python-part/snap/snapcraft.yaml
- snapcraft/internal/mangling.py
- snapcraft/internal/repo/_base.py
- snapcraft/plugins/catkin.py
- snapcraft/plugins/plainbox_provider.py
- snapcraft/plugins/python.py
- snapcraft/tests/repo/test_base.py
- snapcraft/tests/test_mangling.py
-----
Currently Snapcraft rewrites absolute Python shebangs to point into the snap by using `/usr/bin/env`. However, `/usr/bin/env` doesn't handle shebang args, whereas Python itself does.
This PR fixes LP: [#1730472](https://bugs.launchpad.net/snapcraft/+bug/1730472) by accounting for the possibility of shebang args in rewrite, and making sure that all components that rewrite the Python shebang use the same code path to do so. As a side effect of this last step, this PR also fixes LP: [#1673451](https://bugs.launchpad.net/snapcraft/+bug/1673451).
> many: account for python shebang args in rewrite

- integration_tests/snaps/plainbox-simple/snap/snapcraft.yaml
On integration tests we set XDG_CACHE_HOME to a temporary directory in TMPDIR.
In autopkgtests we are now setting TMPDIR to $HOME/autopkgtest_tmp.
The plainbox test tries to write to XDG_CACHE_HOME, which used to be somewhere
it could write. Now that it is in home, to properly work the snap requires the
home plug.
LP: #1732076
-----
> tests: add the home plug to the plainbox snap

- TESTING.md
-----
Add the required `--setup-commands` option to the documentation.
> TESTING: adt on lxc requires squashfuse

- snapcraft/plugins/_python/_pip.py
- snapcraft/plugins/_python/_sitecustomize.py
- snapcraft/plugins/python.py
- snapcraft/tests/integration/plugins/test_python_plugin.py
- snapcraft/tests/unit/plugins/python/test_pip.py
- snapcraft/tests/unit/plugins/test_python.py
-----
Simplify the Python plugin and its tests by using the independently tested pip that was extracted in previous commits. All functionality should remain the same. Please help me test this PR thoroughly!
> python plugin: use extracted pip

- .gitignore
- snapcraft/file_utils.py
- snapcraft/plugins/ament.py
- snapcraft/tests/integration/snapd/test_ament_snap.py
- snapcraft/tests/integration/snaps/ros2/snap/snapcraft.yaml
- snapcraft/tests/integration/snaps/ros2/src/listener_py/launch/talk_and_listen.py
- snapcraft/tests/integration/snaps/ros2/src/listener_py/nodes/listener.py
- snapcraft/tests/integration/snaps/ros2/src/listener_py/package.xml
- snapcraft/tests/integration/snaps/ros2/src/listener_py/setup.cfg
- snapcraft/tests/integration/snaps/ros2/src/listener_py/setup.py
- snapcraft/tests/integration/snaps/ros2/src/talker_cpp/CMakeLists.txt
- snapcraft/tests/integration/snaps/ros2/src/talker_cpp/package.xml
- snapcraft/tests/integration/snaps/ros2/src/talker_cpp/src/talker.cpp
- snapcraft/tests/unit/commands/test_list_plugins.py
- snapcraft/tests/unit/plugins/test_ament.py
-----
As ROS2 nears a stable release, it's a good time to introduce support for it by way of a beta plugin. This PR resolves LP: [#1686850](https://bugs.launchpad.net/snapcraft/+bug/1686850) (and #1443) by doing exactly that. We're starting simple, just bootstrapping ROS2 and using it to build the provided source. ROS2 doesn't have a lot of tooling just yet, so this plugin will need to grow with it.
Note that the high line count is due to an integration test: the plugin itself is relatively small.
> ament plugin: new plugin

- snapcraft/plugins/_ros/rosdep.py
- snapcraft/plugins/catkin.py
- snapcraft/tests/integration/snaps/ros-talker-listener/snap/snapcraft.yaml
- snapcraft/tests/unit/plugins/ros/test_rosdep.py
- snapcraft/tests/unit/plugins/test_catkin.py
-----
Currently the Catkin plugin requires one to specify each and every Catkin package in the workspace that needs to be built and installed into the snap. This is a hindrance for larger projects, especially as oftentimes the entire workspace is needed.
This PR resolves LP: [#1721168](https://bugs.launchpad.net/snapcraft/+bug/1721168) (and #1713) by making the `catkin-packages` property optional. If it's not specified, simply build the entire workspace. Thus the only API change is making what was previously a required property optional, and assigning meaning to its absence.
> catkin plugin: support building entire workspace

- .travis.yml
- tools/travis/run_autopkgtests.sh
- tools/travis/setup_autopkgtests_ppa.sh
-----
WIP: this makes sense only to be run on the daily. But, I need first to check if travis gets green results. I will update the .travis.yml after that.
> tests: run daily autopkgtest in travis

- tools/travis/run_autopkgtests.sh
-----
I must have touched backspace by mistake when I was moving the suite to the nightly, or something, because this worked here: https://travis-ci.org/snapcore/snapcraft/jobs/302748980
I'm sorry.
I added the quote, and now I can run this locally: http://paste.ubuntu.com/26029313/
Hopefully travis will not give us any other surprises.
> tests: add the missing quote on autopkgtest run

- HACKING.md
- debian/control
- snap/snapcraft.yaml
- snapcraft/internal/elf.py
- snapcraft/internal/errors.py
- snapcraft/internal/lifecycle/_runner.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/project_loader/_env.py
- snapcraft/internal/project_loader/_parts_config.py
- snapcraft/tests/integration/general/test_prime.py
- snapcraft/tests/integration/general/test_stage.py
- snapcraft/tests/integration/plugins/test_rust_plugin.py
- snapcraft/tests/unit/__init__.py
- snapcraft/tests/unit/pluginhandler/test_pluginhandler.py
- snapcraft/tests/unit/project_loader/test_config.py
- snapcraft/tests/unit/test_elf.py
- tools/travis/run_tests.sh
During the prime step, the pluginhandler collects all elf files,
as a postprocessing step, the elf files that contain an .interp
section in the elf headers are set to use the linker loader
from core.
Fixes: #1662
-----
I have built a snap (but still sets the LD_FLAG) which can be obtained by `snap install snapcraft --classic --channel edge/patchelf`
> many: ensure classic confined binaries use the correct interpreter

- snapcraft/internal/lxd/_project.py
- snapcraft/tests/unit/commands/test_clean.py
-----
Steps to manually test this:
* export SNAPCRAFT_CONTAINER_BUILDS=helga
* cd snapcraft/tests/integration/snaps/go-hello/
* lxc list helga: | grep go-hello
* Observe no container exists
* snapcraft pull
* lxc list helga: | grep go-hello
* Observe container exists
* snapcraft clean -s pull go-hello
* lxc list helga: | grep go-hello
* Observe container exists
* snapcraft clean go-hello
* Observe container still exists, artifacts were cleaned
* snapcraft clean
* lxc list helga: | grep go-hello
* Observe container was deleted, message "Deleting helga:snapcraft-go-hello"
* Repeat "snapcraft clean", "snapcraft clean go-hello", "snapcraft clean -s pull go-hello"
* Observe no error occurred with already deleted container
Fixes [bug 1734145](https://bugs.launchpad.net/snapcraft/+bug/1734145)
> lxd: delete container only if parts is empty

- snapcraft/plugins/python.py
- snapcraft/tests/unit/plugins/test_python.py
This allows Python scripts that begin with "pip" but aren't actually pip
(such as pip2pi and friends) to be included in snaps using the Python
part.
LP: #1734213
-----
> Make the pip filtering in the Python plugin more fine-grained

- snapcraft/tests/fake_servers/api.py
- snapcraft/tests/integration/store/test_store_push_metadata.py
- snapcraft/tests/unit/store/test_store_client.py
This is because the real store needs for the binary of snap to be first pushed before really the metadata can be sent.
This was already understood by snapcraft (the error message when that doesn't happen express the problem correctly) but one integration test was incorrectly built (see [this failure](https://travis-ci.org/snapcore/snapcraft/jobs/308248189)).
So I fixed the fake store to make that bad test fail, and then fixed the test.
> Enhanced fake store to detect that metadata can't be pushed prior to pushing the binary, and fixed the test

- snapcraft/internal/lxd/_containerbuild.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/unit/commands/test_snap.py
- snapcraft/tests/unit/test_lxd.py
lxd implements exactly the same logic as snapcraft does to choose an
architecture when one is not specified, so remove snapcraft's copy.
It is still necessary to record the architecture of the created
container to detect whether snaps can just be copied across, but this
is now done after the container is started, which will still be correct
when/if support for building on a non-default image is merged.
> lxd: let lxd choose the architecture

- snapcraft/internal/project_loader/_parts_config.py
- snapcraft/tests/integration/__init__.py
- snapcraft/tests/integration/general/test_scriptlets.py
- snapcraft/tests/integration/snaps/scriptlet-install/snapcraft.yaml
It is exported as SNAPCRAFT_ARCH_TRIPLET and usable by
the scripting functionality in snapcraft.
Fixes: #1752
Signed-off-by: Ubuntu <sergio.schvezov@canonical.com>
-----
> project: export the arch triplet into the environment

- snap/snapcraft.yaml
-----
Currently, when building the Snapcraft snap, we try to create the libsodium.so symlink by manually constructing the arch tuple using `uname`. However, this does not work correctly in all cases, for example i686.
This PR fixes LP: [#1733922](https://bugs.launchpad.net/snapcraft/+bug/1733922) by using `gcc -print-multiarch` instead. It's exactly what we need, and it's already a `build-package`.
Please test this PR by simply smoke-testing this snap on i386 (even an i386 LXD container would work):
$ sudo snap install snapcraft --channel=stable/pr-1764 --classic
> snapcraft.yaml: use gcc to determine tuple

- snapcraft/cli/store.py
- snapcraft/storeapi/errors.py
- snapcraft/tests/unit/store/test_store_client.py
This commit will add 2 more sentences to error when trying to register
a reserved name.
Addresses bug at [LP: 1602791](https://pad.lv/1602791).
> Add sentences to error when registering name

- snapcraft/_store.py
- snapcraft/tests/unit/commands/test_list_keys.py
Tell user to see 'register-key --help' if there is no key registered. Before this fix, an empty table was printed. (which is ugly and redundant)
LP: [#1720210](https://bugs.launchpad.net/snapcraft/+bug/1720210)
-----
Hi! I could check that the changed message is printed with my account w/o registering key, and after I registered one, the ordinary table showed up. However, I'm not sure how to write a test for it. Or is it simple enough that there's no test needed? I'm doing this as a GCI task to fix a bitesize bug of snapcraft, and not that familiar with these stuff ;( If there's something I didn't do correctly with the flow, do not hesitate to teach me. Many thanks!
> cli: show helpful message for 'snapcraft list-keys' with no keys

- snapcraft/tests/unit/commands/test_refresh.py
-----
Somehow the refresh test ended up in a folder that's not part of the new structure so it wouldn't run as part of the regular test runs, which allowed #1769 to pass when it shouldn't have.
> tests: move refresh to unit folder

- snapcraft/internal/os_release.py
- snapcraft/plugins/catkin_tools.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/integration/__init__.py
- snapcraft/tests/integration/snapd/test_catkin_tools_snap.py
- snapcraft/tests/integration/snaps/catkin-tools-talker-listener/snap/snapcraft.yaml
- snapcraft/tests/integration/snaps/catkin-tools-talker-listener/src/CMakeLists.txt
- snapcraft/tests/integration/snaps/catkin-tools-talker-listener/src/listener/CMakeLists.txt
- snapcraft/tests/integration/snaps/catkin-tools-talker-listener/src/listener/package.xml
- snapcraft/tests/integration/snaps/catkin-tools-talker-listener/src/listener/scripts/listener_node
- snapcraft/tests/integration/snaps/catkin-tools-talker-listener/src/listener/talk_and_listen.launch
- snapcraft/tests/integration/snaps/catkin-tools-talker-listener/src/talker/CMakeLists.txt
- snapcraft/tests/integration/snaps/catkin-tools-talker-listener/src/talker/package.xml
- snapcraft/tests/integration/snaps/catkin-tools-talker-listener/src/talker/src/talker_node.cpp
- snapcraft/tests/skip.py
- snapcraft/tests/unit/plugins/test_catkin_tools.py
-----
Currently the catkin-tools plugin uses `build-packages` for its build dependency instead of `stage-packages`, which fails on clean systems.
Use `stage-packages` instead. Also, since this would have been caught by an integration test, add one of those as well (to the snapd suite, specifically).
> catkin-tools plugin: use stage-packages

- snapcraft/cli/echo.py
- snapcraft/cli/help.py
- snapcraft/tests/unit/commands/test_help.py
Give it parity with --help but also extend it so topics and plugin help is
not completely hidden.
LP: #1698116
-----
> cli: improve the help command

- demos/opencv/snap/snapcraft.yaml
- snapcraft/internal/elf.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/project_loader/_config.py
- snapcraft/internal/project_loader/_env.py
- snapcraft/internal/project_loader/_parts_config.py
- snapcraft/tests/unit/pluginhandler/test_pluginhandler.py
- snapcraft/tests/unit/project_loader/test_config.py
- snapcraft/tests/unit/test_elf.py
- snaps_tests/__init__.py
- snaps_tests/demos_tests/test_opencv.py
When working with classic confinement `LD_LIBRARY_PATH`
cannot be set without consequences on when other assets on the host are
called from the snap.
This sets an rpath for every elf file when confinement is set to classic
and allows for further extending this mechanism to non classic.
When setting rpaths it also makes use of `$ORIGIN` to setup relative paths.
Fixes: #1663
-----
> many: set rpath for elf files for classic

- snapcraft/tests/integration/store/test_store_register.py
The previous snap name we were using for this test was revoked at some point.
The store is now returning a different message for revoked snaps, so we needed
to refresh this sceneario with a new name registered by someone else, but not
revoked.
-----
> tests: update the snap name already registered for store tests

- snapcraft/internal/lxd/_cleanbuilder.py
- snapcraft/internal/lxd/_project.py
- snapcraft/tests/unit/test_lxd.py
lxc itself prints a useful enough error message when this happens.
> lxd: suppress traceback when lxc launch / init fails

- snapcraft/internal/lifecycle/_packer.py
- snapcraft/tests/unit/commands/test_pack.py
- snapcraft/tests/unit/commands/test_snap.py
Use of the Squashfs fragments feature results in unpredictable snap
composition due to how fragments are gathered and compressed using a
separate thread in mksquashfs. Disable fragments entirely so that the
review tools can perform validation of snaps.
https://forum.snapcraft.io/t/proposal-to-disable-squashfs-fragments-in-snaps/3103
LP: #1576763
Signed-off-by: Tyler Hicks <tyhicks@canonical.com>
-----
> lifecycle: use the -no-fragments mksquashfs option

- TESTING.md
- debian/tests/snapstests
- snapcraft/internal/common.py
- snapcraft/tests/integration/__init__.py
- snapcraft/tests/integration/containers/test_cleanbuild.py
- snapcraft/tests/integration/containers/test_container_builds.py
- snapcraft/tests/integration/general/test_parser.py
- snapcraft/tests/integration/general/test_prime.py
- snapcraft/tests/integration/general/test_stage.py
- snapcraft/tests/integration/plugins/test_rust_plugin.py
- snapcraft/tests/unit/commands/test_snap.py
- snaps_tests/__init__.py
- snaps_tests/demos_tests/test_opencv.py
- spread.yaml
- tools/travis/run_lxd_container.sh
- tools/travis/run_tests.sh
We loosly assume tests are using the snap to run, what is worse is that we setup all the development dependencies together with the runtime ones to hide this fact
-----
> ci: correctly run from snap

- snapcraft/internal/lifecycle/_containers.py
- snapcraft/tests/unit/commands/test_cleanbuild.py
Playing with the version number made me realize my source tarballs were getting bigger and bigger... fixing.
> lifecycle: do not include source tarballs from previous runs

- tools/travis/build_snapcraft_snap.sh
-----
Workaround for [bug #1738461](https://bugs.launchpad.net/snapcraft/+bug/1738461)
> ci: don't fail if the snap transfer fails

- debian/control
- snap/snapcraft.yaml
- snapcraft/internal/common.py
- snapcraft/internal/elf.py
- snapcraft/internal/lifecycle/_runner.py
- snapcraft/internal/project_loader/_config.py
- snapcraft/tests/integration/plugins/test_go_plugin.py
- snapcraft/tests/integration/snaps/go-gotty/snapcraft.yaml
- snapcraft/tests/unit/integrations/test_travis.py
- snapcraft/tests/unit/test_lifecycle.py
patchelf does not handle the existence of the .note.go.buildid section
so we strip it from the resulting binary as from the perspective of the
snap it is not needed.
A newer patchelf is also required which handles the math required for
the way the headers are layed out when using golang's go.
LP: #1736861
Signed-off-by: Ubuntu <sergio.schvezov@canonical.com>
-----
> elf: strip the .note.go.buildid to make room for patching elf

- snapcraft/tests/unit/test_formatting_utils.py
Add unit tests for the "format_path_variable" function in "formatting_utils" module.
-----
Add unit tests which cover format_path_variable function (in formatting_utils module).
> tests: add more unit tests for formatting_utils

- snapcraft/internal/lxd/_cleanbuilder.py
- snapcraft/internal/lxd/_containerbuild.py
- snapcraft/internal/lxd/_project.py
- snapcraft/tests/unit/commands/test_snap.py
- snapcraft/tests/unit/test_lxd.py
-----
Fixes: [bug 730561](https://bugs.launchpad.net/snapcraft/+bug/1730561)
> lxd: always install squashfuse

- snapcraft/internal/meta/_snap_packaging.py
- snapcraft/tests/integration/snaps/assemble/binary1.after
- snapcraft/tests/unit/test_meta.py
XDG_RUNTIME_DIRS does not exist for the snap on first run, the desktop helpers  part has a workaround for this, but snapcraft is a better place for this as it would work for projects not using them.
This is a workaround for LP: #1656340
-----
> meta: create XDG_RUNTIME_DIR in wrappers.

- snapcraft/tests/integration/plugins/python/test_python_plugin.py
- snapcraft/tests/integration/snaps/pip-bzr/snapcraft.yaml
The python plugin test used lp:curtin which recently moved to bzr.
This moves the test to use a bzr repo the ~snappy-dev team controls which is also much simpler and lightweight.
-----
> tests: use a simpler test for bzr and python

- snapcraft/internal/repo/errors.py
- snapcraft/internal/repo/snaps.py
- snapcraft/tests/fake_servers/snapd.py
- snapcraft/tests/integration/general/test_build_snaps.py
- snapcraft/tests/unit/repo/test_snaps.py
Handle invalid snaps listed under `build-snaps`, provide a nice error. Also add retries to the information fetching logic to be able to have easier debugging information when the network goes wrong.
-----
> repo: handle invalid snaps

- snapcraft/tests/integration/general/test_build_snaps.py
- snapcraft/tests/integration/general/test_prime.py
- snapcraft/tests/integration/general/test_stage.py
- snapcraft/tests/integration/plugins/test_go_plugin.py
- snapcraft/tests/integration/plugins/test_rust_plugin.py
- snaps_tests/__init__.py
- snaps_tests/demos_tests/test_opencv.py
We recently added a requirement to the snapcraft deb to install patchelf
from the snapstore which disabled a couple of tests.
-----
> tests: skip classic confined tests on armhf

- snapcraft/extractors/_errors.py
- snapcraft/extractors/appstream.py
- snapcraft/tests/integration/general/test_metadata_appstream.py
- snapcraft/tests/unit/extractors/test_appstream.py
-----
This PR resolves #1694 by adding an Appstream data extractor. Only supporting the summary and description right now, more to come later.
> extractors: support appstream metadata in parts

- snapcraft/internal/pluginhandler/__init__.py
> pluginhandler: warn the inclusion of libraries from the host

- snapcraft/tests/integration/snaps/rust-with-revision/Cargo.toml
- snapcraft/tests/integration/snaps/rust-with-revision/src/main.rs
The test snap rust-with-revisons had an unnecessary dependency
on the `log` crate which was unversioned. The latest version of
`log` breaks with the rust revision this snap is fixed to.
-----
> tests: fix broken rust test snap

- snapcraft/cli/store.py
- snapcraft/tests/unit/commands/test_push.py
I improved a message displayed after pushing a snap. The humanize_list function from formatting_utils is used to make the list of channels more readable. The unit test was added, to check that the message is displayed correctly.
Fixes https://bugs.launchpad.net/snapcraft/+bug/1735476
I'm a Google Code-in participant.
> cli: humanize push message

- snapcraft/internal/elf.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/tests/unit/pluginhandler/test_pluginhandler.py
- snapcraft/tests/unit/test_elf.py
Parse all the primed files and make sure it will work with
the version of the linker provided by the supporting base.
Closes: #1667
-----
> elf: warn if primed files will not work with the base's linker

- snapcraft/storeapi/_client.py
Add reST docstrings to _client
I'm not sure what to do for kwargs, so I've left them out for now.
-----
> storeapi: add docstrings to _client

- snapcraft/internal/lxd/_project.py
- snapcraft/tests/unit/test_lxd.py
-----
As discussed briefly in a hangout with @sergiusens the "Terminating..." message should be a debug message. We don't currently have unit tests for unexpected messages so I'm not touching the tests (@elopio please correct me if I'm wrong on this one).
> lxd: Change "Terminating" message to debug level

- manual-tests.md
- snapcraft/internal/lxd/_cleanbuilder.py
- snapcraft/internal/lxd/_containerbuild.py
- snapcraft/internal/lxd/_project.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/unit/commands/test_snap.py
- snapcraft/tests/unit/commands/test_update.py
- snapcraft/tests/unit/test_lxd.py
-----
Based on the proof of concept #1484 I'm proposing setting up a user in the LXD container specifically when sshfs is used to mount the project folder into a remote instance of LXD to [ensure correct file ownership](https://bugs.launchpad.net/snapcraft/+bug/1741082).
Fixes: [LP: #1741082](https://bugs.launchpad.net/snapcraft/+bug/1741082 )
> lxd: Use user in container when mounting remote via sshfs

- snapcraft/internal/remote_parts.py
- snapcraft/tests/fake_servers/__init__.py
- snapcraft/tests/integration/general/test_parts.py
- snapcraft/tests/unit/commands/test_update.py
> remote_parts: Use hashed folder based on parts URI

- snapcraft/cli/store.py
- snapcraft/tests/integration/store/test_store_export_login.py
-----
When one uses click.File as an argument type, Click just saves it world-readable, and there doesn't seem to be a way to change it.
Use click.Path instead, and open the file ourselves. Then ensure that only the owner can read it once finished.
> cli: exported login should only be readable by owner

- snapcraft/plugins/kbuild.py
- snapcraft/tests/unit/plugins/test_kernel.py
If snapcraft gets invoked by kbuild during a cross-compile session, there's a nasty corner case when the variable CROSS_COMPILE could be defined but effectively be empty, resulting in a FTBFS.
This for example happens when, cross compiling, you setup only the ARCH variable but forget the CROSS_COMPILE variable, kbuild won't complain and it will pass down the pair as it is: one containing the correct ARCH value, the other completely empty.
$ echo $ARCH
arm
$ unset CROSS_COMPILE
$ echo $CROSS_COMPILE
$ make snap-pkg
scripts/kconfig/conf --silentoldconfig Kconfig
CHK include/config/kernel.release
UPD include/config/kernel.release
rm -rf ./snap
mkdir ./snap
make clean
TAR kernel-4.15.0_rc8_next_20180116.tar.gz
sed "s@KERNELRELEASE@4.15.0-rc8-next-20180116@; \ …
> kbuild: pick up CROSS_COMPILE only if it's not empty

- schema/snapcraft.yaml
- snapcraft/internal/meta/_snap_packaging.py
- snapcraft/tests/unit/test_meta.py
This adds schema and rendering for the `sockets` entries in `apps`, to configure socket activations for deamons. See https://github.com/snapcore/snapd/pull/3916 for the snapd implementation
> Add options to configure applications socket activation

- snapcraft/internal/meta/_snap_packaging.py
- snapcraft/tests/integration/snaps/assemble/binary1.after
- snapcraft/tests/unit/test_meta.py
This reverts commit 909f6233a64157c1dbc432f0487610c41d7fd170.
-----
This change enters hook world through the wrappers causing an exception we want to of course avoid.
```
sergiusens@mirkwood:/home/sergiusens$ [ -n "$XDG_RUNTIME_DIR" ] && mkdir -p $XDG_RUNTIME_DIR -m 700
Segmentation fault (core dumped)
```
This is an icky place; long term we need to get rid of exporting `LD_LIBRARY_PATH`
> Revert "meta: create XDG_RUNTIME_DIR in wrappers. (#1818)"

- snapcraft/internal/errors.py
- snapcraft/internal/mangling.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/project_loader/_config.py
- snapcraft/tests/integration/general/test_asset_recording.py
- snapcraft/tests/unit/project_loader/test_config.py
- snapcraft/tests/unit/test_errors.py
- snapcraft/tests/unit/test_lifecycle.py
- snapcraft/tests/unit/test_mangling.py
Require that the snapcraft.yaml explicitly state it needs libc6 so that it is recorded and an explicit action from the developer.
-----
> elf: better handling for newer libc6

- HACKING.md
- debian/control
- snapcraft/internal/project_loader/_config.py
- snapcraft/tests/integration/general/test_asset_recording.py
- snapcraft/tests/unit/project_loader/test_config.py
Making it a build_tools entry in the project_loader was the wrong
call, we do not for example do the same for xdelta3. We should
instead be handling it through the delivery mechanisms in place,
such that it is in debian/control for the deb and bundled in the
snapcraft snap when running from there.
-----
> elf: make patchelf a dependency

- snapcraft/tests/integration/snaps/plainbox-provider-with-deps/snapcraft.yaml
- snapcraft/tests/integration/snaps/plainbox-provider/snapcraft.yaml
-----
Fixes for current failures of integration tests introduced by changes in external plainbox library.
The plainbox library is being merged in to the checkbox
application. The plainbox part should therefore no
longer be needed in snaps.
> tests: remove plainbox part from plugin tests

- snapcraft/internal/lifecycle/_packer.py
- snapcraft/tests/unit/commands/test_snap.py
-----
Currently, Snapcraft just runs `mksquashfs`, relying on the $PATH. However, as a classic snap, Snapcraft sets no PATH. As a result, even when running as a snap, Snapcraft relies on `mksquashfs` being installed on the build system.
Start using the one in the snap in this case.
> lifecycle: use in-snap mksquashfs if running from snap

- tools/travis/run_tests.sh
-----
The snap store team wants to run only one stage. They can define their stage and the script to run through the api. However, in here we have a dependency on a previous stage, so it wouldn't be possible to call `sudo ./tools/travis/run_tests.sh snapcraft/tests/integration/store` independently.
Their tests don't need to build the snapcraft snap from source, so we could just install snapcraft from edge.
I am adding here an optional env var SNAPCRAFT_INSTALL_COMMAND, that the store team can send on their API request set to `sudo snap install snapcraft --edge --classic`.
> tests: allow to overwrite the snapcraft install command

- snapcraft/cli/__main__.py
- snapcraft/tests/integration/general/test_init.py
-----
When running Snapcraft in a specific way (e.g. Docker, LXD) it's possible to have a situation where no locale is set. This happens mostly in CI systems. Click raises a `RuntimeError` in this situation, which is a pretty terrible user experience.
This PR fixes LP: [#1746100](https://bugs.launchpad.net/snapcraft/+bug/1746100) by using C.UTF-8 by default if it's is available This will allow Snapcraft to run on these systems without creating more work for our users.
> cli: use C.UTF-8 if locale not set

- docker/snap-beta.Dockerfile
- docker/snap-edge.Dockerfile
-----
The Dockerfiles currently create a symlink from `/snap/bin/snapcraft` to `/snap/snapcraft/current/bin/snapcraft-classic`. However, `snapcraft-classic` no longer exists. We can't just symlink to `snapcraft` either, or Python isn't found.
Instead of creating a symlink, write a simple script to run the Python (and Snapcraft) out of the snap.
> docker: don't rely on snapcraft-classic

- snapcraft/internal/elf.py
- snapcraft/tests/integration/general/test_prime.py
- snapcraft/tests/integration/snaps/classic-build-existing-rpath/Makefile
- snapcraft/tests/integration/snaps/classic-build-existing-rpath/hello-classic.c
- snapcraft/tests/integration/snaps/classic-build-existing-rpath/snap/snapcraft.yaml
This is enabled to support users setting up rpaths for their
projects for paths that snapcraft would not find otherwise.
-----
> elf: do not strip rpaths that contain $ORIGIN

- snapcraft/internal/elf.py
LP: #1746397
-----
I personally do not see this issue, nor do the tests which build the example for the dotnet plugin which exposes this for some folks.
That said, this check does not hurt.
> elf: check if file exists before checking if ELF

- snapcraft/internal/elf.py
-----
Fixes [LP:1746639](https://bugs.launchpad.net/snapcraft/+bug/1746639)
> elf: use surrogate escape when decoding readelf output

- snapcraft/internal/os_release.py
- snapcraft/internal/repo/_platform.py
- snapcraft/internal/repo/errors.py
-----
It seems there's a regression with running Snapcraft on MacOS (via PyPI). If no file `/etc/os-release` exists on the system, no commands will work and even the "no native builds" error will break.
$ snapcraft
[...]
FileNotFoundError: [Errno 2] No such file or directory: '/etc/os-release'
This branch presents a possible approach for falling back to defaults. We could as a next step try and fill in versions from other systems here. Call sites won't need to be changed this way.
There's no new tests yet - early feedback would be great.
> Provide stub for when /etc/os-release doesn't exist

- schema/snapcraft.yaml
- snapcraft/tests/unit/project_loader/test_config.py
-----
An update from https://forum.snapcraft.io/t/3974, underscores should not be allowed in the version.
> schema: remove underscore from version pattern

- snapcraft/_store.py
- snapcraft/internal/cache/_snap.py
- snapcraft/tests/unit/cache/test_snap.py
-----
In response to https://forum.snapcraft.io/t/snapcraft-push-error-keyerror-architectures/4056 . snapd (and the store) interpret this as `architectures: [all]`. Snapcraft isn't the only tool that creates snaps, and needs to stop assuming an optional field is present when pushing.
> store: support pushing snap with no architectures

- snapcraft/storeapi/errors.py
- snapcraft/tests/fake_servers/api.py
- snapcraft/tests/integration/__init__.py
- snapcraft/tests/unit/store/test_store_client.py
-----
This PR resolves LP: [#1736963](https://bugs.launchpad.net/snapcraft/+bug/1736963) by showing proper error messages even for responses with error return codes.
The requests lib's Response object overwrites __bool__ to return false if the response code indicates a failure. As a result, if we want to see if a response is actually `None` as must compare directly to `None`. Or just make a call and catch a missing attribute which is what we do here.
> storeapi: handle errors even for >400 responses

- snapcraft/internal/elf.py
Some debug messages needed polishing, like the linker check.
Others, like the check for exclusions of libraries, needed
polish to not repeat itself over and over again when
running off of a non supported base. This comes with a
side effect of reducing the amount of calls necessary
for the check where the debug message is displayed.
-----
> elf: better debug messages

- snapcraft/internal/repo/_deb.py
- tests/fixture_setup.py
- tests/unit/repo/test_deb.py
Fetching packages is overly verbose. While there is an
upstream fix for this, it hasn't been yet released.
Reimplement fetch_binary locally without the noise
mimicking upstream as much as possible.
LP: #1663365
-----
> repo: silence deb caching when fetching packages

- snapcraft/internal/meta/_snap_packaging.py
- tests/integration/general/test_snap.py
adapter is a snapcraft.yaml only property and should not make it into
snap.yaml
LP: #1750658
-----
> meta: make sure adapter does not propagate

- schema/snapcraft.yaml
- tests/unit/project_loader/test_config.py
The name's validation in the schema had three issues:
* It performed exceptionally poorly with some names, taking hours to
validate.
* It didn't check the length of names.
* it returned an error message that was not particularly helpful: if
you tried to use a name of `a--b`, for example, it would warn you
that “Snap names consist of lower-case alphanumeric characters and
hyphens. They cannot be all numbers. They also cannot start or end
with a hyphen.” which was probably perplexing.
This addresses these issues. It also is part of a unification effort
of the name validation accross the project, which I go on about on
https://bugs.launchpad.net/snapstore/+bug/1751447.
> schema: improve the snap name's validator

- snapcraft/extractors/_metadata.py
- snapcraft/extractors/appstream.py
- snapcraft/internal/meta/_snap_packaging.py
- tests/unit/extractors/test_appstream.py
- tests/unit/pluginhandler/test_pluginhandler.py
- tests/unit/test_meta.py
-----
@kyrofa and I discussed about moving the task of translating from desktop file id to desktop file path to the appstream extractor. This opens the door to save in the metadata the contents of the file, instead of the path. But we haven't yet decided if that next step would be good.
> extractors: replace desktop file ids with paths

- snap/snapcraft.yaml
snapcraft ships with a lovely tab completer, but it's not plugged in!
This fixes that. Reported as [lp:1751391](https://bugs.launchpad.net/snapcraft/+bug/1751391).
-----
-----
The tests are failing for me on master, and they continue to fail in the same way with my change.
> snap: actually plug the completer in.

- snapcraft/internal/errors.py
- snapcraft/internal/repo/_deb.py
- snapcraft/plugins/_ros/__init__.py
- snapcraft/plugins/_ros/wstool.py
- snapcraft/plugins/catkin.py
- tests/unit/plugins/ros/test_wstool.py
- tests/unit/plugins/test_catkin.py
-----
Currently Wstool is a class within the Catkin plugin. However, in order to support recursively parsing rosinstall files (#1714), Wstool needs to undergo some changes. In order to ease that work, extract Wstool into its own module.
Note that I added some basic error handling here, but no other changes have been made.
> catkin plugin: extract Wstool into its own module

- tests/fake_servers/api.py
- tests/integration/store/test_store_register.py
- tests/unit/store/test_store_client.py
This starts from @maxiberta's #1963 and fixes a couple more strings.
Here goes nothing.
> Fix Store integration tests with updated snap name registration error messages (take 2)

- snapcraft/plugins/_python/_pip.py
- snapcraft/plugins/python.py
- tests/integration/plugins_python/test_python_plugin.py
- tests/integration/snaps/python-with-source-subdir/snap/snapcraft.yaml
- tests/integration/snaps/python-with-source-subdir/source-subdir/hello
- tests/integration/snaps/python-with-source-subdir/source-subdir/setup.py
- tests/unit/plugins/test_python.py
> python plugin: find setup.py when source-subdir is used

- tools/travis/run_lxd_container.sh
- tools/travis/setup_lxd.sh
> ci: switch to stable lxd and unconfined containers

- snapcraft/internal/elf.py
- tests/unit/test_elf.py
-----
Only consider regular files (or symlinks to regular files) as possible ELF binaries in `ElfFile.is_elf`.  At present, Snapcraft has trouble building the core snap due to the presence of device files.
LP: #1752766
> elf: only consider regular files as possible ELF binaries

- snapcraft/internal/project_loader/_config.py
patchelf is a broken build on xenial/armhf and xenial/s390x so we do not add it as a build tool.
Users of the snapcraft deb will need to provide it in a part or use the build-snap.
-----
Integrating changes in #1943 one step at a time
> project_loader: improve the logic to install patchelf as a build tool

- snapcraft/internal/elf.py
- snapcraft/internal/pluginhandler/__init__.py
- tests/unit/test_elf.py
-----
Snapcraft currently resets the cache for each part, but the cache's concept of "resetting" is only to remove libs that weren't found. Caching library lookups between parts causes issues in snaps where multiple parts rely on the same lib, but they come from different places (e.g. git-ubuntu).
This PR makes more progress on LP: [#1752481](https://bugs.launchpad.net/ubuntu/+source/snapcraft/+bug/1752481) by emptying the cache of all libs not already primed. This may slow things down a little, but will further isolate each part, preventing these kinds of issues.
> elf: remove all un-primed libs from soname cache

- demos/java-hello-world/snap/snapcraft.yaml
When building on a host different that the target base, there is no
wrapper created. Make use of `adapter: none` to make this demo a bit
more generic and manually setup the environment.
-----
Part of #1943
> demos: avoid use of the wrapper for java-hello-world

- tests/integration/general/test_hardlink_src_old_tree.py
> tests: remove _options dependency from integration suite

- snapcraft/internal/elf.py
- tests/fixture_setup.py
- tests/unit/test_elf.py
-----
This PR is a spike RFC. Tests will fail. This has been tested, and works, but performance will take a hit. I'll be working on the tests (and rebasing onto #1959) tomorrow, but want to get it up tonight so you guys can verify the approach.
Currently Snapcraft looks for libs by soname, and gets tripped up if it finds multiple sonames that match (i.e. it takes the first one). This happens in the case of libc coming from the core snap, which includes both amd64's and i386's libc, and it takes i386's libc by default.
Fix this issue by matching architecture in addition to soname.
> elf: only set rpaths to libs of the same arch

- snapcraft/internal/elf.py
The logic migrated to the ElfFile class which does not use the string
returned from magic.
-----
> elf: remove dead code

- docker/beta.Dockerfile
- docker/bin/snapcraft-wrapper
- docker/candidate.Dockerfile
- docker/edge.Dockerfile
Setup the correct SNAP_ARCH for our docker images, also blow up in a more
obvious way if it is missing.
-----
> docker: add the architecture

- snapcraft/_baseplugin.py
- snapcraft/internal/errors.py
- snapcraft/plugins/_python/_pip.py
- snapcraft/plugins/python.py
- tests/integration/general/test_after.py
- tests/unit/test_errors.py
When a plugin fails a horrible traceback is printed because there is no
SnapcraftError class handling the situation.
LP: #1753965
-----
> errros: add a specific error when running commands from plugins

- snapcraft/internal/elf.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/pluginhandler/_patchelf.py
- tests/integration/snaps/go-gotty/snapcraft.yaml
Classic confinement for go with patchelf is still a little problematic
and has never really work from a confinement perspective. So we warn if
patchelf fails to run through.
Clean up the logic after the introduction of bases and the requirement
to explicitly add libc6 to stage-packages in case of non host
compatibilities
-----
> pluginhandler: special case go patchelf failures for classic confinement

- snapcraft/plugins/catkin.py
- tests/unit/plugins/test_catkin.py
-----
Currently, Snapcraft replaces a Python call in `etc/catkin/profile.d/10.ros.sh` that uses an absolute path (that doesn't exist in the core snap) to use just the `python` command instead, thereby ensuring the one from the snap is used. However, a recent ROS Kinetic update switched up the profile.d files, using absolute paths to Python elsewhere, breaking all newly-built ROS Kinetic snaps on Ubuntu Core.
Fix this by taking broader approach, checking _every_ file in `etc/catkin/profile.d/` for absolute Python paths and replacing each if found. Note that this should fix the Catkin Tools plugin as well.
Refer to https://forum.snapcraft.io/t/4518 for more information.
Please test this PR using the `edge/pr-2007-catkin-kinetic-fix` channel:
sudo snap install snapcraft …
> catkin plugin: replace python calls in all profile.d scripts

- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/project_loader/_parts_config.py
- tests/unit/__init__.py
- tests/unit/pluginhandler/test_patcher.py
If the snap is not of type app, today, it is not necessary to do
ABI/API checks agains libc6.
LP: #1757094
-----
> pluginhandler: only do elf checking and patching for type app

- tests/integration/general/test_snap.py
> integration tests: snap tests shouldn't be arch-specific

- demos/java-hello-world/snap/snapcraft.yaml
snapd's new checks do not allow for relative symlinks as the main entry
point in a command so use the realpath to the existing path instead.
-----
> demos: use realpath in command entry for java-hello-world

- snapcraft/_options.py
- snapcraft/file_utils.py
- snapcraft/internal/elf.py
- snapcraft/internal/pluginhandler/_patchelf.py
- tests/unit/test_elf.py
- tests/unit/test_file_utils.py
- tests/unit/test_options.py
When checking for compatibility when the host is not ideal for the base
the base needs to be installed. In many cases the linker version for
the base is known in advance so retrieving the linker from the core
is not required.
-----
> many: optimize retrieval of the linker version

- snapcraft/internal/elf.py
- tests/integration/general/test_elf.py
One path is enough for '$ORIGIN' based rpaths.
-----
On `bionic`:
```
(snapcraft) ubuntu@snapcraft-bionic-dev:~/source/snapcraft$ SNAPCRAFT_TEST_KEEP_DATA_PATH=/home/ubuntu/test python3 -m unittest -v -b run tests.integration.general.test_elf.OriginRPATHTestCase
run (unittest.loader._FailedTest) ... ok
test_origin (tests.integration.general.test_elf.OriginRPATHTestCase)
tests.integration.general.test_elf.OriginRPATHTestCase.test_origin ... ok
----------------------------------------------------------------------
Ran 2 tests in 161.552s
OK
```
On `xenial`:
```
(snapcraft) ubuntu@snapcraft-xenial-dev:~/source/snapcraft$ SNAPCRAFT_TEST_KEEP_DATA_PATH=/home/ubuntu/test python3 -m unittest -v -b run …
```
> elf: avoid duplicating rpath entries

- snapcraft/internal/pluginhandler/__init__.py
- tests/unit/pluginhandler/test_pluginhandler.py
Strip the leading / that can be part of a value for the organize keyword
so that os.path.join can correctly join the destination directory for the
organized file.
Closes: #1974
-----
> pluginhandler: organize correcly for targets with leading /

- snapcraft/cli/_errors.py
- tests/unit/cli/test_errors.py
> errors: remove stack data when sending to sentry
