canonical/snapcraft

- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
> catkin plugin: typo s/packages.xml/package.xml/

- snapcraft/cmds.py
- snapcraft/plugins/ant.py
- snapcraft/plugins/python2.py
- snapcraft/plugins/python3.py
- snapcraft/plugins/qml.py
- snapcraft/repo.py
- snapcraft/sources.py
> Replaced the usage of % with .format

- snapcraft/tests/test_cmds.py
> Silence the init unit test and verify stdout

- setup.py
Remove unused imports
Fix flake8 formatting issue
> Minor fixes to setup.py

- snapcraft/__init__.py
- snapcraft/plugins/catkin.py
- snapcraft/tests/test_base_plugin.py
- snapcraft/tests/test_plugin_catkin.py
> Don't follow symlinks when provisioning the build

- snapcraft/plugins/autotools.py
> Inherit directly from the BasePlugin for autotools

- snapcraft/lifecycle.py
- snapcraft/tests/test_lifecycle.py
Loads the initial values of the properties and the current values from the system schema definition yaml file.
> Schema defaults using schema definition

- integration-tests/data/simple-copy/snapcraft.yaml
- integration-tests/data/simple-copy/srcdir/srcdirfile.txt
- integration-tests/units/jobs.pxu
A test to prove that #16 got fixed somewhere along the way.
> A test for directories in the copy plugin

- README.md
- docs/snapcraft overview.svg
Felt like we needed a diagram on the incoming page and had an idea for one.
> Snapcraft overview diagram

- schema/snapcraft.yaml
- snapcraft/__init__.py
- snapcraft/plugins/catkin.py
- snapcraft/plugins/cmake.py
- snapcraft/sources.py
- snapcraft/tests/test_base_plugin.py
- snapcraft/tests/test_plugin_catkin.py
- snapcraft/tests/test_plugin_cmake.py
> Support the source-subdir keyword for parts

- examples/webcam-webui/snapcraft.yaml
- snapcraft/plugins/go.py
- snapcraft/tests/test_plugin_go.py
> go plugin: implement a go-packages plugin property

- snapcraft/cmds.py
- snapcraft/tests/test_cmds.py
> Print stderr for `snappy build` on failure

- snapcraft/plugins/copy.py
- snapcraft/tests/test_plugin_copy.py
This also removes the call to `cp` and uses plain python APIs
> copy plugin: Support globs

- debian/changelog
> Updating debian/changelog for the 0.5 release

- snapcraft/meta.py
Fix https://bugs.launchpad.net/snapcraft/+bug/1519702
> Fix lp1519702

- schema/snapcraft.yaml
- snapcraft/cmds.py
- snapcraft/tests/test_cmds.py
> Support architectures override

- examples_tests/tests.py
> Added an argument to filter examples tests.

- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
> Ensure yaml encoding is passed when parsing

- examples/gopaste/gopaste
- examples/gopaste/snapcraft.yaml
> gopase example: make it more usable

- snapcraft/cmds.py
- snapcraft/commands/list_plugins.py
- snapcraft/tests/test_cmds.py
- snapcraft/tests/test_commands_list_plugins.py
> cli: list-plugins cmd migrated to docopts.

- snapcraft/tests/test_base_plugin.py
Added a test to check that the snapcraft files are not copied to the build dir.
A little cleanup in the rest of the base plugin tests.
> Added a test to check that the snapcraft files are ignored.

- snapcraft/commands/strip.py
- snapcraft/common.py
- snapcraft/lifecycle.py
- snapcraft/meta.py
- snapcraft/tests/test_commands_strip.py
- snapcraft/tests/test_meta.py
> cli: strip command migrated to docopts

- examples/ros/snapcraft.yaml
- examples/ros/src/beginner_tutorials/CMakeLists.txt
- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
> Backport to 1.x: Catkin plugin: Add support for ROS tools.

- snapcraft/plugins/catkin.py
- snapcraft/plugins/roscore.py
> Backport to 1.x: Resolve FIXME in Catkin plugin

- docs/ros-snap.md
- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
> Backport to 1.x: Catkin plugin: Refactor build.

- docs/ros-snap.md
> ROS documentation: Fix missing step to make script executable.

- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
Currently the Catkin plugin prepares to build by rewriting the Catkin <package>Config.cmake files from the ROS Ubuntu packages to point to the install directory instead of system paths. However, it was hard-coded to only rewrite a specific path, and misses others. This PR makes the path rewrites more generic and robust.
> Catkin plugin: Improve cmake path rewrite.

- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
> Backport to 1.x: Catkin plugin: Improve cmake path rewrite.

- snapcraft/plugins/autotools.py
- snapcraft/tests/test_plugin_autotools.py
> Backport to 1.x: Autotools plugin: Set autogen.sh executable.

- debian/changelog
Only merge if this is the last commit for a 1.0 release.
> Update debian/changelog for the 1.0 release.

- examples_tests/__main__.py
Fixes LP: [#1533393](https://bugs.launchpad.net/snapcraft/+bug/1533393)
> Handle the filter parameter for examples tests.

- examples_tests/__main__.py
Fixes LP: [#1533403](https://bugs.launchpad.net/snapcraft/+bug/1533403)
> Added the option to output subunit results in examples tests.

- examples/tomcat-maven-webapp/snapcraft.yaml
> Updated the tomcat example network capability.

- docs/your-first-snap.md
- examples/gopaste/gopaste
- examples/shout/snapcraft.yaml
- examples/tomcat-maven-webapp/wrapper
- examples/webcam-webui/config.py
- examples/webcam-webui/webcam-webui
- integration_tests/snaps/assemble/binary1.after
- integration_tests/snaps/pypi-config/config.py
- integration_tests/test_python_plugin.py
- integration_tests/test_snap.py
- snapcraft/meta.py
- snapcraft/plugins/catkin.py
- snapcraft/plugins/roscore.py
- snapcraft/tests/test_meta.py
- snapcraft/tests/test_plugin_catkin.py
> Replace SNAP envvars with the 16.04 ones.

- examples/gopaste/snapcraft.yaml
- examples/shout/snapcraft.yaml
- examples/webcam-webui/snapcraft.yaml
- examples/webchat/snapcraft.yaml
> Added the network-listener capability.

- docs/snapcraft-syntax.md
- snapcraft/__init__.py
> Backport to 1.x: Add build-package description to docs/snapcraft-sytax.md

- snapcraft/commands/init.py
> Remove 'vendor' from snapcraft init template.

- docs/metadata.md
> Add doc about how to specify metadata (binaries, services or config).

- examples/mosquitto/mosquitto.conf
- examples/mosquitto/publish.py
- examples/mosquitto/snapcraft.yaml
- examples/mosquitto/subscribe.py
> Added a mosquitto example.

- snapcraft/tests/test_meta.py
> Full coverage of meta.py with unit tests.

- snapcraft/sources.py
- snapcraft/tests/test_sources.py
Added full test coverage to the method.
LP: #1538250
> Refactored the local source pull.

- runtests.sh
> Do not report coverage for static and examples tests.

- snapcraft/storeapi/_login.py
- snapcraft/tests/test_storeapi_login.py
> make sure otp is included in login request only if it's not empty

- examples_tests/tests.py
> Fix the examples tests using testtools as the base.

- docs/get-started.md
- docs/intro.md
- docs/plugins.md
- docs/snapcraft-syntax.md
- docs/your-first-snap.md
> Try to capture what the articles are about in a more concise and clearer way.

- examples/godd/snapcraft.yaml
- examples/py2-project/snapcraft.yaml
- examples/py3-project/snapcraft.yaml
- examples/tomcat-maven-webapp/snapcraft.yaml
- examples_tests/tests.py
> Use the git http protocol in the examples tests.

- debian/changelog
- setup.py
Also update the version number in setup.py. I _think_ that's all of them :smiley: .
Please merge only if this is the last commit for 1.0.1.
> Update debian/changelog for the 1.0.1 release.

- docs/metadata.md
- docs/snapcraft-advanced-features.md
- docs/snapcraft-syntax.md
- docs/snapcraft-usage.md
- docs/your-first-snap.md
> Add more links between the individual articles.

- debian/tests/control
- debian/tests/unittests
> Add the unit tests to the autopkgtest suite.

- snapcraft/repo.py
> Clear APT::Update::Post-Invoke-Success

- docs/metadata.md
(steal text from App Dev Manual 15.04)
LP: #1543581
> Document Snapcraft's wrapper script

- docs/snapcraft-parts.md
> Briefly explain the filesystem layout.

- examples_tests/tests.py
- runtests.sh
> examples_tests: decode the output with utf-8

- .travis.yml
> travis: remove the coveralls token

- debian/changelog
> Release for 2.2

- debian/changelog
> Release changelog for 2.2.1

- debian/changelog
> Release changelog for 2.2.2

- runtests.sh
- snapcraft/storeapi/_upload.py
- snapcraft/storeapi/common.py
> storeapi: reduce the mccabe complexity

- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
> catkin plugin: do not overwrite the PYTHONPATH

- .travis.yml
> travis: update the command to wait for the network

- debian/changelog
> Release changelog for 2.3

- debian/changelog
> Releasing 2.3.1

- debian/changelog
- debian/control
> lxd should be a suggestion, not a direct dep

- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
This PR resolves both LP: [#1548406](https://bugs.launchpad.net/snapcraft/+bug/1548406) and [#1548404](https://bugs.launchpad.net/snapcraft/+bug/1548404) by refactoring the `rosdep` dependency resolution code to account for an empty result as well as multiple results on one line.
Note that both of these bugs are fixed here since, while they're separate bugs, the fix for both is very closely related and it would be more work to split them apart than to just do both.
> Catkin plugin: Handle rosdep empty and multiple dependencies.

- snapcraft/plugins/autotools.py
- snapcraft/tests/test_plugin_autotools.py
> Backport to 1.x: Autotools plugin: Support installing via prefix.

- debian/changelog
- setup.py
Also update version number in setup.py.
> Update debian/changelog for the 1.1.0 release.

- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
> catkin plugin: combine deps as a union of sets

- examples/mosquitto/snapcraft.yaml
- examples/ros/snapcraft.yaml
- examples/shout/snapcraft.yaml
- examples/tomcat-maven-webapp/snapcraft.yaml
- examples/webcam-webui/snapcraft.yaml
- examples/webchat/snapcraft.yaml
- schema/snapcraft.yaml
- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
> Slots are of an interface and not of a type

- examples/gopaste/snapcraft.yaml
- examples/mosquitto/snapcraft.yaml
- examples/ros/snapcraft.yaml
- examples/shout/snapcraft.yaml
- examples/tomcat-maven-webapp/snapcraft.yaml
- examples/webcam-webui/snapcraft.yaml
- examples/webchat/snapcraft.yaml
- schema/snapcraft.yaml
- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
> Swap plugs and slot functionality for interfaces.

- debian/changelog
> Release changelog for 2.4

- examples_tests/__init__.py
- examples_tests/test_gopaste.py
- examples_tests/test_java_hello_world.py
- examples_tests/test_opencv.py
- examples_tests/test_shout.py
- examples_tests/test_tomcat_maven_webapp.py
- examples_tests/test_webcam_webui.py
- examples_tests/test_webchat.py
- examples_tests/testbed.py
- examples_tests/tests.py
Tests added for the examples gopaste, java-hello-world, opencv, shout,
tomcat-mave-webapp, webcam-webui and webchat.
LP: #1545071
> examples_tests: added more tests after the snaps are installed

- docs/get-started.md
> Remove information about PPA. snapcraft and tools will be kept up-to-date in xenial.

- examples/busybox/snapcraft.yaml
- examples_tests/test_busybox.py
- integration_tests/test_list_plugins.py
- integration_tests/test_main.py
- snapcraft/plugins/kbuild.py
- snapcraft/tests/test_plugin_kbuild.py
> New plugin: kbuild

- snapcraft/storeapi/__init__.py
- snapcraft/storeapi/_download.py
- snapcraft/tests/test_storeapi_download.py
This is implemented to support kernel building
LP: #1558970
> Support downloading snaps

- snapcraft/pluginhandler.py
- snapcraft/tests/test_pluginhandler.py
LP: #1560158
Signed-off-by: Kyle Fazzari <kyle@canonical.com>
> Migrate old state to new.

- debian/changelog
> Release changelog for 2.5

- examples/busybox/snapcraft.yaml
> Add missing build-packages to the busybox example

- debian/changelog
> Release changelog for 2.6

- snapcraft/meta.py
- snapcraft/tests/test_meta.py
> Clear icon path before trying to write the new one

- integration_tests/__init__.py
> integration tests: use a temporary config path

- docs/upload-your-snap.md
- integration_tests/test_upload.py
- snapcraft/commands/upload.py
- snapcraft/tests/test_commands_upload.py
> add the option to upload an existing snap

- docs/plugins.md
This PR fixes LP: [#1561524](https://bugs.launchpad.net/snapcraft/+bug/1561524) by updating `docs/plugins.md` for the new plugin API. Which isn't really new anymore, but the doc never got updated to reflect.
> docs/plugins.md: Update for new plugin API.

- setup.py
- snapcraft/common.py
> Add libraries to installation and use correct path

- debian/changelog
> Release changelog for 2.7

- snapcraft/plugins/copy.py
- snapcraft/tests/test_plugin_copy.py
Currently the copy plugin copies all symlinks (using a hard link to them if possible). It should do its best to ensure symlinks will be valid when snapped, however, and follow the ones that aren't. This PR resolves LP: [#1532515](https://bugs.launchpad.net/snapcraft/+bug/1532515) by updating the copy plugin to do a relatively conservative check for invalid symlinks. The symlink will be followed if any of the following conditions are true:
- The symlink is absolute.
- The symlink is pointing outside of the part's install directory.
It's possible to still get broken symlinks into a snap using this plugin with certain special cases, but this should catch the majority of use-cases and avoids the complexity of trying to catch all edge cases which would involve actually rewriting symlinks.
> Copy plugin: Follow symlinks if outside of snap.

- examples_tests/__init__.py
> Update the snap command in examples tests.

- snapcraft/internal/meta.py
- snapcraft/lifecycle.py
- snapcraft/meta.py
- snapcraft/tests/__init__.py
- snapcraft/tests/test_meta.py
This is work to enable easier handling of the global `common.get_Xdir()` calls 
LP: #1551849
> Make meta a class

- snapcraft/__init__.py
- snapcraft/_options.py
- snapcraft/common.py
- snapcraft/lifecycle.py
- snapcraft/main.py
- snapcraft/pluginhandler.py
- snapcraft/plugins/cmake.py
- snapcraft/tests/__init__.py
- snapcraft/tests/test_commands_build.py
- snapcraft/tests/test_commands_clean.py
- snapcraft/tests/test_commands_cleanbuild.py
- snapcraft/tests/test_commands_pull.py
- snapcraft/tests/test_commands_snap.py
- snapcraft/tests/test_commands_stage.py
- snapcraft/tests/test_commands_strip.py
- snapcraft/tests/test_common.py
- snapcraft/tests/test_plugin_cmake.py
- snapcraft/tests/test_pluginhandler.py
- snapcraft/tests/test_yaml.py
- snapcraft/yaml.py
> Move common directories to ProjectOptions

- debian/changelog
- debian/control
- setup.py
> Release changelog for 2.8

- snapcraft/_options.py
- snapcraft/plugins/nil.py
- snapcraft/tests/test_yaml.py
> Only add cross build packages when cross compiling.

- integration_tests/snaps/assemble/binary1.after
- snapcraft/internal/meta.py
- snapcraft/tests/test_meta.py
This PR resolves LP: [#1570945](https://bugs.launchpad.net/snapcraft/+bug/1570945)
> Add SNAP_LIBRARY_PATH to LD_LIBRARY_PATH.

- snapcraft/internal/repo.py
- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
> catkin plugin: use ProjectOptions for repo setup

- debian/changelog
- integration_tests/test_main.py
> Release changelog for 2.8.2

- bin/snapcraft-coverage
> Update the snapcraft-coverage script to use the internal dirs

- debian/changelog
> Release changelog for 2.8.3

- debian/changelog
> Release changelog for 2.8.4

- debian/tests/examplestests
- debian/tests/integrationtests
- examples_tests/__init__.py
- integration_tests/__init__.py
- runtests.sh
> autopkgtests: run the tests using the installed package

- examples_tests/__init__.py
> Remove --allow-unauthenticated from examples tests

- examples_tests/test_mosquitto.py
> Update the mosquitto example SNAP_USER_DATA path.

- examples_tests/test_busybox.py
> Update the busybox test to use the snap data path.

- snapcraft/plugins/nodejs.py
- snapcraft/tests/test_plugin_nodejs.py
> Don't clean target before extracting npm

- integration_tests/snaps/simple-nodejs/index.js
- integration_tests/snaps/simple-nodejs/package.json
- integration_tests/snaps/simple-nodejs/snapcraft.yaml
- integration_tests/test_nodejs_plugin.py
- snapcraft/internal/sources.py
- snapcraft/plugins/nodejs.py
- snapcraft/tests/test_plugin_nodejs.py
Doing this by not deleting the npm download.
LP: #1575882
> nodejs plugin: Allow building N times

- debian/changelog
> Release changelog for 2.8.5

- snapcraft/tests/test_config.py
- snapcraft/tests/test_main.py
- snapcraft/tests/test_storeapi_channels.py
- snapcraft/tests/test_storeapi_common.py
- snapcraft/tests/test_storeapi_download.py
- snapcraft/tests/test_storeapi_login.py
- snapcraft/tests/test_storeapi_upload.py
> Import mock from unittest.

- snapcraft/tests/test_storeapi_info.py
> Remove missing replacement for unittest.mock

- debian/changelog
> Release changelog for 2.8.6

- snapcraft/internal/libraries.py
- snapcraft/tests/test_libraries.py
> Don't fail if there is no system library list

- debian/changelog
> Release changelog for 2.8.7

- debian/changelog
> Release changelog for 2.8.8

- debian/tests/control
- debian/tests/examplestests
- examples/mosquitto/subscribe.py
- examples_tests/__init__.py
- examples_tests/test_mosquitto.py
- examples_tests/testbed.py
> autopkgtests: run the install examples tests in classic

- docs/metadata.md
- docs/ros-snap.md
Remove references to caps and replace with plugs in the documentation.
> Remove caps

- docs/snapcraft-syntax.md
- schema/snapcraft.yaml
- snapcraft/internal/meta.py
- snapcraft/tests/test_meta.py
> Support the assumes keyword

- manual-tests.md
- snapcraft/_store.py
> Fix the one-time password login.

- integration_tests/test_snap.py
- snapcraft/internal/lifecycle.py
- snapcraft/tests/test_commands_init.py
> Improve the template for snapcraft init

- docs/your-first-snap.md
Thanks Jamie for the wording.
LP: #1578231
> Updated the documentation about the icon.

- snapcraft/internal/meta.py
- snapcraft/tests/test_meta.py
> Improve the error message when a part binary is not found.

- demos/godd/snapcraft.yaml
- snapcraft/plugins/go.py
- snapcraft/tests/test_plugin_go.py
> Support setting a gopath for a go project from vcs

- snapcraft/tests/fixture_setup.py
> Set the no_proxy environment variable to access the local fake servers.

- debian/changelog
> Release changelog for 2.10.1

- snapcraft/tests/test_lxd.py
> Make the lxd unit test pass in architectures other than amd64.

- snaps_tests/__init__.py
> Support running the snaps tests in multiple architectures

- debian/control
- debian/snapcraft-examples.lintian-overrides
- debian/snapcraft-parser.lintian-overrides
- debian/snapcraft.lintian-overrides
> Fix or address lintian errors and warnings

- debian/changelog
> Release changelog for 2.11

- snapcraft/internal/parser.py
- snapcraft/tests/test_parser.py
> Include 'maintainer' and 'description' in the parser output.

- snapcraft/internal/parser.py
- snapcraft/tests/test_parser.py
LP:#1592133
* Add a test as well.
> Support "```" wiki code tags in the parser.

- snapcraft/_store.py
- snapcraft/storeapi/__init__.py
- snapcraft/storeapi/errors.py
- snapcraft/tests/store/test_store_client.py
- snapcraft/tests/test_commands_login.py
> Improve the store errors returning exceptions

- docs/upload-your-snap.md
> it's myapps.developer.ubuntu.com

- integration_tests/test_store_upload.py
> Fix the store update test to register a unique name

- snapcraft/internal/parts.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/test_commands_update.py
> Support updating cache without content-length

- integration_tests/snaps/rpath-test/snapcraft.yaml
> Add missing build-packages for rpath test

- snaps_tests/demos_tests/test_mosquitto.py
> In the mosquitto demo test, wait for the subscriber process to end

- integration_tests/snaps/basic/snapcraft.yaml
- integration_tests/test_store_upload.py
> Use a snap that doesn't require a manual review for the upload test

- README.md
I couldn't figure out from the Snapcraft github page where to file bugs/issues.  So I added a link.
> add a link for filing bugs/issues

- bin/snapcraft
- bin/snapcraft-parser
> Use '/usr/bin/env python3'

- snapcraft/plugins/gradle.py
- snapcraft/tests/test_commands_list_plugins.py
- snapcraft/tests/test_plugin_gradle.py
https://bugs.launchpad.net/snapcraft/+bug/1600492
https://github.com/snapcore/snapcraft/pull/646
> Re-based feature/gradle-plugin

- snapcraft/plugins/maven.py
- snapcraft/tests/test_plugin_maven.py
Re-based maven plugin + test.
Bug Report: https://bugs.launchpad.net/snapcraft/+bug/1599987
Original PR: https://github.com/snapcore/snapcraft/pull/638
> feature/maven-targets w/ re-based maven.py

- snapcraft/storeapi/errors.py
- snapcraft/tests/test_commands_register.py
> Capture the correct exception when not being able to decode json

- debian/changelog
> Release debian/changelog for 2.13

- snapcraft/internal/parser.py
- snapcraft/tests/test_parser.py
> parser - Add handling for carriage returns in wiki

- snaps_tests/__init__.py
- snaps_tests/testbed.py
> Run tests from /tmp

- docs/intro.md
- snapcraft/main.py
> Replace 'strip' with 'prime' on intro page and step options.

- debian/control
- debian/copyright
- setup.py
Use the new snapcraft.io mailing list as contact information
> Use the new snapcraft.io mailing list as contact information

- snapcraft/tests/test_plugin_python2.py
> Improve python2 test coverage

- debian/snapcraft-completion
Update the completion list of commands #703
> Update the completion list of commands

- snapcraft/plugins/ant.py
- snapcraft/plugins/gradle.py
- snapcraft/plugins/maven.py
https://bugs.launchpad.net/snapcraft/+bug/1606352
> Slightly tweak the "no jar files" errors (lp: #1606352)

- snapcraft/tests/test_plugin_rust.py
> rust plugin: mock downloads in unit tests

- .travis.yml
- debian/tests/control
- requirements-devel.txt
Remove them from debian tests because they are not needed anymore.
LP: #1610263
> In travis, install the static checkers with pip.

- debian/changelog
> Release changelog for 2.15

- integration_tests/snaps/simple-make-artifacts/Makefile
- integration_tests/snaps/simple-make-artifacts/snapcraft.yaml
- integration_tests/snaps/simple-make-artifacts/test.c
- integration_tests/test_make_plugin.py
- snapcraft/plugins/make.py
- snapcraft/tests/test_plugin_make.py
> make plugin: fix artifact collecting

- bin/snapcraft-parser
- snapcraft/internal/parser.py
- snapcraft/tests/test_parser.py
> Actually return a non-zero error code on errors.

- integration_tests/test_store_register.py
- snapcraft/_store.py
- snapcraft/main.py
- snapcraft/storeapi/__init__.py
- snapcraft/tests/store/test_store_client.py
- snapcraft/tests/test_commands_register.py
> Allow registering private packages

- snapcraft/storeapi/__init__.py
- snapcraft/storeapi/_upload.py
- snapcraft/storeapi/errors.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/store/test_store_client.py
- snapcraft/tests/test_commands_push.py
> storeapi: remove dependency on the 'success' attr

- integration_tests/snaps/python-entry-point/python2/python2_test_package/__main__.py
- integration_tests/snaps/python-entry-point/python2/setup.py
- integration_tests/snaps/python-entry-point/python3/python3_test_package/__main__.py
- integration_tests/snaps/python-entry-point/python3/setup.py
- integration_tests/test_clean_dependents.py
- integration_tests/test_gulp_plugin.py
- integration_tests/test_nodejs_plugin.py
- integration_tests/test_parts.py
- integration_tests/test_pkg_config.py
- integration_tests/test_rpath.py
- integration_tests/test_rust_plugin.py
- integration_tests/test_svn_pull.py
- integration_tests/test_tour.py
- integration_tests/test_yaml_in_subdir.py
- runtests.sh
> Enable the static checks for the integration tests

- snapcraft/plugins/nodejs.py
- snapcraft/tests/test_plugin_nodejs.py
> Add the arm64 architecture to the nodejs plugin

- snapcraft/plugins/go.py
- snapcraft/plugins/godeps.py
> Remove the useless call to os.path.join from the go plugin

- snapcraft/internal/sources.py
- snapcraft/tests/test_sources.py
> Make a copy of the snapcraft files common list before using it.

- snapcraft/main.py
> Minor fixes for typos in --help

- snapcraft/internal/meta.py
> Update kernel meta to the latest spec.

- debian/changelog
> Release changelog for 2.16

- debian/tests/control
- snaps_tests/__init__.py
> Use --force-dangerous when testing the installation of snaps

- snapcraft/internal/lifecycle.py
- snapcraft/tests/test_commands_init.py
- snapcraft/tests/test_commands_push.py
> Updated the contents of the snapcraft init template

- integration_tests/snaps/simple-autotools/Makefile.am
- integration_tests/snaps/simple-autotools/configure.ac
- integration_tests/snaps/simple-autotools/snapcraft.yaml
- integration_tests/snaps/simple-autotools/test.c
- integration_tests/test_autotools_plugin.py
> Add an integration test for autotools

- snapcraft/plugins/python.py
- snapcraft/tests/test_plugin_python2.py
- snapcraft/tests/test_plugin_python3.py
> Do not compile pyc files when installing with pip

- integration_tests/__init__.py
- integration_tests/test_store_register_key.py
- snapcraft/__init__.py
- snapcraft/_store.py
- snapcraft/main.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/store/test_store_client.py
- snapcraft/tests/test_commands_list_keys.py
- snapcraft/tests/test_commands_register_key.py
This augments `snap keys` by also showing which keys are registered to
your account on the store.
LP: #1621895
> Add `snapcraft list-keys`

- snapcraft/internal/pluginhandler.py
- snapcraft/tests/test_pluginhandler.py
> Support globbing for organize

- debian/changelog
> Release changelog for 2.17

- snapcraft/plugins/python.py
- snapcraft/tests/test_plugin_python2.py
- snapcraft/tests/test_plugin_python3.py
Requirements and Constraints file can be a local file or a url. Add
a simple check to use the appropriate path
LP: #1621543
> Check if option is url for pip

- integration_tests/snaps/wiki-filesets/snapcraft.yaml
- integration_tests/test_parts.py
- snapcraft/internal/errors.py
- snapcraft/internal/parts.py
- snapcraft/internal/project_loader.py
- snapcraft/tests/test_project_loader.py
Make sure the full project can be resolved before loading
the plugins from the parts
LP: #1622435
> Load project information in one location

- snaps_tests/demos_tests/test_busybox.py
> In the busybox test, use the last installed data dir

- snapcraft/file_utils.py
- snapcraft/plugins/make.py
- snapcraft/tests/test_file_utils.py
- snapcraft/tests/test_plugin_make.py
Hi -- submitting this in order to address some problems encountered snapping camlistore (https://bugs.launchpad.net/snapcraft/+bug/1624798). Please let me know if I can do anything to improve the PR -- thanks!
> make plugin: improve artifact copying (LP: #1624798)

- integration_tests/snaps/bad-yaml/snapcraft.yaml
- integration_tests/test_snap.py
- snapcraft/internal/project_loader.py
- snapcraft/tests/test_project_loader.py
> Report the proper line number on bad yaml errors

- snapcraft/storeapi/__init__.py
- snapcraft/tests/fake_servers.py
Using more appropriate API for fetching specific snap details (on <channel> and <arch>).
> Replacing deprecated API for searching snaps.

- snapcraft/_baseplugin.py
- snapcraft/internal/sources.py
- snapcraft/tests/__init__.py
- snapcraft/tests/test_plugin_gulp.py
- snapcraft/tests/test_plugin_nodejs.py
- snapcraft/tests/test_sources.py
> Make source-depth a parameter and opt-in

- debian/changelog
> Release changelog for 2.18

- integration_tests/snaps/python-and-plainbox-do-not-conflict/2016.com.example:simple/manage.py
- integration_tests/snaps/python-and-plainbox-do-not-conflict/2016.com.example:simple/units/simple.pxu
- integration_tests/snaps/python-and-plainbox-do-not-conflict/snapcraft.yaml
- snapcraft/plugins/plainbox_provider.py
- snapcraft/tests/test_plugin_plainbox_provider.py
> plainbox-provider plugin: rewrite python shebangs

- debian/changelog
> Release changelog for 2.18.1

- snapcraft/_schema.py
- snapcraft/tests/test_project_loader.py
Provide a more specific path for an entry that does not pass
validation.
LP: #1627734
> yaml xpath for errors.

- snapcraft/internal/pluginhandler.py
- snapcraft/tests/test_pluginhandler.py
> pluginhandler: take the file encoding into account.

- integration_tests/test_python_plugin.py
- snapcraft/plugins/python.py
- snapcraft/tests/test_plugin_python.py
> python plugin: only download in pull and build in build.

- debian/changelog
> Release changelog for 2.19

- HACKING.md
- snapcraft/tests/test_sources.py
- tools/staging_env.sh
This is a sourceable script which would make it easy to work
against the staging servers.
LP: #1630083
> tools: script to talk to the staging servers

- snapcraft/internal/pluginhandler.py
- snapcraft/internal/states/_build_state.py
- snapcraft/internal/states/_prime_state.py
- snapcraft/internal/states/_pull_state.py
- snapcraft/internal/states/_stage_state.py
- snapcraft/internal/states/_state.py
- snapcraft/tests/test_pluginhandler.py
- snapcraft/tests/test_states_build.py
- snapcraft/tests/test_states_prime.py
- snapcraft/tests/test_states_pull.py
- snapcraft/tests/test_states_stage.py
> Decouple state handling from plugin options.

- docs/snapcraft-syntax.md
- docs/upload-your-snap.md
Document the `grade` option.
LP: #1630914
> Document the grade option

- integration_tests/snaps/pip-bzr/snapcraft.yaml
- integration_tests/test_python_plugin.py
- snapcraft/plugins/python.py
> python plugin: allow usage of bzr

- snapcraft/_options.py
- snapcraft/tests/test_options.py
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>
> Add powerpc (32bit big-endian) support

- integration_tests/test_store_history.py
- snapcraft/_store.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/store/test_store_client.py
- snapcraft/tests/test_commands_history.py
- snapcraft/tests/test_commands_release.py
Also benefiting of RFC3339 (snapd/SAS) timestamps from the Store.
LP: #1632155
> history/status alignment fixes.

- integration_tests/snaps/pip-root-data-files/setup.py
- integration_tests/snaps/pip-root-data-files/snapcraft.yaml
- integration_tests/test_python_plugin.py
- snapcraft/plugins/python.py
- snapcraft/tests/__init__.py
- snapcraft/tests/test_plugin_python.py
This will avoid a rebuild and dtrt wrt data_files.
LP: #1631071
> python plugin: install from wheel for local setup.py

- snapcraft/internal/parts.py
- snapcraft/internal/pluginhandler.py
- snapcraft/tests/test_commands_clean.py
- snapcraft/tests/test_pluginhandler.py
- snapcraft/tests/test_project_loader.py
LP: #1633163
Signed-off-by:` Sergio Schvezov <sergio.schvezov@ubuntu.com>
> Parametrize call args for pluginhandler

- snapcraft/plugins/python.py
- snapcraft/tests/test_plugin_python.py
> python plugin: wheel and install in the proper order

- debian/changelog
> Release changelog for 2.21

- schema/snapcraft.yaml
- snapcraft/internal/errors.py
- snapcraft/internal/meta.py
- snapcraft/tests/test_meta.py
- snapcraft/tests/test_project_loader.py
> Support for gadget snaps

- snapcraft/__init__.py
- snapcraft/main.py
- snapcraft/storeapi/__init__.py
- snapcraft/tests/test_main.py
> store: send snapcraft version in a header

- debian/changelog
> Release changelog for 2.22

- debian/changelog
> Release changelog for 2.22.1

- README.md
> readme: rocket instead of irc

- tools/retry_autopkgtest.sh
> Add a script to retry autopktests

- snaps_tests/__init__.py
- snaps_tests/testbed.py
> Remove the outdated all snaps image set up for snaps tests

- docs/metadata.md
- docs/snapcraft-syntax.md
- Icon is explained as a declarative entry
- desktop file is documented (as by-contention)
LP: #1642958
> docs: update GUI related integrations

- snapcraft/tests/test_plugin_gradle.py
> On gradle unit tests, unset the proxies

- demos/downloader-with-wiki-parts/test.c
- snaps_tests/demos_tests/test_downloader_with_wiki_parts.py
> Use the connectivity check page to test the downloader snap

- .travis.yml
- HACKING.md
- debian/control
- setup.py
- snapcraft/file_utils.py
- snapcraft/internal/deltas/__init__.py
- snapcraft/internal/deltas/_deltas.py
- snapcraft/internal/deltas/_xdelta.py
- snapcraft/internal/deltas/errors.py
- snapcraft/tests/test_deltas.py
- snapcraft/tests/test_deltas_xdelta.py
- snapcraft/tests/test_file_utils.py
Add a new package "deltas" and implement the XDelta based delta generation feature.
By specifying the source file and target file, it can generate the delta file base on xdelta algorithm. 
(Flexible to extend to use the other algorithms like *bsdiff* later)
LP: #1642822
> create the deltas package/class with xdetal generation implementation

- external_snaps_tests/__main__.py
- snaps_tests/__main__.py
> Add a test script to build external snaps

- .travis.yml
- HACKING.md
- debian/control
- snapcraft/file_utils.py
- snapcraft/internal/deltas/__init__.py
- snapcraft/internal/deltas/_deltas.py
- snapcraft/internal/deltas/_xdelta3.py
- snapcraft/tests/test_deltas.py
- snapcraft/tests/test_deltas_xdelta3.py
> deltas: migrate from xdelta to xdelta3.

- .travis.yml
- README.md
> Replace coveralls with codecov

- snapcraft/tests/test_commands_help.py
- snapcraft/tests/test_file_utils.py
- snapcraft/tests/test_meta.py
- snapcraft/tests/test_plugin_copy.py
- snapcraft/tests/test_plugin_dump.py
- snapcraft/tests/test_pluginhandler.py
- snapcraft/tests/test_project_loader.py
- snapcraft/tests/test_repo.py
- snapcraft/tests/test_states_build.py
- snapcraft/tests/test_states_prime.py
- snapcraft/tests/test_states_pull.py
- snapcraft/tests/test_states_stage.py
This is the first step to switch to testtools, for LP: #1593079
> Replace subTests with TestScenarios

- debian/tests/integrationtests
- debian/tests/snapstests
- snapcraft/tests/test_commands_push.py
> Fix unittests in armhf

- integration_tests/snaps/ftp-source/snapcraft.yaml
> tests: Use a more stable ftp source

- demos/git/snapcraft.yaml
- snapcraft/_options.py
- snapcraft/internal/common.py
- snapcraft/internal/meta.py
- snapcraft/internal/parts.py
- snapcraft/internal/project_loader.py
- snapcraft/tests/test_meta.py
- snapcraft/tests/test_project_loader.py
- snaps_tests/__init__.py
- snaps_tests/demos_tests/tests.py
This requires setting up some paths to the core snap.
<a href='https://bugs.launchpad.net/bugs/1647699'>LP: #1647699</a>
> project: support building classic snaps

- debian/tests/control
- requirements-devel.txt
- snaps_tests/__init__.py
> tests: idempotent store installs.

- debian/snapcraft-completion
- snapcraft/main.py
- snapcraft/tests/test_commands_list_plugins.py
> cli: make plugins be an alias of list-plugins

- integration_tests/snaps/scriptlet-install/snapcraft.yaml
- integration_tests/test_scriptlets.py
- schema/snapcraft.yaml
- snapcraft/__init__.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/pluginhandler/_scriptlets.py
- snapcraft/tests/pluginhandler/mocks.py
- snapcraft/tests/pluginhandler/test_pluginhandler.py
- snapcraft/tests/pluginhandler/test_scriptlets.py
> pluginhandler: install scriptlet support

- snapcraft/internal/parser.py
> parser - Use the same version method as 'snapcraft'

- snapcraft/plugins/cmake.py
- snapcraft/tests/test_plugin_cmake.py
https://bugs.launchpad.net/snapcraft/+bug/1650078
> Updated cmake plugin to use get_build_properties()

- snapcraft/plugins/waf.py
- snapcraft/tests/test_plugin_waf.py
https://bugs.launchpad.net/snapcraft/+bug/1650079
> Updated waf plugin to use get_build_properties()

- demos/scons/SConstruct
- demos/scons/hello.c
- demos/scons/snapcraft.yaml
- demos/scons/wrapper
- snapcraft/plugins/scons.py
- snapcraft/tests/test_plugin_scons.py
- demos/scons
- test_plugin_scons.py
https://bugs.launchpad.net/snapcraft/+bug/1650303
> Updated scons plugin to use get_build_properties()

- snapcraft/internal/parser.py
> Better message for missing snapcraft.yaml in origins.

- snapcraft/plugins/autotools.py
- snapcraft/tests/test_plugin_autotools.py
Also updated schema test in unit tests.
Added tests for get_pull_properties()  to test.
https://bugs.launchpad.net/snapcraft/+bug/1650608
> Updated autotools plugin to use get_build_properties()

- snapcraft/plugins/catkin.py
- snapcraft/tests/test_plugin_catkin.py
Also updated schema test in unit tests.
Added tests for get_pull_properties() to test.
https://bugs.launchpad.net/snapcraft/+bug/1650628
> plugins: update catkin plugin to use get_pull_properties()

- snapcraft/plugins/nodejs.py
- snapcraft/tests/test_plugin_nodejs.py
Updated nodjs to use get_build_properties() and get_pull_properties()
Updated the schema testing in the unit tests.
Added get_build_properties() and get_pull_properties() to the test file.
https://bugs.launchpad.net/snapcraft/+bug/1650600
> Updated nodejs plugin to use get_build_properties()

- snapcraft/plugins/python.py
- snapcraft/tests/test_plugin_python.py
Also updated schema test in unit tests.
Added tests for get_pull_properties() to test.
https://bugs.launchpad.net/snapcraft/+bug/1650626
> plugins: update python plugin to support get_pull_properties()

- snapcraft/plugins/qmake.py
- snapcraft/tests/test_plugin_qmake.py
https://bugs.launchpad.net/snapcraft/+bug/1650553
Also updated unit tests
> plugins: update qmake to use get_build_properties and get_pull_properties()

- snapcraft/plugins/gulp.py
- snapcraft/tests/test_plugin_gulp.py
Also updated schema test in unit tests.
Added tests for get_pull_properties() and get_build_properties() to test.
https://bugs.launchpad.net/snapcraft/+bug/1650603
> plugins: update gulp plugin to use get_build_properties() and get_pull_properties()

- .travis.yml
We can do things in multiple lines keeping things more readable and clean
> travis.yaml: use docker exec to split build phases

- PULL_REQUEST_TEMPLATE.md
> ci: add a checklist in the pull request template

- snapcraft/plugins/nodejs.py
> nodejs plugin: fix the plugin’s dependency installation

- snapcraft/tests/commands/test_clean.py
> tests: fix broken unit test in master

- integration_tests/snaps/rust-with-conditional/Cargo.toml
- integration_tests/snaps/rust-with-conditional/snapcraft.yaml
- integration_tests/snaps/rust-with-conditional/src/main.rs
- integration_tests/snaps/simple-rust/Cargo.toml
- integration_tests/snaps/simple-rust/src/main.rs
- integration_tests/test_rust_plugin.py
- snapcraft/plugins/rust.py
- snapcraft/tests/plugins/test_rust.py
LP: [#1654485](https://bugs.launchpad.net/snapcraft/+bug/1654485)
> rust plugin: add conditional compilation

- snapcraft/internal/parts.py
- snapcraft/tests/commands/test_define.py
> parts: better error message when defining parts

- schema/snapcraft.yaml
- snapcraft/tests/test_project_loader.py
> schema: support the notify daemon type

- integration_tests/snaps/rust-with-revision/snapcraft.yaml
- integration_tests/test_rust_plugin.py
> Run the rust test in armhf

- docs/hooks.md
Finish off LP: [#1586465](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1586465) by documenting how to use snapcraft's hook support.
> Add documentation for hooks.

- integration_tests/snaps/rust-subdir/snapcraft.yaml
- integration_tests/snaps/rust-subdir/subdir/Cargo.toml
- integration_tests/snaps/rust-subdir/subdir/src/main.rs
- integration_tests/test_rust_plugin.py
- snapcraft/plugins/rust.py
- snapcraft/tests/plugins/test_rust.py
LP: [#1654764](https://bugs.launchpad.net/snapcraft/+bug/1654764)
> rust plugin: use the part source path

- integration_tests/test_godeps_plugin.py
- snapcraft/plugins/godeps.py
> godeps plugin: work when GOBIN is set

- debian/changelog
> Release changelog for 2.25

- snapcraft/internal/parser.py
- snapcraft/tests/__init__.py
- snapcraft/tests/test_parser.py
> Handle parser errors better.

- .travis.yml
LP: [#1655790](https://bugs.launchpad.net/snapcraft/+bug/1655790)
> tests: use python2 to check the CLA

- snapcraft/_store.py
> store: proper error colors for login failures.

- snapcraft/storeapi/constants.py
LP: [#1650939](https://bugs.launchpad.net/snapcraft/+bug/1650939)
> ui: add a space after the developer agreement prompt

- snaps_tests/__init__.py
LP: [#1643658](https://bugs.launchpad.net/snapcraft/+bug/1643658)
> tests: use a temporary directory for snaps tests

- .tarmac.sh
LP: [#1659308](https://bugs.launchpad.net/snapcraft/+bug/1659308)
> misc: remove the old tarmac file

- integration_tests/hidden_parts_wiki
- snapcraft/internal/parser.py
- snapcraft/tests/test_parser.py
> Return an error code if an origin is missing a part.

- snaps_tests/__init__.py
- snaps_tests/demos_tests/test_git.py
- snaps_tests/demos_tests/test_ros.py
LP: [#1658875](https://bugs.launchpad.net/snapcraft/+bug/1658875)
> tests: increase the timeout for the ros snap test, decrease the rest

- debian/tests/integrationtests
- debian/tests/snapstests
> tests:  add ubuntu user to sudoers on every adt platform 

- debian/changelog
> Release changelog for 2.26

- integration_tests/__init__.py
- integration_tests/test_empty_dir.py
- integration_tests/test_list_plugins.py
- integration_tests/test_parts.py
- snapcraft/main.py
- snapcraft/tests/test_main.py
LP: [1659817](https://bugs.launchpad.net/snapcraft/+bug/1659817)
> print snapcraft's version on startup when running with --debug

- snapcraft/internal/lifecycle.py
- snapcraft/tests/test_lifecycle.py
LP: [#1590811](https://bugs.launchpad.net/snapcraft/+bug/1590811)
> lifecycle: print the command needed to clean the dirty part

- tools/cla_check_in_travis.sh
LP: [#1657571](https://bugs.launchpad.net/snapcraft/+bug/1657571)
> tests: check the CLA on all the commits

- .travis.yml
LP: [#1663088](https://bugs.launchpad.net/snapcraft/+bug/1663088)
> tests: fix the env vars passed to the docker container in travis

- snapcraft/tests/plugins/test_python.py
LP: [#1663396](https://bugs.launchpad.net/snapcraft/+bug/1663396)
> tests: fix the test that was modifying the environment variables

- integration_tests/snaps/python-with-two-parts/snap/snapcraft.yaml
- integration_tests/test_python_plugin.py
- snapcraft/plugins/python.py
- snapcraft/tests/plugins/test_python.py
LP: [#1663739](https://bugs.launchpad.net/snapcraft/+bug/1663739)
> python plugin: exclude the RECORD files

- debian/changelog
> Release changelog for 2.27

- .travis.yml
- tools/make_beta_pr.py
LP: [#1662975](https://bugs.launchpad.net/snapcraft/+bug/1662975)
> Trigger beta tests on travis every day.

- snapcraft/_store.py
- snapcraft/tests/commands/test_release.py
> Switch Track and Arch in channel maps

- debian/changelog
> Changelog for 2.27.1

- snapcraft/_store.py
- snapcraft/tests/commands/test_release.py
> channel maps: remove 'Series' from output

- snapcraft/plugins/python.py
- snapcraft/tests/plugins/test_python.py
When using staged python, the plugin should also use staged
python headers instead of those on the system.
LP: #1666488
> python plugin: use stage headers if applicable.

- tools/gen_api_docs.sh
> docs: use correct target to generate docs.

- .gitignore
- requirements.txt
- snap/snapcraft.yaml
- snapcraft/internal/common.py
- snapcraft/internal/libraries.py
- snapcraft/internal/project_loader.py
- snapcraft/internal/repo.py
- snapcraft/tests/test_project_loader.py
Integration work to build snapcraft as a snap.
LP: #1666908
> packaging: snapcraft as a snap

- .travis.yml
LP: [#1669247](https://bugs.launchpad.net/snapcraft/+bug/1669247)
> tests:install wget in the container that triggers the beta tests

- demos/mosquitto/launchers/subscribe.py
- snaps_tests/demos_tests/test_mosquitto.py
LP: [#1577867](https://bugs.launchpad.net/snapcraft/+bug/1577867)
> demos, tests: add a message to exit the mosquitto subscriber

- demos/godd/snap/snapcraft.yaml
- snaps_tests/demos_tests/test_godd.py
- snaps_tests/demos_tests/tests.py
LP: [#1544243](https://bugs.launchpad.net/snapcraft/+bug/1544243)
> demos, tests: add the mount-observe plug to be able to run godd

- external_snaps_tests/__main__.py
- runtests.sh
LP: [#1671620](https://bugs.launchpad.net/snapcraft/+bug/1671620)
> tests: support snap directory in external tests

- snapcraft/_store.py
- snapcraft/tests/commands/test_push.py
- snapcraft/tests/fixture_setup.py
> store: enable delta uploads by default when pushing.

- tools/retry_autopkgtest.sh
LP: [#1673981](https://bugs.launchpad.net/snapcraft/+bug/1673981)
> tests: allow to run individual autopkgtest suites

- integration_tests/__init__.py
- integration_tests/snaps/python-pbr/python2/python2_test_package/main.py
- integration_tests/snaps/python-pbr/python2/setup.cfg
- integration_tests/snaps/python-pbr/python2/setup.py
- integration_tests/snaps/python-pbr/python3/python3_test_package/main.py
- integration_tests/snaps/python-pbr/python3/setup.cfg
- integration_tests/snaps/python-pbr/python3/setup.py
- integration_tests/snaps/python-pbr/snapcraft.yaml
- integration_tests/test_python_plugin.py
- snapcraft/plugins/python.py
- snapcraft/tests/plugins/test_python.py
Create the entry_points/console_scripts defined in setup.cfg
when using pbr in setup.py
LP: #1670852
> python plugin: support pbr/setup.cfg projects.

- integration_tests/test_rust_plugin.py
- snaps_tests/demos_tests/test_ros.py
LP: [#1662917](https://bugs.launchpad.net/snapcraft/+bug/1662917)
> tests: expect failures for the tests that can't be run in arm64

- integration_tests/snaps/build-package-version-global/snap/snapcraft.yaml
- integration_tests/snaps/build-package-version/snap/snapcraft.yaml
- integration_tests/test_build_package_version.py
> asset-tracking: use a more likely to be found global build-package

- debian/changelog
> Release changelog for 2.28

- integration_tests/test_store_status.py
> channels: Fix staging store test for Tracks.

- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/project_loader.py
- snapcraft/internal/states/__init__.py
- snapcraft/internal/states/_state.py
- snapcraft/tests/pluginhandler/test_pluginhandler.py
> pluginhandler: factor out state bits into the state package.

- tools/make_beta_pr.py
LP: [#1675107](https://bugs.launchpad.net/snapcraft/+bug/1675107)
> Add platforms for the nightly tests

- CONTRIBUTING.md
Reflect the fact that we no longer require bugs.
> docs: update contribution guide.

- snapcraft/plugins/catkin.py
- snapcraft/tests/plugins/test_catkin.py
The environment created by the Catkin plugin is really only completely valid at runtime (i.e. when packaged as a snap). It's partially valid at build-time. However, it turns out that as a result of sourcing `setup.sh` (which is required at build-time), various dependencies actually need the valid run-time environment (e.g. `LD_LIBRARY_PATH`, valid `ROS_HOME`, etc.).
This PR fixes LP: [#1674487](https://bugs.launchpad.net/snapcraft/+bug/1674487) by making sure `LD_LIBRARY_PATH` is defined before we source `setup.sh`. It also makes sure `ROS_HOME` is always pointing to a valid place.
> catkin plugin: create completely valid environment

- integration_tests/__init__.py
- integration_tests/store/test_store_close.py
- integration_tests/store/test_store_push.py
- integration_tests/store/test_store_register.py
- integration_tests/store/test_store_registered.py
- integration_tests/store/test_store_release.py
- integration_tests/store/test_store_revisions.py
- integration_tests/store/test_store_sign_build.py
- integration_tests/store/test_store_status.py
- snapcraft/storeapi/errors.py
- snapcraft/tests/fake_servers.py
- snapcraft/tests/store/test_store_client.py
Coping with recently added snap-name size limit (40-chars) in Store.
Pending more specific error response from the store. See LP: #1681545
> Fixing Store integration tests.

- demos/shout/snap/snapcraft.yaml
- demos/webchat/snap/snapcraft.yaml
- integration_tests/plugins/test_nodejs_plugin.py
- integration_tests/snaps/nodejs-hello/snapcraft.yaml
- integration_tests/snaps/nodejs-with-run-commands/snapcraft.yaml
- snapcraft/plugins/nodejs.py
- snapcraft/tests/plugins/test_nodejs.py
> nodejs plugin: add support for yarn.

- .travis.yml
> ci: fix travis ordering for locales generation.

- snapcraft/plugins/ant.py
- snapcraft/tests/plugins/test_ant.py
> ant plugin: honour proxy configuration

- requirements.txt
- snapcraft/internal/repo/__init__.py
- snapcraft/internal/repo/_base.py
- snapcraft/internal/repo/_platform.py
- snapcraft/internal/sources/__init__.py
- snapcraft/sources.py
As long as the operating system provides the right toolset, allow
cleanbuilds to go through.
> core: support running from other operating systems.

- integration_tests/plugins/test_rust_plugin.py
- snapcraft/plugins/rust.py
- snapcraft/shell_utils.py
Update the rust plugin to link shared libraries in correctly
> Update rust plugin to set RUSTFLAGS

- snapcraft/internal/meta.py
- snapcraft/shell_utils.py
- snapcraft/tests/test_meta.py
Clean up code for better reuse and make more of the logic
make use of these helpers.
> shell_utils: code cleanup.

- debian/changelog
> release changelog for 2.29

- snapcraft/internal/lifecycle.py
- snapcraft/tests/commands/test_init.py
LP: [#1660880](https://bugs.launchpad.net/snapcraft/+bug/1660880)
> init: add a newline at the end of the file

- snap/snapcraft.yaml
- snapcraft/__init__.py
Also use the version from snap.yaml when running from the snap.
> core: switch to version git.

- integration_tests/__init__.py
- integration_tests/snaps/build-packages-missing-dependency/snap/snapcraft.yaml
- integration_tests/snaps/build-packages-without-dependencies/snap/snapcraft.yaml
- integration_tests/snaps/stage-packages-missing-dependency/snap/snapcraft.yaml
- integration_tests/test_snapcraft_recording.py
- integration_tests/test_stage_package_version.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/repo/_deb.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/pluginhandler/test_pluginhandler.py
- snapcraft/tests/test_lifecycle.py
LP: [#1688151](https://bugs.launchpad.net/snapcraft/+bug/1688151)
> asset-tracking: save the dependencies of build packages

- integration_tests/__init__.py
- integration_tests/snaps/desktop-with-non-ascii/snap/snapcraft.yaml
- integration_tests/snaps/desktop-with-non-ascii/test.desktop
- integration_tests/test_prime.py
- snapcraft/internal/meta.py
LP: [#1662456](https://bugs.launchpad.net/snapcraft/+bug/1662456)
> meta: read and write the desktop file with utf-8 encoding

- snapcraft/_store.py
LP: [#1689953](https://bugs.launchpad.net/snapcraft/+bug/1689953)
> allow capital Y to accept the dev agreement

- manual-tests.md
- snapcraft/internal/lxd.py
- snapcraft/tests/test_lxd.py
LP: [#1662456](https://bugs.launchpad.net/snapcraft/+bug/1662456)
> cleanbuild: set the container language to C.UTF-8

- integration_tests/__init__.py
- integration_tests/test_pull_properties.py
- snapcraft/internal/repo/_deb.py
- snapcraft/tests/test_lifecycle.py
LP: [#1691569](https://bugs.launchpad.net/snapcraft/+bug/1691569)
> state: ignore the 'any' architecture in the build packages apt cache

- integration_tests/snaps/build-virtual-package/snap/snapcraft.yaml
- integration_tests/test_pull_properties.py
- snapcraft/internal/repo/_deb.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/test_lifecycle.py
LP: [#1691580](https://bugs.launchpad.net/snapcraft/+bug/1691580)
>  state: search for the build package that provides a virtual package

- debian/changelog
> Release changelog for 2.30

- debian/changelog
> release changelog for 2.31

- snapcraft/tests/test_meta.py
Use the nifty `_create_file` that was added to the test module and take advantage of testtools.
> tests: reduce the amount of test code in test_meta

- schema/snapcraft.yaml
- snap/snapcraft.yaml
- snapcraft/internal/errors.py
- snapcraft/internal/meta.py
- snapcraft/tests/test_meta.py
Support in snapcraft and for snapcraft.
LP: #1590767
> meta: bash completion support

- snapcraft/tests/fixture_setup.py
- snapcraft/tests/test_lxd.py
- snapcraft/tests/test_project_loader.py
> tests: fix issues with python 3.6

- integration_tests/snaps/stage-with-two-equal-files/snap/snapcraft.yaml
- integration_tests/test_stage.py
- snapcraft/internal/lifecycle.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/tests/pluginhandler/test_pluginhandler.py
LP: [#1660696](https://bugs.launchpad.net/snapcraft/+bug/1660696)
> pluginhandler: check for collisions only in existing files

- requirements.txt
- setup.py
- snapcraft/_options.py
- snapcraft/internal/indicators.py
- snapcraft/internal/lxd.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/repo/_platform.py
- snapcraft/internal/sources/__init__.py
- snapcraft/sources.py
> core: minimal windows support.

- snapcraft/plugins/nodejs.py
- snapcraft/tests/plugins/test_nodejs.py
LP: [#1702661](https://bugs.launchpad.net/snapcraft/+bug/1702661)
> nodejs plugin: copy the content of out of tree symlinks

- snapcraft/internal/errors.py
- snapcraft/internal/lifecycle.py
- snapcraft/internal/repo/__init__.py
- snapcraft/internal/repo/_deb.py
- snapcraft/tests/test_lifecycle.py
> cli: better error message for missing mksquashfs

- snapcraft/plugins/_ros/rosdep.py
- snapcraft/plugins/catkin.py
- snapcraft/tests/plugins/ros/test_rosdep.py
- snapcraft/tests/plugins/test_catkin.py
This PR makes progress on #1444 and LP: [#1683036](https://bugs.launchpad.net/snapcraft/+bug/1683036) by adding the ability for rosdep to parse multiple dependency types. It also updates the catkin plugin to support the new API, but it still only supports debs right now (it'll raise an exception if the dependency type is anything else). This is paving the way for support of pip dependencies coming from rosdep. Actually supporting this will require some experimentation, and of course, a design proposal.
> rosdep: add support for multiple dependency types

- demos/mosquitto/snap/snapcraft.yaml
> demos: update the name of the remote mqtt part

- debian/changelog
- debian/tests/integrationtests
- integration_tests/test_build_snap_grammar.py
> Release changelog for 2.34

- snapcraft/internal/repo/_deb.py
> typo: replace occured with occurred

- integration_tests/test_build_snap_grammar.py
- integration_tests/test_build_snaps.py
- snapcraft/tests/fixture_setup.py
-----
There are two missing scenarios because of bugs:
https://bugs.launchpad.net/snapcraft/+bug/1716054
https://bugs.launchpad.net/snapcraft/+bug/1716055
> tests: add integration tests for build snaps

- integration_tests/test_asset_recording.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/states/_build_state.py
- snapcraft/tests/test_lifecycle.py
> recording: record the machine information collected by uname

- demos/ruby-hello/ruby-hello.rb
- demos/ruby-hello/snap/snapcraft.yaml
- integration_tests/plugins/test_ruby_plugin.py
- integration_tests/snaps/ruby-bins-exist/snapcraft.yaml
- integration_tests/snaps/ruby-bundle-install/Gemfile
- integration_tests/snaps/ruby-bundle-install/snapcraft.yaml
- integration_tests/snaps/ruby-gem-install/snapcraft.yaml
- snapcraft/plugins/ruby.py
- snapcraft/tests/commands/test_list_plugins.py
- snapcraft/tests/plugins/test_ruby.py
- snaps_tests/demos_tests/test_ruby_hello.py
> plugins: add the ruby plugin

- snapcraft/storeapi/constants.py
- snapcraft/tests/fixture_setup.py
- tools/staging_env.sh
myapps and search are deprecated.
LP: #1717990
-----
> store: switch to new endpoints

- snapcraft/tests/plugins/test_nodejs.py
> tests: simplify a little the data in nodejs unit tests

- runtests.sh
- setup.py
> static: fix flake8 errors in setup.py

- .travis.yml
> ci: use travis conditionals

- integration_tests/test_asset_recording.py
- snapcraft/internal/lifecycle.py
- snapcraft/internal/meta.py
- snapcraft/internal/repo/snaps.py
- snapcraft/internal/states/_global_state.py
- snapcraft/tests/fake_servers/snapd.py
- snapcraft/tests/repo/test_snaps.py
- snapcraft/tests/test_lifecycle.py
> recording: record build-snaps installed during the pull

- snapcraft/plugins/rust.py
- snapcraft/tests/plugins/test_rust.py
> rust plugin: record the Cargo.lock file

- snapcraft/plugins/rust.py
- snapcraft/tests/plugins/test_rust.py
> Record rust versions

- integration_tests/test_asset_recording.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/repo/snaps.py
- snapcraft/tests/fake_servers/snapd.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/repo/test_snaps.py
- snapcraft/tests/test_lifecycle.py
- snapcraft/tests/test_lxd.py
> recording: record the snaps installed on the machine

- CODE_STYLE.md
- snapcraft/tests/test_lifecycle.py
> style: use dedent for multiline strings

- snapcraft/internal/lxd.py
- snapcraft/tests/fake_servers/snapd.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/repo/test_snaps.py
- snapcraft/tests/test_lifecycle.py
- snapcraft/tests/test_lxd.py
> tests: refactor the fake snapd to not hardcode values

- snapcraft/internal/lxd.py
- snapcraft/tests/test_lxd.py
-----
Fixes: [bug 1719951](https://bugs.launchpad.net/snapcraft/+bug/1719951)
> lxd: pass SNAPCRAFT_PARTS_URI through into container

- CODE_STYLE.md
> code style: remove the extra quotes in the dedent example

- demos/ruby-hello/ruby-hello.rb
- integration_tests/snapd/test_ruby_snap.py
- integration_tests/snaps/ruby-hello/ruby-hello.rb
- integration_tests/snaps/ruby-hello/snap/snapcraft.yaml
-----
This also fixes the command in the ruby-hello snap.
> tests: move ruby demo test to snapd integration suite

- snapcraft/internal/lxd.py
-----
Fixes: [bug 1719996](https://bugs.launchpad.net/snapcraft/+bug/1719996)
> lxd: use SUDO_UID for ID mapping

- integration_tests/plugins/test_plainbox_provider_plugin.py
> tests: fix the duplicate plainbox test scenarios

- .travis.yml
- integration_tests/containers/test_cleanbuild.py
- integration_tests/test_snap.py
- runtests.sh
- tools/travis/run_lxd_container.sh
- tools/travis/run_tests.sh
- tools/travis/setup_lxd.sh
> tests: reenable the cleanbuild integration test

- snapcraft/tests/commands/test_snap.py
-----
#1588 introduced an error in this test when it is executed as root.
> lxd: fix the unit test for the user id map

- .travis.yml
- tools/travis/build_snapcraft_snap.sh
- tools/travis/run_lxd_container.sh
- tools/travis/run_tests.sh
> tests: use the snapcraft snap for integration tests

- snapcraft/internal/meta.py
- snapcraft/internal/project_loader/_config.py
- snapcraft/internal/project_loader/_env.py
- snapcraft/internal/project_loader/_parts_config.py
- snapcraft/tests/project_loader/test_config.py
- ~~If this is a new feature. Have you discussed the design on the [forum](https://forum.snapcraft.io)?~~
-----
Fixes https://bugs.launchpad.net/snapcraft/+bug/1720230
> project_loader: quote more environment variable values

- snapcraft/internal/os_release.py
-----
Small follow-up after review.
> internal: don't reuse variable in OsRelease

- snapcraft/internal/errors.py
- snapcraft/internal/lxd/_containerbuild.py
- snapcraft/internal/meta.py
- snapcraft/tests/commands/test_snap.py
- snapcraft/tests/fixture_setup.py
- snapcraft/tests/test_lifecycle.py
- snapcraft/tests/test_lxd.py
>  recording: record information from the image in container builds 

- snapcraft/plugins/ruby.py
- snapcraft/tests/plugins/test_ruby.py
-----
Ruby uses some pretty convoluted rules for generating its arch-specific paths, some of which is hard-coded. This path follows a different pattern depending on the architecture on which it runs. As a result, the current Ruby plugin doesn't work on any arch other than amd64 and i386.
Rather than try and be smart about these paths, use globbing to detect them using files we know are in there. That will allow this plugin to start working across all supported architectures.
> ruby plugin: be smarter about arch-specific paths

- snapcraft/internal/lxd/_containerbuild.py
- snapcraft/tests/test_lxd.py
> recording: pass the build info flag to the container

- snapcraft/tests/test_log.py
We need to be less strict given that rogue messages show up when
setting up the log level. We now check for the messages and the
format we want instead of exact output.
-----
> unit tests: make the check for output less strict

- debian/changelog
> Release changelog for 2.35

- requirements-devel.txt
- snapcraft/_store.py
- snapcraft/internal/states/_build_state.py
- snapcraft/internal/states/_global_state.py
- snapcraft/internal/states/_prime_state.py
- snapcraft/internal/states/_pull_state.py
- snapcraft/internal/states/_stage_state.py
- snapcraft/scripts/generate_reference.py
- snapcraft/storeapi/__init__.py
Update to the newest flake8 and fix the issues that it detected.
-----
> static tests: upgrade to the newest flake8

- snapcraft/tests/fixture_setup.py
- snapcraft/tests/integration/general/test_catkin.py
- snapcraft/tests/integration/snapd/test_catkin_snap.py
> tests: share the cache in ros tests

- snapcraft/_store.py
- snapcraft/cli/echo.py
- snapcraft/cli/store.py
- snapcraft/config.py
- snapcraft/integrations/travis.py
- snapcraft/storeapi/__init__.py
- snapcraft/tests/integration/__init__.py
- snapcraft/tests/unit/commands/test_register_key.py
-----
This PR resolves #1709, paving the way toward using attenuated macaroons outside of just `enable-ci travis`.
> store: refactor acquirement of attenuated macaroon

- debian/changelog
> Release changelog for 2.36

- runtests.sh
Simple, but I don't think there is need for anything more…
-----
> Add --help command for the runtests.sh script

- .travis.yml
- requirements-devel.txt
- runtests.sh
- snapcraft/cli/store.py
- tools/travis/run_codespell.sh
> tests: run codespell as part of static tests

- snapcraft/file_utils.py
Add type hinting support to snapcraft/file_utils.py according to PEP 484
-----
> Add type hinting to file_utils.py

- CODE_STYLE.md
- snapcraft/internal/errors.py
- snapcraft/tests/integration/general/test_multiarch_stage_packages.py
- snapcraft/tests/integration/general/test_stage.py
- snapcraft/tests/integration/general/test_stage_package_version.py
- snapcraft/tests/test_errors.py
- snapcraft/tests/unit/commands/test_cleanbuild.py
- snapcraft/tests/unit/commands/test_define.py
- snapcraft/tests/unit/commands/test_snap.py
- snapcraft/tests/unit/pluginhandler/test_plugin_loader.py
- snapcraft/tests/unit/pluginhandler/test_pluginhandler.py
- snapcraft/tests/unit/project_loader/test_config.py
- snapcraft/tests/unit/test_errors.py
- snapcraft/tests/unit/test_lifecycle.py
- snapcraft/tests/unit/test_meta.py
- snapcraft/tests/unit/test_parser.py
-----
First iteration over the suggestions by mpt.
> cli: add what, why, and how to fix to the common errors

- debian/changelog
> Changelog for release 2.37

- snapcraft/tests/fake_servers/api.py
- snapcraft/tests/unit/store/test_store_client.py
> tests: update the registered snap fake

- snapcraft/internal/lifecycle/_runner.py
- snapcraft/tests/unit/test_lifecycle.py
Detect docker container to automatically setup the core snap when working with
classic confinement.
-----
> lifecycle: detect docker to auto setup core

- .travis.yml
- tools/collect_ppa_autopkgtests_results.py
- tools/travis/collect_ppa_autopkgtests_results.sh
- tools/travis/run_lxd_container.sh
- tools/travis/run_ppa_autopkgtests.sh
> tests: collect the autopkgtest results and save them in git 

- setup.py
- snapcraft/internal/meta/__init__.py
- snapcraft/internal/meta/_desktop.py
- snapcraft/internal/meta/_errors.py
- snapcraft/internal/meta/_manifest.py
- snapcraft/internal/meta/_snap_packaging.py
- snapcraft/internal/meta/_version.py
- snapcraft/tests/unit/test_meta.py
> meta: refactor into a package

- snapcraft/formatting_utils.py
-----
Add type hints to snapcraft/formatting_utils.py.
> static tests: add type hints to formatting_utils

- snapcraft/internal/dirs.py
- snapcraft/internal/project_loader/_env.py
- snapcraft/internal/sources/_checksum.py
-----
Added type hints to some modules.
> Add typings to some modules

- debian/changelog
> Release changelog for 2.38

- snapcraft/plugins/cmake.py
-----
Updates the cmake plugin details to include the information about the keywords from the make plugin. Fixes [#1647931](https://bugs.launchpad.net/snapcraft/+bug/1647931).
> cmake plugin: update plugin details

- docker/Readme.md
- docker/snap-beta.Dockerfile
- docker/snap-edge.Dockerfile
> docker: instructions to build from the snap

- snapcraft/plugins/kernel.py
- snapcraft/tests/unit/plugins/test_kernel.py
https://bugs.launchpad.net/snapcraft/+bug/1740882
-----
> kernel plugin: update initrd.img-core path to boot/initrd.img

- snapcraft/tests/unit/store/test_store_client.py
> tests: add snap not found tests

- snapcraft/extractors/appstream.py
- snapcraft/tests/unit/extractors/test_appstream.py
> extractors: also support appdata.xml appstream files.

- snapcraft/tests/matchers.py
> tests: call file directly for the HasArchitecture checker

- snapcraft/plugins/kernel.py
- snapcraft/tests/unit/plugins/test_kernel.py
> kernel plugin: remove dependency on magic

- snapcraft/internal/lxd/_cleanbuilder.py
- snapcraft/internal/lxd/_containerbuild.py
- snapcraft/internal/lxd/_project.py
- snapcraft/tests/unit/test_lxd.py
-----
Fixes: [LP: #1741752](https://bugs.launchpad.net/snapcraft/+bug/1741752)
> lxd: always (re-)injects snaps

- snapcraft/cli/_options.py
This is a one character typo fix in a help string, I'm not sure how relevant that checklist is :)
Being a Canonical employee covers the CLA question.
> Fixed typo

- docker/Readme.md
- docker/snap-beta.Dockerfile
- docker/snap-edge.Dockerfile
-----
Right now they're backwards.
> docker: beta should use beta, edge use edge

- docker/Readme.md
> docker: user proper tags in Readme.md

- debian/control
- snap/snapcraft.yaml
- snapcraft/_store.py
- snapcraft/file_utils.py
- snapcraft/internal/cache/_snap.py
- snapcraft/internal/elf.py
- snapcraft/internal/lifecycle/_packer.py
- snapcraft/internal/lifecycle/_runner.py
- snapcraft/plugins/kernel.py
- snapcraft/tests/unit/commands/test_push.py
- snapcraft/tests/unit/commands/test_snap.py
> many: use in-snap unsquashfs and readelf if running from snap

- debian/changelog
> Release 2.39

- debian/tests/integrationtests
> tests: setup the correct environment for adt

- schema/snapcraft.yaml
- snapcraft/tests/unit/project_loader/test_config.py
-----
In response to https://forum.snapcraft.io/t/3974, update Snapcraft to use the same pattern for version validation as snapd and the review tools.
> schema: update version regex

- snapcraft/internal/elf.py
- snapcraft/internal/mangling.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/project_loader/_parts_config.py
- snapcraft/tests/unit/__init__.py
- snapcraft/tests/unit/test_elf.py
> elf: cache crawled files

- requirements-devel.txt
-----
This is the newest version of mypy. I see no downside to updating, and it makes Atom happy.
> mypy: update to 0.560

- .travis.yml
- debian/changelog
- debian/control
> Release changelog for 2.39.1

- snapcraft/tests/unit/commands/test_clean.py
- snapcraft/tests/unit/plugins/python/test_pip.py
- snapcraft/tests/unit/project_loader/grammar/__init__.py
- snapcraft/tests/unit/project_loader/grammar/test_on_statement.py
- snapcraft/tests/unit/project_loader/grammar/test_processor.py
- snapcraft/tests/unit/project_loader/grammar/test_to_statement.py
- snapcraft/tests/unit/project_loader/grammar/test_try_statement.py
- snapcraft/tests/unit/project_loader/test_config.py
-----
Also clarify names of test base classes so this mistake won't happen again. Should shave a few minutes off unit test time.
> tests: remove duplicate tests

- demos/gradle-with-outputdir/snap/snapcraft.yaml
- demos/gradle/snap/snapcraft.yaml
- demos/java-hello-world/snap/snapcraft.yaml
- demos/qt4-text-editor/snap/snapcraft.yaml
- demos/qt5-text-editor/snap/snapcraft.yaml
- snaps_tests/demos_tests/test_gradle.py
- snaps_tests/demos_tests/test_gradle_with_outputdir.py
- snaps_tests/demos_tests/test_java_hello_world.py
Version fixes and reducing the delta for when testing on bionic, such as
using full paths for commands.
-----
> tests: improvements to demos

- snapcraft/_options.py
- snapcraft/internal/mangling.py
- snapcraft/internal/meta/_snap_packaging.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/project_loader/_parts_config.py
- snapcraft/tests/integration/plugins/test_rust_plugin.py
- snapcraft/tests/unit/test_mangling.py
- snapcraft/tests/unit/test_meta.py
- snapcraft/tests/unit/test_options.py
- snaps_tests/demos_tests/test_opencv.py
Includes support for building classic confined snaps on release like
bionic that target a 16 base and also adds support for using hooks built
with snapcraft.
-----
> elf: contemplate more patching scenarios

- debian/changelog
- snapcraft/tests/integration/plugins/test_plainbox_provider_plugin.py
- snaps_tests/demos_tests/test_opencv.py
> Release changelog for 2.39.2

- snapcraft/_store.py
- tests/unit/commands/test_push.py
> store: stringify message for StoreDeltaApplicationError

- schema/snapcraft.yaml
- snapcraft/extractors/_metadata.py
- snapcraft/extractors/appstream.py
- snapcraft/internal/meta/_snap_packaging.py
- tests/integration/general/test_metadata_appstream.py
- tests/unit/extractors/test_appstream.py
- tests/unit/pluginhandler/test_pluginhandler.py
- tests/unit/test_meta.py
-----
Closes #1954
Requires #1879
>  extractors: add support for common-id 

- tests/integration/__init__.py
- tests/integration/general/test_asset_recording.py
- tests/integration/general/test_no_system_libraries.py
- tests/integration/general/test_prime.py
- tests/integration/general/test_snap.py
- tests/integration/platform.py
- tests/integration/plugins/test_autotools_plugin.py
- tests/integration/plugins/test_go_plugin.py
- tests/integration/plugins/test_kbuild_plugin.py
- tests/integration/plugins/test_rust_plugin.py
- tests/integration/plugins/test_waf_plugin.py
- tests/integration/plugins_java/test_maven_plugin.py
> tests: remove ProjectOptions dependency from integration suite

- tests/integration/general/test_build_package_grammar.py
- tests/integration/general/test_build_snap_grammar.py
- tests/integration/general/test_build_snaps.py
- tests/integration/repo.py
> tests: remove dependency of internal repo from integration suite

- tests/os_release.py
- tests/skip.py
> tests: remove the internal os_release dependency

- snapcraft/internal/elf.py
- snapcraft/internal/mangling.py
- snapcraft/internal/pluginhandler/__init__.py
- tests/integration/general/test_elf.py
- tests/unit/test_elf.py
- tests/unit/test_mangling.py
> pluginhandler: simplify logic when elf patching is required

- schema/snapcraft.yaml
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/pluginhandler/_build_attributes.py
- tests/fixture_setup.py
- tests/integration/general/test_prime.py
> pluginhandler: add option to disable patchelf for a part

- snapcraft/internal/elf.py
-----
This one is pretty self-explanatory. Might get a small performance bump.
> elf: don't parse elf more than necessary

- TESTING.md
> tests: document arm testing setup

- snapcraft/_options.py
- snapcraft/internal/common.py
- snapcraft/internal/errors.py
- snapcraft/internal/lifecycle/_runner.py
- snapcraft/internal/pluginhandler/__init__.py
- snapcraft/internal/project_loader/_env.py
- snapcraft/internal/project_loader/_parts_config.py
- tests/fixture_setup.py
- tests/unit/__init__.py
- tests/unit/project_loader/test_config.py
- tests/unit/test_errors.py
- tests/unit/test_options.py
- tools/travis/run_lxd_container.sh
> core: initial support for bases

- TESTING.md
- tests/fixture_setup.py
- tests/unit/test_fixture_setup.py
-----
Farewell gift for @sergiusens .
> tests: add SNAPCRAFT_KEEP_DATA to debug

- debian/control
- snap/snapcraft.yaml
- snapcraft/internal/project_loader/_config.py
- tests/integration/general/test_asset_recording.py
Also use the same version in the snap and the deb.
-----
> many: use packaging logic to get patchelf

- snapcraft/_options.py
- snapcraft/internal/project_loader/_parts_config.py
- tests/unit/project_loader/test_config.py
> Base check for classic

- HACKING.md
> docs: add execstack to HACKING.md's list of deb deps

- snapcraft/internal/pluginhandler/__init__.py
-----
We should not be doing crazy things with things like https://code.launchpad.net/~mvo/+snap/core18
> pluginhandler: only resort to elf mangling if the snap type is app 

- debian/changelog
- debian/control
- debian/tests/integrationtests-snapd
- debian/tests/snapstests
- snaps_tests/demos_tests/test_java_hello_world.py
- tests/integration/general/test_elf.py
> Release changelog for 2.40

- README.md
> Polish our landing page ✨

- snapcraft/cli/_errors.py
- tests/unit/cli/test_errors.py
Polish the UI following up from the design review.
-----
> errors: improve the UX for sending error data

- debian/changelog
This release is mostly to get a rebuild of snapcraft using
snapcraft 2.40
-----
> Release changelog for 2.40.1

- snapcraft/plugins/dotnet.py
- tests/unit/plugins/test_dotnet.py
> Add support enable configurable runtime version for .NET Core applications

- snapcraft/extractors/_errors.py
- snapcraft/extractors/_metadata.py
- snapcraft/extractors/setuppy.py
- snapcraft/internal/lifecycle/_runner.py
- tests/fixture_setup.py
- tests/integration/general/test_metadata_setuppy.py
- tests/unit/extractors/test_setuppy.py
- tests/unit/test_lifecycle.py
>  lifecycle: handle missing version correctly 

- snapcraft/internal/meta/_snap_packaging.py
- tests/integration/general/test_snapcraftctl_set_grade.py
- tests/unit/test_meta.py
-----
Also fix common_id getting shoved into the YAML, which is disallowed by the schema.
> meta: validate extracted and scriptlet metadata

- .travis.yml
- patches/ctypes_init.diff
- tests/integration/general/test_elf.py
- tools/travis/run_lxd_container.sh
> patches: improve ctypes patch for python 3.5

- tests/unit/cli/test_errors.py
-----
```
(snapcraft) ubuntu@snapcraft-xenial-dev:~/source/snapcraft$ python3 -m unittest -v run tests.unit.cli.test_errors.ErrorsTestCase.test_handler_traceback_send_traceback_to_sentry
run (unittest.loader._FailedTest) ... ok
test_handler_traceback_send_traceback_to_sentry (tests.unit.cli.test_errors.ErrorsTestCase)
tests.unit.cli.test_errors.ErrorsTestCase.test_handler_traceback_send_traceback_to_sentry ... skipped 'raven needs to be installed for this test.'
----------------------------------------------------------------------
Ran 2 tests in 0.061s
OK (skipped=1)
(snapcraft) ubuntu@snapcraft-xenial-dev:~/source/snapcraft$ pip install raven
Collecting raven
Downloading raven-6.6.0-py2.py3-none-any.whl (282kB)
100% …
```
> errors: skip the sentry test if raven is no installed

- debian/changelog
> Release changelog for 2.41

- schema/snapcraft.yaml
- tests/unit/project_loader/test_config.py
- tests/unit/test_meta.py
Allow and validate `refresh-mode` and `stop-mode`.
-----
> schema: allow refresh-mode and stop-mode

- .travis.yml
- TESTING.md
- runtests.sh
- tests/integration/__init__.py
- tools/brew_install_from_source.py
- tools/travis/build_snapcraft_snap.sh
- tools/travis/run_tests.sh
> Osx travis

- snapcraft/cli/_errors.py
- snapcraft/config.py
- snapcraft/internal/errors.py
- tests/unit/cli/test_errors.py
- tests/unit/test_config.py
-----
Meant for a rebase and commit
> errors: implement an always option to send to sentry

- HACKING.md
> HACKING: suggest snapcraft-pr for evaluating PRs

- snapcraft/internal/repo/_deb.py
Revert "repo: use debian.arfile instead of dpkg-deb (#1878)"
This reverts commit fa287bec3376293e791e24ead3e666b11cddfef6.
LP: #1767119
-----
The first run is using `dpkg-deb`, the ssecond run using arfile (didn't even wait for it to finish, but the numbers speak for themselves).
```
(snapcraft) ubuntu@snapcraft-xenial-dev:~/source/vlc/extras/package/snap$ time snapcraft build
DEPRECATED: The 'prepare' keyword has been replaced by 'override-build'
See http://snapcraft.io/docs/deprecation-notices/dn7 for more information.
DEPRECATED: The 'build' keyword has been replaced by 'override-build'
See http://snapcraft.io/docs/deprecation-notices/dn8 for more information.
DEPRECATED: The 'install' keyword has been replaced by …
```
> repo: rollback to using dpkg-deb for deb extraction

- snapcraft/internal/repo/_base.py
- tests/integration/plugins_python/test_python_plugin.py
- tests/unit/repo/test_base.py
-----
Snapcraft's python plugin fixes python shebangs throughout the entire part. However, when using stage-packages, snapcraft only fixes python shebangs in bin directories. This makes combining them in one `snapcraft.yaml` difficult as they always conflict.
This PR fixes [LP: #1766662](https://bugs.launchpad.net/snapcraft/+bug/1766662) by making this behavior consistent, always fixing python shebangs throughout the entire part. It also removes the `sitecustomize.py` coming from the archive, since it's never useful and can cause clashes between parts.
> repo: fix all python shebangs in stage-packages

- snap/snapcraft.yaml
-----
apt moved to salsa.debian.org.
> snapcraft.yaml: update apt repo location

- snap/snapcraft.yaml
> No user site for snapcraft

- debian/changelog
- tests/integration/plugins/test_plainbox_provider_plugin.py
- tests/integration/snaps/plainbox-provider-with-deps/snapcraft.yaml
> Release changelog for 2.42.1

- snapcraft/internal/meta/_manifest.py
- tests/fixture_setup/os_release.py
- tests/unit/project_loader/test_config.py
- tests/unit/test_elf.py
- tests/unit/test_lifecycle.py
> Os release in manifest

- snapcraft/plugins/nodejs.py
> nodejs plugin: update to the latest 6.x LTS point release

- snapcraft/plugins/rust.py
- tests/unit/plugins/test_rust.py
> rust plugin: fix cargo builds and run tests

- snapcraft/cli/_errors.py
> errors: support keyboard interrupts

- snapcraft/cli/lifecycle.py
> provider changes

- snapcraft/internal/lxd/_cleanbuilder.py
- snapcraft/internal/lxd/_containerbuild.py
- snapcraft/internal/lxd/_project.py
- tests/unit/lxd/test_lxd.py
> lxd: wait for cloud-init

- .travis.yml
- snap/snapcraft.yaml
> snap: use set-version and set-grade

- snapcraft/internal/lxd/_containerbuild.py
- snapcraft/project/_project_info.py
- tests/unit/lxd/test_lxd.py
> lxd: proper filename set when using architectures

- snapcraft/internal/errors.py
- snapcraft/internal/pluginhandler/_patchelf.py
- tests/unit/test_errors.py
> Better error

- debian/changelog
- debian/tests/snapstests
> Release changelog for 2.43.1
